### ISSUE TITLE
Notify app the rendering is done after loading resources

### ISSUE THREAD

**Issue by jianhuang01** [visgl/deck.gl#1291]
Icon layer need load texture atlas while rendering, before texture loading is done, the actual rendering is not triggered but app has no way to know that, which makes rendering test is hard to implement.

**Comment by ibgreen** [comment]
#1372 will make it much easier to track resource loading (since it deck.gl will manage the loading instead of the app), and I think we could fairly easily add a callback to indicate when all pending loads for a layer (or all layers) complete.

**Comment by Pessimistress** [comment]
#4091
