### ISSUE TITLE
arclayer/linelayer min/max pixels?

### ISSUE THREAD

**Issue by contra** [visgl/deck.gl#1396]
GeoJSONLayer and ScatterplotLayer support defining the scale + min/max pixels. This is a great API for figuring out the width - but it doesn't seem like this works universally. ArcLayer and LineLayer (for example, there are more) only support strokeWidth, which doesn't really seem to work either.

Proposal is to normalize the API so you can define scale/min/max across all layers for any drawable portion of the layer. It would be nice if some of the extra geojson layer properties were supported as well, like lineJointRounded for Arc/Line layers. Really just want to see some of the great new stuff done for the geojson layer be applied across all layers.

**Comment by contra** [comment]
Is this something you're interested in? I can send a PR for this when I have a minute next week.

**Comment by jianhuang01** [comment]
We are interested in your proposal, any contribution is welcome.

**Comment by Pessimistress** [comment]
Shipped in 7.0.
