### ISSUE TITLE
Suggestion: `all` updateTrigger should result in `dataChanged` being set

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#1400]
See #1398 and https://github.com/uber/deck.gl/commit/cb6a7fe429c0c7790e5bb141c35a6b2c61d6c47b

**Comment by ibgreen** [comment]
@georgios-uber

**Comment by Pessimistress** [comment]
Closing this - some layers e.g. GeoJsonLayer pre-processes data on `dataChanged` flag. It should not be triggered by `updateTriggersChanged.all`.
