### ISSUE TITLE
Question: What are sain defaults for lightSettings?

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#1533]
At the moment, the lighting module seems very scene specific and takes a good bit of understanding light design in order to use. 

To speed up prototyping, I've been thinking about how to abstract away [lightSettings](https://github.com/uber/deck.gl/blob/2fd0f96eb19d97c99f9af7a8cea3dbd363389b4e/docs/shader-modules/lighting.md) prop for the solid polygon layers (or any layer that might use it). In other words, I've been wondering what a "sain default" value for this prop might look like.

My current idea isn't super straightforward, and I was wondering if anyone has a better idea than this:
- calculate bbox of data
- create 4 lights, positioned higher than and outside of any data vertex, pointed at each corner of the bbox
- hard code other light settings to something that will generally work. Perhaps a wide cone, that is medium strength? 
  - If I knew a way to pick these values based on distance between lights, or size of object, etc.. I would do that instead

Is there a more general way of setting up my lights? 

If not, any recommendations on how to learn light design?

**Comment by ibgreen** [comment]
Our light system is rather rudimentary. For natural outdoors look, you probably want a directional light (rather than point lights) representing the sun and some ambient light.

**Comment by chrisgervang** [comment]
What are the settings for that kind of light?

**Comment by jianhuang01** [comment]
Our current lighting system is pretty premature, which only supports point lighting, so requires setting light positions. Ideally we need support directional lighting as default which could rotate along with user's eye position, don't need a light position at all.
