### ISSUE TITLE
[For discussion] Picking performance improvements using multiple PBOs.

### ISSUE THREAD

**Issue by 1chandu** [visgl/deck.gl#1552]
#### Background 
When `picking` is enabled, deck.gl reads picking FBO into CPU memory after each frame,  hence GPU and CPU run in lock step. Using multiple PBOs, performance in these cases can be improved. When picking location changing too fast with few frames old picking information. OldThis shouldn't cause any visible difference as framers are rendered at close to 60 FPS.

Initial experiments show performance improvements in layer-browser with multiple layers rendered, working on PR.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
> When `picking` is enabled, deck.gl reads picking FBO into CPU memory after each frame,  hence GPU and CPU run in lock step.

It should only read the buffer when actually "picking", e.g. the mouse moves or app queries. It should not read picking buffer automatically after every frame.

**Comment by ibgreen** [comment]
Worth checking that this is the case... deck.log.priority = 1 or 2 should turn on some helpful render logs.

**Comment by 1chandu** [comment]
> It should only read the buffer when actually "picking", e.g. the mouse moves or app queries. It should not read picking buffer automatically after every frame.

Yep, you are right, only when picking is requested. Which could happen when the mouse pointer is moving.

**Comment by Pessimistress** [comment]
I believe this is no longer valid after we start throttling pointermove events.
