### ISSUE TITLE
New Layer: IconTrips Layer

### ISSUE THREAD

**Issue by edibusl** [visgl/deck.gl#1618]
Hi, is there any plan to create a layer for moving icons?
It can be sort of a combination of IconLayer and TripsLayer in order to show icons of moving vehicles.
Currently the only option to show large amounts of moving vehicles on mapbox is [this](https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/) example, but it consumes a lot of CPU for a data set which is not that large.

**Comment by jianhuang01** [comment]
Hi, we didn't have plan for that yet, any contribution from the community is more than welcome.

**Comment by rtran9** [comment]
@edibusl I have a [demo](
https://github.com/rtran9/cube-arc-layer) here that animates a cube along the same arc path as `ArcLayer`.

**Comment by zfalen** [comment]
+1 for this feature, or some kind of `onTimeChange()` callback that gives us the position of the "car" / vehicle / shiny dot so you can theoretically use it to render an IconLayer

**Comment by Pessimistress** [comment]
#4199
