### ISSUE TITLE
Weird polygon behaviour

### ISSUE THREAD

**Issue by CraigglesO** [visgl/deck.gl#1630]
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

Not sure if this is a bug or I am just missing one key component. When I try to render flat polygons that "repeat" over themselves I am having issues..
Here is what it looks like:

![alt-1](https://cdn.pbrd.co/images/Hf2b6yQ.png)
![alt-2](https://cdn.pbrd.co/images/Hf2bv7z.png)

here is what it looks like using d3 and svg (which works until the polygons get too large):
![alt-3](https://cdn.pbrd.co/images/Hf2bSfM.png)

Here is my code:

```
import React, {Component} from 'react';
import DeckGL, {PolygonLayer, GeoJsonLayer, PathLayer} from 'deck.gl';

const LIGHT_SETTINGS = {
  lightsPosition: [-125, 50.5, 5000, -122.8, 48.5, 8000],
  ambientRatio: 0.2,
  diffuseRatio: 0.5,
  specularRatio: 0.3,
  lightsStrength: [1.0, 0.0, 2.0, 0.0],
  numberOfLights: 2
};

// -111.8751984, 40.7351688
export default class DeckGLOverlay extends Component {
  static get defaultViewport() {
    return {
      latitude: 40.7351688,
      longitude: -111.8751984,
      zoom: 11,
      maxZoom: 16,
      pitch: 0,
      bearing: 0
    };
  }

  render() {
    const {viewport, data, colorScale} = this.props;

    if (!data) {
      return null;
    }

    const layer = new GeoJsonLayer({
      id: 'geojson',
      data: data,
      opacity: 1,
      stroked: true,
      filled: true,
      extruded: false,
      wireframe: false,
      lineWidthScale: 1,
      lineWidthMinPixels: 30,
      lineWidthMaxPixels: 30,
      lineJointRounded: true,
      // lineMiterLimit: 4,
      fp64: false,
      // getElevation: f => f.properties.color * 100 + 100,
      getFillColor: f => colorScale(f.properties.color),
      // getStrokeColor: f => colorScale(f.properties.color),
      getLineColor: f => colorScale(f.properties.color),
      // lightSettings: LIGHT_SETTINGS,
      // pickable: Boolean(this.props.onHover),
      // onHover: this.props.onHover
    });

    return <DeckGL {...viewport} layers={[layer]} />;
  }
}

```

here is some info from logs:
![alt-4](https://cdn.pbrd.co/images/Hf2cEy2.png)
![alt-5](https://cdn.pbrd.co/images/Hf2d0e5.png)
![alt-6](https://cdn.pbrd.co/images/Hf2d9ck.png)
![alt-7](https://cdn.pbrd.co/images/Hf2dkcH.png)

Any suggestions? Webgl things I am missing?

Thanks,
Craig.

**Comment by jianhuang01** [comment]
@CraigglesO can you provide your data and code package? hard to understand the details from code.

**Comment by CraigglesO** [comment]
@jianhuang01 - thanks for getting back to me!

https://github.com/CraigglesO/isochrone-webgl-example

The polygons overlap with themselves, that is important as I want to highlight the road network and not abstract polygons..

Here is what the polygons look like without flair (using geojson.io):
![alt1](https://cdn.pbrd.co/images/Hj93Jx0.png)

I appreciate your time with this!

Craig.

**Comment by ibgreen** [comment]
I wonder if you are having issues with z-fighting due to depth testing. If you are just rendering flat geometry you could try to turn off depth testing:

```
  <DeckGL onWebGLInitialized={this._oWebGLInitialized.bind(this)}>

  _onWebGLInitialize(gl) {
    setParameters(gl, {
      depthTest: false
    });
  }
```

**Comment by CraigglesO** [comment]
Ah, that's really interesting. That did indeed fix the issue with viewing at an angle it freaking out, but the strange shapes and pointedness instead of rounded edges are still there:
![alt-1](https://cdn.pbrd.co/images/Hjfyi5c.png)

**Comment by Pessimistress** [comment]
This seems to be fixed in the latest release. Reopen if still experiencing issues
