### ISSUE TITLE
render test failed: rendering arc-lnglat failed 

### ISSUE THREAD

**Issue by ianshan0915** [visgl/deck.gl#1877]
#### Actual Result
rendering arc-lnglat failed, percentage (95.187% ) less than the threshold.
#### Expected Result
render passed with percentage over than the threshold
#### Reproduce Steps
yarn test
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
@ianshan0915 Thanks for reporting. What machine are you using? We are getting consistent results on recent macbooks, but maybe other systems have some differences?

**Comment by ianshan0915** [comment]
@ibgreen I tested it on 13-inch Macbook pro 2017.
