### ISSUE TITLE
Several Render tests are failing on Intel GPUs

### ISSUE THREAD

**Issue by 1chandu** [visgl/deck.gl#1902]
Following tests are failing on `Intel Iris Pro`

- path-lnglat
- path-lnglat-64
- arc-lnglat
- arc-lnglat-64
- line-lnglat
- geojson-lnglat
- geojson-extruded-lnglat
- gridcell-lnglat
- grid-lnglat
- hexagoncell-lnglat
- pointcloud-lnglat
- pointcloud-lnglat-64
#### Actual Result
Above tests are failing, some randomly.
#### Expected Result
Above tests should pass
#### Reproduce Steps
Run these tests on using Intel GPU, or do `git push`
#### To Do List 
  - [X] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
Move to 6.1

**Comment by 1chandu** [comment]
Over to Jian, this seems to be more about image comparison than actual rendering, given failures are widespread across many layers.

**Comment by jianhuang01** [comment]
There is no way to make rendering test work on different the computer setup, one long term solution will be a Bot running on a computer which monitors our repo. Move to backlog for now.
