### ISSUE TITLE
add LayerGroup

### ISSUE THREAD

**Issue by treasureMoment** [visgl/deck.gl#1954]
Can it be added LayerGroup，Convenience to layer group operation

**Comment by ibgreen** [comment]
@treasureMoment Yes, this sounds like a good idea. Can you provide a bit more detail about what you would like to see?

**Comment by treasureMoment** [comment]
the objects has the same attributes,only to operation layer group 
like [leaflet](https://leafletjs.com/reference-1.3.0.html#layergroup)

**Comment by tgorkin** [comment]
A more advanced layer grouping concept is being considered as part of #2085
