### ISSUE TITLE
Issue with blending of layers

### ISSUE THREAD

**Issue by chrisui** [visgl/deck.gl#2039]
#### Actual Result

Lower indexed layers are visible through supposed opaque layers. The blue `PathLayer` should be fully opaque however the separate [dashed] `PathLayer` underneath is visible through it. The same happens with a supposed opaque white `PolygonLayer` on top of a `PathLayer`.

I've not touched any gl parameters. I am only using the high level api provided by deck.gl with core layers.

![screenshot 2018-07-12 17 29 39](https://user-images.githubusercontent.com/1042432/42646886-1a4cf11a-85fa-11e8-9f05-905747fdf62a.png)

![screenshot 2018-07-12 17 35 30](https://user-images.githubusercontent.com/1042432/42646891-1c3d0a32-85fa-11e8-9f2f-80e0c31c1882.png)

#### Expected Result

Lower indexed layers under a layer with no transparency should not be visible.

#### Reproduce Steps

Have several layers with no transparency (ie. `getColor => [0, 0, 0]`) and render them over the top of each other.

#### Code Example 

Can/will be followed up if the answer isn't a simple one!

```js
              <PolygonLayer
                id="road"
                fp64={true}
                coordinateSystem={COORDINATE_SYSTEM.METER_OFFSETS}
                coordinateOrigin={[0, 51]}
                data={roadData.lanes}
                getPolygon={lane => lane.contour}
                stroked={true}
                lineWidthScale={0.2}
                getLineColor={lane => [20, 20, 20]}
                getFillColor={lane => [0, 0, 0]}
              />
              <PathLayer
                id="midlines"
                fp64={true}
                coordinateSystem={COORDINATE_SYSTEM.METER_OFFSETS}
                coordinateOrigin={[0, 51]}
                data={roadData.lanes}
                getPath={lane => lane.midline}
                getColor={lane => [246, 127, 1]}
                widthScale={0.1}
                rounded={true}
                dashJustified={true}
                getDashArray={lane => [20, 10]}
              />
              <PolygonLayer
                id="agents"
                fp64={true}
                coordinateSystem={COORDINATE_SYSTEM.METER_OFFSETS}
                coordinateOrigin={[0, 51]}
                data={framesData[frameIndex]}
                getPolygon={agent => agent.bounds}
                stroked={false}
                getFillColor={lane => [255, 255, 255]}
                extruded={true}
                getElevation={lane => 2}
              />
              <PathLayer
                id="belief-follow-paths"
                fp64={true}
                coordinateSystem={COORDINATE_SYSTEM.METER_OFFSETS}
                coordinateOrigin={[0, 51]}
                data={framesData[frameIndex].filter(
                  agent => agent.belief_trajectories[0].length > 0
                )}
                getPath={agent => agent.belief_trajectories[0]}
                getWidth={agent => agent.beliefs[0]}
                widthScale={3}
                getColor={agent => [0, 121, 165]}
              />
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
@chrisui For some legacy reasons the default `opacity` is `0.8` - and apparently not properly documented /o\. If you explicitly set `opacity` to `1` they should be opaque.

- [ ] Update layer doc
- [ ] Should we change the default to `1` in v6?

@jianhuang01 @ibgreen

**Comment by chrisui** [comment]
That solves it, thank you! Have to be honest I somehow totally missed the `opacity` property altogether - had been assuming alpha was always managed with the rgba system.

**Comment by DominusVilicus** [comment]
Maybe we need an RFC for this. I can update the docs in the meanwhile

I'd support adding a breaking change for this and making the default opacity `1`, and perhaps adding a feature to add opacity via the `getColor` option with an RGBA array (`[0,0,0,0.5]` or (`[0,0,0,255]`)

**Comment by Pessimistress** [comment]
@DominusVilicus all colors in deck.gl already support both RGB and RGBA formats.

**Comment by DominusVilicus** [comment]
@Pessimistress 

```js
new ScatterplotLayer({
                    data: [{
                        position: [-122.45, 37.8],
                        color: [20, 100, 150, 255],
                        radius: 15
                    }],
                    getColor: d => d.color,
                    getRadius: d => d.radius
                })
```

still creates a object with transparency. Why is that?

**Comment by Pessimistress** [comment]
The default `opacity` value in 7.x was `0.8`. In v8 it was changed to `1`.
