### ISSUE TITLE
Ability to stroke ScatterplotLayer points and PathLayer lines

### ISSUE THREAD

**Issue by supersonicclay** [visgl/deck.gl#2138]
#### Background
We'd like to have the ability to stroke `ScatterplotLayer` points and `PathLayer` lines.

We'd like this kind of effect
![2018-07-30 15 50 02](https://user-images.githubusercontent.com/469582/43477971-d4fc776a-94b9-11e8-93be-bebb8706c0fd.gif)

A workaround is to render two layers with different colors and sizes, but that would likely be less performant than implementing it natively in deck.gl. Another workaround for points is to use icons, however icons are sized in pixels whereas points are sized based on map projection.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
@supersonicclay Something like https://github.com/uber/deck.gl/pull/2112?

**Comment by ibgreen** [comment]
> That looks like what we'd need for points. I wonder what it would take to do the same for PathLayer

Let's figure out the right approach here

> A workaround is to render two layers with different colors and sizes, but that would likely be less performant than implementing it natively in deck.gl. 

True. It is a tradeoff, we can add more features to each layer, making them slightly less performant for the general use case, and more performant for a specific use case. 

There are ways to make conditional features not cost anything when not using them, but that also takes work, and rigorous performance testing also does.

> Ooo, yes. That looks like what we'd need for points. I wonder what it would take to do the same for PathLayer.

Why just for the PathLayer? Why not for all layers? 

The point being, deck.gl is an "audited" API where we consider the set of props and feature we offer for each layer in conjunction with other layers. If you have props with certain names or functions on one layer, the user would reasonably expect them to be present and/or work similarly on other layers as well.

That is one reason why we have the experimental layers folder where we can groom new layers without having to worry about the API audit constraints.

> A workaround is to render two layers with different colors and sizes, 

Just as an idea: there is a middle ground, it might be possible to have each layer do two draw calls with slightly different "internal scale" (taking a GPU hit but not a CPU / memory hit). It might be possible to do this in way that is easy to apply to all layers.

> whereas icons are sized based on map projection

Adding support for meter sizes and world (in addition to screen) orientation for icons could also be considered.

**Comment by ibgreen** [comment]
@supersonicclay A good first approach could be for you to take the external PR on the ScatterplotLayer and help us get that landed in experimental-layers.
