### ISSUE TITLE
What Would Happen If I Assign Dynamic ID to TripsLayer?

### ISSUE THREAD

**Issue by zicodeng** [visgl/deck.gl#2368]
Hi, I am just curious on what would happen if I assign dynamic ID to TripsLayer?

Consider the following code:

```
new TripsLayer({
        id: myID,
        data: trips,
        getPath: d => d.segments,
        getColor: d => (d.vendor === 0 ? [253, 128, 93] : [23, 184, 190]),
        opacity: 0.3,
        strokeWidth: 2,
        trailLength,
        currentTime: this.state.time
      }),
```

Let's say `myID = 1` first, then changes to `myID = 2`. Does this mean two identical TripsLayers will be rendered on the map? Or TripsLayer with `myID = 1` will be destroyed first?

Thanks in advance!

**Comment by 1chandu** [comment]
@zicodeng , if `id` is changed every time, it will trigger new layer initialization every time. By keeping hte `id` same, internal state gets re-used. More details on how to use layer `id` here : http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=constructor
If you need to explore more you can check this code : https://github.com/uber/deck.gl/blob/cc2571cf2d9ab6a4f16ed2b352cfbe33e852b74f/modules/core/src/lib/layer-manager.js#L397

**Comment by zicodeng** [comment]
@1chandu Thanks for your response. I actually want to initialize a new TripsLayer because I want to dynamically change animation color. I noticed that the animation color is not changed immediately based on props unless I initialize a new TripsLayer with different ID. I am just concerning with the performance.

**Comment by Pessimistress** [comment]
@zicodeng The intended way to recalculate color is to use `updateTriggers`: http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=data-properties
