### ISSUE TITLE
Node.js versions for CI

### ISSUE THREAD

**Issue by DanielRuf** [visgl/deck.gl#2430]
Short question, is there a reason for this version instead of using `10`?

https://github.com/uber/deck.gl/blob/master/.travis.yml#L25

**Comment by jianhuang01** [comment]
When we were adding the node.js 10 in June, 10.4.0 was the most latest release, so we just add it at that time.

**Comment by DanielRuf** [comment]
Well but `10` is always the latest 10.x. So I think we can set it to `10`.
