### ISSUE TITLE
mapbox with deck HexagonLayer onHover event not right

### ISSUE THREAD

**Issue by dfy167** [visgl/deck.gl#2439]
deck 6.2.0 mapblxgl v0.50.0
example:https://bl.ocks.org/Pessimistress/raw/1a4f3f5eb3b882ab4dd29f8ac122a7be/
code:https://jsbin.com/corilak/edit?html,console,output
when onHover on HexagonLayer I get the wrong value , i should be a fix value when move over a Hexagon.but it changed sometimes.

![t](https://user-images.githubusercontent.com/9856271/48594986-e798a000-e98d-11e8-8d17-78c17d87fa89.png)

**Comment by Pessimistress** [comment]
Mapbox's custom layer feature has known z-fighting issues. Do you see the same behavior using [this example](https://github.com/uber/deck.gl/tree/6.3-release/examples/website/3d-heatmap)?
