### ISSUE TITLE
Can deck.gl combined to Arcgis for javascript?

### ISSUE THREAD

**Issue by camillalo** [visgl/deck.gl#2498]
#### Actual Result
I have watched the demo in your website, it's really the best solution for my project's visual requirements. But i can't find any demo which deck.gl is coded in ArcGIS. 
#### Expected Result
Use in arcgis.

**Comment by 1chandu** [comment]
CC: @ibgreen @Pessimistress

**Comment by ibgreen** [comment]
> I have watched the demo in your website, it's really the best solution for my project's visual requirements. 

We are not familiar with ArcGIS, so it is not clear what you would like to achieve. Would you like to use an ArcGIS base map with deck.gl overlays?

Depending on your coding skills, we may be able to give you some advice.

> But i can't find any demo which deck.gl is coded in ArcGIS.

Any links to ArcGIS API etc that you are using? 

Can you share a small demo app that uses ArcGIS in JavaScript, that doesn't need any commercial licenses?

**Comment by camillalo** [comment]
There is a simple demo.
1st，I create the webGL context，
2ed，there is a conception(layer), and i create a GraphicLayer, then i add a line to this layer.

I want:
use deck.gl to draw somethind in arcgis's context.

I can't find any useful demo which is finished in these two webgl libraries.

so, i need some help! 
thank you

`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>Intro to graphics - 4.9</title>

    <link rel="stylesheet" href="https://js.arcgis.com/4.9/esri/css/main.css">
    <script src="https://js.arcgis.com/4.9/"></script>

    <style>
        html,
        body,
        #viewDiv {
            padding: 0;
            margin: 0;
            height: 100%;
            width: 100%;
        }
    </style>

    <script>
        require([
            "esri/Map",
            "esri/views/SceneView",
            "esri/Graphic"
        ], function (
            Map, SceneView, Graphic
        ) {

                var map = new Map({
                    basemap: "hybrid"
                });

                var view = new SceneView({
                    center: [-80, 35],
                    container: "viewDiv",
                    map: map,
                    zoom: 3
                });

                /****************************
                 * Create a polyline graphic
                 ****************************/

                // First create a line geometry (this is the Keystone pipeline)
                var polyline = {
                    type: "polyline", // autocasts as new Polyline()
                    paths: [
                        [-111.30, 52.68],
                        [-98, 49.5],
                        [-93.94, 29.89]
                    ]
                };

                // Create a symbol for drawing the line
                var lineSymbol = {
                    type: "simple-line", // autocasts as SimpleLineSymbol()
                    color: [226, 119, 40],
                    width: 4
                };

                // Create an object for storing attributes related to the line
                var lineAtt = {
                    Name: "Keystone Pipeline",
                    Owner: "TransCanada",
                    Length: "3,456 km"
                };

                /*******************************************
                 * Create a new graphic and add the geometry,
                 * symbol, and attributes to it. You may also
                 * add a simple PopupTemplate to the graphic.
                 * This allows users to view the graphic's
                 * attributes when it is clicked.
                 ******************************************/
                var polylineGraphic = new Graphic({
                    geometry: polyline,
                    symbol: lineSymbol,
                    attributes: lineAtt,
                    popupTemplate: { // autocasts as new PopupTemplate()
                        title: "{Name}",
                        content: [{
                            type: "fields",
                            fieldInfos: [{
                                fieldName: "Name"
                            }, {
                                fieldName: "Owner"
                            }, {
                                fieldName: "Length"
                            }]
                        }]
                    }
                });

                // Add the graphics to the view's graphics layer
                view.graphics.addMany([polylineGraphic]);
            });
    </script>
</head>

<body>
    <div id="viewDiv"></div>
</body>

</html>`

**Comment by ibgreen** [comment]
Thanks for the example will take a look. Before that, I wanted to comment on this question:

> I want: use deck.gl to draw somethind in arcgis's context.

The normal way of using deck.gl on top of a base component is to just put it on top. The deck.gl background is transparent so the graphics will overlay nicely.

It has recently become possible to make deck.gl draw into another context but it is more complicated and better done as a second step.

So just try to include deck.gl (you want the scripting version) and create a deck component and feed it the same `lng/lat/zoom` as you feed to arcgis.

**Comment by camillalo** [comment]
Thanks

**Comment by Pessimistress** [comment]
Supported as of v8.1

https://deck.gl/docs/api-reference/arcgis/overview
