### ISSUE TITLE
Suggestion on setup a more efficient discussion way, Gitter or Google Groups, etc.

### ISSUE THREAD

**Issue by hijiangtao** [visgl/deck.gl#2568]
As mentioned in GitHub issue guidances, we may want the issue area to focus on bug report and new feature discussions, problems on how to develop with deck.gl and how to solve errors in programs should be put into another place called discussion area, such as chatroom or discussion group. 

On the other hand, deck.gl owns too many watchers, and issues like 「how to draw a circle or path」 rather than 「features or bugs report for deck.gl」 would disturb many watchers (I also did such things before, really sorry about that). 

I looked through README and documents, and didn't find such approach in deck.gl community. However, many popular libraries had already landed their discussion in gitter.im or Google groups.

I highly suggest deck.gl team setup a group at gitter, or something places like that.

![image](https://user-images.githubusercontent.com/4990015/51027930-19fcfd00-15cd-11e9-81c9-3a1ca25f3f99.png)

**Comment by Pessimistress** [comment]
We currently have a Slack workspace (see https://github.com/visgl/deck.gl#learning-resources) and a [mailing lis](https://lists.uc.foundation/g/visgl).
