### ISSUE TITLE
Add flow definitions file

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#2647]
> Please keep discussions focused on adding a flow definitions file.

#### Target Use case

Help flow-enabled app that use deck.gl catch errors in use of deck.gl API. 

See #2645

#### Proposed feature

Provide a flow interface file for deck.gl

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by IgorWilbert** [comment]
Hey @ibgreen ! May I work on this issue please?

**Comment by Pessimistress** [comment]
@IgorWilbert Feel free. My main concern about this is how to make sure the type definitions are in sync with API changes, given that this code base is not using flow.

**Comment by IgorWilbert** [comment]
@Pessimistress thanks. Could you please give me your email or any instant message ID? I would like to talk to you about this issue, but I don't want to pollute it with unnecessary comments again. My email address is igor.wilbert@gmail.com. Thanks.

**Comment by Pessimistress** [comment]
Closing because this effort has been abandoned for a while.

The team has decided to gradually introduce typescript definitions and transpile them to flow types. Currently targeting the v9 release.
