### ISSUE TITLE
Storing Layer Configuration in Redux

### ISSUE THREAD

**Issue by ctaylor4874** [visgl/deck.gl#2652]
Hello,

What is the preferred method of storing layer configuration in Redux?  Is there an API or method that can convert Mapbox style spec (JSON) to layer props?  For example, converting

```json
{
    "circle-color": [
        "rgb",
        ["get", "temperature"],
        0,
        ["-", 100, ["get", "temperature"]]
    ]
}
```
to 
```json
getFillColor: () =>  ...
```

Any help is appreciated!

**Comment by Pessimistress** [comment]
@ibgreen has been working on an experimental module [@deck.gl/json](http://deck.gl/#/documentation/json-api-reference-experimental/json-layer-experimental). I believe it's the plan to support dynamic accessors, but the feature is not implemented yet. You can see a demo here: http://deck.gl/json/

**Comment by Pessimistress** [comment]
https://deck.gl/playground/
