### ISSUE TITLE
IconLayer Example: "Delayed" onClick event (Laggy)

### ISSUE THREAD

**Issue by Lowhearth** [visgl/deck.gl#2683]
Hello,

I'm trying to implement some IconLayers on React taking as reference the following example : https://github.com/uber/deck.gl/tree/6.4-release/examples/website/icon

Just starting a fresh copy of the repo, when I try to click on any Icon, the onClick event feedback is delayed for 1 second or so. This behaviour is not shown in the deck.gl demo : https://deck.gl/#/examples/core-layers/icon-layer

It is that the example on the web is not the same code as the one uploaded to github ? If so, how can I achieve such responsiveness on click ?

Thanks

**Comment by hijiangtao** [comment]
The codes are exactly different between these two examples, but the *delayed situation* is not problem of codes themselves exactly.

The event https://deck.gl/#/examples/core-layers/icon-layer uses is `onHover` rather than `onClick`, I think you can put your response in this method https://github.com/uber/deck.gl/blob/6.4-release/examples/website/icon/app.js#L138 and you may get the things you want.

**Comment by Lowhearth** [comment]
I agree that the example is using the onHover event for displaying the Black floating window but
Im refering to the event that gets fired just after clicking on the icon (The floating window becoming white and additional info beeing displayed)

**Comment by hijiangtao** [comment]
I never meet `onClick` delay problem, maybe you need to put your code here, so that we can locate where is the problem more specifically.

**Comment by Pessimistress** [comment]
@Lowhearth The example on the website uses the code from the examples/ directory with some additional UI and styling, but the deck.gl part is the same. What OS & browser are you using?

**Comment by Lowhearth** [comment]
I can post the code, as I said im just starting a fresh copy of the deckgl/examples/icon : 

`import React, {Component} from 'react';
import {render} from 'react-dom';
import {StaticMap} from 'react-map-gl';
import DeckGL, {IconLayer} from 'deck.gl';

import IconClusterLayer from './icon-cluster-layer';

// Set your mapbox token here
const MAPBOX_TOKEN = process.env.MapboxAccessToken; // eslint-disable-line

// Source data CSV
const DATA_URL =
  'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/icon/meteorites.json'; // eslint-disable-line

export const INITIAL_VIEW_STATE = {
  longitude: -35,
  latitude: 36.7,
  zoom: 1.8,
  maxZoom: 20,
  pitch: 0,
  bearing: 0
};

const stopPropagation = evt => evt.stopPropagation();

/* eslint-disable react/no-deprecated */
export class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      x: 0,
      y: 0,
      hoveredItems: null,
      expanded: false
    };
    this._onHover = this._onHover.bind(this);
    this._onClick = this._onClick.bind(this);
    this._closePopup = this._closePopup.bind(this);
    this._renderhoveredItems = this._renderhoveredItems.bind(this);
  }

  _onHover(info) {
    if (this.state.expanded) {
      return;
    }

    const {x, y, object} = info;
    const z = info.layer.state.z;
    const {showCluster = true} = this.props;

    let hoveredItems = null;

    if (object) {
      if (showCluster) {
        hoveredItems = object.zoomLevels[z].points.sort((m1, m2) => m1.year - m2.year);
      } else {
        hoveredItems = [object];
      }
    }

    this.setState({x, y, hoveredItems, expanded: false});
  }

  _onClick() {
    this.setState({expanded: true});
  }

  _onPopupLoad(ref) {
    if (ref) {
      // React events are triggered after native events
      ref.addEventListener('wheel', stopPropagation);
    }
  }

  _closePopup() {
    this.setState({expanded: false, hoveredItems: null});
  }

  _renderhoveredItems() {
    const {x, y, hoveredItems, expanded} = this.state;

    if (!hoveredItems) {
      return null;
    }

    if (expanded) {
      return (
        <div
          className="tooltip interactive"
          ref={this._onPopupLoad}
          style={{left: x, top: y}}
          onMouseLeave={this._closePopup}
        >
          {hoveredItems.map(({name, year, mass, class: meteorClass}) => {
            return (
              <div key={name}>
                <h5>{name}</h5>
                <div>Year: {year || 'unknown'}</div>
                <div>Class: {meteorClass}</div>
                <div>Mass: {mass}g</div>
              </div>
            );
          })}
        </div>
      );
    }

    return (
      <div className="tooltip" style={{left: x, top: y}}>
        {hoveredItems.slice(0, 20).map(({name, year}) => (
          <div key={name}>
            <h5>
              {name} {year ? `(${year})` : ''}
            </h5>
          </div>
        ))}
      </div>
    );
  }

  _renderLayers() {
    const {
      data = DATA_URL,
      iconMapping = 'data/location-icon-mapping.json',
      iconAtlas = 'data/location-icon-atlas.png',
      showCluster = true,
      viewState
    } = this.props;

    const layerProps = {
      data,
      pickable: true,
      wrapLongitude: true,
      getPosition: d => d.coordinates,
      iconAtlas,
      iconMapping,
      onHover: this._onHover,
      onClick: this._onClick,
      sizeScale: 60
    };

    const size = viewState ? Math.min(Math.pow(1.5, viewState.zoom - 10), 1) : 0.1;

    const layer = showCluster
      ? new IconClusterLayer({...layerProps, id: 'icon-cluster'})
      : new IconLayer({
          ...layerProps,
          id: 'icon',
          getIcon: d => 'marker',
          getSize: size
        });

    return [layer];
  }

  render() {
    const {viewState, controller = true, baseMap = true} = this.props;

    return (
      <DeckGL
        layers={this._renderLayers()}
        initialViewState={INITIAL_VIEW_STATE}
        viewState={viewState}
        controller={controller}
      >
        {baseMap && (
          <StaticMap
            reuseMaps
            mapStyle="mapbox://styles/mapbox/dark-v9"
            preventStyleDiffing={true}
            mapboxApiAccessToken={MAPBOX_TOKEN}
          />
        )}

        {this._renderhoveredItems}
      </DeckGL>
    );
  }
}

export function renderToDOM(container) {
  render(<App />, container);
}
`
I've noticed that the on Click delay disapears if I disable the controller throught the DeckGl prop.


Im thinking about just writing my custom controller, I just find it weird that the example code gives me such a different experience from the one published on the web.

Thanks

**Comment by ayeganov** [comment]
@Lowhearth Did you ever figure out why the controller causes the delay issue? I am experiencing the same problem with a GeoJson layer.

**Comment by Lowhearth** [comment]
@ayeganov No, I've ended up implementing the event firing myself.

**Comment by pr1ntr** [comment]
I find this issue to especially true on samsung devices.

**Comment by pr1ntr** [comment]
@Lowhearth can you paste an example of how you worked around this?

**Comment by Lowhearth** [comment]
@pr1ntr 

You can grab the deckGL object like that :
```

    <DeckGL
           ref={deck => {
            this.deckGL = deck;
            }}
           ... />
```


and then implement your own handler for the onClick Event asking the deckGL object if there is an item  in such coordinates : 

```
  onClick = event => {
    
    let pickInfo = this.deckGL.pickObject({
      x: event.nativeEvent.offsetX,
      y: event.nativeEvent.offsetY
    })
    if(pickInfo !== undefined){
     ....
    }
  }
```
That's the basic idea

**Comment by pr1ntr** [comment]
@Lowhearth, O man, yeah I had that idea seemed rather onerous. I think my issue was different. Only happens on Samsung S8/9 devices where onClick doesn't pick up unless you have 100% precision and can tap quickly.

My workaround (oddly) was to use the onHover handler which works a lot more responsively.

**Comment by Pessimistress** [comment]
Consolidating with #5089
