### ISSUE TITLE
Change bearing with touch event in mobile browsers

### ISSUE THREAD

**Issue by dbabbs** [visgl/deck.gl#2734]
#### Description
deck.gl supports changing bearing of the view fine in desktop browsers. However, this same expected behavior does not work on mobile browsers with deck.gl. With standard Mapbox GL JS (no deck.gl integration), one can change the map's bearing on mobile by holding the map with one finger while simultaneously dragging around with a second finger.

#### Repro Steps
Visit an example deck.gl map: https://flightmapper.io/maps/dbabbs on mobile. Try to change bearing with touch events. Only zoom with two finger pinch works. Bearing change does not work

To view intended behavior on Mapbox GL JS in mobile browser (without deck.gl dependency), try a map like: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/ . Bearing changes does work.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 5.3
 - Browser Version: Mobile Safari on iOS 12.1.4 or iOS Chrome 72.0.3626.101
 - OS: iOS 12.1.4

**Comment by jianhuang01** [comment]
Thanks for reporting, this is a new feature because we never planed doing it in this way.

**Comment by RELNO** [comment]
Hi @dbabbs, I've managed to get bearing on mobile via:

```
 <DeckGL
                   
                    ref={ref => {
                        // save a reference to the Deck instance
                        this.deckGL = ref && ref.deck;
                    }}
                    viewState={this.state.viewState}
                    onViewStateChange={this._onViewStateChange}
                    layers={this._renderLayers()}

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
// this is where it happens: 

                    controller={{
                        touchZoom: true,
                        touchRotate: true,
                        dragPan: !this.state.draggingWhileEditing,
                        dragRotate: !this.state.draggingWhileEditing,
                        keyboard: false
                    }}
                >
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                    <StaticMap
                        asyncRender={true}
                        dragRotate={true}
                        reuseMaps={true}
                        mapboxApiAccessToken={
                            process.env.REACT_APP_MAPBOX_TOKEN
                        }
                        preventStyleDiffing={true}
                    />
                </DeckGL>
```
