### ISSUE TITLE
2D smoothing of gpu-grid-layer layer

### ISSUE THREAD

**Issue by Firenze11** [visgl/deck.gl#2830]
#### Target Use case
I need to visually compare the spatial distribution of 2 sets of data points. The following image is roughly what I want, but not exactly it: imagine I plot 2 sets of heatmaps, the pink heatmap representing the density of triangles, the blue heatmap representing the density of circles. 
![image](https://user-images.githubusercontent.com/4994677/54857660-c4745900-4cbd-11e9-9a9f-2c8d329dc4b6.png)

The area of the 2 heatmaps might overlap, like what's shown in the following image: 
![image](https://user-images.githubusercontent.com/4994677/54857791-79a71100-4cbe-11e9-974c-3baaf119b241.png)

Among existing layers, the closest to that I need is the gpu-grid-layer and the contour-layer. However, I think something with a smoother boundary than grid borders would be helpful for visually distinguishing between the two different heatmaps (the boundaries of the two heatmaps have a high chance for overlapping with each other in a grid layer, which 

#### Proposed feature
Provide the possibility to apply 2d smoothing to gpu-grid-layer, similar to what's provided by Seaborn KDE plot https://seaborn.pydata.org/generated/seaborn.kdeplot.html
![image](https://user-images.githubusercontent.com/4994677/54857253-8118eb00-4cbb-11e9-8d29-e8a3e5b6db7a.png)

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by 1chandu** [comment]
Thank you @Firenze11 for the detials , `Heatmap` layer is in our deck.gl road map and planning to implement that in 7.x a release. Please stay tuned !!!

**Comment by Pessimistress** [comment]
HeatmapLayer is available in v8.
