### ISSUE TITLE
Document dataTransform prop for processing JSON loaded directly from URL

### ISSUE THREAD

**Issue by melvinraju** [visgl/deck.gl#2883]
Im trying to implement custom data into the trips example but don't know where to point the code to the nested JSON object. 

I have a JSON file which has [lat, long, timestamps] but is nested within a few layers. I have replaced DATA_URL.TRIPS with my file. Now where do I put the code that specifies where the object is nested. 

hope this makes sense...

**Comment by 1chandu** [comment]
@melvinraju , what is the format of your JSON file?

Our automatic URL loading has some limitations, copy pasting text from this [doc](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=id-string-optional-)

```
The automatic URL loading support is intended as a convenience for simple use cases. There are many limitations, including control over request parameters and headers, ability to parse non-JSON data, control of post-processing, CORS support etc. In such cases, it is always possible to load data using traditional JavaScript techniqwues and rerender the layer with the resulting data array.
```
CC: @ibgreen

**Comment by Pessimistress** [comment]
@melvinraju There is a secret layer prop `dataTransform` that you can use to post-process the loaded JSON.

@1chandu let's add this to the official documentation.
