### ISSUE TITLE
Use views into "Attribute.value" array for accessors

### ISSUE THREAD

**Issue by tsherif** [visgl/deck.gl#2905]
We might get a significant performance improvement on attribute updates if create views into the `value` array that standard accessors could use to update the array directly. This would avoid the step of having to copy the return value from the accessor function into the array [here](https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/attribute.js#L288).

Basically, you would create the views [here](https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/attribute.js#L133) as follows:

```js
this.valueViews = new Array(allocCount);
for (let i = 0; i < allocCount; ++i) {
   this.valueViews[i] = new ArrayType(this.value.buffer, i * this.size * ArrayType.BYTES_PER_ELEMENT, this.size);
}
```

These views could be used as the `target` property for `objectInfo` [here](https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/attribute.js#L286), and updates to that target would directly update the `value` array, so the call to `_normalizeValue` would become unnecessary. This could potentially be introduced as a non-breaking change by having users return `true` from the accessor if they've used the target. So the update code [here](https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/attribute.js#L286-L289) would look something like this:

```js
objectInfo.index++;
objectInfo.target = this.valueViews[objectInfo.index];
const objectValue = accessorFunc(object, objectInfo);
if (objectValue !== true) {
   this._normalizeValue(objectValue, value, i);
   i += size;
}
```

**Comment by ibgreen** [comment]
Presumably we agree that each "view" we create will be a new javascript object that will need to be 1. created and 2. garbage collected at some point. 

To minimize this cost, I assume your thinking is we would create the "views" upfront when we allocate a typed array in the attribute manager, and then release (and garbage collect) them when that typed array is reallocated or released, which means we would reuse these views more than once.

So we'd take some perf hit when creating, expanding data in, and destroying layers, but instead (hopefully) get a speed gain for opt-in accessors.

I think this could be a good idea, though we probably want to benchmark so we understand how big the speed gain of updating through views would be before starting.

**Comment by ibgreen** [comment]
A related thought:

IMHO, the biggest single inefficiency in deck.gl that I am aware of is that we keep around a complete typed array for every attribute after generating and uploading to a Buffer. 

I feel that we should only keep a single scratch arrayBuffer and reuse it when we generate attributes on CPU.

Now, if we did change to maintaining a single array buffer, then we could also regenerate the various views (Float32, Uint8 etc) whenever we create/expand that single arrayBuffer.

This ways the views would also be shared between layers, and there would be no additional hit for the second Float32 attribute in a layer as the views would already have been created.

**Comment by Pessimistress** [comment]
I ran some benchmarks: 

Given the following accessor

```js
var getPosition = (d, {target}) => {
  target[0] = 1;
  target[1] = 2;
  target[2] = 3;
  return target;
};
```

Current behavior (pre-allocated target array):

```js
var context = {target: []};
var value = new Float32Array(3e7);
for (var i = 0; i < 1e7; i++) {
  var position = getPosition(null, context);
  value[i * 3] = position[0];
  value[i * 3 + 1] = position[1];
  value[i * 3 + 2] = position[2];
}
```

Runs at 140 ms/iteration

Proposed behavior (views):

```js
var context = {};
var value = new Float32Array(3e7);
for (var i = 0; i < 1e7; i++) {
  context.target = new Float32Array(value.buffer, i * 3 * 4, 3);
  getPosition(null, context);
}
```

Runs at 570 ms/iteration
