### ISSUE TITLE
Add examples for core layers in gallery

### ISSUE THREAD

**Issue by xintongxia** [visgl/deck.gl#2968]
#### Proposed feature
Deck.gl [examples](http://deck.gl/#/examples/overview) page currently does not have all the demos for all the layers.

For starting point, port [ArcLayer](https://codepen.io/vis-gl/pen/dmmQqa) example from CodePen to deck.gl gallery.

Read the [article](https://github.com/uber/deck.gl/tree/master/examples/gallery) about how to work on gallery locally.

 
#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
     - [x] ArcLayer
     - [x] BitmapLayer
     - [x] ColumnLayer
     - [x] ContourLayer
     - [x] GreatCircleLayer
     - [x] IconLayer
     - [x] LineLayer
     - [ ] MeshLayer
     - [ ] S2Layer
     - [x] TextLayer
     - [ ] TileLayer
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by manishmz** [comment]
@xintongxia what data source should I use to implement a column layer demo?

**Comment by xintongxia** [comment]
> column layer

You can try this dataset
https://github.com/uber-common/deck.gl-data/blob/master/website/hexagons.json

Refer this [example](https://github.com/uber/deck.gl/blob/master/website/src/components/demos/layer-demos.js#L37)

**Comment by xintongxia** [comment]
@manishmz 

Are you planning to add all the examples listed here?

**Comment by manishmz** [comment]
> @manishmz
> 
> Are you planning to add all the examples listed here?

Yes, I am thinking about to add all examples.

**Comment by manishmz** [comment]
@xintongxia I have tried creating examples for SimpleMeshLayer but it's not showing any data visualization and also not giving any error.
Also for the implementing S2Layer example getting an error of 'S2Cell' of undefined.
I tried reading the documentation of these layers but not helping me.

Are there any examples for these layers to refer or anything do you think I am missing?

**Comment by xintongxia** [comment]
@manishmz 

> I have tried creating examples for SimpleMeshLayer but it's not showing any data visualization and also not giving any error.

You can post your code and error message here.

> Also for the implementing S2Layer example getting an error of 'S2Cell' of undefined.
I tried reading the documentation of these layers but not helping me.
> Are there any examples for these layers to refer or anything do you think I am missing?

[S2Layer example](https://github.com/uber/deck.gl/blob/master/examples/layer-browser/src/examples/additional-layers.js#L63)

**Comment by manishmz** [comment]
SimpleMeshLayer Code:
``` <html>
  <head>
    <title>deck.gl Mesh Layer Example</title>

    <script src="http://localhost:3000/deckgl.min.js"></script>
    <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.js"></script>

    <style type="text/css">
      body {
        width: 100vw;
        height: 100vh;
        margin: 0;
      }
    </style>
  </head>

  <body></body>

  <script type="text/javascript">
    const {DeckGL, SimpleMeshLayer} = deck;
    console.log(mapboxgl);
    new DeckGL({
      mapboxApiAccessToken: '<mapbox-access-token>',
      mapStyle: 'mapbox://styles/mapbox/dark-v9',
      longitude: -122.4,
      latitude: 37.74,
      zoom: 11,
      maxZoom: 15,
      pitch: 30,
      bearing: 0,
      layers: [
        new SimpleMeshLayer({
          id: 'mesh-layer',
          data:
            'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/layer-browser/sf.bike.parking.json',
          mesh:
            'https://raw.githubusercontent.com/uber-web/loaders.gl/e8e7f724cc1fc1d5882125b13e672e44e5ada14e/modules/ply/test/data/cube_att.ply',
          sizeScale: 40,
          getPosition: d => d.COORDINATES,
          getColor: d => [Math.random() * 255, Math.random() * 255, Math.random() * 255]
        })
      ]
    });
  </script>
</html> 
```

Not showing any output, and also not giving any error


S2Layer: 
```
<html>
  <head>
    <title>deck.gl S2Layer Example</title>

    <script src="https://unpkg.com/s2-geometry"></script>
    <script src="https://unpkg.com/deck.gl@~7.0.0/dist.min.js"></script>
    <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.js"></script>

    <style type="text/css">
      body {
        width: 100vw;
        height: 100vh;
        margin: 0;
      }
    </style>
  </head>

  <body></body>

  <script type="text/javascript">
    const {DeckGL, S2Layer} = deck;
    console.log(mapboxgl);
    new DeckGL({
      mapboxApiAccessToken: '<mapbox-access-token>',
      mapStyle: 'mapbox://styles/mapbox/dark-v9',
      longitude: -122.4,
      latitude: 37.74,
      zoom: 11,
      maxZoom: 15,
      pitch: 30,
      bearing: 0,
      layers: [
        new S2Layer({
          id: 's2-layer',
          data:
            'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/layer-browser/sf.s2cells.json',
          pickable: true,
          filled: true,
          extruded: true,
          elevationScale: 1000,
          getS2Token: d => d.token,
          getFillColor: d => [d.value * 255, (1 - d.value) * 255, (1 - d.value) * 128],
          getElevation: d => d.value
        })
      ]
    });
  </script>
</html>
```
Error: 
![Screenshot from 2019-07-01 21-38-38](https://user-images.githubusercontent.com/12951656/60451065-d4022700-9c48-11e9-8408-391ee013e413.png)

**Comment by manishmz** [comment]
@xintongxia Any update on this
