### ISSUE TITLE
TripsLayer not working?

### ISSUE THREAD

**Issue by huashaoxu** [visgl/deck.gl#3032]
I try to use Tripslayer by going to create MapboxLayer, but it do not added to mapbox. The console has no information at all. my code:
const myDeckLayer2 = new MapboxLayer({
        id: "my-scatterplot1",
        type: TripsLayer,
        data: 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/trips/trips.json',
        getPath: d => d.segments,
        getColor: d => (d.vendor === 0 ? [253, 128, 93] : [23, 184, 190]),
        opacity: 0.3,
        widthMinPixels: 2,
        rounded: true,
        trailLength,
        currentTime: this.state.time
      });

      const myDeckLayer3 = new MapboxLayer({
        id: "my-scatterplot2",
        type: PolygonLayer,
        data: 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/trips/buildings.json',
        extruded: true,
        wireframe: false,
        opacity: 0.5,
        getPolygon: f => f.polygon,
        getElevation: f => f.height,
        getFillColor: [74, 80, 87],
        material
      });

      map.on("load", () => {
        // map.addLayer(myDeckLayer);
        map.addLayer(myDeckLayer2);
        map.addLayer(myDeckLayer3);
      });
So what should I do now? I have been trying this for a couple of days now.... Any help would be appreciated...

**Comment by balthazar** [comment]
I'm pretty sure I am hitting the same issue, as soon as I provide a timestamp to each point in the `getPath`, it simply disappears

**Comment by balthazar** [comment]
Actually scratch that, it was my mistake with a wrong import + overflowing of the third array element. Make sure you test with the [mock data](https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/sf.trips.json) from the example and see if the issue is still present for you.

**Comment by huashaoxu** [comment]
Has the source code been submitted? There seems to be no commit record
