### ISSUE TITLE
Defining Additional Attributes section is not sufficient to make a functioning subclassed layer

### ISSUE THREAD

**Issue by jowcy** [visgl/deck.gl#3033]
The section on 'Defining Additional Attributes' here http://deck.gl/#/documentation/developer-guide/writing-custom-layers/subclassed-layers?section=defining-additional-uniforms does not provide all necessary steps/code.

I found that when creating a new attribute that the attribute was only available within the first vector (between points 1-2), and was not correctly populated for additional vectors.  To make this work I had to mimic the code found in path-layer.js and path-layer-tesselator.js

**Comment by jianhuang01** [comment]
> I found that when creating a new attribute that the attribute was only available within the first vector (between points 1-2), and was not correctly populated for additional vectors. 
Can you clarify what's the meaning?
> To make this work I had to mimic the code found in path-layer.js and path-layer-tesselator.js
Can you point to the code in path-layer.js and path-layer-tesselator.js?
