### ISSUE TITLE
How to return info objects for all pickable objects for layer?

### ISSUE THREAD

**Issue by ToddJacobus** [visgl/deck.gl#3056]
I'm successfully using the `pickObject` and `pickObjects` methods to get arrays of info objects, but their usage seems to be limited to objects rendered in the viewport.  Is there a built-in way to return info objects for all `pickable` objects for a layer, regardless of whether it has been rendered in the viewport?

Thanks,
Todd

**Comment by jianhuang01** [comment]
we don't have that kind of API, cause you pass the data to each layer, know all the objects in that layer already.
