### ISSUE TITLE
AppAnimationLoop in Customized layer symbols.

### ISSUE THREAD

**Issue by YuhangGu** [visgl/deck.gl#3090]
I'm trying to create animated symbols in deck.gl without synchronous from layer properties, which allowing[ dynamic visual variables](https://gistbok.ucgis.org/bok-topics/symbolization-and-visual-variables
) be applied (order, frequency, duration). I was inspared by [luma animationloop](https://luma.gl/#/examples/webgl-lessons/lesson-09-moving-objects). Does anyone has an idea about embedding Animation loop into the deck.gl customized layers? Thanks for suggestion with examples.

**Comment by 1chandu** [comment]
CC: @tsherif 
We are currently working timeline management system for custamizable animations, please check [RFC](https://github.com/uber/luma.gl/blob/master/dev-docs/RFCs/v7.1/animation-timeline-rfc.md), is this something you are looking for?

**Comment by YuhangGu** [comment]
@1chandu Thank you! That is exactly what I'm looking for. Is it possible to use AnimationLoop in Deck.gl now? I thought it may work but I cannot figure out a right way to use it. It there any demo with Animationloop in Deck.gl layers?

**Comment by Pessimistress** [comment]
deck.gl already runs an AnimationLoop under the hood. As of v8, you can access the timeline in a layer via `this.context.timeline`. A layer can also request a redraw in its `draw` method, see https://github.com/visgl/deck.gl/blob/b5135e2e8a50654d938950fb4e9cfd2ff10cc1fc/modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js#L246
