### ISSUE TITLE
Allow for getTrailLength method in trips-layer

### ISSUE THREAD

**Issue by harisbal** [visgl/deck.gl#3136]
Hello,
I wanted to ask whether it would be possible to include the `getTrailLength` data accessor.
I could give it a go but I suppose the shaders complicate the issue..

**Comment by Pessimistress** [comment]
The TripsLayer is already approaching the WebGL attribute limit and we don't see a common use case where users need to set `trailLength` per path. You can implement this locally by [subclassing](https://deck.gl/docs/developer-guide/custom-layers/subclassed-layers) the TripsLayer class.
