### ISSUE TITLE
boxZoom controller

### ISSUE THREAD

**Issue by Akiyamka** [visgl/deck.gl#3240]
[Controller option](https://github.com/uber/deck.gl/blob/master/docs/api-reference/controller.md) not include enabled by default mapbox controller - [boxZoom](https://docs.mapbox.com/mapbox-gl-js/api/#boxzoomhandler)

#### Target Use case
Adding this feature will allow us to make event-transparent deck.gl overlay without broken mapbox default behavior.

#### Proposed feature
How it work in mapBox you can see [here](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/) (just hold shift and draw rectangle on map).
deck.gl must forward events to map for provide same interaction experience as on map without overlay.
Option can be named as `Deck.controller.boxZoom` (same name as in [mapbox options](https://docs.mapbox.com/mapbox-gl-js/api/)) and must be true by default.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
DeckGL is not dependent on mapbox-gl, therefore it implements its own controllers to handle user interaction. Though we try to be as compatible as possible with various basemap providers, it's not a goal to replicate their behavior 1:1. If you wish to use Mapbox's native event handling, you can look at [this example](https://deck.gl/examples/mapbox/).
