### ISSUE TITLE
Mobile Samsung - IconLayer onClick events do not complete unless tapped very fast.

### ISSUE THREAD

**Issue by pr1ntr** [visgl/deck.gl#3324]
#### Description
On Samsung S9 (and reportedly S8). IconLayer onClick events do not register unless tapped extremely fast. It does not seam to getting the onTouchEnd event 

#### Repro Steps
Make any mapbox-gl/deck.hl map with IconLayers. the onClick event only fires if user hits icon fast enough. Otherwise it will require another tap or moving the map.
(Let me know if you need an example) My current one is for a client project and is pretty complex. Here is an excerpt:

```
_renderLayers() {
    const { iconAtlas, iconMapping, } = this.props
    const { data } = this.state

    const markers = new IconLayer({
      transitions: {
        getColor: {
          duration: 150,
          ease: easing.linear,
        },
        getPosition: {
          duration: 150,
          ease: easing.linear,
        },
      },
      data,
      id: 'marker-layer',
      iconAtlas,
      iconMapping,
      pickable: true,
      onClick: (...args) => console.log('yo', args) || this._onIconClick(...args),
      onHover: this._onIconHover,
      onDragEnd: platformType === 'mobile' ? this._onIconClick : () => {},
      sizeScale: 1,
      getIcon: d => {
        if (d.featured) {
          return FEATURED_TYPES[d.type]
        } else {
          return d.type
        }
      },
      getSize: 64,
      getColor: d => {
        const alpha = d.hover ? 180 : 255

        return [0, 0, 0, d.visible || d.selected ? 0 : alpha]
      },
    })
   return [markers]
}
```

#### Environment (please complete the following information):
Only Galaxy S9/8
Deck.GL 6.3.7
Chrome 75
Android 9

#### Logs
None

**Comment by pr1ntr** [comment]
The behavior seems like deckgl is thinking that the samsung screen has a mouse or some kind of hover functionality

**Comment by 1chandu** [comment]
Not sure what the problem is, but deck.gl uses `EventManager` from [miolnir.js](https://github.com/uber-web/mjolnir.js/blob/master/docs/api-reference/event-manager.md) for processing input events, is it possible the actual problem be in this library that is specific to your device?

**Comment by pr1ntr** [comment]
It only seems specific to the Samsung S9, Note, S8 it seems. Its really strange. Like the performance is fine runs smooth, but it wont pick up taps on IconLayers unless its very very precise. I found a work around for now the project will be live soon and I can share some tests.

**Comment by Pessimistress** [comment]
Consolidating with #5089
