### ISSUE TITLE
GoogleMapsOverlay does not support getCursor

### ISSUE THREAD

**Issue by SterlingMcCall** [visgl/deck.gl#3354]
#### Target Use case
I would like to be able to change the cursor when using deck.gl with Google Maps. It seems to always just inherit the cursor from the Google Map underneath.

Specifically, I was trying to change the cursor on hover of an icon within an `IconLayer`. If I weren't using Google Maps I could set the `getCursor` method on the `Deck` properties. However, the GoogleMapsOverlay [documentation](https://deck.gl/#/documentation/submodule-api-reference/deckgl-google-maps/google-maps-overlay?section=constructor) shows that this is not supported.

#### Proposed feature
Allow the `getCursor` property to be set on a `GoogleMapsOverlay`. Alternatively, support the `getCursor` property on a `Layer` (would probably easier to use).

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
We do set the `cursor` style on the overlay but it doesn't seem to be effective. Does Google Maps API allow you specify your own cursor override? @donmccurdy

**Comment by SterlingMcCall** [comment]
@Pessimistress Google Maps [does allow changing](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions) the drag cursor via the `draggableCursor` property. The problem is that I want the default drag cursor except for when I'm hovering on an icon in an `IconLayer`. I was able to get around it by setting the Google Maps `draggableCursor` to a pointer when the deck.gl `onHover` handler receives an object, and setting the cursor back to the default when the when the cursor leaves the icon. It's hacky and more detailed state management than I'd like, but it works okay.

I'm not sure how it would work if there were native Google maps pins or interactable elements in the same area which would change the cursor and mean it wasn't using the draggable cursor.

Perhaps deck.gl could be modified to take control of the cursor in the same manner under the hood.

**Comment by donmccurdy** [comment]
> Does Google Maps API allow you specify your own cursor override?

Not elegantly, but the 'draggableCursor' property is one option. Another would be CSS or equivalent JS:

```css
.gm-style:first-of-type > div:nth-child(1) {
    cursor: default !important;
}
```

The downside of using `draggableCursor` is it assumes the user has enabled dragging. The downside of the CSS is that it's obviously hacky... And I'm not confident either of these will automatically do the right thing if multiple non-deckgl overlays or markers are present.

> Perhaps deck.gl could be modified to take control of the cursor in the same manner under the hood.

Unfortunately I doubt that's possible right now. There is a fairly strong assumption within Maps API that it manages mouse events itself.
