### ISSUE TITLE
transitions problem on mobile chrome (android)

### ISSUE THREAD

**Issue by czinkos** [visgl/deck.gl#3364]
#### Description
Layer doesn't appear on mobile Chrome (android) when using transitions. deck onLoad function not called. Works on desktop Chrome (both windows and linux).

#### Repro Steps
https://codepen.io/anon/pen/aezrEr

If I remove the transitions property, it works both on mobile and desktop.

#### Environment (please complete the following information):
 - deck.gl 7.1.10]
 - Browser Version: Chrome 75.0.3770.143
 - OS: Android 8.0.0

Thanks.

**Comment by Pessimistress** [comment]
The version referred to by this issue is no longer maintained. Please open a new bug if this is still observed on the latest release.
