### ISSUE TITLE
TextLayer / ScatterplotLayer z-fighting

### ISSUE THREAD

**Issue by marioaks** [visgl/deck.gl#3368]
#### Description

I have created a NodeLayer by combining a ScatterplotLayer and the TextLayer, but I've been running into an issue where the TextLayer always gets rendered above the ScatterplotLayer despite small offsets to the z coordinate in getPosition. The only thing that seems to get the nodes to overlap correctly is making the offsets to the z-coordinate unreasonably large. 

#### Repro Steps

`This is the code I'm using to create my node layer:

      new ScatterplotLayer(
        this.getSubLayerProps({
          id: "node-layer-background", 
          data,
          getPosition: d => [...d.centroid, (data.length - d.rank) * .01],
          getRadius,
          radiusMinPixels,
          radiusMaxPixels,
          getFillColor,
          getLineColor,
         
        })
      ),
      new TextLayer(
        this.getSubLayerProps({
          id: "node-layer-text",
          data,
          getText,
          getPosition: d => [...d.centroid, (data.length - d.rank) * .01],
          fontWeight,
          fontFamily,
          getColor,
          getSize,
          pickable: false
        })
      )
`

The actual output of the code is: 
<img width="248" alt="Overlapping Nodes" src="https://user-images.githubusercontent.com/13203039/61738200-c0ce0d00-ad57-11e9-99cf-7cf9c17588e2.png">

If I change the *.01 to 1000, the nodes overlap correctly: 
<img width="258" alt="Screen Shot 2019-07-23 at 2 41 12 PM" src="https://user-images.githubusercontent.com/13203039/61738274-f1ae4200-ad57-11e9-8dc0-a4555287e222.png">

Small offsets to the z-coordinate seems to work for other layers, but it doesn't work for the TextLayer. Am I doing something wrong?

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 7.1.10]
 - Browser Version: [e.g. Chrome 75.0]
 - OS: [e.g. Mac OS X 10.14.5]

**Comment by Pessimistress** [comment]
An [artificial offset](https://deck.gl/docs/api-reference/core/layer#getpolygonoffset) is add to each layer to reduce z-fighting. Since you do want these two layers to interleave, you can try removing the offset with `getPolygonOffset: null` in both layers.

**Comment by prepfarm** [comment]
Using `getPolygonOffset: null` makes composition layer (that has circle and text) go behind all other layers. If I use only that layer, it's working mostly fine, but it still sometimes overlaps. How to do this and keep this layer above/at position where is defined in array of layers?

Is there better way to do this, since 4 years have passed?
