### ISSUE TITLE
Support for Grafana

### ISSUE THREAD

**Issue by monolithed** [visgl/deck.gl#3405]
#### Proposed feature

Hi,

Are there any plans to make a plugin for Grafana like Apache Superset?

**Comment by Pessimistress** [comment]
Not at the moment. Can you tell us more about this use case?

**Comment by monolithed** [comment]
There is a similar integration with [Apache Superset](https://github.com/apache/incubator-superset) and it looks great. I thought that integration was implemented by you, so sorry for my misunderstanding ))
