### ISSUE TITLE
Be able to adjust stroke location to inside, center, outside

### ISSUE THREAD

**Issue by twgonzalez** [visgl/deck.gl#3439]
#### Target Use case
Being able to adjust the stroke location to inside, center, outside would be helpful when using strokes on polygons and force stroke rendering position.    

Currently less than desirable visual artifacts occur with the stroke position always set to center:
Example:
Layer opacity is set to less than 1.0 
Stroke width is set high enough so stroke now overlaps with fill layer
Overlap area of stroke and fill now are blended with their respective color/opacity versus having clean boundaries.

#### Proposed feature
strokePosition:  inside, center, outside

![PastedGraphic-1](https://user-images.githubusercontent.com/587141/62955770-7ebc4800-bda6-11e9-9f9b-f2d00170279d.png)

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
This can be achieved with [PathStyleExtension](https://deck.gl/docs/api-reference/extensions/path-style-extension)'s `offset` mode.

**Comment by twgonzalez** [comment]
Awesome!  Thanks!
