### ISSUE TITLE
Advice on using Binary Data

### ISSUE THREAD

**Issue by dcooley** [visgl/deck.gl#3467]
### Background

Some of you may have seen the R library I develop - [mapdeck](https://github.com/SymbolixAU/mapdeck) (as @SymbolixAU ) - which means we can call deck.gl from within R. 

All the underlying code which translates R objects into deck.gl compatible javascript is written in C++

So I have full control of how the data is transferred between C++ and Deck.gl. Currently I'm constructing a JSON object, which I'm sending to the various [map layers](https://github.com/SymbolixAU/mapdeck/tree/master/inst/htmlwidgets/lib) and using all the `get*` accessors to unpack it.

To improve performance I'd like to make use of [**`Binary Data`**](https://github.com/uber/deck.gl/blob/master/docs/developer-guide/performance.md#on-using-binary-data) in some way.

Within the C++ objects I know

- the number of objects to be plotted
- the number of coordinates within each object
- all the associated properties; colours as RGBA arrays, radii, etc

So I know the number of vertices which need to be drawn, their positions and colours etc, for every layer type (points, polygons, lines). 

### Question

I'm after advice on how can I best make use of binary data to get the best performance? 

Reading through the docs this seems trivial for 'primitive' layers (scatterplot, pointcloud) which take POINT geometries. How can I extend this for non-primitive layers (polygon, path)?

Also, (and this may or may not be something you can help with) is there another way I can send the data from C++ to the WebGL buffers, maybe using WebAssemply through emscripten?

**Comment by ibgreen** [comment]
@dcooley We love the work you are doing on R / mapdeck, more than happy to try to help: 

First, make sure you understand that we support two ways of using binary data with deck.gl: 

- You can provide the `data` prop as a "binary columnar table" (rather than a traditional row based `Array` of objects). In this case deck.gl will still convert your binary data into its internal binary representation. The disadvantage is that some work is still performed, but this works for all layers.

- You can also bypass the `data` prop and provide binary data already formatted as "attributes", i.e. in the form that the deck.gl layer shaders expect (this seems to be what you are doing now). As you say, this is usually fairly easy for the instanced / "common-primitive" layers but for the non-instanced / "custom-primitive" layers these layout can get very complex as you have discovered.

My point here is that with a combination of the two techniques above you should already today in deck.gl 7.2 be able to accept binary input directly in all cases.

For the future, we are working on techniques to make it easier to generate the custom binary layout our non-instanced layers. However your program will obviously need to do the conversion to deck.gl memory layout at some point, so you may want to convince yourself what you are actually gaining something by moving that conversion out of deck.gl. 

We are also working on supporting generic mappings from Apache Arrow formatted binary tables (and data frames) to deck.gl layers. Arrow is explicitly designed to have be a cross-language binary table representation so it seems ideal for this use case. If you are interested in being an early adopter of that solution we might be able to strike up a collaboration.

**Comment by ibgreen** [comment]
> is there another way I can send the [binary] data from C++ to the WebGL buffers, maybe using WebAssemply through emscripten?

This is a great question, that we have considered but unfortunately have not found time to explore. My hand wavy understanding is that WebAssembly gets its own memory heap allocated, and that performance is significantly better (2x) if that heap size is fixed. What is not clear to me is whether a WebAssembly program can share a typed array allocated in its own heap with external JS code (i.e. deck), or conversely, if a typed array allocated by external JS (deck) could be passed in and populated by the WebAssembly code. 

If you do any work here, would be more than happy to support, including some virtual pair coding/debugging.

Finally, you may be interested in following our pydeck project. We are releasing a set of Python bindings for deck.gl. We focus on Jupyter Notebook integration so we do not use emscripten, but rather the deck.gl JSON API. We expect that it would also be possible to build R bindings on top of that API. And we are exploring using Apache Arrow for binary data transport between the Jupyter kernel and deck.gl.

**Comment by dcooley** [comment]
Thanks for the detailed response! Considering all possible options and potential performance gains I think my next goal is to get an emscripten prototype working. Getting C++ to communicate directly with javascript should give a direct boost in performance, and give a good base on which to build. 

> If you do any work here, would be more than happy to support, including some virtual pair coding/debugging.

Once I get it up and running I'll give you a ping. 

Apache Arrow is also on my radar, and the JSON API will work well for streaming large JSON directly into a map. These are close behind on my TODO list!

**Comment by ibgreen** [comment]
> My next goal is to get an emscripten prototype working

It would be really neat to have a minimal example in deck.gl that showed how to get this working. If you are doing some experiments, maybe something could be packaged up as the "seeds" of such an example and submitted as a PR? 

Just a good package.json installing the right version of emscripten with some scripts to run it, that could help us get started...

>  the JSON API will work well for streaming large JSON directly into a map

The JSON API is mainly a way to expose deck.gl props through a simple 1-to-1 mapping:

- See https://deck.gl/json. 
- Our python bindings just generate such a JSON blob and send to the browser, the @deck.gl/json module handles the layer instantiation. 
- We plan to ensure all our layers and components can be accessed through the JSON API. 
- Avoids custom mappings for each layer in each language wrapper.
- Could be a way for you to make your R bindings more easily extensible with our growing layer catalog as well as externally developed layers.

**Comment by ibgreen** [comment]
@ajduberstein

**Comment by SymbolixAU** [comment]
> Just a good package.json installing the right version of emscripten with some scripts to run it, that could help us get started...

This is the tricky bit; I know next to nothing about creating javascript packages. I'm looking at it from the other point of view; having a C++ library which calls javascript, so it sends data from C++ to deck.gl. 

If I can get it working the other way around too I'll see if I can package it correctly.

**Comment by dcooley** [comment]
Keeping this thread up-to-date

I haven't had any success with the emscipten work; the compile tool-chain is not currently widely supported in R, I think it needs to mature a bit for this to be a viable option.

On using binary data.

All my data can / will come from R as column-based tables, similar to

```js
  const dataFromR = {
    lon: [0,1,2],
    lat: [1,2,3],
    fill_colour: [255,0,0,255,0,255,0,255,0,0,255,255],     // includes alpha
    stroke_colour: [0,0,255,255,0,255,0,255,255,0,0,255],
    radius: [10000,5000,5000],
    ... etc
  };
```

Which I can easily make work in the primitive layers.

```js       
  // interleaved data
  // data will come in from R thus:
  const dataFromR = {
    lonlat: [0,0,1,1,2,2],
    fill_colour: [255,0,0,255,0,255,0,255,0,0,255,255],
    radius: [10000,5000,5000]
  };
 
  const binaryLocation = new Float32Array(dataFromR.lonlat);
  const binaryRadius = new Float32Array(dataFromR.radius);
  const binaryColour = new Float32Array(dataFromR.fill_colour);
  
  const scatter = new deck.ScatterplotLayer({
    data: {
      length: 3,
      attributes: {
        getPosition: {value: binaryLocation, size: 2},
        getRadius: {value: binaryRadius, size: 1},
        getFillColor: {value: binaryColour, size: 4}
      }
    }
  })
  
  deckgl.setProps({layers: [scatter] });
```

---

As has been pointed out the composite layers (e.g. polygons) are trickier. 

> We are also working on supporting generic mappings from Apache Arrow formatted binary tables (and data frames) to deck.gl layers. Arrow is explicitly designed to have be a cross-language binary table representation so it seems ideal for this use case. If you are interested in being an early adopter of that solution we might be able to strike up a collaboration.

From this description, and the native R-based data.frames it seems like using this Apache Arrow formatted binary tables is the most viable solution. 

So I'd be happy to test out this feature if you point me to where I can get started?
