### ISSUE TITLE
Add support for an H3 hexagonAggregator in the HexagonLayer

### ISSUE THREAD

**Issue by dcj** [visgl/deck.gl#3479]
#### Target Use case

I am attempting to aggregate a large number of points from a large number of trajectories, and display the count per-H3 hexagon, of each trajectory that passed through that hexagon.

#### Proposed feature

1) I'd like to use H3 hexagons instead of D3 hexagons.
2) Each of my positions also contains a trajectory id.  I need to the final count per hexagon to be of the trajectories, not the points.
3) Because these are trajectories, as the hexagon resolution increases, there may be positions missing along the trajectory, ideally h3Line is called on each pair of positions, and the result added to the collection of indexes that trajectory passed through
4) Finally, optionally, I'd like to be able to include "nearby" hexagons. In the base case, I want the H3 hexagons of each trajectory at resolution R, and k=0.  But there are cases when I want to include the k-ring=K hexagons of a trajectory as well.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Have you tried supplying your own `hexagonAggregator`? https://github.com/uber/deck.gl/blob/7.2-release/docs/layers/hexagon-layer.md#hexagonaggregator-function-optional
