### ISSUE TITLE
Cursor doesn't change when using MapboxLayers

### ISSUE THREAD

**Issue by nagix** [visgl/deck.gl#3522]
#### Description
When using MapboxLayers, the cursor stays "grab" and doesn't change to "grabbing" on drag. The cursor style cannot be explicitly modified by `map.getCanvas().style.cursor = /* style */`, either.

#### Repro Steps
See https://deck.gl/showcases/gallery/mapbox-layer.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.2.3
 - Browser Version: Chrome 76.0.3809.132, FireFox 69.0, Safari 12.1.2
 - OS: Mac OS X 10.14.6

**Comment by nagix** [comment]
My workaround is to set my own `getCursor` function **after adding a MapboxLayer to the map instance** so that is doesn't modify the existing style.
```
map.__deck.props.getCursor = () => map.getCanvas().style.cursor;
```

**Comment by Pessimistress** [comment]
You can try [Use a Layer from an Existing Deck's Layer Stack](https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/mapbox-layer?section=use-a-layer-from-an-existing-deck-s-layer-stack) which will allow you to set Deck props.

**Comment by Shadowsych** [comment]
Or you can do:

```js
<DeckGL getCursor={() => 'inherit'} />
```

This will inherit the same cursor as Mapbox.
