### ISSUE TITLE
Add domain method to scale functions

### ISSUE THREAD

**Issue by Navneet-Sahota** [visgl/deck.gl#3630]
#### Proposed feature

Add `domain` function to existing `getQuantileScale` and `getOrdinalScale`

#### To Do List 
  - [x] Coding
  - [x] Test

**Comment by 1chandu** [comment]
Should we add `range` too to match existing scaling methods?

**Comment by Navneet-Sahota** [comment]
Modified new functions to use `getScale` and match existing scaling methods.
