### ISSUE TITLE
Arc Pattern

### ISSUE THREAD

**Issue by jtbaker** [visgl/deck.gl#3685]
#### Target Use case
Illustrate direction of travel along arc from source to destination with a mono-color scheme.

#### Proposed feature
`line-pattern` similar to Mapbox's paint property that allows users to choose an icon from sprite sheet to render the feature with, or to render features with arrows.

Sprite Icon or Arrow feature along line to better convey to the user which side of the arc are the source and destination.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by xintongxia** [comment]
You can use [`IconLayer`](https://github.com/uber/deck.gl/blob/master/docs/layers/icon-layer.md#example-pre-packed-iconatlas) which support passing in a sprite.

**Comment by jtbaker** [comment]
@xintongxia I looked through the documentation for `IconLayer` but it seems like its main usage is for plotting point data. Is there any way for it to interface with the `ArcLayer`? Thanks!

**Comment by xintongxia** [comment]
@jtbaker 

you can use more than 1 layers with deck.gl

Something like the following,

```
const layers = [
  new ArcLayer({id: 'arcs', data: ...}),
  new IconLayer({id: 'icon', dataL, ...})
];

return (<DeckGL {...viewport} layers={layers} />);
```
