### ISSUE TITLE
TileLayer performance improvement

### ISSUE THREAD

**Issue by VictorVelarde** [visgl/deck.gl#3695]
#### Target Use case
We have started to test TileLayer for dealing with MVT Tiles. Working to improve its performance would be relevant for this and probably more use cases.

#### Proposed feature
We have checked (using an approach as described in [TileLayer](https://github.com/uber/deck.gl/blob/master/docs/layers/tile-layer.md)) that the major performance cost is in applying a `renderSubLayers` call per tile. 

What we propose here, as a first step, is trying to manage the Tiles differently (per z level), reducing the number of render calls. We have tested it in a fork and it looks it might be useful, so we would be pleased to discuss it over a PR.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ibgreen** [comment]
> We have checked (using an approach as described in TileLayer ) that the major performance cost is in applying a renderSubLayers call per tile.

@VictorVelarde I am working on the somewhat related `Tile3DLayer` (will be available in the imminent deck.gl 7.3 release), and would be very interested in your findings as we also render a lot of sublayers.

I'd like to look at whether there are any performance inefficiencies in 'renderSubLayers` that we can address on a framework level, before we adopt more complex logic in these layers.

**Comment by VictorVelarde** [comment]
Great @ibgreen ! Then we're gonna create a small PR, referencing this issue, with our approach and some metrics. 

/cc @jesusbotella
