### ISSUE TITLE
weather data in WindDemo

### ISSUE THREAD

**Issue by haoran1012** [visgl/deck.gl#3701]
Hi!  @XiaokaiUber !In WindDemo, the weather data is a 72 length array，which Each element has three sub-element.what is meaning of each element,such as[8,0,148]?

**Comment by 1chandu** [comment]
can you provide a link to the source code.

**Comment by haoran1012** [comment]
this is the source code. [``](https://github.com/uber/deck.gl/blob/master/showcases/wind/src/utils/load-data.js) 

this is the weather data. `const WEATHER_DATA_URL =
  'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/wind/weather.bin';`
thank you!

**Comment by haoran1012** [comment]
> can you provide a link to the source code.

this is the source code.https://github.com/uber/deck.gl/blob/master/showcases/wind/src/utils/load-data.js ``

this is the weather data. const WEATHER_DATA_URL = 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/wind/weather.bin';
thank you!

**Comment by gnavvy** [comment]
@haoran1012 If I recall, `72` is the number of hours and the three components `[8, 0, 148]` should be the magnitude of the wind along the x, y, z directions, respectively.
