### ISSUE TITLE
ScenegraphLayer: Support glTF KHR_materials_unlit extension

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#3705]
#### Target Use case
Photogrammetry is already lit, no additional lighting should be applied.

#### Proposed feature
- GLTFLoader in loaders.gl now supports this extension.
- Check `material.unlit`, in this case just render the base color texture.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ibgreen** [comment]
AFAIK, this is only handled in loaders.gl. It also needs to be handled in luma.gl lighting modules and verified/plumbed through in deck.gl. 

Use case: This extension is needed for supporting 3d tiles with photogrammetry.

Maybe move this to v8.x instead of closing?

**Comment by tgorkin** [comment]
Sorry, incorrectly assumed this was complete as part of the linked PR.
