### ISSUE TITLE
flyTo layer data

### ISSUE THREAD

**Issue by cmonacaps** [visgl/deck.gl#3731]
Hi, I would like to set up a transition, when some layer data is loaded, to automatically set the viewport to best-fit that layer data.

But I don't see how to extract the required parameters from the initialized layer, or a utility method to get the parameters from the data.  In this case it is a GeoJSON and GeoJsonLayer, but I didn't see anything more generally as yet either.

Thank you in advance.

**Comment by Pessimistress** [comment]
You can listen to [onDataLoad](https://deck.gl/docs/api-reference/core/layer#ondataload) and call [turf's bbox](http://turfjs.org/docs/#bbox) to get the bounding box of your GeoJSON.
