### ISSUE TITLE
Running showcases

### ISSUE THREAD

**Issue by lperozzi** [visgl/deck.gl#3745]
Hi, I'm very new with deckl.gl, so I'm trying to learn from examples. However, I would like to test the showcases examples (wind or graph), but after `npm start` I have this message that I cannot resolve:

```
> @ start deck.gl/showcases/wind
> webpack-dev-server --progress --hot --open --content-base static

invalid "instanceof" keyword value Promise
npm ERR! code ELIFECYCLE
npm ERR! errno 255
```  

(aside note, the minimal standalone exemples works fines, I just want to learn from the wind exemples since it is more complex and has interaction with multiple layers and source data)

**Comment by scottbasgaard** [comment]
`npm install webpack-dev-server@2.11.0 --save-dev` for example will help.

I have issues with @luma.gl now though, not sure what version works.
