### ISSUE TITLE
Weird Polygon rendering

### ISSUE THREAD

**Issue by jesusbotella** [visgl/deck.gl#3746]
#### Description
Deck.gl is rendering an empty polygon with weird fill from a GeoJSON feature.

The polygon that I'm trying to render is just a regular GeoJSON polygon with no coordinates loop or whatsoever, but it renders a weird fill inside the other part of the polygon instead of filling the actual polygon.

#### Repro Steps
Open this codepen example and you'll see what happens: https://codepen.io/jesusbotella/pen/abboRXe

#### Expected Output
To compare, here's how geojson.io renders the same polygon:
![Screenshot 2019-10-04 at 11 00 43](https://user-images.githubusercontent.com/4319728/66195863-d638af00-e697-11e9-9b81-a5fbf183a604.png)

#### Actual Output
<img width="213" alt="Screenshot 2019-11-18 at 09 21 24" src="https://user-images.githubusercontent.com/4319728/69035830-d8a35e00-09e4-11ea-9a85-7e0a540a8eb3.png">

#### Environment:
 - Framework Version: deck.gl 7.3.2
 - Browser Version: Chrome 77.0.3865.90
 - OS: Mac OS X 10.14.4

#### Logs
No relevant logs related to Deck.gl, just version log.

**Comment by VictorVelarde** [comment]
Any update on this?

**Comment by VictorVelarde** [comment]
It might be the same situation as the one described here: https://github.com/uber/deck.gl/issues/3892
