### ISSUE TITLE
Views not contained inside canvas element

### ISSUE THREAD

**Issue by reinvanimschoot** [visgl/deck.gl#3764]
#### Description

When setting up a simple test case for a Deck.gl implementation, the rendered view is not contained inside the canvas.

![Screenshot 2019-10-09 at 16 18 19](https://user-images.githubusercontent.com/35171567/66489838-86e7e980-eab0-11e9-8664-cd95b832212e.png)
![Screenshot 2019-10-09 at 16 18 52](https://user-images.githubusercontent.com/35171567/66489839-87808000-eab0-11e9-974d-b6a7df286124.png)

#### Repro Steps
My code:

```
import DeckGL, { MapView } from 'deck.gl';
import React from 'react';
import { _MapContext as MapContext, StaticMap, NavigationControl } from 'react-map-gl';

function AssetMap() {
  const [coordinates, setCoordinates] = React.useState({ longitude: -74.006, latitude: 40.7128 });
  const [zoom, setZoom] = React.useState(12);

  return (
    <DeckGL
      ContextProvider={MapContext.Provider}
      views={[new MapView({ id: 'default-view', width: '100%', height: '100%' })]}
      viewState={{
        ...coordinates,
        zoom,
      }}
      id="asset-map"
      height="90vh"
      width="100%"
      controller={true}
      onViewStateChange={(data: any) => {
        const { latitude, longitude } = data.viewState;

        setCoordinates({ latitude, longitude });
        setZoom(data.viewState.zoom);
      }}
    >
      <div style={{ position: 'absolute' }}>
        <NavigationControl />
      </div>

      <StaticMap
        height="100%"
        width="100%"
        mapStyle="mapbox://styles/mapbox/streets-v11"
        mapboxApiAccessToken="pk.eyJ1IjoiY2FsbGFyaWRlIiwiYSI6ImNqeWlvZ2ljODA0YWgzbm82d2FxM3BoeGIifQ.VgvqmFDyg4joDqMGtQJaDQ"
      />
    </DeckGL>
  );
}

export default AssetMap;
```

#### Environment (please complete the following information):
 - Framework Version: 7.3.2

**Comment by 1chandu** [comment]
@reinvanimschoot , it does show the static map in your images correctly (with map box logo), also I don't see you are rendering any layers, i.e. no `layers` props for `DeckGL`. And also don't see any issues with DeckGL props. What is expected here?

Another thing, by providing `viewState` you will not be using deck.gl internal viewState, instead you can provide `initialViewState`, docs [here](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=initialviewstate-object-).

**Comment by reinvanimschoot** [comment]
@1chandu The problem is that even though I tried changing the styling of the Deck/View/StaticMap, it still renders an absolute positioned element that is hidden behind the top header and drawer menu on the side. I cannot seem to get rid of that inherent styling. 

And I noticed in the elements tab that the two views that are rendered are not children of the canvas element but siblings. Not sure if that should be the case? The canvas element itself is correctly rendered and displayed but the views don't care about that styling and are still rendered in the top left corner.

**Comment by 1chandu** [comment]
If the question is , how to position your view at an offset (w.r.t to top-left corner), you can specify `x` and `y` (absolute number or %) for your [view](https://deck.gl/#/documentation/deckgl-api-reference/views/view?section=x-string-number-optional-) object
```
      views={[new MapView({ id: 'default-view', x: 25, y: '10%', width: '100%', height: '100%' })]}
```

**Comment by reinvanimschoot** [comment]
That's not the problem. 

The problem is that none of the children of the div with the deckl-wrapper are actually contained inside of it since they are all absolutely positioned.

I want the canvas and the default view to respect the size of the deckgl-wrapper div, not be stuck behind my header with no way of controlling the style.

<img width="1434" alt="Screenshot 2019-10-10 at 20 59 12" src="https://user-images.githubusercontent.com/35171567/66598336-21275a80-eba1-11e9-9895-e97715910872.png">
<img width="1434" alt="Screenshot 2019-10-10 at 20 59 20" src="https://user-images.githubusercontent.com/35171567/66598337-21bff100-eba1-11e9-9c2f-22e7b4fe20b3.png">
<img width="1425" alt="Screenshot 2019-10-10 at 20 59 29" src="https://user-images.githubusercontent.com/35171567/66598338-21bff100-eba1-11e9-8368-7b28c4f5dd67.png">

**Comment by reinvanimschoot** [comment]
Mind you, even when I added width and height to the deck-gl wrapper in the browser, I still need to set both the canvas and the view to relative positioning, which is not something I can seem to do through code.

**Comment by Pessimistress** [comment]
The style of deckgl-wrapper is managed internally. You need to place DeckGL in another div whose style you can control.

**Comment by aaronsamkennedy** [comment]
I tried to do this in our app and it only by changing the positioning to relative in the wrapping div it seems to be breaking our map and resulting in the warning: luma: Device pixel ratio clamped. When we add the wrapper style the deck component seems to break, a map shows up but with no controls, no viewport and not added layers.

```
<div style={{position:'relative'}}> 
      <DeckGL
        layers={renderLayers({ 
          data: getRuns(geo),
          selected:props.selection,
          onHover: hover => _onHover(hover)})}
        getCursor={() => hover.hoveredObject ? 'pointer' : 'default'} 
        initialViewState={INITIAL_VIEW_STATE}
        controller={true}
        onClick={(click) => _onClick(click)}
      >
        <StaticMap 
          mapboxApiAccessToken={MAPBOX_TOKEN}
          mapStyle={MAPBOX_STYLE} />
      </DeckGL>
    </div>```

any idea why the wrapping styling would be breaking the deck component?

**Comment by Pessimistress** [comment]
We can't reproduce this issue from your description. Here are some suggestions:
- Report the deck.gl version that you are using
- Screenshots
- A Code Sandbox example that reproduces your issue

**Comment by aaronsamkennedy** [comment]
I seemed to fix it in our project by constraining the wrapping div with its own height and width instead of its parents but I have it replicated hear if you wanted to see the assertion error it's causing. Probably just a stupid mistake on my part as I'm still getting the grips on DeckGL.  https://codesandbox.io/s/deckgl-c5lg7
