### ISSUE TITLE
Hide overlapping icons when zooming out

### ISSUE THREAD

**Issue by reinvanimschoot** [visgl/deck.gl#3770]
Hi guys

I was wondering if it was possible to have a big set of icons but when zooming out and they overlap, to just not show the ones that are overlapping.

Like in this demo: http://alex3165.github.io/react-mapbox-gl/demos

thanks!

**Comment by 1chandu** [comment]
deck.gl natively doesn't support clustering, but you can check our [demo](https://deck.gl/#/examples/core-layers/icon-layer) and [example code](https://github.com/uber/deck.gl/tree/master/examples/website/icon).
