### ISSUE TITLE
How to handle antimeridian/longitude-wrapping?

### ISSUE THREAD

**Issue by efossvold** [visgl/deck.gl#3794]
If GreatCircleLayer and TripsLayers crosses the antimeridian and the map is viewed at global zoom level horizontal lines are drawn across the entire map. Is there a way to avoid this? I'd rather have the lines exit on one side of the map and "continue" on the opposite side of the map to their destination coordinates.

[![Screenshot from Gyazo](https://gyazo.com/2cda1cfea4baa2b874479ccb23408a9e/raw)](https://gyazo.com/2cda1cfea4baa2b874479ccb23408a9e)
 
[As suggested in](https://github.com/uber/deck.gl/issues/2499#issuecomment-478353476) in #2499 the [Layer.wrapLongitude](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=wraplongitude-boolean-optional-) can be used to wrap longitude though this only works when higher zoom levels. The documentation suggests "preprocess[ing] the data for their best placement". We have a five figured number of objects in a TripsLayer, I'm not exactly sure what kind of preprocessing can be done to avoid the horizontal lines, it really obscures the view when the number lines increases. Any suggestions?

What would help a lot is an option that allowed the developer to choose whether to split the line (as described in the first paragraph) or draw the horizontal line across the map.

**Comment by Pessimistress** [comment]
Starting 8.2 GreatCircleLayer should render correctly out of the box, and TripsLayer should support `wrapLongitude: true`. Report in the above tracker issue if you still experience problems.
