### ISSUE TITLE
[Extension][Brushing] Allow multiple brushing target

### ISSUE THREAD

**Issue by heshan0131** [visgl/deck.gl#3799]
#### Target Usecase
in kepler.gl brushing filters arcs both target and source are in the brushing range. Current [brushing extension api](https://github.com/uber/deck.gl/blob/master/docs/api-reference/extensions/brushing-extension.md) only allows one `brushingTarget`. 

For kepler.gl to using the brushing extension, we will need support for multiple brushing targets

**This currently is a blocker for kepler to upgrade to 7.3 and use the brushing extension**

#### Proposed feature
Option.1 (Simple)
Add `source-target` as a 4th option

Option.2 (Comprehensive)
Allow `brushingTargets` to be a single target or an array of targets: ['source', 'target']

#### To Do List
Let me know what the preferred solution is. Happy to implement it.

**Comment by Pessimistress** [comment]
`brushingTargets` is currently listed  as an enum, so option 1 is probably more aligned with the existing design.

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/pull/4150
