### ISSUE TITLE
Per-object highlightColor

### ISSUE THREAD

**Issue by kevinresol** [visgl/deck.gl#3803]
#### Target Use case

To have different highlight color for different objects.

#### Proposed feature

make `highlightColor` accepts a function: `pickedObject => array`

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
@1chandu

**Comment by danmarshall** [comment]
I would especially like to have this in TextLayer 👍

**Comment by Pessimistress** [comment]
8.1.4
