### ISSUE TITLE
Tilt single arc in ArcLayer

### ISSUE THREAD

**Issue by stoney95** [visgl/deck.gl#3806]
From the ArcLayer-documentation: 

> getTilt (Function|Number, optional) transition-enabled
> Default: 0
> Use to tilt the arc to the side if you have multiple arcs with the same source and target positions. In degrees, can be positive or negative (-90 to +90).

Is there a way to tilt a single arc (Having only one arc with the same source and target position)?

My visualization has a top-view and displaying arcs with a 90° angle is not very eye-pleasing, as can be seen in the screenshot. I also don't want to change the pitch of the visualization because this would cause some major changes I would like to avoid.

![Screenshot 2019-10-22 at 11 35 40](https://user-images.githubusercontent.com/34100018/67274152-2ac59200-f4c0-11e9-9330-77f31ae97ea6.png)

Using deck.gl@6.4.10 in react@16.10.1 application.

**Comment by 1chandu** [comment]
> Is there a way to tilt a single arc

You can, using `getTilt`, you can have angle to tilt per arc in your data and provide function to retrieve that value, it works similar to any other accessor.

data:
```
[ {sourcePosition: ...  tilt: 45..} , {sourcePosition: ... tilt: 0} ...]
```
then set `getTilt: x => x.tilt`.
