### ISSUE TITLE
Getting the filtered values from DataFilterExtension

### ISSUE THREAD

**Issue by samcreate** [visgl/deck.gl#3840]
I'm creating a web app that has `ScatterplotLayer` with the the DataFilterExtension.  To the right of the map I'm showing aggregated stats of what's being filtered. I can't seem to find how I `get` the filtered values from the `DataFilterExtension` instance? 

Example would be:
```javascript
const DataToBeFiltered = [
      { shots: 23, RecordedDateTime: "time stamp here" },
      { shots: 22, RecordedDateTime: "time stamp here" },
      { shots: 5452, RecordedDateTime: "time stamp here" },
      { shots: 4, RecordedDateTime: "time stamp here" },
      { shots: 6, RecordedDateTime: "time stamp here" },
      { shots: 77, RecordedDateTime: "time stamp here" },
      { shots: 89, RecordedDateTime: "time stamp here" },
      { shots: 3, RecordedDateTime: "time stamp here" },
      { shots: 6767, RecordedDateTime: "time stamp here" },
      { shots: 4, RecordedDateTime: "time stamp here" },
    ];
```
Then I create a scatter plot layer that would filter based on the RecordedDateTime field (which to be clear works great... it shows what I'm looking for on the map)
```javascript
const dataFilter = new DataFilterExtension({ filterSize: 1 });
new ScatterplotLayer({
        id: "Outages",
        data,
        opacity: 0.8,
        radiusScale: 100,
        radiusMinPixels: 1,
        wrapLongitude: true,

        getPosition: d => [d.longitude, d.latitude],
        getRadius: d => {
          // console.log(d);
          let num = d.CustomersAffected;
          let len = num.toString().length;
          return Math.pow(2.6, len);
        },
        getFillColor: d => {
          return [228, 101, 93];
        },

        getFilterValue: d => d.RecordedDateTime / MS_PER_DAY, // in days
        filterRange: [filterValue[0], filterValue[1]],
        filterSoftRange: [
          filterValue[0] * 0.9 + filterValue[1] * 0.1,
          filterValue[0] * 0.1 + filterValue[1] * 0.9
        ],
        extensions: [dataFilter],

        pickable: true,
        onHover: this._onHover
      })
```

Afterwards I want to query for all the filtered content and aggregate the total filtered value for 'shots'

Which in this example would be (23+22+5452+4+6+77+89+3+6767+4):
`Shots: 12,447`

How would I gain access to this data?

**Comment by Pessimistress** [comment]
DataFilterExtension performs filtering on the GPU, so no intermediate JavaScript array is generated. You can however just iterate through your data array and check if the time stamp is within your filterRange.

**Comment by samcreate** [comment]
@Pessimistress 
I decided to get things going to do the filtering myself
```javascript
let filteredData = data.filter(
        d => {
          var time = new Date(d.RecordedDateTime).getTime() / MS_PER_DAY;
          return filterDateStart < time && time < filterDateEnd;
        }
      );
```

It would be nice to have an accessor for the filtered data on the DataFilterExtension. Maybe something like [gpu.js ](https://gpu.rocks/)

**Comment by 1chandu** [comment]
@samcreate , which specific API of gpu.js you are referring too.
You can use luma.gl [Transform](https://luma.gl/docs/api-reference/core/transform), but as with any other GPU based library, data has to be GPU friendly format (JS Typed arrays or WebGL Buffer objects), you can have your `Transform `shader filter and output array indices, which you can treat as filtered indices to access actual data elements. Please note this is `WebGL2` only API.
