### ISSUE TITLE
Stacking chips style for overlapping point geometries

### ISSUE THREAD

**Issue by thespencercox** [visgl/deck.gl#3849]
**Use case**: In some cases "Things" such as those that are read by a passive sensor such as an RFID reader will show up at the same physical location.  For example, all vehicles to enter an RFID enabled lot will show up with the location information for that lot, as opposed to their actual parking spot.  In some cases, it's still important to visualize the specific assets as opposed to an aggregation (ie. I want to know which vehicles are there not just how many vehicles are there).

**Potential solutions**: Carto and Leaflet have both partially solved this problem using "stacked chips styling.  See references:

- https://carto.com/blog/stacking-chips-a-map-hack/
- https://github.com/IvanSanchez/Leaflet.Marker.Stack

![stacked-chips](https://user-images.githubusercontent.com/40441410/68324519-c3ddd680-0084-11ea-9238-eb74f13f331b.png)

**Question**: Has anybody explored this style of implementation in deck.gl?  An offset solution could be very computational potentially.  Any suggestions on approach?

**Comment by 1chandu** [comment]
Not the same, but you can use `GridLayer` (you may have to adjust the grid cell size so each location falls to a different grid cell), and by default elevation is proportion to number of points in the cell.

**Comment by thespencercox** [comment]
Thank you @1chandu !  I will look into this.  My suspicion is that this will work for aggregation style use-cases.  I'm not sure exactly how this will enable me to identify the unique features which share an identical location.  Let me see through.
