### ISSUE TITLE
OnHover showing picked: false when hovering over certain parts of the icon

### ISSUE THREAD

**Issue by shanshanzhu** [visgl/deck.gl#3853]
#### Description
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5092813/68349726-fef6fe80-00b2-11ea-95ed-5e4856f13bee.gif)
When hovering on certain part of the icon layer, in the `onHover` callback the `info.picked` is `false` and `info.object` is `undefined`, causing the overlay not showing in the gif (In the example above, it is when mouse is over the bottom right of the icon)

#### Repro Steps
```
const c = new IconLayer({
  pickable: true,
  opacity: 1,
  getSize: DEFAULT_SIZE,
  alphaCutoff: 0,
  autoHighlight: true,
  onHover: (info) => { console.log(info.picked);}
  ...someDataSource
})
```

#### Environment (please complete the following information):
deck.gl@6.4.10
Chrome @78.0.3904.87

#### Logs

**Comment by 1chandu** [comment]
@shanshanzhu,  Is is possible to test with latest deck.gl , `7.3.4` ?

**Comment by DominusVilicus** [comment]
@shanshanzhu seems like it's conflicting with the dialog that comes up. Are you using CSS Opacity to hide it?

**Comment by shanshanzhu** [comment]
> @shanshanzhu, Is is possible to test with latest deck.gl , `7.3.4` ?
I haven't tested in 7.3.4. Is deckgl 6.4 not gonna be supported?

@DominusVilicus We are not using css opacity in the popover. I think the key issue here is in the `onHover` callback passed to the `IconLayer`. When popover is not shown, it is because the `info.picked` is false.

**Comment by Pessimistress** [comment]
@shanshanzhu You may need to set `pointer-events: false` on your popup. Looks like picking fails when you move the pointer over the popup.

**Comment by DominusVilicus** [comment]
Never even knew that existed @Pessimistress :P
