### ISSUE TITLE
PathLayer Should support Clustering

### ISSUE THREAD

**Issue by UttamRahane** [visgl/deck.gl#3859]
#### Target Use case
Pathlayer should support clustering like the clustering we can do for points.

![image](https://user-images.githubusercontent.com/21005702/68470924-11a03d80-0243-11ea-9739-e35fe69540f1.png)

**Comment by Pessimistress** [comment]
You can look for edge bundling libraries such as https://github.com/philogb/mingle

The output can then be rendered with a PathLayee.
