### ISSUE TITLE
PolygonLayer: Incorrect rendering since 7.3 with interleaved position buffers on Linux/Intel/Mesa

### ISSUE THREAD

**Issue by Darune** [visgl/deck.gl#3886]
#### Description
Since the release of the 7.3 the rendering of extruded polygon layer seems broken, 

I'm running a debian on testing, i'm not exactly sure if it's an OS or a code issue.
I have been able to bisect the issue to this commit: 
https://github.com/uber/deck.gl/commit/29ef6338

I see the issue on the following layers from the documentation:
- GeojsonLayer (extruded)
- S2Layer (extruded)
- Buildings

#### Repro Steps
- open the `websites/example/geojson` or https://deck.gl/ as it happens on the buildings as well.
- Here is a screenshot of the rendering since `29ef6338`
![2019-11-14T14:40:24](https://user-images.githubusercontent.com/783455/68862726-40f4f580-06ee-11ea-9d2a-cba048315db4.png)
- when checking out: `6b029761`
rendering of extruded solid polygon is ok:
![2019-11-14T14:41:48](https://user-images.githubusercontent.com/783455/68862851-7bf72900-06ee-11ea-9df2-41c8f9a16348.png)

 
#### Environment:
 - Framework: deck.gl 7.3
 - Browsers: chrome 78.0.3904.97 / Firefox 70
 - OS: Linux [Debian testing]

#### Logs
Nothing in the console

I'm not sure exactly what i should check regarding my OS to provide more information let me know what I can to do help.

**Comment by Pessimistress** [comment]
@tsherif @1chandu The breaking commit introduced one interleaved buffer for both `positions` and `positions64xyLow`. Somehow this is not interpreted correctly by the vertex shader?

**Comment by Pessimistress** [comment]
@Darune @vykintazo can you go to `chrome://gpu/` in Chrome and share your report?

**Comment by vykintazo** [comment]
Data exported | 2019-11-18T07:17:06.785Z
-- | --
Chrome version | Chrome/78.0.3904.97
Operating system | Linux 5.0.0-36-generic
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/021b9028c246d820be17a10e5b393ee90f41375e/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/021b9028c246d820be17a10e5b393ee90f41375e/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 66e0feec40dc
2D graphics backend | Skia/78 a40a8a58755f952280cac9dfdcbf761aa7d29a52
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --ignore-gpu-blacklist --flag-switches-end

**Comment by Darune** [comment]
```

Data exported | 2019-11-18T09:10:42.971Z
-- | --
Chrome version | Chrome/78.0.3904.97
Operating system | Linux 5.2.0-3-amd64
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/021b9028c246d820be17a10e5b393ee90f41375e/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/021b9028c246d820be17a10e5b393ee90f41375e/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 66e0feec40dc
2D graphics backend | Skia/78 a40a8a58755f952280cac9dfdcbf761aa7d29a52
Command Line | /usr/bin/google-chrome --flag-switches-begin --force-dark-mode --high-dpi-support=1 --force-device-scale-factor=2 --enable-gpu-rasterization --enable-quic --enable-zero-copy --enable-native-gpu-memory-buffers --flag-switches-begin --flag-switches-end
```
I tried removing all the gpu related switches (`--high-dpi-support=1 --force-device-scale-factor=2 --enable-gpu-rasterization --enable-quic --enable-zero-copy --enable-native-gpu-memory-buffers`) and noted same behavior.

**Comment by Darune** [comment]
I had some time to dig into this a bit more today. 
I don't have any experience on WebGL nor OpenGL programming, there is a high probality that my mental model of how things work is totally wrong.

I realized that only the side polygons were having the rendering issue top polygons were looking fine.

So from my understanding of the change of the commit, is that we now automatically add the `64xyLow` vec2 for every coordinates.

Is it possible that those "added" attributes conflict with the `nextPositions` attributes of the `solid-polygon-layer-side` vertex ? 

changing the vertex shader attribute definition to this:
```
attribute vec3 nextPositions;
attribute vec2 nextPositions64xyLow;
attribute vec3 instancePositions;
attribute vec2 instancePositions64xyLow;
attribute float instanceElevations;
attribute vec4 instanceFillColors;
attribute vec4 instanceLineColors;
attribute vec3 instancePickingColors;
```
moved `nextPositions(64xyLow) to the top

Fixes the issue for me, but i'm not sure I understand why.
- Aren't attribute bound to their names ? 
- Is `nextPositions` `positions` with an `offset` of `12` ?
- Why is this OS related ? 

I could not try on other OS but it seems to work on mine. 
I noticed some "aliasing" on some dropped shadow thou, not sure if this is a regression due to my change

- Is this an acceptable solution ?
- Could someone on another Linux try this patch ?

**Comment by Darune** [comment]
I had some time to dig into this a bit more today. 
I don't have any experience on WebGL nor OpenGL programming, there is a high probality that my mental model of how things work is totally wrong.

I realized that only the side polygons were having the rendering issue top polygons were looking fine.

So from my understanding of the change of the commit, is that we now automatically add the `64xyLow` vec2 for every coordinates.

Is it possible that those "added" attributes conflict with the `nextPositions` attributes of the `solid-polygon-layer-side` vertex ? 

changing the vertex shader attribute definition to this:
```
attribute vec3 nextPositions;
attribute vec2 nextPositions64xyLow;
attribute vec3 instancePositions;
attribute vec2 instancePositions64xyLow;
attribute float instanceElevations;
attribute vec4 instanceFillColors;
attribute vec4 instanceLineColors;
attribute vec3 instancePickingColors;
```
moved `nextPositions(64xyLow) to the top

Fixes the issue for me, but i'm not sure I understand why.
- Aren't attribute bound to their names ? 
- Is `nextPositions` `positions` with an `offset` of `12` ?
- Why is this OS related ? 

I could not try on other OS but it seems to work on mine. 
I noticed some "aliasing" on some dropped shadow thou, not sure if this is a regression due to my change

- Is this an acceptable solution ?
- Could someone on another Linux try this patch ?

**Comment by 1chandu** [comment]
Re-arranging the attribute definitions in the vertex shader shouldn't make any difference in the final rendering, I wonder if this is an issue with GPU driver (compiler part).

**Comment by tsherif** [comment]
@vykintazo @Darune could you send screen shots of the "Problems Detected" section as well as the entries for GL_VENDOR, GL_RENDERER, GL_VERSION.

I have seen issues before where the order of inputs into the shaders affects behavior, in particular if there are unused attributes. There two things I'd like to investigate as culprits if we can repro:
- attributes only referenced in unused paths in the vertex shader
- heavy reliance on disable (constant) attributes

**Comment by tsherif** [comment]
Another Linux issue was reported here: #3908 

That one is on Ubuntu 19.04, Intel UHD 620, Mesa 19.0.8

**Comment by Darune** [comment]
I saw the issue, I have very bad performance as well,  I tried running the
the demo app using my modified deck.gl to see if the performance issues are
linked to very big polygons but didn't manage to run it.

So I can't yet say if this problem is related or not. I will try again
tomorrow.

Le jeu. 21 nov. 2019 à 23:45, Tarek Sherif <notifications@github.com> a
écrit :

**Comment by Darune** [comment]
@tsherif, here are the requested screenshots: 
![2019-11-22T12:26:35](https://user-images.githubusercontent.com/783455/69422197-6489f280-0d23-11ea-89fa-9c9f16ca9efb.png)
![2019-11-22T12:25:58](https://user-images.githubusercontent.com/783455/69422199-65228900-0d23-11ea-8a5a-515f89697d4d.png)


full html file
https://drive.google.com/file/d/10xBa1gP1gsJVVuwttWGYoGlOnJC5lANW/view

**Comment by tsherif** [comment]
Perfect, thanks @Darune. This is confirming my suspicions that it's related to Intel GPUs/Mesa drivers.

I'm able to repro in Ubuntu 16.04 when I switch to the Intel GPU (Intel HD 530, Mesa 18.0.5), and it works fine when I'm on the Quadro M1000. 

I'm interested in the workaround "Mesa drivers in Linux handle varyings without static use incorrectly" (Full bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=333885 ). I suspect our issue has to do with packing which would explain why reordering attributes makes a difference. And our shaders include a lot of code paths with variables that are statically referenced but not used.

**Comment by tsherif** [comment]
@Pessimistress a couple of things I want to try: 
- Strip down the PolygonLayer shaders to only include attributes/uniforms/varyings that are used for the draw.
- Replace disabled attributes for uniforms or in-shader defines.

If either of those resolves the issue, I'd say the issue is related to variable packing.

We should also file bugs with Chrome and FF:
https://bugs.chromium.org/p/chromium/issues/list
https://bugzilla.mozilla.org/buglist.cgi?product=Core&component=Canvas%3A%20WebGL&resolution=---

**Comment by vykintazo** [comment]
I am a bit late, but still adding screenshots of mine report, they are a bit different:
![image](https://user-images.githubusercontent.com/13200352/69432644-c3ab2f80-0d42-11ea-864d-0a75e9a447b7.png)
![image](https://user-images.githubusercontent.com/13200352/69432832-17b61400-0d43-11ea-8f86-972453edb8d2.png)

**Comment by Darune** [comment]
I have no other GPU on this laptop, i have one on another computer but i'm not sure the state of its linux partition.
I'll give it a try once at home and let you know. 

I'm not sure how I can help more on this issue, I'm afraid i'm not experienced enough in WebGL to simplify this issue to a more simple test case for chrome / FF issue board.

**Comment by Algirdyz** [comment]
Same problem here. This is a rather big issue for us since we run some visualizations on an Intel NUC PCs running linux in production environment and we got the same rendering error after recent update. Had to downgrade. 

Any ETAs or planing on this bug?

**Comment by tsherif** [comment]
@Algirdyz No ETA, but I will be focusing on this issue later this week. I'll continue to update here as I get a clearer picture of what's going on.

**Comment by Pessimistress** [comment]
A temporary fix is published in 7.3.7, can folks give it a try?

**Comment by Darune** [comment]
the homepage is fixed for me thank you for applying this temporary patch

**Comment by vykintazo** [comment]
Same for me. Homepage looks fine now, as well as my project, thanks!

**Comment by Algirdyz** [comment]
It works great thanks!
