### ISSUE TITLE
Weird parallax / scaling behavior

### ISSUE THREAD

**Issue by kaseymccurdy** [visgl/deck.gl#3887]
Hi there! I was so excited to learn about the ability to put Deck and Mapbox in the same canvas context for a number of reasons. After implementing the approach in the docs [this post](https://medium.com/vis-gl/deckgl-and-mapbox-better-together-47b29d6d4fb1), i found that it seems the mapbox layer is "zoomed" in more than my deckgl layer...

![Screen Recording 2019-11-14 at 8 31 18 AM 2019-11-14 08_46_27](https://user-images.githubusercontent.com/45602551/68872450-4b49cc00-06bb-11ea-9525-fffda6fc1339.gif)

In addition, I've noticed a few other quirks:
- Transitions (FlyTo) dont seem to work
- Opacity on scatterplot layers

If anyone has any direction to point me in, I'd really appreciate it...thank you!

--- 

The implementation of my components:
```
import { StaticMap } from 'react-map-gl';
import DeckGL from '@deck.gl/react';
...
    const map = mapRef.current.getMap();
    const deck = deckRef.current;
    map.addLayer(new MapboxLayer({ id: 'deck-stuff', deck }));
...
      <DeckGL
        initialViewState={mapViewport}
        controller={true}
        onViewStateChange={handleViewStateChange}
        layers={getLayers()}
        useDevicePixels={false}
        ref={(ref) => { deckRef.current = ref && ref.deck; }}
        onWebGLInitialized={handleWebGLInitialized}
      >
        {webGLContext && (
          <StaticMap
            ref={(ref) => { mapRef.current = ref; }}
            mapboxApiAccessToken={mapboxApiAccessToken}
            mapStyle={mapStyle}
            preventStyleDiffing
            onLoad={handleMapLoaded}
            reuseMaps
            preserveDrawingBuffer
            gl={webGLContext.gl}
          />
        )}
      </DeckGL>
```

and here's what my map viewport object looks like:
```
Formatted JSON Data
{ 
   "width":1440,
   "height":694,
   "latitude":40.00929265067086,
   "longitude":-105.12338640756488,
   "zoom":9.692802919210216,
   "bearing":0,
   "pitch":0,
   "altitude":1.5,
   "maxZoom":14,
   "minZoom":0,
   "maxPitch":60,
   "minPitch":0,
   "position":[ 
      0,
      0,
      0
   ]
}
```

**Comment by Pessimistress** [comment]
@kaseymccurdy What are the versions of your mapbox-gl and deck.gl?

**Comment by kaseymccurdy** [comment]
```
    "@deck.gl/aggregation-layers": "^7.3.6",
    "@deck.gl/core": "^7.3.6",
    "@deck.gl/layers": "^7.3.6",
    "@deck.gl/mapbox": "7.3.6",
    "@deck.gl/react": "^7.3.6",
    "react-map-gl": "5.0.10",
    "mapbox-gl": "1.2.1",
```

**Comment by Pessimistress** [comment]
I can't see any obvious issue with your code other than you are using react ref incorrectly (you should set `ref={mapRef}` instead of callback function if you choose to use `React.createRef()`). Mapbox's `addLayer` sometimes silently fails so it's hard to pin down the problem.

I put together a code sandbox example: https://codesandbox.io/s/deckgl-mapbox-layers-interleve-651q1

**Comment by Sitong2014** [comment]
> ```
>     "@deck.gl/aggregation-layers": "^7.3.6",
>     "@deck.gl/core": "^7.3.6",
>     "@deck.gl/layers": "^7.3.6",
>     "@deck.gl/mapbox": "7.3.6",
>     "@deck.gl/react": "^7.3.6",
>     "react-map-gl": "5.0.10",
>     "mapbox-gl": "1.2.1",
> ```



> 嗨，您好！出于多种原因，我很高兴了解将Deck和Mapbox置于同一画布上下文中的能力。在实现本文的文档中的方法[之后](https://medium.com/vis-gl/deckgl-and-mapbox-better-together-47b29d6d4fb1)，我发现似乎mapbox层比我的deckgl层“放大了”。
> 
> ![屏幕录像2019-11-14 at 8 31 18 AM 2019-11-14 08_46_27](https://user-images.githubusercontent.com/45602551/68872450-4b49cc00-06bb-11ea-9525-fffda6fc1339.gif)
> 
> 此外，我还注意到了其他一些怪癖：
> 
> * 转场（FlyTo）似乎不起作用
> * 散点图图层上的不透明度
> 
> 如果有人有任何指示要指向我的方向，我将非常感谢...谢谢！
> 
> 我的组件的实现：
> 
> ```
> import { StaticMap } from 'react-map-gl';
> import DeckGL from '@deck.gl/react';
> ...
>     const map = mapRef.current.getMap();
>     const deck = deckRef.current;
>     map.addLayer(new MapboxLayer({ id: 'deck-stuff', deck }));
> ...
>       <DeckGL
>         initialViewState={mapViewport}
>         controller={true}
>         onViewStateChange={handleViewStateChange}
>         layers={getLayers()}
>         useDevicePixels={false}
>         ref={(ref) => { deckRef.current = ref && ref.deck; }}
>         onWebGLInitialized={handleWebGLInitialized}
>       >
>         {webGLContext && (
>           <StaticMap
>             ref={(ref) => { mapRef.current = ref; }}
>             mapboxApiAccessToken={mapboxApiAccessToken}
>             mapStyle={mapStyle}
>             preventStyleDiffing
>             onLoad={handleMapLoaded}
>             reuseMaps
>             preserveDrawingBuffer
>             gl={webGLContext.gl}
>           />
>         )}
>       </DeckGL>
> ```
> 
> 这是我的地图视口对象的样子：
> 
> ```
> Formatted JSON Data
> { 
>    "width":1440,
>    "height":694,
>    "latitude":40.00929265067086,
>    "longitude":-105.12338640756488,
>    "zoom":9.692802919210216,
>    "bearing":0,
>    "pitch":0,
>    "altitude":1.5,
>    "maxZoom":14,
>    "minZoom":0,
>    "maxPitch":60,
>    "minPitch":0,
>    "position":[ 
>       0,
>       0,
>       0
>    ]
> }
> ```

Brother, have you solved the problem？

**Comment by kaseymccurdy** [comment]
for right now...i just have it in two webGL contexts :( im going to try some things when i get availability and will report back...

**Comment by Pessimistress** [comment]
@Sitong2014 @kaseymccurdy It would help us diagnose the issue if you can put together a code sandbox that reproduces this issue.

If you see the same issue on the link in my previous comment, please report your OS and `devicePixelRatio`.
