### ISSUE TITLE
onZoomStart & onZoomEnd

### ISSUE THREAD

**Issue by SymbolixAU** [visgl/deck.gl#3890]
#### Target Use case

To improve performance when map layers are re-drawn every time the zoom level changes. With `onZoomEnd` we can wait until zooming has finished before re-drawing layers, rather than continuously during the zoom.

#### Proposed feature
`onZoomStart` and `onZoomEnd` [event callbacks](https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#event-callbacks), similar to the current `onDragStart` and `onDragEnd`

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Wheel events are unfortunately discrete, so we can't reliably tell when it "ends" without employing an arbitrary delay (similar to how we handle "single click"). The `HeatmapLayer` implements a debounced update when zoom changes.

**Comment by dcooley** [comment]
ok that makes sense. Is [this](https://github.com/uber/deck.gl/blob/9d962900add82cc8f6b9666d6c1136396de361a3/modules/aggregation-layers/src/heatmap-layer/heatmap-layer.js#L491) the debounced update you're referring to?

**Comment by abouroubi** [comment]
That would be a great feature why is it closed ?
If it was already implemented on the single click, why not use it for the zoom ?

**Comment by vaduga** [comment]
here's a sample onViewStateChange handler that implements zoom end action with a delay. 
*Using refs make rendering faster than useState.

const timerRef = useRef(null);

  const viewStateChanger = (c) => {
    const [lng, lat] = [c.viewState.longitude, c.viewState.latitude];
    const zoom = c.viewState.zoom;

    if (c.interactionState.isZooming) {
      clearInterval(timerRef.current);
      timerRef.current = setTimeout(() => {

// dosomething

      }, 200);
    }
