### ISSUE TITLE
3D Buildings Artefacts in new version

### ISSUE THREAD

**Issue by zoh** [visgl/deck.gl#3896]
I use ArchLinux, Firefox,  double GPU, and I see this:

![2019-11-17-225142_2560x1440_scrot](https://user-images.githubusercontent.com/1598229/69013431-abc55b80-0990-11ea-909c-bcf755c7d6c4.png)

I thing it  depends on the lightnings, but how I may fix it?

**Comment by vykintazo** [comment]
There's another isue on this problem too: #3886
It seems to be linux specific bug in a new version.
I'm also experiencing the same issue on Kubuntu 19.04, Chrome 78.0.3904.97 and Firefox 70.0.1

The worst thing is that this behaviour is also present on homepage of https://deck.gl and causes browser to almost freeze (1 - 3 FPS on live demo there), so I was having trouble navigating there.

**Comment by tsherif** [comment]
This looks like position attributes (or indices) being read as 0. Are either of you getting any errors in the console?

**Comment by vykintazo** [comment]
> This looks like position attributes (or indices) being read as 0. Are either of you getting any errors in the console?

Nope.
