### ISSUE TITLE
The deck.gl page on Firefox 70 and Chrome 78 on Ubuntu 19.04 is very slow

### ISSUE THREAD

**Issue by parrotcar00** [visgl/deck.gl#3908]
#### Description

The deck.gl page on latest Firefox 70 on Ubuntu 19.04 is very slow. I'm seeing 3 FPS rates on the deck.gl page. I see same slowness on Chrome latest on 

I don't see this happening on MacOS. Not sure what is the cause behind this performance difference.

#### Repro Steps

Open deck.gl page on latest Firefox/Chrome on Ubuntu 19.04.

#### Environment (please complete the following information):
 - deck.gl webpage
 - Firefox 70 / Chrome 78
 - Ubuntu 19.04

**Comment by tsherif** [comment]
Hi, could you navigate to `chrome://gpu` in Chrome, copy everything from that page into a plain text file and attach it to this issue?

**Comment by parrotcar00** [comment]
`

Data exported | 2019-11-21T20:12:03.705Z
-- | --
Chrome version | Chrome/78.0.3904.108
Operating system | Linux 5.3.0-20-generic
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/4b26898a39ee037623a72fcfb77279fce0e7d648/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/4b26898a39ee037623a72fcfb77279fce0e7d648/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | 0cc6d390272a
2D graphics backend | Skia/78 dba5c993df3fb95fed01f8131aa0401e83c9198f
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end

`

**Comment by parrotcar00** [comment]
I've attached the chrome://gpu output above ^ in gpu.txt.

**Comment by tsherif** [comment]
Thanks! We're tracking another Linux-related issue here: #3886. Can you see if you see a similar problem with your setup?

**Comment by parrotcar00** [comment]
![screenshot](https://user-images.githubusercontent.com/48635114/69383171-f4c62a00-0c86-11ea-9c73-71efa9588b45.png)

Looks like the same or similar problem. I'm attaching the deck.gl screenshot as it looks on my computer. Looking at the other thread, looks like they were seeing a similarly broken image?

**Comment by tsherif** [comment]
Yeah, I'll test on my own Linux machine later today. And we'll see if they report having a similar GPU to yours.

**Comment by MiklerGM** [comment]
Same problem, Chrome 80, KDE

**Comment by Pessimistress** [comment]
Related issue was fixed in 7.3. Please open a new issue if this is still a problem on the latest release.
