### ISSUE TITLE
Does characterSet prop of the TextLayer not support utf-8 ？

### ISSUE THREAD

**Issue by wlfei0502** [visgl/deck.gl#3909]
Background：
1、Characters are not predicatable.  
2、Language is chinese.

**Comment by The-End-Hero** [comment]
I have the same problem

**Comment by wlfei0502** [comment]
> I have the same problem

Now， I get all characters of every layer. But the Performance is too low.

**Comment by xintongxia** [comment]
I'll look into this issue.

**Comment by Pessimistress** [comment]
This should be fixed in 8.1.3

https://github.com/visgl/deck.gl/issues/4434

**Comment by fifzteen** [comment]
I have the same problem too.

This issue has been closed as fixed at #4434
Then, how we can draw utf-8 characters on TextLayer?

Characters to use are still not predictable, so need to set ALL utf-8 characters to characterSet...?

**Comment by fifzteen** [comment]
I found the opinion about this problem in the discussion below, sorry.
https://github.com/visgl/deck.gl/discussions/5227
