### ISSUE TITLE
GeoJSON layer with polyline goes the wrong way round the world when crossing antemeridian

### ISSUE THREAD

**Issue by lukemcgregor** [visgl/deck.gl#3915]
#### Description
If you have a GEOJson layer with a path that crosses the antemeridian you can sometimes get a line crossing the entire map. This seems to be joining two points which are close together but on opposite sides of the antemeridian.

![image](https://user-images.githubusercontent.com/1284608/69376287-e91e4600-0d0e-11ea-8dec-3c7386e8c7e0.png)

#### Repro Steps
Create a GeoJSON feature with a multiline string crossing the antemeridian (example in codepen below) move map left and right to see the artefact appearing and disappearing 
- https://codepen.io/lukemcgregor/pen/wvvZwjg

Expected: the lines are only linked across the antemeridian
Actual: the lines are linked the other/long way round the globe

NOTE: This also seems to happen with paths that cross the left/right borders of the map when the path crosses the map at +/-180 centerpoint of the map eg when half the path is drawn on one side, and half on the other side.

#### Environment (please complete the following information):
 - deckGL: 7.3.6 (not sure of the version in codepen)
 - Chrome 78.0.3904.108 
 - OSX 10.15.1

#### Logs
N/A

**Comment by FernandaCG** [comment]
Hi, can I work on this??

**Comment by lukemcgregor** [comment]
Id love you to solve this if you can :D

**Comment by Pessimistress** [comment]
With v8.2 you can use `wrapLongitude: true` on the GeoJsonLayer to handle this.
