### ISSUE TITLE
How to select pointClouds with bounding-box?

### ISSUE THREAD

**Issue by zt123123** [visgl/deck.gl#3929]
I want to use `pickObjects` to implement a box selection point cloud and highlight the selected area, but now I have two problems. First, when I use `pickObjects`, I pass in the `x` and `y` parameter of the `onClick` callback function. Then, no matter how I change the `width` and `height` parameters, it always returns an array of length one. In fact, I expect to return a series of points. Secondly, I hope to highlight the point cloud in the selected area. I have not found a way to achieve it. My code is as follows:
```js
    const handleClick = (info, event) => {
      const { x, y } = info;
      const pickInfo = info.layer.context.deck.pickObjects({
        x, y, width: 1000, height: 1000, layerIds: ['point-cloud-layer'],
      });
      console.log(pickInfo);
    };

    const pointCloudLayer = new MapboxLayer({
      id: 'point-cloud-layer',
      type: PointCloudLayer,
      pickable: true,
      onClick: handleClick,
      ...
    });
```
The result like this
![image](https://user-images.githubusercontent.com/18349295/69509615-a8c00180-0f74-11ea-94ef-8e43ef785492.png)

I look forward to receiving a reply, thank you very much.

**Comment by xintongxia** [comment]
Are you using deck.gl's [`PointCloudLayer`](https://deck.gl/#/documentation/deckgl-api-reference/layers/point-cloud-layer)?

**Comment by zt123123** [comment]
@xintongxia  I  am using Mapbox as my project main framework, but it does not support well for pointCloud. so, I use deck.gl's PointCloudLayer to render data, but I need to add the layer to Mapbox. In fact, MapboxLayer is an implementation of mapbox's custom layer API.  As the official website example
```js
import {MapboxLayer} from '@deck.gl/mapbox';
import {ScatterplotLayer} from '@deck.gl/layers';

const map = new mapboxgl.Map({...});

const myScatterplotLayer = new MapboxLayer({
    id: 'my-scatterplot',
    type: ScatterplotLayer,
    data: [
        {position: [-74.5, 40], size: 100}
    ],
    getPosition: d => d.position,
    getRadius: d => d.size,
    getColor: [255, 0, 0]
});

// wait for map to be ready
map.on('load', () => {
    // add to mapbox
    map.addLayer(myScatterplotLayer);

    // update the layer
    myScatterplotLayer.setProps({
      getColor: [0, 0, 255]
    });
}
```
I just change the type to PointCloud. I have tried, if I new a pointCloud instance and set onClick callback, the pickObjects return a series of points, it seems to work well.
