### ISSUE TITLE
About serration of the ScatterPointLayer

### ISSUE THREAD

**Issue by wlfei0502** [visgl/deck.gl#3936]
#### Target Use case
More smoother border of the point is better。

#### Proposed feature
I compare Mapbox.gl to Deck.gl on drawing point.  The Mapbox.gl draws more smoother  than the Deckgl.  Here is the result:

Mapbox.gl:
![Mapbox.gl](https://github.com/wlfei0502/learning_materials/blob/master/images/mapbox.gl.png?raw=true)

Deck.gl:
![Deck.gl](https://github.com/wlfei0502/learning_materials/blob/master/images/deck.gl.png?raw=true)

#### Code
**deck.gl**
```
const deckgl = new deck.DeckGL({
  container: 'container',
  mapboxApiAccessToken: 'pk.eyJ1Ijoid2xmZWkiLCJhIjoiY2puMTB6MXZlNHZjcTNwbnl3dnowYjhoaSJ9.s6ZkjRHGIY6xVNBRAf52MQ',

  initialViewState: {
    latitude: 51.47,
    longitude: 0.45,
    zoom: 4,
    bearing: 0,
    pitch: 0,
  },
  controller: true,

  layers: [
    new deck.GeoJsonLayer({
      id: 'airports',
      data: AIR_PORTS,
      // Styles
      filled: true,
      pointRadiusMinPixels: 20,
      pointRadiusScale: 20,
      getRadius: f => (11 - f.properties.scalerank),
      getFillColor: [255, 140, 0, 255],
	  lineWidthMinPixels:2,
	  lineWidthMaxPixels:2,
	  getLineColor: [200, 0, 80, 255],
      // Interactive props
      pickable: true,
      autoHighlight: true,
    })
  ],
});
```

**mapbox.gl**
```
const map = deckgl.getMapboxMap();


map.on('load', function () {
	// The data option must be replaced by the content of the geojson. Here is only tip.
	map.addSource('point', {type:'geojson', data:'https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_10m_airports.geojson'});
	 
	map.addLayer({
		"id": "point",
		"source": "point",
		"type": "circle",
		"paint": {
			"circle-radius": 20,
			"circle-color": "rgb(255, 140, 0)",
			"circle-stroke-width":2,
			"circle-stroke-color":"rgb(200, 0, 80)",
		}
	});
});
```

**Comment by Pessimistress** [comment]
What is your device pixel ratio? Try set `useDevicePixels: 2` on Deck.

**Comment by wlfei0502** [comment]
My device pixel ratio is 1.5

**Comment by Pessimistress** [comment]
> Can the deck.gl not recognize device pixel ratio by itself 

deck.gl uses `window.devicePixelRatio` by default. You can try manually increasing it and see if it reduces the artifact.

**Comment by wlfei0502** [comment]
> > Can the deck.gl not recognize device pixel ratio by itself
> 
> deck.gl uses `window.devicePixelRatio` by default. You can try manually increasing it and see if it reduces the artifact.
Thanks a lot. Set `useDevicePixels: 2 ` is very effective.
