### ISSUE TITLE
Text rendering is blurry

### ISSUE THREAD

**Issue by ibesora** [visgl/deck.gl#3966]
#### Description
I'm using deck.gl to render an overlay on top of GoogleMaps (via GoogleMapsOverlay) but I find the rendered text is quite blurry compared with what Chrome is doing natively.

Check the following images to see a comparison.
deck.gl 1x ![deckglx1](https://user-images.githubusercontent.com/2301378/70235808-f2be9980-1763-11ea-97ae-e944f3ca7b9f.png)
Chrome 1x ![chromex1](https://user-images.githubusercontent.com/2301378/70235815-f6522080-1763-11ea-8e51-7f51265f150a.png)
deck.gl 2x ![deckglx2](https://user-images.githubusercontent.com/2301378/70235834-ffdb8880-1763-11ea-8f79-72df82841b08.png)
Chrome 2x ![chromex2](https://user-images.githubusercontent.com/2301378/70235838-036f0f80-1764-11ea-8c77-f34c4fdea3bc.png)

I'm creating the TextLayer with the following parameters:
```javascript
new TextLayer({
      id: `text-${radius}`,
      data: featureLayers[key],
      getText: d => d.text,
      getPosition: d => d.position,
      getColor: [255, 255, 255, 255],
      fontWeight: 600,
      fontFamily: 'Josefin Sans',
      getSize: textSize,
      sizeMinPixels: textSize,
      sizeMaxPixels: textSize,
      getTextAnchor: 'middle',
      getAlignmentBaseline: 'center'
})
```
Tried using the [fontSettings](https://github.com/uber/deck.gl/blob/master/docs/layers/text-layer.md#fontsettings-object-optional) attribute with `sdf: true` and `fontSize: 256` but there's no appreciable change

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.3.3
 - Browser Version:  Chrome 78.0.3904.108
 - OS: Ubuntu 18.04.3 LTS

**Comment by danmarshall** [comment]
Take a look at the `fontSettings` object's `fontSize` property. https://deck.gl/#/documentation/deckgl-api-reference/layers/text-layer?section=fontsettings-object-optional-

**Comment by ibesora** [comment]
Mmmm yeah, as I said in the original message I've tried incrementing that to 4 times it's default value but there's no apreciable change 🙄

**Comment by udameli** [comment]
Have you tried setting up the opacity to 1 manually? The default opacity was [previously set to 0.8. for v < 8](https://github.com/uber/deck.gl/pull/3879) Sharper contrast between fully opaque text and fully opaque background should make text rendering less blurry. That worked for me :)

**Comment by dquang-tran** [comment]
The rendered circles are also blurry. I don't have text for my use case but I have the same blurriness issue with Scatterplot as your screenshot

**Comment by Pessimistress** [comment]
You can try set `useDevicePixels: 2` on `Deck`/`GoogleMapsOverlay`

**Comment by Pessimistress** [comment]
Possibly related to https://github.com/visgl/deck.gl/issues/4910
