### ISSUE TITLE
Triggering a recheck of data changing?

### ISSUE THREAD

**Issue by josh-byster** [visgl/deck.gl#3975]
Hi, 
I've been interested in trying to cleanly trigger a refresh of some of the data points when using `IconLayer`. For example, I have a map where when I hover over an icon, I want to change the icon color. Currently, the only way I can see achieving this is to, in the `onHover` handler, `setState` to a shallow copy of the entire dataset, i.e. `myData: [...prevState.myData]`. However, this doesn't seem like the most efficient solution for large datasets to have to do this copy each time I want to change an attribute of one data point on one layer. I noticed that `getIcon` does a shallow equality check in order to determine if it needs to re-render icons, and it does so for every single icon on the map. Is this something I should be noticeably concerned about in terms of performance? Is there any better way to handle this use case?

**Comment by Pessimistress** [comment]
You may want to try `dataComparator` and `_dataDiff`: https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=_datadiff-function-optional-experimental

**Comment by MehdiSaffar** [comment]
@josh-byster I can say that `_dataDiff` is the way to go. I have a large number of data points (> 100k) and I have a tool that updates the value of these data points. since the tool is localized (like radius within 100m), it doesn't touch all the points. with _dataDiff I can say exactly which nodes have been updated.

**Comment by pai-qi** [comment]
> @josh-byster I can say that `_dataDiff` is the way to go. I have a large number of data points (> 100k) and I have a tool that updates the value of these data points. since the tool is localized (like radius within 100m), it doesn't touch all the points. with _dataDiff I can say exactly which nodes have been updated.

 _dataDiff must work together with dataComparator, am I right ?
