### ISSUE TITLE
ScatterplotLayer to support "billboard"

### ISSUE THREAD

**Issue by cosullivan** [visgl/deck.gl#4108]
#### Target Use case
We are using a CompositeLayer that contains an IconLayer, TextLayer and ScatterplotLayer and wish for all sublayers to face the camera. 

#### Proposed feature
ScatterplotLayer to support the "billboard" mode that IconLayer, TextLayer, and PathLayer support.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by karanisverma** [comment]
@Pessimistress I would like to work on this! Please let me know if no one is working on this issue :)

**Comment by Pessimistress** [comment]
@karanisverma go ahead! You can check the IconLayer vertex shader to see how billboarding is implemented: https://github.com/visgl/deck.gl/blob/43d685134ea052d7190cb55b058c881391ff1b7a/modules/layers/src/icon-layer/icon-layer-vertex.glsl.js#L80

**Comment by karanisverma** [comment]
> @karanisverma go ahead! You can check the IconLayer vertex shader to see how billboarding is implemented:
> 
> https://github.com/visgl/deck.gl/blob/43d685134ea052d7190cb55b058c881391ff1b7a/modules/layers/src/icon-layer/icon-layer-vertex.glsl.js#L80

Thanks! Will raise a PR as soon as possible

**Comment by Pessimistress** [comment]
This is available in 8.5.0.
