### ISSUE TITLE
how to light the line?

### ISSUE THREAD

**Issue by xkm0228** [visgl/deck.gl#4155]
i want to create the line  that  shows like  as
![image](https://user-images.githubusercontent.com/24645864/72411025-e71fb300-37a4-11ea-95b7-6457fb416708.png)
it looks like light ,how can i do in trips layer . by now ，i has no idea.  please help me ....

**Comment by Pessimistress** [comment]
You can look into [PostProcessEffect](https://deck.gl/docs/api-reference/core/post-process-effect).
