### ISSUE TITLE
Animating Icon Layer

### ISSUE THREAD

**Issue by sambaskin** [visgl/deck.gl#4199]
I'm trying to visualize car trip data, and I want to use a moving icon to represent each car.
I haven't been able to find any examples where icons move, so I figured that the best way forward would be to modify either the existing trip or icon layer.  
I know that the trips layer works by just adjusting the shading on a normal path layer over time, so I think the best bet would be modifying the icon layer. 
Is there a way to consistently change the getPosition attribute in the icon layer over time?

**Comment by Foosballfan** [comment]
Hi @sambaskin , just add this property `transitions: { getPosition: { duration: 100 } }` or for JSX `transitions={{ getPosition: { duration: 100 } }}`

**Comment by sambaskin** [comment]
Thanks! I should add that in the icon layer javascript file, right? If so, where in the file should I add that property?

**Comment by Foosballfan** [comment]
In the icon layer parameters

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sambaskin** [comment]
Here's my default props section in icon-layer.js after adding that property in. Does this seem right?
I think I'm confused about where I would actually add in the location data that is used to tell the icon where to move.

`const defaultProps = {
  iconAtlas: null,
  iconMapping: {type: 'object', value: {}, async: true},
  sizeScale: {type: 'number', value: 1, min: 0},
  fp64: false,
  billboard: true,
  sizeUnits: 'pixels',
  sizeMinPixels: {type: 'number', min: 0, value: 0}, //  min point radius in pixels
  sizeMaxPixels: {type: 'number', min: 0, value: Number.MAX_SAFE_INTEGER}, // max point radius in pixels
  transitions: { getPosition: { duration: 100 } },
  getPosition: {type: 'accessor', value: x => x.position},
  getIcon: {type: 'accessor', value: x => x.icon},
  getColor: {type: 'accessor', value: DEFAULT_COLOR},
  getSize: {type: 'accessor', value: 1},
  getAngle: {type: 'accessor', value: 0}
};
`

**Comment by Foosballfan** [comment]
Hopefully they'll invest some time in documenting the transitions so we have a clearer picture of what works.
Right now I'm just scouring the net for any examples.

**Comment by sambaskin** [comment]
Here's two things I've found:
The [docs discussing layer transitions](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=transitions-object-optional-), [and one example with radius in a scatter plot layer](https://github.com/uber/deck.gl/issues/2720). 
Maybe I could use enter => to access a function which returns the next value stored in a dataset? 
Also, thank you for your help with this! I really appreciate it

**Comment by sambaskin** [comment]
[Here's something else](https://github.com/uber/deck.gl/issues/1810)
Maybe the icon layer isn't supported by transitions?

**Comment by danias** [comment]
@Foosballfan Foosballfan `transitions: { getPosition: { duration: 100 } }` works BUT as soon as an item is added or removed and the array sequence changes, since there is no identifier to match, markers start flying around. 

There should probably be a getKey data accessor to avoid this behaviour `getKey: d => d.id` else how would it be possible to know what goes where? You can only assume that the size of the array remains the same and there are no replacements.

**Comment by Pessimistress** [comment]
Merging with #2570

**Comment by haelimk** [comment]
@danias Hi. Can I ask you something? I cannot find any solution related to icons flying around. I tried to use getKey: d => d.id, but I don't know where to put the code in. I'm using deck.gl icon layer animation with transition, and my icons are animating properly, but sunddenly they start to flying around like you mentioned. Can I get any solution or answer please? Thank you so much.
