### ISSUE TITLE
HeatmapLayer on mobile Safari

### ISSUE THREAD

**Issue by stevenroussey-privicy** [visgl/deck.gl#4200]
#### Description

Heatmap Layer on iOS looks bad

#### Environment:
 - deck.gl-8.0.10
 - Safari 13.3
 - iOS 13.3

#### Example:
![B2F98666-620B-4437-81A0-2ABC8A81A047](https://user-images.githubusercontent.com/42726156/73114345-83953400-3ece-11ea-943c-0706c031011e.png)

Non-heatmap layers are not pixelated:

![809A32D9-4F36-4543-B991-C2AA024E94E0](https://user-images.githubusercontent.com/42726156/73114387-d373fb00-3ece-11ea-8406-e65ce3d32b3d.png)
![98C40A32-ED55-4604-91D8-0F20C5C81B4E](https://user-images.githubusercontent.com/42726156/73114388-d40c9180-3ece-11ea-95b3-66a78b772529.png)

**Comment by stevenroussey-privicy** [comment]
On desktop (MacOS 10.15, Chrome 78) it the Heapmap is fine:

![image](https://user-images.githubusercontent.com/42726156/73114577-ae808780-3ed0-11ea-9a39-6cda54c1405f.png)

**Comment by Pessimistress** [comment]
@1chandu

**Comment by 1chandu** [comment]
@stevenroussey-privicy , iOS Safari doesn't support rendering float textures, hence has lower precession than other browsers, this could be due to that. But I will take another closer look. Can you share your props for `HeatmapLayer` and also any warnings/errors you see in the browser console, thanks.

**Comment by stevenroussey-privicy** [comment]
kepler.gl doesn't seem to have the same issue, for whatever reason.

**Comment by stevenroussey-privicy** [comment]
![image](https://user-images.githubusercontent.com/42726156/73323629-ebb08680-41fc-11ea-9890-e337abdaa008.png)

**Comment by stevenroussey-privicy** [comment]
`import { HeatmapLayer } from '@deck.gl/aggregation-layers';
import { hexColors } from '../../services/config';
import { h3ToGeo } from 'h3-js';

export default function createHeatmapLayer(container) {
  const heat = new HeatmapLayer({
    id: 'heatmap-layer',
    data: container.state.active,
    intensity: 15,
    radius: 4, //sizeLookup[Math.round(container.state.viewState.zoom)],
    colorRange: hexColors,
    onDataLoad: data => {
      container.onDataLoad(data);
    },
    getPosition: d => {
      if (d.index) {
        const [latitude, longitude] = h3ToGeo(d.index);
        return [longitude, latitude];
      } else {
        return [d.longitude, d.latitude];
      }
    },
  });
  return heat;
}
`

**Comment by athomann** [comment]
I'm experiencing this issue but also have a reduction in zoom performance when the heatmap is used and even when `visible` prop is false.  I can currently replicate the performance when going to https://deck.gl/#/documentation/deckgl-api-reference/layers/heatmap-layer on iOS

**Comment by Pessimistress** [comment]
v8.3 fixes the issue where HeatmapLayer continues to update even when `visible: false`.

Also adding a section in the docs regarding the support for iOS: https://github.com/visgl/deck.gl/blob/master/docs/api-reference/aggregation-layers/heatmap-layer.md#limitations

We will continue to look for better fallback solutions on iOS. At this time it is not a bug but a platform limitation.
