### ISSUE TITLE
Next Steps: TerrainLayer

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#4236]
Continuation of #3984 

## To Do List 
  - [x] Fix Martini (transpile published code to es5.. with rollup [their build tool]?) See: https://github.com/mapbox/martini/issues/10
  - [x] Move TerrainLayer to geo-layers

## Vital Extra Credit
  - [ ] Fix tile border seam line
    - Skirting?: https://github.com/mapbox/martini/issues/7
    - Additional scale for any XY seam (wouldn't solve Z)
  - [x] Improve performance (lots of CPU bound math going on. Can it be offloaded to workers or moved to GPU?) Done: https://github.com/uber-web/loaders.gl/pull/652
  - [x] Create a website demo that doesn't utilize mapbox API (serves as a good 2nd example)
    - [x] Could use FAA Sectional surface texture.
    - Could use US grayscale height map from wind demo.
    - Could use AWS Open Data Terrain Tiles

## Feature

- [ ] Support alternative terrain loaders e.g. quantized mesh

**Comment by kylebarron** [comment]
> Create a website demo that doesn't utilize mapbox API (serves as a good 2nd example)

The main non-Mapbox source of terrain tiles that I know of is [AWS Open Data Terrain Tiles](https://registry.opendata.aws/terrain-tiles/). Note that these use a different encoding than Mapbox's tiles ([source](https://github.com/tilezen/joerd/blob/master/docs/formats.md#terrarium))
```
elevation = (red * 256 + green + blue / 256) - 32768
```
You can just use this tile endpoint with no access key currently required:
https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png

**Comment by Pessimistress** [comment]
Looks like Martini 0.2.0 has fixed the tranpilation issue.

**Comment by chrisgervang** [comment]
Thanks @kylebarron, I think I got the AWS source working too :)

**Comment by kylebarron** [comment]
For now this still only works with a raster satellite image texture, right? It would be awesome for it to work eventually with other vector layers, but I get that that's probably a lot of work.

**Comment by chrisgervang** [comment]
> For now this still only works with a raster satellite image texture, right? It would be awesome for it to work eventually with other vector layers, but I get that that's probably a lot of work.

Yeah, only raster surface paint right now. I've gathered its pretty involved to convert the vector data to a texture. I think #3935 is discussing approaches.

**Comment by kylebarron** [comment]
@chrisgervang 
Would it be possible to allow the `surfaceImage` (and maybe also `terrainImage`) prop to be a function that accepts x, y, z coordinates, not just a templated string? For example, I'm thinking of serving different imagery at different zoom levels, and a templated string is too rigid. If I had to, it looks pretty straightforward to overwrite `getTiledTerrainData`, but other users might also be interested in flexibility of surface image.

**Comment by kylebarron** [comment]
What would you think about letting `meshMaxError` also optionally being a function of the current zoom level? I.e. at low zooms I don't care about having a very accurate mesh, while at high zooms the precision is nice.

**Comment by kylebarron** [comment]
It also appears that when panning, a significant part of the slowness is that tiles outside the current viewport are still being computed.
![Screen Recording 2020-03-04 at 1 47 19 AM](https://user-images.githubusercontent.com/15164633/75861448-a878a300-5dba-11ea-8337-947a4cd2224e.gif)

It appears that [`parse-to-image.js`](https://github.com/uber-web/loaders.gl/blob/880c443ed7/modules/images/src/lib/parsers/parse-to-image.js) is being run on all those tiles. That's easy to see in the gif because all the tiles panning back to the original location are already loaded.
![image](https://user-images.githubusercontent.com/15164633/75861581-d231ca00-5dba-11ea-9b05-cc5085a90b8d.png)

I'm just bringing this up because perceived performance might be better if there were a way to cancel generating tiles for areas that are no longer in the viewport.

**Comment by chrisgervang** [comment]
Just getting around to your comments, Kyle. 

It depends on the use case, but for lots of fine control over the tiles I would recommend (and plan to myself) to use the layer in non-TileLayer mode by rendering many layers with absolute URLs and maintaining my own state. 

Alternatively using it in TileLayer mode has a lot of extensibility options too since there are TileLayer props you can override to control loading and cacheing.

**Comment by kylebarron** [comment]
Interesting; I've found that working with `TileLayer` has been really helpful, so I think personally I'm going to try to work within `TileLayer` but potentially make some PRs to help it work better with terrain. E.g. https://github.com/uber/deck.gl/pull/4397, to help TileLayer request correct extruded tiles.

I'll probably create a separate issue about the general case of cancelling `getTileData` for a `TileLayer`.
