### ISSUE TITLE
PolygonLayer Performance?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#4245]
Looking for more of a design recommendation. I'm seeing performance differences when viewing an app I am working on with two different machines. Below are the machine specs...

Machine 1
---
Windows 10
i7-4790 3.6GHz
32GB RAM
Video Card: NVS 510
Chrome 76

Machine 2
---
Windows 10
i7-6700 3.4GHz
16GB RAM
Video Card: Intel HD Graphics 530
Chrome 79

The app is constantly refreshing the following layers every 100 milliseconds...
- 1 LineLayer - Each layer's dataset size is ~30 points
- 1 PolygonLayer - Dataset size is ~30. Polygon consists of 4 points each (i.e., rectangle)
- 3 TextLayer's - Each layer's dataset size is ~30 points

The app is constantly refreshing the following layers ~every 15 seconds...
- 1 PolygonLayer - Dataset size is ~2000. Polygons consist of 121 points each
- 1 TextLayer - Dataset size is ~2000.

When the 100 millisecond layers are on by themselves the frame rate is on average ~40 FPS...

When the ~2000 layers (i.e., PolygonLayer/TextLayer) are on with the 100 millisecond layers I see a pretty dramatic decrease in frame rate to on average 10fps on Machine 1 and on Machine 2 its worse at 1fps. The CPU/GPU/Memory seem reasonable.

Based on what I described I was curious if there may be something jumping out as a potential bottleneck? Perhaps Polygon size (121 points too precise)?

All data is being passed to the layers as JSON. I was looking into the [Interleaved Buffer](https://github.com/uber/deck.gl/tree/master/examples/experimental/interleaved-buffer) option recommended from the [performance doc](https://github.com/uber/deck.gl/blob/master/docs/developer-guide/performance.md) as potential for more performant rendering.

Again, just looking for potential suggestions...

**Comment by ibgreen** [comment]
Those numbers are so bad I would almost suspect at least one of your machines has disabled GPU acceleration.

I recall once spending a not inconsiderable amount of time investigating a remote user's rendering issues on a low-end Windows laptop, until we discovered that the user had turned off GPU acceleration. Once turned back on things were back to normal, so it is as at least worth checking for.

We also discussed issuing warnings in luma.gl if we detected that the WebGL context has the `majorPerformanceCaveat` which should be true if the system does not have GPU acceleration, but not sure if we actually got this in place.

@tsherif likely has more insights

**Comment by tsherif** [comment]
Can you navigate to chrome://gpu on both machines and post the results here? Key things I'm interested are the entries for "Problems Detected", "GL_VENDOR", "GL_RENDERER" and "GL_VERSION". A screenshot of results from the JavaScript Profiler in the devtools might also be helpful.

**Comment by jfuehner** [comment]
Interestingly enough I'm not seeing an option on either machine with regards to hardware acceleration being on or off...

chrome://gpu reads as follows for the machines...

Machine 1
---
- GL_VENDOR - Google Inc.
- GL_RENDERER - ANGLE (NVIDIA NVS 510 Direct3D11 vs_5_0 ps_5_0)
- GL_VERSION - OpenGL ES 2.0.0 (ANGLE 2.1.0.9379eed38531)

Machine 2
---
- GL_VENDOR - Google Inc.
- GL_RENDERER - ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
- GL_VERSION - OpenGL ES 2.0.0 (ANGLE 2.1.0.48aa52f7305a)

I thought perhaps converting the layer generation over to using the straight binary method for paths and solid polygons may make things more performant. However, that doesn't appear to be the case.

**Comment by tsherif** [comment]
Both are using hardware rendering. (If you want to try it without, you can go to Settings -> Advanced -> System and disable "Use hardware acceleration when available").

Can you copy and paste whatever's listed under "Problems Detected" on the chrome://gpu page?

**Comment by jfuehner** [comment]
@tsherif Sorry for the delay, I was out of the office all last week. Below is what the chrome://gpu Problems Detected output is for each machine...

Machine 1
---
- Protected video decoding with swap chain is for Windows and Intel only 
   Disabled Features: protected_video_decode
- Some drivers are unable to reset the D3D device in the GPU process sandbox
  Applied Workarounds: exit_on_context_lost
- Clear uniforms before first program use on all platforms: 124764, 349137    
   Applied Workarounds: clear_uniforms_before_first_program_use
- Always rewrite vec/mat constructors to be consistent: 398694 
  Applied Workarounds: scalarize_vec_and_mat_constructor_args
- ANGLE crash on glReadPixels from incomplete cube map texture: 518889
  Applied Workarounds: force_cube_complete
- Framebuffer discarding can hurt performance on non-tilers: 570897
  Applied Workarounds: disable_discard_framebuffer
- Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
   Applied Workarounds: disable(GL_KHR_blend_equation_advanced), diable(GL_KHR_blend_equation_advanced_coherent)
- Decode and Encode before generateMipmap for srgb format textures on Windows: 634519
   Applied Workarounds: decode_encode_srgb_for_generatemipmap
- Delayed copy of NV12 displays incorrect colors on NVIDIA drivers: 728670
   Applied Workarounds: disable_delayed_copy_nv12
- Hardware overlays result in black videos on non-Intel GPUs: 932879
   Applied Workarounds: disable_direct_composition_layers
- Video processor blit to swap chain results in column of black pixels on older NVIDIA drivers at certain scaling factors: 911349
  Applied Workarounds: disable_direct_composition_layers
- Metal is only available on macOS
   Disabled Features: metal
- Viz hit-test surface layer version is not enabled by default
   Disabled Features: viz_hit_test_surface_layer
- Skia renderer is not used by default
   Disabled Features: skia_renderer

Machine 2
---
- Older Intel GPUs cannot support protected video decoding and swap chains
   Disabled Features: protected_video_decode
- Some drivers are unable to reset the D3D device in the GPU process sandbox
  Applied Workarounds: exit_on_context_lost
- Clear uniforms before first program use on all platforms: 124764, 349137    
   Applied Workarounds: clear_uniforms_before_first_program_use
- Always rewrite vec/mat constructors to be consistent: 398694 
  Applied Workarounds: scalarize_vec_and_mat_constructor_args
- ANGLE crash on glReadPixels from incomplete cube map texture: 518889
  Applied Workarounds: force_cube_complete
- On Intel GPUs MSAA performance is not acceptable for GPU rasterization: 527565
   Applied Workarounds: msaa_is_slow
- Framebuffer discarding can hurt performance on non-tilers: 570897
  Applied Workarounds: disable_discard_framebuffer
- Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
   Applied Workarounds: disable(GL_KHR_blend_equation_advanced), diable(GL_KHR_blend_equation_advanced_coherent)
- Decode and Encode before generateMipmap for srgb format textures on Windows: 634519
   Applied Workarounds: decode_encode_srgb_for_generatemipmap
- VPx decoding is too slow on Intel Broadwell, Skylake, and CherryTrail: 616318
  Applied Workarounds: disable_accelerated_vpx_decode
- Dynamic texture map crashes on INtel drivers less than version  24: 890227
   Applied Workarounds: disable_nv12_dynamic_textures

**Comment by tsherif** [comment]
I don't see anything there that looks problematic.

I notice the SolidPolygonLayer (one of the sublayers of PolygonLayer) uses a TRIANGLE_FAN, which isn't supported in Direct3D so might run slower on Windows since it has to be emulated (see [MS docs](https://docs.microsoft.com/en-us/windows/win32/direct3d9/triangle-fans?redirectedfrom=MSDN) and section 1.4.1 [here](https://books.google.com/books?id=6crECQAAQBAJ&lpg=PP1&pg=PA3#v=onepage&q&f=false) for some details). It's only when used for drawing the sides of extruded polygons so not sure that's relevant here.

**Comment by jfuehner** [comment]
Interestingly enough I converted things where I could over to using the binary approach for layers. That actually seemed to make performance worse...
