### ISSUE TITLE
Error: AnimationLoop.onCreateContext - illegal context returned

### ISSUE THREAD

**Issue by ibesora** [visgl/deck.gl#4250]
We are having issues with this error randomly appear on Windows 10 machines using Chrome. 

Have you seen any case where Chrome is giving a bad WebGL context?

**Comment by tsherif** [comment]
That error isn't about the context being bad, just that it isn't instrumented properly to work with deck.gl. That should be happening automatically. Do you have some sample code that produces the error?

**Comment by ibesora** [comment]
Unfortunately not, I don't even have access to the computers where that error is hapenning.

**Comment by juanignaciosl** [comment]
It's currently happening to me in Linux and Firefox. The [GeoJSON Layer Polygons example won't work](https://deck.gl/#/examples/core-layers/geojson-layer-polygons). I get the following errors:

```
Error: AnimationLoop.onCreateContext - illegal context returned
```

Before the error I can see this debug trace:

```
Successfully compiled asm.js code (total compilation time 72ms) bundle.js
Failed to create WebGL context: WebGL creation failed: 
* tryNativeGL
* Exhausted GL driver options. dist.min.js:1:30953
Failed to create WebGL context: WebGL creation failed: 
* tryNativeGL
* Exhausted GL driver options. dist.min.js:1:31031
Failed to create WebGL context: WebGL creation failed: 
* tryNativeGL
* Exhausted GL driver options. dist.min.js:1:31057
```


It's Firefox 75.0b11 (64-bit). In Chromium, it works, though, without any trace.

I've checked that `webgl.disabled` is false.

**Comment by juanignaciosl** [comment]
Still an issue pending at deck.gl page.

**Comment by juanignaciosl** [comment]
No, I can't. Some change in my system must have brokent it recently, because I'm sure that it worked. I followed https://support.mozilla.org/en-US/kb/upgrade-graphics-drivers-use-hardware-acceleration?redirectlocale=en-US&redirectslug=how-do-i-upgrade-my-graphics-drivers instructions but it didn't help. Anyway, with https://webglreport.com/?v=1 in Chrome I confirmed that it worked, so it looks like Firefox is rejecting my drivers.

So, it's not related to deck.gl.

Thank you, @Pessimistress !

**Comment by juanignaciosl** [comment]
Just in case anybody else ends here, I followed [ArchWiki Firefox guide to force-enable WebGL](https://wiki.archlinux.org/index.php/Firefox/Tweaks) and it worked: `webgl.force-enabled` to `true`, `webgl.msaa-force` `true`, `security.sandbox.content.read_path_whitelist` to `/sys/`.

**Comment by juanignaciosl** [comment]
Thank you for the heads up :)

**Comment by Pessimistress** [comment]
@ibesora Are you still experiencing this issue? The latest release may log more helpful errors to the console.

**Comment by ibesora** [comment]
As I said before, I don't have access to the computers where this was happening.
Will ping you again if some of our users comes across this.
Thanks!
