### ISSUE TITLE
LineLayer: wrong meter width in MapView, scaled by 1/altitude

### ISSUE THREAD

**Issue by MGraefe** [visgl/deck.gl#4285]
#### Description
LineLayer in meter mode and METER_OFFSETS projection mode has an incorrect width in any MapView that has an altitude != 1.
With the default parameters of the MapView, the width is scaled by 1/1.5, meaning it's too small. You can either set widthScale of the LineLayer to `viewport.altitude` (default 1.5) to fix the problem OR set the altitude to 1.0, however there is obviously a deeper issue with the width calculation.

#### Repro Steps
Minimal codepen: https://codepen.io/mgraefe/pen/wvaWZQa
 - Creates two vertical 'guide' lines at x = 0 and x = 10
 - Creates a single red line at x = 5 with width 10
   - red line should fill space between guide lines perfectly
   - commented pieces of code fix the problem

#### Environment (please complete the following information):
 - deck.gl 8.0.15

**Comment by Pessimistress** [comment]
Fix is published in `8.5.0-alpha.7`
