### ISSUE TITLE
IconLayer opacity not working

### ISSUE THREAD

**Issue by jabberw0ky** [visgl/deck.gl#4287]
**Description**

As stated in the docs, I am trying to set the opacity of the rendered icon through getColor by changing the alpha when masking is set to false but there is no change however the icon vanishes on hitting 0 for the alpha component.

**Repro Steps**

Can be reproduced by making an icon layer, passing an icon from either a URL or by catching locally, make sure the icon is an SVG, and then trying to set the alpha or change opacity.
The 'opacity' variable ranges between 0 - 10

`layers.push( new IconLayer( {`
     ` id: node.nid,`
     ` data: data.transformed,`
     ` pickable: true,`
     ` autoHighlight: true,`
     ` billboard: true,`
      `getIcon: d => ( {`
          `url: d.icon,`
         ` width: 300,`
        `  height: 300,`
        `  mask: false,`
       ` } ),`
      `sizeScale: nodeSizeScale,`
      `getSize: d => 15,`
      `getColor: [ 0, 0, 0, opacity * 25 ],`
      `getPosition: d => [ d.lon, d.lat ],`
      `onHover: info => {`
        `const { hoverInfo } = this.state;`
        `if ( ( info.index !== hoverInfo.index ) || ( info.picked === true ) ) this.setState( { hoverInfo: info }`
` );  } } ) ) `

**Environment:**
 - deck.gl: 7.3.3
 - Google Chrome: 79.0.3945.130
 - Windows 7 Ultimate 64 bit

**Logs**
None

-------------------------------------------**UPDATE**------------------------------------------------------

When i set `mask = true` it still does the same thing, on lowering down the alpha through the color picker. The flat color that i select is being displayed but whenever i try lowering down the opacity the icons for the selected layer would shimmer slightly but would remain opaque and then vanish completely when i hit 0. 

My apologies in advance if i am missing something obvious or not setting up the layer correclty :P

**Comment by Pessimistress** [comment]
`opacity` is a number between 0 and 1.
