### ISSUE TITLE
How to achieve 3d heatmap

### ISSUE THREAD

**Issue by dinglei92** [visgl/deck.gl#4293]
I saw a picture of the 3d heatmap on the documentation, but I didn't see the code.
Can someone tell me how this works?
![微信截图_20200220220722](https://user-images.githubusercontent.com/16033134/74941556-3012f900-542e-11ea-9cc1-b1ea414a517a.png)

**Comment by SymbolixAU** [comment]
That is made from polygons with a `z` coordinate (elevation). So your coordinates will have 3 entries, `[X, Y, Z]`

The original source of this came [this comment](https://github.com/SymbolixAU/mapdeck/issues/40#issuecomment-438614935)

**Comment by CharlieJi** [comment]
Where can i find this whole example.

**Comment by dcooley** [comment]
This specific example was made in `R` [here, in this comment](https://github.com/SymbolixAU/mapdeck/issues/40#issuecomment-438614935).
