### ISSUE TITLE
Styled Components Do Not Appear To Be Appropriate Wrappers For Deck.GL

### ISSUE THREAD

**Issue by abrown945** [visgl/deck.gl#4300]
I tried using a styled.div from the styled-components package as a container for my deck.gl/map set up.

Unfortunately, that does not work but having a component with inline styling does

This was my fix

```
<div
        style={{
          height: "50vh",
          width: "40vw",
          position: "relative"
        }}
      >
     </div>
```

I made this bug in case anyone else had this issue after I had created and closed my own

**Comment by Pessimistress** [comment]
Can you make a code sandbox example that reproduces this issue? We use styled components too and have never observed this.
