### ISSUE TITLE
TileLayer with Standalone deck.gl

### ISSUE THREAD

**Issue by mikeldn** [visgl/deck.gl#4314]
Hi,

I'm trying to use the TileLayer with the standalone version of deck.gl : https://deck.gl/#/documentation/deckgl-api-reference/layers/tile-layer

However, rewriting the example above as standalone code I'm hitting some problems.

This: const tile = new deck.VectorTile(new Protobuf(buffer));
gives me: ReferenceError: Protobuf is not defined

If I import the Pbf library into my page: https://github.com/mapbox/pbf with <script src="https://unpkg.com/pbf@3.0.5/dist/pbf.js"></script>

and change Protobuf to PBF: const tile = new deck.VectorTile(new Pbf(buffer));
gives me: TypeError: deck.VectorTile is not a constructor

Do you have a working example of the TileLayer code for standalone deck.gl, or any advice on settings & libraries?

Demo showing error & code here: https://glitch.com/~gla-deck-tile-layer-test 

Thanks!

**Comment by Pessimistress** [comment]
`VectorTile` is from `@mapbox/vector-tiles`.

You can also use the `MVTLayer` from v8.1 which includes the decoding dependencies.
