### ISSUE TITLE
Pointcloud layer Eye-Dome-Lighting

### ISSUE THREAD

**Issue by mkasznia** [visgl/deck.gl#4333]
Hey Guys, 

is there any way to add/implement eye-doom-lightning for pointcloud layer?
Cause right now, when we have many points with the same color, depth feeling is very bad.

Thanks for help!

**Comment by Pessimistress** [comment]
You want [CameraLight](https://deck.gl/#/documentation/deckgl-api-reference/effects/lighting-effect).

**Comment by mkasznia** [comment]
Thank you for your reply! I tried using CameraLight, however it didn't help a lot.
Without:
![withoutlight](https://user-images.githubusercontent.com/10218749/75622685-793c1900-5ba3-11ea-88a6-5488d9050203.png)
With:
![withlight](https://user-images.githubusercontent.com/10218749/75622692-835e1780-5ba3-11ea-98f5-407cbb026a1d.png)
I'm using:
`const cameraLight = new CameraLight({
        color: [255, 255, 255],
        intensity: 2.5
    });`
Any ideas what am I doing wrong?

**Comment by Pessimistress** [comment]
This is because your point cloud does not have normals. You can consider implementing depth-based coloring with a custom PointCloudLayer, see [example](https://codepen.io/Pessimistress/pen/WNxzbvx?editors=0110)
