### ISSUE TITLE
LineLayer onHover stops working after a while

### ISSUE THREAD

**Issue by mkasznia** [visgl/deck.gl#4339]
#### Description
While using 3dtile layers along with LineLayer, after few seconds LineLayer's onHover stops working.

#### Repro Steps
1. Set 3dtile layer (streaming from cesiumIon with pickable set to false)
2. Set LineLayer with 1 vertical line as follows:
`return new LineLayer({
        id: 'line-layer',
        data,
        pickable: true,
        getWidth: 1,
        getSourcePosition: d => d.from.coordinates,
        getTargetPosition: d => d.to.coordinates,
        getColor: d => [255,0,0],
        onHover: ({object, x, y}) => {
            console.log(object);
        }
    });`
3. Check that initially onHover works great.
4. Play for a while.
5. OnHover is not working any longer

#### Environment (please complete the following information):
 - Framework Version: v8.0.16
 - Browser Version: Chrome 77.0.3865.90 (Official Build) (64-bit)
 - OS: Ubuntu 18.04.3 LTS

#### Logs
No logs in browser's console

**Comment by jincui** [comment]
Same here.
layers: [TileLayer, ScatterplotLayer]
ScatterplotLayer onClick stop work after zoom in/out

```javascript
<DeckGL
      width="100%"
      height="100%"
      initialViewState={{ longitude: 121.430759, latitude: 31.222311, zoom: 9 }}
      controller={true}
      layers={layers}
    />
```

deckgl verson: 8.0.16

**Comment by Pessimistress** [comment]
Please provide a codepen/code sandbox that we can use to reproduce this issue.
