### ISSUE TITLE
layerFilter not working on ScatterplotLayer

### ISSUE THREAD

**Issue by marioaks** [visgl/deck.gl#4343]
#### Description
I've been trying to use the `layerFilter` option on the Deck class but it hasn't been working. I think this might be a bug, but I also may be misunderstanding what `layerFilter` does. 

#### Repro Steps
Essentially, I have a Scatterplot layer with the id="all-locations:hidden". I want this layer to not be visible on the screen, but I still want to manually query the points using the `pickMultipleObjects` function. Therefore, I'm passing in the following layerFilter function as so: 

```
new Deck({
   layerFilter: ({ layer, renderPass }) => {
      if (layer.id === 'all-locations:hidden') {
         return renderPass === 'picking:query'
      }
      return true
   }
})
```

My layer is:
```
<ScatterplotLayer
   id="all-locations:hidden"
   pickable
   data={allLocations}
   getPosition={d => d.coordinates}
   radiusMinPixels={1}
   radiusMaxPixels={1}
/>
```

However, no matter what gets returned in `layerFilter, the layer still gets rendered on the screen. Even if I return false for all layers, they all still get rendered. Am I using this incorrectly?

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 8.1.0-alpha.6]
 - Browser Version: [e.g. Chrome 80.0]
 - OS: [e.g. Mac OS X 10.14]

**Comment by Pessimistress** [comment]
I cannot reproduce this: https://codepen.io/Pessimistress/pen/vYEbxwZ (click anywhere to call `pickMultipleObjects`)

You should check if you misspelled `layerFilter` if it has no effect.
