### ISSUE TITLE
Closed paths with binary attributes and PathLayer

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#4345]
Hi all, I was experimenting with switching my non-binary `PolygonLayer`'s over to using the binary `PathLayer` option with the `_pathType` property. I do see that property is still _experimental_ so perhaps what I'm experiencing are already known issues...

**Deck Version:** 8.0.16
**OS:** Windows 10
**Graphics Card:** NVIDIA NVS 510
**Browser:** Chrome

With that said, I'm using the `PathLayer` to create a closed _(i.e., last vertices same as first)_ polygon outline but am getting unexpected results when using the `_pathType` property. 

Unless I'm mistaken, I'm assuming that if I set the `_pathType` to `loop` the path should be completely closed so long as I close the path. However, what I am seeing is a gap in the path; like it's missing a small segment to close it.

If I set the `_pathType` to null then the path closes without issue. However, based on the [docs](https://deck.gl/#/documentation/deckgl-api-reference/layers/path-layer) this suggests I will miss out on gaining the full performance benefit of using the binary option as normalization won't be skipped when `_pathType` is null.

I assume I am misunderstanding the `_pathType` options? Any clarification would be helpful...

Additionally, when I use a binary `PathLayer` on a decent size dataset _(~1100 polygons with 120 point vertices)_ I get a _spider web_ effect where the paths go all haywire. If I break up the data into smaller chunks _(i.e., multiple binary `PathLayer` layers)_ or use a single non-binary `PolygonLayer` the _spider web_ effect goes away.

Is there a limit to the number of vertices you can have in a binary `PathLayer`? If so, any recommendation on the size (i.e., number of vertices) to limit layers to?

**Comment by kylebarron** [comment]
I didn't take the time to create a reproducible example, but I also had issues attempting to pass binary attributes to a PathLayer (actually TripsLayer), though I had `_pathType` set to `open`. When used on a large dataset, I also had paths rendered in the wrong place. If you added a screenshot of your "spider web", I could tell you if it was similar.

**Comment by jfuehner** [comment]
@kylebarron I’ll work on getting a screen capture together or reproducible example. Were you able to resolve your issue? If so, what did you end up doing?

**Comment by kylebarron** [comment]
> Were you able to resolve your issue? If so, what did you end up doing?

I was trying to use tiled protobuf for [a `TripsLayer` animation](https://all-transit.com/#13.44/37.78483/-122.41954). The hope was that the protobuf format could be stored in the format the `PathLayer` expects, so that near-zero work would have to be done client side: just decode the protobuf and pass to the `TripsLayer`. When I couldn't get that to work I reverted to tiled GeoJSON, which I pass in a normal way to the `TripsLayer`. It probably isn't as performant, but it works.

**Comment by jfuehner** [comment]
@Pessimistress still working on trying to put together an example that reproduces the spider-web issue. The dataset I am working with are elliptical paths with 120 point vertices (lat/lon/alt). However, its proprietary so I need to generate/mockup one similar.

With that said, what I am finding is if I break up my dataset into multiple `PathLayer`'s  with ~500 items/~60,000 vertices with their `_pathType` set to `open` the spider-web effect doesn't occur.

The spider-web effect can be best described as lines stemming from/to each elliptical path's start/close. It almost appears as though deck is not terminating the path prior to starting to draw the next path so you get all these interconnecting lines from/to each path.

**Comment by Pessimistress** [comment]
Are you using a Uint16Array as `startIndices`? Uint16’s max value is 65535.

**Comment by jfuehner** [comment]
*face palm*... That was it... Simply changing the `startIndices` typed array from Uint16 to Uint32 resolved the spider-web effect. I no longer have to chunk my dataset.
