### ISSUE TITLE
Quantile Scaling H3HexagonLayer

### ISSUE THREAD

**Issue by Dieegho** [visgl/deck.gl#4353]
Hi,
I'm using H3HexagonLayer to show a set of data like this:

![ISS1](https://user-images.githubusercontent.com/18587332/75989080-5d04e880-5ed1-11ea-8dcb-298258c26f2b.png)

But the function that generates the color of every h3 hexagon is:

```
rgb = value => {
    const minimum = this.state.min;
    const maximum = this.state.max;
    const ratio = (2 * (value - minimum)) / (maximum - minimum);
    const b = parseInt(Math.max(0, 255 * (1 - ratio)));
    const r = parseInt(Math.max(0, 255 * (ratio - 1)));
    const g = 255 - b - r;
    return [r, g, b];
  };
```
So, I need some help to change the way that H3HexagonLayer fills the color with something like this: (The photo is taken from kepler.gl and has a "classification" by quantile scale and I need to do that in my page)

![ISS2](https://user-images.githubusercontent.com/18587332/75992417-b1f72d80-5ed6-11ea-99e5-0a650688f664.png)

I've been searching and I found that kepler use D3.js library, but I can't find out how to combine this two libraries (Deck.gl and D3.js) to solve my problem.

Hope you people can help me!

**Comment by Pessimistress** [comment]
@heshan0131

**Comment by heshan0131** [comment]
You will need to calculate your own getColor accessor using quantile scale

```js
const colorScale = scaleQuantile().range(colors).domain(values);

new H3HexagonLayer({
  data,
  getFillColor: value => colorScale(value),  
  updateTriggers: {
     getFillColor: {colors, values}
  }
})


```
