### ISSUE TITLE
IconLayer with large number of data nodes sometimes does not display.

### ISSUE THREAD

**Issue by hardysabs2** [visgl/deck.gl#4357]
I am implementing something based on this code example, but the data in each node is a little larger:

https://github.com/uber/deck.gl/tree/8.0-release/examples/website/icon

Occasionally but only with large data sets the layer does not display.  On these occasions splitting into two layers always leads to display success.

This does not always happen and I was wondering if there any common issues to be aware of?

Thanks.

**Comment by xintongxia** [comment]
@tsherif Is there a max size or height/width for GL Texture?

**Comment by tsherif** [comment]
Yes, it's hardware dependent. You can find out the max on your system with this code:
```js
const gl = document.createElement("canvas").getContext("webgl");
gl.getParameter(gl.MAX_TEXTURE_SIZE);
```
