### ISSUE TITLE
Import viewState directly?

### ISSUE THREAD

**Issue by abrown945** [visgl/deck.gl#4359]
For some reason, I cannot use 

`this.props.viewState`

and then

`viewState={viewState}`

in one of my applications. Props is from the deck.gl package somehow and works in other applications like this. It is not state from somewhere else in my app.

This is an example of how I can use it in another application.

```js

//MapWrapper.js

import React, { useState } from "react";
import Map from "./Map";
import useInterval from "./customHook/useInterval";

const MapWrapper = ({ viewState }) => {
  const [isMapCentered, setMapIsCentered] = useState(false);

  // setTimeout hook from overreacted
  useInterval(
    () => {
      setMapIsCentered(true);
    },
    1000,
    []
  );

  const initialViewState = {
    latitude: 30.53251808089843,
    longitude: -87.126242135083,
    width: "80%",
    height: "80vh",
    zoom: 10
  };

  const props = isMapCentered ? viewState : initialViewState;

  return <Map className="App" viewState={props} />;
};

export default MapWrapper;


//Map.js

export default function Map({ viewState }) {
  const layer = new PathLayer({
    id: "path-layer",
    data,
    pickable: true,
    widthScale: 20,
    widthMinPixels: 2,
    getPath: d => d,
    getColor: [235, 64, 52]
  });

  return (
    <div className="Map">
      <MapContainer>
        <DeckGL initialViewState={viewState} controller={true} layers={[layer]}>
          <ReactMapGl
            mapStyle={dark_mode_url}
            mapboxApiAccessToken="/"
          />
        </DeckGL>
      </MapContainer>
    </div>
  );
}

```

I would like to be able to use `viewState` as props in my application. But I cannot figure out where to import it from deck.gl. Where can I import this?

**Comment by abrown945** [comment]
I need it directly because it's value is undefined in the application I can not import as props

**Comment by MehdiSaffar** [comment]
I think I understand what you are trying to achieve. A user sees the map at some initial place. The user might pan away from that initial location, so you want to make sure the user stays at that initial place.

I think what you could do is this:

1. attach an `onViewStateChange` to the Deckgl to be able to track your current `viewState` at any time
2. pass `viewState` down all the way to DeckGL by passing it by `viewState` prop not `initialViewState`
3. every 1s do something like `setViewState(initialViewState)`
