### ISSUE TITLE
_lastPointerDownInfo leads to phantom click events (as it's never cleared)

### ISSUE THREAD

**Issue by ilyabo** [visgl/deck.gl#4360]
#### Description

We have an app in which we are using [`react-map-gl-draw`](https://github.com/uber/nebula.gl/tree/master/modules/react-map-gl-draw)  for selecting many objects at once. If I select some object by clicking on it before starting the "drawing", this object gets stored in `deck._lastPointerDownInfo` and is never cleared. This can lead to phantom click events later:

1. When finishing a map drawing and releasing the mouse over a deck.gl layer
          an onClick event is generated.
2. Deck.gl sets the info of this event to _lastPointerDownInfo
          which holds the last object that was clicked any time before
          starting the map drawing.
 3. The object's info is passed to the onClick handler of the corresponding
          layer which leads to selecting the object and altering the map drawing selection.

I came up with [this workaround](https://github.com/ilyabo/flowmap.blue/blob/master/src/FlowMap.tsx#L627): reaching into `deck` and clearing  `_lastPointerDownInfo` after the map drawing update handler is called. This is pretty ugly and obviously breaks the encapsulation.  I think that `deck._lastPointerDownInfo` should be cleared at some point when it's not relevant anymore. At least, it should have a limited lifetime.

#### Repro Steps

We first select one location by clicking on it and clear the selection. Then, we select a group of different locations by drawing a polygon. Once we connect the last to the first dot a phantom click event is generated which leads to selecting the first location in addition to the ones captured by lasso:

![_lastPointerDownInfo](https://user-images.githubusercontent.com/351828/76109615-17354680-5fdd-11ea-983e-95803eba1df0.gif)

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.17
 - Browser Version: Chrome 80.0
 - OS: Mac OS X 10.15

**Comment by Pessimistress** [comment]
This sounds like a bug in react-map-gl-draw - it should block the propagation of the last `click` event when it's handled.
