### ISSUE TITLE
IconLayer onHover called repeatedly

### ISSUE THREAD

**Issue by hardysabs2** [visgl/deck.gl#4366]
I cannot find definitive documentation, but the examples have onHover calling setState and I have read somewhere that onHover is only called when passed object changes.  However, onHover seems to be called repeatedly for any movement on the object so setState fails on the almost immediate second call.

To manage this, I want to save the current hover object in the layer but the layer is not extensible.

**Comment by Pessimistress** [comment]
You can check if `info.object` is the same before calling `setState`.
