### ISSUE TITLE
TileLayer minZoom Parameter

### ISSUE THREAD

**Issue by ilan-gold** [visgl/deck.gl#4373]
Hello, again.  I am here to ask about the `minZoom` parameter.  Before the recent changes, I think that I could essentially use it to control what tiles are created but it didn't control what was rendered.  Is there a strong opinion here on this?  Was I doing it wrong?  I preferred using it for controlling creation, but not rendering.  As an example, if you go to the [example](https://github.com/uber/deck.gl/blob/master/examples/website/image-tile/app.js) I committed recently, and change the `minZoom` parameter to `-8`, the picture disappears when you zoom out.  My use case is a tiled image pyramid that does not have all the levels created (i.e, in the data for the example I provided, it would be as if there was no images past the eighth level).  If this is desired behavior, is there a way around it?

**Comment by Pessimistress** [comment]
The intention of this prop is to prevent the layer from loading too many tiles at low zoom levels. If we still render all tiles when under-zoomed, we need to figure out another way to limit the number of tiles being requested.

**Comment by ilan-gold** [comment]
I think my question is more as to the behavior after tile fetching/creation. The parameter definitely works as expected for limiting requests.  Nonetheless, it seems that once you zoom out far enough, the tiles that are already rendered disappear.  That behavior seems separate from the parameter's limiting of tile fetching.  I can look further into it, but I'm wondering if you might have any knowledge off hand of potential work-arounds (external to deck.gl).

**Comment by ilan-gold** [comment]
Looking a little deeper, I did a quick and dirty change to fix it at https://github.com/uber/deck.gl/blob/master/modules/geo-layers/src/tile-layer/tileset-2d.js#L154 from :
```javascript
updateTileStates() {
    this._updateTileStates(this.selectedTiles);

    let changed = false;
    for (const tile of this._cache.values()) {
      const isVisible = Boolean(tile.state & TILE_STATE_VISIBLE);
      if (tile.isVisible !== isVisible) {
        changed = true;
        tile.isVisible = isVisible;
      }
    }

    return changed;
  }
```
to
```javascript
updateTileStates() {
    this._updateTileStates(this.selectedTiles);

    let changed = false;
    const {_minZoom = 0, _viewport} = this;
    const {zoom} = _viewport;
    for (const tile of this._cache.values()) {
      const isVisible = Boolean(tile.state & TILE_STATE_VISIBLE);
      if (tile.isVisible !== isVisible && zoom >= _minZoom) {
        changed = true;
        tile.isVisible = isVisible;
      }
    }

    return changed;
  }
```

Let me know if this looks right or like something you'd be interested in.  I'd be happy to do some more robust checking/testing into the change.

**Comment by Pessimistress** [comment]
The issue with your change is that the layer only displays what's cached, but does not request any new tiles from `minZoom`. We can't guarantee that you'll see something when under-zoomed, unless you zoomed slowly past the `minZoom` to get everything loaded in cache.

**Comment by ilan-gold** [comment]
That would be interesting, and seems like it would work - I can play around a bit and get back to you.  

I think the worst case scenario is I can hack around it outside changes to `deck.gl` with a default "Background image" so that it is visible when you zoom out far enough, if no clean solution emerges.

Thanks!

**Comment by ilan-gold** [comment]
Having looked into this closely, I see how your proposed solution works now.  Do you want to expose a bounding box prop?  I understand if there is a desire to keep this as is, and there's no rush.  It's simple enough to hack around with a composite layer that wraps the `TileLayer` + whatever `subLayer` you are using (the former rendered when `zoom => minZoom` and the later otherwise), but I'd be happy to make the PR if you want.
