### ISSUE TITLE
missing compass icon when NavigationControl

### ISSUE THREAD

**Issue by jonenst** [visgl/deck.gl#4383]
#### Description

Using the NavigationControl from react-map-gl  (example code in https://github.com/uber/react-map-gl/issues/973) shows a blank square instead of the compass.
That's because of a recent change in css of mapbox. react-map-gl v5.2.0 has code (https://github.com/uber/react-map-gl/commit/f73b467d81fa379ff3a69e688b59fd97e70b769b ) to deal with it, but it does not work automatically when using DeckGl because it is using the value of the MapContext.Provider context.map.version, which deck.gl doesn't set ( https://github.com/uber/deck.gl/blob/d80e819f14e0f46cc1a91782d259ef390d6baa6b/modules/react/src/utils/position-children-under-views.js#L73 )

a workaround is to manually set the internal state of rect-map-gl navigationcontrol:
```
    <NavigationControl ref={ref => {if (ref != null) {ref._uiVersion = 2;}}}/>
```

#### Repro Steps

<!-- Providing the following could help us resolve this issue faster:
https://github.com/uber/react-map-gl/issues/97

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8
 - Browser Version: any
 - OS: any

**Comment by Pessimistress** [comment]
deck.gl can't really tell which mapbox version you have. react-map-gl should make the uiVersion default to the latest release.

**Comment by AndriiTsapenkoCasafari** [comment]
updating css from v0.53.0 to api.tiles.mapbox.com/mapbox-gl-js/v1.11.0/mapbox-gl.css helps for me

**Comment by Pessimistress** [comment]
The issue should be fixed in the latest react-map-gl.
