### ISSUE TITLE
TripsLayer: struggling to start animation from a particular date.

### ISSUE THREAD

**Issue by lezan** [visgl/deck.gl#4385]
What I am goint to ask is a silly question, but I am struggling with my code since too many hours, and maybe I am not so responsive.

I already checked similiar issues reported, and I fixed some problems with my code, but I did not overcome all issues.
I am trying to start animation from a specific date, but I am unable to do that. To do some clarification:

```
_animate() {
  const {
   // my timestamps are in [0, 92700].
    loopLength = 92700,
    animationSpeed = 60
  } = this.props;

  const timestamp = Date.now() / 1000;
  const loopTime = loopLength / animationSpeed;

  const elapsedTime = ((timestamp % loopTime) / loopTime) * loopLength;
  
  const stringTime = milliToString(elapsedTime * 1000 + new Date('2020/01/09 05:00:00 GMT+01:00').getTime());
	
  this.setState({
    time: elapsedTime,
    stringTime: stringTime,
  });

  this._animationFrame = window.requestAnimationFrame(this._animate.bind(this));
}
```

I am pretty sure the problem lies in `const timestamp = Date.now() / 1000`, and according to that elapsedTime does not start from 0. Is timestamp connect to `DOMHighResTimeStamp` of `requestAnimationFrame`?  How can overcome this kind of problem?

Thanks for your answer.

**Comment by lezan** [comment]
Sorry for this bump, but someone have some suggestions?

**Comment by Pessimistress** [comment]
`currentTime` should be in the sample range and format as the values returned by your [getTimestamp](https://deck.gl/docs/api-reference/geo-layers/trips-layer#gettimestamps). There is no point understanding the example code if it confuses you, because your data's timestamp format is likely different from the example.
