### ISSUE TITLE
TransitionInterpolator and FlyToInterpolator for Non-Geospatial

### ISSUE THREAD

**Issue by ilan-gold** [visgl/deck.gl#4407]
#### Target Use case

Hello again, I am back with a familiar sort of request.  

First, could you export `TransitionInterpolator` from the core?  It does not seem to be currently exported but if it is, could you tell me how to import it?  I am prone to mistakes so could be missing something.  

Second, much like the `TileLayer`, would you be interested in separating out the geo-spatial logic of `FlyToInterpolator`?  The current `flyToViewport` function that it uses from `math.gl` is hardcoded with the geospatial use case but the algorithm it uses is general.  I can make PR's there and here if you'd be interested in separating it out.   Thanks!
#### Proposed features

 - Export `TransitionInterpolator` from the `@deck.gl/core`
 - Make `FlyToInterpolator` more general than the geo-spatial use case (PR's here and in `math.gl`).

**Comment by BertCh** [comment]
I also think this would be useful

**Comment by Pessimistress** [comment]
Thank you! The class is exported starting 8.2: https://deck.gl/docs/api-reference/core/transition-interpolator
