### ISSUE TITLE
renderWorldCopies false - horizontal scroll - layers and map do not seem in sync

### ISSUE THREAD

**Issue by hardysabs2** [visgl/deck.gl#4410]
react-map-gl@5.2.3
deck.gl@7.3.15

With ReactMapGL option renderWorldCopies set to false and an IconLayer layer set in DeckGL when I horizontal scroll the icons on the map move into the new space one by one as you scroll but the first ones are moved 'before' the old map disappears and the new map appears.

Unless this is some browser / platform lag?

Anyone observed this / have an idea for a cause / solution.

**Comment by Pessimistress** [comment]
If you are using the IconLayer example from /examples/website/icon, set `wrapLongitude` to `false`.
