### ISSUE TITLE
GeolocateControl is not working with Deckgl

### ISSUE THREAD

**Issue by sureshgadupu** [visgl/deck.gl#4417]
#### Description

I am trying to use GeolocateControl  ( from React-map-gl) along with deckgl  , When I click on GPS icon it does not move to user location
Following is the simple code I am trying to use.
I am wondering is it a bug or my usage is wrong
`
```
<DeckGL initialViewState={INITIAL_VIEW_STATE}   viewState={viewState} controller={true} ContextProvider={MapContext.Provider}>
		<StaticMap  reuseMaps mapStyle={'mapbox://styles/mapbox/dark-v9'} preventStyleDiffing={true} mapboxApiAccessToken={MAPBOX_TOKEN}/>
	
		<GeolocateControl style={geolocateStyle} positionOptions={{ enableHighAccuracy: true }} 
			trackUserLocation={true} ref={(ref)=> {if (ref != null) {ref._uiVersion = 2;}}}>
        </DeckGL>
```
`

**Comment by Pessimistress** [comment]
You set either `initialViewState` only or `viewState` with `onViewStateChange`. `viewState` overwrites all internal updates. See [documentation](https://deck.gl/#/documentation/deckgl-api-reference/deck).
