### ISSUE TITLE
Updating the initialViewState prop doesn't result in a call to onViewStateChange

### ISSUE THREAD

**Issue by jonenst** [visgl/deck.gl#4420]
#### Description

In stateful mode (initialViewState), panning or zooming calls onViewStateChange(), but setting the initialViewState prop doesn't (it does change the viewState).  Mentionned it in https://github.com/uber/deck.gl/pull/4038#issuecomment-600667968 but got no reply

#### Repro Steps
https://codepen.io/jonenst/pen/PoqyMWM
Notice that panning or zooming calls onViewStateChange, whereas settings the initialViewStateChange does update the view but doesn't call the callback. 

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]
deckgl 8.1
firefox or chrome
linux

**Comment by Pessimistress** [comment]
This is by design. User-initiated view state changes (explicitly setting `initialViewState` and `viewState`) do not trigger `onViewStateChange` to avoid unintended loops.

**Comment by jonenst** [comment]
Ok, thanks for the quick response. We use onViewStateChange to enable/disable labels based on a zoom level threshold. When we programmatically re set initialViewState, we do want to enable/disable the labels. Is there a better solution than manually calling our callback with the viewState we are setting ?
