### ISSUE TITLE
IconLayer autoHightlight flickering and onClick events not registered

### ISSUE THREAD

**Issue by talkl** [visgl/deck.gl#4427]
#### Description
autoHighlight and onClick events on IconLayer are buggy. highlight is flickering and onClick does not register randomly.
The issue was present since i started writing the project. Basically onClick events on the IconLayer are sometimes not registered and when i enable autoHighlight, the click events are even more buggy and most of the time don't register. The weird thing is that GeoJsonLayer autoHighlight and onClick work like magic, so something is up with my IconLayer.

#### Environment:
"deck.gl": "^8.0.16"
Chrome Version 80.0.3987.149 (Official Build) (64-bit)
Mac OS X 10.14.6

![Screen-Recording-2020-03-27-at-12 59 14](https://user-images.githubusercontent.com/9368630/77745162-dbb1f900-702b-11ea-8724-8c323725f40c.gif)

#### Repro Steps
`
import React, {useState, useMemo, useCallback, useContext} from 'react';
import ReactCompareImage from 'react-compare-image';
import DeckGL from '@deck.gl/react';
import {GeoJsonLayer, IconLayer} from '@deck.gl/layers';
import {FlyToInterpolator} from '@deck.gl/core';
import {_MapContext as MapContext, StaticMap, NavigationControl} from 'react-map-gl';
import Style from './Map.module.css';
import { ReactComponent as SatelliteIcon } from '../../assets/satellite.svg';
import { ReactComponent as WorldIcon } from '../../assets/world.svg';
import MapIncidentSpriteImage from '../../assets/map.incident.sprite.image.png';
import {Button, Icon, Modal, Skeleton, message} from "antd";
import {
    IIncident, IIncidentImage, IIncidentProperties, IInteractionState,
    IPipelineData,
    IPipelineProperties, IViewState, TRANSITION_EVENTS
} from "../../interfaces/map.interfaces";
import {Feature, GeoJsonProperties, Geometry, LineString} from "geojson";
import MapTooltip from "./map.tooltip";
import MapComponentContext from './map.component.context';
import moment from 'moment-timezone';
import {
    INCIDENT_ICON_SIZE,
    MAP_EARTH_ICON,
    MAP_FIRE_ICON,
    MAP_NORMAL_ICON,
    MAP_WARNING_ICON,
    MAP_WATER_ICON, PIPELINE_COLOR, PIPELINE_HIGHLIGHT_COLOR
} from "../../constants/map.consts";
import {Moment} from "moment-timezone/moment-timezone";
import {BUTTON_PROPS} from "../../constants/general";
import {exportToJson} from "../../utils/export.utils";
import DemoContext from "../Demo/demo.context";
import {DataFilterExtension} from '@deck.gl/extensions';

interface IMapProps {
    pipelineData: IPipelineData,
    incidentsData: IIncident[],
    pipelineLastCheckedUtc: Moment;
    center: {
        longitude: number;
        latitude: number;
    }
}

interface IDeckGlClickInfo {
    index: number;
    x: number;
    y: number;
    lngLat: number[];
    object: Feature<Geometry, GeoJsonProperties> | IIncident;
}

interface ICompareImages {
    imageBefore?: IIncidentImage;
    imageAfter?: IIncidentImage;
}

const INITIAL_VIEW_ANGLE = {
    zoom: 8,
    pitch: 0,
    bearing: 0
};

const normalMapStyle = 'mapbox://styles/mapbox/outdoors-v11';
const satelliteMapStyle = 'mapbox://styles/mapbox/satellite-v9';

const ICON_MAPPING = {
    [MAP_NORMAL_ICON]: {x: 128, y: 128, width: 128, height: 256, mask: false},
    [MAP_WARNING_ICON]: {x: 266, y: 128, width: 128, height: 256, mask: false},
    [MAP_FIRE_ICON]: {x: 404, y: 128, width: 128, height: 256, mask: false},
    [MAP_EARTH_ICON]: {x: 542, y: 128, width: 128, height: 256, mask: false},
    [MAP_WATER_ICON]: {x: 680, y: 128, width: 128, height: 256, mask: false},
};

export default function Map(props: IMapProps) {
    const demoContext = useContext(DemoContext);
    const initialViewState: IViewState = {
        ...INITIAL_VIEW_ANGLE,
        ...props.center
    };
    const [previousViewState, setPreviousViewState] = useState<IViewState>(initialViewState);
    const [viewState, setViewState] = useState<IViewState>(initialViewState);
    const [mapStyle, setMapStyle] = useState<string>(normalMapStyle);
    const [clickEvent, setClickEvent ] = useState<IDeckGlClickInfo | null>(null);
    const [compareImages, setCompareImages] = useState<ICompareImages>({});
    const [ verticalCompareMode, setVerticalCompareMode ] = useState<boolean>(false);
    const closeTooltip = useCallback(() => {
        setClickEvent(null);
        setViewState({
            ...previousViewState,
            transitionDuration: 'auto',
            transitionInterpolator: new FlyToInterpolator(),
            transitionInterruption: TRANSITION_EVENTS.BREAK,
        });
    }, [previousViewState]);

    const { pipelineData, incidentsData, pipelineLastCheckedUtc } = props;

    const toggleMapStyle = () => {
        const newMapStyle = mapStyle === normalMapStyle ? satelliteMapStyle : normalMapStyle;
         setMapStyle(newMapStyle);
    };

    const closeModal = () => {
        setCompareImages({});
    };

    const openModal = (compareImages: ICompareImages) => {
        setCompareImages(compareImages);
    };

    const toggleCompareMode = () => {
        setVerticalCompareMode(!verticalCompareMode);
    };

    const exportIncident = async (incident: IIncident) => {
        const hide = message.loading('Export in progress..', 0);
        const incidentToExport = {
            type: "Feature",
            properties: incident.properties,
            geometry: {
                type: "Point",
                coordinates: incident.coordinates
            }
        };
        await exportToJson(incidentToExport);
        hide();
    };

    const onHideIncident = (incident: IIncident) => {
        if (!demoContext) {
            return;
        }
        closeTooltip();
        demoContext.hideIncident(incident.properties.id);
    };

    const renderCompareImage = () => {
        const shouldShowModal: boolean = !!compareImages.imageAfter?.url && !!compareImages.imageBefore?.url;
        if (!shouldShowModal) {
            return null;
        }
        return (
            <Modal
                centered
                getContainer={"#root"}
                onCancel={closeModal}
                visible={shouldShowModal}
                title={
                    <div className={Style.compareButtonContainer}>
                        <Button
                            className={Style.mapTooltipButton}
                            {...BUTTON_PROPS}
                            size="small"
                            onClick={toggleCompareMode}
                        >
                            Toggle Alignment
                    </Button>
                    </div>
                }
                footer={null}
            >
                <ReactCompareImage
                    leftImage={compareImages.imageBefore?.url}
                    leftImageAlt="before"
                    leftImageLabel={`Before, Date: ${compareImages.imageBefore?.date}`}

                    rightImage={compareImages.imageAfter?.url}
                    rightImageAlt="after"
                    rightImageLabel={`After, Date: ${compareImages.imageAfter?.date}`}

                    skeleton={<Skeleton active/>}
                    rightImageCss={{ height: '100%', 'width': '100%', objectFit: 'fill'}}
                    leftImageCss={{ height: '100%', 'width': '100%', objectFit: 'fill'}}
                    vertical={verticalCompareMode}
                />
            </Modal>
        );
    };

    const renderPipelineTooltip = () => {
        if (!clickEvent || (clickEvent.object?.properties as IPipelineProperties)?.objectType?.toLowerCase() !== "pipelinesegment") {
            return null;
        }
        const properties = clickEvent.object.properties as IPipelineProperties;
        const name = properties.name;
        const owner = properties.owner;
        const lastChecked = properties.lastUpdate;
        const segment = properties.segment;
        return (
            <MapTooltip
                position={{x: clickEvent?.x, y: clickEvent?.y}}
            >
                <span>{name}</span>
                <br/>
                <span>Owner: {owner}</span>
                <br/>
                <span>Last Updated: {lastChecked}</span>
                <br/>
                <span>Segment: {segment}</span>
            </MapTooltip>
        );
    };

    const renderIncidentTooltip = () => {
        if (!clickEvent || (clickEvent.object?.properties as IIncidentProperties)?.objectType?.toLowerCase() !== "incident") {
            return null;
        }
        const properties = clickEvent.object.properties as IIncidentProperties;
        const type = properties.type;
        const comment = properties.comment;
        const confidence = properties.confidence;
        const imageBefore = properties.imageBefore;
        const imageAfter = properties.imageAfter;
        const date = imageAfter.date;
        return (
            <MapTooltip
                position={{x: clickEvent?.x, y: clickEvent?.y}}
            >
                <span>{type}</span>
                <br/>
                <span>Last Updated: {date}</span>
                <br/>
                <span>{comment}</span>
                <br/>
                <span>Confidence: {confidence}</span>
                <br/>
                <Button
                    disabled={!imageBefore?.url || !imageAfter.url}
                    onClick={openModal.bind({},{imageAfter, imageBefore})}
                    className={Style.mapTooltipButton} {...BUTTON_PROPS}
                    size="small"
                >
                    Compare
                </Button>
                <Button className={Style.mapTooltipButton} {...BUTTON_PROPS} size="small" onClick={exportIncident.bind({}, clickEvent.object as IIncident)}>
                    Export
                </Button>
                <Button className={Style.mapTooltipButton} {...BUTTON_PROPS} size="small" onClick={onHideIncident.bind({}, clickEvent.object as IIncident)}>
                    Hide
                </Button>
            </MapTooltip>
        );
    };

    const isIncidentClassifiedAsWarning = (d: IIncident): boolean => {
        return moment.utc(d.properties.imageAfter.date) > pipelineLastCheckedUtc;
    };

    const getIncidentIcon = (d: IIncident): string => {
        if (isIncidentClassifiedAsWarning(d)) {
            return MAP_WARNING_ICON;
        }
        return MAP_NORMAL_ICON;
    };

    const flyToIncident = (incident: IIncident) => {
        setPreviousViewState(viewState);
        setViewState({
                ...viewState,
                longitude: incident.coordinates[0],
                latitude: incident.coordinates[1],
                zoom: 17,
                pitch: 0,
                bearing: 0,
                transitionDuration: 'auto',
                transitionInterpolator: new FlyToInterpolator(),
                transitionInterruption: TRANSITION_EVENTS.BREAK,
            }
        );
    }

    const pipeline = new GeoJsonLayer({
        id: 'pipeline-layer',
        data: pipelineData,
        parameters: {
            depthTest: false,
        },
        pickable: true,
        autoHighlight: true,
        highlightColor: PIPELINE_HIGHLIGHT_COLOR,
        lineWidthScale: 1,
        lineWidthMinPixels: 5,
        getLineColor: PIPELINE_COLOR,
        getLineWidth: 3,
        onClick: (info: IDeckGlClickInfo, event: any) => {
            setPreviousViewState(viewState);
            setClickEvent({
                index: info.index,
                lngLat: info.lngLat,
                x: info.x,
                y: info.y,
                object: info.object as Feature<LineString, IPipelineProperties>
            });
        }
    });

    const incidents = new IconLayer({
        id: 'incidents-layer',
        data: incidentsData,
        pickable: true,
        autoHighlight: true,
        iconAtlas: MapIncidentSpriteImage,
        iconMapping: ICON_MAPPING,
        getIcon: getIncidentIcon,
        sizeScale: 13,
        getPosition: (d: IIncident) => d.coordinates,
        getSize: INCIDENT_ICON_SIZE,
        getFilterValue: (d: IIncident) => d.opacity,
        filterRange: [0, 1],
        filterSoftRange: [0.2, 1],
        filterTransformSize: true,
        filterTransformColor: true,
        extensions: [new DataFilterExtension({filterSize: 1})],
        onClick: (info: IDeckGlClickInfo, event: any) => {
            flyToIncident(info.object as IIncident);
            setClickEvent({
                index: info.index,
                lngLat: info.lngLat,
                x: info.x,
                y: info.y,
                object: info.object as IIncident
            });
        }
    });

    const layers = [
        pipeline,
        incidents
    ];

    const getMapApi = useMemo(() => ({ closeTooltip }), [closeTooltip]);
    return (
        <DeckGL
            viewState={viewState}
            onViewStateChange={
                ({viewState, interactionState, oldViewState}:
                     {viewState: IViewState, interactionState: IInteractionState, oldViewState: IViewState}) =>  {
                    setViewState(viewState);
                }
            }
            controller={true}
            layers={layers}
            onDragStart={() => setClickEvent(null)}
            ContextProvider={MapContext.Provider}
            useDevicePixels={false}
        >
            <StaticMap
                mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_ACCESS_TOKEN}
                mapStyle={mapStyle}
                preventStyleDiffing={true}
            />
            <MapComponentContext.Provider value={getMapApi}>
                {renderPipelineTooltip()}
                {renderIncidentTooltip()}
                {renderCompareImage()}
                <Icon
                    onClick={toggleMapStyle}
                    className={Style.mapStyleButton}
                    component={
                        mapStyle === normalMapStyle ? () => <SatelliteIcon className={Style.mapButtonIcon}/> :
                            () => <WorldIcon className={Style.mapButtonIcon}/>}
                />
            </MapComponentContext.Provider>
            <div className={Style.mapControl}>
                <NavigationControl
                    onViewportChange={setViewState}
                />
            </div>
        </DeckGL>
    );
}
`

**Comment by Pessimistress** [comment]
IconLayer is not picked if you hover over the empty pixels in an icon. You can adjust this behavior by changing the [alphaCutoff](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer) prop.

**Comment by talkl** [comment]
> IconLayer is not picked if you hover over the empty pixels in an icon. You can adjust this behavior by changing the [alphaCutoff](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer) prop.

1. I changed the alphaCutoff - didn't work
2. Changed the icon to another image with no empty pixels (from deck gl exmple) - didn't work

Is it a problem with react rendering?
