### ISSUE TITLE
Cancel getTileData processing when outside new viewport

### ISSUE THREAD

**Issue by kylebarron** [visgl/deck.gl#4429]
Usually `getTileData` is a relatively fast function of just downloading data and passing it on to `renderSubLayers`. However, when `getTileData` is more computationally intensive, there can be a lag when zooming out or panning. Here's a GIF of tiling terrain and snapping vector features onto the terrain (the first is on a separate worker, the latter isn't). 

![Screen Recording 2020-03-27 at 5 21 46 PM](https://user-images.githubusercontent.com/15164633/77808108-c9e24d00-704f-11ea-9e78-e0236f8153e0.gif)

You can tell that tiles at the original zoom are still computed for a little while after zooming out. 

I'd like to be able to cancel `getTileData` for the high zoom tiles when I zoom out and cross a zoom threshold. Mapbox GL JS does this, though I haven't searched their codebase yet for how.

This issue is 1) to mention the lag can exist when `getTileData` is slow, 2) should I research potential ways to make a PR to fix this inside `deck.gl` 3) any general advice? I was thinking of testing out putting `getTileData` on a thread pool of web workers, and then seeing if it's possible to cancel a running worker. That seems like it would be too invasive as a PR to the TileLayer, though?

Ref: https://github.com/uber/deck.gl/issues/4236#issuecomment-594400675

**Comment by ilan-gold** [comment]
I would also be interested in this sort of feature.  I am not sure how putting `getTileData` on a pool of workers (in general) would work in practice - FWIW I use a library (`geotiff.js`) that does decoding of responses on a pool and it is noticeably faster.  In this sense `getTileData` is on a pool, but abstracted away a bit.  Something that some coworkers and I spitballed was that a priority queue of some sort could also be interesting, so as you zoom out, lower priority requests are never made.  Also, I am not sure what this looks like in practice.

**Comment by kylebarron** [comment]
I haven't gotten around to trying to write a prototype yet, but I'll report back if I do

**Comment by ibgreen** [comment]
> I was thinking of testing out putting getTileData on a thread pool of web workers, and then seeing if it's possible to cancel a running worker. That seems like it would be too invasive as a PR to the TileLayer, though?

deck.gl is typically paired with loaders.gl. Many loaders in loaders.gl support worker loading (default pool size is 5 parallel workers). If getTileData is implemented with a loaders.gl loader, this should already be supported?

> I'd like to be able to cancel getTileData for the high zoom tiles when I zoom out and cross a zoom threshold. 

> a priority queue of some sort could also be interesting for this problem, so as you zoom out, lower priority getTileData requests are never made. Also, I am not sure what this looks like in practice.

The 3D tile layer uses a [`RequestScheduler`](https://github.com/uber-web/loaders.gl/blob/master/modules/loader-utils/src/lib/request-utils/request-scheduler.js) class for this very purpose, it can prevent huge amounts of pending tile loads for tiles that are no longer in view when quickly moving through a big 3D tile scene. 

The `RequestScheduler` is a bit hacky in its current state and needs a bit of work, but there is a background plan to overhaul it and use it more widely.

**Comment by ilan-gold** [comment]
Y'all are so good at doing things that people want! Amazing that you already have one.  That'd be so great :)

**Comment by kylebarron** [comment]
> If getTileData is implemented with a loaders.gl loader, this should already be supported?

True, but in this case I need to do CPU bound work _after_ receiving the response from `loaders.gl`. In my GIF above, the terrain mesh and the image texture are being loaded through `loaders.gl`, but then using the terrain mesh to find the elevation for each coordinate of each line segment (the black lines) is CPU intensive. I haven't looked if it's possible to easily reuse the `loaders.gl` web worker scaffolding for custom code outside of a pre-defined loader.

> The 3D tile layer (or more correctly, the 3D tile loader classes from loaders.gl) uses a [`RequestScheduler`](https://github.com/uber-web/loaders.gl/blob/master/modules/loader-utils/src/lib/request-utils/request-scheduler.js) class for this very purpose, it can prevent huge amounts of pending tile loads for tiles that are no longer in view when quickly moving through a big 3D tile scene.

I think that's exactly what I'm looking for. It looks like the `RequestScheduler` works with arbitrary requests and isn't tied to 3D tiles, so I might try to adapt `TileLayer` to use it.

**Comment by ibgreen** [comment]
> True, but in this case I need to do CPU bound work after receiving the response from loaders.gl

OK I think I got it now :)

The major problem we have faced is that non-trivial workers need to be pre-bundled, so they require a lot of work to set up and maintain, and handling this and providing pre-built worker loaders is part of the value proposition of loaders.gl. 

>  I haven't looked if it's possible to easily reuse the loaders.gl web worker scaffolding for custom code outside of a pre-defined loader.

It does require a bunch of build time wiring, so it is not exactly easy, but it is possible. One idea we have is to create a processing library with a catalog of various geometry processing functions, and using a similar worker setup to loaders.gl to provide worker versions of those. 

It is a bigger vision that would require significant effort though, but it could cover both your TIN-mesh / martini worker, mesh reprojection and many other operations in a nice way.

**Comment by ilan-gold** [comment]
+1 on a scheduler now for managing requests - I have run into a similar use-case, where some work in the fetching function is compute-intensive.

**Comment by kylebarron** [comment]
One more follow up: 

I believe that in addition to being slow when `getTileData` is computationally intensive, the current queue also slows down when the _network request_ is slow. For reference, I'm generating my own satellite imagery on the fly on the backend, and that can take 1-4s to generate an image tile. Without any intelligent scheduling going on, zooming out can be slow since by default the pool of image loaders is 5, and each of those threads waits 1-4s for the imagery to load.

I could probably increase the number of concurrent threads, but I think a request scheduler that cancels now-invalid tiles is a better solution.

I spent a bit of time on a PR yesterday but got lost in the weeds and didn't make much progress.

**Comment by Pessimistress** [comment]
Aside from a scheduler, we could also consider adding bail-out checkpoints for expensive `getTileData` operations: (pseudocode)

```js
class TerrainLayer {
  loadTerrain(tile, loaderOptions) {
    const terrainUrl = getTerrainUrl(tile);
    const options = {
      terrain: loaderOptions
    };
    return fetch(terrainUrl)
      .then(resp => resp.arrayBuffer())
      .then(data => {
        // Check if the tile is still needed before proceeding with expensive operation
        if (!tile.isCancelled) {
          return parse(data, TerrainLoader, options);
        }
        return null;
      });
  }
}
```

**Comment by kylebarron** [comment]
Great point. Depending on the situation, slow tiles could be either:

- Slow network request
- Slow parsing of request

I'd be in favor of including a flag like `isCancelled` on the `tile` object.

But, we'd need to prevent caching of the response when `isCancelled` is `true`. Otherwise `null` could be cached, so panning back to that tile could be cached as empty.

**Comment by ilan-gold** [comment]
I think that would be good.  Just to clarify, would this be something specific to `TerrainLayer` or more generally would the `getTileData` API change to have args more like `{x, y, z, tile}` that can check the `isCanceled` property of `tile`?

**Comment by Pessimistress** [comment]
`getTileData` is actually called with a single `tile` argument. We can clarify that in the docs.

**Comment by kylebarron** [comment]
Yeah `getTileData` is already passed with `x, y, z, url, bbox` keys in the object, so I presume this would just be another key.
