### ISSUE TITLE
How to get boundary values of color range?

### ISSUE THREAD

**Issue by gtitov** [visgl/deck.gl#4432]
I want to build hexagon layer's legend that contain the color range and corresponding boundary values. I found a way to get color range by storing it in the app state. But I can't figure out how to get boundary values that counted dynamically. I thought I could calculate boundaries myself using colorValueDomain, but I don't understand how to retrieve this values. By the way I'm using DeckGL with React and I'm quite new to both technologies.

![image](https://user-images.githubusercontent.com/39987349/77828935-9b3ba380-712f-11ea-8722-7c47214d76b2.png)

**The question is** how to get boundary color values of color range? Is there a more convenient way to built layer's legend?

Here is my HexagonLayer
```javascript
settings.showHexagon && new HexagonLayer({
      id: 'hexagon-layer',
      pickable: true,
      getPosition: node => node.position,
      // colorDomain: [0, 8],
      getColorValue: nodes => { 
        const sumValue = nodes.reduce((sum, {value}) => sum + value, 0)  // {value} это ключ значения в объекте nodes, 0 - стартовое значение sum
        const avgValue = sumValue / nodes.length
        const avgValueRound = Math.round(avgValue * 100) / 100
        return avgValueRound
      },
      getElevationValue: nodes => {
        const sumValue = nodes.reduce((sum, {value}) => sum + value, 0)
        const avgValue = sumValue / nodes.length
        const avgValueRound = Math.round(avgValue * 100) / 100
        return avgValueRound
      },
      elevationScale: 500,
      data: data,
      onHover,
      ...settings
    })
```
And my DeckGL component
```javascript
<DeckGL 
          layers={
            renderLayers(
              {
              data: this.state.nodes,
              month: this.state.selectedMonth,
              onHover: hover => this._onHover(hover),
              settings: this.state.settings
              }
            )
          }
          initialViewState={ INITIAL_VIEW_STATE }
          controller={true}
          onViewStateChange={
            ({viewState, oldViewState}) => {
              const currentZoom = Math.floor(viewState.zoom)
              const oldZoom = Math.floor(oldViewState.zoom)
              if(currentZoom !== oldZoom) {
                const zoomIndex = currentZoom - INITIAL_VIEW_STATE.minZoom
                const newRadius = zoomRadius[zoomIndex]
                let newSettings = this.state.settings
                newSettings.radius = newRadius
                this._updateLayerSettings(newSettings)
              }
            }
          }
>
```

**Comment by SymbolixAU** [comment]
I think you're after the [`onSetColorDomain`](https://github.com/uber/deck.gl/blob/master/docs/layers/hexagon-layer.md#onsetcolordomain-function-optional) callback, which is "called when bin color domain has been calculated."

**Comment by gtitov** [comment]
Seems like it. But I still can't figure out how to refer to bin color domain from from this callback. Is there any example?

**Comment by 1chandu** [comment]
You can get all colors used from `colorRange` prop ([source-code-link](https://github.com/uber/deck.gl/blob/b47d6d5de0f83a3ccb9c550d50c909d6c8de38a4/modules/aggregation-layers/src/hexagon-layer/hexagon-layer.js#L35)).  0th and 5th element will be min and max colors. You can also set a specify array for this prop like any other prop instead of using default colors.

**Comment by gtitov** [comment]
I see. But I want to get not only values of colors, but min and max of my data values corresponding to these colors. Can I do it in the layer statement or in the app?
Probably I need to refer to the bin color domain but I can't see how I can do this.
![image](https://user-images.githubusercontent.com/39987349/78380890-3d9ad180-75dd-11ea-9894-2a36e1992992.png)

**Comment by gtitov** [comment]
![image](https://user-images.githubusercontent.com/39987349/78588173-d2543800-7846-11ea-8aea-baaefd75d73b.png)

**Comment by Pessimistress** [comment]
You want to use `onSetColorDomain` and `onSetElevationDomain`.

**Comment by gtitov** [comment]
Can you give a simple example please? It will help a lot.

**Comment by gtitov** [comment]
Well, here is the example `onSetColorDomain: event => console.log(event)` and in the console we have an array with two numbers min and max. And now we can use it to create legend.
Pretty obvious, but it wasn't clear for me from the documentation.

Thank you for your answers! They've really helped!

**Comment by ionutbalan000** [comment]
How could we implement this for different layer types, such as GeoJsonLayer, PolygonLayer, PathLayer, GridLayer, HexagonLayer?
Polygon and GeoJson do not have this colorDomain option

**Comment by ionutbalan000** [comment]
Also, the information that comes from the console.log is not very helpful
