### ISSUE TITLE
Blurring only the edges of Polygon Layer 

### ISSUE THREAD

**Issue by mogmog** [visgl/deck.gl#4440]
As someone who is new to the under the hood WebGL specifics of Deck, I need some help.

I need to be able to draw a polygon on screen which has the edges blurred. Very similar to this effect, but for a Polygon, not an image.

https://stackoverflow.com/questions/46506503/how-can-i-blur-just-the-edges-of-an-image-in-webgl-shader?rq=1

What would the 'DeckGL Way' of achieving this? Is it possible to somehow pass a shader to the PolygonLayer, or would I need to copy the existing SolidPolygonLayer and hack in a shader like the one in the SO post?

**Comment by mogmog** [comment]
Now I am wondering if the way to do this would be draw a polygon layer with no fill onto a separate view that has a blur effect applied to it? 

Is that possible/the right way? Are effects applied at a view level ?

**Comment by 1chandu** [comment]
You would need some kind of post processing effect, check https://deck.gl/#/documentation/deckgl-api-reference/effects/post-process-effect

But identifying the edges and applying blurring only to those pixels would be more complicated would require these additional components:
- A [LayerPass](https://github.com/uber/deck.gl/blob/master/modules/core/src/passes/shadow-pass.js) to generate a texture of just the edges
- And a Custom SolidPolygonLayer, with fragment shader that samples texture produced above to selectively apply blurring to border pixels.

This would require some solid knowledge of WebGL,  for reference you can check[ this example](https://github.com/uber/deck.gl/blob/master/examples/website/geojson/app.js#L68) which uses inbuilt LightingEffect to generate shadows.
