### ISSUE TITLE
Custom TextLayer not passing props on

### ISSUE THREAD

**Issue by Gopid** [visgl/deck.gl#4442]
Trying to create a custom layer that makes use of TextLayer based on this documentation: https://github.com/uber/deck.gl/blob/master/docs/developer-guide/custom-layers/composite-layers.md

The text layer is getting rendered but the size of the text is significantly smaller compared to the text that is rendered using TextLayer on its own and the text anchor and alignment baseline is not getting picked up.

This is how I'm trying to create the custom layer:
`import { TextLayer, CompositeLayer } from 'deck.gl';

class CustomTextLayer extends CompositeLayer<any> {
  renderLayers() {
    return [
      new TextLayer(this.getSubLayerProps({
        id: `${this.props.id}-text`,
        data: this.props.data,
        pickable: false,
        fontFamily: this.props.fontFamily,
        fontWeight: this.props.fontWeight,

        getPosition: (d: any) => [d.center.longitude, d.center.latitude],
        getText: (d: any) => d.name,
        getSize: 32,
        getAngle: 0,
        getColor: [0, 0, 0],
        getTextAnchor: 'middle',
        getAlignmentBaseline: 'center',
      }))
    ];
  }
}

export default CustomTextLayer;`

Am I missing something?

**Comment by TextTL** [comment]
The getSize accessor is hardcoded to 32 pixels; unless that is your intention, else whatever size passed to the CustomTextLayer is not passed to the Text layer.
