### ISSUE TITLE
Does the i3s layer support 3857 projection?

### ISSUE THREAD

**Issue by The-End-Hero** [visgl/deck.gl#4447]
![image](https://user-images.githubusercontent.com/19590233/78323252-d6acf680-75a3-11ea-8688-2ca789ca2006.png)

**Comment by ibgreen** [comment]
@xintongxia Do you recall if we support Web Mercator (EPSG: 3857) or just WGS 84 (EPSG:4326) in the new `I3SLoader`?

**Comment by xintongxia** [comment]
@ibgreen `I3SLoader` only supports WGS84

**Comment by ibgreen** [comment]
@The-End-Hero would be good to open an issue on https://github.com/uber-web/loaders.gl
