### ISSUE TITLE
HexagonLayer non-iterable data object getColorValue / getColorWeight accessor not working as documented...

### ISSUE THREAD

**Issue by derMart** [visgl/deck.gl#4449]
Hi, I need to use a non-iterable data object on a HexagonalLayer like this:

```
hexagonLayer = new MapboxLayer({
          type: HexagonLayer,
          id: 'heatmap',
          data: {length: myLength, myData: myData},
          getPosition: (obj, objInfo) => {
                 // works as expected, objInfo has index and data attribute
                 return objInfo.data.myData.mySubProp[objInfo.index];
          },
          getColorValue: (obj, objInfo) => {
                 /*
                 objInfo is undefined and obj is an Array.
                 It seems to somehow contain points converted to screencords,
                 each item has a property screenCoord, but thats it...
                 obj: Array(31)
                       0: {screenCoord: Array(2)}
                       1: {screenCoord: Array(2)}
                       2: {screenCoord: Array(2)}
                       ...
                 */
          },
          getColorWeight: (obj, objInfo) =>{
                /*
                similar to getColorValue, objInfo is undefined, 
                obj seems to be just one of the point objects
                from the getColorValue Array
                */
          }
});
```
From the documentation of accessors:
https://deck.gl/#/documentation/developer-guide/using-layers?section=accessors
all accessors should work the same (at least nowhere an exception is stated), having an obj and objInfo argument when data is non-iterable, but they are not. Further it is not clear to me how to access the data (in the case of a non-iterable data object) from within the getColorValue and getColorWeight accessors?

kind regards

**Comment by Pessimistress** [comment]
Technically `getColorValue` and `getElevationValue` are not accessors because they are not called with the original input data. Even if we supply the `objInfo` argument you won't be able to map it back to your `data` object.

@heshan0131 I think it's reasonable to expose the original index of the item in the aggregated items?

**Comment by derMart** [comment]
thanks, yes exposing the indices would be helpful, even better if the original data object could be accesible using the second parameter similar to objInfo for accessors.
Ok, getColorValue is not an accessor, what about getColorWeight?

While it doesn't state that all get* properties are accessors ;-), this line in the documentation:

> All accessor prop names start with get.

might be a bit misleading. Nowhere in the docs is stated which properties starting with get are accessors and which are not.
