### ISSUE TITLE
can tile3dlayer render 3dtiles  not on cesium ion?

### ISSUE THREAD

**Issue by yuxiangyu** [visgl/deck.gl#4457]
we use the tile3dlayer to render 3dtiles on my own web server, but it seems not work.

**Comment by xintongxia** [comment]
@yuxiangyu 

In that case, use `Tiles3DLoader`, and the default [`loader`](https://github.com/uber/deck.gl/blob/master/docs/layers/tile-3d-layer.md#loader-object) for deck.gl `Tile3DLayer` is `Tiles3DLoader`.

**Comment by yuxiangyu** [comment]
Yes, I have used Tiles3DLoader,and the code is just like this:
const layer = new Tile3DLayer({
      id: 'tile-3d-layer',
	  data:'http://localhost:8080/testdata/NewYork/tileset.json',
		        loader: Tiles3DLoader,
     loadOptions: {
		//  headers:header,
		loadGLTF:true,
		}
    })
and it report an error in chrome：
![image](https://user-images.githubusercontent.com/965278/78733472-2ad72280-7978-11ea-8d28-2d64ed681ce9.png)
but in cesium it can be rendered correctly whithout any report

**Comment by yuxiangyu** [comment]
Sorry , the error is :Failed to load resource: the server responded with a status of 404 ()
webpack-internal:///./node_modules/@loaders.gl/tiles/dist/esm/tileset/tileset-3d.js:506 A 3D tile failed to load: undefined fetch failed 404 <!doctype html><html lang="en"><head> 
Can you give some suggest？
And another thing is how about the header? sometimes it can appera the crossorigin error

**Comment by yuxiangyu** [comment]
Failed to load resource: the server responded with a status of 404 () :8080/testdata/NewYork/undefined?v=1.0:1 
webpack-internal:///./node_modules/@loaders.gl/tiles/dist/esm/tileset/tileset-3d.js:506 A 3D tile failed to load: undefined fetch failed 404 <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-

**Comment by yuxiangyu** [comment]
I debuged the loaders.gl and have found the problem: In the  function normalizeTileData(tile, options) {
  if (tile.content) {
		tile.contentUrl = `${options.basePath}/${tile.content.uri}`;
  }
it used the tile.content.uri, but in many other 3dtiles it used the tile.content.url for example the 3dtiles file of NewYork city

**Comment by xintongxia** [comment]
@yuxiangyu 

Thanks for helping. I'll put up a fix in loaders.gl.

You can pass in the `headers` to layer's `loadOptions` does it work for you?

**Comment by yan-map** [comment]
> @yuxiangyu
> Thanks for helping. I'll put up a fix in loaders.gl.

Hi! Any update there? Thank you!
