### ISSUE TITLE
Provide onInteractionStateChange similiar to InteractiveMap

### ISSUE THREAD

**Issue by athomann** [visgl/deck.gl#4476]
#### Target Use case
The current way to get interactionState is from the `onViewStateChange` prop, however that callback doesn't trigger at the same way as `onInteractionStateChange`. `onInteractionStateChange` will trigger `isZooming: false` when you stop wheel scrolling, while `onViewStateChange` will not.  

#### Proposed feature
Provide onInteractionStateChange similiar to InteractiveMap

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Consolidating with #5089
