### ISSUE TITLE
Going underground

### ISSUE THREAD

**Issue by mogmog** [visgl/deck.gl#4480]
Pipes etc may have geojson that is below 0 altitude.

ESRI and other mapping libraries often allow you to configure the camera to be able to swing it under ground ground to view these layers that the ground tiles are normally obscuring.

How would I acheive this in Deck?

**Comment by kylebarron** [comment]
Have you tried plotting data with negative z coordinates? If you don't render a basemap, e.g. a `StaticMap` from React Map GL, I'd guess that the underground data would show.

**Comment by mogmog** [comment]
But there will still be an issue with the fact that the camera (correctly, most of the time) stopped at zoom level 20/altitude 0.

If there is geojson that is deep deep underground, this behaviour will stop me getting close and inspecting that geojson

**Comment by mogmog** [comment]
https://developers.arcgis.com/javascript/latest/sample-code/sceneview-underground/index.html

**Comment by mogmog** [comment]
press the go underground button

**Comment by kylebarron** [comment]
Weird. So when you go underground it changes the camera to be looking _up_. I think you could implement a similar thing in Deck.gl, where you use the normal `MapView` or `FirstPersonView` for above-ground. And then subclass either of the two for your specific below ground case, and switch between them with a button.

**Comment by mogmog** [comment]
What I am unclear about it is what defines camera being 'below ground'? A minus altitude ? It doesnt seem to like such a thing and fails with Error: failed to invert matrix.

**Comment by Pessimistress** [comment]
You can change the `maxZoom` and `maxPitch` of MapView: https://deck.gl/#/documentation/deckgl-api-reference/views/map-view

Looking “up” would be pitch>90.
