### ISSUE TITLE
MVT subLayer filtering

### ISSUE THREAD

**Issue by mogmog** [visgl/deck.gl#4481]
I am trying to  draw all lakes visible on the map with a layer that will eventually use a custom shader.

For this, I believe the approach is to use a MVT layer to get the lake location data, and then for all lakes, draw a custom SolidPolygonLayer?

Therefore I need to somehow filter the data set that the MVT later returns and only render one of those features.

This is what I have so far, but its not quite right,  can anyone advise the way to achieve this?

![image](https://user-images.githubusercontent.com/934073/79101451-6c911000-7d60-11ea-9734-7c92c519076a.png)

**Comment by Pessimistress** [comment]
It's not super clean but you can do it like this:

```js
renderSubLayers: props => {
  const data = Array.isArray(props.data)
    // resolved
    ? data.filter(...)
    // pending
    : data.then(features => features.filter(...));

  return  new SolidPolygonLayer(props, {
    // override props fields
    data
  })
}
```

**Comment by Pessimistress** [comment]
Update: as of deck.gl v8.2 TileLayer always passes down resolved data (i.e. never a Promise), so you can do

```js
renderSubLayers: props => {
  return  new SolidPolygonLayer(props, {
    // override props fields
    data: props.data.filter(isPolygonFeature)
  })
}
```
