### ISSUE TITLE
setProps(layers) can not  work in 8.x?

### ISSUE THREAD

**Issue by yuxiangyu** [visgl/deck.gl#4486]
In the deck's pure-js application , I often used inital the layers firstly like "layers=[new GeoJosonLayer{}] " and then use "deck.setProps(layers)" in 7.x . It can work fine, but when I changed to 8.x yesterday, I suddenly found that can't work. why? what is the correctly method to define before change layers in 8.x?

**Comment by Pessimistress** [comment]
`deck.setProps({layers})`

Nothing changed there between v7 and v8.

**Comment by yuxiangyu** [comment]
I have found the reason, in v8.x the deck cannot be defined as a global variable if you want to use the method setProps. Is it a bug?

**Comment by Pessimistress** [comment]
I see. `deck` is a global object created during initialization. I would recommend naming your own variable something else.
