### ISSUE TITLE
Euler Angles Cause Gimbal Lock

### ISSUE THREAD

**Issue by brswan** [visgl/deck.gl#4491]
I'm using a 3D model that has pitch, roll, and yaw inside of a Scene Graph.

I have noticed, what I think is a Gimbal Lock issue due to the Euler Angles.  https://en.wikipedia.org/wiki/Gimbal_lock

I have used both the getOrientation method and the getTransformMatrix methods.

Has anyone had a similar issue?

**Comment by ibgreen** [comment]
> I think is a Gimbal Lock issue due to the Euler Angles.

@brswan The standard remedy for gimbal lock is to use quaternions. See e.g. [Quaternion](https://math.gl/modules/core/docs/api-reference/quaternion) in math.gl. 

@tsherif

**Comment by brswan** [comment]
@ibgreen Thank you.  I am new to 3D programming so this is helpful.  I have the roll, pitch, yaw angles in degrees.  I am a little lost as to how I would do these calculations with Quaternion and deck gl.

Am I correct in thinking I need to convert the Euler angles into a Quaternion?  Then perform my rotations on the quaternion?  Any help or point in direction would be greatly appreciate.  Thank you

**Comment by ibgreen** [comment]
gimbal lock doesn't really happen in a static situation. It tends to happen when you "compose" euler angles. If you keep rotating an object by applying new Euler angles. 

If you are doing this you can maintain the rotation of the object in a quaternion, and multiply that with another quaternion that represents the incremental rotation. Quaternions can e.g. be converted to matrices that can then be further multiplied to compose with other transformations.

Scenegraphs are unfortunately not an emphasized feature of deck.gl and luma.gl but there is lots of material on the internet on scenegraphs and quaternions, and as the approach really depends on how your code is structured now, maybe just google "replace euler with quaternion"?

On the other hand, if you are not actually updating rotations, you are probably not suffering from gimbal lock...

**Comment by brswan** [comment]
Thank you for the information.  
That does bring up a good point because I am only updating the values statically.  I'm not using animations.

**Comment by tsherif** [comment]
It is possible to see gimbal lock without animation. It depends on the order in which you apply the angles. Try using the `getTransformMatrix` accessor and create a rotation matrix with the angles applied in a different order.

**Comment by tsherif** [comment]
Also can you post the code you're using to create the transform matrix and describe the phenomenon you're seeing?

**Comment by brswan** [comment]
The first two images appear pitch and roll are locked.  I am using getTransformationMatrix here
![01](https://user-images.githubusercontent.com/10222248/79326786-6fffd500-7ee1-11ea-83f2-58c3bf38a86c.png)
![02](https://user-images.githubusercontent.com/10222248/79326787-70986b80-7ee1-11ea-978b-7c5731195abc.png)


These two have the same issue.  I'm using getOrientation here
![03](https://user-images.githubusercontent.com/10222248/79326788-70986b80-7ee1-11ea-8619-fcbd30d438c7.png)
![04](https://user-images.githubusercontent.com/10222248/79326789-70986b80-7ee1-11ea-87c2-4f173b8bd760.png)



This is my actual issue.  You can see the heading stays the same, But between the two position points the aircraft is looking the wrong direction.  I'm using getOrientation here.  getTransformation Matrix has the same issue.
![05](https://user-images.githubusercontent.com/10222248/79326790-70986b80-7ee1-11ea-929b-593dde5559a2.png)
![06](https://user-images.githubusercontent.com/10222248/79326792-71310200-7ee1-11ea-9560-befd2bebe501.png)


Hopefully you can install the code with npm install.

The hamburger button reveals 3 pages: Dashboard, Matrix, and Scene Graph Layer.

The dashboard show the loop that is causing me the problem.  You can click through each datapoint and see the issue using the Playback Track.  If you disable the bank during the loop, the loop does look better.

The Matrix page allows you to manipulate the 3d object using matrix transformations.  I have a button that will perform the transformation in the order stated.

The scene graph layer is the final one.  It uses Orientation.  You must have it in the form of "0,0,0".

Thank you so much for you assistance with this!
[Slimmed.zip](https://github.com/visgl/deck.gl/files/4480888/Slimmed.zip)

**Comment by brswan** [comment]
I'm still stuck with this problem.  We are you able to replicate this or have any potential solutions?

Thanks

@ibgreen @tsherif

**Comment by ibgreen** [comment]
@brswan I do not have time to look into the detail of your example, but assuming it is a static gimbal lock situation, I would still start by trying to replace Euler angles.

You can set up a matrix and call rotateX, rotateY, rotateZ, or create a quaternion for each axis rotation and multiply them.

```
import {Matrix4} from '@math.gl/core';
const rotation = new Matrix4().rotateX().rotateY().rotateZ(); // or rotateXYZ()
```

I personally rarely use Euler angles for the reasons you have found out, and I do not have the mapping from Euler angles to other operations fresh in mind - there may be a couple of caveats compared to my simplistic code above. 

But again, there is an impressive wealth of resources on this topic on the web, e.g.: https://www.andre-gaschler.com/rotationconverter/

**Comment by akre54** [comment]
For future, this is how I solved it with gl-matrix:

```ts
const RADIAN_PER_DEGREE = Math.PI / 180

getTransformMatrix: (d) => {
  const mat = mat4.create()

  mat4.rotateX(mat, mat, d.roll_deg * RADIAN_PER_DEGREE)
  mat4.rotateY(mat, mat, d.heading_deg * RADIAN_PER_DEGREE)
  mat4.rotateZ(mat, mat, d.pitch_deg * RADIAN_PER_DEGREE)
  
  // Axis to rotate around (1, 0, 0) for x, (0, 1, 0) for y, and (0, 0, 1) for z
  const axis = vec3.fromValues(0, 1, 0)
  mat4.rotate(mat, mat, degrees * RADIAN_PER_DEGREE, axis)
  return mat as number[]
},
```
