### ISSUE TITLE
Triggers in TripsLayer

### ISSUE THREAD

**Issue by eportico** [visgl/deck.gl#4492]
#### Target Use case

That we can position vehicles in a timestamp and modify trailLength without change data

#### Proposed feature

Pass currentTime and trailLength to ancestors to we can use updateTriggers in TripsLayer

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Do you mind provide a code snippet of what you are trying to do? `currentTime` and `trailLength` do not require updateTriggers to update.
