### ISSUE TITLE
Cesium world terrain

### ISSUE THREAD

**Issue by mogmog** [visgl/deck.gl#4500]
Am I right in saying that currently the Cesium loader is only for 'assets' that you provide a Ion asset id to?

I am more interested in accessing the Cesium world terrain (https://cesium.com/content/#cesium-world-terrain)

This uses a format called quantised mesh - are there plans on the road map to create a loader for this?

**Comment by ibgreen** [comment]
@mogmog 

History: The loaders.gl team had some discussions with the Cesium folks in the past but our initial push on terrain support and the deck.gl TerrainLayer ended up using the mapbox terrain data service and elevation bitmaps, but we'd love to support the 3D tile terrains as well.

We are building a growing family of geospatial and 3D loaders [loaders.gl](https://loaders.gl). in Adding a loader for this terrain format to loaders.gl makes perfect sense. It already has 3D tile loaders and TerrainLoaders. A starting point would be to open a ticket there.

The good news is that:
- there is most likely already an open source Cesium implementation of this format that could be used as a base
- The loaders.gl team can provide tech leadership/guidance and reviews if someone would like to contribute an implementation. 

If you are interested let us know.

**Comment by kylebarron** [comment]
See prior work here: https://github.com/heremaps/quantized-mesh-decoder/blob/master/src/index.js

**Comment by ibgreen** [comment]
Great, that looks clean and MIT licensed. So for the loader part, it may be mostly a matter of packaging that module into a loaders.gl loader. 

Then understanding if there are any particularities with the resulting mesh, metadata etc, or if it can just be used directly.

**Comment by kylebarron** [comment]
It looks to be a standard mesh, along the same lines of what Martini exports when using the heightmaps. 

There is some interesting metadata in the tiles, which might help with rendering at high pitch.
```c++
    // The minimum and maximum heights in the area covered by this tile.
    // The minimum may be lower and the maximum may be higher than
    // the height of any vertex in this tile in the case that the min/max vertex
    // was removed during mesh simplification, but these are the appropriate
    // values to use for analysis or visualization.
    float MinimumHeight;
    float MaximumHeight;

    // The tile’s bounding sphere.  The X,Y,Z coordinates are again expressed
    // in Earth-centered Fixed coordinates, and the radius is in meters.
    double BoundingSphereCenterX;
    double BoundingSphereCenterY;
    double BoundingSphereCenterZ;
    double BoundingSphereRadius;

    // The horizon occlusion point, expressed in the ellipsoid-scaled Earth-centered Fixed frame.
    // If this point is below the horizon, the entire tile is below the horizon.
    // See http://cesiumjs.org/2013/04/25/Horizon-culling/ for more information.
    double HorizonOcclusionPointX;
    double HorizonOcclusionPointY;
    double HorizonOcclusionPointZ;
```

**Comment by ibgreen** [comment]
Looks good. This is just a "mesh category" loader then?

**Comment by Pessimistress** [comment]
Consolidating with #4236

**Comment by factoidforrest** [comment]
Hi there, I'm wondering if this was ever implemented. Cesium has a bathymetry dataset that I can't find an alternative for. Thanks!

Or if anyone knows of a mapbox world bathymetry, that would work too!
