### ISSUE TITLE
How to update layer props in google maps?

### ISSUE THREAD

**Issue by benderlidze** [visgl/deck.gl#4501]
I can't find out how to update ScatterplotLayer with google maps. I want to change visible(by visibleVar) and radiusMinPixels, radiusMaxPixels according to var zoomLevel. 
This code does not work for me (updateTriggers part):
```
county = {
    id: 'scatterplot-layer',
    data: DATA,
    getPosition: d => {
        return [d.ACE_GEO_LNG, d.ACE_GEO_LAT]
    },
    pickable: true,
    opacity: 1,
    stroked: false,
    filled: true,
    radiusScale: 10,
    radiusMinPixels: zoomLevel,
    radiusMaxPixels: zoomLevel,
    getFillColor: d => [255, 0, 0],
    visible: visibleVar,
    updateTriggers: {
        radiusMinPixels: [zoomLevel],
        radiusMaxPixels: [zoomLevel],
        visible: [visibleVar]
    }
};
deckOverlay = new deck.GoogleMapsOverlay({
    layers: [new deck.ScatterplotLayer(county)]
});
deckOverlay.setMap(map);
```
But this works, and I can update visible prop and radiusMinPixels etc.
```
county= {...params, visible:!params.visible}
deckOverlay.setProps( {layers: [new deck.ScatterplotLayer(params)]} )
```

But I have 6 layers, and if I call `deckOverlay.setProps( {layers: [new deck.ScatterplotLayer(params)]} )`
all other layers disappear, so I have to call it like 
`deckOverlay.setProps( {layers: [new deck.ScatterplotLayer(params), layer1, layer2, layer3... ]} )`
Is there other way to update props?
Thanks

**Comment by Pessimistress** [comment]
You have to pass the entire layer array when you call `setProps`, see https://deck.gl/#/documentation/developer-guide/using-layers?section=faq

You can store all your layer instances, and update one of them like this:

```js
const layers = {
  circles: new ScatterplotLayer(...),
  ...
}

function updateLayer(id, newProps) {
  layers[id] = layers[id].clone(newProps);
  deckOverlay.setProps({layers: Object.values(layers)});
}
```

**Comment by jpoehnelt** [comment]
I also seem to have trouble with updateTriggers using the following pattern:
```js
new deck.GoogleMapsOverlay({
    layers: [new deck.GeoJsonLayer({
        updateTriggers: {
            getFillColor: [state]
        }
    })]
});
```
