### ISSUE TITLE
Very hard to find docs via google search

### ISSUE THREAD

**Issue by andybak** [visgl/deck.gl#4509]
You must be doing something wrong as almost everything turns up above the actual docs - github, gallery, examples.

Even if I search for a specific string from the docs and add "deck.gl" they don't appear.

Your SPA architecture might be breaking something? How about good old server-rendered pages for docs?

**Comment by ibgreen** [comment]
You are correct, search has always been a big issue with the single page architecture in the deck.gl website. 

The good news is that we have been moving most of the vis.gl framework websites to gatsby-generated pages which has made the sites indexable and also supports local search (See https://loaders.gl/, https://math.gl/ etc), but the deck website is more complicated and we have not completed porting it yet.

**Comment by Pessimistress** [comment]
We are migrating from Single Page App to Gatsby in the 8.2 time frame.
