### ISSUE TITLE
pathLayer is not rendering correctly

### ISSUE THREAD

**Issue by ptmstart** [visgl/deck.gl#4510]
#### Description
pathLayer in the latest deck.gl does not render a cube like before.

new behaviour
https://codepen.io/skyluker/pen/rNVvZNP

old behaviour (expected behaviour)
https://codepen.io/skyluker/pen/xxGevLb

#### Repro Steps
listed above in codepen

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]

**Comment by Pessimistress** [comment]
This is not a bug; by default paths are extruded on the XY plane. You can use `billboard: true` if you want the extrusion to always face the camera.
