### ISSUE TITLE
Render 3D buildings with deck GL and mapbox

### ISSUE THREAD

**Issue by abrown945** [visgl/deck.gl#4518]
![image](https://user-images.githubusercontent.com/23192489/79908471-49620280-83e9-11ea-9a15-53e39dab8a8d.png)

I would like to see an example of how to implement the above image if possible.

I am having trouble figuring out how to add the 3D buildings to mapbox and have it integrated with deck.gl

**Comment by ibgreen** [comment]
Have you looked at:
- https://github.com/visgl/deck.gl/tree/master/examples/get-started/pure-js/mapbox

I assume the image comes from
- https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/overview

**Comment by ibgreen** [comment]
Deleted original example link since it doesn't cover the right API. Maybe this example is more appropriate: https://github.com/visgl/deck.gl/tree/master/test/apps/mapbox-layers (since it is an internal test app it may not be fully up-to-date but at least showcases the API).

**Comment by ibgreen** [comment]
This looks relevant: https://deck.gl/gallery/mapbox-layer

**Comment by abrown945** [comment]
@ibgreen Thanks for the links. I saw the last one but it looks like that doesn't use the React version of deck.gl. Sorry for not mentioning that.

I'm not sure if I should change my question or mark this one as answered and ask a new one

**Comment by abrown945** [comment]
I'm going to mark this as closed because I think one of the links can help me figure this out. Thank you for your time!

**Comment by laijackylai** [comment]
@abrown945 May I ask how did you manage to do render the 3d buildings in the end? Thank you~
