### ISSUE TITLE
cesium 3d tiles with mapbox

### ISSUE THREAD

**Issue by theDr46** [visgl/deck.gl#4519]
Hi guys, 
I am trying to visualise my Cesium 3D tileset created from Lidar on a Mapbox basemap.
the 3d points look to be floating above the map. Any idea how to fix this?

**Comment by Pessimistress** [comment]
The basemap is always rendered at altitude=0, while your point cloud has real-world elevation. You can add `position: [0, 0, z]` to the view state to shift the the camera target by `z`.

**Comment by theDr46** [comment]
Thank, it worked

**Comment by Ravikumarmmi1** [comment]
> The basemap is always rendered at altitude=0, while your point cloud has real-world elevation. You can add `position: [0, 0, z]` to the view state to shift the the camera target by `z`.



where am i set position under new MapboxLayer({})
