### ISSUE TITLE
Text Layer fails to load on Edge browsers for release 8.1

### ISSUE THREAD

**Issue by wilson-everlaw** [visgl/deck.gl#4523]
#### Description

The Text Layer fails to display on Edge browsers. It seems to work fine on 8.0, but not on 8.1.
#### Repro Steps

https://deck.gl/#/documentation/deckgl-api-reference/layers/text-layer
Click the above link on an Edge browser and the text layer example will fail to display.

#### Environment (please complete the following information):
 - Framework Version: deckgl 8.1.2
 - Browser Version: Microsoft Edge 44.17763.831.0
 - OS: Windows 10

**Comment by Pessimistress** [comment]
Thanks for reporting. We don't have access to a box with that particular version of Edge. Can you see any error in the console log?

**Comment by wilson-everlaw** [comment]
It seems I was using an older version of Edge, I updated to the latest version and it seemed to be working properly. But to answer your question, no there was no error in the console log.

**Comment by Pessimistress** [comment]
This issue might be related to https://github.com/visgl/deck.gl/issues/4316.
Reopen if a repro is found.
