### ISSUE TITLE
TerrainLayer binding in pydeck

### ISSUE THREAD

**Issue by LjubeBoskovski** [visgl/deck.gl#4531]
#### Target Use case
 I want to be able to use the TerrainLayer in pydeck. It is not listed under the pydeck examples, so I guess it is not implemented yet?

#### Proposed feature
Sample code snippet of how it probably would be implemented:
```
import pydeck as pdk

ELEVATION_LAYER_DATA = 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/terrain.png'
TEXTURE = 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/terrain-mask.png'

layer = pdk.Layer(
        "TerrainLayer",
        data=ELEVATION_LAYER_DATA,
        elevationDecoder={
                'rScaler': 2,
                'gScaler': 0,
                'bScaler': 0,
                'offset': 0
                },
        texture=TEXTURE,
        bounds=[-122.5233, 37.6493, -122.3566, 37.8159]
        )

view_state = pdk.ViewState(latitude=37.7749295, longitude=-122.4194155, zoom=11, bearing=0, pitch=45)

# Render
r = pdk.Deck(layers=[layer], initial_view_state=view_state)
r.to_html("terrain_layer.html", notebook_display=False)
```
This sample was created following the style of the other pydeck examples and the deck.gl TerrainLayer example.

**Comment by kylebarron** [comment]
I made an example yesterday, but haven't put it on the website yet:

![image](https://user-images.githubusercontent.com/15164633/80288013-35bce180-86f2-11ea-9073-33ceeb9a56e9.png)

You'll need to add your own surface image satellite tile endpoint:

```py
import pydeck as pdk
view_state = pdk.ViewState(latitude=46.24, longitude=-122.18, zoom=11.5, bearing=140, pitch=60)
TERRAIN_IMAGE = '"https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png"'
SURFACE_IMAGE = '"..."'
ELEVATION_DECODER = {
  'rScaler': 256,
  'gScaler': 1,
  'bScaler': 1 / 256,
  'offset': -32768
};
layer = pdk.Layer('TerrainLayer', None, min_zoom=0, max_zoom=23, strategy='no-overlap', elevation_decoder=ELEVATION_DECODER, texture=SURFACE_IMAGE, elevation_data=TERRAIN_IMAGE)
r = pdk.Deck(
    layers=[layer],
    initial_view_state=view_state,
)
r.show()
```

**Comment by davidbrochart** [comment]
I'm quite new to 3D mapping and (py)deck, but is it possible to pass a quantized mesh as one produced by e.g. https://github.com/kylebarron/quantized-mesh-encoder? Or must it be encoded into a `PNG` image?

**Comment by kylebarron** [comment]
Right now deck.gl's TerrainLayer in JS only supports PNG-encoded images. In [my demo](https://github.com/kylebarron/quantized-mesh-encoder/blob/master/site/src/quantized-mesh-layer.js) in JS, I use a modified TerrainLayer that supports Quantized Mesh files.

Pydeck doesn't currently have the ability to subclass a deck layer, so the easiest way for this to work in Pydeck is to update deck.gl's TerrainLayer to allow QuantizedMesh as well.

**Comment by davidbrochart** [comment]
Thanks @kylebarron.
Is this a planned work, or not really on the roadmap? Would it add any performance gain? I guess it would allow to use other mesh generators in the back-end, instead of currently only Martini in the front-end, right?

**Comment by kylebarron** [comment]
Basically quantized mesh allows you to offload mesh creation to the backend instead of the frontend. Right now only Martini is used in the frontend because Delatin is significantly slower
