### ISSUE TITLE
calculate zoom level based on available data.

### ISSUE THREAD

**Issue by UttamRahane** [visgl/deck.gl#4538]
Is there any way in deck gl or luma gl to calculate zoom level as per the available data? EX. I'm fetching data from API and it looks like
![image](https://user-images.githubusercontent.com/21005702/80476180-a7ea2c00-8967-11ea-8855-d2edfa24277c.png)
and I want to calculate and set zoom level so it should look like
![image](https://user-images.githubusercontent.com/21005702/80476293-d23be980-8967-11ea-9033-ab4218e4c23d.png)

**Comment by kylebarron** [comment]
You should be able to calculate the bounding box from your data and then use [`fitBounds`](https://deck.gl/#/documentation/deckgl-api-reference/viewports/web-mercator-viewport?section=fitbounds).

**Comment by UttamRahane** [comment]
Thanks. that's what I was looking.
