### ISSUE TITLE
Allow use of break-word on Text Layer without a maxWidth

### ISSUE THREAD

**Issue by wilson-everlaw** [visgl/deck.gl#4540]
#### Target Use case

I'd like to display a list of words for every entity, so that the string breaks on every word (a word on each line) regardless of `maxWidth`. Currently theres no good way to do that with `break-word` without the words getting split.

It would be useful for those who need to use the Text Layer to easily display a vertical list of words.

#### Proposed feature

Have some sort of flag to ignore `maxWidth` and breaks the line for every word. Or it could be another mode all together along with `break-word` and `break-all`. 

The feature would look like this:
![Screen Shot 2020-04-28 at 12 23 59 PM](https://user-images.githubusercontent.com/54958000/80528663-27b5cd80-894b-11ea-93ea-0ca7b85522e0.png)
where each word is always its own line.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Does it work if you set `maxWidth` to `1`?

**Comment by wilson-everlaw** [comment]
No, it defaults to `break-all` whenever the `maxWidth` is exceeded.

**Comment by Pessimistress** [comment]
I think the easiest way to do this is to insert line breaks into your text strings yourself:

```js
getText: d => d.text.replace(/ /g, '\n')
```

**Comment by wilson-everlaw** [comment]
That seems to work, thanks!
