### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.depthFBO.resize')

### ISSUE THREAD

**Issue by bergkvist** [visgl/deck.gl#4542]
#### Description
The map crashes/stops responding on iPhone 7, Safari 13 when the map is touched.

#### Repro Steps
I'm using the map component below:
```jsx
import React, useState from "react"
import { MapController } from "deck.gl"
import { StaticMap } from "react-map-gl"
import DeckGL from "@deck.gl/react"
import mapStyle from "./mapStyle.json"

export default function WorldMap() {
  const [currentViewState, setViewState] = useState({
    latitude: 60,
    longitude: 8,
    zoom: 6,
    minZoom: 0,
    maxZoom: 22,
    pitch: 50,
    bearing: 0,
    width: 0,
    height: 0
  })
  return (
    <div>
      <DeckGL
        layers={[]}
        viewState={currentViewState}
        controller={MapController}
        onViewStateChange={({ viewState }) =>
          setViewState({ ...currentViewState, ...viewState })
        }
      >
        <StaticMap reuseMaps mapStyle={mapStyle} />
      </DeckGL>
    </div>
  )
}
```
The map renders correct initially on my iPhone, but as soon as I touch the map it crashes.

#### Environment (please complete the following information):
 - Framework Version: [deck.gl 8.1.3, react-map-gl 5.2.5]
 - Browser Version: [Safari 13]
 - OS: [iPhone 7, iOS 13.3.1]

#### Logs
Here you can see the stack trace from my iPhone:

![image](https://user-images.githubusercontent.com/410028/80550879-d72d8700-89c1-11ea-811b-374af0e7759f.png)
![image](https://user-images.githubusercontent.com/410028/80550899-e7ddfd00-89c1-11ea-92d0-de52d827bbe5.png)
![image](https://user-images.githubusercontent.com/410028/80550946-0f34ca00-89c2-11ea-845c-457cd5b00048.png)
![image](https://user-images.githubusercontent.com/410028/80550960-1956c880-89c2-11ea-8578-a1a4ca83784c.png)
![image](https://user-images.githubusercontent.com/410028/80550976-270c4e00-89c2-11ea-9341-9896df7b15b2.png)
![image](https://user-images.githubusercontent.com/410028/80550978-296ea800-89c2-11ea-8da4-ff1c2be3904c.png)
![image](https://user-images.githubusercontent.com/410028/80550884-dbf23b00-89c1-11ea-8c9f-22c1572103b1.png)
![image](https://user-images.githubusercontent.com/410028/80550981-2e335c00-89c2-11ea-8782-1e11a570fce8.png)
![image](https://user-images.githubusercontent.com/410028/80550988-312e4c80-89c2-11ea-8f5a-3fda4643612e.png)

**Comment by Pessimistress** [comment]
Fixed in 8.1.4
