### ISSUE TITLE
Can I change Cursor on hover of point?

### ISSUE THREAD

**Issue by UttamRahane** [visgl/deck.gl#4548]
In Scatterplot  layer, can I change cursor to pointer on hover of plotted points?
ex.  https://news.google.com/covid19/map

**Comment by Pessimistress** [comment]
```js
let isHovering = false;

Deck({
  ...
  onHover: ({object}) => (isHovering = Boolean(object)),
  getCursor: ({isDragging}) => (isDragging ? 'grabbing' : (isHovering ? 'pointer' : 'grab'))
})
```

**Comment by UttamRahane** [comment]
Thanks @Pessimistress .

**Comment by JG145** [comment]
Hey,

How does this work with DeckGL instead?

**Comment by Pessimistress** [comment]
`isHovering` is passed to `getCursor` as of v8.4.

**Comment by spiderdab** [comment]
Version 8.8.15 here.
Is it possible that ScatterplotLayer doesn't implement getCursor? I needed to read 'isHovering' to change the cursor, but it seems to me that nothing changes if using it.
i.e.:
```
getCursor: (cursor: any) => {
      console.log(cursor);
      return 'crosshair';
}
```
doesn't log anything, nor changes cursor to 'crosshair'.

**Comment by chriszrc** [comment]
I got here because the cursor wasn't changing, but I'm using the `GoogleMapsOverlay` and realized I needed to change the google map cursor instead, so this worked just fine:

```
getCursor: ({ isHovering, isDragging }) => {
      if (isHovering) {
        map.setOptions({ draggableCursor: "pointer" });
      } else {
        map.setOptions({ draggableCursor: "" });
      }
      return "grab";
    },
```
