### ISSUE TITLE
ArcLayer .json Flow Column

### ISSUE THREAD

**Issue by schandler88** [visgl/deck.gl#4552]
I've been attempting to replicate the ArcLayer example but I'm confused about the sample json "flows" column. 

> {
>   "type": "FeatureCollection",
>   "features": [
>     {"type":"Feature","properties":{"name":"Los Angeles, CA","flows":{"3":13,"8":-30,...
> 
for the array **flows** - the first digit: **"3"** 
I believe this digit is referencing the seqential order of the subseqent features _(3rd one on the list)_

but I can't figure out what the second number references **:13**

## Is there someone who can break down this flow array or point me in the direction on how to replicate it?

THANK YOU!!

**Comment by Pessimistress** [comment]
All deck.gl layers use accessors for styling, so that you can calculate color/width etc. from your own data format. I do not think you should spend time trying to reshape your data into the format of a particular example.
