### ISSUE TITLE
i3sLayer support

### ISSUE THREAD

**Issue by The-End-Hero** [visgl/deck.gl#4554]
https://tiles.arcgis.com/tiles/m0PBUckKDOxneVs5/arcgis/rest/services/test_3d_logo/SceneServer/layers/0

For the above services, i3sLayer reports an error.
![image](https://user-images.githubusercontent.com/19590233/80689842-7c4e7980-8b00-11ea-88ea-ab227a1b752b.png)

**Comment by The-End-Hero** [comment]
https://tiles.arcgis.com/tiles/m0PBUckKDOxneVs5/arcgis/rest/services/test_3d/SceneServer/layers/0
The above services can be displayed normally

**Comment by mdt-kathur** [comment]
same error here.

I used ArcGIS pro to publish scene service, and encounter this error.

I noticed that on this scene service, in the JSON file the defaultGeometrySchema has several labels and there's a "region" label

ordering: [
"position",
"normal",
"uv0",
"color",
"region"
]

my guess is that, loaders.gl currently doesn't support region.
