### ISSUE TITLE
Programatically dispatching pointer events?

### ISSUE THREAD

**Issue by josh-byster** [visgl/deck.gl#4555]
Is there any way to dispatch a pointer event via JavaScript that would be handled by the DeckGL `onClick` prop? I would like to click at a certain location programmatically as part of an automated test suite. I keep trying different combinations of properties of the form:

```
var evt = new PointerEvent('mouse',{clientX: 610, clientY: 209, pointerType:"pointerup"})
document.getElementById("view-default-view").dispatchEvent(evt);
```

However, I try logging out in my `onClick` handler the result of every click event, namely I log the second argument passed to the callback which seems to contain picking events. Nothing gets logged when I run a command like the above, but it works completely fine when I issue a manual click with my mouse.

Thank you!

**Comment by Pessimistress** [comment]
You need to trigger both `pointerdown` and `pointerup` to get a click event.

**Comment by josh-byster** [comment]
@Pessimistress thank you for the response. However I'm trying to dispatch both events and I don't seem to get a result with that either.

For example I created [this](https://codepen.io/jbyster/pen/eYpGzQj?editors=1111) Codepen where clicking in the canvas causes a log of `"Click event"` in the console.

However, I added at the bottom of the JavaScript a commented-out delayed click:

```
setTimeout(() => {
    var evt = new PointerEvent('pointerdown');
    document.getElementById("deckgl-overlay").dispatchEvent(evt);

    var evt2 = new PointerEvent('pointerup');
    document.getElementById("deckgl-overlay").dispatchEvent(evt2);
  
},1000);
```

If I uncomment this and run it, not only does no click event get logged to the console, but further when I click around manually on the canvas, nothing gets logged anymore. I'm not quite sure what's happening—perhaps I'm incorrectly dispatching events or at least the wrong events?

**Comment by Pessimistress** [comment]
Try this:

```js
var evt = new PointerEvent('pointerdown', {clientX: 100, clientY: 100});
document.getElementById("deckgl-overlay").dispatchEvent(evt);
var evt2 = new PointerEvent('pointerup', {clientX: 100, clientY: 100});
window.dispatchEvent(evt2);
```

**Comment by josh-byster** [comment]
Yes, that fixed it! For anyone looking in the future, I had to change from `deckgl-overlay` to `deckgl-wrapper` presumably because I'm using it with React in my project, but the above works flawlessly. Thank you!
