### ISSUE TITLE
.onViewStateChange not firing when using .setProps({viewState: ...})

### ISSUE THREAD

**Issue by CaptainMack** [visgl/deck.gl#4556]
Hello all,

I am trying to use deck.gl on top of Mapbox in my Vuejs application. I have opted for the first option in the Getting Started article: 

> _Using the Deck canvas as a overlay on top of the Mapbox map, in pure JS or React. This is the most tested and robust use case._ is still the most robust use-case?

I've set it up, so I can control the map and Deck canvas synchronously using mouse, by calling map.jumpTo in the onViewStateChange event handler. 

However, I have some preset-buttons that programmatically changes from 2D to 3D view etc., using deck.setProps. However, onViewStateChange does not get called, which means that the canvas rotates according to the setProps, but the map view does not change accordingly.

I've checked similar issues, however these use the second option of using deck.gl layers as custom Mapbox layers.

I am using initialViewState as follows:

```
initialViewState: {...this.viewState},
onViewStateChange: ({ viewState }) => {
this.viewState = viewState
this.map.jumpTo({
center: [viewState.longitude, viewState.latitude],
zoom: viewState.zoom,
bearing: viewState.bearing,
pitch: viewState.pitch
});
}
```

**Comment by CaptainMack** [comment]
I am using stateless by setting viewState instead of initialViewState - I cannot use mouse etc. to move the map, as it remains "sticky" - it returns to original viewState.

`// creating the deck.gl instance
    this.deck = new Deck({
      canvas: this.$refs.canvas,
      width: "100%",
      height: "100%",
      controller: true,
      viewState: { ...this.viewState },
      onViewStateChange: ({ viewState }) => {
        this.viewState = viewState;
        this.map.jumpTo({
          center: [this.viewState.longitude, this.viewState.latitude],
          zoom: this.viewState.zoom,
          bearing: this.viewState.bearing,
          pitch: this.viewState.pitch
        });
      },
      layers: [
        new HexagonLayer({
          id: "hexagonLayer",
          data,
          elevationRange: [0, 500],
          elevationScale: 250,
          extruded: true,
          getPosition: d => [Number(d.lng), Number(d.lat)],
          opacity: 1 /*,
          getElevationValue: points => Number(Math.random(0.1, 100))*/
        })
        /*new HeatmapLayer({
          id: "heatmapLayer",
          data,
          intensity: Number(Math.random(0.5, 10)),
          getPosition: d => [Number(d.lng), Number(d.lat)],
          getWeight: point => Number(1)
        })*/
      ]
    });`

**Comment by Pessimistress** [comment]
See [documentation](https://deck.gl/#/documentation/developer-guide/views-and-projections?section=using-a-view-class-with-view-state) on how to use stateless views.

```js
function setCamera(viewState) {
  deck.setPropse({viewState});
  map.jumpTo(...)
}

Deck({
  ...
  onViewStateChange: ({viewState}) => setCamera(viewState)
});
```

**Comment by CaptainMack** [comment]
Thank you for pointing me in the right direction @Pessimistress 

I think the key part I missed was saving the state as the last action in my onViewStateChange handler.

For anybody else, who might be having same problem, I ended up with the following:

```
    this.deck = new Deck({
      canvas: this.$refs.canvas,
      width: "100%",
      height: "100%",
      controller: true,
      viewState: { ...this.viewState },
      onViewStateChange: ({viewState}) => this.setCamera(viewState),
      layers: [
        new HexagonLayer({
          id: "hexagonLayer",
          data,
          elevationRange: [0, 500],
          elevationScale: 250,
          extruded: true,
          getPosition: d => [Number(d.lng), Number(d.lat)],
          opacity: 1 /*,
          getElevationValue: points => Number(Math.random(0.1, 100))*/
        })
      ]
    });
```
this.viewState refers to my state object in my components data () and the setCamera function from my components methods section is as follows:

```
setCamera(viewState) {
      this.deck.setProps({viewState});
      this.map.jumpTo({
          center: [viewState.longitude, viewState.latitude],
          zoom: viewState.zoom,
          bearing: viewState.bearing,
          pitch: viewState.pitch
      });
      this.viewState = { ...viewState }
}
```
