### ISSUE TITLE
`WebMercatorViewport.fitBounds` fails assertion when min latitude is -90

### ISSUE THREAD

**Issue by johallar** [visgl/deck.gl#4558]
#### Description

`WebMercatorViewport.fitBounds()` fails assertion when minimum Latitude is -90. I would expect -90 to be the lower bound for latitude (+90 works for the upper bound)

#### Repro Steps

https://codepen.io/joe-ohallaron/pen/wvKrEBd - Open browser console to see assertion failure. A minimum latitude of -89 works but once it hits -90 the assertion fails.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.16, and latest
 - Browser Version: Chrome 81.0.4044.129
 - OS: Mac OSX 10.14.6

#### Logs

```dist.dev.js:45327 Uncaught Error: @math.gl/web-mercator: assertion failed.
    at assert (dist.dev.js:45327)
    at worldToPixels (dist.dev.js:46106)
    at WebMercatorViewport.project (dist.dev.js:45821)
    at fitBounds (dist.dev.js:45391)
    at WebMercatorViewport.fitBounds (dist.dev.js:83496)
    at pen.js:5
...
```

**Comment by kylebarron** [comment]
> Because the Mercator projects the poles at infinity, a map using the Web Mercator projection cannot show the poles. Services such as Google Maps cut off coverage at 85.051129° north and south

https://en.wikipedia.org/wiki/Web_Mercator_projection#Properties

I don't think this is a bug.

**Comment by johallar** [comment]
Fair enough. I think it would still be good to be consistent between the poles (90 works and -90 doesn't), or have a documented max/min so this edge case is easily addressable.

**Comment by Pessimistress** [comment]
The WebMercator projection calculates `log(tan(PI/4 + lat/2))`

- When latitude is -90 degrees: `Math.log(Math.tan(0))` -> `Math.log(0)` -> `-Infinity` (expected)
- When latitude is 90 degrees: `Math.log(Math.tan(Math.PI / 2))` -> `Math.log(16331239353195370)` -> `37.33185619326892` (??)

JavaScript being JavaScript. -__-
