### ISSUE TITLE
Emojis (unicode) on a map

### ISSUE THREAD

**Issue by thomasgwatson** [visgl/deck.gl#4560]
hey friends,

Perhaps a little related to #3909

I am trying to put emojis on a map, in a TextLayer. Rauff rauff! 🐶 '\uD83D\uDC36'

I'm just short-cutting all points to show the dog emoji, and ensuring I have that listed in the characterSet property:

`getText: d => '\uD83D\uDC36',`
`characterSet: ['\uD83D\uDC36']`

This gets me:

![image](https://user-images.githubusercontent.com/5193218/80852520-17695100-8bde-11ea-925c-0fd58d1945cd.png)

Now, browsers are fine with '\uD83D\uDC36' (or \u{1F436} for that matter) but I suspect somewhere between the javascript running my text layer and the web.gl canvas, that something is not happy with that encoding.

Am I missing something simple to get the emoji to render with the appropriate colors or should I just concede defeat, bail on the text layer and just get emoji svg/glyphs for an icon layer?

**Comment by Pessimistress** [comment]
The text is rendered as expected. The `TextLayer` currently uses the font as a color mask (i.e. black and white) so any color in the font is lost. I don't see an easy way to fix this unless there's a reliable test to tell which characters should use the inherit colors and not be re-colored with `getColor`...

**Comment by thomasgwatson** [comment]
@Pessimistress Ok, I suspected that might be the case. Sounds like auto packing iconAtlas (paired with something like https://github.com/twitter/twemoji) is the best way to get emoji on to a deck.gl layer.

Thanks so much for the reply, really appreciate it.
