### ISSUE TITLE
Artifacts when panning when using PostProcessEffect with shared GL context

### ISSUE THREAD

**Issue by kylebarron** [visgl/deck.gl#4563]
#### Description

Best described with a gif:

![Screen Recording 2020-05-03 at 10 22 01 PM](https://user-images.githubusercontent.com/15164633/80936088-d6636f00-8d8c-11ea-9b21-b61a7b21ca9f.gif)

I've only noticed this when rendering into a GL context shared with Mapbox GL JS through `StaticMap`.

#### Repro Steps

Note, this code isn't perfectly reproducible as is, but should give a general idea. I can work to make a completely reproducible example if needed.

The `LandsatTileLayer` is a custom layer that is essentially a `TileLayer` rendering `BitmapLayer`s.

<details>
<summary>Code</summary>

```jsx
import React from 'react';
import DeckGL from '@deck.gl/react';
import { MapboxLayer } from '@deck.gl/mapbox';
import { PostProcessEffect } from '@deck.gl/core';
import { StaticMap } from 'react-map-gl';
import { getNaipUrl } from '../util';
import { NAIPLayer, MODISLayer } from '../mapbox-layers';
import { LandsatTileLayer } from '../deck-layers';
import { vibrance } from '@luma.gl/shadertools';

// You'll get obscure errors without including the Mapbox GL CSS
import '../../css/mapbox-gl.css';

const mapStyle = require('./style.json');

const initialViewState = {
  longitude: -112.1861,
  latitude: 36.1284,
  zoom: 12.5,
  pitch: 0,
  bearing: 0,
};

const vibranceEffect = new PostProcessEffect(vibrance, {
  amount: 1,
});

export default class Map extends React.Component {
  state = {
    gl: null,
    viewState: initialViewState,
    naipTileUrl: getNaipUrl(),
    
    // Show NAIP imagery at zoom >= 12
    useNaip: true
  };

  // DeckGL and mapbox will both draw into this WebGL context
  _onWebGLInitialized = gl => {
    this.setState({ gl });
  };

  _onMapLoad = () => {
    const map = this._map;
    const deck = this._deck;

    // This id has to match the id of the Deck layer
    map.addLayer(
      new MapboxLayer({ id: 'landsat-tile-layer', deck }),
      'aeroway_fill'
    );
  };

  onViewStateChange = ({viewState}) => {
    this.setState({viewState})
  }

  render() {
    const { gl, naipTileUrl, viewState, useNaip } = this.state;
    const layers = [
      new LandsatTileLayer({
        id: 'landsat-tile-layer',
        gl,
        rgbBands: [4, 3, 2],
        visible: viewState.zoom >= 7 && (viewState.zoom <= 12 || !useNaip),
      }),
    ];

    return (
      <DeckGL
        ref={ref => {
          // save a reference to the Deck instance
          this._deck = ref && ref.deck;
        }}
        layers={layers}
        initialViewState={initialViewState}
        onViewStateChange={this.onViewStateChange}
        controller
        onWebGLInitialized={this._onWebGLInitialized}
        glOptions={{ stencil: true }}
        // Weird effects with MapboxLayer
        effects={[vibranceEffect]}
      >
        {gl && (
          <StaticMap
            ref={ref => {
              // save a reference to the mapboxgl.Map instance
              this._map = ref && ref.getMap();
            }}
            gl={gl}
            onLoad={this._onMapLoad}
            mapStyle={mapStyle}
            mapOptions={{ hash: true }}
          />
        )}
      </DeckGL>
    );
  }
}
```

</details>

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.1.4
 - Browser Version: Chrome 81.0.4044.122
 - OS: Mac OS X 10.15.3

#### Logs

No errors or warnings

**Comment by Pessimistress** [comment]
If you are using mapbox already, I recommend using a [raster tile source](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#raster) in the map style. Context sharing is not meant to handle complex rendering pipelines, since we don't have full control of the GL state.

**Comment by kylebarron** [comment]
I do use a Mapbox GL raster tile source when the source data is a normal RGB image, but here my use case is extending the BitmapLayer to do [arbitrary satellite band operations](https://github.com/kylebarron/deck.gl-extended-layers/blob/ef3a49531860fa12c80a64737dd810b4ddb8da63/src/bands-bitmap-layer/bands-bitmap-layer-fragment.js#L61-L73). For example, creating [vegetation indexes](https://en.wikipedia.org/wiki/Normalized_difference_vegetation_index) on the GPU. In the example above, creating a true color is one possible band combination. The `BitmapLayer` affords this kind of custom image processing, but it seems much more difficult to extend a Mapbox raster layer.

I think here the simplest workaround is just to copy the desired image effect into my custom shader.
