### ISSUE TITLE
Increase transparency of heatmap as we move away from center. 

### ISSUE THREAD

**Issue by UttamRahane** [visgl/deck.gl#4564]
Is there a way to fade away color of heatmap from center point?
![image](https://user-images.githubusercontent.com/21005702/81058004-2fe1b000-8eeb-11ea-9c92-65fc45eece9d.png)
see the above image. the color of heatmap should reduce smoothly. 
I used
`
threshold: 0.001,
 intensity: 1.2,
 radiusPixels: 50,
`
see the color at header of arrow. it's a light yellow then it becomes slightly dark. I want to make it transparent smoothly. like
![image](https://user-images.githubusercontent.com/21005702/81058556-4a685900-8eec-11ea-8ec6-27cdf8e28fc5.png)

**Comment by 1chandu** [comment]
Can you try increasing the threshold, it increases the opacity as you go further away from the center to make those regions more transparent, at the same time pixels far way will be harder to spot.
Also in general, heatmaps work very well when looking at high density data, i.e. a given pixel color is impacted by multiple data points. And regarding the bands, we could achieve similar affect but would require some additional customization.

**Comment by UttamRahane** [comment]
@1chandu 
I tried with increasing threshold but it doesn't looks as expected. I agree that heatmap looks well for high density data. can I fill whole region/country where group of data is available with some different colors gradients according to weight (not choropleth but more smooth like heatmap or contour)?
so I want to fill all the pixels with respect to nearest data object's weight and can create a group of objects having similar weight. 
ex.  
![image](https://user-images.githubusercontent.com/21005702/81481332-e677c480-924c-11ea-9ccc-22317a358470.png)

**Comment by UttamRahane** [comment]
using isobar like
![image](https://user-images.githubusercontent.com/21005702/81481710-94846e00-924f-11ea-9c6f-608316926c57.png)
following is the perfect example which I want
![image](https://user-images.githubusercontent.com/21005702/81481737-c85f9380-924f-11ea-8611-bb0d5721c0a7.png)

**Comment by 1chandu** [comment]
> I tried with increasing threshold but it doesn't looks as expected. 

Can you create a codepen demo ([example](https://codepen.io/vis-gl/pen/bvvQXw)) and share it?

Regarding colors, If I understand right, you want to defined custom colors for weight ranges, you can do that by defining your own color set by setting `colorRange` prop.

**Comment by UttamRahane** [comment]
@1chandu default color range is also fine. I want to fill the empty area where the data points are not available and should decide colors based on nearest data points. see the demo [https://codepen.io/uttamrahane/pen/VwvxBJr](url) and providing how the output which I'm expecting
![image](https://user-images.githubusercontent.com/21005702/81506229-83e8fc00-9312-11ea-86a9-f3b75caab4d6.png)

**Comment by 1chandu** [comment]
> I want to fill the empty area where the data points are not available

`HeatMapLayer` is not designed to fill empty areas, it operates it pixel level and it is very computationally expensive.  The image in your above comment, seem to be have generated using  high density data, as you can the color variation and smooth curves. But the demo you have has only few points. 

You can use `radiusPixels` prop to some extent to color empty areas near actual data locations, and increasing this value increases that area, at the same time, it will average out hotspots.

**Comment by UttamRahane** [comment]
Then I should try with different layers, may be contour or custom layer.  tell me if you have any suggestions and thank you so much for the reply.

**Comment by robinator8** [comment]
@UttamRahane did you get anything to work? I am having a similar problem. I have a continuous set of data and I want the heatmap to display it properly (I do not want density based). Although I do not want as much interpolation.
