### ISSUE TITLE
Toggling layer visibility with a checkbox and updateTriggers

### ISSUE THREAD

**Issue by alitarraf** [visgl/deck.gl#4571]
#### Description
I am  facing issue with implementing a checkbox to turn on or off a layer in pure js using updatetriggers.
I have looked at the documentation [here](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=visible-boolean-optional-) and [here](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/layer.md#updatetriggers-object-optional).

I have this layer with the visible property controlled by a function "enabled". I added the updateTriggers for the visible property.
```
    const myIconlayer = new IconLayer({
        id: 'icon-layer',
        data:educationData.features,
        pickable: true,
        iconAtlas: './schooltr.png',
        iconMapping: ICON_MAPPING,
        getIcon: d => 'marker',
        
        visible: enabled,
        updateTriggers: {
          visible: [true, false],
        },

        sizeScale: 6,
        getPosition: d => d.geometry.coordinates,
        getSize: d => 5,
        getColor: d => [Math.sqrt(1000), 140, 0],
      });

      deckgl.setProps({
        layers: [hexagonLayer,myIconlayer],
        viewState: Object.assign({}, currentViewState)
      });
```
I am updating the visibility with the following enabled function that reads a checkbox element id.
```
    function enabled() {
      // Get the checkbox
      var checkBox = document.getElementById("Education");

      // If the checkbox is checked, display return true
      if (checkBox.checked == true){
        console.log("checkbox true")
        return true    
      } else {
        console.log("checkbox false")
        return false
      }
    }
```

However nothing happens on the map, it doesnt seem to change the visibility of the layer. However when i do it manually (replacing with false and true the visible prop) it works.

Here is an example of the working app.
https://covmob-website.herokuapp.com/
![image](https://user-images.githubusercontent.com/21084320/81225447-ed56cb00-8ff1-11ea-8f84-52d97b5af062.png)

What am I missing to make the checkbox turn on and off the visibility of the layers?

#### Environment (please complete the following information):
 - Framework Version: deck.gl latest
 - Browser Version: Chrome Version 81.0.4044.129 
 - OS: W10 64bit

**Comment by Pessimistress** [comment]
`visible` is a boolean and does not accept a function. https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=visible-boolean-optional-

Just update the value instead of using `updateTriggers`.

**Comment by alitarraf** [comment]
Removing `updateTriggers` still doesnt solve the issue.  I read [here](https://github.com/visgl/deck.gl/issues/2245#issuecomment-417343221) that I cant update layers and that is why i thought i needed the update triggers.

My checkbox is toggling but it looks like the visibility property is not reading the `enabled` function boolean return. see snapshot.
![image](https://user-images.githubusercontent.com/21084320/81226819-1d06d280-8ff4-11ea-9bbf-9ffb9c23dff9.png)

If there is a better way of doing this in pure js similar to the example of icons [here](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer) I am more than happy to try that.

**Comment by alitarraf** [comment]
just reread your comment, and now it makes more sense, you mean I should access my layer and update set the visible property to boolean. Can you point me to how to do that?

**Comment by Pessimistress** [comment]
You are correct that layer props cannot be changed after creation. Even `updateTriggers` cannot be changed. You must create a new instance of the layer if you want to update a prop. See [this example](https://deck.gl/gallery/hexagon-layer).

You can learn more about the reactive programming model in https://deck.gl/#/documentation/developer-guide/using-layers

**Comment by alitarraf** [comment]
Thanks a lot!! I used the options method and got it to work.

**Comment by ArslanAslam92** [comment]
@alitarraf I am stuck at something similar. Could you guide a bit how you achieved this?
I am also using pure javascript. I want to show/hide layer on click of a checkbox.

**Comment by alitarraf** [comment]
Hi, this is how I worked it out. Also checkout the source code for this example https://deck.gl/gallery/hexagon-layer. renderlayer function and also you can have a look at http://sets-cloud.com/covrex/

You have the `renderlayer()` function:
```
// here you are creating the option for the layer to be visible or not depending on wether the checkbox is checked or not.
    let optionsEducation = {
        visible: document.getElementById('Education').checked
      };

//here you are defining your layers parameters
const educationLayer = new IconLayer({
        id: 'education-layer',
        data:educationData.features,
        pickable: true,
        iconAtlas: './img/school.png',
        iconMapping: ICON_MAPPING,
        getIcon: d => 'marker',
        sizeScale: 5,
        getPosition: d => d.geometry.coordinates,
        getSize: d => 5,
        onHover: updateTooltipPOI,
        ...optionsEducation // <<<<<<<--------notice here we are using the optionsEducation variable in the layer
      });

// here you are setting the deckgl prop to render your layer
 deckgl.setProps({
        layers: [educationLayer],
        viewState: Object.assign({}, currentViewState)
      });
```

**Comment by ElMiguelNarvaez** [comment]
> Hi, this is how I worked it out. Also checkout the source code for this example https://deck.gl/gallery/hexagon-layer. renderlayer function and also you can have a look at http://sets-cloud.com/covrex/
> 
> You have the `renderlayer()` function:
> 
> ```
> // here you are creating the option for the layer to be visible or not depending on wether the checkbox is checked or not.
>     let optionsEducation = {
>         visible: document.getElementById('Education').checked
>       };
> 
> //here you are defining your layers parameters
> const educationLayer = new IconLayer({
>         id: 'education-layer',
>         data:educationData.features,
>         pickable: true,
>         iconAtlas: './img/school.png',
>         iconMapping: ICON_MAPPING,
>         getIcon: d => 'marker',
>         sizeScale: 5,
>         getPosition: d => d.geometry.coordinates,
>         getSize: d => 5,
>         onHover: updateTooltipPOI,
>         ...optionsEducation // <<<<<<<--------notice here we are using the optionsEducation variable in the layer
>       });
> 
> // here you are setting the deckgl prop to render your layer
>  deckgl.setProps({
>         layers: [educationLayer],
>         viewState: Object.assign({}, currentViewState)
>       });
> ```

**Comment by ElMiguelNarvaez** [comment]
@alitarraf,  would you be able to share your code? because it contains many features necessary to produce quality maps like yours!
Regards
