### ISSUE TITLE
pydeck: offline javascript throws error on Windows as encoding isn't set

### ISSUE THREAD

**Issue by bandersen23** [visgl/deck.gl#4576]
#### Description

Windows throws an error on the `js.read()` part of the cdn_picker as the default windows encoding is different from linux. 

https://github.com/visgl/deck.gl/blob/32bf7848396b817c71e87f7e9fb387f64057507f/bindings/pydeck/pydeck/io/html.py#L27

#### Repro Steps

Used the example code to test: https://github.com/visgl/deck.gl/blob/master/bindings/pydeck/examples/scatterplot_layer.py

This line is changed to:
https://github.com/visgl/deck.gl/blob/32bf7848396b817c71e87f7e9fb387f64057507f/bindings/pydeck/examples/scatterplot_layer.py#L43

```python
r.to_html("scatterplot_layer.html", notebook_display=False, offline=False)
```
#### Environment (please complete the following information):
 - Framework Version: pydeck 0.3.1
 - Browser Version: N/A in this bug
 - OS: Windows 10

#### Logs

Error thrown: 
```python
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1063293: character maps to <undefined>
```
@ajduberstein - PR coming soon.

**Comment by ajduberstein** [comment]
Fixed by #4577
