### ISSUE TITLE
TextLayer Styling

### ISSUE THREAD

**Issue by btbritz** [visgl/deck.gl#4579]
#### Target Use case
Add a cleaner look and feel of the text out of the box rather than trying to make a new custom layer altogether. Padding, border-radius, and a separate alpha channel on the background prop thats already there (Rather than it being linked to color or opacity). Maybe a slight drop shadow? Nothing crazy, just something that isn't so ridged...

#### Proposed feature
Something in the vain of:
<img width="234" alt="Screen Shot 2020-05-08 at 4 00 39 PM" src="https://user-images.githubusercontent.com/3333099/81455804-1f2c7680-9145-11ea-9e5a-95f9b3abac01.png">

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by jfuehner** [comment]
Along the same line with regards to @btbritz  enhancements to the TextLayer styling. It would be great if support was added for styling the border color and border width around the text label's bounding box...

ArcGIS Feature Service JSON has a esriTS type for TextSymbol's. The TextSymbol object supports both borderLineColor and borderLineSize properties which provide the ability style the border around the text label bounding box...

https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-TextSymbol.html

**Comment by jfuehner** [comment]
To add-on to this request. It would also be great if the TextLayer would provide the ability to add a stroke/outline to the text characters.

**Comment by Jojocaster** [comment]
While having a dedicated alpha channel shouldn't be hard (one line ot change [here](https://github.com/visgl/deck.gl/blob/f8d2a3a51abe99e0e995b4ba088c09aa7572b1c2/modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer-fragment.glsl.js#L50) and [there](https://github.com/visgl/deck.gl/blob/f8d2a3a51abe99e0e995b4ba088c09aa7572b1c2/modules/layers/src/text-layer/multi-icon-layer/multi-icon-layer.js#L76)) I'm struggling a bit to figure out how to get to the background itself - maybe padding could be handled [here](https://github.com/visgl/deck.gl/blob/f8d2a3a51abe99e0e995b4ba088c09aa7572b1c2/modules/layers/src/text-layer/utils.js#L73), and maybe handle the border radius in the shader? I'm not the best when it comes to shaders,  but as fr as I get it `alphaCutOff` seems to be determining whether we're painting the background or the text - there might be something to do there.

**Comment by Pessimistress** [comment]
The following new props are now available in 8.5.0-alpha.1:

* `background`
* `backgroundPadding`
* `outlineWidth`
* `outlineColor`
* `getBackgroundColor`
* `getBorderWidth`
* `getBorderColor`

See https://github.com/visgl/deck.gl/blob/master/docs/api-reference/layers/text-layer.md for details.

**Comment by rkhayat** [comment]
@Pessimistress thanks for the update, may I recommend `backgroundPadding` accept 4 parameters? similar to CSS, this would allow more control for each side.

**Comment by rkhayat** [comment]
Related: https://github.com/visgl/deck.gl/issues/5598

**Comment by Pessimistress** [comment]
v8.5.0 is published. Please open a new issue for any additional feature requests.
