### ISSUE TITLE
Overlayer disappear when I stop hover the map on Firefox

### ISSUE THREAD

**Issue by Nahelou** [visgl/deck.gl#4580]
Hello thanks for reading this !
I'm gis specialist (really not a dev) and I am faced with a problem that I cant solve... : 

I created a map based on Mapbox and Deckgl and I have a problem only on Firefox, (the map is here if you want to see...  [map](https://nahelou.github.io/site/pages/deck_mobiliPro/index.html) )

On Firefox ( 75.0 ), when I mouse over the map the overlayer display well, but as soon as I stop, it disappear...

I do not reproduce on Chrome/Edge/Safari, has anyone ever had the problem ?

Sorry if I'm not at the right place to ask this,
Thanks a lot

**Comment by Pessimistress** [comment]
Do you see console error when this happens?

I noticed that you are using a version that is not actively maintained (v7.1). I would recommend updating to v8, or at least the latest v7 (7.3).

**Comment by Nahelou** [comment]
Hello ! 
Yes I saw it, but I had those errors with mapbox.js on my first version of the map, but the overlayer displayed well  :'( 
I'm gonna try to update the code, because for the moment I'm with a wonderful white screen and no error on v8 haha
Thanks a lot, I close the ticket until I update the map, time to see if that fix the problem :)
