### ISSUE TITLE
Combining TileLayer with bounds

### ISSUE THREAD

**Issue by grahambates-sp** [visgl/deck.gl#4581]
How would I go about using the TileLayer to load a slippy map with url containing z/x/y values , but instead of showing the whole map, only showing the imagery up to the bounds passed in, effectively creating a cut away section of tiled imagery?

**Comment by grahambates-sp** [comment]
To clarify, I am trying to create something similar to the screenshot in 
https://github.com/visgl/deck.gl/issues/4562

but a 2D set of tiles floating above (ie with bounds), rather than 3d terrain. But same 'cut away' effect.

**Comment by grahambates-sp** [comment]
Thinking about it, maybe this doesn't make sense for TileLayer? I can create a similar effect  with a work around  by using static mapbox api and Bitmap layer.

![image](https://user-images.githubusercontent.com/45166327/81669994-e9d2a200-943e-11ea-8ec8-eb18941c1700.png)

**Comment by ibgreen** [comment]
If you are fine with clipping on tile granularity:
- You can raise the tiles off the ground by providing a modelMatrix prop. 
- I expect you can customize the TIleLayers `getTileData` or `renderLayers` to not load or render tiles you are not interested in.
- If you need a "skirt" around the tiles, you probably want to use the TerrainLayer, creating fake terrain maps (I should e.g. be possible to create an elevation image with constant elevation)

- If you need to clip tiles to an arbitrary region, there is some support for clipping but not as easily accessed, you can clip images, clip geojson, do shader level clipping, but you'd probably need to dig deeper into the APIs on your own, and I expect you'd create your own skirts.

**Comment by grahambates-sp** [comment]
It's the tile granularity thing that I eventually realised might cause more problems that it's worth.

(I am same user as mogmog where I chatted before about similar work).

In case I do decide to go down the shader level route can you point me towards any code of relevance for inspiration?)

**Comment by d1ken** [comment]
So I can not make clipping like this?
Those was been done with Leaflet and leaflet-boundary-canvas plugin.
Leaflet use canvas, deck.gl use webgl, so I can not just port this plugin.
Polygons are fields boundaries of my farm.
Tiles, clipped with polygons are NDVI, them should be clipped because of much better visibility of fields boundaries.
I found clip-extension.js  on mvt-layer, but I do not understand how I can modify it for tile-layer.

![Screenshot_2020-09-19 Map](https://user-images.githubusercontent.com/1562211/93662964-cb278c00-fa6c-11ea-9591-826ce05c8d63.png)

**Comment by kylebarron** [comment]
I think you're looking for the proposed Mask Effect: https://github.com/visgl/deck.gl/pull/4161/files

**Comment by d1ken** [comment]
Yes, you are right, this is what I need.
Does it planned to implement?
