### ISSUE TITLE
DeckGL is picking objects from non-pickable MVTLayer after zooming

### ISSUE THREAD

**Issue by evstinik** [visgl/deck.gl#4584]
#### Description
My layers composition:
- 4 MVTLayers as a background, fed with vector tiles, non pickable
- PolygonLayer representing interactable objects, fed with objects geometries, pickable

PolygonLayer have set up onClick handler, which works until I start zooming the map back and forth.
After zooming when I click on object only DeckGL's onClick handler gets called and the object it picks is some feature from the background MVTLayers.

#### Repro Steps
1. Open https://jsfiddle.net/hacknick/1xmh32ry/
2. Open console, so you can see log messages
3. Click on red rectangle, see that click handlers works (both layer's and DeckGL's)
4. Zoom out to max zoom allowed, then zoom in to max
5. Click on red rectangle again

Expected:
- Both layer's and DeckGL's onClick handlers get called
- Correct object is picked ({ name: 'My Rectangle', contours... } in example jsfiddle)

What we have:
- Only DeckGL's onClick handler gets called or nothing at all
- Object returned in pickingInfo is feature from Tile/MVTLayer ({"type":"Feature", ...})

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.1.5 (latest)
 - Browser Version: Chrome 81.0
 - OS: macOS Catalina 10.15.2

#### Logs
Nothing relevant

![Screenshot 2020-05-13 at 12 27 45](https://user-images.githubusercontent.com/11078071/81801811-46a08c00-9515-11ea-972e-10ef88bbcd2b.png)
![Screenshot 2020-05-13 at 12 28 16](https://user-images.githubusercontent.com/11078071/81801819-499b7c80-9515-11ea-9ed0-9675ce40d536.png)

**Comment by Pessimistress** [comment]
Thank you for reporting this issue. While we work on the fix, I'd highly recommend you not using 4 MVTLayers. Every tile is downloaded and parsed 4 times if you do so. Instead, you can provide your own [renderSubLayers](https://deck.gl/#/documentation/deckgl-api-reference/layers/tile-layer).

**Comment by evstinik** [comment]
> Thank you for reporting this issue. While we work on the fix, I'd highly recommend you not using 4 MVTLayers. Every tile is downloaded and parsed 4 times if you do so. Instead, you can provide your own [renderSubLayers](https://deck.gl/#/documentation/deckgl-api-reference/layers/tile-layer).

Thank you for the response and recommendation. 

Just to be clear, we're using 4 _different_ sets of data (in difference to the example fiddle provided), so each layer is unique. Also each layer has to have unique stroke/fill colors and option to toggle visibility in UI.

**Comment by Pessimistress** [comment]
Fix is published in 8.1.6

**Comment by evstinik** [comment]
@Pessimistress thank you! Everything works! :)
