### ISSUE TITLE
Unable to find React-Map-GL feature data

### ISSUE THREAD

**Issue by seeyijie** [visgl/deck.gl#4585]
Hello, 

In a related issue: https://github.com/visgl/deck.gl/issues/4399

I was able to get it work and running, however, I realised if I am unable to get data from Mapbox Studio and all the data sets I uploaded there. I am now, only limited to the data I have with my Deck.gl layers.

I have referred to the particular documentation:
https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/overview?section=using-with-react

I am sure I have successfully injected layers into Mapbox, however, I am unable to get the features from Mapbox styles. Is there any solution to it?

Thank you.

**Comment by kylebarron** [comment]
That documentation you pointed to is an advanced case of rendering Deck.gl _underneath_ Mapbox layers. It's not necessary for simple cases.

You can use data from Mapbox Studio if you render it with `Source`s and `Layer`s from React Map GL, which is equivalent to using Mapbox GL JS.

**Comment by seeyijie** [comment]
Thank you @kylebarron. 

I am using it for a project that requires data using deck.gl layers and data from mapbox studio. I am also using Nebula.gl EditableGeoJsonLayer which is compatible to deck.gl for some geospatial analysis.

**Comment by Pessimistress** [comment]
What do you mean by "get the features from Mapbox styles"? Are you having trouble displaying them or querying them?

**Comment by seeyijie** [comment]
@Pessimistress Sorry, I should have make it clearer, I meant source layer of Mapbox. I am able to see how I style the source layer of the data, however, I am unable to query it. 

```
  function handleOnHover(event) {
    const {
      features,
      x,
      y,
      // lngLat,
    } = event;
    setX(x);
    setY(y);
    console.log(event);
}
```

This is what I see when I console.log(event) when I hover tilesets hosted by Mapbox (OSM data, other custom tilesets)

![image](https://user-images.githubusercontent.com/36152992/81883669-680e8000-95c8-11ea-8734-f9243a75f0fb.png)

This is also what I see when I hover on a deck.gl layer.
![image](https://user-images.githubusercontent.com/36152992/81883744-9b510f00-95c8-11ea-9684-73af8a013931.png)

**Comment by Pessimistress** [comment]
deck.gl does not have visibility into the features of the base map. You can use https://visgl.github.io/react-map-gl/docs/api-reference/static-map#queryrenderedfeatures

**Comment by seeyijie** [comment]
Thank you @Pessimistress ! This solves the issue.
