### ISSUE TITLE
FlyTo then highlight?

### ISSUE THREAD

**Issue by btbritz** [visgl/deck.gl#4590]
I've tried to search for this functionality in the docs but seem to be missing it.

Scenario: I have a search bar that filters a copy the plotted data based off of user input. After the user selects a filtered data point, I use the `FlyToInterpolator` to "travel" to the corresponding node on the deck. 

At this point I'd like to highlight that that selected node that the user has flown to because that particular node could be set within a series of 100 nodes or more.

Is something like this possible?

Thanks!

**Comment by Pessimistress** [comment]
See `autoHighlight` and `highlightedObjectIndex` in [Layer props](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer)

**Comment by btbritz** [comment]
Ah thank you! Must have looked right over it...several times...
