### ISSUE TITLE
How to set vertical height( or altitude ) of IconLayer or TextLayer 

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4599]
Hi, can you please suggest me how to set vertical height( or altitude ) of IconLayer or TextLayer 
![360截图20200518113210704](https://user-images.githubusercontent.com/24310750/82171937-4b8d8300-98fb-11ea-8202-f3b5013acca7.jpg)
? 

![360截图20200518112924632](https://user-images.githubusercontent.com/24310750/82171817-f81b3500-98fa-11ea-89da-1e5f8186fda5.jpg)

**Comment by Pessimistress** [comment]
Return a 3D point with `getPosition`.

**Comment by Doraemonnn** [comment]
Like this? It doesn't work ...

![360截图20200519161149968](https://user-images.githubusercontent.com/24310750/82302200-d8b00500-99eb-11ea-8908-ffb3a2a87eee.jpg)

**Comment by Pessimistress** [comment]
Yes it does work. Your problem is #4600.
