### ISSUE TITLE
GeoJsonLayer and IconLayer intersect

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4600]
When adding geojson layer and iconlayer layer at the same time, geojson will pass through the middle of iconlayer. How can I solve this problem?

![360截图20200518154259160](https://user-images.githubusercontent.com/24310750/82187160-940a6800-991e-11ea-9990-db384a2eb16a.jpg)

**Comment by Pessimistress** [comment]
Looks like your icons do not have their anchors set correctly. See `anchorX` and `anchorY` in [documentation](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer?section=properties).

**Comment by Doraemonnn** [comment]
I set the anchorY property. But the effect is not good. When I reduce the map, the elevation of the icon will increase. Just like this ...


![360截图20200519171708429](https://user-images.githubusercontent.com/24310750/82308769-d4d4b080-99f4-11ea-8d2f-5e2bc724fe57.jpg)
![360截图20200519171719859](https://user-images.githubusercontent.com/24310750/82308811-e0c07280-99f4-11ea-8f00-9837d7ab1e87.jpg)

**Comment by Pessimistress** [comment]
Without you sharing any details on what you tried I can only guess from your screenshot. You probably did not set anchorY correctly. See [example](https://github.com/visgl/deck.gl/tree/master/examples/website/icon/data).

**Comment by Doraemonnn** [comment]
@Pessimistress 
The GeojsonLayer corresponds to the blue area on the map.  And the IconLayer corresponds to the green icon on it.  I set the height of GeojsonLayer to 300 and the anchorY of IconLayer to 300. However, the icon doesn't stick to the map. As shown in the figure above

![360截图20200520090843094](https://user-images.githubusercontent.com/24310750/82393781-fcba2780-9a79-11ea-8da9-2f9db65896da.jpg)
![360截图20200520090924740](https://user-images.githubusercontent.com/24310750/82393786-ffb51800-9a79-11ea-98f6-8a5aa6e6f4a5.jpg)

**Comment by Pessimistress** [comment]
anchorY is in pixels relative to the icon itself. 0 is top and 128 (height) is bottom.

**Comment by Doraemonnn** [comment]
@Pessimistress 
I wonder is it possible to hover the icon on the geojsonLayer with height. 

![360截图20200520162410966](https://user-images.githubusercontent.com/24310750/82423605-93a4d500-9ab6-11ea-9d18-09a64995e5c6.jpg)

**Comment by Pessimistress** [comment]
Set `z` in `getPosition` to the height of your polygon.

`getPosition` defines the world position (lon, lat, alt) where you want to render the icon.

`anchorY` defines how you want to place the image relative to the world position.
