### ISSUE TITLE
Hexagon color rendered with H3HexagonLayer doesn't match value set in getFillColor

### ISSUE THREAD

**Issue by lcastillo84** [visgl/deck.gl#4601]
#### Description
Hexagon's fill color in rendered **H3HexagonLayer** doesn't match the value set in getFillColor accessor. See example in the picture below:

![H3HexagonLayer_issue_50](https://user-images.githubusercontent.com/30120511/82234999-27807080-9900-11ea-95a4-8b68fe02d32d.png)

#### Repro Steps
1. Create DeckGL map within a React app.
2. Add H3HexagonLayer and set `getFillColor: [255, 0, 0], `
3. Use any color picker browser [extension](https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg) to check the color of rendered hexagon. Rendered color is rgb(176, 0, 0) instead of rgb(255, 0, 0)

##### Code example (App.js)
```
import React from 'react';
import DeckGL from '@deck.gl/react';
import { StaticMap } from 'react-map-gl';
import { H3HexagonLayer } from '@deck.gl/geo-layers';

const initialViewState = {
  latitude: 8.993370,
  longitude: -79.529865,
  zoom: 13
}

function App() {

  const layers = [
    new H3HexagonLayer({
      data: [
        { hex: '8866a5045bfffff', value: -1 },
        { hex: '8866a506e1fffff', value: 1 },
      ],
      pickable: true,
      extrude: false,
      getHexagon: (d) => d.hex,
      getFillColor: [255, 0, 0], 
      getElevation: (d) => 0,
    },
    )
  ]

  return (
    <div>
      <span>Expected Color rgb(255,0,0): </span>
      <div style={{ backgroundColor: 'rgb(255,0,0)', borderRadius: '50%', height: 15, width: 15, display: 'inline-block' }}></div><br />
      <span>Resulting Color rgb(176,0,0): </span>
      <div style={{ backgroundColor: 'rgb(176,0,0)', borderRadius: '50%', height: 15, width: 15, display: 'inline-block' }}></div>
      <div style={{ height: 400, width: 800, position: 'relative' }}>
        <DeckGL
          controller={true}
          initialViewState={initialViewState}
          layers={layers}
        >
          <StaticMap mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_API_KEY} />
        </DeckGL>
      </div >
    </div>
  )
}

export default App;
```

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.1.4, react-map-gl 5.2.5
 - Browser Version: Chrome 81.0.4044.138
 - OS: Windows 10 Pro 1909

#### Logs
No errors in console

**Comment by Pessimistress** [comment]
It's due to lighting. You can set `extruded: false` to turn off 3D (misspelled as `extrude` in your code sample).

**Comment by lcastillo84** [comment]
Thank you, that was it!
