### ISSUE TITLE
Dashed path animation to show flow

### ISSUE THREAD

**Issue by wonjiky** [visgl/deck.gl#4602]
If I were to try to animate dashed lines between two coordinates to show flow (like image below) what would be the best way to tackle it? I first thought it was using the TripsLayer but realised it wasn't...

Through reading other posts, I would believe the procedure to be to build a custom animated PathLayer and inject custom fragment shader?... I have no experience with WebGL so I would greatly appreciate for any tips or guidance.. Thanks in advance!
 
<img width="890" alt="Screenshot 2020-05-18 at 19 16 41" src="https://user-images.githubusercontent.com/14053486/82241466-819f2700-993c-11ea-87a6-2714ebd241b4.png">

**Comment by Pessimistress** [comment]
You can take a look at [this tutorial](https://observablehq.com/@pessimistress/deck-gl-tutorial-subclassing-a-layer?collection=@pessimistress/deck-gl-tutorials). `PathLayer`'s uv is per-segment, instead of end-to-end, but the idea would be similar.

**Comment by Pessimistress** [comment]
Example using v8.3's `highPrecisionDash` mode: https://codepen.io/Pessimistress/pen/NWrYMgr
