### ISSUE TITLE
Unexpected visual artifacts in official demo

### ISSUE THREAD

**Issue by yuanhan1890** [visgl/deck.gl#4604]
#### Description
I find there is an unexpected line in official demo; And it can be reproduced in the latest version(8.1.7) using PathLayer.
[GeoJsonLayer example](https://deck.gl/#/documentation/deckgl-api-reference/layers/geojson-layer)

#### Repro Steps
open url, and it will show **occasionally**.

#### Environment:
 - Framework Version: deck.gl@8.1.2 (i find it in header scripts)
 - Browser Version: 81.0.4044.138 (Official Build) (64-bit)
 - OS: Mac OS X 10.14.6； Graphics Intel Iris Plus Graphics 650 1536 MB

#### Logs
![image](https://user-images.githubusercontent.com/15167617/82416430-9d293f80-9aac-11ea-826a-02e169acad80.png)

**Comment by Pessimistress** [comment]
The Intel GPUs are known to have precision issues. Can you narrow it down to a small data sample - is it a tiny segment, or sharp angle?

**Comment by yuanhan1890** [comment]
@Pessimistress , Maybe i should truncate the precision of path coordinates. Thanks.

**Comment by yuanhan1890** [comment]
https://github.com/visgl/deck.gl/blob/master/modules/core/src/utils/typed-array-manager.js#L50

TypeArrayManager returns Float64Array with "-1.578406111277176e+307" filled in the last indices, and pathTesselator doesn't update positions in these indices. Maybe it is a bug, and doesn't caused by GPU compatibility.

**Comment by yuanhan1890** [comment]
[reproduce demo](https://stackblitz.com/edit/js-4q7y4z)

Reproduce steps:

1. click "toggle route", reveal green route and hide points.
2. click "toggle route", hide green route.
3. click "toggle route", reveal red route and visual artifacts.

**Comment by Pessimistress** [comment]
Thank you for the demo, I am able to reproduce the issue.

`TypeArrayManager` is expected to produce arrays larger than necessary. The excess indices are not supposed to be used by the shader. I will investigate.

**Comment by Pessimistress** [comment]
Can you confirm that this is fixed in the latest release?
