### ISSUE TITLE
I want use postProcessEffect when I extends MapboxLayer class, But the effects block the staticMap, can anyone help me? please!

### ISSUE THREAD

**Issue by tan9710630** [visgl/deck.gl#4617]
Frist the office MapboxLayer dose not support PostProcessEffect, so I custom the deck-tuis.js add this effects:
```
if (deck) {
    deck.setProps(deckProps);
    deck.props.userData.isExternal = true;
  } else {
    // Using external gl context - do not set css size
    Object.assign(deckProps, {
      gl,
      width: false,
      height: false,
      viewState: getViewState(map)
    });
    const postProcessEffect = new PostProcessEffect(brightnessContrast, {
      brightness: 0.01,
      contrast: 0.01
    });
    deck = new Deck(deckProps);
    deck.setProps({effects:[postProcessEffect]})

    // If deck is externally provided (React use case), we use deck's viewState to
    // drive the map.
    // Otherwise (pure JS use case), we use the map's viewState to drive deck.
    map.on('move', () => onMapMove(deck, map));
    map.on('remove', () => {
      deck.finalize();
      map.__deck = null;
    });
  }
```
But I get a wrong result like this:
![QQ截图20200528104345](https://user-images.githubusercontent.com/22703484/83092620-42a56a00-a0d0-11ea-9ece-34aa46ac6512.jpg)
![QQ截图20200516124135](https://user-images.githubusercontent.com/22703484/83092665-54870d00-a0d0-11ea-93d9-c512f900283d.jpg)
and even worse when I rotate the view looks like the render dose not clear last frame:
![QQ截图20200528104749](https://user-images.githubusercontent.com/22703484/83092820-b778a400-a0d0-11ea-8400-8a43e6250dc8.jpg)

**Comment by tan9710630** [comment]
I add this following code into layer's render function, and I fix the clear last frame problem.
`gl.clear(GL.COLOR_BUFFER_BIT | GL.DEPTH_BUFFER_BIT);`
still I can fix the background block problem.

**Comment by gallickgunner** [comment]
This feels very similar to https://github.com/mapbox/mapbox-gl-js/issues/9499

**Comment by kylebarron** [comment]
In general using PostProcessEffect with MapboxLayer can be difficult because of the `gl` context sharing. See: https://github.com/visgl/deck.gl/issues/4563

**Comment by Pessimistress** [comment]
When you use MapboxLayer, deck.gl and mapbox-gl share the same WebGLContext, therefore deck does not own the end-to-end rendering. This is outside of our control.
