### ISSUE TITLE
Visualizations freeze on viewState update on v 8+

### ISSUE THREAD

**Issue by haxzie** [visgl/deck.gl#4618]
#### Description
I have been using deck.gl v7.3.15 and updated to v8.*. Now, after the update, whenever I update the viewState using `setProps` the visualization freezes and it is unresponsive for scrolls or drags but the `onViewStateChanged` callback gets fired whenever I interact with it. I have gone through the migration docs for v7 -> v8 but there is no mention of changes for methods/functions I have been using. Is there anything that I am missing? I am using mapbox-gl as base with deck-gl as controller, all the interactions are controlled by deck-gl and the map responds to the changes but the visualizations dont. 

This was the behavior on v7.3.15
![deck-v7](https://user-images.githubusercontent.com/53584487/83111596-7db09900-a0e2-11ea-9ad5-07303e1a4f87.gif)

This is the current behavior on all versions above v8.0.*
![deck-v8](https://user-images.githubusercontent.com/53584487/83111638-8dc87880-a0e2-11ea-8998-65a92e2bb393.gif)
![v8-freeze](https://user-images.githubusercontent.com/53584487/83111657-94ef8680-a0e2-11ea-96da-f789d31be8c7.gif)

#### Repro Steps
1. Intialize a deck instance with basemap
2. change the viewstate with setProps

Ps. Change the library version to 7.3.15 and this works just fine

I have created a sample repository with the implementation here [https://github.com/haxzie/deckgl-bug-test](https://github.com/haxzie/deckgl-bug-test) you can look at the [specific file here](https://github.com/haxzie/deckgl-bug-test/blob/master/src/components/PathMap.vue)

A sample deployment with this bug reproduced -> [https://elegant-dubinsky-f4e41e.netlify.app/](https://elegant-dubinsky-f4e41e.netlify.app/) (might take a bit to load the data)

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.0 and above
 - Browser Version: FireFox 76.0.1, Chromium v83.0.4103.61
 - OS: Ubuntu 20.04

#### Logs
No logs or warnings

**Comment by Pessimistress** [comment]
https://deck.gl/#/documentation/overview/upgrade-guide?section=auto-view-state-update

You should only set `initialViewState` and never `viewState` if you want deck to track its own view state changes.

**Comment by Pessimistress** [comment]
Read about stateful/stateless usages:
https://github.com/visgl/deck.gl/issues/4556
https://github.com/visgl/deck.gl/issues/4075

**Comment by haxzie** [comment]
Awesome! Thank you @Pessimistress :+1:

**Comment by grahambates-sp** [comment]
What is useMapView imported from when you describe `const [state, dispatch] = useMapView(); `
