### ISSUE TITLE
How to cite deck.gl (bibtex entry)

### ISSUE THREAD

**Issue by bergkvist** [visgl/deck.gl#4619]
### Is there a recommended/correct way to cite deck.gl in academic publications?

What I have right now (in `references.bib`):
```bib
@online{deck.gl,
  author={Uber},
  title={deck.gl: WebGL2 powered geospatial visualization layers},
  url={https://deck.gl/#/},
  year={2016},
  urldate={2020-05-29},
}
```

**Comment by ibgreen** [comment]
@bergkvist I don't think we have ever discussed this. But it looks reasonable. 

- As a nit I'd drop the `/#/` from the URL that is just an artifact of how the site is built right now but will change.
- Uber is indeed the original author but has now donated deck.gl to the Linux Foundation (Urban Computing Foundation). Not sure if that should be captured, this looks fine.

PS - If you do cite it, would be fun to see a link to the paper when it is ready :)
