### ISSUE TITLE
Mini RFC: Improve 180th meridian handling in geospatial projection

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#4621]
#### Background

deck.gl currently does not choose the "ideal" copy of the world to project a point onto.

v6.1 introduced the `wrapLongitude` prop, which dynamically re-positions a point in the `project` shader module. It works for instanced layers with a single anchor, e.g. IconLayer and ColumnLayer, and have a somewhat unexpected effect on ArcLayer at low zoom levels (the arc would switch between the longer path and the shorter path).

The general advice we give users is to pre-process their data so that some longitudes are shifted to the neighboring world (< -180 or > 180). This is relatively easy in ArcLayer and LineLayer, but not as straightforward in e.g. PathLayer, and PolygonLayer. (#3794)

It is reasonable to expect the GeoJsonLayer and GreatCircleLayer to correctly render specification-compliant out of the box.

#### Proposal

When `wrapLongitude: true`:

1. Nothing changes for the anchored instanced layers
2. ArcLayer and LineLayer: current behavior is to always draw the link cross the longitude of the viewport center. The proposed behavior is to always draw the shortest path in terms of delta longitude. This can be done in the vertex shaders with little perf concerns.
3. PathLayer and PolygonLayer: current behavior produces visual artifacts for all features. The proposed behavior is to auto-split features at the 180th meridian. The implementation will use utilities from the new `@math.gl/polygon` module and introduce additional CPU overhead when opt-in.
4. TileLayer: currently passes `wrapLongitude` through to sublayers. The proposed behavior is to always turn the prop off. This will prevent unnecessary perf hit, given that geospatial tiles do not cross the 180th meridian. 

2 and 3 are breaking changes. However, arguably the existing behaviors are either wrong or completely unusable.

#### To Do List
  - [x] Add label and assign to milestone
  - [x] GreatArcLayer
  - [x] PathLayer
  - [x] PolygonLayer
  - [x] TileLayer
  - [x] ArcLayer
  - [x] LineLayer
  - [x] Doc update
  - [ ] What’s new update
  - [x] Upgrade guide
  - [ ] Test

**Comment by Pessimistress** [comment]
cc @kylebarron @ibgreen @heshan0131  for review

**Comment by heshan0131** [comment]
Looks good to me

**Comment by novakand** [comment]
Incorrect PathLayer display when compared to Google maps Polyline. The wrapLongitude parameter is set to true. 
Can this be somehow fixed in the near future? https://jsfiddle.net/Novakand/50uj7dbg/5/

**Comment by Pessimistress** [comment]
@novakand Your google polyline and deck overlay are using different data (longitude 153 vs -153)

**Comment by novakand** [comment]
Yes, thanks for the answer. Looked inattentively
