### ISSUE TITLE
Custom getColorValue fct to normalize variable by MAX of ALL hexagon cells

### ISSUE THREAD

**Issue by alitarraf** [visgl/deck.gl#4622]
I am creating a custom function to get the color value and elevation value of the hexagon layer. I am facing an issue in calculating data for my custom function.

Let us take this example from documentation, with the added functionality of having a variable radius implemented through options (not shown below):
```
 class MyHexagonLayer {
    renderLayers() {
      return new HexagonLayer({
        id: 'hexagon-layer',
        getColorValue: myFunction(),
        data,
        radius: 500
      });
    }
 }
```
My data looks like this: `index,lon,lat, Pharmacy, Restaurant`, with 1 or 0 as pharmacy,restaurants row values.

Now `myFunction()` goal is to normalize the number of pharmacy & restaurant in each cell. For example:
- Hex Cell 1 has 5 pharmacies, 10 restaurants --> total point of interest of 15
- Hex Cell 2 has 2 pharmacies, 7 restaurants --> total point of interest of 9
- MAX (ALL HEX CELLS) = MAX (15,9) = 15
- `myFunction()` output should be a weighted sum of pharmacy and restaurants in each cell divided by the MAX number of point of interest of all cells (in this case Max =15). This is important because the hex radius is variable, therefore, the MAX of all cells is variable. An example of what the function should return *weighted_sum / MAX_All_Hex_Cells*:
   - Hex Cell 1: (weight_A x 5+weight_B x 10)/15
   - Hex Cell 2: (weight_A x 2+weight_B x 7)/15

My issue is how do i compute the **maximum number of points of ALL HEX CELLS (15 in example above), and not IN each cell.**
I thought to calculate the sum of all points counts in each hex cell, then find the maximum value of that sum across all cells:

```
function myFunction(points) {
   //calculating weighted_sum
   let weighted_sum = arraySum(points.map(p => p['Pharmacy']))*weight_A +
              arraySum(points.map(p => p['Restaurant']))*weight_B;
  
 // calculate MAX_All_Hex_Cells
let sumHexPOI = arraySum(points.map(p => p['Pharmacy'])) + 
arraySum(points.map(p => p['Restaurant']));

 let MAX_All_Hex_Cells = Math.max(sumHexPOI); 
//this is not working, since i need to store each of the hex sumHexPOI in an array
 and compute their maximum. 

  return weighted_sum/MAX_All_Hex_Cells;

}

function arraySum(array) {
      return array.reduce((a,b) => a + b, 0);
    }
```
I can get the sum of points of interest in each hexagon, however how do I store that into an array and do a Math.max to get the maximum?

**Comment by Pessimistress** [comment]
I believe `colorRange` is automatically fitted to the extent of color values, i.e. the min of all cells is assigned the first color, and the max of all cells is assigned the last color. You should just return the weighted sum in `getColorValue`, because adjusting all of them by the same scaler has no effect.

**Comment by alitarraf** [comment]
Yes, visually colors will be automatically fitted. However I care about the range of value and need them to be from 0-10 in this specific case. Any suggestions?

**Comment by Pessimistress** [comment]
[colorDomain](https://deck.gl/#/documentation/deckgl-api-reference/layers/hexagon-layer?section=properties)?

**Comment by alitarraf** [comment]
Yes, I am using color domain to set the bound. However my issue here is how to calculate the max value ?

```
function myFunction(points) {
...
let values = points.map(p => p['Point_of_interest']).reduce((a,b)=>a+b,0);
let maxValue = Math.max(values); /// THIS IS WHERE it is failing....

...
}
```
If I `console.log(values)` I get the sum of POI in each hexagon. I tried storing them in an temporary array and then taking the max, but still not working out.
```
temp_arr.push(values);
let maxValue = Math.max(temp_arr);
```

I would appreciate any direction or hints!

Thanks!

**Comment by Pessimistress** [comment]
> Yes, I am using color domain to set the bound

I don't understand what you are trying to accomplish. If you want the max color to be applied to the max value, then simply don't use `colorDomain`. You do not have to adjust the color value.

**Comment by alitarraf** [comment]
I want to calculate the max value accross all hex cells. Simply because i am bounding all my values which range from 0 to 500 to 0 to 10. So i need to normalize my rows based on that max. All hex value should be a value from 0 to 10. 

Then the color, and a hover tip showing that value will follow through.

I hope this clarify things a bit. Thanks for your help!

**Comment by Pessimistress** [comment]
> All hex value should be a value from 0 to 10.

My suggestion is don't mess those values. Internally they are only used to calculate color. The only place users will see them is in the tooltip. You can normalize the value before displaying it, by listening to `onSetColorDomain`.

**Comment by alitarraf** [comment]
Thanks, I will try that and get back to you.

**Comment by alitarraf** [comment]
I ended up changing my approach. Thanks for the help!
