### ISSUE TITLE
Limit pitch and bearing of deck gl

### ISSUE THREAD

**Issue by bnping** [visgl/deck.gl#4623]
Can we increase or decrease  the max and min values of pitch and bearing in deck class ?.

**Comment by Pessimistress** [comment]
To restrict pitch, add `minPitch` `maxPitch` to your `viewState` or `initialViewState`.

[documentation](https://deck.gl/#/documentation/deckgl-api-reference/views/map-view?section=constructor)

To restrict bearing, you need to implement the `onViewStateChange` callback:

```js
OnViewStateChange: ({viewState}) => {
  return {...viewState, bearing: 0};
});
```
