### ISSUE TITLE
pydeck: Document local file usage for IconLayer

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#4625]
#### Description

Pydeck needs an example of a local URI passed to the `IconLayer`'s [`iconAtlas`](https://github.com/visgl/deck.gl/blob/master/docs/layers/icon-layer.md#iconatlas-texture2d--string) loading an image. Apparently deck.gl supports base64-encoded images as an argument passed to iconAtlas.

See comments on #3900

**Comment by Pessimistress** [comment]
Pydeck should convert images to a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) which is natively supported by deck.gl.

**Comment by kylebarron** [comment]
That should be pretty straightforward I think? You just need a MIME type and then base64 encode the content?

**Comment by ibgreen** [comment]
Yup: https://stackoverflow.com/questions/6375942/how-do-you-base-64-encode-a-png-image-for-use-in-a-data-uri-in-a-css-file
