### ISSUE TITLE
Performance problem and optimization

### ISSUE THREAD

**Issue by bnping** [visgl/deck.gl#4628]
I have the data prop that update frequently (every one sec). Only the position of  every item is changing. The code below is like my project code. Stutter is visible and cause a bad user experience. 

```
  const DATA = [...];
  let currentYear = null;

  function selectYear(year) {
    currentYear = year;
    currentData = DATA.map(d => ({
      position: d.position[year],
      population: d.populations
    }));
    render();
  }

  function render() {
    const laye1 = new ScatterplotLayer({
      // `data` changes every time year changed, but positions don't need to update
      data: currentData,
      getPosition: d => d.position,
      getRadius: d => Math.sqrt(d.population),
      ...
    });
    const layer2 = new IconLayer({
      // `data` changes every time year changed, but positions don't need to update
      data: currentData,
      getPosition: d => d.position,
      getRadius: d => Math.sqrt(d.population),
      ...
    });

    deck.setProps({layers: [laye1, layer2]});
  }
```

**Comment by kylebarron** [comment]
You should give this a read: https://deck.gl/#/documentation/developer-guide/performance-optimization. You can use props like `updateTriggers` to specify what parts of the data to update.

**Comment by bnping** [comment]
@kylebarron. The  updateTriggers and https://deck.gl/#/documentation/developer-guide/performance-optimization is avoid speaking when the position is changing. I hope if their a simple code to show how we can use updateTriggers when only the position change based on time.
