### ISSUE TITLE
error in generating TextLayer

### ISSUE THREAD

**Issue by bnping** [visgl/deck.gl#4629]
I am facing this error when I do New TextLayer. I am using deck 8+

![image](https://user-images.githubusercontent.com/63243110/83420669-3f3f1500-a427-11ea-9ad0-939b3c68d3ae.png)

**Comment by Pessimistress** [comment]
Please check that `coordinateSystem` is a valid value.

**Comment by bnping** [comment]
@Pessimistress  this is my data object [
  {
    "count": 37,
    "coordinates": [
      2.430052166850821,
      44.27887862797744
    ]
  },
  {
    "count": 4,
    "coordinates": [
      2.430035528067718,
      44.278890897831175
    ]
  }
]
