### ISSUE TITLE
Problems with icon color

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4631]
I added some icons to the map.  But the color of the icons was affected  by the geojsonlayer with height and became white. How to solve this problem?

![360截图20200602104536435](https://user-images.githubusercontent.com/24310750/83474532-d86d3a80-a4be-11ea-8045-c1871769ba43.jpg)
![360截图20200602104839633](https://user-images.githubusercontent.com/24310750/83474539-dd31ee80-a4be-11ea-9968-8b7423065920.jpg)
![360截图20200602104915744](https://user-images.githubusercontent.com/24310750/83474548-e02cdf00-a4be-11ea-8b84-ee6daa42ff1c.jpg)

**Comment by kylebarron** [comment]
Closing in favor of #4646
