### ISSUE TITLE
MVT Layer Object Picking?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#4633]
Can you share how deck’s MVT Layer handles object picking?

Specifically, was curious how it would handle overlapping objects within a specific tile. Is the implementation able to perform deep-picking similar to how non-tile layers (ie, PathLayer, TextLayer, etc) are implemented?

**Comment by kylebarron** [comment]
Sorry! This was the GitHub issue equivalent of butt dialing...

**Comment by kylebarron** [comment]
> Specifically, was curious how it would handle overlapping objects within a specific tile. Is the implementation able to perform deep-picking similar to how non-tile layers (ie, PathLayer, TextLayer, etc) are implemented?

The TileLayer renders other layers as children of each tile. I think that deep picking should be supported. Do you have an example where you suspect it's not working?

**Comment by jfuehner** [comment]
@kylebarron, thanks for the explanation. I don’t have an example where it is not working... More so just investigating it’s possible use in my application.

Would you have any recommendations on tools for generating MVT’s on the fly for use with real-time data?

**Comment by kylebarron** [comment]
Generating MVTs is a backend task. I believe the standard approach to dynamic MVT generation is to store data in PostGIS and export MVT, added recently I think.

**Comment by jfuehner** [comment]
@kylebarron does the MVTLayer allow performing POST requests to a service endpoint?  Perhaps to pass a more complex object for filtering.

**Comment by jfuehner** [comment]
@kylebarron I created a an `MVTLayer` that is rendering some simple polygons. However, the `onHover`/`onClick` events are not firing...

```
        new MVTLayer({
          data: `http://localhost:8100/api/tiles/test/{z}/{x}/{y}`,
          minZoom: 0,
          maxZoom: 23,
          getLineColor: [192, 192, 192],
          getFillColor: [140, 170, 180],
          onHover: (info, event) => {
            debugger;
          },
          onClick: (info, event) => {
            debugger;
          }
        })
```

You can download the MVT bytes being sent to the browser [here](https://drive.google.com/file/d/1fYEyMVQ4tavA-N0M3ak57CLwJQQJQW9M/view?usp=sharing)...
