### ISSUE TITLE
Problems with icon color

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4646]
I added some icons to the map.  But the color of the icons was affected  by the geojsonlayer with height and became white. How to solve this problem?

![](https://user-images.githubusercontent.com/24310750/83474532-d86d3a80-a4be-11ea-8045-c1871769ba43.jpg)

![](https://user-images.githubusercontent.com/24310750/83474539-dd31ee80-a4be-11ea-9968-8b7423065920.jpg)

![](https://user-images.githubusercontent.com/24310750/83474548-e02cdf00-a4be-11ea-8b84-ee6daa42ff1c.jpg)

**Comment by Pessimistress** [comment]
Your icon is "inside" the polygon, so it gets mixed with the top surface's color.
You can force the icons to be on top like this:

```js
layers: [
  new GeoJsonLayer(...),

  // Note: draw the icons last
  new IconLayer({
    ...,
    parameters: {depthTest: false}
  })
]
```
