### ISSUE TITLE
pydeck: Using data fields within a GeoJSON Layer

### ISSUE THREAD

**Issue by SoominLee1206** [visgl/deck.gl#4653]
<img width="928" alt="1" src="https://user-images.githubusercontent.com/64841056/83861505-9f9dc180-a75b-11ea-91cd-fc9f9f0464fd.png">
<img width="904" alt="2" src="https://user-images.githubusercontent.com/64841056/83861522-a3c9df00-a75b-11ea-9d5e-f106ac5015a5.png">
<img width="889" alt="3" src="https://user-images.githubusercontent.com/64841056/83861527-a4fb0c00-a75b-11ea-8589-3b46a26d733e.png">
<img width="877" alt="4" src="https://user-images.githubusercontent.com/64841056/83861532-a593a280-a75b-11ea-8ef0-d2d2bd2f164f.png">
<img width="799" alt="5" src="https://user-images.githubusercontent.com/64841056/83861541-a7f5fc80-a75b-11ea-99a2-8a0ee94eca44.png">

Hello everyone.

I’m trying to change countries’ color on the map depend on the population.

I’m using pydeck, but I cannot see the differences of color between the countries, and I don’t know why. 

It would be a great help if you could find the mistakes.

Here are my imgaes of code.

Thank you in advance!

**Comment by ajduberstein** [comment]
@SoominLee1206 thanks for sharing! Is your data in a GeoJSON properties field? Can you try `properties.population`?

**Comment by SoominLee1206** [comment]
Thanks! it worked!
