### ISSUE TITLE
Dynamically create layers with DataFilterExtension

### ISSUE THREAD

**Issue by KhorZL** [visgl/deck.gl#4660]
Hi,

I'm currently working on a project that requires user to upload new GeoJson files, create GeoJsonLayers and apply filters on the layer based on the number of additional information the user has. I'm having trouble with getting the data filters to work.

The GeoJson datasets are in the following format
```
{
    type: "...",
    features: [
        {
            type: "feature",
            properties: {"info1": value1, "info2": value2 ...},
            geometry: {type: "polygon", coordinates: {[..., ..., ...], ....}}
        },
        ..
        ..
        ..
    ]
}
```
Additional informations are stored in the **properties** object, stored as key-value pairs.

To create/destroy layers dynamically, I am storing the list of DeckGL layers in an array, I am either appending a new layer to the array, or to delete, search for the layer with the same *id* and pop it from the array. The array would look like this:
```
const [list_of_layers, set_list_of_layers] = useState(
            new GeoJsonLayer({ .... }),
            new GeoJsonLayer({ .... }),
            ..
            ..
)
```
When the user adds a new layer, we do the following:
```
set_list_of_layers([...list_of_layers, new GeoJsonLayer({
                id: "custom_0_xxx",
                data: get_file_values,
                visible: true
                ..
                ..
            })
        ])
```
At this point, ```extensions: [new DataFilterExtension({filterSize: N})]``` is not initialized in the layer as we do not know the **filterSize**.

On the browser-side, the user will have input options to filter layer points by defining boundaries on the additional information. One example of additional information is *year-of-event*, the user can choose a boundary min-max value, e.g. [2012, 2017] and the layer should filter out relevant data points using **DataFilterExtension**, showing only data-points that have occured within 2012-2017.

To edit the previous layer, we copy the props, destroy the previous layer and create a new layer as such (this is adapted loosely from our current code):
```
const prevProps = layer.props;
set_list_of_layers(list_of_layers.filter(layer => !layer.id === target_id));
set_list_of_layers([...list_of_layers,
            new GeoJsonLayer({
                ...prevProps,
                getFilterValue: d => d.properties["info1"],
                filterRange: [min, max],
                extensions: [new DataFilterExtension({filterSize: 1})]            
            })
        ])
```

Theoretically, this should create a new layer that shows only data-points within the filter range. However, all the data-points are non-visible. 

![image](https://user-images.githubusercontent.com/25986947/83971775-ae2cda00-a90f-11ea-8e08-327320f24a40.png)

A snippet of the layer props from console shows that the props are passed as expected, but is not visible. The filtering works if the initial layer is passed the ```extensions: new DataFilterExtension``` props, but this seems to be a workaround.

I was hoping to better understand how I can improve the implementation of editing the DataFilterExtension dynamically in my layers.

Cheers

**Comment by Pessimistress** [comment]
@KhorZL Thank you for bringing your use case to our attention.

There is technically a bug - when extensions change mid-lifecycle, the layer does not call the extension's `initializeState`, so the data filter attributes are never registered.

With that said, in your application, I do not recommend switching the extension size dynamically. Even if the bug is fixed, doing so will bring some perf overhead due to the disposal/creation of an attribute and re-compiling the shader. It's more efficient to initialize the layer with an extension of `{size: 4}`, and if the user requests only 2 filters, just return an array of two with `getFilterValue` (missing elements are by default backfilled with 0s), and set the spare filter ranges to `[-1, 1]` to disable them.

Fixing this bug will require a change to the core Layer class, which is at a slightly higher risk than patching normal bugs. Since we are very close to releasing v8.2, unless the above workaround does not work for you, we may not patch the current release.

**Comment by KhorZL** [comment]
@Pessimistress Thanks for the informative response. I've taken your advice and initialized the layer with the maximum *filterSize*.  However, I'm having a little trouble understanding this implementation.

>  if the user requests only 2 filters, just return an array of two with `getFilterValue` (missing elements are by default backfilled with 0s), and set the spare filter ranges to `[-1, 1]` to disable them.

I have experimented with this, setting getFilterValue as an array of two and filterRange as an array of two nested arrays. This throws me the following error:
![image](https://user-images.githubusercontent.com/25986947/83995369-cb9f8980-a98b-11ea-8e23-b65d0855d93b.png)

Correct me if I'm wrong, I am under the impression that the size of ```getFilterValue``` and ```filterRange``` array should be of the same size as defined by *filterSize*.  And the properties of ```getFilterValue``` and ```filterRange``` are index-matched (i.e. filterRange[0] is the value boundary on getFilterValue[0]).

If so, when the user requests only 2 filters at index 0 and 2, when ```{size: 4}```, should the filter value look something like this?
```
getFilterValue: d => [d.properties.value0, d.properties.value1, d.properties.value2, d.properties.value3]
filterRange: [[0, 10], [-1,1], [0,10], [-1,1]]
```

**Comment by Pessimistress** [comment]
Yes...

```js
getFilterValue: d => [d.properties.value0, 0, d.properties.value2, 0]
filterRange: [[0, 10], [-1,1], [0,10], [-1,1]]
```

`filterRange` is set as two uniforms so all *[filterSize]* values have to be provided.

**Comment by KhorZL** [comment]
Gotcha! This workaround works for me. On another note, is there a way to filter string values? For example, if my dataset has a list of countries and I would like to filter these countries based on the country's name.

**Comment by KhorZL** [comment]
Closing this issue as I found a workaround the problem, which is to apply getFillColor conditionally. Thanks for all your help!
