### ISSUE TITLE
Transitions in OrthographicView

### ISSUE THREAD

**Issue by ricardoekm** [visgl/deck.gl#4664]
#### Description
Animations and transitions work fine when using GEO application (i.e. MapView), however when using OrthographicView I'm getting the following error when trying to use a LinearInterpolator:

```
Error: longitude is required for transition
(anonymous function)
src/transitions/transition-interpolator.js:103
  100 | 
  101 | this._requiredProps.forEach(propName => {
  102 |   const value = props[propName];
> 103 |   assert(
      | ^  104 |     Number.isFinite(value) || Array.isArray(value),
  105 |     `${propName} is required for transition`
  106 |   );
```

reducer.js
```
viewState: {
...viewState,
zoom: state.zoom + ZOOM_JUMP_SIZE,
transitionInterpolator: new LinearInterpolator(),
transitionDuration: 500 }
```
#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.1.7
 - Browser Version: [e.g. Chrome 71.0]
 - OS: Mac OS X 15.5

**Comment by Pessimistress** [comment]
You need to pass the keys to be interpolated to the `LinearInterpolator` constructor, i.e.

```js
new LinearInterpolator(['target', 'zoom'])
```

I realized that we don't have a dedicated documentation for this class...

**Comment by ricardoekm** [comment]
Works like a charm. Thanks.

**Comment by ricardoekm** [comment]
Should I leave it open until the doc is updated?

**Comment by mikeohyan** [comment]
Stupid question, I keep getting the same issue and a bit confused what `target` is in reference to.

For context, we seem to be getting a similar error when using the OrthographicView when the initial interaction with the map is to do a mouse-wheel zoom. It's not an issue if we do some sort of panning translation first though....

Running deck 8.5.0.

**Comment by jeffmacinnes** [comment]
@mikeohyan I ran into this same issue. The fix was to make sure set the `target` property in the viewstate when initializing Deck

```javascript
new Deck({
    initialViewState: {
       rotationX: 0,
       rotationOrbit: 0,
       zoom: 0.1,
       target: [0, 0, 0]
    },
})
```
