### ISSUE TITLE
Blurred color in heatmap layers

### ISSUE THREAD

**Issue by ricardoekm** [visgl/deck.gl#4665]
Hi everyone,
Is there a way to disable alpha calculation in the heatmap layer? 

I'd like to get solid colors, similar to the example below:
<img width="643" alt="heatmap" src="https://user-images.githubusercontent.com/747894/84178903-8fd3f500-aa5b-11ea-9511-ee70666e88ad.png">

Thanks.

**Comment by ricardoekm** [comment]
If that's not currently possible I'd appreciate it if you could please narrow the section of the code in the layer I need to play with.

Thanks.

**Comment by kylebarron** [comment]
Playing around with the toggles in the [example](https://deck.gl/#/documentation/deckgl-api-reference/layers/heatmap-layer), it looks like alpha is fully opaque by default, unless you change the layer's opacity.

You can set a custom color map with the `colorRange` prop

**Comment by ricardoekm** [comment]
Yes, I guess it's something else.

When I use the default color range I get the following heatmap, as you can see the image seems blurred. I thought it was opacity:
<img width="1404" alt="heat_map" src="https://user-images.githubusercontent.com/747894/84195297-b18da600-aa74-11ea-9a28-39227cdf42f9.png">

However when I change the color range to only 4 different colors the results improves
<img width="1401" alt="heat_map_less_colors" src="https://user-images.githubusercontent.com/747894/84195396-e26ddb00-aa74-11ea-9a56-5b9bb2be46d6.png">

Any idea on what's causing the blurred image in the first example? (Sorry if it's a dumb question) Thanks.

**Comment by Pessimistress** [comment]
I think the HeatmapLayer documentation incorrectly implies that `colorRange` has to contain 6 colors. It can in fact be any number.

You may decrease the blurring between colors by supplying a `colorRange` array that assigns the same color to multiple steps, e.g.:

```js
colorRange: [blue, blue, yellow, yellow, red, red]
```
