### ISSUE TITLE
How can I get deck.layers

### ISSUE THREAD

**Issue by litar77** [visgl/deck.gl#4666]
I try to encapsulate the deck into a class,like this:

export class XXX {

  constructor(props){

    this.props = {};
    this.count = counter++; // Keep track of how many sccene instances you are generating

    this._deck= new Deck({
     ...
____________________________________________________________

then,I want get layers by this._deck

newlayers=this._deck.layers;
 console.log(newlayers);

but  the I get newlayers is undefined,
so I try get layers form this._deck.layerManager

the layerManager return null also

but I console.log(this._deck),found the layerManager is not NULL

![image](https://user-images.githubusercontent.com/3349892/84215273-52717500-aaf8-11ea-850f-c8cd69b8aba8.png)

I am confused how to get the layers from the deck objec

**Comment by Pessimistress** [comment]
You are looking for `deck.props.layers`

**Comment by litar77** [comment]
@Pessimistress 
Thank you very much for answering, the problem has been solved.
But I am still very confused why both this._deck.layerManager and this._deck.layers return null?
Why do I have to use props to get the properties of the deck object?
Hope to get your answer, thank you very much

**Comment by Pessimistress** [comment]
@litar77 Anything that is not in the [documentation](https://deck.gl/#/documentation/deckgl-api-reference/deck) is a non-public API. Do not rely on non-public API in your application.
