### ISSUE TITLE
Layer opacity bug?

### ISSUE THREAD

**Issue by gallickgunner** [visgl/deck.gl#4667]
I've seen this in some layers that the opacity parameter doesn't work as I think it should. I've tested the arc specifically for this issue.  On opacity `0` the arcs should be hidden but instead it makes the color or the the breadth of the arc just a little bit transparent. Here is an image to illustrate.

![Untitled](https://user-images.githubusercontent.com/40718428/84370833-a7ab9600-ab8d-11ea-99d1-987da6ff056e.png)
As we can see, the arc don't disappear but only the middle portion gets transparent and that too looks like it's on `0.3` opacity when I've set it to `0`.

On opacity `1` it works like this.
![Untitled](https://user-images.githubusercontent.com/40718428/84370901-c316a100-ab8d-11ea-882c-27d66ad78584.png)

Any way to hide the arcs on opacity `0` ?

 - Framework Version: deck.gl 8.1.1
 - Browser Version: Chrome 70.0
 - OS: Windows 10

**Comment by Pessimistress** [comment]
I cannot reproduce this on https://deck.gl/#/documentation/deckgl-api-reference/layers/arc-layer

Are you setting your own blending parameters?

**Comment by gallickgunner** [comment]
Dang, I'm dumb. We had implemented a blending mode feature in the early stages but it wasn't being used so I forgot about it altogether. Removing it fixed the issue. Thanks.
