### ISSUE TITLE
Tooltip issue 

### ISSUE THREAD

**Issue by SoominLee1206** [visgl/deck.gl#4668]
Hi. I want to pop up tooltips with countries’ names when the mouse is hover,
but the countries' name does not appear.
It’s fixed with the world ‘{name}’, and I wonder why. 
<img width="739" alt="1" src="https://user-images.githubusercontent.com/64841056/84438371-668cb200-ac71-11ea-8e3f-ab81d697edee.png">
<img width="741" alt="2" src="https://user-images.githubusercontent.com/64841056/84438373-67bddf00-ac71-11ea-942c-79ed7e895725.png">
<img width="674" alt="3" src="https://user-images.githubusercontent.com/64841056/84438376-68ef0c00-ac71-11ea-9e24-a1489424dfe6.png">
<img width="681" alt="스크린샷 2020-06-12 오전 5 44 45" src="https://user-images.githubusercontent.com/64841056/84438384-6d1b2980-ac71-11ea-9a0d-74885093f8db.png">

**Comment by ajduberstein** [comment]
I believe this is a side effect of using the HeatmapLayer, which doesn't have an object with the `name` field in its picking info. Picking info varies from layer to layer as [mentioned in the docs](https://github.com/visgl/deck.gl/blob/master/docs/developer-guide/interactivity.md#the-picking-info-object).

A workaround to the same effect–load in a world country boundaries GeoJSON file (like the one you see in `DATA_URL` in [this example](https://pydeck.gl/gallery/custom_layer.html)) and make it transparent (set `filled` to `True`, `opacity` to `0`, `stroked` to `False`)and pickable.
