### ISSUE TITLE
ScatterplotLayer Binary Format?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#4669]
Does the [ScatterplotLayer](https://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer)  support binary attributes similar to the [PathLayer](https://deck.gl/#/documentation/deckgl-api-reference/layers/path-layer)  or [TextLayer](https://deck.gl/#/documentation/deckgl-api-reference/layers/text-layer)? I’m not seeing anything in the documentation so I assume not...

**Comment by Pessimistress** [comment]
Yes it's a standard layer

**Comment by jfuehner** [comment]
@Pessimistress ah! So it can take the same binary `data` construct as say the PathLayer?

Something like...
```

// USE BINARY
// Flatten the vertices
// [-122.4, 37.7, -122.5, 37.8, -122.6, 37.85, ...]
const positions = new Float64Array(POINT_DATA.map(d => d.point).flat(2));
// The color attribute must supply one color for each vertex
// [255, 0, 0, 255, 0, 0, 255, 0, 0, ...]
const colors = new Uint8Array(PATH_DATA.map(d => d.path.map(_ => d.color)).flat(2));
// The "layout" that tells PathLayer where each path starts
const startIndices = new Uint16Array(PATH_DATA.reduce((acc, d) => {
  const lastIndex = acc[acc.length - 1];
  acc.push(lastIndex + d.path.length);
  return acc;
}, [0]));

new ScatterplotLayer({
  data: {
    length: PATH_DATA.length,
    startIndices: startIndices, // this is required to render the paths correctly!
    attributes: {
      getPath: {value: positions, size: 2},
      getColor: {value: colors, size: 3}
    }
  }
})
```

**Comment by kylebarron** [comment]
See https://deck.gl/#/documentation/developer-guide/performance-optimization?section=use-binary-data

**Comment by jfuehner** [comment]
@kylebarron got it, thanks!
