### ISSUE TITLE
ScenegraphLayer dynamically changing scale (getScale) not working

### ISSUE THREAD

**Issue by euzu** [visgl/deck.gl#4671]
When I zoom in i want the 3D model to come out of the ground.
 But if i use `getScale : [1, getHeightAtZoom(viewState.zoom), 1]` it has no effect.

**Comment by ibgreen** [comment]
Shooting from the hip: You may need to use the `updateTriggers` mechanism to force the layer to actually update the scale attribute. For a constant value it should not technically be needed, but worth trying.

**Comment by euzu** [comment]
i tried it, but i used the wrong state variable, now it seems to work, thank you
