### ISSUE TITLE
Unable to achieve true transparency on layers

### ISSUE THREAD

**Issue by KhorZL** [visgl/deck.gl#4672]
Hi

I have been trying to toggle alpha channel (A in RGBA) to 0, which I assume to be controlling the opacity. However, I noticed that setting the alpha channel to 0 only gives me a fully opaque white color.

I then hypothesized that this was because I did not change the opacity value. However, after setting both ```getFillColor: [200, 0, 0, 0], opacity: 0``` I still get a fully opaque white layer.

![image](https://user-images.githubusercontent.com/25986947/84532447-d4d87f80-ad18-11ea-9537-704c48a2f9ed.png)

I was wondering if I was missing anything? Or is there a way to achieve true transparency?

Also, I am trying to render opacity per layer object based on some properties. i.e. ```opacity: (d) => d.properties.flooded ? 1 : 0``` but I understand that opacity is a blanket props for all objects within a layer. Other than opacity and alpha channel, is there any other way to achieve this?

**Comment by Pessimistress** [comment]
Check your WebGL parameters and CSS:mix-blend-mode of the canvas

**Comment by KhorZL** [comment]
Thanks for the quick response! Is there anything I should be looking out for in the WebGL parameters and CSS? I'm not adding any mix-blend-mode options in my CSS files.

**Comment by Pessimistress** [comment]
Are you using Deck standalone? MapboxLayer? ArcGIS?

**Comment by KhorZL** [comment]
Hi, you're right! I just found out that the project was also using InteractiveMap from ```react-map-gl``` and that was throwing the color blending issues. Adding layers to both maps solved the issue, thanks!
