### ISSUE TITLE
DeckGL Layer Ordering

### ISSUE THREAD

**Issue by seeyijie** [visgl/deck.gl#4682]
I have been searching for quite some time but I could not deterministically set the order of the layers being rendered on the map. So lets say if I have GeoJsonLayer 1 and GeoJsonLayer 2, is there a way to ensure GeoJsonLayer 2 is loading on top of GeoJsonLayer 1? 

Thank you.

**Comment by Pessimistress** [comment]
Layers are drawn in the order that they present in the `layers` prop.

**Comment by seeyijie** [comment]
![image](https://user-images.githubusercontent.com/36152992/85108710-c0c5de00-b242-11ea-9579-a749f26ac044.png)

So I have a blue line but is underneath the yellow line. 

I console log the state that is sent to layers prop and it seems like very first or last index, it still showed the above image. 

On closer looked, I saw that the lifecycle of the newly created is set to "Initialized", while the rest are 'Matched. State transferred from previous layer'.

**Comment by seeyijie** [comment]
I got it to work. Silly mistake on my part.

I forgot to update the mapRef
