### ISSUE TITLE
Performance when managing viewState manually (in React)

### ISSUE THREAD

**Issue by manzt** [visgl/deck.gl#4683]
Hi all, thank you for all your hard work on deck.gl! I have looked through the issues and can't seem to find if there are (performance) trade-offs when managing `viewState` with React state + `onViewStateChange` vs. specifying `initialViewState`. I ask because (naively) managing `viewState` as described below will (and specified in the docs) causes a re-render on every interaction.

```javascript
const view = new OrthographicView({ id: 'ortho', controller: true });
function Spatial() {
  const [viewState, setViewState] = useState(DEFAULT_VIEW_STATE);
  const layers = /* some code to create deck layers */
  function handleViewStateChange({ viewState: nextVewState }) {
    setViewState(nextViewState);
  }
  return (
    <DeckGL
      glOptions={{ webgl2: true }}
      layers={layers}
      viewState={viewState}
      onViewStateChange={handleViewStateChange}
      views={view}
    />
  );
}
```

If there is, it would be good to describe the tradeoffs in the docs. Another alternative would be to provide `initialViewState` and keep a reference to the current `viewState` using a combination of `useRef` and `onViewStateChange` as described in this issue: https://github.com/hubmapconsortium/vitessce/issues/574

**Comment by ibgreen** [comment]
> causes a re-render on every interaction.

Well if you interact you need to re-render the layers right? So I assume you are distinguishing between a React re-render and a deck.gl re-render, asking it it is worth avoiding the latter? 

If you have a lot of overhead in your React renders you may see some slow down, but then you probably want to optimize your React code anyway. 

I can assure you that performance was not even a consideration when we added the `initialViewState` prop. It was added to support declarative (callback-less) view state management (see the deck.gl JSON examples on the website).
