### ISSUE TITLE
Do not redraw on opacity or other style related updates

### ISSUE THREAD

**Issue by owzh** [visgl/deck.gl#4689]
Currently, I am working on a project that ties a slider to the opacity of a tile layer. It looks like whenever the opacity value is updated, the entire overlay is redrawn. Performance feels sluggish when there are a few overlays on the map due to all the redraws. Is there a way to do this without going through the lifecycle methods and perhaps just update the inline styles instead? Please advise, thanks!

Sample code below:

```
const generateImageTiles = (data, opacity) => {
  return new TileLayer({
    opacity,
    getTileData: ({ x, y, z }) =>
      load(
        http
          .get(getTileUrl(data, x, y, z), {
            responseType: 'arraybuffer',
            withCredentials: true,
          })
          .then((response) => response.data),
        ImageLoader
      ),
  });
};

const Component = ({ opacity, data }) => {
  const { map } = useContext(MapContext);
  const [overlayRef, setOverlayRef] = useState();

  useEffect(() => {
    if (map) {
      if (!overlayRef) {
        const ref = new GoogleMapOverlay({
          layers: [generateImageTiles(data, opacity)],
        });
        ref.setMap(map);
        setOverlayRef(ref);
      } else {
        const layers = [generateImageTiles(data, opacity)];
        overlayRef.setProps({ layers });
      }
    }
  }, [data, opacity, overlayRef, map]);

  return null;
};
```

I was able to around this somewhat by setting `overlayRef._overlay.getPanes().overlayLayer.style.opacity`. However, this only gives control over the entire overlay but not the individual child layers.

**Comment by Pessimistress** [comment]
What do you mean by "do not redraw"?  Deck has to redraw to reflect your change to `opacity`.

**Comment by owzh** [comment]
Because opacity is tied to a slider, it's possible for us to pass in many different opacity values in a short amount of time. We have it throttle so that it doesn't kick in as often. Still, there are alot of redraws taken place with each opacity value change. Since the image is already loaded on the map, I was hoping there would be a way to directly update the opacity without creating new `layers` array each time.

**Comment by Pessimistress** [comment]
Creating layers is extremely cheap (> 1M iterations/s). See https://deck.gl/#/documentation/developer-guide/using-layers?section=should-i-be-creating-new-layers-on-every-render-

**Comment by owzh** [comment]
Thanks for the link! Definitely appreciate all the work that's being done with this library. That was very informative. Kudos to the team!

Our old implementation was using Google map APIs directly. Using the same slider and have it auto slide from first image to third image with no throttling, here are the results for each implementation.

Here is using our old implementation calling Google Map APIs:
<img width="845" alt="Screen Shot 2020-06-18 at 8 52 53 PM" src="https://user-images.githubusercontent.com/34451896/85085407-be617680-b1a5-11ea-96ee-c0503c937337.png">

Here is the performance using deck.gl.
<img width="881" alt="Screen Shot 2020-06-18 at 8 53 01 PM" src="https://user-images.githubusercontent.com/34451896/85085410-befa0d00-b1a5-11ea-922c-360dd5af9ea0.png">

There are fewer frames per second with deck.gl and it's also slightly slower. We have it working but was just curious if there's an alternative.

**Comment by owzh** [comment]
I think I was hoping that there would be something like `overlayRef._overlay.getPanes().overlayLayer[0].style.opacity` where the index is the layer. But it goes against the concept of reactive programming and we are manipulating data outside of the lifecycles methods. 

I am going to close out the issue. Thanks for the taking out the time to answer the question.
