### ISSUE TITLE
react-map-gl GeolocateControl does not work in deck.gl

### ISSUE THREAD

**Issue by yzheng1998** [visgl/deck.gl#4691]
The geolocate control doesn't work when I put it inside of the DeckGL component. It is clickable, and visually the icon turns blue and turns as if it is loading, but it doesn't load the user's current location. Additionally, the onViewportChange and onGeolocate functions are not triggered.

```javascript
<DeckGL
    ContextProvider={MapContext.Provider}
    layers={renderLayers(markers)}
    initialViewState={viewport}
    controller={true}
>
    <GeolocateControl positionOptions={{ enableHighAccuracy: true }} trackUserLocation={true} />
    <StaticMap
        reuseMaps
        ref={mapRef}
        width={window.innerWidth}
        height={window.innerHeight}
        mapStyle={mapStyle}
        preventStyleDiffing={true}
        mapboxApiAccessToken={MapboxAPIKey}
        style={{ zIndex: 100, position: "absolute" }}
    ></StaticMap>
</DeckGL>
```

**Comment by kylebarron** [comment]
Have you tried putting it inside the `StaticMap` component?

**Comment by yzheng1998** [comment]
Yes and when you put it inside, it becomes unclickable. I've tried playing around with zIndex as well with that and nothing changed.

**Comment by kylebarron** [comment]
I've had to fiddle with these before. I appear to have had success with the `NavigationControl` component putting it outside `StaticMap`:
https://github.com/kylebarron/all-transit/blob/01e5eda5dcfffb200e9922db219eff5c173749a1/site/src/components/Map/index.js#L479-L482

I haven't tried `GeolocateControl` before

**Comment by yzheng1998** [comment]
Yeah I’ve gotten `NavigationControl` to work in that way. My hunch is that `GeolocateControl` hasn’t been made compatible with Deck.gl

**Comment by kylebarron** [comment]
Have you tested it in a pure react map gl app?

**Comment by Pessimistress** [comment]
Looks like the `GeolocateControl` still needs a map: https://github.com/visgl/react-map-gl/blob/master/src/components/geolocate-control.js#L202

`map` is missing from DeckGL's ContextProvider.

**Comment by yzheng1998** [comment]
Gotcha, I think that's it. How do I pass in a map?

**Comment by yzheng1998** [comment]
Solved it by creating a custom MapContext.Provider that appends the map to the value of the context provided by DeckGL. Let me know if there is a better way. This seems to be working!

```javascript
<DeckGL
    ContextProvider={MapContext.Provider}
    layers={renderLayers(markers)}
    initialViewState={viewport}
    controller={true}
>
    <StaticMap
        reuseMaps
        ref={mapRef}
        width={window.innerWidth}
        height={window.innerHeight}
        mapStyle={mapStyle}
        preventStyleDiffing={true}
        mapboxApiAccessToken={MapboxAPIKey}
    ></StaticMap>
    <MapContext.Consumer>
        {(outerContext) => {
            return (
                <MapContext.Provider
                    value={{
                        map: mapRef.current ? mapRef.current.getMap() : null,
                        ...outerContext
                    }}
                >
                    <CurrentLocationButton
                        positionOptions={{ enableHighAccuracy: true }}
                        trackUserLocation={true}
                    />
                </MapContext.Provider>
            );
        }}
    </MapContext.Consumer>
</DeckGL>
```
