### ISSUE TITLE
Trip layer: Icon at the tip when animating

### ISSUE THREAD

**Issue by arunkarepu** [visgl/deck.gl#4696]
Hi team, I was able to animate the data using trip layer with just track lines. Is it possible to have icon at the tip of each trip something like a car at the tip followed by line. 
I checked IconLayer documentation which can display icons but there is no way to move these icons like trip layer. Now question is there a way to integrate both IconLayer and TripLayer to achieve the given target or can we achieve this by just using any of the above layers?

**Comment by kylebarron** [comment]
You can use the `IconLayer` separately and also animate its positions

**Comment by arunkarepu** [comment]
Thanks for the reply. What about trailing path which we can show when using trip layer? Can we do that using just IconLayer?

**Comment by kylebarron** [comment]
No, I think you want the combination of both layers
