### ISSUE TITLE
"Cannot read property 'length' of undefined" loading Cesium OSM Buildings as Tile3DLayer

### ISSUE THREAD

**Issue by andybak** [visgl/deck.gl#4698]
Cesium have added a source for Tile3D data based on OSM 3D buildings: https://cesium.com/content/cesium-osm-buildings/

After some help from @xintongxia I figured out how to add it as a to a Deck GL Map. 

However it gives the error: "Cannot read property 'length' of undefined"

Other Cesium Tile3D layers do not - including those with similar 3D geometry (try their Melbourne or New York samples.

The error can be seen here: https://codepen.io/andybak/pen/NWxxWBJ?editors=1111

**Comment by ibgreen** [comment]
If you replace deck.gl scripts `dist.min.js` with `dist/dist.dev.js` and `dist.min.js` with `dist.dev.js` for loaders you may be able to debug the source.

**Comment by Pessimistress** [comment]
@ibgreen The error is thrown here:

https://github.com/visgl/loaders.gl/blob/master/modules/gltf/src/lib/parse-gltf.js#L102

`gltf.json.buffers` is undefined.

**Comment by ibgreen** [comment]
Opened visgl/loaders.gl#983

**Comment by Pessimistress** [comment]
This issue has been fixed in loaders.gl@2.3.6.
