### ISSUE TITLE
TextLayer crash after upgrade to 8.1.10

### ISSUE THREAD

**Issue by AndriiTsapenkoCasafari** [visgl/deck.gl#4701]
#### Description
after upgrade to 8.1.10 geting an error 
`deck: error during update of MultiIconLayer({id: 'values-text-layer-characters'}) 

RangeError: offset is out of bounds
    at Float32Array.set (<anonymous>)
    at MultiIconLayer._autoUpdater (attribute.js:443)
    at Attribute.updateBuffer (attribute.js:192)
    at AttributeManager._updateAttribute (attribute-manager.js:313)
    at AttributeManager.update (attribute-manager.js:140)
    at MultiIconLayer._updateAttributes (layer.js:523)
    at MultiIconLayer._updateState (layer.js:758)
    at MultiIconLayer._update (layer.js:704)
    at LayerManager._updateLayer (layer-manager.js:430)
    at LayerManager._updateSublayersRecursively (layer-manager.js:365)`

Appears after some map interaction: zoom, pan
![image](https://user-images.githubusercontent.com/48671729/85185723-d4eaf900-b29d-11ea-9951-8a0ab6a4f73d.png)

**Comment by Pessimistress** [comment]
What is the last version that worked for you? There has not been any recent changes that would affect this layer.

**Comment by AndriiTsapenkoCasafari** [comment]
7.3.3 worked

**Comment by Pessimistress** [comment]
Please create a codepen/code sandbox that reproduces this issue.

**Comment by jean1880** [comment]
Saw this as well, specifically while rapidly scrolling in and out of a map, with mapbox tileset. Seemed to happen but fairly frequently, while zooming in, or zooming out quickly with the mouse scroll wheel.

Stack:
deck.gl@8.2.2
react@ 16.13.1

**Comment by Pessimistress** [comment]
@jean1880 This issue was closed because we were unable to reproduce the bug. If you are experiencing the same please provide a codepen/code sandbox.

**Comment by jean1880** [comment]
We have to do our own internal investigation, we have many libraries in a
rather large project, and given how few people seem to have an issue, my
instinct tells me it is some sort of interaction between libraries. If we
narrow it down and discover it is this library I'll post a codepen. This
can remain closed for now, have it saved in our own internal ticket if we
discover we do need to update.
