### ISSUE TITLE
TileLayer zoom interval

### ISSUE THREAD

**Issue by gsahbi** [visgl/deck.gl#4707]
My mvt doesn't have tiles for every zoom level so how can get TileLayer to only request intervals of z

Example :
- for z between 6 and 8  will request zoom level 6 
- for z between 9 and 12 will request z = 9 
and so one

**Comment by kylebarron** [comment]
There's no built in way to do that, but since you can overzoom a single layer you could have two separate MVTLayers where you set the visibility prop as necessary

**Comment by gsahbi** [comment]
@kylebarron I see

I can skip fetching some zoom levels by overriding getTileData but I cannot garantee the user will zoom at the desired z that is not  skipped

**Comment by kylebarron** [comment]
The user doesn't need to. If the max zoom for a tile layer is 6, it will still be shown at zoom 8 using zoom 6 tiles.

```js
  const layer1 = new TileLayer({
    data: 'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png',
    minZoom: 6,
    maxZoom: 6,
    renderSubLayers: ...,
    visible: z >= 6 && z < 8
  });
  const layer2 = new TileLayer({
    data: 'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png',
    minZoom: 9,
    maxZoom: 12,
    renderSubLayers: ...,
    visible: z >= 9
  });
```

**Comment by Pessimistress** [comment]
You can try something like

```js
getTileData: ({x, y, z}) => {
  const z0 = Math.floor(z / 3) * 3; // the zoom level that we want to load at
  const deltaScale = Math.pow(2, z0 - z);
  const x0 = x * deltaScale;
  const y0 = y * deltaScale;
  // multiple tiles will map to one tile at the lower zoom level. Only load one of them.
  if ((x0 %1) === 0 && (y0 % 1) === 0) {
    return fetch(getUrl(x0, y0, z0));
  }
  return null;
}
```

**Comment by gsahbi** [comment]
> The user doesn't need to. If the max zoom for a tile layer is 6, it will still be shown at zoom 8 using zoom 6 tiles.
> 
> ```js
>   const layer1 = new TileLayer({
>     data: 'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png',
>     minZoom: 6,
>     maxZoom: 6,
>     renderSubLayers: ...,
>     visible: z >= 6 && z < 8
>   });
>   const layer2 = new TileLayer({
>     data: 'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png',
>     minZoom: 9,
>     maxZoom: 12,
>     renderSubLayers: ...,
>     visible: z >= 9
>   });
> ```

This actually didn't work as expected , I ended up having higher zoom levels all rendering at the same time
As if minZoom and maxZoom had no effect.

Also I donno how to use visible props, it's a boolean AFAIK

**Comment by kylebarron** [comment]
Currently `maxzoom` only has an effect for the _source_, not the _visualization_. So if both layers have `visible: true`, you'll see both rendered at high zooms >= 9. I think `visible` should work to turn off the first layer at a higher zoom.

Also try Pessimistress' solution

**Comment by gsahbi** [comment]
Actually what i'm trying to achieve is a progressive loading of H3 hex sub layer because my data is huge 
So I'm trying to map  z to  h3 aperture. the tile server will do a translation but client will load the same tiles multiple times. for example 10 and 11 will load aperture 8 which is a waste of resources.

    # map zoom to aperture in server
    z = tile['zoom']      
    if z < 10:           
        aperture = 7      
    elif 10 <= z < 12:    
        aperture = 8      
    elif 12 <= z < 14:     
        aperture = 9      
    else:                 
        aperture = 10

**Comment by gsahbi** [comment]
> You can try something like
> 
> ```js
> getTileData: ({x, y, z}) => {
>   const z0 = Math.floor(z / 3) * 3; // the zoom level that we want to load at
>   const deltaScale = Math.pow(2, z0 - z);
>   const x0 = x * deltaScale;
>   const y0 = y * deltaScale;
>   // multiple tiles will map to one tile at the lower zoom level. Only load one of them.
>   if ((x0 %1) === 0 && (y0 % 1) === 0) {
>     return fetch(getUrl(x0, y0, z0));
>   }
>   return null;
> }
> ```

I tried your suggestion but I got weird behavior, upper and left tiles disappear at certain zoom levels. I think it's because of the condition on fraction x and y : 
if ((x0 %1) === 0 && (y0 % 1) === 0) {

**Comment by gsahbi** [comment]
> Currently `maxzoom` only has an effect for the _source_, not the _visualization_. So if both layers have `visible: true`, you'll see both rendered at high zooms >= 9. I think `visible` should work to turn off the first layer at a higher zoom.
> 
> Also try Pessimistress' solution

Your initial suggestion works like charm .. I just had to bring viewState.z  prop from the upper container  and apply the visible condition.
