### ISSUE TITLE
DeckGL with ReactMapGL Marker

### ISSUE THREAD

**Issue by dquang-tran** [visgl/deck.gl#4709]
Is it possible to make it so that ReactMapGL's [Marker](http://visgl.github.io/react-map-gl/docs/api-reference/marker) go on top of the DeckGL layers?

Example from https://github.com/visgl/deck.gl/issues/4451 : https://codesandbox.io/s/xenodochial-cache-h66mp
How do you make red markers go on top of the blue route but leave the blue route to be on top of the map?

I saw this [doc](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/mapbox/overview.md) but not sure if it would solve my problem since mapbox markers are not rendered on a layer

**Comment by kylebarron** [comment]
The `PathLayer` is a deck.gl layer and the Marker is a Mapbox/React Map GL layer. By default deck.gl and Mapbox render into different `canvas`es, so the Deck layers will always be on top. To render the Marker on top, you'd have to use the [`MapboxLayer`](https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/mapbox-layer). Or render your Marker's with deck.gl's IconLayer.

**Comment by Pessimistress** [comment]
Use [ContextProvider](https://deck.gl/#/documentation/submodule-api-reference/deckgl-react/deckgl?section=react-context).

**Comment by dquang-tran** [comment]
@Pessimistress This is it. Thanks!

**Comment by dquang-tran** [comment]
@Pessimistress related issue after I implemented Markers using ContextProvider. Now my react structure looks like this

```
<DeckGL
  viewState={viewState}
  layers={layers}
  ....
  ContextProvider={_MapContext.Provider}
>
  <StaticMap
    ref={this.mapRef}
    mapboxApiAccessToken={MAPBOX_TOKEN}
    mapStyle={MAP_STYLE_URL}
  />
  <Marker longitude={lng} latitude={lat}><div>Hello</div></Marker> 
</DeckGL>
```
The Marker is now on top of all the layers rendered by DeckGL, which is what I want. However, I am seeing the issue where hovering over a Marker triggers an onHover event if there is a layer right underneath the marker. Is there a way to prevent the propagation? Can `_MapContext`'s `eventManager` help?

**Comment by riancz** [comment]
For any people looking up solution to this issue:

It is as simple as @dquang-tran mentioned. I would just add that the context can be imported like `import { _MapContext } from 'react-map-gl';` and does not need any additional setup.

**Comment by DonovanCharpin** [comment]
@kylebarron you were saying we could use the IconLayer. But I don't see how we can drag icons from this layer? Am I missing something?

**Comment by Clebal** [comment]
@DonovanCharpin here you can see a very very simple example: https://codesandbox.io/s/draggable-icon-j9l3b?file=/index.html (there are better ways to structure the logic)

**Comment by claraberendsen** [comment]
What would be the new fix, since v7 of react-map-gl this solution doesn't work

**Comment by addy** [comment]
@claraberendsen I imagine that is has something to do with the new `useMap()` hook, but trying to figure it out myself right now.

**Comment by CharlieMartell** [comment]
Also trying to figure out how to get this to work with react-map-gl v7 and deck.gl v8

**Comment by dung-phan** [comment]
Any updates on this issue with latest version of deck.gl?

**Comment by adriangonzalezericsson** [comment]
Any updates? Is it still impossible to use Markers in the following way?
<DeckGL>
   <MapGL>
         <Marker>

**Comment by nogurtMon** [comment]
From the Upgrade Guide:

"If you are using react-map-gl controls (Marker, Popup, NavigationControl etc.) with deck.gl's ContextProvider, do not upgrade to this version. The old approach no longer works with v7. We are moving the support for this use case to a new project that does not depend on mapbox."

**Comment by woadies** [comment]
Based on the current situation, if the use case is as simple as showing a marker with a label. I chose to convert the component from an UI library to a PNG. If anyone have this problem, hoping this will be fixed soon.

**Comment by bhargavtenali** [comment]
@dquang-tran Can you provide me the versions of 
React-Map-GL,
Decl-gl,
and Mapbox-gl,
I tried with older versions, but marker is not diplaying over deck gl layer

**Comment by woadies** [comment]
I will provide you with mine in case the OP has moved on
```
    "mapbox-gl": "^2.15.0",
    "deck.gl": "^8.9.18",
    "react-map-gl": "^7.0.25",
``` 
On the visGL doc, is has been said that this problem concerns v7

**Comment by vacaramin** [comment]
Anyone on this issue, looking for a fix in the latest version I found it, use a mapbox-overlay for the additional layers you add. 
So you probably are stuck, with having a deckGL parent and within it a mapbox. and somehow the mapbox layer comes on top. and you can't use the markers or anything that mapbox renders in that case, just remove the deckGl parent it a overlay child to the mapboxgl, this article will help you out a lot 

[Life saver link](https://deck.gl/docs/api-reference/mapbox/mapbox-overlay)

and some snippets that'll help you
```
function DeckGLOverlay(props: DeckProps) {
  const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props));
  overlay.setProps(props);
  return null;
}
```
```
const layers = [
      new [Your layer type]({
        id: "trips",
        data: DATA_URL.TRIPS,
        getPath: (d) => d.path,
        // additional attributes of your layers. 
      }),
    ];
```


```
<DeckGLOverlay layers={layers} />
```
