### ISSUE TITLE
IconLayer does not render local png icon

### ISSUE THREAD

**Issue by lezan** [visgl/deck.gl#4713]
#### Description
I am not able to render a local icon with IconLayer. I try with my icon (done with TexturePacker) and also with your icon. Switch to an url as iconAtlas (same png icon) can render it.

#### Repro Steps
You can try with this codesandox: https://codesandbox.io/s/icon-layer-example-vjcn3.
In this example I try with icon and data example provide here: https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer, but I get the same error also with my iconAtlas and iconMapping.

In my specific case is a bit different, what I did is:
```
const iconMapping = {
	test1: {
	    x: 0, y: 0, width: 37, height: 37,
	},
	test2: {
	    x: 37, y: 0, width: 37, height: 37,
	},
};

const layerIcon = new IconLayer({
	id: 'icon',
	data: data.iconLayer.data,
	iconAtlas: '../../assets/images/icons.png',
	iconMapping,
	getIcon: (d) => (d.name === 'test1' ? 'test1' : 'test2'),
	getPosition: (d) => [d.long, d.lat, 0],
	sizeScale: 15,
});
```
but same result.

#### Environment:
 - Framework Version: deck.gl 8.1.12, react 16.13.1
 - Browser Version: Firefox 77.0.1
 - OS: Windows 10, latest update.

#### Logs
```
DOMException: "An attempt was made to use an object that is not, or is no longer, usable"
```

**Comment by Pessimistress** [comment]
The URL is not valid.

In your code sandbox, you can try `return <img src="images/icon-atlas.png" />`, which is unable to load the image.

**Comment by lezan** [comment]
Thanks for your quickly answer.
 
> 
> The URL is not valid.

Are you talking about URL in sandbox or in my example? The former is the same [here](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer?section=example-pre-packed-iconatlas) and [here](https://github.com/visgl/deck.gl/blob/b086cf3c2c84b162aca3d23e333c595a9e7cc44e/examples/website/icon/app.js#L111).

> In your code sandbox, you can try `return <img src="images/icon-atlas.png" />`, which is unable to load the image.

As value of `iconAtlas`? Just like that? I did but `Unexpected token (386:15)`. With `function() {return (<img src="images/icon-atlas.png" />)}` it does not gives error, but it just renders a rect without icon.

**Comment by Pessimistress** [comment]
> As value of iconAtlas?

No, I meant instead of drawing DeckGL, just render an image in HTML. It proves that the rendered page does not see the image at that URL.

**Comment by lezan** [comment]
Ok, so the correct way of do it is not to put a string in iconAtlas but import image before and then pass it to iconAtlas. Now is working as expected.

```
import icon from '../../assets/images/icon.png';

new IconLayer({
    ...
    iconAtlas: icon,
    ...
});
```

Maybe can you correct what is [here](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer) and [here](https://github.com/visgl/deck.gl/blob/master/docs/layers/icon-layer.md) and change it from

```
const ICON_MAPPING = {
  marker: {x: 0, y: 0, width: 32, height: 32, mask: true}
};
```
to
```
const ICON_MAPPING = {
  marker: {x: 0, y: 0, width: 128, height: 128, anchorY: 128, mask: true}
};
```
as reported [here](https://github.com/visgl/deck.gl/blob/e0d9a2528db452b6b47353dbe53f94e6b478d418/website/src/doc-demos/layers.js#L96); also `sizeScale` from `15` to `8`, to make it consistent.

**Comment by Pessimistress** [comment]
The iconAtlas URL in the sample code is not an error. You simply do not have your project set up to serve the static asset. Look into the examples/ directory in this repo for complete project examples.
