### ISSUE TITLE
Rendering React Components at given coordinates

### ISSUE THREAD

**Issue by yzheng1998** [visgl/deck.gl#4714]
Is there any way to render react components at given point coordinates?

My specific use case is I want to render a pie chart that shows a break down of the categories of points within a cluster, like in the following example:
![image](https://user-images.githubusercontent.com/31601104/85456609-c08c5200-b564-11ea-8b3a-c3f3d507d53a.png)
https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/

I need to dynamically calculate the pie chart breakdown depending on the points within a cluster, and therefore I cannot use the IconLayer to render this. Any advice?

**Comment by Pessimistress** [comment]
You can use [Marker](http://visgl.github.io/react-map-gl/docs/api-reference/marker) with [ContextProvider](https://deck.gl/#/documentation/submodule-api-reference/deckgl-react/deckgl).

**Comment by jaballogian** [comment]
could someone please share the example code? I'm having trouble too
thank you
