### ISSUE TITLE
New FillStyleExtension behaviour when used in MVT subLayer 

### ISSUE THREAD

**Issue by reececasey** [visgl/deck.gl#4718]
#### Description
Upon testing the new `FillStyleExtension` (https://github.com/visgl/deck.gl/pull/4676) within a GeoJSON subRender of the MVT layer I observed some strange behaviour. When zooming in on polygons they divide with lines creating smaller polygons. The pattern also will not show until lower zoom levels. 

I have tested using a straight GeoJSON layer and it seems fine, although there is still some strange zoom behaviour for scale but that I can probably work around. The below example is a single polygon.

![ezgif com-crop](https://user-images.githubusercontent.com/29492440/85539500-cf7b0f00-b60d-11ea-80e9-65b4c471d894.gif)

Not sure if this is to do with my setup and the pattern has just brought this to light but thought I would share. I know its still in beta stage but also couldn't find any issue for it. 

A long awaiting feature though, so thanks! 

#### Repro Steps
Setup MVT layer with geojson subRender using FillStyleExtension

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.0-beta.1
 - Browser Version: Chrome 83.0.4103.116
 - OS: Mac OS X 10.14.5

#### Logs
N/A

**Comment by danielwhatmuff** [comment]
+1 👍

**Comment by Pessimistress** [comment]
I think there are two things happening here: 

- The extension crashes when used with MVTLayer because it doesn't handle non-lnglat coordinate system correctly. I will put up a fix.
- I haven't seen your code, but you should not override the props that MVTLayer passes to `renderSubLayers`, including `extensions`. When the above bug is fixed you should be able to use the extension on the MVTLayer itself.

**Comment by reececasey** [comment]
Great thanks @Pessimistress I can move the extensions to the MVTLayer no problem, that is well worked out by the way. Thanks for the PR for the latlng issue 👍 much appreciated.

**Comment by reececasey** [comment]
Great thanks @Pessimistress fixes the divide issue, I moved the extension to the MVT layer as suggested too.

However, the pattern still only shows at low zoom levels. Is this something you have seen happen?

**Comment by Pessimistress** [comment]
https://codepen.io/Pessimistress/pen/qBbrbaw

**Comment by kylebarron** [comment]
![Screen Recording 2020-06-26 at 1 30 29 PM](https://user-images.githubusercontent.com/15164633/85894136-6cc27880-b7b1-11ea-89d4-b82f0a62d07b.gif)

Just noting the fill style is quite "trippy" when zooming

**Comment by Pessimistress** [comment]
@kylebarron https://en.wikipedia.org/wiki/Moir%C3%A9_pattern

**Comment by reececasey** [comment]
@Pessimistress Sorry yes working, must have been the older version. Thanks again for the fast turn around.
