### ISSUE TITLE
Picking mechanism ignores overlays

### ISSUE THREAD

**Issue by goszczynskip** [visgl/deck.gl#4719]
#### Description
When displaying overlay on deck.gl canvas picking mechanism still triggers onHover methods. 
This wasn't happening in 7.x versions. 

#### Repro Steps

Create IconLayer with any icon and onHover callback.
Display modal covering icon in Deck.gl as a Deck.gl child (in React jsx).
Moving mouse over modal (and over hidden icon) triggers onHover. 

#### Environment:
 - Framework Version: 8.1.8
 - Browser Version: Firefox 77.0.1
 - OS: Windows 10

EDIT:
there is example code: https://codesandbox.io/s/quirky-leavitt-02d6v?file=/src/App.js

**Comment by Pessimistress** [comment]
This is intentional. In 7.x it was impossible to interact with <DeckGL>’s child components, as illustrated by https://github.com/visgl/deck.gl/issues/3389. If you want to block Deck from receiving events from the modal, the easiest way is to render it as a peer of <DeckGL> instead of a child.

**Comment by goszczynskip** [comment]
Thanks for quick response. It makes sense now. However rendering components (in my case popups) outside of DeckGL component is tricky with what you proposed. My components need *project* function provided by *viewport* to position themselves correctly over map. I havent figured out how to pass it out of DeckGL except using refs. It looks like deck is constructing it internally during each render (references are changing). Do you have any idea how to solve this? Eg. hoising it to parent component and passing it to DeckGl would be great. In that case I could easly share it between DeckGL and custom components.

**Comment by Pessimistress** [comment]
This is what the "stateless" mode is for (using `onViewStateChange` and `viewState`).
https://deck.gl/#/documentation/developer-guide/views-and-projections?section=using-a-view-class-with-view-state

The viewport can be constructed from the view state using [WebMercatorViewport](https://deck.gl/#/documentation/deckgl-api-reference/viewports/web-mercator-viewport).
