### ISSUE TITLE
Symbols on line layer.

### ISSUE THREAD

**Issue by UttamRahane** [visgl/deck.gl#4724]
Is there any way to add symbols/icons on line?  I'm looking something like 
[https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/](url)

with some following properties 
layout: {
                'icon-image': 'oneway-large',
                'icon-rotate': 0,
                'icon-rotation-alignment': 'map',
                'icon-allow-overlap': true,
                'icon-size': 1.5,
                'icon-ignore-placement': true,
                'symbol-placement': 'line-center',
            },

**Comment by Pessimistress** [comment]
Duplicate of #4199
