### ISSUE TITLE
ScaleControl throws error

### ISSUE THREAD

**Issue by pthomas931** [visgl/deck.gl#4726]
#### Description
When using the react-map-gl ScaleControl component the browser throws an error. 

- Firefox: "TypeError t is undefined" error.
- Chrome: "TypeError Cannot read property '_container' of undefined"

#### Repro Steps
Include a ScaleControl, observe error:

```
<DeckGL
      ...
      ContextProvider={MapContext.Provider}
    >
      ...
      <ScaleControl />
</DeckGL>
```

https://codesandbox.io/s/bold-hellman-vg8fi?file=/src/App.js

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.1.12
 - Browser Version: Firefox 77.0.1 / Chrome  83.0.4103.116
 - OS: Mac OS X

#### Logs
![image](https://user-images.githubusercontent.com/606946/85760764-26511900-b6e0-11ea-8d6f-57683755a002.png)

**Comment by kylebarron** [comment]
I think you need to put `ScaleControl` inside a `div`. `_container` is not defined because there's no container around the `ScaleControl`.

**Comment by pthomas931** [comment]
I tried wrapping the control in a simple `<div>`, but no luck. 

Updated https://codesandbox.io/s/bold-hellman-vg8fi?file=/src/App.js 

Thanks for the quick response though!

**Comment by kylebarron** [comment]
I've done this successfully before: https://github.com/nst-guide/web/blob/2848ad858d987c7e0c00fe9b14ea9ed98f9e64b6/src/components/Map/index.js#L466-L474

**Comment by Pessimistress** [comment]
`<ScaleControl>` requires access to the mapbox Map, which deck does not own. You can place it inside `<StaticMap>` if you are using one, otherwise it won't work.

**Comment by kthyer** [comment]
I have this problem even when placing it within `<StaticMap>`. Is this code correct? https://codesandbox.io/s/inspiring-mayer-vgyhu

Does it only work with an `<InteractiveMap>` like in this code? https://codesandbox.io/s/recursing-grothendieck-ipwdw

**Comment by pthomas931** [comment]
Good find, it does appear to only work with <InteractiveMap> and it would appear this is a bug in `react-map-gl` with nothing to do with deck.gl 

Pen: https://codesandbox.io/s/cranky-meitner-9cd7t

Thanks everyone for your help!
