### ISSUE TITLE
Viewport Transition crashing when using stateless "viewState" and "onViewStateChange" combination

### ISSUE THREAD

**Issue by juandjara** [visgl/deck.gl#4731]
#### Description

I'm using the "viewState" and "onViewStateChange" combination of deck.gl instance props in my project in order to be able to trigger programatic updates to the viewState. Whenever I trigger a viewState update that includes a transition (using `FlyToInterpolator`) this crashes when executing the following `setProps` with the `viewState` received from `onViewStateChange`. 

I think the issue comes from [this line](https://github.com/visgl/deck.gl/blob/7e7b4bfce8bcf367534e200933459679bfa0f96b/modules/core/src/lib/deck.js#L279), as it says **the viewport is not defined** because of something that the transition code is doing. I've come to think this because in versions < 8.2 of deck.gl this issue was not present.

#### Repro Steps

See the adapted [codepen](https://codepen.io/juandjara/pen/yLeobyz) with the modified FlyToInterpolator example from the examples gallery

#### Environment (please complete the following information):
 - Framework Version: [deck.gl 8.2.0-beta.2]
 - Browser Version: [Firefox 77.0.1]
 - OS: [Mac OS X 10.15.5]

#### Logs

Here are the error logs: [console-export-2020-6-26_22-11-21.txt](https://github.com/visgl/deck.gl/files/4839032/console-export-2020-6-26_22-11-21.txt)

cc @clebal

**Comment by Pessimistress** [comment]
Thanks for testing beta! Fixed in 8.2.0-beta.3
