### ISSUE TITLE
How can I am Implementation nebula gl in Angular with (deck gl, mapbox) ?

### ISSUE THREAD

**Issue by sunaryaap** [visgl/deck.gl#4745]
Currently, I'm using deck.gl, mapbox, ScatterplotLayer in Angular and it works.
Im using this the package:
import { ScatterplotLayer } from '@deck.gl/layers';
import { MapboxLayer } from '@deck.gl/mapbox';
import {DataFilterExtension} from '@deck.gl/extensions';

![image](https://user-images.githubusercontent.com/11072105/86116475-b4216f80-baf7-11ea-907d-9e126d65e59d.png)

Next step I want to add feature draws on the map like kepler.gl, like this:

![image](https://user-images.githubusercontent.com/11072105/86116517-c4d1e580-baf7-11ea-8fb1-459b1e035476.png)

Actually I'm very confused because in the reference I found only react-map-gl can implement for nebula.gl,
the question is, How can I Implementation nebula.gl with @deck.gl/mapbox and @deck.gl/layers ?

**Comment by Pessimistress** [comment]
I’d suggest you read the nebula.gl source code.
