### ISSUE TITLE
Tile3DLayer: Does not render color attributes for I3S mesh layers

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#4749]
#### Description

- colored attributes are rendered for 3D Tiles because they use the `ScenegraphLayer`, but the color attribute is ignored when rendering `SimpleMeshLayer`
- https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js#L218

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]

**Comment by ibgreen** [comment]
@belom88

**Comment by Pessimistress** [comment]
`SimpleMeshLayer` only colors with either `texture` or `instanceColors`. The mesh's colors attribute is never used.

We may add a new prop to switch on this behavior.

**Comment by xintongxia** [comment]
> `SimpleMeshLayer` only colors with either `texture` or `instanceColors`. The mesh's colors attribute is never used.
> 
> We may add a new prop to switch on this behavior.

For `SimpleMeshLayer`, maybe we can do something as below?

```
##### `mesh` (Geometry|Object|Promise)

...

The following attributes are expected:

- `positions` (Float32Array) - 3d vertex offset from the object center, in meters
- `normals` (Float32Array) - 3d normals
- `texCoords` (Float32Array) - 2d texture coordinates
- `colors` (Float32Array) - colors in the format `r,g,b` or `r,g,b,a`


`colors` of each object in the `data` stream are decided by the following orders:

- If `texture` is provided, use `texture` colors.
- If `colors` is provided, use the multiplication of `getColor()` and `colors`.
- Use `getColor()`
```

**Comment by Pessimistress** [comment]
@xintongxia In existing use cases `mesh` may already contain the `colors`/`COLOR_0` attribute (part of the loaders.gl mesh format and the `Geometry` class), we are just not using it in the layer shader. It will be a breaking change if we start to disregard instance colors.

**Comment by ibgreen** [comment]
>  if we start to disregard instance colors.

We can combine the vertex and instance colors, same as ScenegraphLayer.
