### ISSUE TITLE
Coloring the bars of a HexagonLayer

### ISSUE THREAD

**Issue by ivanovishado** [visgl/deck.gl#4751]
Hi. Is there any way to change the colors of the bars on a `HexagonLayer`?

We're looking for something similar to the functionality of the `hue` parameter of `Seaborn`. In case you're not familiar with that, it's used to assign colors to the bars depending on a categorical variable.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/17692634/86503581-22269a80-bd75-11ea-9723-64bec50ed87b.png">

**Comment by Pessimistress** [comment]
Look for “color” in [the documentation](https://deck.gl/docs/api-reference/aggregation-layers/hexagon-layer).
