### ISSUE TITLE
Overlapping features order in GeoJsonLayer

### ISSUE THREAD

**Issue by hygorkn** [visgl/deck.gl#4752]
I'm drawing mobile network antenna sectors on map, and each sector has a radius and a color based on its transmission frequency.

I would like to order the features so that the smaller sectors appears on top of the larger ones,  allowing me to hover properly each one of them. I've tried to use `getElevation` and set `depthTest: false` but it didn't work.

![image](https://user-images.githubusercontent.com/36460865/86537187-835c8400-bec3-11ea-8a36-cdd6b1625c43.png)
![image](https://user-images.githubusercontent.com/36460865/86537195-8fe0dc80-bec3-11ea-95ae-8f2b935f8c75.png)

Is that possible?

**Comment by Pessimistress** [comment]
> I've tried to ... set `depthTest: false` but it didn't work.

How exactly does it not work? I don't see anything from your screenshots that is unexpected. Your polygons are translucent so I can't tell which one is on top. If `depthTest` is off then they will be drawn in the order that they are defined.

**Comment by hygorkn** [comment]
The problem is that I can't get the hover information on the smaller ones. You can see in the images that the tooltip didn't change as I moved the mouse. Thanks for the response.

**Comment by Pessimistress** [comment]
Please provide a codepen/codesandbox that reproduces your issue.

**Comment by hygorkn** [comment]
While I was writing the codepen I noticed that sorting the GeoJSON source and putting it in a single Deck GeoJsonLayer solved it.
Before, I was splitting the features into multiple GeoJsonLayers based on their frequency and sorting the Layer Array. Thanks!

**Comment by Siva326** [comment]
@hygor-knust : Could you please share sample code to draw antenna sector on maps? 

Thanks in advance.
