### ISSUE TITLE
pydeck: Error when passed a dataframe with int values 

### ISSUE THREAD

**Issue by tkahng** [visgl/deck.gl#4755]
#### Description

Error when passed a dataframe with int values, solved by converting to float.
Would expect either types be accepted, given that they are not used by anything within the layer that explicitly states so. 
Here, the 'deposit' is not used for any function in the layer.

![image](https://user-images.githubusercontent.com/28710670/86742158-dfb1d600-c072-11ea-9800-d887f5007116.png)
![image](https://user-images.githubusercontent.com/28710670/86742291-f8ba8700-c072-11ea-80c2-e09fb9e3b26f.png)

**Comment by kylebarron** [comment]
Are you able to share your dataset?

**Comment by tkahng** [comment]
Sure!
the notebook has the path to the sqlitedb and the first cell under the Pydeck header is where i make the dkdf dataframe.
uncommenting the last line that converts the int to float is what made it work for me. 
  
[https://github.com/tkahng/trkPython/blob/master/realestateanalysis/aptrentgeo1.ipynb](url)

**Comment by ajduberstein** [comment]
Thanks for filing the issue, @tkahng! I'm not able to reproduce the bug.

Using the code below as a toy example–you'll notice that `deposit` is an int64 and is never converted to be a float.

```python
import pandas as pd
import pydeck

df = pd.DataFrame([
    {
        'lng': 126.96635,
        'lat': 37.58070,
        'deposit': 1000,
        'area': 29.76,
        'date': '2019-01-01'
    }])

assert df.dtypes['deposit'] == 'int64'

df['color'] = [[6, 255, 33]]  # or any other RGB value

layer = pydeck.Layer(
    'ScatterplotLayer',
    df,
    get_position=['lng', 'lat'],
    auto_highlight=True,
    get_radius=1000,
    get_fill_color='color',
    pickable=True)

# Set the viewport location
view_state = pydeck.ViewState(
    longitude=126.97,
    latitude=37.58,
    zoom=10,
    min_zoom=5,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36)

r = pydeck.Deck(layers=[layer], initial_view_state=view_state)
r.to_html('ScatterplotLayer.html')
```

![image](https://user-images.githubusercontent.com/2204757/87062167-902df000-c1c1-11ea-903f-25899d61e275.png)

**Comment by tkahng** [comment]
i see, thank you for looking into it @ajduberstein !
