### ISSUE TITLE
Double click not working on GoogleMapsOverlay

### ISSUE THREAD

**Issue by ibesora** [visgl/deck.gl#4758]
#### Description
Even though double click is not supported as an event, when using the `onClick` handler in the `DeckGL` react component you get two consecutive clicks when double clicking on the map.

When double clicking on a layer in GoogleMapsOverlay only the first click is received, making it impossible to handle double clicks even manually.

#### Repro Steps
I've created a [codesandbox](https://codesandbox.io/s/deckgl-x2z0j?file=/src/DeckGLOverlay.js) to reproduce the issue. It basically creates a Google Map and uses that to create a `GoogleMapsOverlay` with a `ScatterPlotLayer` with a blue circle on top of it. To reproduce the behaviour please do the following steps: 
1. Open the console by clicking on the _Console_ label just below the web panel on the right side of the app
2. Double click on the blue circle and see how `onClick` is only called once

Notice that even though the codesandbox is using a `ScatterPlotLayer`, this also happens at least with the `MVTLayer` and the `GeoJsonLayer`, that's why I think it's a problem with `GoogleMapsOverlay`
#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.1
 - Browser Version: Chrome 83.0.4103.116 (Official Build) (64-bit), Firefox 77.0.1+build1-0ubuntu0.20.04.1
 - OS: Ubuntu 20.04 LTS 

#### Logs
Nothing showing in the logs except the click messages

**Comment by Pessimistress** [comment]
Deck is blocked from receiving any pointer events by Google Maps. All events are generated by listening to the corresponding Maps events:

https://github.com/visgl/deck.gl/blob/7b3b615edb86c7a6adf9230bdcb139a58e9933d3/modules/google-maps/src/utils.js#L22-L26

**Comment by ibesora** [comment]
I don't know if I understood you correctly. Are you proposing I add an event listener to the Google Map instance and then call deck.pick to know if the click was inside a deck.gl geometry?

Another question: I see that you are capturing click, mousemove and mouseout events from Google Maps, why not all the other ones?

Thanks!

**Comment by Pessimistress** [comment]
Sorry, I was just explaining why GoogleMapsOverlay behaves differently from using Deck standalone. If you want dblclick supported we need to add a listener for that event. Feel free to open a PR.

> why not all the other ones?

I think dblclick is the only thing we are leaving out? https://developers.google.com/maps/documentation/javascript/events#ui-events

**Comment by Pessimistress** [comment]
Double click is supported in 8.2.4:

```js
new GoogleMapsOverlay({
  ...
  onClick: (info, event) => {
    if (event.tapCount === 2) {
      // double clicked
    }
  }
})
```
