### ISSUE TITLE
How to display both SimpleMeshLayer and HexagonLayer

### ISSUE THREAD

**Issue by emleechan** [visgl/deck.gl#4760]
Hi I currently have a few layers such as HeatmapLayer, PointCloudLayer, and HexagonLayer that can be displayed on top of each other. I have a 2D obj file that I also am able to display with SimpleMeshLayer in Orbit/Orthonormal view.

When SimpleMeshLayer  is displayed with the others in OrbitView/Orthonormal, the other layers become centralized in the middle of and the data points seems to have collapsed into one datapoint in the middle. 

Is it possible to display non-geospatial data (my obj file) and geospatial data (not collapsed in the centre) at the same time?

**Comment by Pessimistress** [comment]
You cannot render geospatial data with non-geospatial views (e.g. the OrbitView). For geospatial data, see supported [coordinate system](https://deck.gl/docs/developer-guide/coordinate-systems) documentation.

**Comment by emleechan** [comment]
Make sense. Would there be a way to load an OBJ file in a geospatial setting to display along the same coordinates as the geospatial data I'm currently displaying - maybe something similar to `https://deck.gl/examples/point-cloud-layer/`.

**Comment by Pessimistress** [comment]
Use `coordinateSystem: COORDINATE_SYSTEM.LNGLAT` (default) if your `getPosition` returns `[lng, lat, alt]`. Use `coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS` if your `getPosition` returns `[x, y, z]` in meters from `coordinateOrigin`.

**Comment by emleechan** [comment]
Great, Pointcloudlayer works! I know HexagonLayer and  HeatmapLayer only work with COORDINATE_SYSTEM.LNGLAT. Is there a way to display these ones as well alongside the x,y,z currently? Or even just display a flat png/obj with COORDINATE_SYSTEM.LNGLAT?

**Comment by Pessimistress** [comment]
I don't understand your question. Please check the linked documentation - coordinate system is per layer, so you can stack as many layers as you want of any coordinate system.

**Comment by emleechan** [comment]
Sorry let me reword, I'm trying to display Hexagonlayer in Orbitview along with the mesh layer, is this possible?  I have the appropriate points (lat, long, altitude) but it is rendering as one giant hexagon in Orbitview, but works fine in default view.

**Comment by Pessimistress** [comment]
As I said, OribitView does not understand geospatial coordinates.

It’s possible however to render xyz coordinates in a MapView (the default view). In your case, you will use MapView with two layers:
- `PointCloudLayer` with `coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS`
- `HexagonLayer` with
`coordinateSystem: COORDINATE_SYSTEM.LNGLAT` (default)
