### ISSUE TITLE
How to set the height of heat map ?

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4761]
I set the height of the heat map. But it doesn't work. The heat map is covered by geojson. How to solve this problem ?

![360截图20200709102206593](https://user-images.githubusercontent.com/24310750/86990106-6b8c4500-c1ce-11ea-8504-4c626cc0aee3.jpg)
![360截图20200709102739732](https://user-images.githubusercontent.com/24310750/86990325-ec4b4100-c1ce-11ea-8945-a2a572339298.jpg)
![360截图20200709102757619](https://user-images.githubusercontent.com/24310750/86990338-f40ae580-c1ce-11ea-8940-693c324b4d24.jpg)

**Comment by ibgreen** [comment]
You might be able to use the `modelMatrix` property.

**Comment by Doraemonnn** [comment]
@ibgreen 
I have set the properties of modelMatrix. But the heat map is surrounded by a black border. Is there any way to solve this problem ?

![360截图20200709133427027](https://user-images.githubusercontent.com/24310750/87001078-33dec680-c1e9-11ea-8695-961db0e16481.jpg)
![360截图20200709133446664](https://user-images.githubusercontent.com/24310750/87001092-3a6d3e00-c1e9-11ea-87fb-01bed037da09.jpg)

**Comment by Doraemonnn** [comment]
@ibgreen 
I have set the properties of modelMatrix. But the heat map is surrounded by a black border. Is there any way to solve this problem ?

![1](https://user-images.githubusercontent.com/24310750/87001651-85d41c00-c1ea-11ea-93a3-74797dddcaaf.jpg)
![2](https://user-images.githubusercontent.com/24310750/87001687-908eb100-c1ea-11ea-8fb1-0dd7ef8540e5.jpg)

**Comment by Pessimistress** [comment]
Try draw the HeatmapLayer after the PolygonLayer.

**Comment by Doraemonnn** [comment]
@Pessimistress 
I have set the HeatmapLayer after the PolygonLayer. But the color of the heatmap has been affected by  the PolygonLayer. How to solve this problem ?

![1](https://user-images.githubusercontent.com/24310750/87215499-9d85de80-c369-11ea-94a4-b09dc1d7128f.jpg)
![2](https://user-images.githubusercontent.com/24310750/87215503-a1b1fc00-c369-11ea-9995-1971d8e0bf0a.jpg)
![4](https://user-images.githubusercontent.com/24310750/87215529-f6557700-c369-11ea-9043-64f9771d7af3.jpg)

**Comment by Pessimistress** [comment]
We cannot debug your app from screenshots. Please create a Codepen/Code sandbox that reproduces your issue.
