### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by Georger2323** [visgl/deck.gl#4763]
I've just started developing in JS a few weeks now. I've used mapbox gl gs to create a few map visualizations.

Now I just came across deck and trying to get started with React. However, I couldn't find any complete tutorial on how to create a simple map.

For example, I've tried to do [this simple tutorial ](https://deck.gl/docs/get-started/using-with-react) but I don't know whether it's the complete code or not. e.g What am I supposed to write on index.html?

When I c/ped the second code from the above site (and after adding my mapbox api and "export default app" at the end), nothing appears when I run/debug the program although it loads correctly.

Aren't there any tutorials somewhere, like mapbox has where you can build simple apps?

**Comment by Pessimistress** [comment]
Look at the /examples/get-started in this repo.

They are also linked to in https://deck.gl/docs#react

**Comment by Georger2323** [comment]
The link I provided is one of the tutorials in this repo. However, as I said above, I believe it's not the complete code, because it doesn't work, but I don't know what is missing.

For example, when i copy paste the following code, nothing appears on the screen. 

`/// app.js
import React from 'react';
import DeckGL from '@deck.gl/react';
import {LineLayer} from '@deck.gl/layers';
import {StaticMap} from 'react-map-gl';

// Set your mapbox access token here
const MAPBOX_ACCESS_TOKEN = 'your_mapbox_token';

// Viewport settings
const INITIAL_VIEW_STATE = {
  longitude: -122.41669,
  latitude: 37.7853,
  zoom: 13,
  pitch: 0,
  bearing: 0
};

// Data to be used by the LineLayer
const data = [
  {sourcePosition: [-122.41669, 37.7853], targetPosition: [-122.41669, 37.781]}
];

function App({data}) {
  const layers = [
    new LineLayer({id: 'line-layer', data})
  ];

  return (
    <DeckGL
      initialViewState={INITIAL_VIEW_STATE}
      controller={true}
      layers={layers}
    >
      <StaticMap mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN} />
    </DeckGL>
  );
}`

**Comment by Pessimistress** [comment]
Have you clicked on the “full examples” link in the readme? They are complete, standalone setups that you can use to bootstrap a project.

If you want to learn react, you can also find tutorials on how to create a working React application on http://reactjs.org.
