### ISSUE TITLE
The bug of heat map

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4765]
When I set the properties of modelMatrix,  the heat map is surrounded by a black border. Is there any way to solve this problem ?

![87001651-85d41c00-c1ea-11ea-93a3-74797dddcaaf](https://user-images.githubusercontent.com/24310750/87113838-c0e55680-c2a1-11ea-9e42-06fe3c79c988.jpg)
![87001687-908eb100-c1ea-11ea-8fb1-0dd7ef8540e5](https://user-images.githubusercontent.com/24310750/87113846-c478dd80-c2a1-11ea-8daa-9b2ccc1512bd.jpg)

**Comment by Pessimistress** [comment]
Same as #4761

Please don’t open duplicate issues.
