### ISSUE TITLE
ArcLayer(layer) didn't move when zoom  page with mapbox NavigationControl

### ISSUE THREAD

**Issue by supercatlww** [visgl/deck.gl#4766]
#### Description
deck.gl/examples/get-started/pure-js/mapbox/

I use this demo when I add zoom controls on mapbox(like blew) , then zoom map with zoom controls,  layers(like ArcLayer, GeoJsonLayer) created by deck.gl didn't scale,  but map scaled.
var nav = new mapboxgl.NavigationControl();
map.addControl(nav, "top-right");

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 8.1.0]

#### Logs
I found function onViewStateChange didn't triggered when zoom page with mapbox NavigationControl, but triggered when scale page interaction by fingers.

**Comment by Pessimistress** [comment]
When you use pure-js, mapbox and deck.gl are independent instances that do NOT talk to each other. When one of the camera changes, your app is responsible of telling the other to update its camera as well.

You can see this in the example app where we subscribe to deck’s `onViewStateChange`:


https://github.com/visgl/deck.gl/blob/6fa00b515b9db225db5f4c8e09b0deebc99d855f/examples/get-started/pure-js/mapbox/app.js#L37-L44

When you use a Mapbox control, you’ll have to tell deck.gl that the map has changed by calling `deck.setProps` with a new viewState.

**Comment by supercatlww** [comment]
It works, thank you very much~
