### ISSUE TITLE
Mapbox layer throws an error when leaving the page

### ISSUE THREAD

**Issue by jjballano-qatium** [visgl/deck.gl#4767]
#### Description
I'm working in a React app where we want to have deck and mapbox layers. 
The code we have is something like this, removing many other lines of code that I think are not needed here:
```
const onLoad = (): void => {
    map.current.addLayer(
      new MapboxLayer({ id: "mylayerid", deck: deck.current }),
      "settlement-label"
    );
  };
[....]
<DeckGL width="100%"
            height="100%"
            effects={[]}
            ref={(ref): void => {
              deck.current = ref?.deck;
            }}
            initialViewState={viewState}
            onViewStateChange={onViewStateChange}
            layers={layers()}
            onHover={onMouseMove}
            onDrag={onMouseMove}
            controller={true}
            onLoad={onLoadDeck}
            onWebGLInitialized={onWebGLInitialized}
          >
            {glRef.current && (
              <ReactMapGL
                onLoad={onLoad}
                ref={(ref): void => {
                  map.current = ref?.getMap();
                }}
                width="100%"
                height="100%"
                mapboxApiAccessToken={token}
                preventStyleDiffing={true}
                mapStyle={styleId}
                gl={glRef.current}
              >
              </ReactMapGL>
            )}
          </DeckGL>
```

This is working well, but the error is thrown when I navigate to another page using react-router-dom. 
This makes Deck to execute [finalize method](https://github.com/visgl/deck.gl/blob/master/modules/react/src/deckgl.js#L111) which, among other things, removes the layerManager.
After that happened, Mapbox fire the render event, which [mapbox-layer is subscribed](https://github.com/visgl/deck.gl/blob/master/modules/mapbox/src/deck-utils.js#L58) so it gets executed and uses the layerManager.
In some other tests I made, [drawLayer is also executed by Mapbox](https://github.com/visgl/deck.gl/blob/master/modules/mapbox/src/mapbox-layer.js#L40) with same result of an error being thrown.

I've made a couple of changes [[1]](https://github.com/qatium/deck.gl/blob/master/modules/mapbox/src/deck-utils.js#L59) and [[2]](https://github.com/qatium/deck.gl/blob/master/modules/mapbox/src/deck-utils.js#L87) and now it's working, but I'm not sure if it's the best solution. If you think it's good enough, i could create a PR to you.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.0, mapbox-gl 1.11.0 and react-map-gl 5.2.7

#### Error thrown
![image](https://user-images.githubusercontent.com/60729742/87143802-06585280-c2a7-11ea-9140-4d342f1a0a34.png)

**Comment by Pessimistress** [comment]
Thanks for reporting this.

Your changes look reasonable, it would be great if you can open a PR!

Meanwhile, it's not clear to me why mapbox attempts to render after it's unmounted. Perhaps the "safe" way to write the application is to remove the layer on unmount, mirroring the `addLayer` operation:

```js
const [map, setMap] = useState(null);
const [gl, onWebGLInitialized] = useState(null);

useEffect(() => {
  if (map) {
    map.addLayer(id, ...);
  }
  return () => map && map.removeLayer(id);
}, [map]);

return (
  <DeckGL ... onWebGLInitialized={onWebGLInitialized}>
    {gl && <MapGL ... onLoad={evt => setMap(evt.target)}/>}
  </DeckGL>
);
```

**Comment by jjballano-qatium** [comment]
removeLayer also fire a render event which is handled by MapboxLayer after the layerManager is removed. 
I'm going to create the PR.

**Comment by Pessimistress** [comment]
Fixed published in `deck.gl@8.2.3`. Thank you!
