### ISSUE TITLE
How to debug in react?

### ISSUE THREAD

**Issue by stevenroussey-privicy** [visgl/deck.gl#4770]
The documentation mentions how to debug if you have a reference to the Deck object. But when using React and DeckGL, I have no reference and thus cannot debug. How can I set log levels?

As a point of reference, how to set log level in [this example](https://github.com/visgl/deck.gl/blob/master/examples/website/arc/app.js#L107)?

**Comment by Pessimistress** [comment]
`window.deck.log.level`

**Comment by stevenroussey-privicy** [comment]
OMG, it is a global. Thanks!
