### ISSUE TITLE
TripsLayer auto animation

### ISSUE THREAD

**Issue by stevenroussey-privicy** [visgl/deck.gl#4771]
#### Target Use case
* Easier to get started with the trips layer by not having to generate a separate event loop, which is often done poorly in react on first pass.
* Faster and more efficient by not running react updates on the entire map component tree
* Can stop animations when moving the map, etc.

#### Proposed feature
* Prop for `animate` to start the animation
* `initialTimestamp` for where to start the animation

OR

use `transitions` prop in some fashion

OR

AnimatedTripsLayer that handles the animation (updating the a child TripsLayer)

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Does transitions not work on `currentTime`?

**Comment by stevenroussey-privicy** [comment]
`transitions` does work! Just 16x off from doing it myself with request animation frame. Still, I will create a CompositeLayer that handles the timeouts (in this case, just so they repeat).
