### ISSUE TITLE
ArcLayer animation options

### ISSUE THREAD

**Issue by stevenroussey-privicy** [visgl/deck.gl#4772]
#### Target Use case
* animated arcs looks cool, and everyone loves recreating WarGames
* animating arcs is difficult. Previous attempts are no longer valid on newer versions of deck.gl

#### Proposed feature
* provide props for animation (boolean), and speed. Perhaps delay to start (typical case is to fly in to bounds and then play animation).
* could use transitions?

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Check out https://observablehq.com/@pessimistress/deck-gl-tutorial-subclassing-a-layer

We strive to keep the core layers concise and performant for the most common use cases. We could accept a PR for a new layer extension if the API is generic enough.

**Comment by stevenroussey-privicy** [comment]
Nice example! 

It does not work for me though, I get this error:

```
:3000/static/js/35.chunk.js:320642 luma.gl: GLSL compilation errors in vertex shader arc-layer-vertex-shader-1
629:   DECKGL_FILTER_COLOR(vColor, geometry);
630: 
631: vArcLength = distance(source, target);
^^^ ERROR: 'target' : undeclared identifier
```

I assume some internal structure changed from v8.0.17 to v8.2.2 (maybe globe related?)

I'll look into layer extensions in the meantime.

**Comment by stevenroussey-privicy** [comment]
Looks like the declarations were moved inside an if statement. Fix would be to declare (but not set) the variables earlier, before the if block. Just guessing, since I don't know how these shaders work.

**Comment by stevenroussey-privicy** [comment]
What is `geometry.uv.x` that everything is based on?

**Comment by Pessimistress** [comment]
I believe `u` is between -1 and 1 along the width of the arc.
