### ISSUE TITLE
Transitions enter function

### ISSUE THREAD

**Issue by stevenroussey-privicy** [visgl/deck.gl#4773]
Can someone help me with transitions on a layer and the `enter?: (v: number) => number` function? I can't grok what it does. 

My use case: I have a hexagon layer and when I fly to it (well, just after), I want it to animate the values from 0 to their calculated weights.

At the moment, I am just setting
```js
transitions: {
      elevationScale: {type: "interpolation", duration: 600 }
```

That would work great if the position and zoom of the viewport was static and the data was changing. But in my case the data is static, but I want it animate the elevation on command (from zero).

**Comment by Pessimistress** [comment]
You need to set `elevationScale` to 0 on the first render. Transition is triggered when you set i`elevationScale` to the target number when you’re ready.

`enter` only works for attribute transitions, where a “from value” may not be found.

**Comment by stevenroussey-privicy** [comment]
Thanks for the elevationScale hint.

Can you give an example on when enter() would be used? Thanks.

**Comment by Pessimistress** [comment]
https://codepen.io/Pessimistress/pen/YzwzqNE

**Comment by yuya737** [comment]
@Pessimistress could you briefly explain why `getRadius` in your `ScatterplotLayer` example can be animated via `transitions: {enter: ...}` without a previous render, and `elevationScale` needs a prior layer to exist from which to animate?

Is it related to attribute transitions? I'm unclear about what that precisely means
