### ISSUE TITLE
H3TileLayer

### ISSUE THREAD

**Issue by stevenroussey-privicy** [visgl/deck.gl#4777]
#### Proposed feature & Target Use case
* Like the TileLayer, the ability to load only the data needed for display at a specific zoom layer, but using h3 hexagons instead of squares so that the request matches the indexed data.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Check out https://github.com/visgl/deck.gl/tree/master/examples/experimental/h3-grid
