### ISSUE TITLE
how to dynamically change the light

### ISSUE THREAD

**Issue by yuxiangyu** [visgl/deck.gl#4785]
Hi, I want change the position or intensity of the light in the runtime. for example when click a polygon, the point light can move to the top of the polygon and the light can be  gradually diminished after one second.

**Comment by Pessimistress** [comment]
Check the embedded Codepen in this page: https://deck.gl/docs/api-reference/core/lighting-effect

The key is to keep persistent light instances, and call `deck.redraw(true)` whenever the options have changed.

**Comment by yuxiangyu** [comment]
Thanks, I'll try it
