### ISSUE TITLE
Scatterplot Radius Transition Not Working

### ISSUE THREAD

**Issue by sambaskin** [visgl/deck.gl#4787]
I've been trying to get an animated scatterplot layer to work, but the point is just static on the map. 
My goal is for the radius to increase over a 1000 ms duration, similar to [this example](https://codepen.io/jianhuang01/pen/JzjBxj
). 
I've tried changing the code for transitions in different ways based off what I've seen in other examples, but it either runs into an error and doesn't display anything, or just displays the static icon. 

I've also re-downlodaed the node_modules just in case I was missing something related to transitions, but that didn't affect anything.

Also, I tried using the exact code from the above example and it still doesn't work. 

Is there anything outside of the scatterplot layer in app.js that could be preventing the transition from playing? 

Code: (app.js)
```
import React from 'react';
import {render} from 'react-dom';
import {StaticMap} from 'react-map-gl';
import DeckGL from '@deck.gl/react';
import {ScatterplotLayer} from '@deck.gl/layers';
import point_data from './pickupData.json';
import token from './token.json';
// Set your mapbox token here
const MAPBOX_TOKEN = token[0]
const MALE_COLOR = [0, 128, 255];
const FEMALE_COLOR = [255, 0, 128];

// Source data CSV
const DATA_URL = 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/bart-stations.json'
 // 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/scatterplot/manhattan.json'; // eslint-disable-line

const INITIAL_VIEW_STATE = {
  longitude: -84,
  latitude: 34,
  zoom: 11,
  maxZoom: 16,
  pitch: 0,
  bearing: 0
};

export default function App({
  data = point_data,
  mapStyle = 'mapbox://styles/mapbox/light-v9'
}) {
  const layers = [
    new ScatterplotLayer({
      id: 'scatter-plot',
      data,
      pickable: true,
      stroked: false,
      radiusScale: 6,
      radiusMinPixels: 1,
      radiusMaxPixels: 100,
      lineWidthMinPixels: 1,
      getPosition: d => [d[0], d[1], 0],
      getFillColor: [0, 128, 255],
      getLineColor:[0,0,0],
      getRadius: 40,
      transitions:
      {
          getRadius: {
          duration: 1000,
          enter: t => [t[0]*0.1]
        }
      }
    })
  ];

  return (
    <DeckGL layers={layers} initialViewState={INITIAL_VIEW_STATE} controller={true}>
      <StaticMap
        reuseMaps
        mapStyle={mapStyle}
        preventStyleDiffing={true}
        mapboxApiAccessToken={MAPBOX_TOKEN}
      />
    </DeckGL>
  );
}

export function renderToDOM(container) {
  render(<App />, container);
}`
```

Source:
pickupData.json 

```
[
[-84,34,40]
]

```
I'm only animating one point just to keep it simple. Format: [lon,lat,radius]

**Comment by Pessimistress** [comment]
Your `radiusMinPixels` prop is in effect. Remove it and you will see the transition.

**Comment by sambaskin** [comment]
> Your `radiusMinPixels` prop is in effect. Remove it and you will see the transition.
I just tried that and it's still not animating. I also tried removing lineWidthMinPixels and radiusMaxPixels and still no luck

**Comment by Pessimistress** [comment]
https://codepen.io/Pessimistress/pen/YzwzqNE

Note that attribute transition only works in WebGL2-enabled browsers (i.e. no Safari). You should see a warning in the console if it's not supported.

**Comment by sambaskin** [comment]
I'm running chrome 83.0.4103.116 which I think is WebGL2-enabled

**Comment by sambaskin** [comment]
<img width="537" alt="Screen Shot 2020-07-15 at 8 29 21 PM" src="https://user-images.githubusercontent.com/30935970/87612956-f5aa4100-c6d9-11ea-9678-b4a7233e6d64.png">
Here are the warnings I get in the console

**Comment by Pessimistress** [comment]
You are using a very old version of deck.gl. I don't think attribute transition was supported then.

**Comment by sambaskin** [comment]
I'll update now, and let you know if it fixes it. Thanks!

**Comment by sambaskin** [comment]
I've been running npm install deck.gl again, but that doesn't seem to work. I'm assuming I'm updating incorrectly. What's the correct way to update? I couldn't find any documentation on it online

**Comment by Pessimistress** [comment]
> I couldn't find any documentation on it online

Google "how to update npm package"

**Comment by sambaskin** [comment]
That worked thanks!
