### ISSUE TITLE
Scatterplot Zoom - Condense X-axis instead of changing radius.

### ISSUE THREAD

**Issue by karthik947** [visgl/deck.gl#4792]
I'm using Scatterplot layer for non-geospacial data where I need to plot an elongated horizontal chart. I'm running into a unique issue where instead of changing the radius of each point during zoom, the axis (X- axis) need to be condensed. The points overlap when the axis get condensed, which is creates a pattern, is what my objective here is. Let me illustrate with a picture.

In the below picture, during zoom 1 you can see the scatterplot against 4 points in xaxis and multiple y axis points. When I zoom out (zoom2), I need to condense the data to just 2 x axis points keeping the radius constant. Same thing with zoom 3, condense x-axis and plot. The goal is to zoom axis and not the data, which I tried to find the documentation for but couldn't.  Any assistance is greatly appreciated! Thank you. 

![image](https://user-images.githubusercontent.com/30058307/87703188-1052e780-c7b8-11ea-8a30-2974402251cc.png)

**Comment by Pessimistress** [comment]
Some high-level ideas:

- Use a `modelMatrix` with your ScatterplotLayer:

```js
import {Matrix4} from 'math.gl';

let scaleX = 1;

const layer = new ScatterplotLayer({
  id: 'points',
  modelMatrix: new Matrix4().scale([scaleX, 1, 1]),
  ...
});
```

- Implement a [custom controller](https://deck.gl/docs/api-reference/core/controller#event-handling):

```js
import {OrthographicView, OrthographicController} from '@deck.gl/core';

class MyController extends OrthographicController {
  handleEvent(event) {
        if (event.type === 'wheel') {
            this.onWheel(event);
        } else {
            super.handleEvent(event);
        }
    }

  setProps(props) {
    super.setProps(props);
    this.onWheel = props.onWheel;
  }
}

Deck({
  views: new OrthographicView(),
  controller: {onWheel: updateXScale},
  ...
});
```

**Comment by karthik947** [comment]
Thanks for the response. I tried this but couldn't get to work. I've used modelMatrix also implemented custom controller. I created updateXScale function to know the current zoom and pan (arguments below) but don't know how to translate that onto the chart.

![image](https://user-images.githubusercontent.com/30058307/87750502-44aac000-c819-11ea-8420-d16a8c58f3e5.png)

**Comment by karthik947** [comment]
I used the prop radiusUnits and set it to pixels to prevent scaling while zooming. This seems to do the trick. The rendering performance isn't great though, I thought deckgl is capable of identifying overlapping pixels and avoid rendering them to boost performance. My plot size is  just 100k points but the performance is painfully slow when I zoom in and out. Anyways, I'm closing this issue as I figured out the solution for keeping the radius static while zooming.

`radiusUnits : 'pixels'`

**Comment by Pessimistress** [comment]
The performance during zooming should not be different unless you are changing point positions. If you post your solution here we can help you identify perf issues and it will help others who try to implement the same feature in the future.

**Comment by karthik947** [comment]
Thank you. I'll open a separate issue and link it here to avoid confusion.

**Comment by prostgles** [comment]
I'm trying to achieve something similar where the y-axis scale should not change (zooming should not change the y distance between the two points).

I've tried the following code but it does not seem to do what I need.

Will appreciate any sort of help

https://codepen.io/vis-gl/pen/YzpXqzv
```
/*
* https://deck.gl/docs/api-reference/core/orthographic-view
*/

const {DeckGL, OrthographicView, ScatterplotLayer, TextLayer} = deck;


let getMMatrix = (zoom) => [Math.max(0, zoom), 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];// new Matrix4().scale([Math.max(1, zoom), 1, 1]);
let _deck = new DeckGL({
  views: new OrthographicView({
    flipY: false,
    // near: 0.1,
    // far: 1000,
  }),
  initialViewState: {
    target: [100, 100, 0],
    zoom: 0,
    minZoom: -2,
    maxZoom: 40
  },
  controller: true,
  onViewStateChange: ({viewState}) => {
    render(viewState.zoom)
  },
  layers: [ ]
});
render(0)

function render(zoom = 0){
  _deck.setProps({
    layers: [
      new ScatterplotLayer({
        id: 'circles',
        data: [
          { x: 0, y: 0, r: 20 },
          { x: 110, y: 110, r: 20 },
        ],
        modelMatrix: getMMatrix(zoom),
        getPosition: d => [d.x, d.y],
        getRadius: d => d.r,
        getFillColor: d => [0,0,0],
        getLineWidth: 1,
        lineWidthUnits: 'pixels',
        radiusUnits : 'pixels',
        stroked: true
      })
    ]
  })
}
  
```

**Comment by Pessimistress** [comment]
@prostgles zoom is logarithmic. The viewport scale is `2 ** zoom` and to counter that you need to transform your data with `1/2 ** zoom`.

BTW your code is creating a new `data` object on every render. You need to set it as a constant to avoid perf hit.

**Comment by prostgles** [comment]
Thanks for the quick reply and the tips!

I've amended as seen below but Y axis is still collapsing and zooming origin deviates from cursor position.

```js
let getMMatrix = (zoom) => [2 ** (zoom/2), 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
```

**Comment by Pessimistress** [comment]
@prostgles `1/2 ** zoom` is not `2 ** (zoom/2)`.

**Comment by prostgles** [comment]
My mistake. I've tried with `[1/2 ** zoom, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]` but still no joy. 

I've noticed that with this value the x distance between the points seems fixed so I changed the func to ` [1, 0, 0, 0, 0, 1/2 ** zoom, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];` which seems ok (locks y scale) except that scroll anchoring seems broken (zooming with the cursor centred on the right circle should keep it in the same position)

**Comment by Pessimistress** [comment]
> scroll anchoring seems broken 

You need to lock `viewState.target`'s y in `onViewStateChange`, see https://deck.gl/docs/developer-guide/interactivity#add-constraints-to-view-state

**Comment by prostgles** [comment]
I am not sure I fully understand what needs doing. The `viewState.target` examples refer to how the center point of the drawing relates to the screen which means that a constant value would only lock the center. In my case I feel like I would need to adjust the target `y` value based on `zoom` and the `cursor.y` position to ensure that the point drawn under the cursor does not change position after zooming

**Comment by Pessimistress** [comment]
```js
  onViewStateChange: ({viewState, oldViewState}) => {
    render(viewState.zoom)
    const oldScale = 2**oldViewState.zoom;
    const newScale = 2**viewState.zoom;
    if (oldScale != newScale) {
      viewState.target[1] = oldViewState.target[1] / newScale * oldScale;
    }
    return viewState;
  }
```

**Comment by prostgles** [comment]
Thank you very much for helping me out!

This is the final code that works as expected:

```js

const {DeckGL, OrthographicView, ScatterplotLayer, TextLayer} = deck;

let getMMatrix = (zoom) => [1, 0, 0, 0, 0, 1/2 ** zoom, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];// new Matrix4().scale([Math.max(1, zoom), 1, 1]);
let _deck = new DeckGL({
  views: new OrthographicView({
    flipY: false,
    // near: 0.1,
    // far: 1000,
  }),
  initialViewState: {
    target: [100, 100, 0],
    zoom: 0,
    minZoom: -2,
    maxZoom: 40
  },
  controller: true,
  onViewStateChange: ({viewState, oldViewState}) => {
    render(viewState.zoom)
    const oldScale = 2**oldViewState.zoom;
    const newScale = 2**viewState.zoom;
    if (oldScale != newScale) {
      viewState.target[1] = oldViewState.target[1] / newScale * oldScale;
    }
    render(viewState.zoom)
    return viewState;
  },
  layers: [ ]
});
render(0)

function render(zoom = 0){
  _deck.setProps({
    layers: [
      new ScatterplotLayer({
        id: 'circles',
        data: [
          { x: 0, y: 0, r: 20 },
          { x: 110, y: 110, r: 20 },
        ],
        modelMatrix: getMMatrix(zoom),
        getPosition: d => [d.x, d.y],
        getRadius: d => d.r,
        getFillColor: d => [0,0,0],
        getLineWidth: 1,
        lineWidthUnits: 'pixels',
        radiusUnits : 'pixels',
        stroked: true
      })
    ]
  })
}
```
