### ISSUE TITLE
[MapboxLayer] Weird render artifacts when color with opacity

### ISSUE THREAD

**Issue by Akiyamka** [visgl/deck.gl#4794]
#### Description
When i add alfa (opacity) to rgba it looks broken
```
getFillColor: [255, 0, 0, 100]
```
![image](https://user-images.githubusercontent.com/6587585/87711412-e72e5900-c7af-11ea-9fd9-4a460ef7df82.png)

#### Repro Steps
- A CodeSandbox [example](https://codesandbox.io/s/epic-paper-mem5b?file=/src/App.js
) that reproduces the behavior

#### Environment (please complete the following information):
@deck.gl/core: 8.1.10
@deck.gl/layers: 8.1.10
@deck.gl/mapbox: 8.1.10 
- Browser Version: Firefox 78.0.1 (64-bit)
 - OS: Linux (Fedora 32)

**Comment by Akiyamka** [comment]
In chrome 
![image](https://user-images.githubusercontent.com/6587585/87712100-e0541600-c7b0-11ea-8092-273e1fc0cb92.png)

**Comment by Pessimistress** [comment]
I can't reproduce this with FF 78.0.2 on Windows and Mac. Might be an OS-related issue?

**Comment by Akiyamka** [comment]
@Pessimistress thank you for response.
I have tested on 5 machines and can say the scariest artifacts are visible on a combination of linux, firefox and proprietary NVIDIA drivers =).
<details>
  <summary>Screenshot</summary>

 ![image](https://user-images.githubusercontent.com/6587585/87764251-bd604b00-c81e-11ea-89a6-6f2b6c50e5ff.png)
</details>

In setups where everything looks not so bad, the artifact appears in rare scenarios (for example, first hot page reloading in the codesendbox broke render)

However, on all devices in all browsers, I do not see that transparency works, rather the color becomes lighter as the alpha channel value decreases
<details>
  <summary>Half transparent</summary>

![image](https://user-images.githubusercontent.com/6587585/87764967-e0d7c580-c81f-11ea-8089-92b2bdf2ea88.png)
</details>

**Comment by Pessimistress** [comment]
If you change your code to use `MapboxLayer` directly instead of an existing Deck instance:

```js
const deckLayer = new MapboxLayer({
        type: ScatterplotLayer,
        id: "scatter-plot",
        ...
      });

      map.on("load", () => {
        map.addLayer(deckLayer);
      });
```

The opacity should work.

Alternatively, you can add the following to the `Deck` constructor:

```js
import GL from '@luma.gl/constants';

new Deck({
  ...
  parameters: {
    depthMask: true,
    depthTest: true,
    blendFunc: [GL.SRC_ALPHA, GL.ONE_MINUS_SRC_ALPHA, GL.ONE, GL.ONE_MINUS_SRC_ALPHA],
    blendEquation: GL.FUNC_ADD
  }
})
```

Because you are using Mapbox integration, it is expected to have some complications. There is no guarantee that Mapbox will restore the WebGL parameters when it hands the context back to deck.gl.

**Comment by Akiyamka** [comment]
@Pessimistress, thank you very match!

> Alternatively, you can add the following to the Deck constructor:
Unfortunately, this did not give any results, everything remained as it was

> If you change your code to use MapboxLayer directly instead of an existing Deck instance:
But this option worked perfectly.

> Because you are using Mapbox integration, it is expected to have some complications.
As I understand it this is where the magic begins to solve mapbox and deckgl integration problems =)
https://github.com/visgl/deck.gl/blob/d9c2f34847c1a950609a2e5480a34e42807e8eed/modules/mapbox/src/deck-utils.js#L34
