### ISSUE TITLE
does Scatterplot layer support altitude ?

### ISSUE THREAD

**Issue by djouallah** [visgl/deck.gl#4795]
I am using Deck.GL to create a custom Visual in Google datastudio and it works perfectly, see report here.

https://datastudio.google.com/u/0/reporting/65758cec-07e2-404f-a1f9-cf57043ca48d/page/SVfXB

sorry if the questions was answered elsewhere, but I can't make scatterplot  to render altitude, what am Doing wrong ?

see code here

const INITIAL_VIEW_STATE = {
    
    bearing: 0,
    longitude: longitudeView,
    latitude:  latitudeView,
    zoom: zoomparameter,
    minZoom: minZoomparameter,
    maxZoom: maxZoomparameter,
    pitch: Pitchparameter,
    
  };
new Deck({
  width: width,
  height: height,
  initialViewState: INITIAL_VIEW_STATE,
  
  controller: true,
  layers: [
    new ScatterplotLayer({
      data : vizData,
      radiusScale   : radiusScaleparameter,
      getPosition: d => [d.lng,d.lat,0 + d.alt],
      getRadius: d => (d.sizeid || DefaultSize) ,
      getFillColor: d => ( COLOR_SCALE(d.colorid) || [0,0,0] ),
      radiusMinPixels: radiusMinPixelsparameter,
      radiusMaxPixels: radiusMaxPixelsparameter,
      pickable: true,
      
    })
  ],

**Comment by Pessimistress** [comment]
> I can't make scatterplot to render altitude

I can't tell from your link what the altitude values you are trying to use. When you are looking at the whole world like this altitude probably start to be noticeable from 10KM up.

**Comment by djouallah** [comment]
Thank You very much what a great Product !!!!!
