### ISSUE TITLE
The display of GLB model in deck.gl is different from three.js

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4796]
Why does the GLB model display differently on the page and in the tool ? I use GLTFLoader to load the model. And the version of @loaders.gl is 2.2.7.

![1](https://user-images.githubusercontent.com/24310750/87746419-1c27c380-c823-11ea-9031-2776d22224f5.jpg)
Display effect on the page

![2](https://user-images.githubusercontent.com/24310750/87746437-23e76800-c823-11ea-9577-7088df845912.jpg)
Display effect in tools

![5](https://user-images.githubusercontent.com/24310750/87746557-7cb70080-c823-11ea-8dbf-f6eb584015e5.jpg)

![4](https://user-images.githubusercontent.com/24310750/87746443-28ac1c00-c823-11ea-93c3-44abfdc84c4d.jpg)

**Comment by ibgreen** [comment]
@Doraemonnn, thanks for reporting. What is the difference between what you call "page" and "the tool"? One is deck.gl in your browser and one is something else, some other app that is not related to deck.gl?

**Comment by Doraemonnn** [comment]
@ibgreen 
Here is the address of the website : https://gltf-viewer.donmccurdy.com/ . You can upload GLB files on this website.

I also uploaded GLB's compressed package.
[0001.zip](https://github.com/visgl/deck.gl/files/4936128/0001.zip)

**Comment by Pessimistress** [comment]
You need `_lighting: 'pbr'` [documentation](https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer#_lighting)
