### ISSUE TITLE
Trips layer doesn't animate after upgrading Deck.GL

### ISSUE THREAD

**Issue by sambaskin** [visgl/deck.gl#4799]
I updated Deck.GL from 7.0 to the latest version, and a project that uses a trips layer doesn't animate the trips anymore. When I run it, it just displays paths. I've tried lowering the opacity to see if there's any movement, but everything is completely static. At the time that the first trip is supposed to start, every trip appears simultaneously as a path.
I did modify the trips layer source file (I removed the trail fade and also made each trail a standard length), but I've tried replacing it with the original trips-layer.js file and I still have the same problem.
I didn't see any trips layer changes in the [update log.](https://github.com/visgl/deck.gl/blob/master/docs/upgrade-guide.md)

Does anybody know what could cause this?

**Comment by Pessimistress** [comment]
Also note that `getTimestamps` was added in 7.1. The `[lng, lat, timestamp]` format has been deprecated.

**Comment by sambaskin** [comment]
I completely blanked on including the code, my bad! The issue was that I was using the [lng,lat,timestamp] format. Thanks!
