### ISSUE TITLE
IconLayer data won't update with esri arcgis maps

### ISSUE THREAD

**Issue by ronavraham** [visgl/deck.gl#4804]
I'm using deck.gl Icon Layer through the arcgis support, and when I change the layer's data prop, the layer won't redraw.

for example, given this code:
```
var layer = new DeckLayer();

layer.deck.layers = [new IconLayer({
  id: 'icon-layer',
  data: this.graphics, // 10,000 different graphics created earlier
  pickable: true,
  iconAtlas: 'https://image.flaticon.com/icons/svg/3075/3075933.svg',
  iconMapping: { marker: { x: 0, y: 0, width: 512, height: 512, mask: true }},
  scaleSize: 15,
  getIcon: d => 'marker',
  getPosition: d => [d.geometry.x, d.geometry.y],
  getSize: d => 50,
  getColor: d => [Math.sqrt(d.exits), 140, 0],
})];

new MapView({
        container: "viewDiv",
        map: new ArcGISMap({
          basemap: "dark-gray-vector",
          layers: [this.layer]
        }),
        center: [34, 32],
        zoom: 6
      });

updatelayer() {
     let il = layer.deck.layers.find(l => l.id === 'icon-layer');
     il.props.data = [];
 }
```
The layer won't redraw after calling `updatelayer()`, and won't get cleared.
Also, the example on esri's website [(https://developers.arcgis.com/javascript/latest/sample-code/custom-lv-deckgl/index.html)](https://developers.arcgis.com/javascript/latest/sample-code/custom-lv-deckgl/index.html)
won't work as well if I change the way it works, so that every 50 ms the layer won't get recreated from scratch but just update it's data prop.

**Comment by Pessimistress** [comment]
You are supposed to create a new layer instance to update props. The `props` object is frozen and cannot be modified. Creating a new layer instance is very cheap. See https://deck.gl/docs/developer-guide/using-layers#should-i-be-creating-new-layers-on-every-render

**Comment by ronavraham** [comment]
@Pessimistress Thanks for the clarification.
