### ISSUE TITLE
Add text to IconLayer

### ISSUE THREAD

**Issue by Dorni2** [visgl/deck.gl#4813]
Hey,
I'm trying to add a short text under each icon in my IconLayer which describe it.

Of course I can add a new text layer with some offset from each icon, but this solution will be inefficient with large amount of data, so I'm looking for another option.

Thank you.

**Comment by Pessimistress** [comment]
> Of course I can add a new text layer with some offset from each icon

I don't get this - you should only need one `TextLayer` that uses the same data as your `IconLayer`. There is a [getPixelOffset](https://deck.gl/docs/api-reference/layers/text-layer#getpixeloffset) prop to set the offset.
