### ISSUE TITLE
How to disable the right mouse button？

### ISSUE THREAD

**Issue by Doraemonnn** [visgl/deck.gl#4815]
When I drag the right mouse button, the bottom of the model is exposed. The tester of my company has brought this bug to me. How to disable the right mouse button？

![11](https://user-images.githubusercontent.com/24310750/88246305-aa40f580-cccc-11ea-9177-6d690ca44fda.jpg)
Figure 1

![22](https://user-images.githubusercontent.com/24310750/88246349-ce9cd200-cccc-11ea-9751-5027bbf87d36.jpg)
Figure 2

**Comment by Pessimistress** [comment]
You can implement a custom `MapController` by overriding the [handleEvents](https://deck.gl/docs/api-reference/core/controller#event-handling) method.
