### ISSUE TITLE
Location of camera on pitch 89.5

### ISSUE THREAD

**Issue by MacieJCzarkowskI** [visgl/deck.gl#4816]
Hey,
I'm trying to set starting location exactly where is the point on my picture
`			viewState: {
				pitch: 89.5,
				latitude: (the same location as pin),
				longitude:  (the same location as pin),
			},
`
But camera is far from this point, so the question is, can i change the distance observer/point ?

![localizationOfPopup](https://user-images.githubusercontent.com/28688531/88311126-d0888480-cd10-11ea-96fd-ce8a74bd2d7c.png)

**Comment by Pessimistress** [comment]
The default `maxPitch` is 60. You need to set it to 90.

**Comment by MacieJCzarkowskI** [comment]
I have set it to 90 degrees but problem is that i would like to be closer this point on this pitch :)

**Comment by Pessimistress** [comment]
The default view (MapView) looks AT the specified location instead of looking FROM it. You can try [FirstPersonView](https://deck.gl/docs/api-reference/core/first-person-view).
