### ISSUE TITLE
pydeck Error displaying widget with binary transport

### ISSUE THREAD

**Issue by dgiebs** [visgl/deck.gl#4824]
#### Repro Steps
Copied code from https://pydeck.gl/gallery/binary_transport.html into a jupyter notebook (jupyter lab),
run `generate_vis(True)`, results in `Error displaying widget`, logs below.

#### Environment (please complete the following information):
@deck.gl/jupyter-widget v8.2.3
pydeck 0.4.0
Chrome Version 84.0.4147.89 (Official Build) (64-bit)
Mac OS X 10.14.6

#### Logs
```
index.js:18 Uncaught (in promise) TypeError: Cannot read property '2bd30f32-927b-441f-9ce7-eba1095c6b9f' of undefined
    at c.binary (index.js:18)
    at Object.onMessage (index.js:18)
    at e.value (index.js:18)
    at e.value (index.js:18)
    at e.value (index.js:18)
    at manager-base.js:93
```
that uuid is the layer id

**Comment by Pessimistress** [comment]
Fix is published in @deck.gl/jupyter-widget v8.2.4

**Comment by ajduberstein** [comment]
Fixed in the latest release of pydeck: https://pypi.org/project/pydeck/0.4.1/

**Comment by dgiebs** [comment]
awesome, thanks!
