### ISSUE TITLE
TerrainLayer With STK/AGI Terrain Service?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#4825]
Is it possible to use the [TerrainLayer](https://deck.gl/docs/api-reference/geo-layers/terrain-layer) with an [STK/AGI Terrain Service](https://help.agi.com/TerrainServer/RESTAPIGuide.html)?

In looking at the TerrianLayer [example](https://github.com/visgl/deck.gl/blob/master/examples/website/terrain/app.js) it appears deck requires a url to `elevationDecoder` and `elevationData`... I am not seeing a way to get such urls from the STK/AGI Terrain Service...

**Comment by kylebarron** [comment]
Loaders.Gl now has a quantized mesh loader so you can do it, you'll just have to slightly modify the terrain layer code

**Comment by Pessimistress** [comment]
Consolidating with #4236
