### ISSUE TITLE
Ability to cancel tile requests (even after they start)

### ISSUE THREAD

**Issue by supersonicclay** [visgl/deck.gl#4831]
#### Target Use case
Improve performance when `getTileData` makes `fetch` requests that are slow. Browsers only allow so many concurrent `fetch` requests. If a user pans around enough fill up the max concurrent requests of the browser, then newer requests for what the user is actually seeing are queued behind requests for tiles that are now off the screen.

#### Proposed feature

Expose an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) instance to the `getTileData` function. If a tile's request is "cancelled", then its abort signal is triggered. This AbortSignal can be passed to the `fetch` options in order to cancel the fetch request if, for example, a tile never finished loading and is now off the screen.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by kylebarron** [comment]
Ref related previous discussion here: https://github.com/visgl/deck.gl/issues/4429#issuecomment-634270281

**Comment by Pessimistress** [comment]
As of 8.2.0, cancelled tiles should not call `getTileData` at all. The suggestion in the other thread deals with `getTileData` that contains multiple async operations, and allow a tile to be cancelled when it's only partially done.

**Comment by kylebarron** [comment]
I think the question is when the cancellation happens, and there's 3 points where it might make sense:

- Before a `fetch` is initiated, this is already implemented in 8.2
- After a `fetch` is initiated, while waiting for a slow network request. I believe this is what @supersonicclay is interested in; since the browser has a maximum number of concurrent requests, it would be nice to abort a `fetch` that has already started but is no longer in view, which would more quickly allow a new tile to start loading.
- After a `fetch` has finished, where you have some compute intensive transformation of the downloaded data. This is what was discussed in https://github.com/visgl/deck.gl/issues/4429#issuecomment-634270281

**Comment by supersonicclay** [comment]
Exactly @kylebarron !

**Comment by kylebarron** [comment]
It seems like you just want to pass an `isCancelled` or maybe `onCancelled` prop through to `getTileData`...?

https://github.com/visgl/deck.gl/blob/1aff4952f5a5229abcd18e50af977c25eabee76a/modules/geo-layers/src/tile-layer/tile-2d-header.js#L57

**Comment by supersonicclay** [comment]
I don't think `isCancelled` ever changes to true after a call to `getTileData` starts.

Also, I think it is much cleaner and more reusable to expose an `AbortSignal` directly to the `getTileData` function. That way, callers have less they need to implement. I also want to integrate this into the standard way of using `TileLayer.data` since that also makes `fetch` requests that may be slow.

**Comment by ibgreen** [comment]
As mentioned before (caveat I haven't tested it):

If you have a signal from an [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) and you are using loaders.gl, the following should work

```js
const controller = new AbortController();
load(url, [loaders...], {fetch: {signal: controller.signal}}
``` 

As you can see, `signal` is an option to `fetch()`, and if you pass `fetch` option object to loaders.gl `load()`, it will be passed on as options to `fetch`.

Alternativeky, you can call fetch directly yourself, and call `parse` on the `Response`:
```js
const response = await fetch(url, {signal});
parse(response, [loaders...]);
```

`Layer.loadOptions` is basically an options object that deck.gl passed to loaders.gl, so `{fetch: signal}` should work there as well, though perhaps you'll need to find a way to pass a signal from freshly minted `AbortController`.

**Comment by supersonicclay** [comment]
@ibgreen that's what I'm looking to do. But I think it makes sense for deck.gl to construct the `AbortController`s and provide them in:
1. As a property to the argument to `getTileData` if provided or
2. As part of the options passed to its fetch calls if the application passes `data` array with the x, y, z placeholders

I'll open a PR in a bit to show what I'm proposing.

**Comment by kylebarron** [comment]
> As part of the options passed to its fetch calls if the application passes `data` array with the x, y, z placeholders

Note that the `data` prop doesn't call `fetch` on its own. The `data` prop only handles url resolution, and then passes to `getTileData`. So I think the argument is to send an `AbortSignal` instance to the default `getTileData`, which is `fetch`:
https://github.com/visgl/deck.gl/blob/1aff4952f5a5229abcd18e50af977c25eabee76a/modules/geo-layers/src/tile-layer/tile-layer.js#L139-L144

**Comment by supersonicclay** [comment]
You can see the PR for what I'm thinking. There's one TODO in there to better prioritize which ongoing requests get aborted. Right now, it just aborts any ongoing tile request that is no longer visible.

**Comment by supersonicclay** [comment]
The PR is now ready for review and works well.
