### ISSUE TITLE
How to update Deck gl layer on Mapbox gl js

### ISSUE THREAD

**Issue by John2397** [visgl/deck.gl#4834]
I'm currently using Deck's layers on Mapbox gl js.

I have a scatter plot layer in which I insert data periodically (every x ms).

My question is how can I update the map once the new data are pushed to the layer?

This is how I declare and push data to the layer:

```
const myDeckLayer = new MapboxLayer({
    id: 'my-scatterplot',
    type: ScatterplotLayer,
    data: [
        {position: [100.434,30.3344, 10], size: 3}
        
    ],
    getPosition: d => d.position,
    getRadius: d => d.size,
    getColor: [255, 0, 0]
});

map.on('load', function ()
{
    var timer = setInterval({
		myDeckLayer.props.data.push(myObject)
	}, 200)
});
```

If the above was a mapbox layer, I could call the following every time I'd like to update the map:
`map.getSource('sourceID').setData(jsonObject)`

But how could I do that using the Deck gl layer in pure Javascript?

**Comment by Pessimistress** [comment]
You should not mutate an existing data array. Layers are only updated if props change shallowly.

Call [setProps](https://deck.gl/docs/api-reference/mapbox/mapbox-layer#setpropsprops) with a new `data` object:

```js
myDeckLayer.setProps({data: data.concat(...)})
```

**Comment by John2397** [comment]
Thank you

**Comment by MariaZentsova** [comment]
Hi @John2397 I am also struggling with the same issue. The changes in data come from props in my case. Could you please kindly share how you got to work your example?

**Comment by John2397** [comment]
> Hi @John2397 I am also struggling with the same issue. The changes in data come from props in my case. Could you please kindly share how you got to work your example?

Sure.
```
var carData = [];
const scatterPlotLayer = new MapboxLayer({
    id: 'my-scatterplot',
    type: ScatterplotLayer,
    data: [],
    getPosition: d => d.position,
    getRadius: d => d.size,
    getColor: d => d.color
});

map.on('load', function ()
{
    var timer = setInterval({   //every 200 ms do
		var new_carData=
		{
			position: new_position, //e.g [30,30,10]
			size: 5,
			color: [23, 184, 190]
		};

	carData= carData.concat(new_carData); //Append the new object to the array
        scatterPlotLayer.setProps(  {data: carData}  );
	}, 200)
});


```
