### ISSUE TITLE
Textlayer binary attributes

### ISSUE THREAD

**Issue by Bowlx** [visgl/deck.gl#4836]
#### Description
I'm trying to suply data to TextLayer by using binary attributes (such as here https://deck.gl/docs/api-reference/layers/text-layer#use-binary-attributes) but indices seems to be have no effect on string length and layer rendering only 1 symbol per object

#### Repro Steps
codepen example: https://codepen.io/bowlx/pen/RwPGaGb

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.4
 - Browser Version:  Chrome 84.0.4147.105
 - OS: Windows 10

**Comment by Pessimistress** [comment]
Your binary `getPosition` value must be in the same layout as the `getText` value, i.e. for each character there must be one position.

If the first text string has 10 characters, you need to repeat the first anchor position 10 times.

**Comment by Bowlx** [comment]
welp, misread docs, thank you for the answer.
