### ISSUE TITLE
Provide MapView-style controls for non-ECEF 3D spatial data

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#4839]
#### Target Use case

I believe OrbitView is our only 3D non-WGS84 view. Often it's useful for a user to move about a space even if that space is not Earth-centered/Earth-fixed, e.g., the controls in [this three.js example](https://threejs.org/examples/misc_controls_map.html)–note how dragging left or right with the cursor or pressing left/right with the arrow keys does not produce a rotation. This [pydeck example](https://pydeck.gl/gallery/point_cloud_layer.html) and similar LIDAR point clouds would benefit from more `MapView`-style controls.

#### Proposed feature

Add MapView-style controls to the OrbitView.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
FYI you can always use MapView with `coordinatSystem: COORDINATE_SYSTEMS.METER_OFFSETS, coordinateOrigin: [0, 0, 0]`

**Comment by doudou003** [comment]
> FYI you can always use MapView with `coordinatSystem: COORDINATE_SYSTEMS.METER_OFFSETS, coordinateOrigin: [0, 0, 0]`

I can't understand. Do you have demo

**Comment by doudou003** [comment]
> > FYI you can always use MapView with `coordinatSystem: COORDINATE_SYSTEMS.METER_OFFSETS, coordinateOrigin: [0, 0, 0]`
> 
> I can't understand. Do you have demo

@doudou003

**Comment by Pessimistress** [comment]
@doudou003 Please stop spamming unrelated issues. If you need help, create your own thread in Discussions. Your comments will be deleted.
