### ISSUE TITLE
Custom layer shader compile problem

### ISSUE THREAD

**Issue by litar77** [visgl/deck.gl#4840]
I ‘v’ develop a custom layer,The following vertex shader was written：

void main(void) {
  geometry.worldPosition = instancePositions;
  geometry.pickingColor = instancePickingColors;
  uv = vec2(positions.x, positions.z);
  geometry.uv = uv;

  vec2 raySize=calcRaySize();
  vec3 offset_common = vec3(positions.x*raySize.x,positions.y*raySize.x, positions.y*raySize.y);
  DECKGL_FILTER_SIZE(offset_common, geometry);

  gl_Position = project_position_to_clipspace(instancePositions, instancePositions64Low, offset_common, geometry.position); 
  DECKGL_FILTER_GL_POSITION(gl_Position, geometry);
  
  vec4 color = positions.z<1.0?instanceOriginColor:instanceDestinationColor;
  vColor = vec4(color.rgb, color.a * opacity*calcFadingRatio());
  DECKGL_FILTER_COLOR(vColor, geometry);

  alive=instanceTriggerTime+diffusionTime*diffusionTimes+fadeTime-u_time>0.0?0.0:1.0;
}
`;

but，When I run the program, the browser reported the following error：
**_515:   gl_Position = project_position_to_clipspace(instancePositions, instancePositions64Low, offset_common, geometry.position); 
^^^ ERROR: 'assign' : cannot convert from 'const mediump float' to 'Position highp 4-component vector of float'_**

I read the source code of IconLayer in deck.gl and found that the shader is written in the same way as mine。
I really can't find where the error is now, please help me , it is greatly appreciated.

**Comment by Pessimistress** [comment]
[project_position_to_clipspace](https://deck.gl/docs/api-reference/core/project32) is part of the `project32` shader module. You need to include this module before using it: 

https://github.com/visgl/deck.gl/blob/f65ac9c067e2450ad4000c0124231200df11f39b/modules/layers/src/icon-layer/icon-layer.js#L72

**Comment by litar77** [comment]
The problem has been solved, thank you very much。
