### ISSUE TITLE
'race condition' when data from async iterable is loading too fast (RangeError: offset is out of bounds)

### ISSUE THREAD

**Issue by usefulthink** [visgl/deck.gl#4841]
#### Description

It seems there is kind of a race-condition problem when data from an async iterable is coming in too fast, resulting in an error `deck: error during update of TripsLayer({id: 'trips'}) RangeError: offset is out of bounds` when allocating memory.
The issue itself isn't really observeable in the debugger (because due to breakpoints the timing-problems apparently don't occur) but happens consistently in the application I'm working on.

I spent quite a while debugging this and here is what I found out:

 - The error is caused by `instanceCount` being `NaN` in `Tesselator._rebuildGeometry()`: https://github.com/visgl/deck.gl/blob/1aff4952f5a5229abcd18e50af977c25eabee76a/modules/core/src/utils/tesselator.js#L196

 - This in turn comes from `vertexStarts` not being fully initialized, due to `startRow` and `endRow` having wrong values: https://github.com/visgl/deck.gl/blob/1aff4952f5a5229abcd18e50af977c25eabee76a/modules/core/src/utils/tesselator.js#L170-L178
  In my application, that is `startRow = 325` and `endRow = 390`, but `vertexStarts.length === 255`. This then leads to `vertexStarts` getting filled with `NaN`. These numbers correspond to the ranges of records being yielded from my async generator in subsequent calls (the calls before the error yield records 178 to 255, 255 to 325 and 325 to 390) so it seems the second one of those is being ignored.

 - the reason for this seems to be in the handling of async iterables and the changeFlags in the `ComponentState` and `Layer` classes. The main loop in `ComponentState. _resolveAsyncIterable()` can run multiple times between two renders: https://github.com/visgl/deck.gl/blob/1aff4952f5a5229abcd18e50af977c25eabee76a/modules/core/src/lifecycle/component-state.js#L221-L232
  When that happens, the code in `Layer.diffProps()` will overwrite the dataChanged information from the first load with data from the second load leading to the observed behaviour.

##### possible solutions

I'm not entirely sure what the best way to solve this would be, for now I will just add some delays to the data-loading to make sure this doesn't happen (it might be a localhost-only thing anyway). 

I saw that at least the `PathTesselator` supports multiple ranges in `changeFlags.dataChanged`, so I think it might be a good approach to append to the `dataChanged` property instead of overwriting it in `Layer.setChangeFlags()` https://github.com/visgl/deck.gl/blob/1aff4952f5a5229abcd18e50af977c25eabee76a/modules/core/src/lib/layer.js#L740-L745
It looks like resetting of the change-flags after rendering has already been taken care of so this should be fairly easy to do and I would be happy to provide a PR for this. Then again, I don't yet have the full picture here, so please let me know if there are better ways to solve this.

#### Repro Steps

I hope the analysis above is enough to understand and discuss this issue, otherwise I will try to put together a minimal example to reproduce this (the code I'm working on is unfortunately neither minimal nor am I able to share it publicly).

#### Environment (please complete the following information):
 - Framework Version: deck.gl@8.2.4 (npm)
 - Browser Version: Chrome 83.0.4103.116 (Official Build) (64-bit)
 - OS: Mac OS X 10.13.6

**Comment by Pessimistress** [comment]
Thanks for reporting! A fix is landed in 8.2.6.
