### ISSUE TITLE
How can i update layer Attribute with buffer？

### ISSUE THREAD

**Issue by litar77** [visgl/deck.gl#4844]
I wrote a custom instanse layer to receive point data through web socket, I defined a buffer, as follows:
/* Singal buffer layout:
  | attribute    | size     |
  | ------------ | -------- |
  | positions.x  | 1 float  |
  | positions.y  | 1 float  |
  | positions.z  | 1 float  |
  | TriggerTime  | 1 float  |
  | OColor.R     | 1 byte   |
  | OColor.G     | 1 byte   |
  | OColor.B     | 1 byte   |
  | OColor.A     | 1 byte   |
  | DColor.R     | 1 byte   |
  | DColor.G     | 1 byte   |
  | DColor.B     | 1 byte   |
  | DColor.A     | 1 byte   |
  | ------------ | -------- |
  | total        | 24 bytes |
 */

I set props in the initializeState() of the custom layer to map the corresponding Attribute data in the buffer：

_if (signalBuffer) {
      const bufferData=new Float32Array(signalBuffer.buffer);
      const buffer = new Buffer(gl,bufferData);

      const bytesPerDatum=signalBuffer.bytesPerDatum;

      const positions = {buffer, type: GL.FLOAT, size: 3, offset: 0, stride: bytesPerDatum};
      const TriggerTimes = {buffer, type: GL.FLOAT, size: 1, offset: 12, stride: bytesPerDatum};
      const OColors = {buffer, type: GL.UNSIGNED_BYTE, size: 4, offset: 16, stride: bytesPerDatum};
      const DColors = {buffer, type: GL.UNSIGNED_BYTE, size: 4, offset: 20, stride: bytesPerDatum};

      const props={
        data: {
          length: signalBuffer.buffersize,
          attributes: {
            getPosition: positions,
            getTriggerTime: TriggerTimes,
            getOriginColor:OColors,
            getDestinationColor:DColors
          }
        },
      }
      Object.assign(this.props,props);
    }_
At the same time, I also deal with AttributeManager：
_const attributeManager = this.getAttributeManager();

    /* eslint-disable max-len */
    attributeManager.addInstanced({
      instancePositions: {
        size: 3,
        type: GL.DOUBLE,
        fp64: this.use64bitPositions(),
        transition: true,
        accessor: 'getPosition'
      },
      instanceTriggerTime: {
        size: 1,
        transition: true,
        type: GL.FLOAT,
        accessor: 'getTriggerTime',
        update: this.calcTriggerTime
      },          
      instanceOriginColor: {
        size: 4,
        transition: true,
        normalized: true,
        type: GL.UNSIGNED_BYTE,
        accessor: 'getOriginColor', 
        defaultValue: DEFAULT_ORIGIN_COLOR
      } ,
      instanceDestinationColor: {
        size: 4,
        transition: true,
        normalized: true,
        type: GL.UNSIGNED_BYTE,
        accessor: 'getDestinationColor', 
        defaultValue: DEFAULT_DESTINATION_COLOR
      }
    });_

However, the application can be started and run normally, but no objects are displayed in the layer。
I want to use "Supply attributes directly" to improve the performance of layer data update. Please help to see where the problem is? Where should I handle layer update Attribute?

**Comment by Pessimistress** [comment]
> I set props in the initializeState() of the custom layer to map the corresponding Attribute data in the buffer：

`layer.props` is a frozen object. You need to provide props from outside the layer.

If you want to wrap the handling of your custom buffer in a layer, you can create a [CompositeLayer](https://deck.gl/docs/developer-guide/custom-layers/composite-layers) that controls the props of its sub layers.

**Comment by litar77** [comment]
@Pessimistress 
Thank you very much for your reply.
I recently tried some other methods to update dynamic data. I tried to use updateTriggers, when the time variable is constantly modified to trigger the layer to update the data, the code is as follows:

_**this._ptLayer=new ScatterplotLayer({
          id: 'scatterpoints',
          data: DATA,
          getPosition: (object, {index,data,target}) => {
            const dtv=new DataView(data.src);
            target[0] = dtv.getFloat32(index * 24,true);
            target[1] = dtv.getFloat32(index * 24 + 4,true);
            target[2] = dtv.getFloat32(index * 24 + 8,true);
            // console.log(target);
            // target[0]=data.scr[index*8];
            // target[0]=data.scr[index*8]+4;
            return target;
          },
          getLineColor: (object, {index, data, target}) => {
            const dtv=new DataView(data.src);
            target[0] = dtv.getUint8(index * 24+16);
            target[1] = dtv.getUint8(index * 24+17);
            target[2] = dtv.getUint8(index * 24+18);
            target[3] = dtv.getUint8(index * 24+19);
            // console.log(target);
            return target;
          },
          getFillColor:  (object, {index, data, target}) => {
            const dtv=new DataView(data.src);
            target[0] = dtv.getUint8(index * 24+20);
            target[1] = dtv.getUint8(index * 24+21);
            target[2] = dtv.getUint8(index * 24+22);
            target[3] = dtv.getUint8(index * 24+23);
            return target;
            // console.log(target);
          },
          updateTriggers: {
            getPosition: [TriggleTime],
            getRadius:[TriggleTime],
          },
          pickable: true,
          autoHighlight: true,
          stroked: true,
          filled: true,
          getRadius: ()=>{
            return 10+TriggleTime%50},
          getLineWidth: 5
        });**_


However, I modify the TriggerTime variable regularly through the function in the main program,
   
 **_if(signalBuffer)
    {
      signalBuffer.push(sigporps);
      TriggleTime=Date.now();
      // console.log(sigporps);
    }_**

I have observed that TriggleTime has been changing, but I don’t know why, the geometric objects drawn in ScatterLayer have not changed.Please help to see if there is a problem with the writing of my updateTriggers

**Comment by Pessimistress** [comment]
#4826

**Comment by litar77** [comment]
> #4826

I found that UpdateTrigger needs to reorganize Layers in the drive variables to take effect，I call the following code after receiving the data:

 const {layers}=this._deck.props;
    const newLayers=[];
    for(const lyr of layers)
    {
      if(lyr.id!=='scatterpoints')
      {
          newLayers.push(lyr);
      }
    }
    newLayers.push(layer);
    this._deck.setProps({layers:newLayers});
