### ISSUE TITLE
Customizable MOVEMENT_SPEED and rotation amount when key pressing

### ISSUE THREAD

**Issue by liokm** [visgl/deck.gl#4849]
#### Target Use case
Hi, I want to customize the speed of panning and rotation when key left/right/... is pressed, when using `OrbitView`.
Currently, `MOVEMENT_SPEED` and rotation amount (15˚ for key left/right and 10˚ for key up/down) are hard-coded in `OrbitState` and seems a bit hard to be overrode.

#### Proposed feature
It would be great if these values could be customized in extended `Controller` such as `MyController`, or `OrbitState` could be exported (seems `_getUpdatedState` needs to be overrode as well in this case..).

Thanks!

**Comment by Pessimistress** [comment]
Consolidating with #5089
