### ISSUE TITLE
Slow performance on large screens

### ISSUE THREAD

**Issue by danielwhatmuff** [visgl/deck.gl#4854]
Interested to get some feedback on the observation below. We noticed a significant slow down in the performance of our app when using big screens and replicated using the deck.gl examples.

#### Description
Very slow performance on large screens.

#### Repro Steps
Use a big screen on the deck.gl examples (I tried https://deck.gl/examples/geojson-layer-polygons/) and am on an imac 27-inch late 2015 5K. Have also tried on a 27-inch LG ultrafine 5K display.
You will see a significant slowdown in rendering and zooming/moving around the map.

#### Environment
 - Framework Version: deck.gl 8.1.7
 - Browser Version: Version 84.0.4147.105 (Official Build) (64-bit)
 - OS: Mac OS X 10.15.5

#### Logs
No errors, just a high GPU/CPU burn and lots of lag.

**Comment by ibgreen** [comment]
The fragment shader is called for every pixel on that big screen, for a 5K screen it is >10 million invocations per frame.

Set `Deck.useDevicePixels: false` to reduce the rendered resolution.

**Comment by danielwhatmuff** [comment]
Amazing thanks for the quick reply. We will test this asap.

**Comment by reececasey** [comment]
@ibgreen do you know of anything similar when using the ReactMapGl component?

**Comment by ibgreen** [comment]
@reececasey Good question, they would obviously face the same problem but off the top of my head I don't know what mechanisms they offer to deal with. A quick google search lead me to this issue (with lots of cross links) maybe it can serve as a starting point for your investigation: https://github.com/mapbox/mapbox-gl-js/pull/6395 ?

**Comment by reececasey** [comment]
> @reececasey Good question, they would obviously face the same problem but off the top of my head I don't know what mechanisms they offer to deal with. A quick google search lead me to this issue (with lots of cross links) maybe it can serve as a starting point for your investigation: [mapbox/mapbox-gl-js#6395](https://github.com/mapbox/mapbox-gl-js/pull/6395) ?

Amazing thank you, if mapbox-gl has it as a config option sure we will find away to get it into the reactmapgl component 👍
