### ISSUE TITLE
I want to add a 'minimap' function... Please help me

### ISSUE THREAD

**Issue by Jenny-YJ** [visgl/deck.gl#4861]
I'm implementing a map app using deck.gl like this
[https://raw.github.com/visgl/deck.gl-data/master/images/docs/minimap.gif](url)

I'm going to add a minimap feature,
The z-index is lower than the Geojson layer, which is added below the Geojson layer.

![image](https://user-images.githubusercontent.com/69177905/90094976-5628ae80-dd6a-11ea-871d-ddb5e751f747.png)

The same phenomenon is true with functions such as 'NavigationControl'.

'Minimap' was added using 'View', and is there any way to apply style (ex. zIndex, border) to 'View' layer?

For your information...
In developer mode in the Chrome app, if I apply the style directly, it works well.
The Border effect of that picture is also something I added in the 'Chrome' app.

My source..
<DeckGL
    views ={[ new View({id : "minimap", x : 10, y: 10, width :'15%', height:'15%', controller:true, **style:{zIndex:1**}}) ] }
    layers={this._renderLayers()}
    pickingRadius={5}
    initialViewState={mapview}
    controller={true} 
    getTooltip= {this._renderTooltip}
    ContextProvider={MapContext.Provider}
    pickable = {true}
>
  <MapView id="main" controller={true}>
    <InteractiveMap 
    reuseMaps
    mapStyle={initmapinfo}
    preventStyleDiffing={true}
    pickable = {true}
    >
    <div style={{ position: "absolute", right: 0, top: 30, zIndex: 7 }}><NavigationControl /></div>
    <div style={{ position: "absolute", right: 0, top: 0, zIndex: 7 }}> <FullscreenControl /></div>
    <div style={{ position: "absolute", bottom: 30, left: 20, zIndex: 7}}><ScaleControl maxWidth={100} unit={"metric"}/></div>
    </InteractiveMap>
  </MapView>  
  
  <MapView id="minimap" controller={true}>
    <InteractiveMap
      mapStyle= 'http://10.1.1.17:8001/styles/klokantech-basic/style.json' //{initmapinfo}
      latitude = {mapview.latitude}
      longitude = {mapview.longitude}
      zoom = {mapview.zoom+1}
      style={{zIndex: 6}}
    />
  </MapView>
  
</DeckGL>

**Comment by Pessimistress** [comment]
[Views](https://deck.gl/docs/api-reference/core/view) do not have CSS styles.

Here is an [example](https://github.com/visgl/deck.gl/blob/master/test/apps/minimap/app.js).

**Comment by Jenny-YJ** [comment]
I am very grateful for the quick answer.

You mean CSS styles are not available?

1. Is there any way to add a style like boderline to the 'mini-map' view?

2. I'm going to use two Geojson layers and one Path layer simultaneously.
Is there only a layer addition order to control their z-index?


Thank you.

**Comment by Jenny-YJ** [comment]
> Views are not DOM elements, they are internal constructs that are drawn into the WebGL context.

 OK Thank you.

> Yes, you can add a `<div>` inside `<DeckGL>` and style it however you want.

Tried to wrap it up with a `<div>` .
But  it occurs an Uncaught Type Error when I added `<View>` or `<MapView>` in `<div>`.


> Layers are drawn in the order that they appear in the `layers` array.
OK thanks. then
In the case of  `<ScaleControl>`, 'zIndex' was applied using `<div>`, but it could not be put on GeoJsonLayer.
What did I do wrong?

```
<DeckGL 
    layers = {this._renderLayers()}
    views = {VIEWS}
    pickingRadius={5}
    initialViewState={viewState}
    controller={true}
    onViewStateChange={this._onViewStateChange}
    getTooltip= {this._renderTooltip}
    ContextProvider={MapContext.Provider}
    pickable = {true}
>
    <View id="main">
    <InteractiveMap
        key="map"
        reuseMaps
        mapStyle={initmapinfo}
        preventStyleDiffing={true}
        pickable = {true}
        >
      <div style={{ position: "absolute", bottom: 30, left: 20, zIndex: 99}}><ScaleControl maxWidth={100} unit={"metric"}/></div>
    </InteractiveMap>
    </View>
    <div style={{ position: "absolute", margin:10, right: 0, top: 30, zIndex: 1 }}><NavigationControl /></div>                
</DeckGL>
```

Thank you for you time.

**Comment by Pessimistress** [comment]
You can wrap a `<div>` inside a `<View>`, but not the other way around. See https://deck.gl/docs/api-reference/react/deckgl#jsx-views

The base map is always under the deck.gl canvas, so are its children. To use react-map-gl controls, see [ContextProvider](https://deck.gl/docs/api-reference/react/deckgl#contextprovider)

**Comment by Jenny-YJ** [comment]
Already tried to wrap a `<StaticMap>` up with a `<div>`, too.
Only `<GeojasonLayer>` is shown and the map is gone.

**Comment by Jenny-YJ** [comment]
:) Don't wrap a `<StaticMap>` up  but add an empty `<div>` that added style, separately with  `<StaticMap>` - it works..
I don't know if this is the right way.

If `<ScaleControl>` is in a `<deck>` , throw the error. because it must be wrapped in a `<InteractiveMap>` .
Even though when use `<ScaleControl>`  in a `<StaticMap>` instead of` '<InteractiveMap>` 
then it throw the error, too. 
 `<ScaleControl>` should be inside a `<InteractiveMap>`?

**Comment by Pessimistress** [comment]
https://github.com/visgl/react-map-gl/issues/1168
