### ISSUE TITLE
How to add new object by click.

### ISSUE THREAD

**Issue by zhanghaooo** [visgl/deck.gl#4863]
Hi，I want to develop a layer that can add new objects(maybe some points) by click, but I find that `onClick()` method of `Class Layer` can only pick the object which is already rendered. Could anyone help me? Thanks a lot.

**Comment by jfuehner** [comment]
@zhanghaooo maybe have a look at [nebula.gl](https://nebula.gl/). It is a companion library for editing.

**Comment by zhanghaooo** [comment]
Thanks, yeah, I have looked at `nebula.gl`, I may have to extend the `EditMode` if I want to develop a 
 layer with personalized behavior. But there is only a little document of it, and it may be hard for me to do this by just referring the build-in modes code of `nebula.gl`.
