### ISSUE TITLE
Layer's always in "Awaiting state"

### ISSUE THREAD

**Issue by namndtth** [visgl/deck.gl#4865]
Hi everyone,
I am using Line Layer and DeckGL React to draw a line between two points when I click on DeckGL.
But when rendering this Line Layer, it does not show up and the life cycle is always in "Awaiting State".
I checked the issues but cannot find out the answer.
Here is my code for this function.
```
createLineLayer(points: any) {
        var layers = this.state.layers;
        const layer = new LineLayer({
            id: `line-layer ${Math.floor(Date.now())}`,
            data: points,
            coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
            getColor: [255, 255, 255],
            getWidth: 10,
        })
        this.setState({layers});
    }
```
Thank you for any help.

**Comment by namndtth** [comment]
I'm using deck.gl version 8.2.5

**Comment by Pessimistress** [comment]
You are not using the `layer` variable.

**Comment by namndtth** [comment]
@Pessimistress i'm sorry for delete that line of code when i copy to here. But i used this variable like this:
```layers.push(layer);```

**Comment by Pessimistress** [comment]
DeckGL does not update unless the `layers` prop changes shallowly. You need to create a new array:

```js
this.setState({layers: [...layers, layer]});
```

**Comment by namndtth** [comment]
@Pessimistress Oh, It seem does not exist in documents, right ? I searched the whole document but cannot find it or I might miss it ?

**Comment by Pessimistress** [comment]
https://deck.gl/docs/developer-guide/using-layers#the-reactive-programming-paradigm

It works similarly to a React pure component. There is no direct way to observe changes in a plain JavaScript array and you should not expect rendering to change when by mutating it.

**Comment by namndtth** [comment]
Thanks for your valuable information.
