### ISSUE TITLE
How to draw cuboid on pointcloud layer Deckgl?

### ISSUE THREAD

**Issue by aubeena007** [visgl/deck.gl#4867]
![screenshot-localhost_8080-2020 08 15-14_22_31](https://user-images.githubusercontent.com/69108888/90309134-2d87ec80-df03-11ea-8a26-b3afd7219683.png)
i want to draw a cuboid on top of a pointcloud how to do that

**Comment by Pessimistress** [comment]
You can use the [SimpleMeshLayer](https://deck.gl/docs/api-reference/mesh-layers/simple-mesh-layer).

**Comment by aubeena007** [comment]
> You can use the [SimpleMeshLayer](https://deck.gl/docs/api-reference/mesh-layers/simple-mesh-layer).

is possible to drag and draw a SimpleMeshLayer

**Comment by Pessimistress** [comment]
Check out nebula.gl.
