### ISSUE TITLE
Line layer does not appear correctly once map style is changed dynamically

### ISSUE THREAD

**Issue by George2397** [visgl/deck.gl#4870]
I use the deck gl line layer on Mapbox gl js to show the trajectory of a drone in real time. The location is updated every 1 second.
Once I change the map's style dynamically (after, let's say 5 reps or seconds), the line layer stops being displayed correctly and becomes discontinuous. I tried with several Mapbox map styles.

The map's style is changed by using `map.setStyle('mapbox://styles/mapbox/' + 'light-v10');`
[Here is a fiddle that demonstrates the problem](https://jsfiddle.net/George2323/vs25fk83/5/) (wait 6-7 seconds)

The problem does not occur with the scatter plot layer.
Is this a bug or am I doing something wrong?

**Comment by Pessimistress** [comment]
`style.load` is triggered twice, once after the initial load and once after you change the map style. Your data is therefore being updated in two `setInterval` loops simultaneously.

BTW your fiddle is using deck.gl v6 which is no longer supported. I'd recommend updating to the latest.

**Comment by George2397** [comment]
Thank you. I've tried to clear the first interval before calling `map.setStyle(...);`. 

It works but the line of the trajectory starts again from the beginning once the style is changed. Is there a way to keep the line layer intact?

**Comment by Pessimistress** [comment]
Closing since this is not an issue related to deck.gl.
