### ISSUE TITLE
Ripple effect for selected point

### ISSUE THREAD

**Issue by UttamRahane** [visgl/deck.gl#4872]
Is there any way to add ripple effect for selected point in ScatterplotLayer/GeoJsonLayer/IconLayer? I'm trying to highlight selected object with some animation effects. like [https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated](url)

**Comment by UttamRahane** [comment]
![image](https://user-images.githubusercontent.com/21005702/90478697-2b17d380-e14b-11ea-87a9-254fab354cae.png)

**Comment by UttamRahane** [comment]
Perfect, Thank you so much @Pessimistress for the help.

**Comment by Nitikaa** [comment]
@UttamRahane  I wanted to add ripple effect on lineLayer,  the same thing I'm facing like its re-rendering all the layers (with large data). can you brief on iTime approach ?

**Comment by Nitikaa** [comment]
@Pessimistress I wanted to add ripple effect on lineLayer, the same thing I'm facing like its re-rendering all the layers (with large data). can you brief on iTime draw() approach ?
