### ISSUE TITLE
- + keyCode in controller.js is not working in Firefox

### ISSUE THREAD

**Issue by liokm** [visgl/deck.gl#4874]
#### Description
In [controller.js](https://github.com/visgl/deck.gl/blob/master/modules/core/src/controllers/controller.js#L431), the `event.keyCode` is used for matching `-` and `+` keys, this does not work in Firefox as the [`keyCode` is obsolete](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and has different value for these keys from those in Chrome.
Instead, `event.key` or `event.code` could be used.
control-panel.js and test-controller.js have used keyCode as well.
Plus, +/- on numpad might need to be supported as well?

#### Repro Steps
For example, https://deck.gl/examples/line-layer/ supports key-pressing zoom in/out in Chrome, but not in Firefox.

#### Environment (please complete the following information):
 - Framework Version: deck.gl@latest
 - Browser Version: Firefox 78.0.2
 - OS: Mac OS X 10.15

Thanks!

**Comment by Pessimistress** [comment]
Thanks for reporting! A fix is landed in 8.2.6.
