### ISSUE TITLE
Layer.updateState does not receive oldContext

### ISSUE THREAD

**Issue by cneumann** [visgl/deck.gl#4877]
#### Description
Documentation for [`Layer.updateState`](https://deck.gl/docs/api-reference/core/layer#updatestate) and also [`Layer.shouldUpdateState`](https://deck.gl/docs/api-reference/core/layer#shouldupdatestate) says that `oldContext` is passed as one of the properties of the argument object. However, the only properties present are `changeFlags`, `context`, `oldProps`, `props`.

Background: I'm implementing a custom `CompositeLayer` that uses an `IconLayer` and want to update the data based on zoom level (to avoid icon overlap when zoom out). Since that is fairly expensive I want to only do this when the zoom level has changed, therefore I wanted to compare `context.viewport.zoom` with `oldContext.viewport.zoom` to detect when an update is necessary. Therefore I would prefer that this is not addressed by adjusting the documentation, but the code ;)

#### Repro Steps
Create a custom `CompositeLayer` that attempts to access `oldContext` from the `updateState` lifecycle method.
```js
class CustomLayer extends CompositeLayer {
    updateState({context, oldContext}) {
        // the next line crashes because oldContext is undefined
        if (context.viewport.zoom !== oldContext.viewport.zoom) {
            // re-compute data for IconLayer
        }
    }
}
```

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.5
 - Browser Version: Chrome 84
 - OS: Windows 10

**Comment by Pessimistress** [comment]
`oldContext` is no longer available. You can save the information in layer state for later use.

**Comment by cneumann** [comment]
Thanks for the pointer to an alternative, I'm using the layer state and it works well. Since the removal was intentional I agree that it is "only" a documentation bug ;)
