### ISSUE TITLE
Modify heatmap to use inverse distance weighting

### ISSUE THREAD

**Issue by robinator8** [visgl/deck.gl#4878]
Hi I'm trying to use the heatmap as a method of doing spatial interpolation over a continuous data set (eg. weather). I'm looking for some direction into how I would go about changing the heatmap algorithm to use inverse distance weighting (or any other spatial interpolation function).

**Comment by Pessimistress** [comment]
It might not be worth it (complexity + inefficiency) to implement sophisticated interpolation in the shader. The GPU is best optimized to perform linear interpolation inside a triangle. The most flexible solution is to calculate interpolated values on the CPU, triangulate, and draw (see solution in https://github.com/visgl/deck.gl/issues/4827).

There are many techniques to refine a surface generated by Delaunay Triangulation, e.g. an uniform grid, [Ruppert's Algorithm](https://en.wikipedia.org/wiki/Ruppert%27s_algorithm), etc.
