### ISSUE TITLE
How to get data from TileLayer

### ISSUE THREAD

**Issue by supersonicclay** [visgl/deck.gl#4882]
Is there a clean way to get the data currently loaded into a TileLayer? I know it has an internal cache and a concept of `selected` tiles being tiles currently rendered. But I'm looking for a way to enumerate all the data it has for those selected tiles.

Thanks!

**Comment by kylebarron** [comment]
[`onViewportLoad`](https://deck.gl/docs/api-reference/geo-layers/tile-layer#onviewportload)

**Comment by supersonicclay** [comment]
Is there an equivalent event that's called when tiles are made invisible or purged from the cache?

**Comment by kylebarron** [comment]
No I don't believe so.

**Comment by supersonicclay** [comment]
Ok `onViewportLoad` gives me what I need for this use case. Thanks!

**Comment by supersonicclay** [comment]
Is there another callback for when the TileLayer starts requesting data again? Something like a `onViewportLoading` event.
