### ISSUE TITLE
Adding Stroke/Border to Deck.gl polyline features

### ISSUE THREAD

**Issue by ArslanAslam92** [visgl/deck.gl#4884]
I'm displaying roads in deck.gl as geojson polyline features. The road is made up of small 'segments'. Their width represents a specific traffic variable. The segments are small and i'd like to find a way to give a border/stroke to them so the end of one segment and start of another is prominent. I've checked the 'stroke: true' option. but that works for only polygon features in a geojson layer. The segments are identifiable in the first picture as widths vary but for instance in the second picture, presence of an outline for each segment would really help identify each segment. Any ideas how this can be done?

![image](https://user-images.githubusercontent.com/67629817/90956095-94695080-e483-11ea-814a-552dd5374566.png)

![image](https://user-images.githubusercontent.com/67629817/90956099-9f23e580-e483-11ea-843e-a20c6dfbff6d.png)

I've checked #4856 However it will give me borders at the sides, but not where one segment ends and the other one starts i.e the clone (border) layer would be underneath my feature layer. What I require is something like this

![image](https://user-images.githubusercontent.com/67629817/90956382-6b968a80-e486-11ea-85a3-ed9bd9976cf1.png)

**Comment by ArslanAslam92** [comment]
I am not sure what you meant by this @Pessimistress 
E.g. I have 951 segments. In one GeoJSON.

What you mean is draw one segment in orange (lets say) and the same one in black? And then the next 2 and so on.

**Comment by Pessimistress** [comment]
Say you have a path: `[[0, 0], [0, 1], [1, 1], [1, 2]]`

You'll need to break it into 3 paths: `[[0, 0], [0, 1]]`, `[[0, 1], [1, 1]]`, `[[1, 1], [1, 2]]` 

Then draw each one twice: `[[0, 0], [0, 1]]`, `[[0, 0], [0, 1]]`, `[[0, 1], [1, 1]]`, `[[0, 1], [1, 1]]`, `[[1, 1], [1, 2]]`, `[[1, 1], [1, 2]]` 

with `getLineColor: (d, {index}) => index % 2 === 0 ? BLACK : ORANGE`
and `getLineWidth: (d, {index}) => index % 2 === 0 ? 2: 1`
