### ISSUE TITLE
Question: how exactly does ScenegraphLayer support lighting?

### ISSUE THREAD

**Issue by brncsk** [visgl/deck.gl#4889]
I'm trying to add lighting to an untextured `glTF` model loaded into a `ScenegraphLayer` instance (simply in order to emphasise the structure of the model) but I'm admittedly a bit puzzled on how to approach this. So far I tried the following:

- Set `_lighting` to `'flat'` on the layer and added a number of lights using `LightingEffect` on the Deck instance. This resulted in the model being displayed unlit and flat.
- Set `_lighting` to `'pbr'`. This resulted in the model not being rendered at all.

My questions are the following:

- Is lighting (either 'flat' or 'pbr') something that requires setup on the model side (e.g. materials etc.)?
- Is it possible to get the flat lighting to work without this?

**Comment by ibgreen** [comment]
Some quick initial info:
- `pbr` looks for PBR materials, see https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materials, following the PBR metallicity-roughness model. 
- PBR materials are normally loaded by the GLTFLoader. It would certainly be possible to add such material definitions manually/programmatically but not sure if we have any examples of that).

**Comment by ibgreen** [comment]
Stating the obvious, you also want to verify that the lights are (relatively) close to your object to get effective shading.

**Comment by brncsk** [comment]
@ibgreen Thanks for the clarification – adding materials manually to the glTF file did solve the problem. The following repository is a good starting point for anyone looking to do this: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box/glTF/Box.gltf#L107
