### ISSUE TITLE
Point Cloud layer not displayed on mapbox gl js

### ISSUE THREAD

**Issue by John2397** [visgl/deck.gl#4890]
I used the [data ](https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/pointcloud.json )from  [this point cloud layer example](https://deck.gl/docs/api-reference/layers/point-cloud-layer) to create my own layer.

It seems to work on 6.4 version of deck gl but not on the latest one.

[Here is an example](https://playcode.io/658889/)  that works with the 6th version but not with the latest (uncomment the latest version to test)

PS: Why do the point data appear scattered all over the world? Is the points' location incorrect or am I doing something wrong?

**Comment by Pessimistress** [comment]
You are not specifying the coordinate system of your data, which defaults to `LNGLAT`.

Make sure you copy all props from the example that you are trying to follow.

**Comment by John2397** [comment]
Thank you

**Comment by mikahoy045** [comment]
> Thank you

I tried to follow your approach but can't get it work, since theres an error like `error: Uncaught ReferenceError: COORDINATE_SYSTEM is not defined`

How do you get it working?

**Comment by mikahoy045** [comment]
I get no error but no pointcloud showed. Is there something wrong? can I just use deck gl loader for LAZ file also?
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src="https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css" rel="stylesheet" />

        

    
   
   <script src="https://unpkg.com/deck.gl@latest/dist.min.js"></script>
   
  

    <style>
        body { margin: 0; padding: 0; }
        #map { position: absolute; top: 0; bottom: 0; width: 100%; }
    </style>
</head>
<body>
<style>
    #menu {
        position: absolute;
        background: #fff;
        padding: 10px;
        font-family: 'Open Sans', sans-serif;
    }
</style>

<div id="map"></div>
<script>
    const {MapboxLayer, PointCloudLayer, COORDINATE_SYSTEM} = deck;

    var pointCloudLayer = new MapboxLayer(
        {
            id: 'deckgl-PointCloudLayer',
            type: PointCloudLayer,            
            coordinateSystem: COORDINATE_SYSTEM.LNGLAT,                               
            data: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/pointcloud.json',            
            getPosition: d => d.position,            
            getColor: d => d.color,
            sizeUnits: 'meters',
            pointSize: 0.75,
            opacity: 1
        }
    );

    mapboxgl.accessToken = 'pk.eyJ1IjoiZ2VvcmdlMjMyMyIsImEiOiJja2MwZmxjbGYxajF4MnJsZ2pzbjhjdHc2In0.znh7LExrIEsKBB7SWYJ3hg';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        zoom: 1,
        maxPitch: 55,
        center: [4.899, 52.372]
    });

    map.on('load', function() {
        map.addLayer(pointCloudLayer)
    });
</script>

</body>
</html>`
