### ISSUE TITLE
Animating ScatterplotLayer Points

### ISSUE THREAD

**Issue by btbritz** [visgl/deck.gl#4892]
Hi,

I'm curious if it's possible to animate points already rendered on a  ScatterplotLayer from one x/y location to another x/y location smoothly?

Right now I am simply replacing my source data and everything just jumps to a different position on repaint.

Thanks

**Comment by Pessimistress** [comment]
[transitions](https://deck.gl/docs/api-reference/core/layer#transitions)

**Comment by btbritz** [comment]
Thanks for the link @Pessimistress !

Can I ask for an example if it's not too much trouble? Currently I have:

```
layers.push(new ScatterplotLayer({
    ...
    getPosition: node => {
        if (useAltData) { // For now I just have a button that toggles _useAltData_
            return [node.xAlt, node.yAlt]
        } else {
            return [node.x, node.y]
        }
     },
    ...
    transitions: {
        getPosition: {
             duration: 500
        }
    },
}))
```
Do I need an updateTrigger? Or maybe I'm missing something else entirely?

**Comment by btbritz** [comment]
Ah.

Solved by putting an updateTrigger on _useAltData_.
