### ISSUE TITLE
getCursor support for ArcGIS (2D/DeckLayer and 3D/DeckRenderer)

### ISSUE THREAD

**Issue by damix911** [visgl/deck.gl#4895]
#### Description
**I am still debating if this is a valid issue or we should pursue another way of obtaining the same result**.

When using ArcGIS maps, it should be possible to specify a cursor by doing (for 2D):

    const layer = new DeckLayer({
      "deck.getCursor": () => "ne-resize"
    });

Or, for 3D:

    const renderer = new DeckRenderer(sceneView, {
      "getCursor": () => "nw-resize"
    });

But, currently, these have no effect.

#### Repro Steps
[This pen](https://codepen.io/dawken/pen/QWNvxPy?editors=1010) unsuccessfully tries to override the cursor.

#### Environment (please complete the following information):
 - Framework Version: can repro with the latest `master` branch.

#### Logs
N/A.

**Comment by damix911** [comment]
A fix was installed with PR #4895.

**Comment by Pessimistress** [comment]
8.2.7
