### ISSUE TITLE
When I load 3DTiles,the model has rotated???

### ISSUE THREAD

**Issue by limzgiser** [visgl/deck.gl#4898]
![image](https://user-images.githubusercontent.com/27998168/91379667-c993eb00-e855-11ea-9380-66d606e1147d.png)

**Comment by ibgreen** [comment]
Hmm, I can only guess, this almost looks it could be a `gltfUpAxis` in the 3d tile that is not being respected. Or some transformation matrix in either the tile or the gltf model that is not being applied.

When you pan around, does it feel like the model center is on the ground? (half of it "below" / half of it "above")?

@belom88

**Comment by limzgiser** [comment]
@ibgreen Thank you for your answer. 
My data comes from osgb, and I use open source tools (https://github.com/fanvanzh/3dtiles) to convert to 3dtiles. The gltfUpAxis of the transferred data is "Z" by default, and it can be displayed normally when I load it with cesium.
But when I load with deckgl, the result is rotated like the picture above. I set gltfUpAxis of tileset.json to Y, which works in cesium, that is, the display result is rotated.
But I can't find a method to set gltfUpAxis in deckgl 3dtilelayer. How can I make deckgl load 3dtiles with gltfUpAxis="Z" correctly?

![3dtiles](https://user-images.githubusercontent.com/27998168/91518820-a0419080-e923-11ea-93e1-ad058af59874.gif)

**Comment by limzgiser** [comment]
![3dtiles](https://user-images.githubusercontent.com/27998168/91519328-d7fd0800-e924-11ea-9f99-77d13fc1f411.gif)

**Comment by ibgreen** [comment]
Looking into the `Tile3DLoader` in loaders.gl, as far as I can tell `gltfUpAxis` support is not implemented, i.e. it is always interpreted as `Y`.

I am actually a bit surprised we haven't had issues with this before. I opened an issue in loaders.gl. It will probably not be fixed immediately however I will try to get some attention on it in the next week or two.

**Comment by atlasdatatech** [comment]
@ibgreen thanks very much.

**Comment by limzgiser** [comment]
@ibgreen thanks very much.

**Comment by wcwcwcwc** [comment]
I have the same problem 
![企业微信截图_1599041316325](https://user-images.githubusercontent.com/44514114/91968607-720ae900-ed47-11ea-8637-2cfbbd6552a8.png)
How do I rotate this？

**Comment by sanyavanya** [comment]
@limzgiser @wcwcwcwc Can you provide us with specific models you're using so that we can start working on this issue?

**Comment by Pessimistress** [comment]
This should be fixed in loaders.gl 2.3.1
