### ISSUE TITLE
Right click event is not triggered

### ISSUE THREAD

**Issue by RobertFlorinDragut** [visgl/deck.gl#4902]
Description
When uploading a layer with deck.gl and rightclicking on a shape, the right click event does not get triggered. The following line is used for triggering the event:

`onClick: (info, event) => console.log(event.rightButton) //true`

Repro Steps

Add a deck.MVTLayer object, set pickable property to true and add the line above for triggering the right click event. Right click on a shape from the layer

 Environment:
 - Framework Version: can repro with the latest master branch.
 - Browser Version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
 - OS: Windows 10 64 bit

Logs
N/A

**Comment by Pessimistress** [comment]
I cannot reproduce this issue with https://github.com/visgl/deck.gl/tree/master/test/apps/mapbox-tile. Right clicks yield expected events.

You should check if other parts of your application is intercepting `pointerdown`/`pointerup` events.
