### ISSUE TITLE
Unmounting Tile Layer within React Modal Produces Assertion Error

### ISSUE THREAD

**Issue by RaymondDashWu** [visgl/deck.gl#4903]
### Description
![image](https://user-images.githubusercontent.com/33266041/91535286-c6d1de00-e8c7-11ea-9bb3-07efbc0ff3ad.png)
When using a tile layer within a react-modal the tiles will stop rendering after re-opening and closing. Seemingly the ids are still cached despite the component being unmounted

### Possible issues? My guesses
- [react-modal]([https://github.com/reactjs/react-modal](https://github.com/reactjs/react-modal)) uses React portals. Would this cause any issues?

### Things I've tried
- Conditionally rendering based on an isOpen in Redux store
- Attaching unmounting functionality to a Redux action in the parent component
- unmountComponentAtNode at various levels of the React app including parent of modal
- Same as above with removechild

### Link to code
[Where the modal component gets used](https://github.com/CodeLabs-Hubble-gl/kepler.gl/blob/hubbleExport/src/components/render-settings-modal.js#L110)
[Parent of modal component + Redux connections/actions](https://github.com/CodeLabs-Hubble-gl/kepler.gl/blob/hubbleExport/src/components/hubble-export.js#L59)

**Comment by Pessimistress** [comment]
This error is usually caused by reusing a layer that has been finalized. You should always construct a new layer instance during rerender.

**Comment by RaymondDashWu** [comment]
Thanks! That fixed it. I had been working on that on and off for a long time now!
