### ISSUE TITLE
GeoJson layer multicolor line

### ISSUE THREAD

**Issue by mfoglio** [visgl/deck.gl#4904]
I have a GeoJson layer composed of multiple lines. I'd like to color some of them with more than one color. 

I noticed that if I pass an array of color to the _getLineColor_ parameter, the line is colored with both color but the line disappear in certain point and it is not clear how the colors are changed. This is not documented so I don't know if it might work or not.

``` 
 new GeoJsonLayer({
    id: DIVVY_LAYER.RAIL_LINES,
    data,
    autoHighlight: true,
    pickable: true,
    getFillColor: (d) => [255, 255, 255], 
    getLineColor: (d) => [[255, 0, 0], [0, 255, 0], [0, 255, 0]],
    getRadius: 10,
    getLineWidth: 40
})
```

<img width="358" alt="Screen Shot 2020-08-28 at 11 46 25 AM" src="https://user-images.githubusercontent.com/19287629/91592390-1c3bd880-e924-11ea-8137-281efb27e877.png">

I had a look at the [PathStyleExtension](https://deck.gl/docs/api-reference/extensions/path-style-extension) to try to use a dashed line but there is not way to specify and offset with respect to the line start (just an often with respect to the width). I saw it has been proposed to implement a property getStrokeDashOffset [here](https://github.com/visgl/deck.gl/issues/398) but it doesn't look like it has already been implemented. 

Let me know how I can further help you

**Comment by Pessimistress** [comment]
When you return an array of colors with `getLineColor`, it should have one color for each segment of that path.

**Comment by mfoglio** [comment]
I know. But I'd like to draw a line using multiple colors. I was wondering why it appears to work with multiple colors and if it is possible to make it work to do what I'd like.

**Comment by Pessimistress** [comment]
Let me clarify:

Say your first geometry is a line string `[[0,0],[1,1],[2,2],[3,3]]`

If `getColor` returns `[255,0,0]`, then the path is drawn in red

If `getColor` returns `[[255,0,0],[0,255,0],[0,0,255]]`, then the path will be drawn in red, green and blue. The more vertices that your path contains, the more colors you need to provide. If you don't provide enough colors for the number of line segments, the rest will be filled with `[0,0,0,0]` which is invisible.

**Comment by mfoglio** [comment]
This is a lot of help. Now I understand. Thank you!

So there is no way to alternate between to color? I've seen the [PathStyleExtension](https://deck.gl/docs/api-reference/extensions/path-style-extension) which would be great (provided that I edit the geojson and create a line for each of the colors that I have) but it doesn't appear to have a way to set an offset to start drawing the line after some space. For instance:
- Consider two dashed overlapping lines: one blu line, one red line
- Let X represent a segment of the blu line
- Let Y represent a segment of the red line

With the PathStyleExtension I can draw two lines. If I could set an offset for one of the two lines (either the blu or the red) I could a have a result like this: `XYXYXYXYXY`

Instead, two overlapping lines of the kind `X X X X X` `Y Y Y Y Y` will be drawn, resulting in only one of the two being visible.

It appears PathStyleExtesion let you set an offset with respect to the width: getOffset

Could you confirm there is no way to do what I'd like to do? Or anything similar?

**Comment by Pessimistress** [comment]
`getOffset` offsets the path, not the dash array.

> Could you confirm there is no way to do what I'd like to do? 

Not with the built-in layer. You can extend the `PathLayer` yourself to add said functionality.
