### ISSUE TITLE
Interactivity problem with MVTLayer

### ISSUE THREAD

**Issue by Clebal** [visgl/deck.gl#4913]
#### Description
I've two layers created using MVTLayer. The first one (at the bottom of the layer stack) is a layer of polygons that MVTLayer creates using GeoJsonLayer. The second one (at the top, over the polygons features) is a layer of points created using ScatterplotLayer (the bug also happens with IconLayer) in renderSubLayers.

Both layers have interactivity but only the polygon layer interactivity is being listened although the points are over the polygons. The point layer interactivity isn't being executed, just in certain level of zooms, very randomly.

You can see in this [example](https://deck-gl-mvt-layer-interactivity.stackblitz.io/) (where the interactivity is a console.log with the layer id where the mouse is hover a feature) how in the browser console only appears layer1 (the polygon layer). Something a layer2 (the point layer) randomly appears but I couldn't identify why. I think that the interactivity isn't being working properly with MVTLayer.

Here is the Stackblitz [code](https://stackblitz.com/edit/deck-gl-mvt-layer-interactivity?file=index.js) where you can see the code and a commented icon layer where the issue also happens.

#### Repro Steps

1. Create a polygon layer.
2. Create a point layer which will be on the top of the polygon features.
3. Try to interact with the points.
4. See that deck.gl seems to understand that the polygon is over the point.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.7
 - Browser Version: Chrome 85.0
 - OS: macOS 10.14.6

**Comment by Pessimistress** [comment]
Your code link is dead.

**Comment by Clebal** [comment]
@Pessimistress fixed. Sorry!

**Comment by Pessimistress** [comment]
Thanks. This is caused by a bug in assigning z-index to tiled layers in the picking mode. I will put up a fix.

**Comment by Clebal** [comment]
@Pessimistress thank you so much!!! Is there a planned date to release the 8.2.8 or 8.3 with the fix?

**Comment by Pessimistress** [comment]
Published 8.2.8

**Comment by Clebal** [comment]
@Pessimistress thank you 👍  The fix is working perfectly.
