### ISSUE TITLE
Animating deck.gl's Scatterplot layer based on timestamps in javascript

### ISSUE THREAD

**Issue by ebaustria** [visgl/deck.gl#4916]
Hello everyone,

I am new to javascript and deck.gl, so I apologize in advance for any stupid questions or mistakes. Now onto my problem: I have been visualizing trips data with deck.gl, and I would now like to display the arrivals of trips at specific pairs of coordinates on the map when each trip arrives at a destination. Ultimately, for each arrival I want to render a filled circle whose radius expands for a second or two before disappearing. Each circle should have its center at the coordinates of the destination.

Does anyone have suggestions for how I might be able to do this (or for how I could just render circles at specific timestamps, with no animation)? Based on what I've gathered from the documentation, I thought subclassing the Scatterplots layer would be the easiest way. Does this sound like a good idea, or is there a better way to do it (e.g. by not creating a custom layer at all)? The JSON file I am using for the data has the following form:
```
[
  {"name": "B.PM.Pel_28", "coordinates": [-52.834517, -31.729593], "timestamp": 22799.89999994871, "color": [253, 128, 93]},
...
]
```
Thank you for reading my question. Any suggestions are welcome.

**Comment by juscc** [comment]
I think the Data filter extension sounds like it fits your needs :) 

https://deck.gl/examples/data-filter-extension/
https://deck.gl/docs/api-reference/extensions/data-filter-extension

**Comment by ebaustria** [comment]
Thanks for your response. I ended up finding a solution using update triggers and transitions, but I'll look into this when I have more time to work on improvements.
