### ISSUE TITLE
Tooltip under layers using pydeck.

### ISSUE THREAD

**Issue by hjoner** [visgl/deck.gl#4917]
Hello, 

I´m trying to use a tooltip with pydeck but it is under map layers!
What can i do to fix this issue? 

![tooltip_e](https://user-images.githubusercontent.com/44177765/92161162-9679ca80-ee06-11ea-96e7-2f47e5c57f1a.png)

Thanks

**Comment by ajduberstein** [comment]
@hjoner I haven't seen this before. Source code would help. Do you have some example code you can share?

**Comment by hjoner** [comment]
Hello @ajduberstein.

You can find a min code example here: [https://github.com/hjoner/Tooltip_test]

`import json
import pydeck as pdk
import pandas as pd
from urllib.request import urlopen

token = 'your_token'

path = ('PORTO_ALEGRE_GRID_CVLI_sem0_TURNO_0_tipo0.geojson')
with open(path) as response:
        grid = json.load(response)
lat = -30.0478
lng = -51.1706

view_state = pdk.ViewState(latitude= lat,
                           longitude= lng,
                           zoom=11,
                           pitch=0) 

layer_2d = pdk.Layer( 'GeoJsonLayer',
                            grid, id='geojson',
                            opacity = 0.5,
                            stroked = True, lineWidthScale = 5,
                            filled = True,
                            extruded = False,
                            wireframe= True,pickable=True,
                            get_elevation='properties.CRIMES * 200',
                            get_fill_color = 'properties.cor' , 
                            get_line_color=[255, 0, 0, 500],
                            tooltip=True,)

tooltip = {
   "html": "<b>Nro Ocor:</b> {Nro Ocor} <br/> <b>Data Fato:</b> {Data Fato}<br/><b>Dia da Semana:</b> {Dia da Semana} <br/> <b>Hora Fato:</b> {Hora Fato} <br/> <b>Orgao Carga:</b> {Orgao Carga} <br/> <b>Tipo Fato:</b> {Tipo Fato} <br/> <b>BAIRRO:</b> {BAIRRO} <br/> <b>Ano Registro:</b> {Ano Registro} <br/> <b>Flagrante:</b> {Flagrante} <br/> <b>Endereco:</b> {Endereco} <br/> <b>Nro Interno Ocorrencia:</b> {Nro Interno Ocorrencia} <br/> <b>Nro Endereco:</b> {Nro Endereco} ",
   "style": {
        "backgroundColor": "steelblue",
        "color": "white"
   }
}

mapa1 = pdk.Deck(mapbox_key = token,
initial_view_state=view_state, tooltip = tooltip,
layers=[layer_2d],
)   
mapa1.to_html('teste.html')`


That's not working how it should to me.

**Comment by hjoner** [comment]
Adding more information, this does not occur when using whit streamlit (`st.pydeck_chart(pdk.Deck())`).
Has you can see:
![tooltip_e2](https://user-images.githubusercontent.com/44177765/92493971-862d6b00-f1cb-11ea-90d6-ac14a3a4c3ee.png)

**Comment by ajduberstein** [comment]
Add a z-index to the tooltip and that should resolve your issue.

```python
tooltip = {
   "text": "Testing",
   "style": {
        "backgroundColor": "steelblue",
        "color": "white",
        "z-index": 2,
   }
}
```
