### ISSUE TITLE
ScenegraphLayer Conditional Models/Questions

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#4918]
Hi all!

I am looking into using the [ScenegraphLayer](https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer/). After reviewing the documentation I had a few questions that wasn’t completely clear...

- I see from the deck website [example](https://github.com/visgl/deck.gl/blob/master/examples/website/scenegraph/app.js) it is providing a static URL to the 3D model.

From the docs it states the `scenegraph` can be a (URL|Object|Promise). 

Would there be a way to display a different model based on a condition of a property/attribute passed as a part of the `data` object?

- I see the ScreengraphLayer inherits [Base Layer](https://deck.gl/docs/api-reference/core/layer). Safe to assume that I can pass binary attributes similar to [PathLayer](https://deck.gl/docs/api-reference/layers/path-layer), [TextLayer](https://deck.gl/docs/api-reference/layers/text-layer), etc?

- I notice the deck website [example](https://deck.gl/examples/scenegraph-layer/) runs a bit laggy on my machine. Wondering if there are any performance concerns I should be aware of?

**Comment by ibgreen** [comment]
> Would there be a way to display a different model based on a condition of a property/attribute passed as a part of the data object?

Yes, this should work. Though switching scenegraph can be somewhat expensive, so if frequently switching, a possible alternative is to have two `ScenegraphLayer` instances and control them via the `visible` prop.

> I notice the deck website example runs a bit laggy on my machine. Wondering if there are any performance concerns I should be aware of?

You are rendering a full scenegraph for each row in your table. If the scenegraph is really complex, and you activate PBR lighting, and your table has a lot of rows, you will eventually reach the performance limits of your GPU.

> I see the ScreengraphLayer inherits Base Layer. Safe to assume that I can pass binary attributes similar to PathLayer, TextLayer, etc?

Not 100% sure without checking, but I think so.

**Comment by jfuehner** [comment]
@ibgreen thanks for the quick reply! 

Would you have an example you could share where a conditional can be performed to switch the model based on a data attribute/property?

In terms of the GPU performance limits when PBR is activated. Safe to assume using the experimental `_lighting` attribute would help with GPU performance?

**Comment by ibgreen** [comment]
Just a conditional that returns different urls?


```js
const layer = new ScenegraphLayer({
    id: 'scenegraph-layer',
    data,
    scenegraph: alternateModel 
      ? 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb'
      ? 'alternate-scenegraph.glb'
  });
```

> In terms of the GPU performance limits when PBR is activated. 

Yes, generally PBR (Physically based rendering) is a more expensive lighting model, so expect better visuals but lower performance when enabling PBR.

**Comment by jfuehner** [comment]
@ibgreen hmm, I was more so hoping I could do something like...

```
const layer = new ScenegraphLayer({
    id: 'scenegraph-layer',
    data,
    scenegraph: d => d.type === ‘duck’ 
      ? 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb'
      ? 'alternate-scenegraph.glb'
  }); 
```

**Comment by ibgreen** [comment]
@jfuehner What comes to my mind when I see that code is that you want the layer to keep polling that callback (with some parameter `d`) and automatically change the model if `d.type` has changed?

That's not how deck.gl works. You need to rerender the layer to trigger a change.

**Comment by jfuehner** [comment]
@ibgreen Got it, sounds like I will need to group/categorize my data and create multiple [ScenegraphLayer](https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer)'s.
