### ISSUE TITLE
pydeck: Use index values of a geopandas.GeoDataFrame/pandas.DataFrame in a tooltip

### ISSUE THREAD

**Issue by yudai-nkt** [visgl/deck.gl#4921]
I want to use index values of a (Geo)DataFrame in a tooltip, but I can't as far as I tried. I tried to put index name in braces, but it appeared verbatim in the output.

Here is a reproducible example (credit to @ajduberstein in #4858):

```python
import pydeck as pdk
import geopandas as gpd

DATA_URL = 'https://raw.githubusercontent.com/MinnPost/simple-map-d3/master/example-data/world-population.geo.json'

world = gpd.read_file(DATA_URL)
world.index.name = 'id'
display(world.head())
layers = [
    pdk.Layer(
        "GeoJsonLayer",
        data=world,
        pickable=True,
        auto_highlight=True,
        get_fill_color=[255, 255, 140]),
]

pdk.Deck(
    layers,
    map_provider=None,
    tooltip={'text': '#{id}: {NAME}'},
).show()
```

<img width="1224" alt="スクリーンショット 2020-09-05 2 07 28" src="https://user-images.githubusercontent.com/13291527/92269134-86eda500-ef1e-11ea-8a5a-3ce14c368a00.png">

While index in the example above just consists of consecutive numbers and is not so informative, my actual use case has decent meanings in the index and I want to utilize it to describe the layer. I don't want to duplicate the index into a column though.

Is this possible? If not, I would like to request this feature.

**Comment by ajduberstein** [comment]
Thanks for filing the feature request, @yudai-nkt. This is both a simple and reasonable change. I'll see what I can do.

In the meantime, changing `data=world` to `data=world.reset_index()` in your layer should solve your problem. Let me know if that works.

**Comment by yudai-nkt** [comment]
I didn't come up with that idea. I reluctantly duplicated `world`'s index as a workaround, but `data=world.reset_index()` enables me to use index values without altering the content of the original DataFrame itself. Thanks!
