### ISSUE TITLE
Dragging objects on the screen is too slow

### ISSUE THREAD

**Issue by TheRomanOne** [visgl/deck.gl#4924]
I'm trying to implement a dragging mechanism in deck.gl. The idea is to be able to move around cuboids on the screen with the mouse, similarly to how it's done in Unity's editor (for example).
For simplicity, I want to be able to move them on their XY plane (with z=0)
I managed to come up with a set up that pretty much does that, but it's very slow

This is my code

    import  React from 'react';
    import DeckGL, {COORDINATE_SYSTEM, SimpleMeshLayer, OrbitView} from 'deck.gl';
    import {CubeGeometry} from '@luma.gl/engine'

    const INITIAL_VIEW_STATE =
    {
      target: [0, 0, 0],
      zoom: 2.5
    };

    let data = [
      {
        position: [-5, 0, 0],
        scale: [5, 10, 18],
        color: [205, 50, 210],
        angle: [0, -28, 34],
      },
      {
        position: [5, 0, 0],
        scale: [10, 12, 3],
        color: [255, 50, 120],
        angle: [-52, 0, 14],
      }
    ]

    class App extends React.PureComponent
    {
      constructor(props)
      {
    
        super(props);
    
        this.pos_change = true;
        this.state = 
        {
          data,
          isDragging: true,
          changed: true
        }
      }
      
      getMeshLayer = () =>
      {
        return [
          new SimpleMeshLayer(
            {
              coordinateSystem: COORDINATE_SYSTEM.IDENTITY,
              id: "simple_mesh_layer",
              data: this.state.data,
              pickable: true,
              getColor: d => d.color,
              getScale: d => d.scale,
              getPosition: [0, 0, 0],
              getOrientation: d => d.angle,
              getTranslation: d => d.position,
    
              mesh: new CubeGeometry(),
              onDragStart: () => this.setState({isDragging: false}),
              onDrag: (i, e) => this.movecube(i, e),
              onDragEnd: () => this.setState({isDragging: true}),
              updateTriggers:
              {
                getPosition: [this.state.changed]
              }
            }
          )
        ]
      }
    
      movecube = (info, event) =>
      {

        let axis = 0, sign = 1, mag = 3;
        
        if(event.additionalEvent === "panleft")
          sign = -1;
        else if(event.additionalEvent === "panup")
          axis = 2;
        else if(event.additionalEvent === "pandown")
        {
          axis = 2;
          sign = -1;
        }
      
        this.state.data[info.index].position[axis] += sign * mag;
        this.setState({changed: !this.state.changed})
        // info.object.position[0] += 10;
        // let s = [...this.state.data];
        // s[info.index].position[axis] += sign * mag;
        // this.setState({data: s})

        // return true;
      }

      render()
      {
            return(
          <div>
          <DeckGL
          controller={this.state.isDragging}
          initialViewState={INITIAL_VIEW_STATE}
          views={new OrbitView()}
          width={'100%'} 
          height={'100%'}
          layers={this.getMeshLayer()}
          parameters={{
            clearColor: [0.15, 0, 0.2, 1]
          }}
        />
           </div> 
        );
      }
    }

    export default App;

While this seems to work, it's response time is super slow.
What is thew better way to approach this problem?

**Comment by Pessimistress** [comment]
If you are rendering a lot of objects, you can try using the `_datadiff` prop: https://deck.gl/docs/api-reference/core/layer#_datadiff

**Comment by mogmog** [comment]
You are using React's state to keep track of the offsets - maybe try putting your layer in a composite layer and using Deck's  state system to keep track of the offsets

**Comment by mogmog** [comment]
Actually, i think the problem is because you are redefining your data array each time a mouse event is fired.

**Comment by TheRomanOne** [comment]
> Actually, i think the problem is because you are redefining your data array each time a mouse event is fired.

I figured as much, but I also tried to define the data outside and use 
`
    updateTriggers: {
          getPosition: [this.state.changed]
    }
`
and it didn't perform any better...

In `Nebula.gl` there's a layer called `EditableGeoJsonLayer` that has en edit mode in which you can move an object around.. does DeckGL has an equivilant?

**Comment by ibgreen** [comment]
> In Nebula.gl there's a layer called EditableGeoJsonLayer that has en edit mode in which you can move an object around.. does DeckGL has an equivilant?

nebula.gl was designed to be the "editable layer pack" for deck.gl, a companion framework, if that makes any sense.

I.e. if we wanted to add more editing features to deck.gl, we should first consider if they could be done in nebula.gl

**Comment by mogmog** [comment]
Ah, I didn't realise that. I need to perform something similar (but simpler) to the OP - i need to be able to drag around bit map layers. Should I be thinking about dragging a (hidden) geojson layer of the same bounds and keep the bitmapLayer updated in sync?

**Comment by ibgreen** [comment]
Yes, perhaps that is a way to reuse the editing modes already provided by nebula.gl.

I'd personally love to see nebula.gl grow beyond its geojson editing roots and add more general 3D and geospatial editing modes, but obviously that depends on contributors (as with all open source). 

It could be worth opening an issue in nebula.gl and get the thoughts of the maintainers and community there. As a starting point, perhaps a general layer dragging mode would seem to be a useful thing to have in nebula.gl?
