### ISSUE TITLE
Prevent panning maps outside of the canvas.

### ISSUE THREAD

**Issue by phyopwint1912** [visgl/deck.gl#4926]
Hello, 
First of all, it's not a bug, more like how to set the configuration to prevent panning maps outside of the canvas.
We are using deck.gl to generate the maps on react project. When moving around the maps, it can drag outside of the viewport and no clues where it has gone. Is there any way to prevent this behaviour. Thank you.

**Comment by Pessimistress** [comment]
Can you attach a video of what you are describing?

**Comment by phyopwint1912** [comment]
> Can you attach a video of what you are describing?

![video](https://user-images.githubusercontent.com/17942350/92635446-6e0f3600-f308-11ea-9417-5760ac096990.gif)

**Comment by Pessimistress** [comment]
So you want to apply constraints to the view state. You can do so by manipulating the `viewState` object with [onViewStateChange](https://deck.gl/docs/api-reference/core/deck#onviewstatechange):

```js
new Deck({
  initialViewState: {longitude: 0, latitude: 0, zoom: 10},
  controller: true,
  onViewStateChange: ({viewState}) => {
    if (viewState.longitidue > MAX_LON) viewState.longitude = MAX_LON;
    ...
    return;
  }
})
```

**Comment by phyopwint1912** [comment]
@Pessimistress Thanks fro the reply.

`onViewStateChange: ({viewState}) => {
    if (viewState.longitidue > MAX_LON) return;  // does that job but I dont know how to find Max Longitude of the viewport.
    ...
    return viewState;
  }`

**Comment by Pessimistress** [comment]
That depends on your data. If you are using GeoJSON you can look at turf.js' [bbox](http://turfjs.org/docs/#bbox).
