### ISSUE TITLE
Is there an easy way to combine the icon and path layers?

### ISSUE THREAD

**Issue by VSJAQ** [visgl/deck.gl#4928]
Hi! Thanks fore great app! I "merged" the rendering of the path and icon layers using the CompositeLayer, but I need a fairly large number of such elements, nevertheless, quite unique. This method leads to duplication of a large number of lines of code. Is there some way to draw the path under the icon or vice versa inside one component provided by default or using some extension?

**Comment by Pessimistress** [comment]
Can you provide a screenshot of what you are trying to achieve?

**Comment by VSJAQ** [comment]
yep, this one
![image](https://user-images.githubusercontent.com/51055013/92759293-03620700-f3a9-11ea-976e-93746e524a4a.png)
i achieve it, but it too much code only fore icon over the path
![image](https://user-images.githubusercontent.com/51055013/92759645-65227100-f3a9-11ea-9e1d-065b69ded37b.png)

**Comment by Pessimistress** [comment]
Currently there isn't a layer/extension that deals with this. What you are doing is what I would recommend.
