### ISSUE TITLE
LineLayer not shown when looking at it from above

### ISSUE THREAD

**Issue by mrlarssen** [visgl/deck.gl#4931]
I'm drawing a LineLayer using:

`new LineLayer({
      id: 'line',
      data: [
{"start":[3.6,60.8,0],"end":[3.6,60.8,-100]},
{"start":[3.6,60.8,-100],"end":[3.6,60.8,-200]},
{"start":[3.6,60.8,-200],"end":[3.6,60.8,-300]},
...],
      getSourcePosition: (d: any) => d.start,
      getTargetPosition: (d: any) => d.end,
      getColor: d => [255,255,255],
      getWidth: 8
    })`

And the line draws fine. But when I zoom very close, or I look at the line directly from above it disappears. The Z coordinates (altitude) I have are negative. But I'm not sure if that's related.

Version:
deck.gl 8.2.5

![linelayer](https://user-images.githubusercontent.com/5980467/92771807-7bc1cb80-f39b-11ea-98d2-891781ff8af9.gif)

**Comment by Pessimistress** [comment]
By default the far plane is positioned at the ground level. You can modify this behavior by supplying a [farZMultiplier](https://deck.gl/docs/api-reference/core/web-mercator-viewport) to the `viewState`/`initialViewState` (default is 1.01).

The data filter example contains negative altitude: https://github.com/visgl/deck.gl/blob/master/examples/website/data-filter/app.js#L19-L26

**Comment by mrlarssen** [comment]
Thank you, that works!
