### ISSUE TITLE
Interleave mapbox and deck.gl layers freely

### ISSUE THREAD

**Issue by gsahbi** [visgl/deck.gl#4938]
I need to obtain the following from top to bottom:

Layer5.  more deck layer
Layer4.  deck layer
Layer3.  mapbox road + label
Layer2.  deck layer
Layer1.  mapbox land + water + etc..

I followed the Kepler.gl way and was able to do layers 1 to 3 :

```js
<ReactMapGl > // bottom mapbox
    <DeckGL />   //deck layer 2
</ReactMapGl>  
<ReactMapGl />  // top mapbox layers
```

Any suggestions on how to add layers on top, I tried using deck.gl as a canvas for mapbox but it's not usable, maps are flickering and other components are not behaving correctly

**Comment by Pessimistress** [comment]
>  I tried using deck.gl as a canvas for mapbox but it's not usable, maps are flickering and other components are not behaving correctly

Please include your code if you want help with this
