### ISSUE TITLE
Rendering a 3d tube

### ISSUE THREAD

**Issue by incadenza** [visgl/deck.gl#4939]
Just getting acquainted with the library and exploring the API. I had a question I wasn't able to answer myself so far from reading the docs. Is there a recommended path for rendering something like a 3d tube? Using the existing `layers` parlance, it would be an elevated 3d `PathLayer`, rendered from a series of [x,y,z] coordinates. Think of a subway tube built above ground.

Any thoughts / ideas on approaching this problem?

Thanks in advance.

**Comment by Pessimistress** [comment]
You will need to create the tube geometry yourself and render with the SimpleMeshLayer.

If you just need pseudo-3D thinkness and your user won't look at it close up, you can try PathLayer with `billboard: true`.

**Comment by incadenza** [comment]
thanks, @Pessimistress - I figured as much but thought I'd ask.

**Comment by ibgreen** [comment]
> You will need to create the tube geometry yourself

Maybe you could use: https://luma.gl/docs/api-reference/engine/geometries#cylindergeometry
