### ISSUE TITLE
Ouline a icon

### ISSUE THREAD

**Issue by makeupsomething** [visgl/deck.gl#4940]
I have added some icons to a map with the IconLayer which is working for me. 
I want to apply a color to the icon and am doing this by using the `getColor` function with the `mask: true` parameter. But I would like the icon to have an outline/border that is a different color. Is there any way this is achievable currently?

**Comment by Pessimistress** [comment]
The IconLayer does not support `mask: true` and multiple colors. You can create two IconLayers, one for the icon and one for the outline.

**Comment by makeupsomething** [comment]
Thank you, this worked perfectly!
