### ISSUE TITLE
Add viv/avivator to deck.gl showcase page

### ISSUE THREAD

**Issue by kylebarron** [visgl/deck.gl#4941]
I was talking to @ajduberstein and we agreed that the [Viv project](https://github.com/hms-dbmi/viv) and the corresponding [avivator viewer](http://avivator.gehlenborglab.org/?image_url=https://viv-demo.storage.googleapis.com/Vanderbilt-Spraggins-Kidney-MxIF.ome.tif) show a really great non-geospatial use case of deck.gl in the biomedical realm. I think it would be a great project to add to the showcases page in the documentation.

cc @ilan-gold. If you're interested, do you have a thumbnail, couple sentences of descriptive text, and a preferred link?

**Comment by ilan-gold** [comment]
@kylebarron Let me gather some details and someone from our team (me or someone else) will reply.  Thanks for the interest!

**Comment by ngehlenborg** [comment]
@kylebarron @ajduberstein We'd be very happy to contribute something. Thanks for the invitation to contribute and supporting us along the way!

**Comment by ngehlenborg** [comment]
_Text:_
Viv is a library for multiscale visualization of high-resolution, highly multiplexed bioimaging data on the web. It directly renders data in Bio-Formats-compatible Zarr and OME-TIFF formats. Avivator is a lightweight image viewer that showcases the capabilities of Viv. The development of Viv and Avivator was supported with funding from the National Institutes of Health and Harvard University.

_Preferred link:_
https://github.com/hms-dbmi/viv

_Thumbnail Option 1:_
<img width="1024" alt="avivator-thumbnail" src="https://user-images.githubusercontent.com/1216518/94836373-ea190d00-03e0-11eb-8b5d-a5c30b12e035.png">

_Thumbnail Option 2:_
<img width="1024" alt="viv-thumbnail" src="https://user-images.githubusercontent.com/1216518/94836385-ed13fd80-03e0-11eb-82f8-46f58dff3e75.png">
