### ISSUE TITLE
DataFilterExtension with OR conditions

### ISSUE THREAD

**Issue by zogs** [visgl/deck.gl#4943]
Hello,

I'm having fun playing with deckgl latetly and i'm considering using it for coorporate projects.

I want to filter dynamically 12000+ polygons in a geojson that are categorized into 4 categories. 
It's working great when i want to filter one category, it's fast as light. 
```
getFilterValue: f => [f.properties.aocid], //1,2,3,4
filterRange: [1,1],
extensions: [new DataFilterExtension({filterSize: 1})],
```
or if i want to display 1 and 2 and 3.
but it seems there is no way to show ONLY 1 and 3... 
or am i wrong ?

Thank you for your time,

**Comment by Pessimistress** [comment]
The DataFilterExtension is designed to work with continuous values. Arbitrary categorical data can be more efficiently handled by sorting them into multiple layers, i.e.:

```js
const layers = Array.from({length: 4}, (_, i) =>
  new GeoJsonLayer({
    id: `geojson-${i}`,
    data: DATA.features.filter(f => f.properties.aocid === i + 1),
    visible: isVisible(i + 1),
    ...
  });
```

**Comment by Clebal** [comment]
@zogs what @Pessimistress said is a good solution. But if you cannot split the layer in multiples, you can achieve what you want updating the getFilterValue method:

Imagine `displayedAocid` is an array of numbers that save the aocid values that can be displayed.

```
getFilterValue: f => Number(displayedAocid.some(aocid => aocid === f.properties.aocid)
filterRange: [1,1],
extensions: [new DataFilterExtension({filterSize: 1})],
```

**Comment by zogs** [comment]
Thanks you both,
@Clebal clever solution, but it seems it is only working at initialization, not when re-rendering layers via .setProps({layers:layers}) 
My guess is that getFilterValue() is not reevaluated in this case ...

**Comment by zogs** [comment]
First solution by @Pessimistress is working but filtering throught 11k+ multiple times is be a bit slow

**Comment by Clebal** [comment]
@zogs you have to use updateTriggers to inform deck to reevaluate getFilterValue after `displayedAocid` changes.

**Comment by zogs** [comment]
oh yeah i forgot about that !! Thank you sir @Clebal , it's working great and still fast as light !!

i will continue my exploration of deckgl, so much things to try !

going to close this. thanks

**Comment by N-D-P** [comment]
> @zogs what @Pessimistress said is a good solution. But if you cannot split the layer in multiple, you can achieve what you want using the getFilterValue method in this way:
> 
> Imagine `displayedAocid` is an array of numbers that save the aocid values that can be displayed.
> 
> ```
> getFilterValue: f => Number(displayedAocid.some(aocid => aocid === f.properties.aocid)
> filterRange: [1,1],
> extensions: [new DataFilterExtension({filterSize: 1})],
> ```

Is there a way to implement filtering this way for filterSize more than 1 ??
In normal case of using DataFilterExtension, we pass range to filterRange,if we need more then 1 filter

**Comment by N-D-P** [comment]
> > The DataFilterExtension is designed to work with continuous values. Arbitrary categorical data can be more efficiently handled by sorting them into multiple layers, i.e.:
> > ```
> > const layers = Array.from({length: 4}, (_, i) =>
> >   new GeoJsonLayer({
> >     id: `geojson-${i}`,
> >     data: DATA.features.filter(f => f.properties.aocid === i + 1),
> >     visible: isVisible(i + 1),
> >     ...
> >   });
> > ```
> 
> I'm facing the same issue, but I'm using an MVTLayer, so I don't have access to the feature list. Is there a way to filter the data based on a property ? The DataFilterExtension is not working for me, because my property is of type string.

@abouroubi To work with string, I implemented as @Pessimistress suggested to tweak getFilterValue and its working fine for me.

The idea is if your filters exist then  ( return 1 when your filters values are matching with your property ) or else return 1

```
const filters = [ARRAY OF STRINGS]


getFilterValue: d => filters ?  
                                   filters.includes( d.properties.STRING_VALUE) ? 1 : 0 
                                   : 1
filterRange: [1,1],
extensions: [new DataFilterExtension({filterSize: 1})],
```

**Comment by abouroubi** [comment]
@N-D-P thanks a lot, it's working.
