### ISSUE TITLE
Discrepancies between how JSONConverter works in the playground vs. when using @deck.gl/react

### ISSUE THREAD

**Issue by brncsk** [visgl/deck.gl#4946]
#### Description / Repro steps:

Specifically, the `mapStyle` attribute of `MapView` does seem to work in the [playground](https://deck.gl/playground/) (snippet taken from the `website/3D heatmap (HexagonLayer)` example):

```json
    {
      "@@type": "MapView",
      "controller": true,
      "mapStyle": "mapbox://styles/mapbox/dark-v9"
    }
```

...but fails to do so when used in tandem with the react component:

```js
import React from 'react';
import DeckGL from "@deck.gl/react";
import { JSONConverter } from "@deck.gl/json";

const jsonConverter = new JSONConverter(...); // Actual configuration omitted for clarity

() => {
  const deckProps = jsonConverter.parse(...); // Again, omitted for clarity, but contains the `MapView` snippet from above
  return <DeckGl {...deckProps} />
};
```

Actual result: the mapbox basemap shows up in the playground but does not show up when the latter example is run.
Expected result: feature parity between the two.

Is this a supported use case? Also: is there a way to specify a mapbox-gl access token in the JSON config?

#### Environment:
 - Framework Version: deck.gl 8.2.5
 - Browser Version: Chrome 85.0
 - OS: macOS 10.16

**Comment by Pessimistress** [comment]
This is by design. The JSON use case does not have means to import external libraries otherwise, so a base map solution is included. When you use react/pure-js, we don't bundle a base map solution so that you can choose what to use.

See [Deck class documentation](https://deck.gl/docs/api-reference/core/deck) for common APIs.

[Example](https://github.com/visgl/deck.gl/examples/get-started/react/mapbox) of using Mapbox with the react component.

**Comment by ibgreen** [comment]
> is there a way to specify a mapbox-gl access token in the JSON config?

Agree in general that the docs could be a little better here.

In the playground, you can set the map token on the root props (or on the view).
- `props.mapboxApiAccessToken`
- `view.props.mapToken`

https://github.com/visgl/deck.gl/blob/master/examples/playground/src/deck-with-mapbox-maps.js#L17
