### ISSUE TITLE
Incoporating coordinate systems into pydeck

### ISSUE THREAD

**Issue by xhlulu** [visgl/deck.gl#4950]
With layers like `PointCloudLayer`, I've found that other coordinate systems like `METER_OFFSETS` are needed in order to render them onto a map. The [docs on coordinate systems for deck.gl](https://deck.gl/docs/developer-guide/coordinate-systems) shows how to use the `COORDINATE_SYSTEM` constants indicators when creating a layer. It would be nice to have them in `pydeck` as well, such that we could create a point cloud layer in this way:

```python
point_cloud_layer = pdk.Layer(
    "PointCloudLayer",
    data=point_clouds,
    ...,
    coordinate_system=pdk.COORDINATE_SYSTEM.METER_OFFSETS,
    
)
```

Let me know if there's any way I can help!

**Comment by ibgreen** [comment]
@ajduberstein may know what enums are exposed, but maybe in the mean time you can just use the actual numeric value: https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/constants.js#L35

**Comment by xhlulu** [comment]
Thanks! I'll bookmark this page.
