### ISSUE TITLE
RFC: Viewport features

### ISSUE THREAD

**Issue by padawannn** [visgl/deck.gl#4952]
#### Target Use case
Allow an easy way to get viewport features from MVTLayer

#### Proposed feature
Add an onViewportFeatures function callback in MVTLayer that returns the viewport features

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by padawannn** [comment]
And this is a bit more elaborated RFC

# RFC: Viewport features

# RFC: onViewportFeatures function callback in MVTLayer

- **Author**: Javier Aragón (CARTO)
- **Date**: September, 2020
- **Status**: **Draft**

References

- Filter features within map view: [https://docs.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/](https://docs.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/)
- Carto VL Viewport aggregations: [https://carto.com/developers/carto-vl/v0.10.0/guides/aggregations/#viewport-aggregations](https://carto.com/developers/carto-vl/v0.10.0/guides/aggregations/#viewport-aggregations)
- Arcgis: Query features from a FeatureLayerView: [https://developers.arcgis.com/javascript/latest/sample-code/featurelayerview-query/index.html](https://developers.arcgis.com/javascript/latest/sample-code/featurelayerview-query/index.html)

### Summary

This RFC proposes the creation of a new callback function in the MVTLayer that returns the features that are displayed on the map.

### Motivation

Sometimes you want to extract relevant information from the current view of the map (the viewport), to better understand *What am I seeing in the current map view?* Particularly in the MVTLayer where you don't know the data unless you make a call to the backend.

Currently, the MVTLayer has the onViewportLoad callback that returns all visible tiles features when all tiles in the current viewport are loaded, but this function is not enough to filter viewport features for the following reasons:

- You can drag or zoom the map and new tiles are not loaded so the onViewportLoad would not be called.
- Get viewport features outside the MVTLayer code is not trivial because you need to wait for the user interaction has finished (dragend, zoomend, etc) and be sure that all tiles have been loaded. Also, the code to filter the tiles is not easy.

The function that calculates the viewport features would be called inside the updateState function (like _updateTileset in tile-layer) but it would wait for user interaction has finished through a debounce function (similar to the one used in the heatmap-layer) and it would also wait to all tiles have been loaded.

In a branch in our fork we've developed this RFC and we have tested with tiles that have between 100K and 300K features and it works really fast [https @://github.com/CartoDB/deck.gl/blob/feature/ch102314/viewport-features/modules/geo-layers/src/mvt-layer/mvt-layer.js](https://github.com/CartoDB/deck.gl/blob/feature/ch102314/viewport-features/modules/geo-layers/src/mvt-layer/mvt-layer.js)

### Options

You can take our branch and test it with something like this:

```jsx
const layer = new MVTLayer({
	onViewportFeatures: f => { console.log(f.length); }
});
```

**Comment by Pessimistress** [comment]
I agree this is an important use case. Feedback is mainly around API design.

- Naming convention: the event callbacks are usually named `on<subject><verb>`. `onViewportFeatures` should be something like `onRenderedFeaturesChange` which describes the nature of the event better?
- Behavior: while the calculation is quite heavy, no other deck.gl API defer the triggering of an event. We try not to use hard-coded delays, which may not suit everybody's needs. Alternatively, we may tap into the existing callback `onViewportLoad` (called when all visible tiles are loaded) and add the ability to request the features:

```js
this.props.onViewportLoad(data, {
  getRenderedFeatures: this._getViewportFeatures.bind(this)
});
```

This moves the control of the debounce to the application side:

```js
new MVTLayer({
  onViewportLoad: (_, evt) => updateViewportFeaturesDebounced(evt.getRenderedFeatures)
})
```

**Comment by padawannn** [comment]
Thank you for the feedback @Pessimistress,

About tap into the existing callback onViewportLoad, with the current code this function is not called when you "make small movements" on the map that does not loads new tiles however the features that you're seeing on the screen would have changed. Maybe, we could call onViewportLoad callback when all visible tiles are loaded or if the viewport change and you are not loading new tiles.

What do you think about that?

**Comment by Pessimistress** [comment]
Ok maybe not making a breaking change to `onViewportLoad`. We can maybe create a new callback `onViewportChange`?
