### ISSUE TITLE
Load icons dynamically in iconLayer upon data change

### ISSUE THREAD

**Issue by nanda248** [visgl/deck.gl#4956]
I'm currently able to render iconLayer on the map with following data set called myData.
myData is a react state which has attributes like {id, name, icon} where icon is an svg icon.

const iconLayer = new IconLayer({
        id: 'icon-layer',
        data: **myData**,
        pickable: true,
        coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS,
        getIcon: d => ({
          url: d.icon,
          width: 64,
          height: 64
        }),
        ....
  });

I would like to change the icon of particular data set. Changing icon in myData state doesn't get reflected accordingly on map.
But, icon change can be reflected only if i create new IconLayer with new myData and use that iconLayer in the map. 

Is there anyway to reflect myData state change dynamically on the map without having to create IconLayer again?

**Comment by Pessimistress** [comment]
You are supposed to create a new layer instance to apply any change, see https://deck.gl/docs/developer-guide/using-layers#should-i-be-creating-new-layers-on-every-render

To update icons without creating new data, use [updateTriggers](https://deck.gl/docs/api-reference/core/layer#updatetriggers).
