### ISSUE TITLE
Responsive icon size on iconLayer and placement of colored border around icon

### ISSUE THREAD

**Issue by nanda248** [visgl/deck.gl#4957]
I have actually 2 questions related to iconLayer and I'm gonna ask in the same post.

## Responsive icon size upon zoom in/out
Currently I have some icons displayed using iconLayer on map and icon sizes remain the same during zoom in/out. IconLayer is defined as below.
```javascript
const iconLayer = new IconLayer({
        id: 'icon-layer',
        data: myDeviceData,
        pickable: true,
        coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS,
        getIcon: d => ({
          url: d.icon, // svg icon
          width: 64,
          height: 64
        }),
        sizeMinPixels: 80,
        sizeMaxPixels: 100,
        sizeScale: 0.5,
        getPosition: d => d.coordinates
      });
```
Now the icon sizes remains the same when user zoom in and out. 
- Is it possible to scale down the icon size together with the map during zoom out? 
Cos some icons are located very close to each other and they will be cramped and overlap each other when user zooms out.

## Colored border around user-selected icon in iconLayer
I have icons displayed on the map and I want to select some icons and selected icons should have blue colored border box around it. By the way, all my icons are square shaped. 
- How do you think I can achieve this icon selection? Should I have another layer for icon selection or is there anyway to modify css attributes of the icon?

**Comment by Pessimistress** [comment]
Scaling on zoom: see [sizeUnits](https://deck.gl/docs/api-reference/layers/icon-layer#sizeunits)

Border: you can either assign a colored icon to the selected one (see [mask: false](https://deck.gl/docs/api-reference/layers/icon-layer#iconmapping)) or create another icon layer to render the outline.
