### ISSUE TITLE
CATERSIAN coordinate

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#4962]
Hello all, I tried to use CARTESIAN coordinate, but I was not able to get it to work. I copied the ScatterplotLayer example, and change it to CARTESIAN as below:

```
var {
    ScatterplotLayer,
    Deck,
    COORDINATE_SYSTEM
} = deck;

const INITIAL_VIEW_STATE = {
    x: 10,
    y: 10,
    zoom: 15
};

const deckgl = new Deck({
    initialViewState: INITIAL_VIEW_STATE,
    controller: true,
    layers: [
        new ScatterplotLayer({
            coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
            data: [{
                position: [10, 10],
                color: [255, 0, 0],
                radius: 100
            }],
            getFillColor: d => d.color,
            getRadius: d => d.radius
        })
    ]
});
```

There was no error, but deck did not draw anything?

Thanks for any help!

**Comment by Pessimistress** [comment]
You are drawing cartesian coordinates into a `MapView` (the default). You need either an `OrthographicView` or an `OrbitView`. Read about projection systems [here](https://deck.gl/docs/developer-guide/views)

**Comment by txtl** [comment]
Great! I followed the doc, and I was able to get the example working.

Thank you very much!

**Comment by doudou003** [comment]
@Pessimistress use CATERSIAN coordinate，Whether there is 3D non geospatial support, the same as https://github.com/visgl/deck.gl/issues/4839

**Comment by doudou003** [comment]
> @Pessimistress使用 CATERSIAN 坐标，是否有 3D 非地理空间支持，同#4839

@doudou003
