### ISSUE TITLE
MVTLayer Point Styling?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#4963]
Had a question about the [MVTLayer](https://deck.gl/docs/api-reference/geo-layers/mvt-layer/)...

Would there be a recommended approach on adding labels and/or icons to an MVTLayer? I don’t believe the MVT spec provides a way to embed/encode such things within the tiles...

**Comment by Pessimistress** [comment]
You can override `renderSubLayers` with your own callback. See [use IconLayer instead of ScatterplotLayer to render the point features in a GeoJsonLayer](https://deck.gl/docs/api-reference/core/composite-layer#_sublayerprops)
