### ISSUE TITLE
Help finding a more efficient way to fade individual TextLayer icons in and out depending on timestamps

### ISSUE THREAD

**Issue by ebaustria** [visgl/deck.gl#4964]
Hello,

I have a data set that consists of coordinates, timestamps, and text that I am visualizing with a TextLayer. The structure of the JSON file is as follows:

```
[ {"coordinates": [-52.791532,-31.353468], "timestamp": 60.0, "notification": "message created"},
  {"coordinates": [-52.834517,-31.729593], "timestamp": 120.0, "notification": "message created"},
   ...
]
```

Eventually I would like the individual TextLayer icons to appear at their respective coordinates and then fade out after a couple seconds when the current time of the visualization reaches the respective timestamps of the objects.

I have managed to get the icons to appear and disappear according to their timestamps, and I have attempted to use transitions to have the icons fade in and out. My code for the layer is:

```
      new TextLayer({
        id: 'messages',
        data: messages,
        getPosition: d => d.coordinates,
        getText: d => d.notification,
        getSize: 16,
        getColor: d => [0, 0, 0, isVisible(d.timestamp, this.state.time, 50, 255)],
        backgroundColor: [255, 255, 255],
        getTextAnchor: 'middle',
        getAlignmentBaseline: 'top',
        getPixelOffset: [0, 3],
        updateTriggers: {
          getColor: [d => [0, 0, 0, isVisible(d.timestamp, this.state.time, 50, 255)]]
        },
        transitions: {
          getColor: {
            type: 'spring',
            stiffness: 0.01,
            damping: 0.15,
            duration: 200
          }
        }
     })
...
function isVisible(timestamp, current, tolerance, size) {
  if (timestamp >= current && timestamp <= (current + tolerance)) {
    return size;
  }
  return 0;
}
```

My problem is that this method is not efficient enough. It causes the rendering of the layer to be slow and sluggish. Is there a way to do what I'm trying to do that achieves a higher level of performance? Or does someone see an error in my code that I'm missing? Thank you.

**Comment by Pessimistress** [comment]
`DataFilterExtension`

[example](https://deck.gl/examples/data-filter-extension/) 

[documentation](https://deck.gl/docs/api-reference/extensions/data-filter-extension)
