### ISSUE TITLE
bin loader for deck gl 

### ISSUE THREAD

**Issue by aubeena007** [visgl/deck.gl#4968]
i have a bin file which contain a pointcloud is there is any bin loader available for deck gl or should i convert it into pcd or glb format

**Comment by ibgreen** [comment]
Bin files are often raw data if it contains just one attribute (positions, colors) just load into a typed array? 

If more than one attribute you need some metadata to know where to split the bin file... hard to say without more info

**Comment by Pessimistress** [comment]
PCD and GLB have specifications. Bin is not a defined file format. Bin stands for binary, and can contain anything. You need to consult the source of your file to know what's inside.
