### ISSUE TITLE
Multiple errors in Safari browsers for IconLayer and ScatterplotLayer

### ISSUE THREAD

**Issue by tlevin** [visgl/deck.gl#4969]
Writing this as a help request as it is most likely related to user error vs actual bug.

I am getting the same set of errors in both a ScatterplotLayer and an IconLayer:
![Screen Shot 2020-09-23 at 9 23 42 AM](https://user-images.githubusercontent.com/12662241/94040980-80648780-fd7e-11ea-9124-48843a144892.png)

Here is a snippet of my layer code:
```
export const statusLayer = ({ data, onClick, selectedCar }: statusLayerProps) => {
  return new ScatterplotLayer({
    id: 'statusCircle',
    data,
    onClick,
    pickable: true,
    stroked: true,
    radiusUnits: 'pixels',
    transitions: {
      getPosition: {
        duration: 2000,
      },
    },
    radiusScale: 1,
    opacity: 1,
    getRadius: d => {
      if (d.isVisible === false) {
        return 0;
      }
      return d.uuid === selectedCar ? 14 : 8;
    },
    getPosition: d => [d.longitude, d.latitude],
    getFillColor: d => {
      if (d.uuid === selectedCar) {
        return [255, 255, 255];
      }
      return selectedCar === null ? d.statusColor : [...d.statusColor, 120];
    },
    lineWidthUnits: 'pixels',
    getLineColor: d => (d.uuid === selectedCar ? d.statusColor : [0, 0, 0, 0]),
    getLineWidth: d => (d.uuid === selectedCar ? 3 : 0),
  });
};
```

My versions: 
@deckgl/layers: 8.2.2

I was able to go to the demo pages on safari without issues, but copying the code directly into my project caused the same errors.

Any help would be appreciated as I don't know how to debug further

**Comment by ibgreen** [comment]
Hmm, looks like the WebGL2 polyfills have not been installed?

@tsherif just in case anything comes to mind?

**Comment by kylebarron** [comment]
Are you including both `@deck.gl/layers` and `@deck.gl/core`? You need both.

**Comment by Pessimistress** [comment]
Can you try cloning one of the examples in `/examples/get-started`? This is likely related to your bundler config.

**Comment by tlevin** [comment]
Thanks for the quick responses.
I cloned the examples, they worked fine.
@deck.gl/core version: 8.1.7

Is there anything I have to do to enable webgl2 polyfills?  I am working out of a monorepo structure so have little ability to change the global webpack config

**Comment by tlevin** [comment]
I was able to get it to work by following the luma.gl polyfill readme found here: https://www.npmjs.com/package/@luma.gl/webgl2-polyfill/v/7.3.2

Now it is working fine.  I think my webpack was aggressively treeshaking any polyfills out.  Thanks for the help, it pointed me at the polyfills.

**Comment by Pessimistress** [comment]
@ibgreen I've seen webpack configs that assume `sideEffects: false` when it's not defined. The polyfill relies on this line:

https://github.com/visgl/luma.gl/blob/9384106f180a413b4652a0bd2df3d13ca451a0de/modules/gltools/src/polyfill/polyfill-context.js#L32-L33

**Comment by ibgreen** [comment]
Yes, that seems like a familiar pattern, we should move that into a function called from the functions that need it.

Either open a new bug on that, or reopen and retitle this one.

**Comment by Pessimistress** [comment]
https://github.com/visgl/luma.gl/issues/1404
