### ISSUE TITLE
extends Composite class using standalone package

### ISSUE THREAD

**Issue by TextTL** [visgl/deck.gl#4970]
Hello all,

I'm trying to create a Composite class using a standalone package (dist.min.js), I the HTML file, I have

```
<script src="./deckgl/dist.min.js"> 
<script type="module" src=./layers/NewLayer.js"> 
```

in NewLayer.js, I have
```
import * as deck from "../deckgl/dist.min.js";

var {
  DEFAULT_FONT_FAMILY,
  DEFAULT_FONT_WEIGHT,
  DEFAULT_CHAR_SET,
  DEFAULT_LINE_HEIGHT,
  CompositeLayer,
} = deck;
...
....
class NewLayer extends CompositeLayer {
```
DEFAULT_FONT_FAMILY, DEFAULT_FONT_WEIGHT, DEFAULT_CHAR_SET,DEFAULT_LINE_HEIGHT can be resolved, but not CompositeLayer. I had this error on the console:

```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at NewLayer.js:65
```
65 is the line "class NewLayer extends CompositeLayer {"

If I copy the NewClass to the html <body><script></script>, then there's no error. 

I'm not a javascript expert, any suggestion?

Thank you!

**Comment by TextTL** [comment]
When I change from 
```
import * as deck from ../deckgl/dist.min.js"; 
```
to 
```
import {
  DEFAULT_FONT_FAMILY,
  DEFAULT_FONT_WEIGHT,
  DEFAULT_CHAR_SET,
  DEFAULT_LINE_HEIGHT,
  CompositeLayer,
} from "./deckgl.dist.min.js";
```

I got this error: "Uncaught SyntaxError: The requested module '../deckgl/dist.min.js' does not provide an export named 'CompositeLayer'
"

**Comment by ibgreen** [comment]
Loading a bundled deck.gl script in HTML populates a global variable `deck`.

No import is needed. Just extend `deck.CompositeLayer` etc.

**Comment by TextTL** [comment]
> Loading a bundled deck.gl script in HTML populates a global variable `deck`.
> 
> No import is needed. Just extend `deck.CompositeLayer` etc.

That works as I stated above.  I just want to keep the html small and manageable by having new Composite layers in separate files

**Comment by Pessimistress** [comment]
You need to drop this line: `import * as deck from "../deckgl/dist.min.js";` if you are using inline scripts. `deck` is already a global object when you include the pre-built bundle.

`DEFAULT_FONT_*` are not exported by deck. If those are present in your `deck` object then most likely somewhere in your own code you are overwriting it.

**Comment by TextTL** [comment]
> You need to drop this line: `import * as deck from "../deckgl/dist.min.js";` if you are using inline scripts. `deck` is already a global object when you include the pre-built bundle.
> 
> `DEFAULT_FONT_*` are not exported by deck. If those are present in your `deck` object then most likely somewhere in your own code you are overwriting it.

Thanks for that. 
I don't have "import * as deck from "../deckgl/dist.min.js";"  when extending the Composite in the inline script.  I trying to delay deck resolution by using function NewLayer(deck) {...} in NewLayer.js. There was no error now. I'm trying to see if it works as I want 

Thanks.

**Comment by TextTL** [comment]
I closed this issue after following the suggestion from Pessimistress, and it works as intended. 

Thanks,
