### ISSUE TITLE
Help determining hexagon size/area/vertex-coordinates at different latitudes on a HexagonLayer

### ISSUE THREAD

**Issue by SterlingMcCall** [visgl/deck.gl#4971]
I am trying to determine the area of each hexagon when hovered used within the HexagonLayer.

I can approximate the area of a hexagon if I know the either the radius, apothem, side length, or hexagon vertices in WGS84 coordinates. The layer accepts a radius property, in meters, but the resulting hexagons overlayed on the map are equally sized despite their latitude, so their radii cannot technically be the same number of meters as the value passed into the 'radius' property on the layer.

For example, a hexagon over the equator will have a much larger surface area than a hexagon of the same visual size projected over Greenland.

I inspected the payload to the `onHover()` method provided to the HexagonLayer properties, but am unable to find any reference to the hexagon vertices or the radius adjusted to the latitude.

Is it possible to use the projection to derive the actual radius in meters given the original radius and the hexagon's latitude and longitude?

**Comment by Pessimistress** [comment]
You can access the underlying column layer like this:

```js
function onHover(info) {
  const hexagonLayer = info.layer;
  const [columnLayer] = info.layer.getSubLayers();
  const radius = columnLayer.props.radius;
  const center = columnLayer.props.data[info.index].position;
  // ...
}
```

**Comment by SterlingMcCall** [comment]
@Pessimistress I appreciate your help, but I'm still unsure on how I can use that information to derive the dimensions of the hexagon in longitude/latitude or in actual meters.

The radius property is always the same, while the actual radius of the hexagon in meters should be dependent on the actual placement on the earth. This will help me find the center of the hexagon, I need to be able to find the coordinates of at least one of the six vertices around the hexagon in order to determine the size.

I've tried putting various breakpoints in methods within the column layer, such as `tesselateColumn()` in column-geometry.js to try and understand what is happening under the hood. I am unfamiliar with the math and the comments in the source leave much to be desired. But, from what I understand, the points are not in world coordinates, and would need to be converted to lng/lat in order for me to use them how I need, but I'm at a bit of a loss on how to do that, especially from the information available to me on the info passed into the onHover() method.

Again, I appreciate any insight you are able to provide.

**Comment by Pessimistress** [comment]
> The radius property is always the same

Note I was accessing the `radius` prop of the sub layer, not the hexagon layer. The sub layer's radius is calculated based on the viewport.

The `ColumnLayer` just creates a regular unit hexagon. So the area you're looking for is

![area](https://latex.codecogs.com/svg.latex?\Large&space;S=\frac{3\sqrt{3}}{2}\cdot{R^2})

**Comment by SterlingMcCall** [comment]
@Pessimistress I was half correct when I stated that the radius prop does not seem to change. It does change when the viewport itself is updated, but within the same viewport, there can be multiple hexagons at different latitudes, all of which will report the same radius. Is the reported radius based off the center of the viewport? Or is it possible to query the viewport for the radius at a given latitude?

Here is a codepen demonstrating this behavior, logging the radius value to the console on hover: https://codepen.io/sterlingmccall/pen/bGpJvgW

If you hover over any hexagon without changing the viewport, the radius value will appear to be the same for all hexes. If you change the viewport, the radius will change, but will still be equal for all hexagons. However, the hexagons closer to the equator should be "larger" than those at higher or lower latitudes.

**Comment by Pessimistress** [comment]
Under the hood, hexagons are generated in the common space ("Web Mercator units"). You can find out this radius as follows:

```js
  const hexagonLayer = info.layer;
  const [columnLayer] = info.layer.getSubLayers();
  const radius = columnLayer.props.radius;
  const center = columnLayer.props.data[info.index].position;
  const {viewport} = info.layer.context;

  // The "common" radius (this is a constant)
  const radiusCommon = radius * viewport.getDistanceScales().unitsPerMeter[0];

  // The meter radius at any arbitrary position
  const radiusAtCenter = radiusCommon / viewport.getDistanceScales(center).unitsPerMeter[0];

  // Calculate area
```

**Comment by SterlingMcCall** [comment]
@Pessimistress Thank you very much for the explanation!
