### ISSUE TITLE
Transition is not smooth with 8.2.8

### ISSUE THREAD

**Issue by TextTL** [visgl/deck.gl#4974]
#### Description
I've got a deck script that moves icons when their positions are updated. Icons move smoothly when using 8.0.0. When I tried with 8.2.8, the icons did not move smoothly. 

#### Repro Steps
```
        const rayLayer = new IconLayer({
          id: "ray-layer",
          data: data,
          iconMapping: "data/location-icon-mapping.json",
          iconAtlas: "data/location-icon-atlas.png",
          sizeUnits: "meters",
          getPosition: (d) => d.position,
          getIcon: (d) => d.symbolid,
          getSize: (d) => d.size,
          updateTriggers: {
            getPosition: updated,
          },
          transitions: {
            getPosition: 200,
          },
        });
```
#### Environment (please complete the following information):
Framework: Deck GL 8.2.8
Browser: Edge Version 85.0.564.63
OS: Windows 10

**Comment by Pessimistress** [comment]
I cannot reproduce this with the code you provided. Please create a Codepen/JSFiddle that demonstrates the issue you're describing.

**Comment by TextTL** [comment]
It's odd that the exact same codes run smoothly on codepend.

https://codepen.io/txtl-smith/pen/rNebBKJ

The only difference is dist.min.js. codepend does not accept 'https://unpkg.com/deck.gl@^8.2.8/dist.min.js', then I have to use 'https://unpkg.com/deck.gl@latest/dist.min.js' with the assumption that https://unpkg.com/deck.gl@latest/dist.min.js is the same as https://unpkg.com/deck.gl@^8.2.8/dist.min.js

**Comment by TextTL** [comment]
I think it's my GPU problem. The problem occurs when the  GPU is 99% when running these codes. It runs smoothly when the GPU is only 9-10%. I'll try to understand more if it's the graphic card driver or something else that causes the spike in GPU.

**Comment by txtl** [comment]
It turned out to be the issue with the latest driver from Nvidia for GT 1030. I closed the issue.
