### ISSUE TITLE
What can I do to make text center without padding offset? 

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#4975]
I tried the NodeLayer mentioning in the document: "A NodeLayer that renders a text string inside a circle at each anchor position, by combining the ScatterplotLayer and the TextLayer.". I couldn't make the text center inside the circle without making manual adjustment of the y-position. What did I do wrong?  I have codepen here: https://codepen.io/txtl-smith/pen/oNxOgqG?editors=0010

Thanks,

**Comment by Pessimistress** [comment]
[getPixelOffset](https://deck.gl/docs/api-reference/layers/text-layer#getpixeloffset)

**Comment by txtl** [comment]
> [getPixelOffset](https://deck.gl/docs/api-reference/layers/text-layer#getpixeloffset)


Just tried that method, but zooming does not give a good result. Text and circle are not in sync when zooming out/zooming in. 

https://codepen.io/txtl-smith/pen/oNxOgqG

Thanks,

**Comment by txtl** [comment]
I think I found the cause; when I disabled sdf as below, the text is centered as expected. This makes the text blurry when zooming in. 

        fontSettings: {
          // sdf: true,
          fontSize: 64,
          buffer: 2,
          radius: 2,
        },

Thank you,

I'm closing the ticket.
