### ISSUE TITLE
Setting Map Panning Boundaries for Deck.gl

### ISSUE THREAD

**Issue by meguna** [visgl/deck.gl#4976]
I'm currently using the React implementation of Deck.gl and was wondering if there was any way I could set panning boundaries with something like longitudes and latitudes in such a way that users cannot pan outside of that boundary. I am able to do this with Mapbox Gl elements such as StaticMap (using mapbox options) but right now this effect isn't being applied to my deck gl layers, so their positions goes out of sync when I hit the boundary. I would like a way to set the same boundaries to the deck gl layers.

I can attach some code snippets if it would be helpful.

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/issues/4234
