### ISSUE TITLE
How to identify which layer is picked on an mouse event. 

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#4982]
I implemented a composite layer 
```
class NewLayer extends CompositeLayer {
       renderLayers() {
              return [
                          new TextLayer ({....}),
                          new ScatterPlotLayer({....}),
                          new ScatterPlotLayer({.....})
                          ]
      }         
}
```
I enabled pickable and caught onClick event with
````
new NewLayer ({... 
                   pickable: true,
                   onClick:  info => console.log (info);
}
````
I looked at the object from console.log, and  I couldn't distinguish which layer under NewLayer was clicked. 

Is there a way to know which layer is the target of the mouse click? The info returned from onClick is identical except the x,y of the mouse pointer.

Thanks,

**Comment by txtl** [comment]
Is it a right way to identify the layer by adding target to the info like this? 

```
  getPickingInfo({
    info,
    sourceLayer
  }) {
    console.log("NodeLayer: getPickingInfo");
    info['target'] = this.id;
    return info;
  }
```

**Comment by Pessimistress** [comment]
`event.sourceLayer`

**Comment by txtl** [comment]
> `event.sourceLayer`

I tried 
```
onClick: (info, event) => console.log (event.sourceLayer)
```
I got "undefined". I console.log (event), and I did not see the property: sourceLayer anywhere in the event object.

**Comment by Pessimistress** [comment]
You can populate it like this:

https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/tile-layer/tile-layer.js#L176

**Comment by txtl** [comment]
Got it!

Thanks,
