### ISSUE TITLE
PointCloudLayer does not render correctly when using meter_offsets.

### ISSUE THREAD

**Issue by namndtth** [visgl/deck.gl#4983]
Hi everyone.

I'm using a point cloud layer. I set its coordinate system to METER_OFFSETS and its coordinate origin to a originPoint[x, y]. I assigned this originPoint to target in viewSet with target[2] = 0 and set zooming level to 14. As a result, I see small point cloud in the middle of screen as in the attached image. I try to zoom out but this point cloud will disappear when reaching a certain level of zooming. 

Thanks for any help.
![pointcloud](https://user-images.githubusercontent.com/42760423/94770248-55151480-03de-11eb-9127-d87290948f8f.png)

**Comment by Pessimistress** [comment]
Please include your code, ideally with a codepen. We cannot help you debug from a screenshot.

**Comment by namndtth** [comment]
@Pessimistress Thank you for your reply!
My problem was resolved by using MapView instead of OrthographicView.
