### ISSUE TITLE
ArcGIS DeckLayer does not work with the latest esri-loader

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#4985]
`@deck.gl/arcgis` works with `esri-loader@<=2.14.x` but not `esri-loader@2.15.0`.

#### Repro Steps

- Go to https://github.com/visgl/deck.gl/tree/master/examples/get-started/pure-js/arcgis
- Install dependencies and run - deck layers do not render on app start
- Add `"resolutions: {"esri-loader": "2.14.0"}` to package.json
- Install dependencies and run - deck layers render as expected

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.8

#### Logs

Looks like `accessor.properties` is `undefined` with the latest ArcGIS release:

https://github.com/visgl/deck.gl/blob/b6f8a21f95ec7695fd7825a67396d9328e0dbfe6/modules/arcgis/src/deck-props.js#L49

**Comment by damix911** [comment]
Thank you. I had just start heaving problems with this and I was blaming it on NPM caching/stale packages but then it started becoming clear that there is a version program. I'll find out.

**Comment by Pessimistress** [comment]
Update: I checked in a temporary workaround:

`loadArcGISModules([...], {version: '4.15'})`
