### ISSUE TITLE
IconLayer and svg loading

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#4986]
#### Description
IconLayer was not able to load svg when using url:  "data:image/svg+xml;charset=utf-8, <svg>....</svg>"; while loading from server url is ok. 

#### Repro Steps

I've an svg as below:
```
<svg width="74" height="24" viewBox="0 0 74 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M53.7153 1.5L75.5 11.745L53.7006 22.4427L1.5 22.4428V1.50014L53.7153 1.5ZM53.5837 22.5C53.584 22.4998 53.5845 22.4996 53.5848 22.4995L53.5837 22.5Z" fill="#1D1E25" stroke="#2BFA09" stroke-width="2"/>
</svg>
```
and the code:
```
const SVG_BITS = `\
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">\
  <path d="M53.7153 1.5L75.5 11.745L53.7006 22.4427L1.5 22.4428V1.50014L53.7153 1.5ZM53.5837 22.5C53.584 22.4998 53.5845 22.4996 53.5848 22.4995L53.5837 22.5Z" fill="#1D1E25" stroke="#2BFA09" stroke-width="2" />\
</svg>`;

    const SVG_DATA_URL = `data:image/svg+xml;charset=utf-8,${SVG_BITS}`;
.....
....
        getIcon: (d) => ({
          id: "icon-1",
          url: SVG_DATA_URL,
          width: 74,
          height: 21
        }),
```

I followed the example from https://github.com/visgl/loaders.gl/blob/master/modules/images/test/lib/test-cases.js , to test my svg, and I got "DOMException: The source image cannot be decoded."  

When I took out "fill="#1D1E25" stroke="#2BFA09" stroke-width="2"" from the d path, Deckgl displayed the image without stroke and fill. 

Here's the codepen to demonstrate the issue: https://codepen.io/txtl-smith/pen/rNebBKJ

#### Environment :
 - deck.gl 8.2.8
 - Browser: Microsoft Edge Version 85.0.564.63  
 - OS: Windows 10 pro. 

#### Logs

DOMException: The source image cannot be decoded

**Comment by Pessimistress** [comment]
deck.gl is not decoding any image. It uses your browser's built-in capability. If your image cannot be displayed, you need to check if it's a valid format supported by the browser.

In your case, your data URL is not properly escaped. `data:image/svg+xml;charset=utf-8,${encodeURIComponent(SVG_BITS)}`

**Comment by txtl** [comment]
Great! It works after having this: "${encodeURIComponent(SVG_BITS)". I did not see $encodeURIComponent(...) in the example. 

Thank you so much!
