### ISSUE TITLE
Circle Around Cursor

### ISSUE THREAD

**Issue by NickAkhmetov** [visgl/deck.gl#4991]
Hello all,

I'm trying to add a circular indicator around the cursor (similar to e.g. a circular brush in Photoshop.) I can see in the [last update's documentation](https://deck.gl/docs/whats-new#world-repeating-in-web-mercator-maps) that this appears to be possible:

![image](https://user-images.githubusercontent.com/2059298/71849768-b397a700-3087-11ea-8c48-93d8bb9188db.gif)

I couldn't find any resources regarding how to add the indicator pictured there; could I be pointed to this information? Though it doesn't perfectly match the behavior I would like (I would like its size and presence to be toggled by react variables rather than being static/appearing only on click), it would provide me with a useful reference to follow if those attributes aren't programmable by default.

Thank you in advance!

**Comment by kylebarron** [comment]
I'm guessing that pointer circle was automatically added by Mac's screen recording tool; the circle only exists when clicking.

**Comment by NickAkhmetov** [comment]
Ah, I wasn't aware of that.

With that in mind, is there a way to add something along these lines as a layer?

**Comment by Pessimistress** [comment]
Since it's just one circle you'll likely get similar performance just drawing a div around the cursor and style it with CSS. It will give you more styling flexibility.

**Comment by NickAkhmetov** [comment]
That makes sense. Thanks for the follow up!
