### ISSUE TITLE
 Error: No valid loader found data: "" for http://xxxx.xxxx.xxxx/javascript/models/stack.glb

### ISSUE THREAD

**Issue by theseusyang** [visgl/deck.gl#4993]
I have an Error ,  Error: No valid loader found data: "" for http://xxxx.xxxx.xxxx/javascript/models/stack.glb
when adding ScenegraphLayer on mapbox using deck.gl.

the codes are blow:

```
const sceneLayer = new deck.MapboxLayer(
            {
              id: 'scenelayerId',
              type: deck.ScenegraphLayer,
              data: [ {position: [118,39], size: 100} ],

              scenegraph: 'http://xxxx.xxxx.xxxx.xxxx/javascript/models/stack.glb',
            //   data:[],
              getPosition: d => d.coordinates,
              sizeScale:10,
              getOrientation: [0, 0, 0],
              getTranslation: [0, 0, 0],
              getScale: [1, 1, 1],
              pickable: true,
              _lighting: 'pbr',
      
              onClick: ($event) => {
                alert('Hello! I am a duck and I am guarding my work!!');
              },
            });
```

I have no found any solution about this problem, and have no idea why this bug happens, please help!

**Comment by kylebarron** [comment]
You likely need to register the GLB loader: https://loaders.gl/modules/core/docs/api-reference/register-loaders

**Comment by theseusyang** [comment]
thanks @kylebarron ,I have registered the `GLTFloader registerLoaders([GLTFLoader]);` before that. but errors still happen

**Comment by Pessimistress** [comment]
Can you check that you have only one copy of `@loaders.gl/core` using `yarn list "@loaders.gl/*"`

**Comment by theseusyang** [comment]
yes, I manually add @loaders.gl/core/dist/dist.min.js and @loaders.gl/gltf/dist/dist.min.js on html

**Comment by Pessimistress** [comment]
Ah, you cannot do that. deck.gl already includes a copy of `@loaders.gl/core` and that is the copy you need to register your loader with.

```js
const {registerLoaders} = deck;

registerLoaders(loaders.GLTFLoader);
```

**Comment by theseusyang** [comment]
Ok, I will try it

**Comment by theseusyang** [comment]
when using  registerLoaders(loaders.GLTFLoader);

this error is happened 

`Uncaught (in promise) TypeError: registerLoaders is not a function`

I import deck.gl javascript by using 

`<script cross-origin  src="http://localhost:8089/javascript/deck.gl/@8.2.5/deck.gl.min.js"></script>`

**Comment by Pessimistress** [comment]
Apologies, it should be `loaders.registerLoaders`. I've corrected the above comment.

[example](https://codepen.io/Pessimistress/pen/gzYydZ)

**Comment by theseusyang** [comment]
@Pessimistress thank your answers

when I add  `loaders.registerLoaders(loaders.GLTFLoader); ` into codes
Error1 is :
` Uncaught (in promise) Error: null loader`

but when I add `loaders.registerLoaders(GLTFLoader); ` into codes
Error2 is:
`loaders.registerLoaders(GLTFLoader)`

I'm confused  these results

**Comment by theseusyang** [comment]
I upgrade the deck.gl version to 8.2.9, and use dist.dev.js

**Comment by Pessimistress** [comment]
You still need to include `@loaders.gl/gltf` with a script tag.

Please create a codepen if you are still experiencing issues; I can't tell what you're doing wrong from your description.

**Comment by theseusyang** [comment]
OK,but when include @loaders.gl/gltf, the error is happened again:

Error: No valid loader found data: "" for http://xxxx.xxxx.xxxx/javascript/models/stack.glb

**Comment by theseusyang** [comment]
I will create a codegen for this issue

**Comment by theseusyang** [comment]
https://codepen.io/theseusyang/pen/dyXbdzO

**Comment by Pessimistress** [comment]
What are you trying to demonstrate with that codepen?

If I add the following to its html there is no error:

```html
<script src="https://unpkg.com/deck.gl@latest/dist.min.js" ></script>
<script src="https://unpkg.com/@loaders.gl/gltf@latest/dist/dist.min.js" ></script>
```

**Comment by theseusyang** [comment]
yes I fix this bug, by adding loaders.gl/gltf@latest/dist/dist.min.js. 

now the problem is that 3D model is not shown in html
