### ISSUE TITLE
enable rotation without Cmd/Shift

### ISSUE THREAD

**Issue by hpetersilka** [visgl/deck.gl#4995]
Hi deck.gl team!

I'm using TypeScript with React Hooks and I've implemented a view similar to this one: https://deck.gl/examples/hexagon-layer/
But I'd like to have the controller behaviour similar to this one: https://deck.gl/examples/plot/

Main goal is to enable 3D-rotation without pressing Cmd/Shift.
(otherwise I cannot use rotation on touch devices)

I've tried to use `ControllerOptions` but it looks like I'm missing the TypeScript definition for this type.
I've also tried to implement a custom controller but this seems to be an overkill for such a simple feature.

The deck.gl parts of my package.json:
```
"@deck.gl/aggregation-layers": "^8.2.9",
"@deck.gl/core": "^8.1.9",
"@deck.gl/layers": "^8.1.9",
"@deck.gl/react": "^8.2.9",
```

That's how I initialize DeckGL:
```
    const [viewport, setViewport] = useState<ViewStateProps>({
        pitch: 45,
        latitude: 3,
        longitude: 5,
        zoom: 6,
        bearing: 60,
        maxZoom: 25,
        maxPitch: 90,
    });

    ...

    <DeckGL
        viewState={viewport}
        controller
        layers={layers}
        effects={[lightingEffect]}
        onViewStateChange={({ viewState }: { viewState: Viewport }): void => setViewport(viewState)}
        getTooltip={getTooltip}
    />
```

Thank's in advance for your support!

Best regards,
Harald

**Comment by Pessimistress** [comment]
We have discussed exposing this as a controller option, but have not implemented it. Meanwhile you can do this:

```js
import {MapController} from '@deck.gl/core';

class MyMapController extends MapController {
  constructor(props) {
    super(props);
    this.invertPan = !this.invertPan;
  }
}

<Deck ... controller={MyMapController} />
```

**Comment by kylebarron** [comment]
Possibly similar to https://github.com/visgl/deck.gl/issues/4853

**Comment by hpetersilka** [comment]
Thanks @Pessimistress !

I just had to slightly adapt it because of TypeScript rejected with
`Type 'typeof MyMapController' is not assignable to type 'boolean | Controller | null | undefined'.`

And I had to put MyMapController into a .js file because TypeScript rejected it with
`Property 'invertPan' does not exist on type 'MyMapController'.`

So that's my working solution now:

MyMapController.js:
```
class MyMapController extends MapController {
    constructor(props) {
        super(props);
        this.invertPan = !this.invertPan;
    }
}
```

Usage:
```
<DeckGL
                viewState={viewport}
                views={[
                    new MapView({
                        controller: MyMapController,
                    }),
                ]}
                layers={layers}
                effects={[lightingEffect]}
                onViewStateChange={({ viewState }: { viewState: Viewport }): void => setViewport(viewState)}
                getTooltip={getTooltip}
            />
```


Regards, Harald
