### ISSUE TITLE
How to setup  the sizescale property of ScenegraphLayer to correct position deviation

### ISSUE THREAD

**Issue by theseusyang** [visgl/deck.gl#4996]
when setup sizescale: 1000 in  ScenegraphLayer, the 3D model's  coordinates position deviates from the oriented position.

```
              data: [ {position: [119.6384, 39.9291]} ],
              scenegraph: 'stack.glb',
              getPosition: d => d.position,
              sizeScale: 1000,
              getOrientation: [0, 115, 90],
              getTranslation: [0, 0, 0],
              getScale: [1, 1, 1],
              pickable: true,
              _lighting: 'pbr',
```

which property parameter will be change to correct the position deviation?

@Pessimistress please help, thanks in advance!

**Comment by Pessimistress** [comment]
[getTranslation](https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer#gettranslation)

This is not a bug. If you want to ask a question, please use the question template.

**Comment by theseusyang** [comment]
will, I will. thanks a lot
