### ISSUE TITLE
Plotting geotiff file in pydeck

### ISSUE THREAD

**Issue by manisekhar-kothuri** [visgl/deck.gl#4997]
I have .tif file of Europe. I want to plot it in pydeck.
How to do that?

Below static plot is created using Rasterio package. But, my aim is to generate interactive plot
![image](https://user-images.githubusercontent.com/59639296/95295568-f09dfd80-0894-11eb-94cd-928c0d98cc1d.png)

**Comment by ajduberstein** [comment]
I'm a bit late to getting around to this but you can [export an image from rasterio with bounds](https://rasterio.readthedocs.io/en/latest/quickstart.html#dataset-georeferencing) and then use those bounds to set the location of the image in [pydeck](https://pydeck.gl/gallery/bitmap_layer.html). Also, you'll have to convert the image to base64-encoded bytes, which is discussed [here](https://github.com/visgl/deck.gl/issues/4977#issuecomment-700155508).
