### ISSUE TITLE
Heatmap - How to scale weight, threshold and radius from zoom?

### ISSUE THREAD

**Issue by rgazelot** [visgl/deck.gl#5003]
Hello, I tried to update the weight of my heat map when the zoom level changes. But it seems to be to much and all is freezing. My data is a around 3000 positions. Here is my layer's code :

```js
new HeatmapLayer({
    data,
    id: 'heatmap-layer',
    visible: true,
    pickable: false,
    colorRange: [
      [185, 16, 224, 0],
      [185, 16, 224, 25],
      [185, 16, 224, 38],
      [185, 16, 224, 64],
      [185, 16, 224, 102],
      [185, 16, 224, 127]
    ],
    getPosition: d => [d.lng, d.lat],
    getWeight: d => (zoom === 0 ? 0 : (zoom * 1) / 22),
    radiusPixels: 40,
    intensity: 1,
    threshold: 0.2,
    updateTriggers: {
      getWeight: [zoom]
    }
  })
```

Is there an efficient way to update the weight, threshold and radius property when the zoom level changes?

Thanks a lot for your help!

**Comment by Pessimistress** [comment]
You should adjust `intensity` instead of invalidating `getWeight`. See [performance tips](https://deck.gl/docs/developer-guide/performance#favor-constants-over-callback-functions)

**Comment by rgazelot** [comment]
@Pessimistress Thanks for the answer. I tried this way :

```js
new HeatmapLayer({
    data,
    id: 'heatmap-layer',
    visible: true,
    pickable: false,
    colorRange: [
      [185, 16, 224, 0],
      [185, 16, 224, 25],
      [185, 16, 224, 38],
      [185, 16, 224, 64],
      [185, 16, 224, 102],
      [185, 16, 224, 127]
    ],
    getPosition: d => [d.lng, d.lat],
    getWeight: d => 1 / 22,
    radiusPixels: 40,
    intensity: 1 / 22,
    threshold: 0.2,
    intensityScale: zoom
  })
```
But everything continue to freeze. Did I miss something about the documentation you shared?

**Comment by Pessimistress** [comment]
- First, make sure that your app works smoothly without changing the layer. If it still "freezes", then your issue is elsewhere.
- You should make `colorRange` a constant. Props that shallowly change trigger layer updates that may be expensive.
- `getWeight` does not need to be a callback if it is constant.
- There is no prop called `intensityScale`. [documentation](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/aggregation-layers/heatmap-layer.md#properties).

**Comment by rgazelot** [comment]
@Pessimistress thanks a lot for the answer. I made a constant for the colorRange, but didn't solve the issue. Here is my layer:

```js
const colorRange: ColorRange = [
    [249, 240, 255],
    [211, 173, 247],
    [179, 127, 235],
    [146, 84, 222],
    [114, 46, 209],
    [83, 29, 171]
  ]

  return new HeatmapLayer({
    data,
    id: 'vehicles-heatmap-layer',
    visible: isVisible,
    pickable: false,
    colorRange: colorRange,
    getPosition: d => [d.lng, d.lat],
    radiusPixels: (zoom * 30) / 22,
    intensity: (zoom * 1) / 22,
    threshold: 0.3
  })
```

What I need exactly is to make the Radius and the Weight scale linearly from the zoom level. In order to be able to reproduce the effect the designer set on mapbox studio:

<img width="353" alt="Screenshot 2020-10-12 at 15 56 26" src="https://user-images.githubusercontent.com/1488251/95754547-7fe74e80-0ca3-11eb-9285-891f7e1b1d4c.png">

Everything still freeze like hell. If I set constants, the animation is quite fine, at least the same as [the documentation](https://deck.gl/docs/api-reference/aggregation-layers/heatmap-layer).

Do you think it's possible to make these properties scale according to the zoom level?

**Comment by Pessimistress** [comment]
Looks like the update is not denounced if you change `radiusPixels` during zoom. I will investigate.

**Comment by Pessimistress** [comment]
Try 8.3.0

**Comment by rgazelot** [comment]
@Pessimistress Perfect! The debounce works perfectly. Thanks a lot for your help and the job you do. Congrats to all the team!
