### ISSUE TITLE
@deck.gl/arcgis - unable to use transition property

### ISSUE THREAD

**Issue by pdnellius** [visgl/deck.gl#5005]
#### Description
With the current implementation of `@deck.gl/arcgis` I'm unable to use the `transitions:{...}` property.

#### Repro Steps
- Clone repo
- Navigate to `deck.gl/examples/get-started/pure-js/arcgis`
- `npm install`
- `npm install d3`
- open `app.js`
- add `import {easeCubicInOut} from 'd3';`
- within `new GeoJsonLayer({...})` under `getFillColor:...,` add the transitions property per https://deck.gl/docs/api-reference/core/layer#transitions :
```
        new GeoJsonLayer({
        ...
        getRadius: (f) => 11 - f.properties.scalerank,
        getFillColor: [200, 0, 80, 180],
        transitions: {
          getFillColor: {
            duration: 3000,
            easing: easeCubicInOut,
            enter: (value) => [value[0], value[1], value[2], 0] // fade in
          }
        },
        ...
     })
```
- Observe that points do not fade in as expected

**Example:**
https://codesandbox.io/s/festive-smoke-u8de0?file=/app.js

#### Environment (please complete the following information):
 - Framework Version: `@deck.gl/arcgis` v8.2.10
 - Browser Version: Chrome 85
 - OS: macOS 10.15.7

#### Logs
```
deck: WebGL2 not supported by this browser. Transition animation is disabled. 
```
Note: I _am_ using a WebGL2-compatible browser, I do not receive this error when running a standard deck.gl example

**Comment by Pessimistress** [comment]
`deck.gl/arcgis` uses the WebGL context created by ArcGIS. If ArcGIS creates a WebGL1 context then transition will not be supported. @damix911 is there a way to opt into WebGL2?

**Comment by damix911** [comment]
> is there a way to opt into WebGL2?

Not at present time. I don't think there are immediate plans to allow for it in the public  API but I'll check with other devs if there is any way we can help.

**Comment by Pessimistress** [comment]
Removing the bug label since this is something outside of deck.gl's control

**Comment by pdnellius** [comment]
@damix911 I know this has been closed, but is this something you can follow up on? if the API had an option for a WebGL2 context it should be backwards compatible, no? it'd be really nice to use the more performant transition properties

**Comment by damix911** [comment]
Yeah, we had a discussion about this a while ago but now I am bringing it up again; devs seems pretty onboard about offering a WebGL 2 opt-in; I guess the latest release (4.18) was just too busy for this to make the cut.

I'll keep you posted.

**Comment by damix911** [comment]
> One real problem with making a big WebGL1 codebase work on WebGL2 is that WebGL1 extensions are not supported in WebGL2 (this is true for those WebGL1 extensions that have replacement APIs in WebGL2, meaning that code has to be modified or the code will crash or those features will be lost).

We have an internal abstraction layer that _for the most part_ is taking care of this; I think we are in a good spot technically but haven't put much thought into enabling this publicly. There are probably a few things to smooth out but we have sucessfully ran the JS API in WebGL 2 mode in the past. I was even able to write a `"webgl2-compute"` layer once.

I'll suggest that we expose it as a beta opt-in.

**Comment by zakjan** [comment]
@damix911 Do you mind if I ask what's the status of exposing WebGL2 opt-in? I couldn't find it in 4.19. Possibly it could be in 4.20?

**Comment by damix911** [comment]
Hello @zakjan sorry for the super-late reply.

It's not in 4.19, nor in 4.20. As far as I know all of our code base is working fine in WebGL 2 mode, but we haven't flipped the switch yet.

I think both the options of defaulting to 1 and allowing opt-in to 2, as well as defaulting to 2 and allowing opt-out to 1 are on the table.

I'll keep you posted.

**Comment by damix911** [comment]
It's still early to say for sure, but the ArcGIS JS API team is on track to merge WebGL 2 support in the upcoming release of the API. 

This effort should fix this issue and close it "for real".
