### ISSUE TITLE
onHover - setToolTip undefined

### ISSUE THREAD

**Issue by pdnellius** [visgl/deck.gl#5008]
#### Description
When calling `onHover: setToolTip()` and following the implementation instructions on https://deck.gl/docs/developer-guide/interactivity#using-the-built-in-tooltip, a tooltip is not displayed.

#### Repro Steps
- clone https://github.com/visgl/deck.gl/tree/8.2-release/examples/get-started/pure-js/basic
- `npm install`
- implement setToolTip:
```
...
const deck = new Deck({
  initialViewState: INITIAL_VIEW_STATE,
  controller: true,
  layers: [
    new GeoJsonLayer({
      id: "base-map",
      data: COUNTRIES,
      // Styles
      stroked: true,
      filled: true,
      lineWidthMinPixels: 2,
      opacity: 0.4,
      getLineColor: [60, 60, 60],
      getFillColor: [200, 200, 200]
    }),
    new GeoJsonLayer({
      id: "airports",
      data: AIR_PORTS,
      // Styles
      filled: true,
      pointRadiusMinPixels: 2,
      pointRadiusScale: 2000,
      getRadius: (f) => 11 - f.properties.scalerank,
      getFillColor: [200, 0, 80, 180],
      // Interactive props
      pickable: true,
      autoHighlight: true,
      onHover: (info) => setTooltip(info.object, info.x, info.y)
    }),
    new ArcLayer({
      id: "arcs",
      data: AIR_PORTS,
      dataTransform: (d) =>
        d.features.filter((f) => f.properties.scalerank < 4),
      // Styles
      getSourcePosition: (f) => [-0.4531566, 51.4709959], // London
      getTargetPosition: (f) => f.geometry.coordinates,
      getSourceColor: [0, 128, 200],
      getTargetColor: [200, 0, 80],
      getWidth: 1
    })
  ],
  getTooltip: ({ object }) => object && object.message
});
...
```
- observe console error: `Uncaught ReferenceError: setTooltip is not defined`

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.10
 - Browser Version: Chrome 85
 - OS: macOS 10.15.7

#### Example
https://codesandbox.io/s/gallant-leaf-h0hmc?file=/app.js

#### Logs
```
Uncaught ReferenceError: setTooltip is not defined
```

**Comment by padawannn** [comment]
https://github.com/visgl/deck.gl/issues/1861

**Comment by Pessimistress** [comment]
Just delete the `onHover` line. I think it is the leftover from an old example.
