### ISSUE TITLE
Sometimes plot markers are missing when exporting as image

### ISSUE THREAD

**Issue by vivek091195** [visgl/deck.gl#5014]
I am facing this issue randomly. When plotting icons with deck.gl on Google map and taking a screenshot, sometimes the screenshot comes properly, but sometimes the plot markers are missing. I am using HTML2Canvas to render a screenshot and deck.gl to plot the markers on the map. Once I click the screenshot icon and get the proper screenshot, the deck.gl canvas isn't getting modified, yet the next time randomly the plot markers disappear if I take the screenshot again. Code used for setting icon layers is -

```
 deck.setProps({
    layers: layers,
    glOptions: { preserveDrawingBuffer: true },
    onBeforeRender: () => {
      console.log('called : onBeforeRender');
    },
    onAfterRender: () => {
      console.log('called : onAfterRender');
    }
  });
```

Code for converting it via HTML2Canvas-
```
    html2canvas(document.body, options())
      .then(async function (canvas) {
        let a = document.createElement('a');
        a.href = canvas.toDataURL('image/jpeg', 1);
        a.download = 'screenshot.png';
        a.click();
})
```

options-
```
return { allowTaint: true,
    letterRendering: 1,
    foreignObjectRendering: true,
    quality: 1,
    width: width,
    height: height,
    scale: ratio,
    useCORS: true,
    logging: false
}

```

I tried `redraw` method also on the deck, but the same issue still exist.

**Comment by Pessimistress** [comment]
See #4436

You may need to set `glOptions.preserveDrawingBuffer`.

**Comment by coder-at-work** [comment]
@Pessimistress I am setting `glOptions.preserveDrawingBuffer` as true already

**Comment by Pessimistress** [comment]
You need to set it upon initialization (either `new Deck` or `new GoogleMapsOverlay`). The option is only used when creating the WebGL context.

**Comment by coder-at-work** [comment]
@Pessimistress I tried setting it up like this-

```
    const deckGlProps = {
      glOptions: {
        preserveDrawingBuffer: true
      }
    };
    this.mapOverlay = new GoogleMapsOverlay({
      parameters: deckGlProps
    });
    this.mapOverlay.setMap(this.map);
```

But the issue is still happening, please correct me if I am going wrong somewhere.

**Comment by coder-at-work** [comment]
@Pessimistress I tried upgrading @deck.gl/google-maps to `8.3.0-beta.2`, but still observing the same issue.

**Comment by Pessimistress** [comment]
`glOptions` is a top-level prop. You should not nest it in `parameters`.

**Comment by vivek091195** [comment]
@Pessimistress I am setting **glOptions** upon initialization of **GoogleMapsOverlay**, but still observing the issue randomly.
```
    const deckGlProps = {
      glOptions: {
        preserveDrawingBuffer: true
      }
    };
    this.mapOverlay = new GoogleMapsOverlay(deckGlProps);
    this.mapOverlay.setMap(this.map);
```
Is there anything else that I might be missing? Sometimes, it works fine but in some instances the plot markers are missing.

**Comment by Pessimistress** [comment]
Can you create a CodeSandbox that reproduces your issue?

**Comment by vivek091195** [comment]
@Pessimistress I guess, it will be difficult to replicate the same over code sandbox because of plotting data issues. I am attaching the issue below(one screenshot is proper with the markers but the other is missing the markers).
<img width="823" alt="Screenshot 2020-11-02 at 5 11 00 PM" src="https://user-images.githubusercontent.com/31046026/97864609-da1d8180-1d2e-11eb-84ff-9b75486d6c08.png">
<img width="807" alt="Screenshot 2020-11-02 at 5 11 14 PM" src="https://user-images.githubusercontent.com/31046026/97864621-e3a6e980-1d2e-11eb-9274-a4af98a0b388.png">

Initialization - 
```
    const deckGlProps = {
      glOptions: {
        preserveDrawingBuffer: true
      }
    };
    this.mapOverlay = new GoogleMapsOverlay(deckGlProps);
    this.mapOverlay.setMap(this.map);
```

I am forcing redraw before capturing the canvas, Code for converting the canvas to the image-
```
    mapObj && mapObj.map.mapOverlay._deck.redraw(true);
    html2canvas(document.body, options())
      .then(async function (canvas) {
        let a = document.createElement('a');
        a.href = canvas.toDataURL('image/jpeg', 1);
        a.download = 'screenshot.png';
        a.click();
})
```
Options-
```
return { allowTaint: true,
    letterRendering: 1,
    foreignObjectRendering: true,
    quality: 1,
    width: width,
    height: height,
    scale: ratio,
    useCORS: true,
    logging: false
}
```

But sometimes, when I try to capture a screenshot, the plot markers are missing as shown in attached screenshot and sometimes it works fine.

**Comment by Pessimistress** [comment]
You shouldn't need to force redraw with `preserveDrawingBuffer: true`.

I am not familiar with html2canvas so I can't speak to whether there are some caveats using it. Can you try calling `mapOverlay._deck.canvas.toDataURL` directly and see if it still comes up empty sometimes?

**Comment by vivek091195** [comment]
@Pessimistress I tried capturing it directly with `mapOverlay._deck.canvas.toDataURL`, but still it misses out the markers sometimes. I removed force redraw as well but no luck.

**Comment by Pessimistress** [comment]
There is likely something else in your app that is either changing the content of the overlay or trigger rerender when that happens. Without seeing the rest your code it's hard to tell what is going on. You can find a basic example here:
https://codepen.io/Pessimistress/pen/ExyyzjV

**Comment by vivek091195** [comment]
@Pessimistress I am using `'@deck.gl/google-maps'` and setting deckGlProps like this-
```
    const deckGlProps = {
      glOptions: {
        preserveDrawingBuffer: true
      }
    };
    this.mapOverlay = new GoogleMapsOverlay(deckGlProps);
    this.mapOverlay.setMap(this.map);
```

I even tried putting console.log in onAfterRender to check if any re-rendering is happening post I click on screenshot button, but it isn't happening,
```
      mapControl.map.mapOverlay._deck.setProps({
        layers: layers.sort(compare('id')).reverse(),
        onAfterRender: (gl) => {
          console.log(gl)
          setCanvas(mapControl.map.mapOverlay._deck.canvas.toDataURL());
        },
        getTooltip: ({ object }) => {
          if (!object) {
            return null;
          }
          if (!(object.isLabelsActive && object.label)) {
            return null;
          }
          return {
            text: object && `${object.label}`
          };
        }
      });
```

One catch which I found is - If I remove `onAfterRender` and try to capture the canvas directly with `mapControl.map.mapOverlay._deck.canvas.toDataURL()`, it is always coming as empty. Could you please help me with a working basic example of a screenshot utilizing GoogleMapsOverlay instead of Deck overlay?

**Comment by Pessimistress** [comment]
> If I remove onAfterRender and try to capture the canvas directly with mapControl.map.mapOverlay._deck.canvas.toDataURL(), it is always coming as empty. 

You are not using @deck.gl/google-maps@^8.3.0 as I suggested.

> Could you please help me with a working basic example

I asked you to create a code sandbox 3 comments ago. Posting an excerpt of your code over and over again does not help me help you.

**Comment by vivek091195** [comment]
@Pessimistress Thanks a lot for your help. I actually tried with the version which you suggested a few days ago - `8.3.0-beta.2`. In a few instances, it was failing there too but with `@deck.gl/google-maps@^8.3.0`, I tried multiple times haven't noticed a failure. Will update here if I get the issue again.
