### ISSUE TITLE
Variable width path

### ISSUE THREAD

**Issue by dcooley** [visgl/deck.gl#5021]
[Here is a working fiddle](https://jsfiddle.net/symbolixau/09e2u5jg/191/) with an example of multi-coloured paths, where each coordinate has a different colour, and each segment of the path gets two colours. 

Here's a snippet of the code

```js
class MultiColouredPathLayer extends deck.PathLayer {
  
    initializeState() {
      super.initializeState();           
      this.state.attributeManager.addInstanced({
        colors: {
          size: this.props.colorFormat.length,
          vertexOffset: 0,
          type: 0x1401,  // UNSIGNED_BYTE
          normalized: true,
          accessor: 'getColor',
          transition: ATTRIBUTE_TRANSITION,
          defaultValue: DEFAULT_COLOR,
          shaderAttributes: {
            instanceFirstColour: {
              vertexOffset: 0
            },
            instanceLastColour: {
              vertexOffset: 1
            }
          }
        }
      });
    }
  
    getShaders() {
      return {
        ...super.getShaders(),
        inject: {
          'vs:#decl': `          
          attribute vec4 instanceFirstColour;
          attribute vec4 instanceLastColour; 
          
          varying vec4 firstColour;
          varying vec4 lastColour;
          `,
          'vs:#main-end':`
          firstColour = vec4( instanceFirstColour.rgb, instanceFirstColour.a * opacity );
          lastColour = vec4( instanceLastColour.rgb, instanceLastColour.a * opacity );

          vColor = mix( firstColour, lastColour, positions.x );          
          `
        }
      }
    };
  }
```

I've tried to extend this where each coordinate also gets its own width

```js
widths: {
          size: 1,
          vertexOffset: 0,
          type: 0x140a, // DOUBLE
          //normalized: true,
          accessor: 'getWidth',
          //transition: ATTRIBUTE_TRANSITION,
          defaultValue: 1,
          shaderAttributes: {
            instanceFirstWidth: {
              vertexOffset: 0
            },
            instanceLastWidth: {
              vertexOffset: 1
            }
          }
        }
```

but I can't see how to inject into the vertex shader these Instance Width values so the [`vec2 widthPixels`](https://github.com/visgl/deck.gl/blob/8.2-release/modules/layers/src/path-layer/path-layer-vertex.glsl.js#L174) variable uses them.

So my question is, is it possible to have a segment where either end has a different width, and if so, how do I inject these values into the shader?

**Comment by Pessimistress** [comment]
You are correct there isn't a hook to modify width before calculating the joints. We should consider moving the `DECKGL_FILTER_SIZE` hook to before the width is used.

As a hack, you can inject into the vertex shader by search and replace:

```js
inject: {
  `vec2 width;`: `widthPixels *= ...`

}
```

Unrelated - I highly recommend you not adding two more attributes for each feature. You can reuse the existing one and add an `instanceNext*`. PathLayer already has 13 attributes and the WebGL limit is 16.

**Comment by dcooley** [comment]
> As a hack, you can inject into the vertex shader by search and replace:

I think I'll leave the hacks for now; I'd rather keep using the stable API to make changes.

> We should consider moving the DECKGL_FILTER_SIZE hook to before the width is used.

Would you like me to open a separate issue to formally request this?

---

> I highly recommend you not adding two more attributes for each feature

Thanks for the tip. I've [updated the code](https://jsfiddle.net/symbolixau/09e2u5jg/198/) to only add one extra `instance` attribute

**Comment by Pessimistress** [comment]
This issue can serve as the feature request.

**Comment by Pessimistress** [comment]
With 8.3.0 you should be able to inject into the [vs:DeckGL_FILTER_SIZE](https://deck.gl/docs/developer-guide/custom-layers/writing-shaders#vsdeckgl_filter_size) hook. `size.xy` will represent the width in common space.

**Comment by dcooley** [comment]
I don't quite see how to implement this because it seems like I need to update `widthPixels` to use either the extant 'instanceStrokeWidth`, or my new `instanceNextStrokeWdith`.

**Comment by Pessimistress** [comment]
```js
inject: {
  'vs:DECKGL_FILTER_SIZE': `\
    float widthAtVertext = mix(instanceStrokeWidth, instanceNextStrokeWidth, positions.x);
    size *= widthAtVertext / instanceStrokeWidth;
  `
}
```

**Comment by dcooley** [comment]
Are `instanceStrokeWidth` and `positions.x` available inside `vs:DECKGL_FILTER_SIZE` ? I get [errors saying they're not available](https://jsfiddle.net/symbolixau/09e2u5jg/247/)

![Screen Shot 2020-10-13 at 6 24 12 pm](https://user-images.githubusercontent.com/8093396/95828972-5c92d100-0d81-11eb-9318-9b3768e06a2c.png)

**Comment by Pessimistress** [comment]
Sorry, yes, in the hooks you only have access to the attributes that you injected.

You can keep `instanceFirstWidth` and `instanceLastWidth` and do this:

```js
inject: {
  'vs:#decl': `          
    attribute vec4 instanceLastColour;
    attribute float instanceFirstWidth;
    attribute float instanceLastWidth;
    `,
  // store `positions` in global context
  'vs:#main-start':`
    geometry.uv = positions;
    `,
  'vs:DECKGL_FILTER_SIZE':`
    float widthAtVertext = mix(instanceFirstWidth, instanceLastWidth, geometry.uv.x);
    size *= widthAtVertext / instanceFirstWidth;
    `,
  ...
}
```

This will max out your attribute count at 16.

You can save one attribute slot by sending the width ratio between the last vertex and the first vertex, see https://jsfiddle.net/aok5z9xq/

**Comment by dcooley** [comment]
Excellent. This gives me a lot to work with. 

An interesting artefact I've noticed is if the path is 'closed', the first segment width gets changed. 

![Screen Shot 2020-10-14 at 8 14 41 am](https://user-images.githubusercontent.com/8093396/95917335-cfd62a80-0df5-11eb-939b-f62d5cf97eee.png)

This is not an issue if the paths 'cross' (self-intersect).

![Screen Shot 2020-10-14 at 8 15 52 am](https://user-images.githubusercontent.com/8093396/95917442-fe540580-0df5-11eb-8ad9-26b1a5d918a1.png)

I think I can get around this as I'll be using the 'binary' format, and will specify the `_pathType:` argument, but I'll let you know if I still have this issue.

**Comment by Pessimistress** [comment]
For loops you need to repeat two vertices' worth of colors/widths to match the internal positions attribute structure:

```js
path: [
        [-0.3,0.3],    // top-left
        [0.3,0.3],     // top-right
        [0.3,-0.3],    // bottom-right
        [-0.3,-0.3],    // bottom-left
        [-0.3,0.3],
      ],
colour: [
        [255,0,0,255],  // Red
        [0,255,0,255],  // Green
        [0,0,255,255],  // Blue
        [0,0,0,255],     // Black
        [255,0,0,255],
        [0,255,0,255]
      ],
width: [
        2000,
        4000,
        6000,
        8000,
        2000,
        4000,
      ]
```

It has to do with each join requiring 3 vertices (before, current, after) to render correctly.
