### ISSUE TITLE
Can I display a onHover tooltip on a MapboxLayer ?

### ISSUE THREAD

**Issue by Nahelou** [visgl/deck.gl#5022]
Hello !

I'm stuck with an issue and couldn't find anything to help yet.
I'm trying to add a pop-up / tooltip to the scatterPlot hover of a DeckGL rendered on a MapboxGL Map (MapboxLayer type ScatterplotLayer) like the code here:
     
**const** airportOut = new MapboxLayer({
                id: "scatterOut",
                type: ScatterplotLayer,
                data: dataToArcLayer,
                getPosition: (d) => d.destination,
                radiusScale: 500,
                getRadius: 10,
                getColor: this.inFlowColors,
                radiusMinPixels: 2,
                onHover: (info) => setTooltip(info.airport, info.x, info.y),
        });
        this.map.addLayer(airportOut);

I'm using the lastest version of DeckGL and MapboxGL, with Vue

I've tried this, with the MapBox documentation : [https://docs.mapbox.com/mapbox-gl-js/example/popup-on-hover/]()
But the hover on my layer don't work at all (while this.map.getLayer('scatterOut') is actually working)

Is there a documentation for this ? 
Maybe I didn't find it... Thanks a lot !

**Comment by Pessimistress** [comment]
`pickable` must be set to `true`

https://deck.gl/docs/developer-guide/interactivity#enabling-picking

**Comment by Nahelou** [comment]
Oh... That was easy haha
Thanks a lot ! Have a good day

**Comment by luojiandan** [comment]
@Pessimistress 
Thanks too.

**Comment by luojiandan** [comment]
@Pessimistress 
Thanks too.
How aboud transitions in MapboxLayer?

Issue：https://github.com/visgl/deck.gl/issues/5110
