### ISSUE TITLE
IconLayer intersecting with map layer during tilting of the map

### ISSUE THREAD

**Issue by nanda248** [visgl/deck.gl#5024]
I am using GeoJSON layer for map and IconLayer (using Auto Packing for icons and billboard: true) for the icons.

Currently I'm having the issue where the map layer is intersecting the the icons during tilting. 
Please see the 2 screenshots I put below. Left one is top view without tilting, Right one is the view after tilting. As you see in right screenshot, icon is dissected by some lines on map layer.

![image](https://user-images.githubusercontent.com/19261650/95721540-54fdfa00-0ca5-11eb-93c6-d7f7669ba97d.png)

I'm wondering if there's any way for the icons to be always positioned on top of map layer. Can anyone suggest a solution?

Thanks in advance ^^

**Comment by Pessimistress** [comment]
You can turn off depth test with

```js
new IconLayer({
  ...
  parameters: {
    depthTest: false
  }
})
```

**Comment by nanda248** [comment]
Thanks a lot, @Pessimistress !!! It's working as I expected now.

**Comment by pachacamac** [comment]
Thanks that saved me a few hours
