### ISSUE TITLE
Cannot read property 'highlightedObjectIndex' of undefined with 8.3

### ISSUE THREAD

**Issue by supersonicclay** [visgl/deck.gl#5028]
#### Description
When using nebula.gl, I'm getting an error when upgrading from 8.2 to 8.3.

#### Repro Steps
https://codesandbox.io/s/stoic-saha-wp4ku?file=/index.js

Downgrade to 8.2: works
Upgrade to 8.3:
```
Cannot read property 'highlightedObjectIndex' of undefined
```

#### Environment (please complete the following information):
 - Framework Version: 8.3

**Comment by Pessimistress** [comment]
Looks like EditableGeoJsonLayer is not sending `oldProps` when calling `updateState`:

https://github.com/uber/nebula.gl/blob/master/modules/layers/src/layers/editable-geojson-layer.ts#L289

**Comment by supersonicclay** [comment]
Fixed in nebula 0.21.1.

**Comment by joenordlingNeerAI** [comment]
I am getting this same bug in Nebula 22.3 any ideas?
