### ISSUE TITLE
pydeck don't render map tiles in html

### ISSUE THREAD

**Issue by omar-3** [visgl/deck.gl#5032]
#### Description

I have successfully installed and ran pydeck in my machine and there are no errors at all when running the examples provided in the website. The problem is the output; the layers get rendered as intended but the map tiles don't show at all. So the output is just the layers with white background.

#### Repro Steps

I ran this example https://pydeck.gl/gallery/bitmap_layer.html, and that was the output

![alt text](https://i.ibb.co/4Y1mgBY/Screen-Shot-2020-10-15-at-1-18-24-AM.png)

I tried opening the html file in chrome and safari and nothing happens. 

#### Environment (please complete the following information):

 - Mac OS X 10.13

#### Logs

From Chrome console

deck: Using Mapbox base maps
mapbox-gl.js:29 This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
x @ mapbox-gl.js:29
api.mapbox.com/styles/v1/mapbox/satellite-v9?access_token=None:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
mapbox.js:11 e
onError @ mapbox.js:11
api.mapbox.com/styles/v1/mapbox/satellite-v9?access_token=None:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
mapbox.js:11

**Comment by kylebarron** [comment]
That's because you haven't provided a Mapbox API Key. See https://pydeck.gl/installation.html#getting-a-mapbox-api-key

**Comment by omar-3** [comment]
> That's because you haven't provided a Mapbox API Key. See https://pydeck.gl/installation.html#getting-a-mapbox-api-key

Perfect, thank you.
