### ISSUE TITLE
Transitions not being triggered when data is updated

### ISSUE THREAD

**Issue by ricardoekm** [visgl/deck.gl#5036]
#### Description
I'm trying to add transitions property to a Scatterplot layer to create a fade-in effect when data is updated. On the first render the transition is executed properly. However, when the data is updated the transition is not executed, even though the new data is correctly rendered.

Did I get anything wrong? Thanks.

#### Repro Steps

```typescript
 return new ScatterplotLayer({
      id: props.id,
      data,
      getPosition: super.getPosition,
      updateTriggers: { getFillColor: Math.random() },
      transitions: {
         getFillColor: {
            duration: 1200,
            easing: d3.easeCubicOut,
            enter: value => [value[0], value[1], value[2], 0]
         }
      }
})
```

If we create a new layer each render cycle the transition works fine on the first render and when updating (i.e. changing to a new id every time)
```typescript
 return new ScatterplotLayer({
      id: props.id + Math.random(),
      data,
      getPosition: super.getPosition,
      updateTriggers: { getFillColor: Math.random() },
      transitions: {
         getFillColor: {
            duration: 1200,
            easing: d3.easeCubicOut,
            enter: value => [value[0], value[1], value[2], 0]
         }
      }
})
```

#### Environment
 - Framework Version: ^8.1.7
 - Browser Version:  86.0.4240.75
 - OS: Mac OS X 10.15

**Comment by Pessimistress** [comment]
`enter` only applies to *added* objects. You do not seem to be changing the fill color between data updates, so for most points there will be no visible transition.

If that is not the problem you are describing, please create a codepen/codesandbox that illustrates your issue.

**Comment by ricardoekm** [comment]
Hi Pessimistress, thanks for your reply.

Can you please elaborate on what's the definition of added objects? In this case I'm updating the entire dataset, so the shallow comparison will return false for all rows. None of them have the transition applied, even though they are correctly rendered.

**Comment by ricardoekm** [comment]
Here goes a code sandbox that reproduces the issue:
[Codesandbox](https://codesandbox.io/s/react-map-gl-geocoder-v2-example-forked-gz2wk?file=/src/index.js)

**Comment by Pessimistress** [comment]
Before update, you have 1 black circle
After update, you have 1 black circle
The `getFillColor` transition transitions color from black to black == No visible transition

If you update the color to red, you'll see it transition from black to red.

If you have 1 black circle before transition, and 2 black circles after transition, then the second one will fade it (there's no "from" value, so `enter` is called)

**Comment by ricardoekm** [comment]
Imagine I have two data points: A and B.

If I understand correctly, what you're saying is:
* add A: A pops up with animation,
* add A then add B: A pops up with animation, B pops up with animation.
* add A, delete A, add B: A pops up with animation, B doesn't

I understand there should be some technical explanation, but IMO it doesn't make a lot of sense from the user standpoint. If the rows count is the same it doesn't run the transition, if it decreases it doesn't either, if it increases it runs on the additional rows regardless of who they are.

If the data comparator returns this is a different row perhaps Deck shouldn't use the from field cached from another row?

**Comment by Pessimistress** [comment]
In the current implementation, deck.gl's transition feature identifies objects by their index. This means that whatever is at index 0 before the update, transitions to whatever is at index 0 after the update. If you want to "delete" something, you need to make two layer updates:

data: [A]
-> data: []
-> data: [B]

There is a backlog feature request to support key-based transition, see related issues:

https://github.com/visgl/deck.gl/issues/4199
https://github.com/visgl/deck.gl/issues/3435
https://github.com/visgl/deck.gl/issues/2570

**Comment by Pessimistress** [comment]
Merging with #2570
