### ISSUE TITLE
Layer's visible props does not update when using with React hook useState

### ISSUE THREAD

**Issue by HuyHoang-Ta** [visgl/deck.gl#5037]
Hello, I am using DeckGL with React TypeScript. There is a question relevant to changing  layer's visible props dynamically i want to ask:

1. Normal use case works correctly: layer's visibility changes according to the visible props
```
const [visible, setVisible] = useState<boolean>(true);
const layers = [
        new GeoJsonLayer({           
            data,
            visible,
        }),
 ]
```
2. **useState** on layers works unexpectedly: layer's visibility does not change when visible props changes
```
const [visible, setVisible] = useState<boolean>(true);
const [layers, setLayers] = useState<any[]>([
        new GeoJsonLayer({
            data,
            visible,
        }),
 ]);
```
Thank you.

**Comment by Pessimistress** [comment]
That's not how hooks work. `visible` is evaluated when it's used, in your case, only when the component was rendered the first time (`useState(initialState)`). You need to construct a new layer instance whenever `visible` changes.

**Comment by HuyHoang-Ta** [comment]
Thank you!

**Comment by florinvirdol** [comment]
Hi, guys,
There's no way to programmatically change a property (like visible property) in Angular environment and with Google Maps?
@Pessimistress  I need to construct a new layer instance whenever `visible` changes?!

Thank you very much!

**Comment by AdriSolid** [comment]
@florinvirdol Try to reproduce your issue in a codepen and open a new Discussion, thanks!

**Comment by suryakumara** [comment]
> That's not how hooks work. `visible` is evaluated when it's used, in your case, only when the component was rendered the first time (`useState(initialState)`). You need to construct a new layer instance whenever `visible` changes.

Hi, I want to ask some question. So if I need to update `data` inside GeoJSONLayer, I need to re-create new GeoJSONLayer ? . Because I did't get any documentation about how to update data in React.
