### ISSUE TITLE
Question about lighting effects

### ISSUE THREAD

**Issue by liubx** [visgl/deck.gl#5040]
Hi, I  drew a set of polygons on Map with same lighting effect and default material. But the lighting effect shows on map is different. What factors make the differences?  Thanks

```
// The lighting effect I set.

         new LightingEffect({
            ambientLight: new AmbientLight({
              color: [255, 255, 255],
              intensity: 1.5,
            }),
            directionalLight1: new DirectionalLight({
              color: [255, 255, 255],
              intensity: 1.0,
              direction: [-1, 3, -1],
            }),
            directionalLight2: new DirectionalLight({
              color: [255, 255, 255],
              intensity: 1.0,
              direction: [1, -8, -2.5],
            }),
          }),
```

<img width="1097" alt="Screen Shot 2020-10-17 at 7 59 45 AM" src="https://user-images.githubusercontent.com/7749950/96323269-f773ff80-104e-11eb-9e92-076c4c592051.png">

**Comment by Pessimistress** [comment]
Please use the bug template if you want to open a bug. Otherwise use the question template.

**Comment by liubx** [comment]
I am very sorry about that. I will submit it with a right template.
