### ISSUE TITLE
Bug about lighting effect

### ISSUE THREAD

**Issue by liubx** [visgl/deck.gl#5042]
#### Description
I  drew a set of polygons on Map with same lighting effect and default material. But the lighting effect of each polygon shows on map are not all the same. Is this a Bug?  Thanks
<img width="962" alt="Screen Shot 2020-10-18 at 9 33 39 AM" src="https://user-images.githubusercontent.com/7749950/96356704-05944f80-1125-11eb-990c-0e0d456525f0.png">

#### Repro Steps
- Load data with Deck.gl and PolygonLayer
- [Codepen example](https://codepen.io/liubx/pen/pobyXMV)

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.3.1
 - Browser Version: Chrome 86.0
 - OS: Mac OS X 10.15.7

#### Logs

**Comment by Pessimistress** [comment]
Thank you for reporting. There is an issue in handling normal precision in the `SolidPolygonLayer`, and I'll put up a fix.

Meanwhile, here are some suggestions:

- `effects` is a `Deck` prop, not a layer prop.
- When dealing with objects this small, it's more practical for you to use the [METER_OFFSETS](https://deck.gl/docs/developer-guide/coordinate-systems#supported-coordinate-systems) coordinate system. I can't imagine your original data came in lngLat format.

**Comment by Pessimistress** [comment]
Fixed in 8.3.2

**Comment by liubx** [comment]
Thanks!
