### ISSUE TITLE
Grid Coordinate System

### ISSUE THREAD

**Issue by HuyHoang-Ta** [visgl/deck.gl#5050]
- Hello everyone, currently I am displaying a **GeoJsonLayer** using **COORDINATE_SYSTEM.METER_OFFSETS** in my map.

- Now, I need to display **a coordinate system grid with label (in meter)** for my layer like this: 

![coordinate-grid](https://user-images.githubusercontent.com/61722520/96686520-d3931f80-13a8-11eb-9174-b18601f7c40e.jpg)
Are there any methods in DeckGL that can help me achieve this ? I have looked at **GridLayer** which I thought can help me , but it seems nothing is rendered as in the document it says 

> The GridLayer at the moment only works with COORDINATE_SYSTEM.LNGLAT

**Comment by Pessimistress** [comment]
GridLayer does not display a grid, it aggregates data into a grid. You need `LineLayer` and `TextLayer`.

**Comment by HuyHoang-Ta** [comment]
Are there any methods getting the bounding box (in lattitude/longitude or x/y) of current view since I need to display a grid fitting the whole view when zomming in and out.

**Comment by Pessimistress** [comment]
You can use [@turf/bbox](http://turfjs.org/docs/#bbox) to get the bounding box of a GeoJSON.

**Comment by HuyHoang-Ta** [comment]
This helps me get the current bounding box of my layer, but i need the full box for my screen (the white region)

![bbox](https://user-images.githubusercontent.com/61722520/96817272-31774400-1449-11eb-80ac-3483e09e8365.png)

**Comment by HuyHoang-Ta** [comment]
Hello, this is the solution I am using with React: [Render callbacks](https://deck.gl/docs/api-reference/react/deckgl#render-callbacks). In order to get the bounds, use [viewport.getBounds()](https://deck.gl/docs/api-reference/core/viewport#getbounds) which will return an array of coordinates (x/y for OrthographicView or latitude/longitude for MapView) 

Here is my result when using this (two red dot at top right and bottom left corner):

![bbox-fullview](https://user-images.githubusercontent.com/61722520/96821300-ca11c200-1451-11eb-8044-2c2bb037d624.png)
