### ISSUE TITLE
Grid layer and bearing

### ISSUE THREAD

**Issue by ricardoekm** [visgl/deck.gl#5057]
Is it possible to tell the grid layer to doesn't take the bearing into account or rotate it so it doesn't appear to be tilted when the map has a bearing parameter?

<img width="438" alt="grid_bearing" src="https://user-images.githubusercontent.com/747894/96788244-8e331a00-13c9-11eb-8101-544ed2651bad.png">

Thanks.

**Comment by Pessimistress** [comment]
GridLayer does not change orientation. You can look at ScreenGridLayer if you always want the grid to be aligned with the current view.

**Comment by ricardoekm** [comment]
Ok, gotcha. Thanks for the response! 

The only issue, in terms of experience, with the screengridlayer is that is hard for the user to keep tracking of what's going on when panning because the cells keep changing colors (because the points are moving on the screen).

Any idea on how to get a "static grid" that rotates with the map?

I've noticed [grid-aggregator](https://github.com/visgl/deck.gl/blob/fe5fe706945086394a7dca60dd527233eef1586b/modules/aggregation-layers/src/cpu-grid-layer/grid-aggregator.js#L89) has a _projectPoints_ parameter.

Perhaps if I pass projectPoints=true and a special viewPort?

**Comment by Pessimistress** [comment]
`ScreenGridLayer` is essentially aggregating projected points.

I think what you need is something like `cellOffset` on `ScreenGridLayer` (right now the grid always starts from top-left) so you can keep the grid stable relative to the map.

**Comment by ricardoekm** [comment]
ok, thanks for the help!
