### ISSUE TITLE
WMS Raster Layers?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#5058]
Was curious if there are any plans for a layer or loader that supports loading from WMS tile server sources?

I asked a similar [question](https://github.com/visgl/deck.gl/issues/4309) some time ago. @xintongxia mentioned loaders.gl supported 3D only at the time so wasn’t sure if anything had changed...

**Comment by kylebarron** [comment]
As long as the WMS server supports XYZ indexing (which I think they do by spec?) then you can easily pass the correct url to `getTileData`. Have you tried something like this?

**Comment by jfuehner** [comment]
@kylebarron it’s an ArcGIS serving up the WMS tiles. Where can I find documentation on the getTileData function or what would be a good example to look at?

**Comment by kylebarron** [comment]
https://deck.gl/docs/api-reference/geo-layers/tile-layer#gettiledata

**Comment by jfuehner** [comment]
@kylebarron thanks! So, your thinking is I should be able to use a custom TileLayer that overrides the getTileData to construct the appropriate url the WMS service expects?

**Comment by kylebarron** [comment]
Yes

**Comment by jfuehner** [comment]
@kylebarron I threw together a hardcoded custom TileLayer that overrides the getTileData function...

```
import {TileLayer} from '@deck.gl/geo-layers';
import {load} from '@loaders.gl/core';

export default class WmsTileLayer extends TileLayer {
  getTileData(tile) {
    const {props} = this;
    //const {data} = props;
    const {bbox} =  tile;
    const {east, north, south, west} = bbox;
    const urlQueryStringParams = {
        bbox: [west, south, east, north].join(','),
        format: 'image/png',
        height: 512,
        layers: ['Airports', 'Roads'].join(','),
        request: 'GetMap',
        service: 'WMS',
        srs: 'EPSG:4326',
        styles: '',
        version: '1.1.1',
        width: 512
    }
    const urlQueryString = Object.keys(urlQueryStringParams).map(key => key + '=' + urlQueryStringParams[key]).join('&');
    const url = 'https://ndgishub.nd.gov/arcgis/services/All_Transportation/MapServer/WMSServer';
    
    return load(url + '?' + urlQueryString)
  }
}

WmsTileLayer.layerName = 'WmsTIleLayer';
```
However, I am receiving the error; GeoJSON does not have type...

<img width="784" alt="Screen Shot 2020-10-23 at 6 33 11 PM" src="https://user-images.githubusercontent.com/1843941/97059411-5c06f100-155e-11eb-9513-ea06dab5cdd6.png">

I assume it is because I am not passing a proper loader to the loaders.gl `load` function?

**Comment by Pessimistress** [comment]
@jfuehner Please read the example on the documentation page. Your data is not a geojson and you are not specifying how it should be rendered.

**Comment by Pessimistress** [comment]
Also, `getTileData` is a TileLayer prop. You don't need to create a custom layer.

**Comment by jfuehner** [comment]
@Pessimistress I recognize my data is not geojson... I am trying to render image tiles from a WMS service. 

@kylebarron suggested I try using getTileData with a appropriately constructed WMS url format which I did.

Would you have a recommendation on how to connect to a WMS service?

**Comment by kylebarron** [comment]
Look at the example: https://github.com/visgl/deck.gl/blob/8.3-release/examples/website/map-tile/app.js

You don't need to subclass the TileLayer

**Comment by Pessimistress** [comment]
@jfuehner Let's try again. Go to the [documentation page](https://deck.gl/docs/api-reference/geo-layers/tile-layer) and read from the top. Your answer is in the second paragraph.

**Comment by jfuehner** [comment]
@Pessimistress @kylebarron My sincerest apologies, I totally understand now... I was making it way more complicated than it needed to be. 

I have it working wonderfully... Thanks for dealing with my ineptitudes :pensive: and really appreciate your patience.
