### ISSUE TITLE
No documentation or examples on IconLayer rotation

### ISSUE THREAD

**Issue by bbest-airmatrix** [visgl/deck.gl#5067]
When going through the IconLayer documentation I noticed there is an accessor function `getAngle` and even in the interactable example with a map of SF you can change the angle of the icons. However there is no documented attribute called `angle` that can be set when defining a layer. The View Code link on the website doesn't work so I wasn't able to see how the icons are being rotated. Can someone provide some insight on how to do this?

**Comment by Pessimistress** [comment]
The prop is called `getAngle`, not `angle`.
