### ISSUE TITLE
webgl uses canvas.toDataURL() without content

### ISSUE THREAD

**Issue by MyShallowTime** [visgl/deck.gl#5069]
https://deck.gl/examples/scatterplot-layer/
![image](https://user-images.githubusercontent.com/20198963/97248667-39662800-183d-11eb-839b-74fcb6e092f6.png)
This image without content.I found a solution online:
When getting the webgl object, pass in one more {preserveDrawingBuffer: true}, and then use canvas.toDataURL() to get it.
mapboxgl solves this problem。
![image](https://user-images.githubusercontent.com/20198963/97248594-189dd280-183d-11eb-96e0-8973b8fa00a0.png)
Can deck.gl support this parameter? Thanks.

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/issues/4436

**Comment by MyShallowTime** [comment]
> #4436

Thank you。
