### ISSUE TITLE
Shapefile to GeoJson

### ISSUE THREAD

**Issue by digiiitalmb** [visgl/deck.gl#5071]
How can I convert Shapefile to GeoJson?

From what I understand properties for shapes are stored in DBF file, and .shp file only contains the shape information.
Original GeoJson file is 140mb so naturally it takes much longer to download and I want to use .shp instead which is only 30 mb, but it's not exactly clear how I could either convert it back to Geojson that could be loaded into a layer.

Any help would be super appreciated.

**Comment by kylebarron** [comment]
This was recently added to loaders.gl https://loaders.gl/modules/shapefile/docs/api-reference/shapefile-loader. If you only want the shapes you can use the SHPLoader directly.

**Comment by digiiitalmb** [comment]
Hello Kyle, thanks for your answer, the thing is I want shapes and shape properties together.

```
import {SHPLoader} from '@loaders.gl/shapefile';
import {load} from '@loaders.gl/core';

load('/PEA.shp', SHPLoader).then(function(result) {
        
        console.log(result);
        //setMarkets(result);

});
```  

But the result doesn't seem to be an actual GeoJson here, so I'm not sure what needs to be done in order to convert it into GeoJson?

**Comment by digiiitalmb** [comment]
For the record files PEA.dbf, PEA.prj, PEA.sbn, PEA.sbx, PEA.shx exist in same dir as PEA.shp.

**Comment by kylebarron** [comment]
Use the `ShapefileLoader`

**Comment by digiiitalmb** [comment]
@kylebarron thanks for this, now I do get GeoJson

My bad for not understanding the diff between SHPLoader and ShapefileLoader

I do see PEA.cpg 404 error in console, even though that file is optional. So maybe that's something that should be looked into.

**Comment by kylebarron** [comment]
That file describes the text encoding for the DBF. When it exists it needs to be read, but for remote datasets, you can't know if it exists unless you try to load it.
