### ISSUE TITLE
Using <NavigationControl/> component  error cannot read 'bearing' of null

### ISSUE THREAD

**Issue by digiiitalmb** [visgl/deck.gl#5073]
I want to see compass on the map, but when I try to load in the  <NavigationControl /> controller I get following error
`Uncaught TypeError: Cannot read property 'bearing' of null`

This is my import

`import MapGL,{NavigationControl} from 'react-map-gl';`

This is how my JSX is looking like this

<DeckGL
      layers={layers}
      initialViewState={INITIAL_VIEW_STATE}
      controller={true}
      getTooltip={getTooltip}
      onClick={handleClick}
    > 
      <StaticMap
        reuseMaps
        mapStyle={mapStyle}
        preventStyleDiffing={true}
        mapboxApiAccessToken={MAPBOX_TOKEN}
      />
      <NavigationControl />
</DeckGL>  

Bearing is set in initialViewState

**Comment by Pessimistress** [comment]
Use the bug template if you want to report a bug. Otherwise use the question template.

**Comment by bplmp** [comment]
@digiiitalmb my guess is you're not putting the `NavigationControl` **inside** the `MapGL` component.

You might be doing this: 

```js
<MapGL
  {...viewport}
  width="100%"
  height="100%"
  mapStyle="mapbox://styles/mapbox/dark-v9"
  onViewportChange={setViewport}
  mapboxApiAccessToken={MAPBOX_TOKEN}
/>
<NavigationControl />
``` 

When you should actually be doing this:

```js
<MapGL
  {...viewport}
  width="100%"
  height="100%"
  mapStyle="mapbox://styles/mapbox/dark-v9"
  onViewportChange={setViewport}
  mapboxApiAccessToken={MAPBOX_TOKEN}
>
  <NavigationControl />
</MapGL>
```
