### ISSUE TITLE
Set map margins

### ISSUE THREAD

**Issue by ariel262626** [visgl/deck.gl#5074]
I'm trying to set margins on the map container but nothing works for me.

`    <div style={{margin: "0 1rem"}}>
      <DeckGL
        layers={[layers]}
        initialViewState={{ ...viewport }}
        width={`${width}%`}
        height={"80%"}
        controller={true}
      >
        <StaticMap
          height="100%"
          width="100%"
          mapStyle="******"
          mapboxApiAccessToken={******}
        />
      </DeckGL>
    </div>`

In my case, I need to show 2 maps on the same page with margins between them, I tried to change the width and height of the parent div but it seems the map just ignore it.

**Comment by alasarr** [comment]
You could try something like this:

```js 
const style = {
  margin: "10px"
};
<div className="mapContainer">
      <DeckGL
        id="map1"
        style={style}
        controller={true}
        initialViewState={INITIAL_VIEW_STATE}
      >
        <StaticMap
          height="100%"
          width="100%"
          mapStyle="https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"
        />
      </DeckGL>
    </div>
```

**Comment by ariel262626** [comment]
> You could try something like this:
> 
> ```js
> const style = {
>   margin: "10px"
> };
> <div className="mapContainer">
>       <DeckGL
>         style={style}
>         controller={true}
>         initialViewState={INITIAL_VIEW_STATE}
>       >
>         <StaticMap
>           height="100%"
>           width="100%"
>           mapStyle="https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"
>         />
>       </DeckGL>
>     </div>
> ```

It doesn't work, the maps still overlapping

**Comment by Pessimistress** [comment]
The parent container needs `position: relative` if Deck's width and height are relative.

**Comment by ariel-upstream** [comment]
> The parent container needs `position: relative` if Deck's width and height are percentages relative to the container.
> 
> You can also use the [style](https://deck.gl/docs/api-reference/core/deck#style) prop.

I tried that of course but the issue is that it crashed when I try to set the parent container to `position: relative`

**Comment by Pessimistress** [comment]
I can't tell you what's wrong with the description you provided. Can you create a CodeSandbox?

**Comment by ariel-upstream** [comment]
> I can't tell you what's wrong with the description you provided. Can you create a CodeSandbox?

https://codesandbox.io/s/map-relative-container-ojvyt

**Comment by Pessimistress** [comment]
Your container div does not have a height assigned. DeckGL canvas by default has `position: absolute` so that it can use percentage width and height. If the parent's height is 0 then `height: '40%'` is 0. You can see how the layout works by inspecting the page elements in the console. 

You can overwrite the default `position` value with the `style` prop if you want. If you are still confused, replace `<DeckGL>` with `<div>` using the same style in your example and see if your style really gets you what you need. What you have is a CSS issue.

**Comment by ariel262626** [comment]
> I can't tell you what's wrong with the description you provided. Can you create a CodeSandbox?

https://codesandbox.io/s/map-relative-container-ojvyt
