### ISSUE TITLE
Polygon layer fill should not update when line color update triggers change

### ISSUE THREAD

**Issue by heshan0131** [visgl/deck.gl#5085]
#### Description
When I use PolygonLayer and provide getLineColor accessor and its updateTriggers, polygon layer renders PathLayer, passing getLineColor -> getColor. Change of lineColor triggers should only update the PathLayer, it should not cause the solid polygon layer to update...

<img width="620" alt="Screen Shot 2020-10-29 at 10 22 24 PM" src="https://user-images.githubusercontent.com/3605556/97662802-3a61aa00-1a35-11eb-9782-81ef31b777f8.png">

**Comment by Pessimistress** [comment]
Fixed in 8.3.5
