### ISSUE TITLE
3d tiles are invisible at some view angles

### ISSUE THREAD

**Issue by xiemeilong** [visgl/deck.gl#5090]
#### Description
3d tile will be invisible when bearing of viewstate is bewteen 45 and 86  in some where.
It should be always visible.

#### Repro Steps
https://codepen.io/xiemeilong/pen/yLJjPJW

#### Environment (please complete the following information):
 - latest
 - Chrome 85
 - OS: windows 10

**Comment by ibgreen** [comment]
@vdunaev Can you see if this is reproducible on our end?

**Comment by belom88** [comment]
I gathered some clues on this issue:

- It is not related to bearing. I tried `bearing` equals to 15, 30, 90 - the same result;
- Something wrong with test dataset in the sandbox (https://codepen.io/xiemeilong/pen/yLJjPJW);
-- If I try well-known NewYork tileset (https://assets.cesium.com/75343/tileset.json token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1OGEwZjIzMi0yZjg1LTQyOWItYmY0ZC05ZWIxOWY2NGYwMzEiLCJpZCI6MjYxMzMsInNjb3BlcyI6WyJhc3IiLCJnYyJdLCJpYXQiOjE1ODczMTUxNzR9.XC1i5MXBtMiapKvoClMMH-KkjxNZtGhQiPiJif4RzJ4), it is shown on a map correctly:
![Screenshot from 2020-12-04 11-55-27](https://user-images.githubusercontent.com/18549629/101143764-679f0a80-3628-11eb-8687-9310065724a3.png)
-- I tried your tileset (96188) with "@loaders.gl/examples/website/3d-tiles" application. It is located somewhere in Pacific Ocean (long/lat: 179.99857,-1.49646):
![Screenshot from 2020-12-04 11-56-06](https://user-images.githubusercontent.com/18549629/101143931-a92fb580-3628-11eb-8369-196161a6dd96.png)
