### ISSUE TITLE
Still facing issue raised under #5014 (Sometimes plot markers are missing when exporting as image)

### ISSUE THREAD

**Issue by vivek091195** [visgl/deck.gl#5091]
I am setting glOptions upon initialization of GoogleMapsOverlay, but still observing the issue randomly.

```
    const deckGlProps = {
      glOptions: {
        preserveDrawingBuffer: true
      }
    };
    this.mapOverlay = new GoogleMapsOverlay(deckGlProps);
    this.mapOverlay.setMap(this.map);
```

Is there anything else that I might be missing? Sometimes, it works fine but in some instances, the plot markers are missing.

**Comment by Pessimistress** [comment]
Reopened #5014

Please do not open duplicate issues.
