### ISSUE TITLE
LightingEffect is not working on Tile3DLayer

### ISSUE THREAD

**Issue by xiemeilong** [visgl/deck.gl#5094]
#### Description
LightEffect is  not working on 3d Tile layers.

#### Repro Steps
https://codepen.io/xiemeilong/pen/oNLyMez

#### Environment (please complete the following information):
 - Framework Version: latest
 - Browser Version: Chrome 85
 - OS: Windows 10

**Comment by Pessimistress** [comment]
Please add your code to repro steps.

**Comment by Pessimistress** [comment]
See https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer#_lighting
