### ISSUE TITLE
Add distance support to PointLight

### ISSUE THREAD

**Issue by xiemeilong** [visgl/deck.gl#5097]
#### Target Use case
hight light a limited  region of 3dtile layer, not all 

#### Proposed feature
Add distance parameters  to PointLight.  for example, [PointLight in threejs](https://threejs.org/docs/#api/en/lights/PointLight) 
distance - Maximum range of the light.

**Comment by Pessimistress** [comment]
I do not understand this request. Please describe the feature in full sentences, add a sample code snippet, and screenshots illustrating the desired effect.
