### ISSUE TITLE
The deck.gl page is very slow on iPhone 12 Pro

### ISSUE THREAD

**Issue by nagix** [visgl/deck.gl#5101]
#### Description
The deck.gl page that draws 10,000 GeoJSON LineStrings is very slow with any browser on iPhone 12 Pro. There is no performance issue with the same browser/OS versions on my old iPhone 8 Plus.

#### Repro Steps
CodePen: https://codepen.io/nagixx/full/rNLZWew

#### Environment:
 - Framework Version: deck.gl 8.3.6 and Mapbox GL JS 1.12.0
 - Browser Version: Safari 14, Chrome (for iOS) 86.0.4240.93 and FireFox (for iOS) 29.1
 - OS: iOS 14.1 and 14.2

**Comment by Pessimistress** [comment]
The actual pixels rendered is determined by two factors:
- The client pixel width/height of the map. For optimal mobile experience you need to inform the browser with a [viewport meta tag](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design#The_viewport_meta_tag)
- Multiplied by the device pixel ratio. You can control this behavior via [useDevicePixels](https://deck.gl/docs/api-reference/core/deck#usedevicepixels)

**Comment by nagix** [comment]
Thank you for your comment @Pessimistress. I tried every combination from viewport meta  tag values, `useDevicePixels` values and with/without iframe, however, I still see a large performance difference (iPhone 12 Pro is slow).

CodePen: https://codepen.io/nagixx/full/rNLZWew (viewport: `"width=device-width, initial-scale=1"`, `useDevicePixels`: `false`, iframe)
Normal web page: https://www.nagi-p.com/v1/x/deck.html (viewport: `"width=device-width, initial-scale=1"`, `useDevicePixels`: `false`, non-iframe)

**Comment by nagix** [comment]
Resolution of iPhone 12 Pro is slightly larger than iPhone 8 Plus, but it doesn't explain the performance gap.
- iPhone 8 Plus: 1,920x1,080 pixels (401 ppi, -webkit-device-pixel-ratio : 3)
- iPhone 12 Pro: 2,532x1,170 pixels (460 ppi, -webkit-device-pixel-ratio : 3)

**Comment by Pessimistress** [comment]
Thank you for these tests. I have a SE 2020 and all the above links run fine. Any chance you can connect it with a computer and capture some performance profiles? Do you see similar discrepancies with all the [website examples](https://deck.gl/examples), or just some of them?

**Comment by nagix** [comment]
Regarding the [examples](https://deck.gl/examples), iPhone 12 Pro is far slower in:
- ArcLayer
- GeoJsonLayer (Polygons)
- GeoJsonLayer (Paths)
- HexagonLayer
- LineLayer
- ScenegraphLayer
- Tile3DLayer
- TripsLayer
- 3D Plot
- CARTO
- Mapbox
- DataFilterExtension
- Playground

Almost same performance in:
- ContourLayer
- HeatmapLayer
- IconLayer
- TerrainLayer
- TextLayer
- TileLayer
- TileLayer (Non-geospatial)
- ArcGIS
- Google Maps

iPhone 12 Pro is faster:
- PointCloudLayer
- ScatterplotLayer
- ScreenGridLayer
- BrushingExtension

**Comment by Pessimistress** [comment]
I don't see any immediate pattern. We've seen issues in past updates of iOS Safari (all browsers use WebKit under the hood) but it is odd that this is device-specific.

Could you join the Slack for more discussion? You can find the link in the repo README.

**Comment by nagix** [comment]
Ok, I just join the Slack workspace. I will share the profiling data from both iPhone 12 Pro and 8 Plus.

**Comment by nagix** [comment]
From the further investigation, it is found that WebGL instanced draw calls are slow, and it's likely the cause of the issue. Actually, this example in https://medium.com/@pailhead011/instancing-with-three-js-part-2-3be34ae83c57 is far slower on iPhone 12.

I opened a bug ([Bug 218949](https://bugs.webkit.org/show_bug.cgi?id=218949)) on WebKit Bugzilla.

**Comment by nevets963** [comment]
@nagix were you able to get any response from Apple about this issue? It looks like the issue still persists in iOS 14.6 :(

**Comment by nagix** [comment]
Unfortunately, I didn’t get any response about this issue.

**Comment by tech-meppem** [comment]
Investigating more, I found found that there may be problems with instance drawing on webgl, iPhone.
I tried to disable instancing completely (inside luma.gl, by editing the Model class constructor, via editing the props passed in).
This works on desktop, with a couple of rendering errors.
However, on iPhone, it causes the page to completely crash and fail.

**Comment by ibgreen** [comment]
While a solution to the iOS 14 performance issue would indeed be to implement a non-instanced rendering mode, deck.gl is heavily based on instanced rendering and implementing (and maintaining!) separate code paths for non-instanced rendering would be a significant burden.

While it is disappointing that Apple hasn't addressed the open bug on instancing performance in iOS 14, the good news is that iOS 15 is coming with [a new ANGLE based WebGL backend](https://developer.apple.com/safari/technology-preview/release-notes) (same backend that other browsers are using) so there is good hope that this will fix the instancing performance issue. 

Therefore we are deferring any decisions on non-instanced support until we see how things work on iOS 15.

If you are able to give the iOS 15 preview a test spin, let us know.

**Comment by nagix** [comment]
Today I updated my iPhone 12 Pro to iOS 15, and I confirmed that this instancing performance issue was fixed! At least, my application and deck.gl examples all work smoothly, so I close this issue.
