### ISSUE TITLE
Icon Layer - iconAtlas if and how to use

### ISSUE THREAD

**Issue by ariel262626** [visgl/deck.gl#5104]
Hi,
I'm trying to figure out if I should use the iconAtlas file, 
If I have 4 icons to draw how the iconAtlas will be? 
What is the difference if I statically import my icons and then use them or create the iconAtlas method?

Thanks in advance!

**Comment by Pessimistress** [comment]
> You can pre-generated a sprite image (iconAtlas), which packs all your icons into one layout, and a JSON descriptor (iconMapping), which describes the position and size of each icon in the iconAtlas. You can create sprite images with tools such as [TexturePacker](https://www.codeandweb.com/texturepacker). This is the most efficient way to load icons.

https://deck.gl/docs/api-reference/layers/icon-layer
