### ISSUE TITLE
IconLayer Binary Attributes?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#5106]
Hi! I was looking into using the [IconLayer](https://deck.gl/docs/api-reference/layers/icon-layer) with binary attributes.

Hoping someone can provide a bit more clarification on the section regarding binary attributes from the docs...

“If data.attributes.getIcon is supplied, since its value can only be a typed array, iconMapping can only use integers as keys.”

Would there be an example of what the `iconMapping` data structure needs to look like for binary attributes?

Assuming I supply `getIcon` as TypedArray of integers representing the binary icon image data...

**Comment by Pessimistress** [comment]
> Assuming I supply getIcon as TypedArray of integers representing the binary icon image data...

`getIcon` is supposed to contain icon ids, not image data.

**Comment by jfuehner** [comment]
@Pessimistress I see, thanks for clearing that up. Sounds like I can’t use binary attributes for my use case with `getIcon`.

Does the `getIcon` function support a object URL’s?

Basically, I have a use-case where I am receiving a base64 encoded image/icon and need to render it. Was thinking the `IconLayer` would be the appropriate layer.

**Comment by Pessimistress** [comment]
Please read https://deck.gl/docs/api-reference/layers/icon-layer#example-auto-packing-iconatlas

The point of supplying binary data is to bypass CPU processing and directly upload your data to the GPU. There is no point doing so in your case because the icon atlas has to be laid out on the CPU.
