### ISSUE TITLE
@deck.gl/arcgis - DeckRender flickering on iOS

### ISSUE THREAD

**Issue by pnellius-akqa-cfa** [visgl/deck.gl#5108]
#### Description
Map flickers when the user touches the map on iOS while using `DeckRenderer` when using Vue

#### Repro Steps
- Create a Vue app
- Create a DeckRenderer map using 'local' mode
- Use a vector map
- Instantiate in `mounted()`

#### Environment (please complete the following information):
- @deck.gl/arcgis
- Vue 2.6.11 using vue-cli
- iOS 14, iPhone 8 (Xcode Simulator), iPhone X (real device), iPhone 12
- Safari

Full screen example:
https://nenq7.csb.app

Code:
https://codesandbox.io/s/distracted-cray-nenq7?file=/src/components/MapTest.vue

#### Logs
No errors

**Comment by Pessimistress** [comment]
I cannot reproduce this issue on my iPhone (SE 2020). Can you make a screen capture?

Is the issue still there if you remove `DeckRenderer`?

**Comment by pnellius-akqa-cfa** [comment]
Here is the issue (still with `DeckRenderer`) on an iPhone 11
https://drive.google.com/file/d/1gRTlLvRy7X4DyI0usxWBTaHhvl-VAeZg/view?usp=sharing

I'm going to use DeckLayer next and see if the issue still persists...

**Comment by pnellius-akqa-cfa** [comment]
Also of note - if I add a scatterplot layer with lots more points, the issue gets worse. Flickering appears most on zooming in/out

**Comment by pnellius-akqa-cfa** [comment]
Ok, I have been able to reproduce this issue sans-deck.gl. It appears to be an issue with arcGIS. I'm going to close this here.
