### ISSUE TITLE
Problem installing for Jupyter Lab: 'DECKGL_SEMVER' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by pybokeh** [visgl/deck.gl#5109]
I am following the instructions [here](https://pydeck.gl/installation.html) for Jupyter Lab:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
DECKGL_SEMVER=`python -c "import pydeck; print(pydeck.frontend_semver.DECKGL_SEMVER)"`
jupyter labextension install @deck.gl/jupyter-widget@$DECKGL_SEMVER
```
For that 2nd line, I get the following error:
'DECKGL_SEMVER' is not recognized as an internal or external command

This is a strange command to execute.  I thought perhaps it is an environment variable that needs to be set.  So on Windows I tried:
```
set DECKGL_SEMVER='python -c "import pydeck; print(pydeck.frontend_semver.DECKGL_SEMVER)"'
```

But when I then do:
```
jupyter labextension install @deck.gl/jupyter-widget@$DECKGL_SEMVER
```

I get the following error:
```
An error occured.
ValueError: "@deck.gl/jupyter-widget@$DECKGL_SEMVER" is not a valid npm package
See the log file for details:  C:\Users\your_username\AppData\Local\Temp\jupyterlab-debug-_q8w72gn.log
```

Windows 10, Python 3.8, node version 14.15.0 and npm version 6.14.8

**Comment by kylebarron** [comment]
Hmm maybe the docs were written with Mac/Unix in mind. I don't know Windows well, but yes, that's intended to be an environment variable you set.

We should update the docs but in the meantime you should be able to avoid the environment variable by running the command directly and pasting it on the next line, e.g. on my Mac:

```
> python -c "import pydeck; print(pydeck.frontend_semver.DECKGL_SEMVER)"
~8.2.*
> jupyter labextension install "@deck.gl/jupyter-widget@~8.2.*"
Building jupyterlab assets (build:dev:minimize)
```

(because of the shell I use, I need quotes when I paste those characters)

**Comment by ajduberstein** [comment]
What @kylebarron says is true–the instructions are for Mac/Unix. I'll update the docs.

**Comment by pybokeh** [comment]
Thanks for the helpful replies.  The workaround has worked for me.
