### ISSUE TITLE
help:how to rotate and align viewport horizontally based on feature?

### ISSUE THREAD

**Issue by aubeena007** [visgl/deck.gl#5111]
![screenshot-localhost_8080-2020 11 02-17_49_29](https://user-images.githubusercontent.com/69108888/97870858-94b28180-1d39-11eb-907f-b7f4944c1eb6.png)
 am drawing a rectangle using nebula gl on deck gl.
as soon i draw i need to rotate view-port into horizontal also zoom more and align center like below image
![screenshot-localhost_8080-2020 11 02-18_03_10](https://user-images.githubusercontent.com/69108888/97871051-ea872980-1d39-11eb-866d-639beb9dc779.png)

**Comment by Pessimistress** [comment]
You can use [WebMercatorViewport.fitBounds](https://deck.gl/docs/api-reference/core/web-mercator-viewport#fitbounds) to find the center and zoom for your feature. Then rotate it by adding a bearing:

```js
const viewport = new WebMercatorViewport({width, height});

// Assume your feature is a polygon
const coordinates = feature.geometry.coordinates[0];

const minLng = Math.min(...coordinates.map(p => p[0]));
const minLat = Math.min(...coordinates.map(p => p[1]));
const maxLng = Math.max(...coordinates.map(p => p[0]));
const maxLat = Math.max(...coordinates.map(p => p[1]));
const {longitude, latitude, zoom} = viewport.fitBounds([[minLng, minLat], [maxLng, maxLat]]);

const cornerA = viewport.projectPosition(coordinates[0]);
const cornerB = viewport.projectPosition(coordinates[1]);
const bearing = -Math.atan2(cornerB[1] - cornerA[1], cornerB[0] - cornerA[0]) / Math.PI * 180;

setViewState({longitude, latitude, zoom, bearing});
```
