### ISSUE TITLE
Enable picking for CompositeLayer but disable for sublayers ?

### ISSUE THREAD

**Issue by manzt** [visgl/deck.gl#5113]
We have been working on creating a `CustomGridLayer` (for [Viv](https://github.com/hms-dbmi/viv)) which is a `CompositeLayer` comprised of a grid of `n * m` small sublayers (https://github.com/hms-dbmi/vizarr/pull/43). 

![image](https://user-images.githubusercontent.com/24403730/98728240-39027c80-2367-11eb-872f-0b6c486a6aaa.png)

With so many sublayers, we are running into an issue with too many pickable layers. For our purposes, we really just need the coordinates for a mouse hover/click on the `CompositeLayer` and not picking info from the sublayers. Is it possible to enable picking (or just mouse events?) for the `CompositeLayer` and disable for the sublayers?

I've tried `layer = new CustomGridLayer({ ...props, pickable: true })` and setting `pickable: false` in the sublayer constructors (within `CustomGridLayer.renderLayers`, but this seems to disable any picking events. Thanks for the help in advance!

cc: @will-moore

**Comment by Pessimistress** [comment]
> I've tried layer = new GridLayer({ ...props, pickable: true }) and setting pickable: false in the sublayer constructors (within GridLayer.renderLayers), but this seems to disable any picking events.

You need at least one sublayer to be pickable. The composite layer itself doesn't render anything, so if you disable picking for all sublayers, no picking events will be fired.

If you are going to render many instances of the `CustomGridLayer`, you will eventually still run into the picking limit (max 255 layers). Alternatively, you can set `pickable: false` on your `CustomGridLayer`, and then render a single [GridCellLayer](https://deck.gl/docs/api-reference/layers/grid-cell-layer) with one square behind each `CustomGridLayer` that is the picking target.

**Comment by manzt** [comment]
Ah, I see. Thank you for the help! Since our `CustomGridLayer` is does not have a square `cellSize` I don't know if `GridCellLayer` will work. I'm going to try a single `SolidPolygonLayer` to create a large picking target and then calculate which grid item was clicked using `info.coordinates` in `CustomGridLayer.getPickingInfo`

**Comment by Anand2489** [comment]
I ran into similar issue when using multiple layers with the following arrangements

1. TileLayer -- [pickable = true]
2. PathLayer -- [pickable = false]
     Renders data of length = 1 always
3. LinkClusterLayer -- Composite Layer
    a. PathLayer -- [pickable = true] & renders data of length ~ 4k
    b. TextLayer -- [pickable = false] & renders data of length ~ 4k
4. IconClusterLayer -- Composite Layer
    a. IconLayer -- [pickable = true] & renders data of length ~ 4k
    b. TextLayer -- [pickable = false] & renders data of length ~ 4k


Can we run into `too many pickable layers` issues even in case DeckGL provided Core layers are used ?
