### ISSUE TITLE
Icon layer issue when using icons of small size ( border in grey color issue)

### ISSUE THREAD

**Issue by sachin156** [visgl/deck.gl#5116]
I am using icon layer with png for representing the blue color image in ArcGIS maps.

But whenever the size of icon is very small the icon is displaying with grey color border where as there is no border in the original image and as the icon size is very small  the whole image is getting dominated by the grey color.

I am attaching the image of what actually I am using and how it displays on map when size is small.

![iconlayer_grey](https://user-images.githubusercontent.com/25587702/98812333-4a6f8580-2448-11eb-9b15-ae5ac99d2f82.PNG)

![arrow_blue](https://user-images.githubusercontent.com/25587702/98812361-5fe4af80-2448-11eb-8c81-d053ea64920d.png)

Below is the sample code I am using

let iconlayer = new IconLayer({
      id: 'icon-layer',
      data: this.icondata,
      pickable: true,
      getIcon: d => ({
        url: d.iconurl,
        width: 128,
        height: 128
      }),
      sizeScale:7,
      getPosition: d => d.coordinates,
      getSize: this.view.zoom-14,
      getAngle: d => getIconAngle(d.pointA, d.pointB),
      updateTriggers: {
        getSize:this.view.zoom,
      },
    });

**Comment by Pessimistress** [comment]
Please fill in the bug template if you wish to report a bug.
