### ISSUE TITLE
Icon layer when using icons of small size

### ISSUE THREAD

**Issue by sachin156** [visgl/deck.gl#5117]
I am using icon layer with png for representing the blue color image in ArcGIS maps.

But whenever the size of icon is very small the icon is displaying with grey color border where as there is no border in the original image and as the icon size is very small the whole image is getting dominated by the grey color.

Below is the sample code I am using

let iconlayer = new IconLayer({
id: 'icon-layer',
data: this.icondata,
pickable: true,
getIcon: d => ({
url: d.iconurl,
width: 128,
height: 128
}),
sizeScale:7,
getPosition: d => d.coordinates,
getSize: this.view.zoom-14,
getAngle: d => getIconAngle(d.pointA, d.pointB),
updateTriggers: {
getSize:this.view.zoom,
},
});

Images that I am originally using and the one which is showing up on the map (after decreasing the size).

![blue_arrow](https://user-images.githubusercontent.com/25587702/98819927-7e9c7380-2453-11eb-9ff1-74f9cb77dd99.png)

![iconlayer_grey](https://user-images.githubusercontent.com/25587702/98819834-63316880-2453-11eb-924f-88a1e968d3bd.PNG)

Any Suggestions would be helpful on how to get the same color as the original one , Thanks in Advance.

**Comment by Pessimistress** [comment]
What version are you using? A bug was fixed in 8.3.0, see #2169

**Comment by sachin156** [comment]
@Pessimistress ,I  have changed the version to 8.3.0 but still I am getting the issue , I am not sure why this might be the problem. Thanks for the reply

**Comment by Pessimistress** [comment]
Can you try the `loadOptions` prop as suggested in https://github.com/visgl/deck.gl/issues/2169#issuecomment-704585080

**Comment by sachin156** [comment]
Used the below snippet in the icon layer

loadOptions: {
        imagebitmap: {
          premultiplyAlpha: 'none'
        }
    }  

but still the issue is same.

**Comment by Pessimistress** [comment]
Please create a Codepen/CodeSandbox that illustrates your issue.

**Comment by sachin156** [comment]
Sorry for the late response , here is the codepen https://codepen.io/sachin15/pen/pobqrVO

**Comment by Pessimistress** [comment]
@sachin156 The png you use in the Codepen is colored in gray. Did you mean to use a different image?

If you just need the image for its shape then you can always use the [mask mode](https://deck.gl/docs/api-reference/layers/icon-layer#iconmapping):

```
  getIcon: d => ({
    url: 'https://image.flaticon.com/icons/png/512/130/130884.png',
    width: 128,
    height: 128,
    mask: true
  }),
  getColor: [0, 0, 255],
```

**Comment by sachin156** [comment]
@Pessimistress Thanks a lot, for quick response and it solved my issue.
