### ISSUE TITLE
How could I use ScenegraphLayer with gltf module move from one position to another position(COORDINATE_SYSTEM.METER_OFFSETS) 

### ISSUE THREAD

**Issue by Mrrabbitan** [visgl/deck.gl#5119]
Data format:
 * [
 *   {name: 'Colma (COLM)', address: '365 D Street, Colma CA 94014', exits: 4214, coordinates: [-122.466233, 37.684638]},
 *   ...
 * ]

const result = data.map((i) => {
//relative position around coordinateOrigin
    return { name: 'Colma', address: '1', exits: 4214, coordinates: [i?.center[0], i?.center[1]] }
  })

const sceneLayer = new ScenegraphLayer({
    id: 'mkz-layer' + Math.random(),
    data: result,
    _lighting: 'pbr',
    streamName: '/car/position',
    coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS,
    coordinateOrigin: [0, 0, 0],
    scenegraph: cone,
    _animations: {
      '*': { speed: 5, playing: true },
    },
    sizeScale: 1,
    getOrientation: [0, 90, 90],
    getPosition: [0, 0, 0],
    getTranslation: (d) => (d?.coordinates == undefined ? [0, 0, 0] : d.coordinates),
  })

**Comment by Mrrabbitan** [comment]
with above codes the module just stay under the anchor position ,cant move anymore

**Comment by ibgreen** [comment]
Since it is the same translation for all rows, then `modelMatrix` prop is more efficient.

If you change an accessor, you need to use the `updateTriggers` mechanism to ensure the attribute is recalculated.

A quick search on those two terms in the deck.gl docs should get you up to speed.

**Comment by Mrrabbitan** [comment]
> Since it is the same translation for all rows, then `modelMatrix` prop is more efficient.
> 
> If you change an accessor, you need to use the `updateTriggers` mechanism to ensure the attribute is recalculated.
> 
> A quick search on those two terms in the deck.gl docs should get you up to speed.

@ibgreen 
Thanks alot for your quick response, ScenegraphLayer it’s a great feature，after solved this question ,I will paste the anwser,and then Close the comment

**Comment by Pessimistress** [comment]
`getTranslation` must return a 3D vector in meters. You are returning `d.coordinates` which is 2D in longitude-latitude.

See [documentation](https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer#gettranslation)
