### ISSUE TITLE
Passing local url of texture/height to terrain layer doesn't work

### ISSUE THREAD

**Issue by danielXr** [visgl/deck.gl#5121]
#### Description
I'm trying to load the TerrainLayer with locally VTs (taken from the example in deck.gl site, png, file:///the_location_in_my_pc.png)
When providing the original url of the same file, it works like a charm.
#### Repro Steps
This works:
```
import pydeck as pdk
import os

# Define how to parse elevation tiles
ELEVATION_DECODER = {"rScaler": 2, "gScaler": 0, "bScaler": 0, "offset": 0}
elevation_data = '"https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/terrain.png"'
texture_data = '"https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/terrain-mask.png"'
# elevation_data = '"file:///Users/daniel/PycharmProjects/mwi/tmp_files/terrain_sample_img/terrain.png"'
# texture_data = '"file:///Users/daniel/PycharmProjects/mwi/tmp_files/terrain_sample_img/terrain-mask.png"'
bounds = [-122.5233, 37.6493, -122.3566, 37.8159]
    


terrain_layer = pdk.Layer(
    "TerrainLayer", data=None, 
    elevation_decoder=ELEVATION_DECODER, 
    texture=texture_data, 
    elevation_data=elevation_data, 
#     elevation_decoder=el_decoder, 
#     texture=texture_img, 
#     elevation_data=heights_img, 
    bounds=bounds
)

view_state = pdk.ViewState(latitude=37.6493, longitude=-122.5233, zoom=11.5, bearing=140, pitch=60)

r = pdk.Deck(terrain_layer, initial_view_state=view_state, map_style='')


r.show()
```
Download the images and give it a try - doesn't work:
```
import pydeck as pdk
import os

# Define how to parse elevation tiles
ELEVATION_DECODER = {"rScaler": 2, "gScaler": 0, "bScaler": 0, "offset": 0}
#elevation_data = '"https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/terrain.png"'
#texture_data = '"https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/terrain-mask.png"'
elevation_data = '"file:///Users/daniel/PycharmProjects/mwi/tmp_files/terrain_sample_img/terrain.png"'
texture_data = '"file:///Users/daniel/PycharmProjects/mwi/tmp_files/terrain_sample_img/terrain-mask.png"'
bounds = [-122.5233, 37.6493, -122.3566, 37.8159]
    


terrain_layer = pdk.Layer(
    "TerrainLayer", data=None, 
    elevation_decoder=ELEVATION_DECODER, 
    texture=texture_data, 
    elevation_data=elevation_data, 
#     elevation_decoder=el_decoder, 
#     texture=texture_img, 
#     elevation_data=heights_img, 
    bounds=bounds
)

view_state = pdk.ViewState(latitude=37.6493, longitude=-122.5233, zoom=11.5, bearing=140, pitch=60)

r = pdk.Deck(terrain_layer, initial_view_state=view_state, map_style='')


r.show()
```

#### Environment:
 - Framework Version: pydeck 0.5.0
- Jupyter notebook 5.7.10
 - OS: Mac OS X 10.15.7

**Comment by Pessimistress** [comment]
The current pydeck release does not support local image files. You need to convert the image to a DataURL: https://github.com/visgl/deck.gl/issues/4977

There is a pending feature request to make it easier.

**Comment by kylebarron** [comment]
I think this is just due to web browsers not being able to access local files. If you start a local web server it'll probably work, e.g.:
```
cd /Users/daniel/PycharmProjects/mwi/tmp_files/terrain_sample_img/
python -m http.server
```
Then I think pydeck should be able to access `http://localhost:8000/terrain.png` and `http://localhost:8000/terrain_mask.png`

**Comment by danielXr** [comment]
@kylebarron , I have tried that and it also didn't work...
@Pessimistress , it seems that the issue you mentioned is different and was already solved.

This is a real setback - this makes the TerrainLayer for those having their own VTs not really useful.. :(

**Comment by danielXr** [comment]
Consulted with a fried and he managed to fix the issue by adding and enabling a CORS extension (CROSS DOMAIN).
As I understand google extensions a basically spy software, It is only a temporal solution....

@Pessimistress  any idea when TerrainLayer will support local URLs?

**Comment by Pessimistress** [comment]
@danielXr have you tried the data URL solution?

cc @ajduberstein

**Comment by danielXr** [comment]
@Pessimistress , it would be nice if you can provide o snippet on how to do this.
I tried doing with requests lib but it doesn't support local files...

**Comment by kylebarron** [comment]
> Consulted with a fried and he managed to fix the issue by adding and enabling a CORS extension (CROSS DOMAIN).

This means that it does work with local files, but you had a CORS issue... I thought that `localhost` was considered the same host for any port extension, so that you can access `localhost:8000` without issue from the default Jupyter port (`localhost:8888`)

**Comment by Pessimistress** [comment]
@danielXr It is in the description of the issue that I linked.

```python
import base64
image = 'data:image/jpeg;base64,'+ str(base64.b64encode(open("/path/to/file", "rb").read()).decode('utf-8'))
```

Then

```python
elevation_data = '"' + image + '"'
```
