### ISSUE TITLE
MVTLayer tiles can disappear at poles and extreme angles when using GlobeView

### ISSUE THREAD

**Issue by robhawkes** [visgl/deck.gl#5124]
#### Description

- When combining `MVTLayer` and `GlobeView` some tiles are removed / not loaded depending on zoom and angle of view
- This seems to only occur at the poles, or when zoomed in and viewing the globe at an extreme angle
- Adding the following to `getBounds()` in `globe-viewport` has helped with the poles issue, but not the extreme angles
```javascript
getBounds(options = {}) {
  const unprojectOption = {targetZ: options.z || 0};

  const left = this.unproject([0, this.height / 2], unprojectOption);
  const top = this.unproject([this.width / 2, 0], unprojectOption);
  const right = this.unproject([this.width, this.height / 2], unprojectOption);
  const bottom = this.unproject([this.width / 2, this.height], unprojectOption);

  if (right[0] < this.longitude) right[0] += 360;
  if (left[0] > this.longitude) left[0] -= 360;

  // START HACK: Temporary hack to stop tiles disappearing when looking down at poles
  if (Math.abs(180 - (Math.abs(top[0]) + Math.abs(bottom[0]))) < 5) {
    left[0] = -180;
    right[0] = 180;
  }
  // END HACK

  return [
    Math.min(left[0], right[0], top[0], bottom[0]),
    Math.min(left[1], right[1], top[1], bottom[1]),
    Math.max(left[0], right[0], top[0], bottom[0]),
    Math.max(left[1], right[1], top[1], bottom[1])
  ];
}
```

**Poles:**
![image](https://user-images.githubusercontent.com/22612/99076163-9fc7a600-25b2-11eb-9497-1c252c50130f.png)
![image](https://user-images.githubusercontent.com/22612/99076203-ace49500-25b2-11eb-9b2b-71c2e32a5d66.png)
![image](https://user-images.githubusercontent.com/22612/99076248-b837c080-25b2-11eb-8e5b-9ab9bb3621b4.png)

**Extreme angles:**
![image](https://user-images.githubusercontent.com/22612/99076315-d69dbc00-25b2-11eb-9673-3b477ecbde32.png)
![image](https://user-images.githubusercontent.com/22612/99076342-e3221480-25b2-11eb-8727-840e1f15ab26.png)

#### Repro Steps
- Use `GlobeView`
- Add an `MVTLayer` from Mapbox using only admin and water features

**Poles:**
- Zoom in until globe fills most of the viewport
- Tilt globe down to view pole and rotate

**Extreme angles:**
- Zoom in quite close so left/right edges of globe are out of view
- Rotate globe up/down so you are looking at north/south hemisphere at an extreme angle
- Tiles will disappear in those hemispheres

**General:**
- I've found a large browser window can help replicate the issues (perhaps even in a portrait format)
- [CodeSandbox example](https://codesandbox.io/s/deckgl-5123-tessellation-zyecp)

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.3.6 (also master / 8.4.0-alpha.2)
 - Browser Version: Chrome 86.0.4240.198
 - OS: Windows 10

#### Logs
- No log outputted

**Comment by Pessimistress** [comment]
Fix published in 8.3.9.
