### ISSUE TITLE
H3HexagonLayer output issue when using GlobeView

### ISSUE THREAD

**Issue by robhawkes** [visgl/deck.gl#5125]
#### Description

- When combining `H3HexagonLayer` and `GlobeView` there is an issue with the output
- The results look similar regardless of whether the layer is extruded or not
- When zooming in it looks like only one of the vertices is incorrect on at least the top face

Zoomed in: 
![image](https://user-images.githubusercontent.com/22612/99085702-6dbd4080-25c0-11eb-9db5-453929366ee8.png)

![image](https://user-images.githubusercontent.com/22612/99085139-c0e2c380-25bf-11eb-83a7-06f4a4430295.png)

Zoomed out:
![image](https://user-images.githubusercontent.com/22612/99085301-ee2f7180-25bf-11eb-8bb9-004dc2759540.png)

#### Repro Steps
- Use `GlobeView`
- Add a `H3HexagonLayer` using example data from deck.gl demo page
- [CodeSandbox example](https://codesandbox.io/s/deckgl-globe-hex-jje27?file=/src/index.js:163-177)

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.3.6 (also master / 8.4.0-alpha.2)
 - Browser Version: Chrome 86.0.4240.198
 - OS: Windows 10

#### Logs
- No log outputted

**Comment by Pessimistress** [comment]
While we investigate, you can work around this by adding `highPrecision: true`.

**Comment by Pessimistress** [comment]
Fixed in 8.3.8
