### ISSUE TITLE
Is there a way to change a subset of a layer visibilty prop?

### ISSUE THREAD

**Issue by tamir-jether** [visgl/deck.gl#5136]
Let's say I have a simple scatterplot layer. I know that by using the 'visible' attribute i can dynamically change whether i see the entire layer or not.

What i would like to do, in theory, is to pass a function to the 'visible' attribute, instead of a boolean. I would like to have the ability to change part of the objects in the layer to be visible and part not.

From the documentation, i see it impossible to pass a function to the 'visible' attribute. So my question is this - is there any way to make something like that work in a different way? 
I might be able to do so by changing size to 0 maybe, but that doesnt sound like a valid solution.

thanks!

**Comment by Pessimistress** [comment]
[DataFilterExtension](https://deck.gl/docs/api-reference/extensions/data-filter-extension) [example](https://deck.gl/examples/data-filter-extension/)

**Comment by tamir-jether** [comment]
Exactly what i was looking for, thanks!
