### ISSUE TITLE
Extend PathLayer round joint and no round cap

### ISSUE THREAD

**Issue by TextTL** [visgl/deck.gl#5139]
Hi,

I'm looking for a method to extend PathLayer so that the joints are rounded, but not the cap. I looked at the code, but I don't know how to inject codes to disable this if statement 

  // extend out a triangle to envelope the round cap
  if (isCap) {
    offsetVec = mix(perp * sideOfPath, dir * jointType * 4.0 * flipIfTrue(isStartCap), isJoint);
  }

Any recommendation is really appreciated.

Thanks,

**Comment by Pessimistress** [comment]
This is very hacky, but you can inject into an arbitrary position in a shader:

https://codepen.io/Pessimistress/pen/dyXQBJr

**Comment by txtl** [comment]
@Pessimistress 

It works great! Thank you very much for your help!

**Comment by txtl** [comment]
BTW, it would be nice to turn it into a feature.

**Comment by Pessimistress** [comment]
This will be available in 8.5.0. You can try it now in `8.5.0-alpha.2` with `capRounded` and `jointRounded` props.
