### ISSUE TITLE
chrome sidebar shaking

### ISSUE THREAD

**Issue by grenoblien** [visgl/deck.gl#5141]
#### Description

My webpage shakes alot in certain ratio of web browser. 
It does not happen on Microsoft Edge. 
It does not happen when I just add ReactMapGL component. 
But it happens when I put ReactMapGL inside DeckGL.

<ReactMapGL
          {...viewport}
          width="100%"
          height="100%"
          onViewportChange={handleViewportChange}
          mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
          mapStyle="mapbox://styles/mapbox/streets-v9"
          onHover={(e) => console.log(e)}
        >
          {/* <div className="navi-control">
    <NavigationControl />
  </div> */}
        </ReactMapGL>

#### Repro Steps

I attach my code. 

import React, { useState, useCallback } from "react";
import ReactMapGL from "react-map-gl";

import DeckGL from "deck.gl";
import Coordinate from "./Coordinate";
import CityLayer from "./CityLayer";
import MarkerLayer from "./MarkerLayer";

require("dotenv").config();

// Set your mapbox token here
const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN; // eslint-disable-line

function Deck() {
  const [viewport, setViewport] = useState({
    latitude: 37.284387,
    longitude: 127.067898,
    zoom: 11,
    bearing: 0,
    pitch: 10,
  });

  const [latlon, setLatlon] = useState({
    latitude: 37.284387,
    longitude: 127.067898,
  });

  const handleViewportChange = useCallback((newViewport) => {
    setViewport(newViewport);
  }, []);

  const handleMouseHover = useCallback((e) => {
    if (e.x !== -1) {
      const mouseLat = e.coordinate[0];
      const mouseLon = e.coordinate[1];
      setLatlon({
        latitude: mouseLat,
        longitude: mouseLon,
      });
    }
  }, []);

  const [hoverInfo, setHoverInfo] = useState({});

  const hideTooltip = () => {
    setHoverInfo({});
  };

  const expandTooltip = (info) => {
    if (info.picked) {
      setHoverInfo(info);
    } else {
      setHoverInfo({});
    }
  };

  const layers = [
    CityLayer,
  ];

  return (

    <div>
      <DeckGL
        initialViewState={viewport}
        controller={true}
        layers={[layers]}
        onViewportChange={handleViewportChange}
        onHover={handleMouseHover}
      >
        <ReactMapGL
          {...viewport}
          width="100%"
          height="100%"
          onViewportChange={handleViewportChange}
          mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
          mapStyle="mapbox://styles/mapbox/streets-v9"
          onHover={(e) => console.log(e)}
        >
          {/* <div className="navi-control">
    <NavigationControl />
  </div> */}
        </ReactMapGL>
      </DeckGL>
    </div>
  );
}

export default Deck;

#### Environment (please complete the following information):
 - Framework Version: "deck.gl": "^8.3.4",
 - Browser Version: chrome 86.0.4240.198
 - OS: Win 10

**Comment by Pessimistress** [comment]
Please look at the [get started example](https://github.com/visgl/deck.gl/blob/master/examples/get-started/react/mapbox/app.js) on how to use DeckGL with react-map-gl.

**Comment by suryakumara** [comment]
> #### Description
> My webpage shakes alot in certain ratio of web browser. It does not happen on Microsoft Edge. It does not happen when I just add ReactMapGL component. But it happens when I put ReactMapGL inside DeckGL.
> 
> <ReactMapGL {...viewport} width="100%" height="100%" onViewportChange={handleViewportChange} mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN} mapStyle="mapbox://styles/mapbox/streets-v9" onHover={(e) => console.log(e)} > {/*
> 
> 
> */}
> #### Repro Steps
> I attach my code.
> 
> import React, { useState, useCallback } from "react"; import ReactMapGL from "react-map-gl";
> 
> import DeckGL from "deck.gl"; import Coordinate from "./Coordinate"; import CityLayer from "./CityLayer"; import MarkerLayer from "./MarkerLayer";
> 
> require("dotenv").config();
> 
> // Set your mapbox token here const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN; // eslint-disable-line
> 
> function Deck() { const [viewport, setViewport] = useState({ latitude: 37.284387, longitude: 127.067898, zoom: 11, bearing: 0, pitch: 10, });
> 
> const [latlon, setLatlon] = useState({ latitude: 37.284387, longitude: 127.067898, });
> 
> const handleViewportChange = useCallback((newViewport) => { setViewport(newViewport); }, []);
> 
> const handleMouseHover = useCallback((e) => { if (e.x !== -1) { const mouseLat = e.coordinate[0]; const mouseLon = e.coordinate[1]; setLatlon({ latitude: mouseLat, longitude: mouseLon, }); } }, []);
> 
> const [hoverInfo, setHoverInfo] = useState({});
> 
> const hideTooltip = () => { setHoverInfo({}); };
> 
> const expandTooltip = (info) => { if (info.picked) { setHoverInfo(info); } else { setHoverInfo({}); } };
> 
> const layers = [ CityLayer, ];
> 
> return (
> 
> ```
> <div>
>   <DeckGL
>     initialViewState={viewport}
>     controller={true}
>     layers={[layers]}
>     onViewportChange={handleViewportChange}
>     onHover={handleMouseHover}
>   >
>     <ReactMapGL
>       {...viewport}
>       width="100%"
>       height="100%"
>       onViewportChange={handleViewportChange}
>       mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
>       mapStyle="mapbox://styles/mapbox/streets-v9"
>       onHover={(e) => console.log(e)}
>     >
>       {/* <div className="navi-control">
> <NavigationControl />
> ```
> 
> */} ); }
> export default Deck;
> 
> #### Environment (please complete the following information):
> * Framework Version: "deck.gl": "^8.3.4",
> * Browser Version: chrome 86.0.4240.198
> * OS: Win 10
> 
> #### Logs

Hi I got same problem, I add map deckgl inisde dialog MUI. any idea how solve this ?
