### ISSUE TITLE
Icons aren't rendered when close to each other.

### ISSUE THREAD

**Issue by nagermen** [visgl/deck.gl#5142]
Hello, thank you for your terrific works, you guys rock.
 I am trying to visualize data that consist of lot of icons sometimes overlapping on each other. However client doesn't want to use clustering or hexagon layers etc and overlapping is fine for them. 
So I used _IconLayer_ to visualize the data, but it seems like when Icons are close to each other deck.gl skips on some of them, and renders only small part of icons. here is a [link](https://stackblitz.com/edit/angular-mapbox-deckgl-rsyg4j?file=src/app/app.component.ts) to it.
Have created 2 separate data sets, one with original like coordinates other one slightly randomized, the rest of the data is the same, only coords are different. When I use randomized data all 100 icons are rendered and pickable etc, however when I use original one only 9-10 icons are rendered and only those are pickable even if I use pickObjects method with box selection still only those 10 icons are being selected.

I cannot understand why is this happening and have no idea how to solve it. Any help is much appreciated. 

Thanks a lot.

I am using
angular: v9.x, deck.gl: v8.3.x, mapbox: v1.9.1.

**Comment by Pessimistress** [comment]
Many of your data points have identical coordinates and therefore overlap each other. You can see this by changing the `opacity` of the IconLayer to 0.1. There is nothing you can do to pick multiple objects from the same pixel. You will have to cluster them.

**Comment by nagermen** [comment]
@Pessimistress Thank you for your reply. 
I was just confused why `pickObjects ` is not picking overlapping items? I was thinking If I am giving correct boundary box it should pick every object within the box, even if they are overlapping. Is this wrong? so if there are overlapping object pickObjects method is only going to pick the ones on the top? Does this mean that the rest aren't rendered?

Thanks a lot.

**Comment by Pessimistress** [comment]
They are rendered, but that doesn't mean they can be picked. You can read about deck.gl's picking technique [here](https://deck.gl/docs/developer-guide/custom-layers/picking#the-color-picking-technique). `pickObjects` can only pick the objects rendered on top. 

You can use [pickMultipleObjects](https://deck.gl/docs/api-reference/core/deck#pickmultipleobjects) with the `depth` parameter to pick overlapped objects. However, in your use case, where there can be a large number of icons rendered to the same location, the overhead to get all the objects increases with the number of objects you are trying to pick. It'll be much easier for you to preprocess your data and only render the unique ones.

**Comment by nagermen** [comment]
thank you very much for your help, will try to do that. 
I'll close this as it is not an issue.
