### ISSUE TITLE
No Background Map in the HTML File saved with .to_file in Pydeck

### ISSUE THREAD

**Issue by logan0402** [visgl/deck.gl#5144]
# Summary

When I try with the example code of Pydeck the map I got with .show() in Jupyter notebook is normal with mapbox background map while if I use .to_file to save it as HTML file, I cannot see background mapbox map layer in the HTML file 

# Steps to reproduce

Run the code below
Inspect the browser output

Code

```python
import pydeck as pdk
import pandas as pd
from vega_datasets import data as vds
import ipywidgets
from palettable.cartocolors.sequential import BrwnYl_3
import json
MAPBOX_API_KEY ="###############
data = 'https://raw.githubusercontent.com/groundhogday321/dataframe-datasets/master/fake_commute_data.csv'
commute_pattern = pd.read_csv(data)
print(commute_pattern.head(2))
view = pdk.ViewState(latitude=32.800382, longitude=-97.040728, pitch=50, zoom=9)
arc_layer = pdk.Layer('ArcLayer',
                      data=commute_pattern,
                      get_source_position=['from_lon', 'from_lat'],
                      get_target_position=['to_lon', 'to_lat'],
                      get_width=5,
                      get_tilt=15,
                      # RGBA colors (red, green, blue, alpha)
                      get_source_color=[255, 165, 0, 80],
                      get_target_color=[128, 0, 128, 80])
arc_layer_map = pdk.Deck(map_style='mapbox://styles/mapbox/light-v10',
                         layers=arc_layer,
                         initial_view_state=view,
                         mapbox_key=MAPBOX_API_KEY)
arc_layer_map.to_html(r'############\arc_layer_map.html')
arc_layer_map.show()
```

## Expected behavior:
Expect there is normal background mapbox map layer in the html I generate with above code.

## Actual behavior:
Map in the HTML file
![image](https://user-images.githubusercontent.com/74434554/99148903-d8d34980-268a-11eb-8c9a-1053f067aeb5.png)
Map in the Notebook
![image](https://user-images.githubusercontent.com/74434554/99148913-ec7eb000-268a-11eb-85e8-1e26c800f589.png)

I check the chrome console when I open the html file generated by Python:
![image](https://user-images.githubusercontent.com/74434554/99673933-a43e0400-2a75-11eb-95ba-f0e9fec2570b.png)
![image](https://user-images.githubusercontent.com/74434554/99673938-a6a05e00-2a75-11eb-8f8e-07c879e319fb.png)
![image](https://user-images.githubusercontent.com/74434554/99673945-a902b800-2a75-11eb-8b08-839547cbab86.png)
![image](https://user-images.githubusercontent.com/74434554/99673953-aacc7b80-2a75-11eb-99c1-8ac62281291a.png)

## Is this a regression?
No

# Debug info
None
# Additional information
Python version: 3.7.2
OS version: Windows 10
Browser version: Chrome 79.0.3945.117

**Comment by kylebarron** [comment]
Can you look for errors in the browser console when you open the html file? It probably has to do with the Mapbox token not getting saved to the HTML file

**Comment by ajduberstein** [comment]
Can you run `print(pydeck.__version__)` and let us know the output? It does look like your Mapbox API key isn't getting set.

**Comment by logan0402** [comment]
> Can you run `print(pydeck.__version__)` and let us know the output? It does look like your Mapbox API key isn't getting set.

Hi, the version I am using is 0.2.1

**Comment by logan0402** [comment]
> Can you look for errors in the browser console when you open the html file? It probably has to do with the Mapbox token not getting saved to the HTML file

Hi, I update the console picture in the issue description

**Comment by ajduberstein** [comment]
@logan0402 can you update pydeck? The latest version is 0.5.0.

**Comment by logan0402** [comment]
> @logan0402 can you update pydeck? The latest version is 0.5.0.

I try to use conda to upgrade to 0.5.0, but when I run 'conda install -c conda-forge pydeck=0.5.0' it keeps on at solving environment procedure T.T

**Comment by logan0402** [comment]
Wow, I install pydeck 0.5.0 and this problem is solved that I can see background map in the HTML I generate with Pydeck
Thanks a lot~

P.S.
I try to install Pydeck 0.5.0 with conda install -c conda-forge pydeck=0.5.0 but it is trapped at 'solving environment'
Finally I download pydeck 0.5.0 tar.bz2 package to my laptop and install it from the local

**Comment by logan0402** [comment]
> Can you look for errors in the browser console when you open the html file? It probably has to do with the Mapbox token not getting saved to the HTML file

Hi, I upgrade Pydeck to 0.5.0 following the suggestion from @ajduberstein and the problem is solved
Thanks~
