### ISSUE TITLE
Are animations with transition and updateTriggers in mobile browsers deactivated?

### ISSUE THREAD

**Issue by felixbuchholz** [visgl/deck.gl#5146]
I’m animating an icon layer with updateTriggers and transitions on getColor and getSize. It’s implemented within a stateful React component updating the layers in a useEffect hook when the updateTrigger variables change. The animation works perfectly on desktop browsers. 

On **any** mobile browser the transition functionality seems to be deactivated. Is there a way to allow the same behavior on mobile? 

Thanks in advance!

**Comment by Pessimistress** [comment]
Not sure what mobile browsers you are talking about. If you are referring to iOS, attribute transitions are WebGL2 only, which is not supported on iOS.

**Comment by felixbuchholz** [comment]
Thank you so much that helped a lot! Going to check it on Android later 👍
