### ISSUE TITLE
SimpleMeshLayer is vertically flipped

### ISSUE THREAD

**Issue by doninpr** [visgl/deck.gl#5147]
#### Description

When I create a SimpleMeshLayer on top of a Polygon and try to rotate them in one direction, the layers rotate in different directions.

This is texture that (as I expected) must be facing north:
<img width="60" alt="texture" src="https://user-images.githubusercontent.com/23110750/99526800-d899bd80-29ac-11eb-9784-4bf5d86b35cd.png">

But this is how it shows without rotating:
<img width="300" alt="step1" src="https://user-images.githubusercontent.com/23110750/99526995-23b3d080-29ad-11eb-8557-00da52ddd4c9.png">

And then what is happen when I rotate both layers:

30 degree:
<img width="300" alt="degree30" src="https://user-images.githubusercontent.com/23110750/99527199-78efe200-29ad-11eb-8dbe-213d49afbb3d.png">

45 degree:
<img width="300" alt="degree45" src="https://user-images.githubusercontent.com/23110750/99527208-7d1bff80-29ad-11eb-8962-9e0d4894f903.png">

#### Repro Steps

Codesandbox example: https://codesandbox.io/s/deckgl-simplemesh-i9d51?file=/src/App.js

#### Environment:
 - Framework Version: [e.g. deck.gl 6.3.0]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]

**Comment by Pessimistress** [comment]
SimpleMeshLayer's [getOrientation](https://deck.gl/docs/api-reference/mesh-layers/simple-mesh-layer#getorientation) returns an Euler angle, it has nothing to do with turf.js' definition of rotation.

If you don't like the starting orientation generated by `PlaneGeometry` you can always manually flip the texCoords.

**Comment by doninpr** [comment]
I get it, thanks!
