### ISSUE TITLE
Issues with Unit Testing of the deckGL React component

### ISSUE THREAD

**Issue by srideviayyagari** [visgl/deck.gl#5149]
Hello,

I'm trying to setup the unit testing for the DeckGL React component. But, running in to issues. Here is the sample test script that I'm trying to run . Can you please take  and let me know if I'm missing anything. Thank you.

App.Test.js

import testLayer from '@deck.gl/test-utils';
import { GeoJsonLayer } from 'deck.gl';

//deck.log.level=1;
jest.setTimeout(15000)
describe('deck.gl test', function() {
  it('GeoJsonLayer#tests', t => {
      testLayer({Layer: GeoJsonLayer, testCases: [{
          // Test case 1
          props: {
            data: [{
              "type": "Feature",
              "geometry": {
                "type": "Point",
                "coordinates": [125.6, 10.1]
              },
              "properties": {
                "name": "Dinagat Islands"
              }
            }]
          },
          assert: ({layer, subLayers}) => {
            t.ok(layer.state.features, 'should update features');
            t.is(subLayers.length, layer.props.stroked ? 2 : 1, 'correct number of sublayers');
          }
      }]});
  });
});

after "npm Test", this is the error I'm getting the below error.

 FAIL  src/App.test.js (19.101 s)
  deck.gl test
    × GeoJsonLayer#tests (6 ms)

  ● deck.gl test › GeoJsonLayer#tests

    TypeError: (0 , _testUtils.default) is not a function

       6 | describe('deck.gl test', function() {
       7 |   it('GeoJsonLayer#tests', t => {
    >  8 |       testLayer({Layer: GeoJsonLayer, testCases: [{
         |       ^
       9 |           // Test case 1
      10 |           props: {
      11 |             data: [{

      at Object.<anonymous> (src/App.test.js:8:7)

  console.log
    deck: deck.gl 8.3.6 - set deck.log.level=1 (or higher) to trace attribute updates

      at Object.<anonymous> (node_modules/@deck.gl/core/src/lib/init.js:45:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        26.185 s
Ran all test suites related to changed files.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.

**Comment by Pessimistress** [comment]
As the error message says, `testLayer` is not a default export. You need `import {testLayer} from '@deck.gl/test-utils'`

**Comment by srideviayyagari** [comment]
Thanks for your reply. I have added the import for test-utils. That fixed the error. But, I'm getting in to issues with WebGL2 not supported b the browser.  However, I was able to run a sample demo application that we have created for our software and it ran fine in Chrome. So, not sure of this WebGL2 compatibility issue.

Please see the below error.
console.log
    deck: deck.gl 8.3.6 - set deck.log.level=1 (or higher) to trace attribute updates

      at Object.<anonymous> (node_modules/@deck.gl/core/src/lib/init.js:45:5)

  console.warn
    deck: WebGL2 not supported by this browser. Transition animation is disabled.

      at new AttributeTransitionManager (node_modules/@deck.gl/core/src/lib/attribute/attribute-transition-manager.js:25:7)
      at new AttributeManager (node_modules/@deck.gl/core/src/lib/attribute/attribute-manager.js:72:39)
      at ScatterplotLayer._getAttributeManager (node_modules/@deck.gl/core/src/lib/layer.js:897:12)
      at ScatterplotLayer._initState (node_modules/@deck.gl/core/src/lib/layer.js:908:35)
      at ScatterplotLayer._initialize (node_modules/@deck.gl/core/src/lib/layer.js:582:10)
      at LayerManager._initializeLayer (node_modules/@deck.gl/core/src/lib/layer-manager.js:320:13)
      at LayerManager._updateSublayersRecursively (node_modules/@deck.gl/core/src/lib/layer-manager.js:284:16)

 FAIL  src/App.test.js (24.83 s)
  deck.gl test
    × GeoJsonLayer#tests (15025 ms)

  ● deck.gl test › GeoJsonLayer#tests

    thrown: "Exceeded timeout of 15000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       5 | jest.setTimeout(15000)
       6 | describe('deck.gl test', function() {
    >  7 |   it('GeoJsonLayer#tests', t => {
         |   ^
       8 |       testLayer({Layer: GeoJsonLayer, testCases: [{
       9 |           // Test case 1
      10 |           props: {

      at src/App.test.js:7:3
      at Object.<anonymous> (src/App.test.js:6:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        28.002 s
Ran all test suites related to changed files.

**Comment by Pessimistress** [comment]
> I was able to run a sample demo application that we have created for our software and it ran fine in Chrome. So, not sure of this WebGL2 compatibility issue.

I assume you are running the tests in Node? The warning is about the environment that you are running the test in. It's also just a warning, does not cause your test to fail.
