### ISSUE TITLE
Implement tooltip when having several layers

### ISSUE THREAD

**Issue by tamir-jether** [visgl/deck.gl#5152]
I have 2 layers. one is a scatterplot, the other is a heatmap.
They both use the same data and same locations.
I have a working tooltip for the scatterplot layer, using the onHover field.
All was working fine when i just had 1 layer - the scatterplot. Once i add a heatmap layer above it, the tooltip doesnt work anymore. Its like the heatmap layer is literally on top of the scatterplot and the scatterplot doesnt "know" the mouse is hovering above its objects.

Is there anyway to solve that?

**Comment by Pessimistress** [comment]
If you don't need to pick the HeatmapLayer, don't set it's `pickable` prop to `true`.
