### ISSUE TITLE
IconLayer SVGs without size and width

### ISSUE THREAD

**Issue by adityasigmacomputing** [visgl/deck.gl#5158]
Is there any way for an IconLayer to use an SVG that has a viewBox but not an explicitly set width and height (by loading it with some default size or asking the user to supply a size for the asset)? 
Here's the exception I get, for reference
`index.js:1 DOMException: Failed to execute 'createImageBitmap' on 'Window': The image element contains an SVG image without intrinsic dimensions, and no resize options or crop region are specified.`

**Comment by Pessimistress** [comment]
Please provide the IconLayer props and the SVG you are using.

**Comment by adityasigmacomputing** [comment]
Here's one of svgs:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="150px" height="150ox"><circle cx="12" cy="12" r="12"/></svg>`
and here's the IconLayer props (let me know if this isn't specific enough):
```
{
      id: `icon-layer-[unique identifier is here]`,
      data,
      pickable: true,
      iconAtlas: [url to one asset here],
      iconMapping: {
        marker: {
          x: 0,
          y: 0,
          width: 150,
          height: 150,
          mask: true,
        },
      },
      getIcon: _ => 'marker',
      autoHighlight: true,
      sizeMinPixels: 1,
      sizeMaxPixels: 100,
      sizeScale: sizeScale,
      updateTriggers: {
        getFillColor: getFillColor,
      },
      getPosition: getPosition,
      getColor: getColor,
      getSize: getSize,
      onHover: ({ object, x, y }) => {
        setTooltip(
          [x, y],
          object
        );
      },
    }
```

**Comment by Pessimistress** [comment]
You can add this to the BitmapLayer:

```js
  loadOptions: {
    imagebitmap: {
      resizeWidth: 150,
      resizeHeight: 150
    }
  }
```

[ImageLoader options](https://loaders.gl/modules/images/docs/api-reference/image-loader)

**Comment by zebapy** [comment]
I'm still encountering this problem in Firefox 95 on mac OS 11.6 even with the fix in https://github.com/visgl/deck.gl/issues/5158#issuecomment-731369250 

Adding a `width`/`height` attributes on my `svg` does fix it but our icons avoid these attributes on purpose
