### ISSUE TITLE
Is it possible to save animation of interactive map into the HTML file?

### ISSUE THREAD

**Issue by logan0402** [visgl/deck.gl#5161]
# Summary
I generate a COLUMNLAYER with interactive widgets and it works as expected in Notebook. However, in the HTML file generated by .to_html, there is just the statistic for one year and there is no interactive widgets.
Is it possible to save animation controller of interactive map into the HTML file?
If possible, please provide me with some solution or tips, thanks

# Steps to reproduce
Run the code below
Inspect the browser output

Code
```python
# data
# in this example, the population was scaled down
data = 'https://raw.githubusercontent.com/groundhogday321/dataframe-datasets/master/gapminder_centroids.csv'
gapminder = pd.read_csv(data)
gapminder['scaled_population'] = gapminder['pop']/50_000

# view (location, zoom level, etc.)
view = pdk.ViewState(latitude=39, longitude=35, pitch=50, zoom=1)

# layer
gapminder_layer = pdk.Layer('ColumnLayer',
                             data=gapminder,
                             get_position=['longitude', 'latitude'],
                             get_elevation='scaled_population',
                             elevation_scale=100,
                             radius=200_000,
                             get_fill_color=[255, 165, 0, 80],
                             pickable=True,
                             auto_highlight=True)

# render map
# with no map_style, map goes to default
gapminder_layer_map = pdk.Deck(layers=gapminder_layer, 
                               initial_view_state=view,
                               mapbox_key=MAPBOX_API_KEY)

# display and save map (to_html(), show())
# display(gapminder_layer_map.show())
# display at botton

# widgets
slider = ipywidgets.IntSlider(value=1955, min=1955, max=2005, step=5)
play = ipywidgets.Play(value=1955, min=1955, max=2005, step=5, description='Press play', interval=1_000)
ipywidgets.jslink((play, 'value'), (slider, 'value'))
layout = ipywidgets.HBox([slider, play])

# function
def update_plot(year):
    gapminder_layer.data = gapminder[gapminder['year'] == year]
    return gapminder_layer_map.update()

# interaction between widget and function
interact = ipywidgets.interactive_output(update_plot, {'year': slider});
display(layout, interact)

# display and save map (to_html(), show())
gapminder_layer_map.show()
gapminder_layer_map.to_html(r'./interactive_layer_map.html')
```
## Expected behavior:
Expect there is normal background mapbox map layer in the html I generate with above code.

## Actual behavior:
When check the .show() result in Notebook, there is interactive widgets
![image](https://user-images.githubusercontent.com/74434554/99888975-32221680-2c51-11eb-970e-1ec227716c5a.png)

However in the HTML file generated by .to_html, there is just the statistic for year 1955 and there is no interactive widgets
![image](https://user-images.githubusercontent.com/74434554/99889002-8a591880-2c51-11eb-96f4-979a8b726838.png)

## Is this a regression?
No

# Debug info
None
# Additional information
Python version: 3.7.2
OS version: Windows 10
Browser version: Chrome 79.0.3945.117
Pydeck version: 0.5.0

**Comment by ajduberstein** [comment]
No, it’s not possible at the moment. The animations rely on the Jupyter kernel.

There are many tools for capturing a gif or mp4 from a screen, and those are currently the way to save animations from pydeck.

**Comment by logan0402** [comment]
> No, it’s not possible at the moment. The animations rely on the Jupyter kernel.
> 
> There are many tools for capturing a gif or mp4 from a screen, and those are currently the way to save animations from pydeck.
> 
> I should add that there are plans for some interactive components in pydeck but they likely won’t be available for another 3-6 months.

Thanks for this information. 
The maps in pydeck are really practical and fantastic. Looking forward to the future upgrade in pydeck
