### ISSUE TITLE
Rendering of IconLayer is cut off on top of a geojson filled polygon with map pitch 

### ISSUE THREAD

**Issue by juscc** [visgl/deck.gl#5163]
Please see codesandbox here https://codesandbox.io/s/deckgl-icon-geojson-4pqow?file=/src/App.js
<img width="532" alt="Screen Shot 2020-11-23 at 7 13 41 pm" src="https://user-images.githubusercontent.com/13215850/99940316-05404180-2dc0-11eb-891c-b7ce8ffe8c5a.png">

When rendering the icon layer and rotating/adding pitch to the map, it gets cut off by the filled polygon. Is there any way to fix this?

**Comment by Pessimistress** [comment]
#5024

**Comment by juscc** [comment]
> #5024

As always, thank you @Pessimistress for the prompt response! It's working as expected now.
