### ISSUE TITLE
TextLayer - "deck: Missing character" with unicode char

### ISSUE THREAD

**Issue by enodr** [visgl/deck.gl#5164]
#### Description
Using unicode chars from font icon creates error "deck: Missing character" even thought the characterSet has been passed.

The error does not prevent the font to display correctly.

Maybe it would also help in the error message to print the hex or decimal code for the missing character if the error is legit.

#### Repro Steps
- See codepen for error in console: https://codepen.io/domoxo/pen/vYKoKgL

#### Environment (please complete the following information):
 - Framework Version: 8.3.8
 - Browser Version: any
 - OS: any

**Comment by Pessimistress** [comment]
Thanks for the report. This has been fixed in 8.3.9.
