### ISSUE TITLE
TileLayer Base Map Fill Viewable Area?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#5166]
I was curious if there is a recommended way to have a raster base map fill the users entire viewable area when using TileLayer/BitmapLayer even when zoomed completely out? 

In looking at the [example](https://deck.gl/docs/api-reference/geo-layers/tile-layer) within the TileLayer documentation when zoomed completely out empty map area is seen...

I am currently using MapBox to render our raster base maps which has the `renderWorldCopies `property. Would a similar solution be achievable with TileLayer?

**Comment by Pessimistress** [comment]
https://deck.gl/docs/api-reference/core/map-view#constructor-1

https://deck.gl/examples/tile-layer/
