### ISSUE TITLE
Text Layer, multiple font and weight

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#5167]
I'm having a use-case that rendering Texts which may have different fonts and weights. For example, [{text: "Text1", font: "Arial", weight: "normal"}, {text: "Text2", font: "Veranda", weight: "bold"}, {text: "Text3", font: "Arial", weight: "bold"},...]. Currently, to achieve what is needed, I have to create all combinations of fonts and weights layers to achieve because the fontWeight and fontSettings are attributes, not accessors.  Is there any way to have a single layer to handle all combinations? or at least to have each layer handles multiple font weights using an accessor?

Thanks,

**Comment by Pessimistress** [comment]
The TextLayer does not currently support this use case. You can create a custom composite layer that sorts objects into multiple text layers. There is no significant perf penalty in doing that, since the layer has to build a separate font atlas for each weight/font combination anyways.

**Comment by txtl** [comment]
Thanks for the advice!
