### ISSUE TITLE
Cannot force width/height to 100% in @deck.gl/core. Resizing bug

### ISSUE THREAD

**Issue by enodr** [visgl/deck.gl#5170]
When using @deck.gl/core it is not possible to force width / height to 100% and thus prevents automatic resizing of the component when the browser window changes.

The code which overwrites the width/height style is here:
https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/deck.js#L463

The react component works because on every frame the styling is overwritten. See code:
https://github.com/visgl/deck.gl/blob/master/modules/react/src/deckgl.js#L173

This bug is also related to: https://github.com/visgl/deck.gl/issues/4561

A flag to prevent the automatic style assignment of width/height would be nice.

**Comment by Pessimistress** [comment]
Please fill in the bug template if you wish to report a bug.

**Comment by enodr** [comment]
I opened a new bug report with the template here: https://github.com/visgl/deck.gl/issues/5174
