### ISSUE TITLE
Is it possible to have a specific icon depending the type key in my JSON data?

### ISSUE THREAD

**Issue by acebelowzero** [visgl/deck.gl#5171]
I am trying to get specific Icons on a Icon layer depending on what type my object has.

For example. 

If my JSON data has the type jumbo jet then I want to display a jumbo jet icon
 { type: "jumbo jet", "coordinates": [ -106.13529000000001, 31.46139 ], "planeID": "3d10000" },

If my JSON data has the type jet then I want to display a helicopter Icon
 { type: "helicopter", "coordinates": [ -106.13529000000001, 31.46139 ], "planeID": "3d12320000" },

**Comment by Pessimistress** [comment]
[getIcon](https://deck.gl/docs/api-reference/layers/icon-layer#geticon)

**Comment by acebelowzero** [comment]
@Pessimistress getIcon sets the whole Icon layer to be that specific icon, I want to have different Icons in one Iconlayer

**Comment by Pessimistress** [comment]
All accessor functions are called once for each object in your data array.

**Comment by acebelowzero** [comment]
ah ok, I see now thanks!

**Comment by acebelowzero** [comment]
Attempting to use specific icons depending on the case I get these icons instead.
![weird icon](https://user-images.githubusercontent.com/64754588/100552771-765f7900-3246-11eb-80ac-04f180270e22.PNG)


code on how I am assigning the icon
```
getIcon: (d) => {
            if(d.flight == "Person") {
              return {
              url: "@/assets/Person.svg",
              width: 128,
              height: 128,
            };
            }
            if(d.flight === "Unkown") {
              return {
              url: "https://srv-store3.gofile.io/download/dtxpEg/unknown.svg",
              width: 128,
              height: 128,
            };
            }
            if(d.flight === "Aircraft") {
              console.log("true")
              return {
              url: "https://srv-store5.gofile.io/download/xXj7af/Aircraft%20(1).svg",
              width: 128,
              height: 128,
            };
            }else {
              return {
              url: "https://srv-store5.gofile.io/download/xXj7af/Aircraft%20(1).svg",
              width: 128,
              height: 128,
            };
            }

          },
```
