### ISSUE TITLE
Cannot force width/height to 100% in @deck.gl/core + VueJS

### ISSUE THREAD

**Issue by enodr** [visgl/deck.gl#5174]
#### Description
The current logic in @deck.gl/core prevents the user from assigning width=100% and height=100% styling properties for the canvas, thus preventing it from being able to resize correctly.
Moreover the current code logic introduces a resizing problem on retina displays which 'flickers' the component by resizing it with wrong values in a loop (because canvas.clientWidth is double value of canvas.width in pixels).

We can clearly see in the screenshot below that the styling properties have been overwritten with a fixed width and height in px, thus preventing the component from resizing correctly when the browser window changes. Also note in this particular case (retina display) that the canvas width and styling width properties in px are different because of retina display and canvas size measurement (one pixel is double on retina display).
<img width="880" alt="Capture d’écran 2020-11-23 à 23 05 43" src="https://user-images.githubusercontent.com/10436257/100058745-276ea980-2e2a-11eb-84be-cce6c4e923e7.png">

#### Repro Steps
Create a new simple Deck class with width=100% and height=100% and register a onResize callback to print height and width. By inspecting the console you see that instantiating the component and resizing the window that the component does not resize anymore.

The bug is located in this code logic:
https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/deck.js#L463

The React component is not affected because at every frame it rewrites the width=100% and height=100% props.
https://github.com/visgl/deck.gl/blob/master/modules/react/src/deckgl.js#L173

This bug is related to: https://github.com/visgl/deck.gl/issues/4561

#### Environment (please complete the following information):
 - Framework Version: deck 8.3.8 + VueJS
 - Browser Version: any
 - OS: any
- Hardware: retina display for the resizing loop/flicker
**EDIT**: testing has been done with VueJS

#### Logs
<img width="454" alt="Capture d’écran 2020-11-23 à 23 05 21" src="https://user-images.githubusercontent.com/10436257/100058751-2b023080-2e2a-11eb-8a22-8e6c1ad4340b.png">

EDIT2: the conclusions of the cause of the bug in this first report are not correct. See comments below.

**Comment by Pessimistress** [comment]
> By inspecting the console you see that instantiating the component and resizing the window that the component does not resize anymore.

Can you create a Codepen? Your screenshot clearly shows `onResize` being called when the window resizes.

**Comment by enodr** [comment]
The log above is just from the component mounting. No window resize occured; The values you can see are with the retina display problem (3240 is double from 1620 because of discrepancy between canvas.clientWidth and canvas.width). I will do a codepen later today to show the problem but from the source above the issue seems clear (code forces style width and height with values in px while we do not want that. Obviously if the height/width style is fixed in px, resizing cannot occur anymore).

**Comment by Pessimistress** [comment]
Just to clarify, the code you referenced only sets `canvas.width` and `canvas.height`. What controls DOM resizing are `canvas.style.width` and `canvas.style.height`, which are set to `width` and `height` in Deck's props.

**Comment by enodr** [comment]
Hi,

So after much testing I have made progress and clearly my first conclusion were erroneous as you noted. Clearly the bug only happens with VueJS. Here are the details:

1. Cannot pass onViewStateChange at creation.  This does not work with VueJS:
`let deck = new Deck({...this.$props, onViewStateChange = this.handleViewStateChange})`
So a workaround is needed.

2. As noted here https://github.com/loftylabs/vue_deckgl/blob/main/src/components/deckgl/DeckGl.vue#L50 we need to set props once before we can add onViewStateChange.  So this type of code is needed:

```
// pass onAfterRender callback
mounted() {
       this.deck = new Deck({ ...DECKGL_SETTINGS,
            ...this.$attrs, 
            ...this.$props,
            onAfterRender: this.setupHandlers
            })
}
// ...
        /* The initialization of DeckGL is not working properly with Vue.
            We need to setProps once before interactive listeners can be added (IE - onViewStateChange).
            We know it's safe to do so once the render has taken place twice. (First Render = Canvas, Second Render = Layers)
        */
        hasInitialRenderBugResolved(){
            if(this.afterRenderCounter == 1){
                return true                
            }
            this.afterRenderCounter += 1
            this.deck.setProps({...this.deck.props}) // PROBLEM HERE !!
            return false
        },
        // Once we know we have moved past the initialRender cycle, we can then remove listener for onAfterRender, attach interactive listeners, and emit initialRender is complete.
        setupHandlers(){
            if(this.hasInitialRenderBugResolved()){
                this.deck.setProps({...this.deck.props, onViewStateChange: this.moveMap, onAfterRender: ()=>{}})
                this.$emit('initialRender', true)
                this.hasHandlers = true
            }
        }
```

BUT the problem is that when calling ...this.deck.props the values of height and width are 0.

Here is with some logging the output of the console.
<img width="970" alt="console log" src="https://user-images.githubusercontent.com/10436257/100149703-e2388f00-2e9e-11eb-9a04-13c6308442d9.png">

Why in the onAfterRender callback width and height became 0 ? So the easy fix is to reapply width and height = 100% but there must be a bug somewhere? At least the callbacks not working at instantiation with VueJS is strange.

**Comment by Pessimistress** [comment]
The Deck class never overwrites user props. If `deck.props` contains a value it would be because you called either the constructor or `setProps` with it.

**Comment by enodr** [comment]
I have prepared this simple codepen to demonstrate the issue. Maybe I overlook some stupid thing but when I use the onAfterRender callback then the props.width and props.height are 0.

https://codepen.io/domoxo/pen/abmoVoj

**Comment by Pessimistress** [comment]
If you comment out `deckgl` from `data` it will work. You are asking Vue to hijack the properties inside the deck instance.

**Comment by enodr** [comment]
Thanks I just figured that out also. Solution is to declare this.deckgl in created() instead of putting it in the reactive properties. I am sure many people would be interested by a simple example on the official documentation of how to use with VueJS and not fall in this logic bug.

Thanks for your help and I hope this issue will help users to figure out with VueJS.

**Comment by Pessimistress** [comment]
> I am sure many people would be interested by a simple example on the official documentation of how to use with VueJS and not fall in this logic bug.

None of the current contributors are familiar with Vue. We will happily accept a PR if you want to give it a shot.
