### ISSUE TITLE
EditableGeoJsonLayer behaves strangely with Multiple views

### ISSUE THREAD

**Issue by grahambates-sp** [visgl/deck.gl#5177]
#### Description

I am combining multiple views (MapView and OrthView) with multiple view states.

I have noticed that when I use a EditableGeoJSONLayer, the points appear in wrong places, some kind of longitude/latitude rotation. Occasionally they are placed in the right place.

![image](https://user-images.githubusercontent.com/45166327/100269787-ffc53180-2f4e-11eb-8c63-afe3277e5564.png)

#### Repro Steps

The following codesandbox has 2 views with 2 viewStates.

https://codesandbox.io/s/red-architecture-ji1tp?file=/index.js

Uncomment the OrthView to see the issue. (and zoom out)

**Comment by Pessimistress** [comment]
There is a known picking bug that `coordinate` does not always work when using overlapping views. You can work around this by reordering your views while we address this.

**Comment by Pessimistress** [comment]
This is addressed in `8.4.0-alpha.5`
