### ISSUE TITLE
TextLayer Border Color/Size Rendering Options?

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#5179]
I am not seeing in the documentation for  [TextLayer](https://deck.gl/docs/api-reference/layers/text-layer) a way to set a border size or border color. Does the TextLayer support such rendering options?

**Comment by Pessimistress** [comment]
Not sure what you mean by border, but no it's not supported right now.

#4579
#3750

**Comment by jfuehner** [comment]
@Pessimistress believe #4579 is in line with what I am looking for...

Essentially, ArcGIS Feature Service JSON has a `esriTS` type for [TextSymbol](https://developers.arcgis.com/documentation/common-data-types/symbol-objects.htm)'s. The TextSymbol object supports both `borderLineColor `and `borderLineSize` properties which provide the ability style the border around the text label bounding box...

https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-TextSymbol.html

**Comment by Pessimistress** [comment]
Can you add your comment to the feature request?
