### ISSUE TITLE
drawLayer crashes if any of the props has the value undefined

### ISSUE THREAD

**Issue by andreasg123** [visgl/deck.gl#5180]
#### Description
[hms-dbmi/viv](https://github.com/hms-dbmi/viv) may set a layer prop to `undefined`. If that is the case, `drawLayer` crashes in luma.gl in `copyUniforms`.
https://github.com/hms-dbmi/viv/issues/300

#### Repro Steps
Copy the example from the [viv documentation](http://viv.gehlenborglab.org/#getting-started). Embed it in a React app and attempt to view an OME-TIFF image.

#### Environment (please complete the following information):
 - Framework Version: 8.4.0-alpha.2
 - Browser Version: Version 86.0.4240.198 
 - OS: macOS 10.15.7

#### Logs
    deck: error during drawing of XRLayer({id: 'XR-Static-Layer-0-512-512-0-6-Background-Image-ome-tiff-#detail#'}) TypeError: Cannot read property 'length' of undefined

**Comment by kylebarron** [comment]
`lensSelection` is a custom prop added by viv. I don't think this issue is related to deck.gl directly. @ilan-gold

**Comment by ilan-gold** [comment]
@andreasg123 I will fix this bug.  In the mean time, you can use a 0 for that argument and it should work.

**Comment by andreasg123** [comment]
I opened the issue here as well because I don't think that deck.gl should crash if somebody uses a layer prop with a value of `undefined`.

**Comment by ilan-gold** [comment]
@andreasg123 It's possible I am doing something wrong.  I agree that it is strange, but if it is an issue, I can always report a bug.  I may be doing something wrong here.  I do have a `defaultProp` set for this.

**Comment by ilan-gold** [comment]
If it is a bug, we should be able to create a somewhat more minimal example. I appreciate you bringing this to my attention a lot and love that people are trying out the repo :) warms my heart

**Comment by andreasg123** [comment]
I missed slightly when looking through the stack trace of the minified code (stupid Next.js and Webpack). The stack trace is actually this:

    toTypedArray
    toIntArray
    setUniforms

`toIntArray` comes from `this._uniformSetters[uniformName]`: https://github.com/visgl/luma.gl/blob/master/modules/webgl/src/classes/program.js#L205

Thus, the issue isn't with `undefined` in general but with a prop that has `toIntArray` associated and has the value `undefined`.
