### ISSUE TITLE
Use GLTFLoader instead of GLTFScenegraphLoader

### ISSUE THREAD

**Issue by vincentmvdm** [visgl/deck.gl#5185]
Hi! 

I'm loving SceneGraphlayer but am getting the following warning:

`deck: ScenegraphLayer.props.scenegraph is deprecated and will be removed in a later version. Use GLTFLoader instead of GLTFScenegraphLoader instead`.

I unfortunately have no idea what it means. I'm using the same functions (registerLoader etc.) as the documentation: https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer.

I'd appreciate any help you can provide!

Thanks!

**Comment by Pessimistress** [comment]
Thanks for reporting. The warning is erroneously issued while the scenegraph is still loading. I'll put up a fix.

**Comment by vincentmvdm** [comment]
> Thanks for reporting. The warning is erroneously issued while the scenegraph is still loading. I'll put up a fix.

Amazing, thank you! I really appreciate it!

**Comment by Pessimistress** [comment]
Fixed in 8.3.10.
