### ISSUE TITLE
Lost mouse control when updating viewState

### ISSUE THREAD

**Issue by txtl** [visgl/deck.gl#5186]
I followed the viewState example to change the viewState of  Orthographical view. After updating the viewState with the mouse-click, I couldn't interact with Deck GL using the mouse any longer. What step did I miss?

Here's the codepen: https://codepen.io/txtl-smith/pen/gOrdKjK

Thanks,

**Comment by Pessimistress** [comment]
You either use `initialViewState` or `viewState` with `onViewStateChange`. [documentation](https://deck.gl/docs/api-reference/core/deck#initialviewstate)

**Comment by txtl** [comment]
I tried initialViewState and onViewStateChange, and it worked as expected. 

Thanks a lot!
