### ISSUE TITLE
NavigationControl of react-map-gl is not working. 

### ISSUE THREAD

**Issue by ats1999** [visgl/deck.gl#5189]
Live https://codesandbox.io/s/silent-sun-b66m4?file=/src/App.js:77-94 

Is there any way to achieve this if no then can we disable onClick for `deck.gl` so `react-map-gl` can handle onClick?

**Comment by Pessimistress** [comment]
Just render it on top of `<DeckGL>`

**Comment by ats1999** [comment]
I edited in this sandbox  https://codesandbox.io/s/reverent-framework-uepze?file=/src/App.js:874-911 

Still, NavigationControl is not working.

**Comment by Pessimistress** [comment]
Your original code was using `<ReactMapGL>` as the parent of `<DeckGL>`. In that case, you want to render `<DeckGL>` as the first child and then other controls.

If you wish to use `<DeckGL>` as the parent, you need to make `<NavigationControl>` a child of `<DeckGL>` and specify the [ContextProvider](https://deck.gl/docs/api-reference/react/deckgl#contextprovider).

**Comment by ats1999** [comment]
Thanku you so much. This solved my problem
