### ISSUE TITLE
GridCellLayer - GetPosition point not on center of Grid

### ISSUE THREAD

**Issue by alok-mani-ds** [visgl/deck.gl#5191]
How to form a Grid Layer around a given Lat-Lng point keeping the point at the center of the Grid?
The closest solution I got to is GridCellLayer, however the Grid is rendered with the point being at a corner of the grid rather than the center?

![image](https://user-images.githubusercontent.com/57582354/100408029-ff807f80-308f-11eb-97eb-9fba0648fdd6.png)
In the above image, I have implemented the GridCellLayer for a single point, the point is marked with the Pink icon - it is clearly visible that the point is on the corner - can GridCellLayer have an optional parameter to let the GridCellLayer be formed with the reference of the point being at its center rather than a corner?

**Comment by Pessimistress** [comment]
The GridLayer is just a special case of [ColumnLayer](https://deck.gl/docs/api-reference/layers/column-layer) with a default `offset` of `[1, 1]`. You can overwrite it with `offset: [0, 0]` to center it at the anchor position.

**Comment by alok-mani-ds** [comment]
[ColumnLayer](https://deck.gl/docs/api-reference/layers/column-layer) served the purpose perfectly. Thanks a ton.
