### ISSUE TITLE
MVTLayer - Tiles borders are shown when getLineWidth is very high.

### ISSUE THREAD

**Issue by Clebal** [visgl/deck.gl#5192]
#### Description
While very large geometries like countries or states are being visualised (using the MVTLayer) it's necessary to use a large line width to display a notorious border (I know that maybe there are others ways to achieve that, but it's an example). The border is well painted, the problem is that when you zoom in, the tile borders are shown as you can see in the following images:

Around zoom 5:
![image](https://user-images.githubusercontent.com/9151432/100443068-56468300-30a9-11eb-9e06-0c0fdd279054.png)

When you zoom in:
![image](https://user-images.githubusercontent.com/9151432/100442797-edf7a180-30a8-11eb-96bc-281c3e892c14.png)

#### Repro Steps

- Steps to reproduce the behavior: just zoom in.

- A Stackblitz [example](https://stackblitz.com/edit/deck-gl-mvt-layer-high-line-width-bug?file=index.js) that reproduces the behavior.

#### Environment
 - Framework Version: deck.gl 8.3.9 (and minor versions also)
 - Browser Version: Chrome 86
 - OS: macOS Mojave 10.14.6

**Comment by Pessimistress** [comment]
deck.gl itself cannot tell which part of the polygon is an actual border and which part is cut by the border of a tile. Vector tiles are generated with some overlap (buffer) and they get clipped when rendered. Your line width must not exceed the buffer size. All tools that create vector tiles provide some option for you to customize the buffer size, [example](http://mapnik.org/documentation/node-mapnik/3.6/#VectorTile).

**Comment by Clebal** [comment]
@Pessimistress oh, that's true! I didn't remember that. Thank you so much.
