### ISSUE TITLE
Can we provide any custom styling or image to icons in iconLayer in deck.gl

### ISSUE THREAD

**Issue by ats1999** [visgl/deck.gl#5193]
I am using latest version of `deck.gl` and `react-map-gl` to display map. I need to render **Markers** on some point on the map. All markers should have a height(z-axis) on the map. 
> Consider situation of flight tracker application where user want to see the height of each flight in real time. 

Thanks to `deck.gl` which provides a way to set heights of icons. It accepts array of three points, `[lng,lat,altitude(z-axis)]`. Previously i was using **Marker** component of **react-map-gl**, but it doesn't provide a  way to give height or altitude to markers. That's why i started using `deck.gl`

`deck.gl` accept a `iconAtlas: "https://img.icons8.com/dusk/64/000000/user-location.png"` which is basically a image `url`. 

It provides some styling to image,  like `width,height,rotate`, etc. But i want more control over the icons. I want to rotate the icon using `rotateX,rotateY (css) etc`. It provides a `getAngle()` method to rotate around **a** axis. 

It doesn't provide more control like **recat-mao-gl**, where we could use a `<img>` tag directly. So, we have full control over the icon. 

To get full control on the icons i tried this, `iconAtlas:<img>..` this this doesn't worked. 

How can i achive this.

**Comment by Pessimistress** [comment]
You can supply a `HTMLImageElement` or `HTMLCanvasElement` to `iconAtlas`.

```js
iconAtlas: document.getElementById('my-image')
```

**Comment by ats1999** [comment]
I used your suggestion like this 
```js
const DroneImage = require("../path");
var img1 = document.createElement('img');
img1.src=DroneImage;
img1.style.opacity=0.3;
img1.style.transform="rotate(90deg)"
```
Although the image is displaying at the specified position on the map, the style is not being applied. 

### Working in HTML and CSS
the same thing if we do in HTML and CSS like below then it is working fine. 
```js
var img = document.createElement('img');
    img.src="https://res.cloudinary.com/bdevg/image/upload/v1606483976/right-arrow_pdxgkq.png";
    img.style.opacity=0.3;
    img.style.transform="rotate(90deg)"
    document.body.appendChild(img)
```
The above code is working fine. 
check -> https://www.w3schools.com/code/tryit.asp?filename=GL5YGS6EQ0JN

**Comment by Pessimistress** [comment]
CSS does not change the underlying data in an image. If you want to distort it you need to draw the result to a canvas, then use that canvas as an input to the IconLayer.

I'm not sure I understand your use case. Can you attach a picture of what you are trying to achieve?

**Comment by Pessimistress** [comment]
If you just want 3d rotation of a symbol then you should use SimpleMeshLayer instead of IconLayer.

**Comment by ats1999** [comment]
> CSS does not change the underlying data in an image. If you want to distort it you need to draw the result to a canvas, then use that canvas as an input to the IconLayer.
> 
> I'm not sure I understand your use case. Can you attach a picture of what you are trying to achieve?

You can get the picture from here #5198 

All lines have some height(altitude)I want to show drones which are flying on the line. If the map pitch is around **50-60** then i want to rotate it around the x-axis(`rotateX(..) equivalent CSS property`). And, I want to rotate the image around the path according to bearing between two previous points `equivalent CSS - rotate(..deg)`.

**Comment by Pessimistress** [comment]
Just set `billboard` to `false`.
