### ISSUE TITLE
angle to iconLayer is not properly working. 

### ISSUE THREAD

**Issue by ats1999** [visgl/deck.gl#5198]
I have some icons rendered through the `IconLayer`. 

I want to give an angle to each icon according to it's position. 

### Without angle
![Screenshot (488)](https://user-images.githubusercontent.com/54087826/100518753-b17e8f80-31e7-11eb-954f-1aa900b9ff4e.png)

See the icons position. 

### With angle 
![Screenshot (489)](https://user-images.githubusercontent.com/54087826/100518770-c9561380-31e7-11eb-8d56-cf163bd2fd99.png)
 There is much difference in the position of the icons. 

Angle could be anything(0-360), and it should rotate at its position. But, here is this is not working. 

### Code 

```js
id: `drone-icon-layer-deck-${idx}`,
            data: [
                {name:`Drone-${idx}`,coordinates:lngLat}
            ],
            pickable: true,
            billboard:true,
            // getIcon: return a string 
            iconAtlas: img1,
            getIcon: (d) => "marker",
            iconMapping: ICON__MAPPING,
            sizeScale: 15,
            getPosition: (d) => d.coordinates,
            getSize: (d) => 7,
            getColor: (d) => [Math.sqrt(d.exits), 140, 0],
            getPixelOffset: [30, 40],
            getAngle:(360-angle)
```

**ICON__MAPPING**
```js
const ICON__MAPPING = {
    marker: { x: 0, y: 0, width: 128,
      height: 128, mask: false
    }
};
```

**Comment by Pessimistress** [comment]
You should not have non-zero `getPixelOffset` if you want the icon anchored at the exact position.

**Comment by ats1999** [comment]
> You should not have non-zero `getPixelOffset` if you want the icon anchored at the exact position.

You can see in the first image, icons are properly positioned. 
In the second image, i gave an angle between **0-306** then the problem occurs. 

if i remove this `getPixelOffset: [30, 40]` and pass angle `getAngle:(360-angle)` then also same problem is coming.

**Comment by Pessimistress** [comment]
Can you share your iconAtlas? Is your marker centered in the frame?

**Comment by ats1999** [comment]
```js
var img1 = document.createElement('img');
img1.src=DroneImage;
```
use 
```js
iconAtlas: img1
```

**Comment by ats1999** [comment]
Image url https://res.cloudinary.com/bdevg/image/upload/v1606483976/right-arrow_pdxgkq.png

**Comment by ats1999** [comment]
Icon and path height have the same height **(4000)**
```js
[77.05491961950801, 31.767043730430355,4000] 
```

**Comment by Pessimistress** [comment]
Can you create a code sandbox that reproduces your issue?

**Comment by ats1999** [comment]
ok!
GIve me some time.

**Comment by ats1999** [comment]
This is code sandbox https://codesandbox.io/s/silent-sun-b66m4?file=/src/App.js

change `getAngle:120` and differences

**Comment by Pessimistress** [comment]
Your `iconMapping` does not match the dimensions of your `iconAtlas`. The image is only 64x64 and you specified the icon frame to be 128x128.

**Comment by ats1999** [comment]
# Thanks, it's solved
