### ISSUE TITLE
what would better fit my app. deck.gl vs kepler.gl

### ISSUE THREAD

**Issue by tamir-jether** [visgl/deck.gl#5199]
I asked a similar question in a kepler.gl slack channel (couldnt find a matching deck.gl channel, so im posting it here, i hope its ok. and if not, would understand if it gets deleted)

i just have a general question about the usage of kepler vs deckgl (with react). im trying to create a simple app over deckgl (or kepler), using react.  i want to show a specific kind of data over the map, add custom controls and tooltip and i dont need all the default options kepler gives(self-editing, downloading, updating and filtering data for example). there is this example: sudonull.com/post/11412-Interactive-map-for-a-web-application-in-a-couple-of-hours
i guess my question is pretty much this - any reason to create this app using react + deckgl, or react + kepler would pretty much give me all i need from deckgl + some extra features and its just better to use it?
thanks!

**Comment by Pessimistress** [comment]
> couldnt find a matching deck.gl channel

https://github.com/visgl/deck.gl#learning-resources

**Comment by Pessimistress** [comment]
I suggest you start by running the [get-started examples](https://github.com/visgl/deck.gl/tree/8.3-release/examples/get-started) and see if they meet your needs. kepler.gl is a way more complicated component to set up if you don't really need the features that it offers.
