### ISSUE TITLE
Deck.gl display a different icon than provided

### ISSUE THREAD

**Issue by acebelowzero** [visgl/deck.gl#5200]
Attempting to use specific icons depending on the case I get these icons instead.
weird icon
![weird icon](https://user-images.githubusercontent.com/64754588/100552830-d9e9a680-3246-11eb-9008-784cd9fc4ac8.PNG)

code on how I am assigning the icon

```
getIcon: (d) => {
            if(d.flight == "Person") {
              return {
              url: "@/assets/Person.svg",
              width: 128,
              height: 128,
            };
            }
            if(d.flight === "Unkown") {
              return {
              url: "https://srv-store3.gofile.io/download/dtxpEg/unknown.svg",
              width: 128,
              height: 128,
            };
            }
            if(d.flight === "Aircraft") {
              console.log("true")
              return {
              url: "https://srv-store5.gofile.io/download/xXj7af/Aircraft%20(1).svg",
              width: 128,
              height: 128,
            };
            }else {
              return {
              url: "https://srv-store5.gofile.io/download/xXj7af/Aircraft%20(1).svg",
              width: 128,
              height: 128,
            };
            }

          },
```

why is this happening?

**Comment by Pessimistress** [comment]
Make sure you follow the [example](https://deck.gl/docs/api-reference/layers/icon-layer#example-auto-packing-iconatlas) on the documentation page.

If you need help debugging, create a Codepen or CodeSandbox that reproduces your issue.

**Comment by acebelowzero** [comment]
I saw that the data already contains the icon url. 
here is a sandbox
https://codesandbox.io/live/hnjiwxv

**Comment by acebelowzero** [comment]
line 167 is where the icons are set

**Comment by Pessimistress** [comment]
I don't know what I'm looking for in your sandbox. Can you delete the irrelevant layers and zoom to where your data is?

**Comment by acebelowzero** [comment]
yes sir

**Comment by Pessimistress** [comment]
Also if you look in your console, all the svg icons fail to load.

**Comment by acebelowzero** [comment]
do the icons have to be from an url? or can they be from local folder for instance my assets folder

**Comment by Pessimistress** [comment]
If you are confused about whether a URL is valid, create a `<img src={url} />` and see if it can be displayed. deck.gl has the same level of access as your app.

**Comment by acebelowzero** [comment]
Im trying to avoid having to use an url if I have too then its fine ill deal with it.
 I want to display an specific icon depending on the object field "flight".
In the example you provided me the data has a url field that links to the specific icon.
Is it possible to intead use getIcon to first do a check to see if what "d.flight" as is which is what I am doing now.
Then instead of having this:
```
getIcon: (d) => {
  if(d.flight == "this-icon") {
  return {
    url: "www.link-to-icon.com",
    width: 128,
    height: 128,
    anchorY: 128
}
}
}
```
I want to have this
```
getIcon: (d) => {
  if(d.flight == "this-icon") {
  return {
    url: "@/path/to/icon",
    width: 128,
    height: 128,
    anchorY: 128
}
}
}
```

I the next thing is when I use the if to get these red icons.
![weird icon](https://user-images.githubusercontent.com/64754588/100555162-e7a72800-3256-11eb-9326-b78ef7ec8fab.PNG)


@Pessimistress

**Comment by Pessimistress** [comment]
`url` can either be an absolute address or a relative path. 

I can't tell you what's wrong from a screenshot. Please fix your code sandbox.

**Comment by acebelowzero** [comment]
https://codesandbox.io/live/8illwe3

**Comment by acebelowzero** [comment]
line 94 is where the issue is

**Comment by acebelowzero** [comment]
I am using a path and the image cannot be found

**Comment by Pessimistress** [comment]
> I am using a path and the image cannot be found

Delete your deck.gl code and just create a few `<img>` elements. Test your path until you can see them rendered. This is not a deck.gl issue.

**Comment by acebelowzero** [comment]
Let me try to find the right path
