### ISSUE TITLE
Display density graph

### ISSUE THREAD

**Issue by henriktorget** [visgl/deck.gl#5215]
Hey!

I am looking into using Deck.gl for the Ocean Data Foundation. 
Have currently been following the documentation, but can't get anything to show from my own data. 

I am at a standstill. Could someone please see if there is anything I have been missing?

```
 const [aggegateedAisData, setAggregatedAisData] = React.useState<any>([])
  
  React.useEffect(() => {
    const agg = aisData.map(d => { return ({ COORDINATES: [d.lat, d.lon] }) })
    /**
     * [
     *  {COORDINATES: [ 59.8906, 10.758 ]},
     *  ...,
     * ]
     */
    console.log(agg);
    setAggregatedAisData(agg)
  }, [aisData])

  return <ReactMapGL
    style={style}
    {...viewport}
    onViewportChange={(viewport) => setViewport(viewport)}
    mapboxApiAccessToken={"Our Token"}
  >
    <DeckGL
      viewState={viewport as ViewStateProps}
      layers={[new GridLayer({
        id: 'grid-layer',
        data: aggegateedAisData,
        pickable: true,
        extruded: true,
        cellSize: 20,
        elevationScale: 4,
        //@ts-ignore
        getPosition: d => d.COORDINATES,
      })]}
    />
  </ReactMapGL>`

**Comment by Pessimistress** [comment]
deck.gl coordinates follow the GeoJSON convention (lon, lat not lat, lon).

PS you don't need to remap your input data. Just use `getPosition: d => [d.lon, d.lat]`

**Comment by henriktorget** [comment]
![image](https://user-images.githubusercontent.com/5030524/101014272-eaab5c80-3565-11eb-89ea-353d98b57be2.png)
It's now rendering something. Not sure how useful this is yet but a starting point. Thanks a lot for the quick response. @Pessimistress 👍
