### ISSUE TITLE
Per-feature z-index

### ISSUE THREAD

**Issue by ibesora** [visgl/deck.gl#5216]
#### Target Use case
When dealing with a single layer with multiple features (like points in an MVT for example), you might want to draw some of those features on top of others interactively

#### Proposed feature
Have a getZIndex or similar function that can be defined per feature similar to how getRadius or getFillColor are implemented in some layers

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
There is no concept of "z-index" in deck.gl. In instanced rendering, the features are drawn in parallel, instead of a sequential order. It is possible to add a small depth shift to each geometry to achieve that effect, however it may interfere with the actual 3d depth. We are unlikely able to add this as a generic feature. It will have to be applied on a case-by-case bases.

**Comment by ibesora** [comment]
Thank you for your answer, I can see how that might be a problem.
I've seen some issues saying that points support 3d coordinates where the first two coords are the latitude and longitude pair and the third one a height. 
Do you think what I'm asking could be done providing a geometry transform function to the layer that's called per geometry vertex before rendering? I'm thinking about leaving both x and y coordinates the same but changing the z one to move a feature up and down. That would effectively result in what I want.

**Comment by Pessimistress** [comment]
You can add the small z shift in most layers' `getPosition` accessor. `GeoJsonLayer` hides the accessor with an implementation to the GeoJSON spec. If your tiles contain only points, you can always supply your own `renderSubLayers`:

```js
new MVTLayer({
  ...
  renderSubLayers: props => new ScatterplotLayer({
    getPosition: (f, {index}) => f.geometry.coordinates.concat(index * 0.001),
	...
  });
});
```

**Comment by ibesora** [comment]
For documentation purposes in case somebody wants to do the same using an MVT layer and arrives here. The following code works:

```javascript
new MVTLayer({
  ...
  renderSubLayers: (props) => {
    return new ScatterplotLayer({
      ...props,
      getPosition: (f, index): => {
        const z = index * 0.01
        return [
           ...f.geometry.coordinates,
          z
        ]
      }
    })
  }
}
```
Notice that, as we are passing the props from the MVTLayer to the ScatterplotLayer, it inherits the modelview matrix and the coordinate system origin and we can use the data fetched by the MVT layer as is. If, otherwise, we don't pass the MVTLayer props to the ScatterplotLayer, we will need to convert the MVT data coordinates to world coordinates.

**Comment by amandakoster** [comment]
Hello All,

Happy to have found this example. However, I am using a GeoJsonLayer which does not have the accessor `getPosition`. GeoJsonLayer does [render the following sublayers:](https://deck.gl/docs/api-reference/layers/geojson-layer#sub-layers) SolidPolygonLayer, PathLayer and ScatterplotLayer. Of these, only [ScatterplotLayer](https://deck.gl/docs/api-reference/layers/scatterplot-layer) has the getPosition accessor. How would I add a `z-index `to Scatterplot subLayer of a GeoJsonLayer?

Thanks in advance! Amanda

**Comment by Anand2489** [comment]
@amandakoster you can try [getpolygonoffset](https://deck.gl/docs/api-reference/core/layer#getpolygonoffset) to offset complete layer along the z-axis. It's a base layer property, so should solve your case too

**Comment by jzzfs** [comment]
@amandakoster what worked for me in my `GeoJsonLayer` was to sort the `data` so that the features that need to be "on top" are rendered **last**.
This applies both to the initial render and all [subsequent re-renders](https://deck.gl/docs/developer-guide/performance#avoid-unnecessary-shallow-change-in-data-prop) — e.g. in an `onHover` callback.

**Comment by jzzfs** [comment]
@chriszrc I suppose you'll have to split the layers into circles & text.

**Comment by chriszrc** [comment]
@jzzfs I originally did split the layers, but then the labels are still on top of everything :(

**Comment by gabrielmilitaruwebmarc** [comment]
@chriszrc did you manage to fix the issue? I have the same problem.

**Comment by chriszrc** [comment]
@gabrielmilitaruwebmarc nope 😥

**Comment by alonzoalden** [comment]
@chriszrc I'm wondering the same thing, been trying to figure this out for several months now.  

I found this older thread: https://github.com/visgl/deck.gl/discussions/5672 

Apparently setting a text-background, or setting a "z" position on the position used work, but I have not been successful in when trying either of these.

Have you found anything new?
