### ISSUE TITLE
Using DataFilterExtension with a none sequential filter

### ISSUE THREAD

**Issue by tamir-jether** [visgl/deck.gl#5217]
I want to filter some data using the DataFilterExtension.
I would like to filter the data using some attribute X. From the api can see my only option is to give him a sequence filter. e.g: [0,100].
Is there any way to filter values in a non sequential  way?
For example i would like to show values in those ranges:
[0,50], [100,200], [300,500]

thanks!

**Comment by Pessimistress** [comment]
`filterRange` is sent to GPU as a uniform, therefore it cannot support more sophisticated logic. You can always update `getFilterValue` to use arbitrary criteria:

```js
const bands = [[0,50], [100,200], [300,500]];

new SomeLayer({
  ...
  extensions: [new DataFilterExtension({size: 1})],
  getFilterValue: d => {
    return bands.some(range => d.value >= range[0] && d.value <= range[1]) ? 1 : 0;
  },
  filterRange: [0.5, 1.5],
  updateTriggers: {
    getFilterValue: bands
  }
});
```

**Comment by tamir-jether** [comment]
I see, putting the "logic" inside the getFilterValue instead.
Thanks.
