### ISSUE TITLE
MVT rendering artifacts

### ISSUE THREAD

**Issue by thomasgwatson** [visgl/deck.gl#5220]
Hey folks,

Trying to chase down where some rendering artifacts might be emerging.

Any hints on how to debug would be appreciated (I had a look at prior tickets but didn't find any that seemed relevant).

Challenge:
- At different zoom levels, MVTs with polyline data are showing some glitches in their rendering.
- Sometimes this inconsistency resolves after a pause on zooming: (implying that some zoom levels are rendering fine, and/or there are too many features and it is taking time to render them accurately)

I wonder if there is a discrepancy between the schema of MVT used by the MVT service we are using, and how deck.gl is expecting the MVT to look like.

At times it looks like the glitching features are just displaced; that they have the wrong cartesian coordinates for the tile zoom level being used. And that once the zoom is changed, the new tile arrives and the features are re-rendered, the glitching features 'snap' back into place

Some pics that demonstrate this:

low-zoom, you can see the 'confetti' effect where some features are displaced
<img width="344" alt="Screen Shot 2020-12-03 at 14 37 41" src="https://user-images.githubusercontent.com/5193218/101101011-762fe800-357c-11eb-99eb-c1de83dd108d.png">L

Zoom in, different features seem displaced
<img width="873" alt="Screen Shot 2020-12-03 at 10 45 21" src="https://user-images.githubusercontent.com/5193218/101100994-6e704380-357c-11eb-9caf-91cde491a48e.png">

After a few moments of processing (perhaps the higher zoom tile loads)
<img width="843" alt="Screen Shot 2020-12-03 at 10 45 26" src="https://user-images.githubusercontent.com/5193218/101101006-73cd8e00-357c-11eb-83d7-a92d6546c0e7.png">

Little video of what it can show up as:
https://youtu.be/czyEF3xow9U

**Comment by neokore** [comment]
Hi @thomasgwatson!
I'm trying to reproduce your bug, but I can't. Can you share with us an example where this bug happens? Looking at the video and screenshots, looks like it could be caused by a geometry optimization bug, but I'm not sure if it could be caused by the MVT data or the renderer, so it would be nice to have an example to work with.
Thanks!

**Comment by thomasgwatson** [comment]
@neokore I cross-posted this to the Data Hub team (the providers of the MVTs) and they think it is an issue on their side.

They shared:
"I think this is due to the mvt served from datahub. Current, when requesting mvt the coordinates are "adjusted" to 512 pixelsize with no extend. So, the data is not "detailed" enough be used on higher zoom levels then the requested. "overzooming" is the term here.
This is not adjustable by the user but clearly should"

I'll work with them to resolve, guessing we can close this issue. Thanks for your follow up, very appreciated

**Comment by 0xflumedev** [comment]
Hi @neokore @thomasgwatson I am experiencing similar over at https://github.com/visgl/deck.gl/issues/6966 but not with polylines.
