### ISSUE TITLE
getDashArray() dash and gap specifications sometimes causing unexpected solid rendering 

### ISSUE THREAD

**Issue by Schroedernick2** [visgl/deck.gl#5235]
#### Description

There seems to be a bug with specifying the dash and gap size in `getDashArray()` It seems that if the gap size plus the dash size is larger than the distance between vertices then that section renders as solid. Documentation regarding how `dashSize` and `gapSize` are used and information about what units they correspond to could be beneficial here.

#### Repro Steps
Example: https://codesandbox.io/s/deckglreact-map-gl-forked-y8f2l?file=/src/App.js
In the codesandbox example, the specified gap size is very large in `getLaneMarkerDashArray()` and it seems because of this the whole section between vertices renders as solid.

#### Environment
 - Framework Version: deck.gl 8.2.8
 - Browser Version: Chrome 87.0.4280.88
 - OS: Mac OS X 10.15.7

**Comment by Pessimistress** [comment]
See https://deck.gl/docs/api-reference/extensions/path-style-extension#tips-on-rendering-dash-lines

`LaneLayer` is not part of deck.gl. You need to open an issue in streetscape.gl.
