### ISSUE TITLE
HeatmapLayer does not support COORDINATE_SYSTEM.METER_OFFSETS

### ISSUE THREAD

**Issue by romanIlyushin-bc** [visgl/deck.gl#5248]
#### Repro Steps
Use heatmap layer [example](https://deck.gl/docs/api-reference/aggregation-layers/heatmap-layer),add `coordinateSystem` and `coordinateOrigin` params. 
```
const layer = new HeatmapLayer({
  id: 'HeatmapLayer',
  data: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/sf-bike-parking.json',
  getPosition: d => d.COORDINATES,
  radiusPixels: 25,
  coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS,
  coordinateOrigin: [-122.4, 37.74, 0]
});
```
Yes, I know about mercator projection, but the layer just totally disappears instead of being rendered with wrong coordinates. 

Heatmap layer should either support METER_OFFSETS, either explicitly note in the docs that it's not supported yet.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.3.0
 - Browser Version: all
 - OS:  Mac OS X 10.15.7

#### Logs
No warnings

**Comment by Pessimistress** [comment]
Fixed in 8.4.12.
