### ISSUE TITLE
[Google Maps] Icon disappearing in satellite mode on higher zoom level

### ISSUE THREAD

**Issue by vivek091195** [visgl/deck.gl#5249]
The icon layer is disappearing at higher zoom levels in satellite mode but appears fine in normal mode. Default layer config being used by me is - 
 
```
      new IconLayer({
          id:'data-layer',
          data:this.props.map.Icons,
          pickable: true,
          iconAtlas:dataIncons,
          iconMapping:dataMappings,
          sizeScale: 150,
          sizeMinPixels: 24,
          sizeMaxPixels: 48,
          getPosition: d => d.coordinates,
          getIcon: d => d.icon,
          onClick: info => this.iconClick(info),
      }),
```

deck.gl versions- 
```
    "@deck.gl/aggregation-layers": "^8.2.8",
    "@deck.gl/core": "^8.2.8",
    "@deck.gl/google-maps": "^8.3.0",
    "@deck.gl/layers": "^8.2.8",
```

PFA screenshot,
Normal mode-
<img width="1154" alt="Screenshot 2020-12-10 at 2 59 41 PM" src="https://user-images.githubusercontent.com/31046026/101754036-5018c380-3af9-11eb-8532-fb522cd135e5.png">

Satellite mode-
<img width="1120" alt="Screenshot 2020-12-10 at 2 59 28 PM" src="https://user-images.githubusercontent.com/31046026/101754111-6161d000-3af9-11eb-83c3-8890e20e1c58.png">

**Comment by AdriSolid** [comment]
I supposed you are using `@deck-gl/google-maps` ?
If you can provide a CodePen to test it will be useful!

**Comment by vivek091195** [comment]
@AdriSolid Yes, I am using `@deck-gl/google-maps` version 8.3.0

**Comment by AdriSolid** [comment]
@vivek091195 are you able to provide a Codepen/CodeSandbox?

**Comment by vivek091195** [comment]
Hi @AdriSolid , I have created a fiddle for the same, 
In satellite mode, at a certain zoom level, the icons are getting disappeared.
PFB fiddle link for the same,
[https://jsfiddle.net/vivekkumar091195/7a9t8zxv/](url)

**Comment by AdriSolid** [comment]
@vivek091195 thanks!
You can bypass this, setting `tilt` to `0` in your map config:
```javacript
{
  ...mapConfig,
  tilt: 0
}
```

**Comment by Pessimistress** [comment]
Tilting is not supported in GoogleMapsOverlay, see: https://deck.gl/docs/api-reference/google-maps/overview#supported-features-and-limitations
