### ISSUE TITLE
GeojsonLayer fillColor not working for MultiPolygon

### ISSUE THREAD

**Issue by sneha1404** [visgl/deck.gl#5257]
#### Description

Bug: FillColor is only applied to the first polygon in multipolygon array
Expected Behaviour : FillColor should be applied to all the polygons in Multipolygon array
Codepen Sample : https://codepen.io/sneha1404/pen/yLagmvQ?editors=0010

#### Environment (please complete the following information):
 - Framework Version:  Deck.gl 8.2.8
 - Browser Version: Chrome 87.0.4280.88
 - OS: Mac OS X 10.15

#### Logs
No error in browser console

**Comment by kylebarron** [comment]
Your GeoJSON is invalid: polygons must follow the right hand rule and your second polygon has incorrect winding order. You can test on https://geojsonlint.com/

**Comment by Pessimistress** [comment]
`MultiPolygon` coordinates must be an array of polygons, each polygon being an array of rings.

Your feature contains only one polygon, which has 3 rings. The first ring is interpreted as the outer boundary (filled), and the subsequent rings are interpreted as holes (not filled).

See [GeoJSON specification](see https://tools.ietf.org/html/rfc7946#section-3.1.7).

**Comment by charlieforward9** [comment]
[`@turf/rewind`](https://turfjs.org/docs/api/rewind) solved it for me
