### ISSUE TITLE
Extend Image Props to RGB

### ISSUE THREAD

**Issue by ilan-gold** [visgl/deck.gl#5258]
#### Target Use case
As of recent (#5197), the `BitmapLayer` (and others) use the new prop type for images.  Generally speaking, though, as is pointed out in the new [`BitmapLayer` docs](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/layers/bitmap-layer.md#image-stringtexture2dimageimagedatahtmlcanvaselementhtmlvideoelementimagebitmapobject), the `image` object is more general and works with three attributes, `data`, `height,` and `width`.  `data` needs to be an RGBA-formatted array but this makes it hard to use the `BitmapLayer` shaders/features for `RGB` data without re-adding `loadTexture` code and forcing it to be called or adding an alpha channel.  I understand that you can pass in your own texture, but it would be easier if the `RGB` format could be inferred.

#### Proposed feature
Check if `data.length === image.height * image.width * 3` to see if `GL.RGB` should be used as `dataFormat`/`format` explicitly here (instead of luma's default RGBA):
https://github.com/visgl/deck.gl/blob/f633c8c580c536bc8e97b99df0bc08bea3549df0/modules/core/src/utils/texture.js#L31-L34
I'm not sure how well that check would literally play out (I think it would work for `ImageBitmap` objects but not others) but something like it would be nice.  I also understand if this is outside the bounds of what the `image` prop should do, and we should be passing in textures, although this might be hard with `TileLayer` since you don't have access to `this.context.gl` in `renderSubLayers`, I think.  I would need to investigate this one.
#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by kylebarron** [comment]
You can now pass an object that will be passed as props to luma.gl's Texture2D constructor, so it should give the user complete options I believe. Does that work for you?

**Comment by ilan-gold** [comment]
@kylebarron I hadn't thought of that but now reading the docs more closely, I see it is clear.  Let me try that.

**Comment by ilan-gold** [comment]
@kylebarron The issue is that you need to store you `image` object along with all of its props before it is saved in whatever state it is going to be saved in (like in `TileLayer`) - otherwise, if you edit the `image` object when creating the sub layer, the referential equality is broken which slows things down a lot, like:

```javascript
const { data, width, height } = this.state;
const image = data.length === width * height * 3 ?
 { data, width, height, format: GL.RGB } :
 { data, width, height }; // RGBA
return new BitmapLayer({ image, ...sharedLayerProps });
```
So the other option is to intercept the data returned from whatever loader you are using before the data is saved in state, which is OK but feels a bit weird.  I would like if deck.gl could handle this but I understand if it is outside the bounds of what an `image` is as a prop (since `image` is mostly tied to browser objects which are RGBA).

**Comment by kylebarron** [comment]
> So the other option is to intercept the data returned from whatever loader you are using before the data is saved in state, which is OK but feels a bit weird

Yes, but not sure why this is a bad approach?

```js
function getTileData() {
	const data = loadZarr();
	const imageParams = createTextureParams(data);
	return {data, **imageParams}
}
```

Why would you need to change texture params after you load the image?

**Comment by ilan-gold** [comment]
I get caught up in some weird things when writing code and this is one of those things :) But no matter, I agree with the sentiment that it would be too much to check all of the combinations.  I will close this.  Thanks for the help.
