### ISSUE TITLE
Hover tooltip keeps open statically when moving the map in mobile

### ISSUE THREAD

**Issue by neokore** [visgl/deck.gl#5260]
#### Description
When you are using Deck.gl in a mobile phone using a hover tooltip and try to center the map after touching on a feature, the tooltip keeps open in its original place until you touch in another place.

#### Repro Steps
1 - Prepare a map with a points layer and hover tooltips for the features
2 - Set the behavior to center the map on the selected feature after clicking on them.
3 - Touch in a feature far from the center of the screen
![image](https://user-images.githubusercontent.com/938057/102457565-37516600-4043-11eb-8376-39cc2608c206.png)
4 - The map will move to center the feature on the screen but the tooltip will keep open in the original place
![image](https://user-images.githubusercontent.com/938057/102457654-6071f680-4043-11eb-8bfa-b1ed1b2e38ec.png)

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.3.8
 - Browser Version: Chrome v86
 - OS: Android 10

**Comment by Pessimistress** [comment]
Well this is technically expected... The built-in tooltip only updates when you move the pointer, not when the viewport is programmatically manipulated. There are more scenarios that could break the tooltip, e.g. your app could update the data in the scatterplot layer, and there is no way for the tooltip to know. This is usually where an app starts implementing its own tooltip.

In your case, do you expect the tooltip to go away or move with the object? Suppose we make the tooltip "smarter", it is still hard to predict the desirable behavior. Maybe we need a method to explicitly update/clear the tooltip content?

**Comment by neokore** [comment]
In our case, removing the tooltip would be enough, but I can't find how to do it with the built-in tooltip. Do Deck.gl has any method to hide it programmatically?

**Comment by Pessimistress** [comment]
Not yet, that would be a feature request.

**Comment by Pessimistress** [comment]
While we work on this, you can clear the tooltip with:

```js
deck.tooltip.setTooltip(null);
```

**Comment by neokore** [comment]
Thank you @Pessimistress, I'll try it

**Comment by Pessimistress** [comment]
This will be fixed in 8.5.0.

**Comment by Pessimistress** [comment]
Fix is included in `8.5.0-alpha.2`.
