### ISSUE TITLE
ScenegraphLayer not show when using the object loaded by GLTF loader

### ISSUE THREAD

**Issue by sunyonglincanada** [visgl/deck.gl#5274]
#### Description

I was using the ScenegraphLayer along with GLTF loader to load content from the glb file. The logic is I want to save the glb file using the loader to cache when the file loads the first time, then I will fetch the object from cache and assign it to the ScenegraphLayer as the value of scenegraph. However, the layer - animated boxes did not show up when using the object loaded by the GLTF loader but the getScene did get the scenegraph I sent in.

#### Repro Steps

Using ScenegraphLayer and GLTF loader
Screenshot when using object - https://imgur.com/a/P9Pa9aV

Codepen Example - https://codepen.io/sunyonglincanada/pen/dypzEYx
#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.3.11
 - Browser Version: Chrome 87.0
 - OS: Mac OS X 10.14

**Comment by Pessimistress** [comment]
You are overwriting `getScene` with a function that returns `undefined`. Comment it out and it will work.

**Comment by sunyonglincanada** [comment]
Thanks for the updates! It works fine after removing the getScene.

One more question is that I am trying to load ScenegraphLayer using the object from the cache by LocalForage. But it pops up an error - **deck: error during initialization of ScenegraphLayer({id: 'ScenegraphLayer'}) Error: luma.gl: assertion failed.
    at assert (0.chunk.js:56955)** The thing is I logged the object from the cache before sending it in the scenegraph and it is the same as the one that using gltf loader - https://imgur.com/a/H1SzTLQ

Here is the gist for my code - https://gist.github.com/sunyonglincanada/6fe79b8035b8c3f045abd4f37d1e0ca0

**Comment by Pessimistress** [comment]
Please use Discussions for Q&A. This issues is being closed since it's not a bug.

**Comment by sunyonglincanada** [comment]
sorry about that. will do. Thanks
