### ISSUE TITLE
Is there a way to load las file(point cloud data) as Tile3DLayer on map?

### ISSUE THREAD

**Issue by daqjjang** [visgl/deck.gl#5275]
Hi, I am just a beginner with Web and Deck.gl . 
I just wonder whether there is a way to load las file on map. 
 
import React, {useState} from 'react';
import {render} from 'react-dom';
import {StaticMap} from 'react-map-gl';
import DeckGL from '@deck.gl/react';
import {Tile3DLayer} from '@deck.gl/geo-layers';
import {COORDINATE_SYSTEM} from '@deck.gl/core';
import {CesiumIonLoader} from '@loaders.gl/3d-tiles';
import {Tiles3DLoader} from '@loaders.gl/3d-tiles';
import {PointCloudLayer} from '@deck.gl/layers';
import {LASWorkerLoader} from '@loaders.gl/las';
// import {PLYWorkerLoader} from '@loaders.gl/ply';
import {registerLoaders} from '@loaders.gl/core';

// Additional format support can be added here, see
// https://github.com/visgl/loaders.gl/blob/master/docs/api-reference/core/register-loaders.md
registerLoaders(LASWorkerLoader);
// registerLoaders(PLYWorkerLoader);

// Data source: kaarta.com
const LAZ_SAMPLE =
'http://localhost:8080/metuArch.las';
const layers3d = [
  new PointCloudLayer({
    id: 'laz-point-cloud-layer',
    data: LAZ_SAMPLE,
    coordinateOrigin: [ 126.97, 37.56],
    coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS,
    getNormal: [0, 1, 0],
    getColor: [255, 255, 255],
    opacity: 0.5,
    pointSize: 0.5
  })
];
  return (
    <DeckGL layers={[layers3d]} initialViewState={initialViewState} controller={true}>
      <StaticMap reuseMaps mapStyle={mapStyle} preventStyleDiffing />
    </DeckGL>
  );
}

export function renderToDOM(container) {
  render(<App />, container);
}

**Comment by Pessimistress** [comment]
Please read the pinned #5234 and only open issue following templates. Head to discussion for general help.

**Comment by daqjjang** [comment]
Oh, I see. Thanks for the notification.
