### ISSUE TITLE
TextLayer does not behave as documented for getTextAnchor

### ISSUE THREAD

**Issue by andreasg123** [visgl/deck.gl#5281]
#### Description

`getTextAnchor` in `TextLayer` is documented to have [this default](https://deck.gl/docs/api-reference/layers/text-layer#gettextanchor):
```
x => x.textAnchor || 'middle'
```
The actual default is `'middle'`: https://github.com/visgl/deck.gl/blob/8.3-release/modules/layers/src/text-layer/text-layer.js#L83

This means that data with `textAnchor` properties is not processed as expected.

`getAlignmentBaseline` and `getPixelOffset` also do not have the documented defaults.

Please update the implementation or the documentation.

**Comment by Pessimistress** [comment]
Thanks for reporting. The documentation has been updated.
