### ISSUE TITLE
H3HexagonLayer transition prop not being passed down to sublayer

### ISSUE THREAD

**Issue by josephlevenson** [visgl/deck.gl#5286]
#### Description

H3HexagonLayer transitions do not work as they are not passed down to the sublayer

#### Temporary Workaround
See https://github.com/visgl/deck.gl/discussions/5283#discussioncomment-248471

#### Environment:
 - Framework Version: 8.3.11

**Comment by Pessimistress** [comment]
Fixed in 8.3.12
