### ISSUE TITLE
run npm i $deck.gl/arcgis, get error

### ISSUE THREAD

**Issue by luojiandan** [visgl/deck.gl#5292]
![deck](https://user-images.githubusercontent.com/5663556/103418766-18b6a780-4bcb-11eb-9414-d7a0ce4a23c4.png)

```javascript
 npm i @deck.gl/rcgis
```

无法使用展开运算符“@”以在表达式中引用变量。只能将“@deck”作为命令的参数。要在表达式中引用变量，请使用“$deck”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

**Comment by dfellis** [comment]
It looks like Powershell uses the Perl-ism of `$` and `@` to refer to scalar and array variables, respectively: https://blog.netwrix.com/2018/10/04/powershell-variables-and-arrays/

I'm not on Windows, but try `npm i "@deck.gl/arcgis"` to work around your shell's mangling of the command?

**Comment by luojiandan** [comment]
@dfellis Thanks:)
```javascript
npm i "@deck.gl/arcgis"
```
it works!
