### ISSUE TITLE
use cdn normal but use moudle appear error

### ISSUE THREAD

**Issue by hahaxiaowai** [visgl/deck.gl#5294]
#### Description
I use loader.gl and  deck.gl to load 3Dtile in mapbox, At the begining, I use cdn to get Tile3DLayer and MapboxLayer, It's working，I successfully loaded the Tile3DLayer, but when I use npm to import @deck.gl/geo-layers and @deck.gl/mapbox, It always reports errors ：Cannot read property 'ArcLayer' of undefined ，I'm not use ArcLayer. Just use mapbox and geo-layers.
Is it my usage error？Or there is an error here.
not work:
``` js
import {registerLoaders} from "@loaders.gl/core";
import {DracoWorkerLoader} from "@loaders.gl/draco";
import {CesiumIonLoader} from "@loaders.gl/3d-tiles";
import {Tile3DLayer} from "@deck.gl/geo-layers";
import {MapboxLayer} from "@deck.gl/mapbox";
```
work:
``` js
import {registerLoaders} from "@loaders.gl/core";
import {DracoWorkerLoader} from "@loaders.gl/draco";
import {CesiumIonLoader} from "@loaders.gl/3d-tiles";
const {Tile3DLayer, MapboxLayer}  = window.deck;
```

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 8.3.12
 - Browser Version: [e.g. Chrome 87.0]
 - OS: [e.g. Win10]

#### Logs
Cannot read property 'ArcLayer' of undefined

**Comment by Pessimistress** [comment]
Can you create a CodeSandbox that reproduces this issue?

**Comment by hahaxiaowai** [comment]
It's working in CodeSandbox When I install @deck.gl/core, @deck.gl/mesh-layers and @deck.gl/layers ,Although I don't use it. 
But when I use the rollup to pack it, It's going to have the problems That I'm talking about，and Packaging error：'global' is not exported by node_modules\probe.gl\env.js,

**Comment by Pessimistress** [comment]
`@deck.gl/layers` and `@deck.gl/mesh-layers` are peer dependencies of `@deck.gl/geo-layers`: https://unpkg.com/browse/@deck.gl/geo-layers@8.3.12/package.json

**Comment by hahaxiaowai** [comment]
Thanks to answer,  I still have a problem to solve,  Why did I report an error using rollup packaging

``` node
[!] Error: 'global' is not exported by node_modules\probe.gl\env.js, imported by node_modules\@deck.gl\core\dist\esm\lib\init.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules\@deck.gl\core\dist\esm\lib\init.js (3:9)
1: import { registerLoaders } from '@loaders.gl/core';
2: import { ImageLoader } from '@loaders.gl/images';
3: import { global } from 'probe.gl/env';
            ^
4: import log from '../utils/log';
5: import { register } from '../debug';
Error: 'global' is not exported by node_modules\probe.gl\env.js, imported by node_modules\@deck.gl\core\dist\esm\lib\init.js
```

**Comment by Pessimistress** [comment]
The issue is likely in your rollup config. I suggest you follow the link in the error message to see what options you can tweak. Go to [discussions](https://github.com/visgl/deck.gl/discussions) and share your bundler setup if you still need help debugging.

**Comment by hahaxiaowai** [comment]
Thank you for your help，I'll try to find a solution in the discussions

**Comment by jeffpeck10x** [comment]
@hahaxiaowai I'm having the same issue, trying to rollup with deck.gl
```
[!] Error: 'global' is not exported by ../../node_modules/probe.gl/env.js, imported by ../../node_modules/@deck.gl/core/dist/esm/lib/init.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
../../node_modules/@deck.gl/core/dist/esm/lib/init.js (3:9)
```

In googled and this is the only place where it otherwise came up.

Did you find a solution for using rollup?

**Comment by ibgreen** [comment]
We already did a push a while back to replace the problematic `probe.gl/env` import with a proper `@probe.gl/env` module and conversion to `globalThis`.  I suspect you are using an older version of deck.gl as the problematic file in your error message no longer contains that import.

https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/init.js#L46
