### ISSUE TITLE
pickMultipleObjects MVTLayer

### ISSUE THREAD

**Issue by ralphking** [visgl/deck.gl#5295]
#### Description

It seems that pickMultipleObjects on an MVT layer is giving the same behaviour as these previous issues:

https://github.com/visgl/deck.gl/issues/2478
https://github.com/visgl/deck.gl/issues/2563

It returns copies of a single info object, up to the depth set in the arguments, rather than individual objects.

#### Repro Steps

1) Create/use an MVT Layer
2) call pickMultipleObjects in the usual way 

Expected - you get multiple info objects back up to the depth you have set in the parameters

Actual - you get multiple instances of the same object, in an array the length of the depth passed as a parameter

Using the deck codepen for MVT layer, you can switch on picking, and pop the below into onClick method to see the issue:

```
 const pickedMultipleObjects = layer.context.deck.pickMultipleObjects({ x, y , depth: 5})
```

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.5
 - Browser Version: Chrome 87.0.4

**Comment by Pessimistress** [comment]
This is fixed in 8.3.13.

**Comment by ebbishop** [comment]
I'm seeing this show up again in 8.8.20.

**Comment by GeospatialMax** [comment]
getting this behaviour as well (in 8.8.20). Same layers and objects are picked until max depth, see screenshot below

![image](https://user-images.githubusercontent.com/16649402/208306452-32ca7262-2785-4c56-b199-abeec6430d60.png)

**Comment by Pessimistress** [comment]
This issue was about an older version of deck.gl. Please do not reply to closed issues.
