### ISSUE TITLE
Abort tile requests when creating a new Tileset2D

### ISSUE THREAD

**Issue by andreasg123** [visgl/deck.gl#5297]
#### Target Use case

When experimenting with changing z-slices quickly in [Viv](https://github.com/hms-dbmi/viv), I noticed that tiles from previously visible z-slices continued loading, delaying the loading of tiles for the currently visible z-slice. I believe that Viv uses `updateTriggersChanged.getTileData` to make `TileLayer` create a new `Tileset2D`: https://github.com/hms-dbmi/viv/issues/337

#### Proposed feature

When a new `Tileset2D` is created, the previous one just gets abandoned:
https://github.com/visgl/deck.gl/blob/8.3-release/modules/geo-layers/src/tile-layer/tile-layer.js#L78

I would like to request that all pending tile requests in the previous `Tileset2D` are aborted before the new tile set is created.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ilan-gold** [comment]
I think we can close this now, @Pessimistress ?

**Comment by Pessimistress** [comment]
Fixed in `deck.gl@8.4.0-alpha.6`
