### ISSUE TITLE
Issue with mapbox

### ISSUE THREAD

**Issue by Cbarrow98** [visgl/deck.gl#5307]
Hello,

Apologies for the rudimentary question, however i am stuck on how to set my Mapbox API key within jupyter as in the code structure it does not give a clear answer.

I tried:

token = open("https://api.mapbox.com/tokens/v2/cbarrow98?access_token=pk.eyJ1IjoiY2JhcnJvdzk4IiwiYSI6ImNramxmOHZ1aTBhaWgyc3FlamNhMHR4ejQifQ.PzpAaQqpSRwO4664gXqaRQ").read()     # you will need your own token 

However this doesn't work ?

Any suggestions

 thanks you

**Comment by Pessimistress** [comment]
Please read the pinned #5234 and only open issue following templates. Head to discussions for general help.
