### ISSUE TITLE
TextLayer wordBreak default value is invalid

### ISSUE THREAD

**Issue by anthonynorth** [visgl/deck.gl#5311]
#### Description
The default value for [`wordBreak`](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/layers/text-layer.md#wordbreak-string-optional) prop on TextLayer is not a valid wordBreak value: [`word-break`](https://github.com/visgl/deck.gl/blob/master/modules/layers/src/text-layer/text-layer.js#L75). 

Valid options are `break-word`, `break-all`.

**Comment by Pessimistress** [comment]
Fixed in 8.3.14
