### ISSUE TITLE
TileLayer opacity changes from white to gray

### ISSUE THREAD

**Issue by prostgles** [visgl/deck.gl#5319]
#### Description

Thanks a lot for this amazing library!

I'm trying out the TileLayer functionality and I've noticed that as the opacity lowers the image fades to gray. At 0 opacity, however, it becomes fully white.
Would it be possible to make it fade to white (as in the last example) instead of gray?

`opacity: 0.4`
![image](https://user-images.githubusercontent.com/67743060/104246428-e411de00-545d-11eb-8d9b-c5b7321684aa.png)

`opacity: 1`
![image](https://user-images.githubusercontent.com/67743060/104246836-977ad280-545e-11eb-8a26-48a69c93cf42.png)

openlayers opacity: 0.4
![image](https://user-images.githubusercontent.com/67743060/104247936-8a5ee300-5460-11eb-97e9-a820c3a42ac8.png)

```
/*
 * https://deck.gl/docs/api-reference/geo-layers/tile-layer
 */
const {DeckGL, TileLayer, BitmapLayer} = deck;

const layer = new TileLayer({
  id: 'TileLayer',
  data: 'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png',
  opacity: 0.4,
  
  maxZoom: 19,
  minZoom: 0,
  renderSubLayers: props => {
    const {
      bbox: {west, south, east, north}
    } = props.tile;

    return new BitmapLayer(props, {
      data: null,
      image: props.data,
      bounds: [west, south, east, north]
    });
  },
  pickable: true,
});

new DeckGL({
  
  initialViewState: {
    longitude: -122.4,
    latitude: 37.74,
    zoom: 11,
    maxZoom: 20,
    pitch: 30,
    bearing: 0
  },
  controller: true,
  getTooltip: ({tile}) => tile && `x:${tile.x}, y:${tile.y}, z:${tile.z}`,
  layers: [layer]
});
  
```

Thanks!

#### Expected Behavior
TileLayer to fade to white as the opacity approaches 0

#### Environment
 - Framework Version: https://unpkg.com/deck.gl@latest/dist.min.js
 - Browser Version: Chrome latest
 - OS: [e.g. Mac OS X 10.15 / iOS 14.2]

**Comment by kylebarron** [comment]
You should be able to change the `BitmapLayer` `transparentColor` to white: https://deck.gl/docs/api-reference/layers/bitmap-layer#transparentcolor

**Comment by prostgles** [comment]
Thanks a lot for the quick response!

I've set `transparentColor: [255,255,255,255],` and now it works as I wanted
