### ISSUE TITLE
Tile3DLayer opacity/visibility not updating

### ISSUE THREAD

**Issue by brncsk** [visgl/deck.gl#5322]
#### Description
Changes to the `opacity` or `visible` keys in the JSON declaration are not reflected in the state of `Tile3DLayer` instances.
(This happens both when using the playground or `@deck.gl/json` directly). AFAICT no other layer produces such behavior.

#### Expected Behavior
`Tile3DLayer` opacity/visibility reflects changes to the JSON declaration.

#### Repro Steps
1. Open https://deck.gl/playground/.
2. Select any of the `Tile3DLayer` examples.
3. Modify JSON to include an `opacity` key with a value less than `1` or a `visible` key set to `false`.
4. Observe opacity/visibility not changing.

(Also reproducible using `@deck.gl/json` from npm directly).

#### Environment
 - Framework Version: 8.3.11
 - Browser Version: Chrome 88.0
 - OS: macOS 10.15

**Comment by Pessimistress** [comment]
Fixed in `deck.gl@8.4.0-alpha.6`, will be part of the v8.4 release

**Comment by brncsk** [comment]
@Pessimistress Thank you, I just tried and upgrading to `deck.gl@8.4.0-alpha.6` does indeed solve this problem.
