### ISSUE TITLE
s2 cells render incorrectly when they cross antimeridian

### ISSUE THREAD

**Issue by supersonicclay** [visgl/deck.gl#5372]
#### Description
s2 cell boundaries are rendering incorrectly when they cross the antimeridian

![image](https://user-images.githubusercontent.com/469582/105515395-dea06900-5c91-11eb-9755-200e731c030e.png)

#### Repro Steps
https://codesandbox.io/s/s2-antimeridian-bug-2xxko

#### Environment
 - Framework Version: deck.gl 8.3.14
 - Browser Version: Chrome
 - OS: Mac OS X

**Comment by Pessimistress** [comment]
Fixed in 8.3.15
