### ISSUE TITLE
Window Resizing Does not Work as it did in 8.3.X

### ISSUE THREAD

**Issue by ilan-gold** [visgl/deck.gl#5375]
#### Description

When you resize the window it seems to compress the canvas and/or offset it.  This might be desired i.e this is what should happen and is the result of a fix in #5371 #5350 or #5348.

#### Expected Behavior

The behavior from previous versions of deck.gl is maintained.  Are there upgrade docs somewhere maybe?  I looked at hte CHANGELOG and upgrade guide but didn't see anything.

#### Repro Steps
Resize the window in both examples - the old version maintains the image, but the new one does not (see screenshots):
Previous (8.3.14): https://codesandbox.io/s/cool-joliot-7nmoo?file=/package.json
Now (8.4.0-beta.1): https://codesandbox.io/s/sad-frost-y4hfu?file=/package.json
Before resize:
<img width="675" alt="Screen Shot 2021-01-23 at 11 10 49 AM" src="https://user-images.githubusercontent.com/43999641/105607349-2267a100-5d6c-11eb-9889-a141b513e42d.png">
After:
<img width="488" alt="Screen Shot 2021-01-23 at 11 11 23 AM" src="https://user-images.githubusercontent.com/43999641/105607354-272c5500-5d6c-11eb-8bce-c61caba09a57.png">

#### Environment
 - Framework Version: 8.4.0-beta.1
 - Browser Version: Firefox 84.0.2
 - OS: Mac OSX 10.4.16

#### Logs
N/A

**Comment by Pessimistress** [comment]
This issue is upstream in luma.gl.

**Comment by ilan-gold** [comment]
Thanks @Pessimistress!!!!

**Comment by Pessimistress** [comment]
Fixed in `@luma.gl/engine@8.4.0-beta.2`
