### ISSUE TITLE
GeoJSON Formatting Problem for PyDeck and Deck

### ISSUE THREAD

**Issue by stevenjbark** [visgl/deck.gl#5383]
Hello Everyone,
I am trying to generate my own geojson files for use in PyDeck and Deck. When I compare my own geojson with the geojson for Vancouver data, I can find no differences other than the contents of the files. The formatting appears to be equivalent and I have validated both geojson/json files using JSONLint. However, when I try to use this file in the same manner as the Vancouver example, I have the following error in the Inspect Element console. Major problem appears to be that my geojson file does not have geometry. However, I can validate this file does have geometry in the proper formatting as far as I can tell. I have reformatted to be identical to Vancouver data, but cannot resolve this issue. I can provide lines for the geojson file, but the entire file is over 15 meg so I would upload to a GoogleDrive or something like that if helpful. Any ideas would be greatly appreciated.

This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/. mapbox-gl.js:29:4643
deck: error during initialization of GeoJsonLayer({id: 'e3eb5d9d-6583-4aea-808b-78453ae31f31'}) Error: GeoJSON does not have geometry
    v assert.js:3
    value log.js:109
    m geojson.js:70
    value geojson-layer.js:113
    value layer.js:568
    value layer.js:539
    value layer-manager.js:331
    value layer-manager.js:295
    value layer-manager.js:254
    value layer-manager.js:181
    value layer-manager.js:156
    value deck.js:278
    setProps deckgl.js:118
    value deck.js:640
    value deck.js:675
    value animation-loop.js:282
    n animation-loop.js:155
layer-manager.js:232:6
    value layer-manager.js:232
    value layer-manager.js:334
    value layer-manager.js:295
    value layer-manager.js:254
    value layer-manager.js:181
    value layer-manager.js:156
    value deck.js:278
    setProps deckgl.js:118
    value deck.js:640
    value deck.js:675
    value animation-loop.js:282
    n animation-loop.js:155
deck: error during update of GeoJsonLayer({id: 'e3eb5d9d-6583-4aea-808b-78453ae31f31'}) Error: GeoJSON does not have geometry
    v assert.js:3
    value log.js:109
    m geojson.js:70
    value geojson-layer.js:113
    value layer.js:568
    value layer.js:551
    value layer-manager.js:351
    value layer-manager.js:221
    value layers-pass.js:32
    value layers-pass.js:11
    value deck-renderer.js:61
    value deck.js:653
    value deck.js:332
    value deck.js:705
    value animation-loop.js:289
    value animation-loop.js:381
    value animation-loop.js:181
    e animation-loop.js:321
layer-manager.js:232:6
WebGL warning: generateMipmap: Tex image TEXTURE_2D level 0 is incurring lazy initialization. texture.js:215:18
Geometry exceeds allowed extent, reduce your vector tile buffer size 3 bf4a5724-4d2e-42a9-b00b-af61ece05468:1:4615
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 17 mapbox-gl.js:29:308011
deck: error during update of GeoJsonLayer({id: 'e3eb5d9d-6583-4aea-808b-78453ae31f31'}) Error: GeoJSON does not have geometry
    v assert.js:3
    value log.js:109
    m geojson.js:70
    value geojson-layer.js:113
    value layer.js:568
    value layer.js:551
    value layer-manager.js:351
    value layer-manager.js:221
    value layers-pass.js:32
    value layers-pass.js:11
    value deck-renderer.js:61
    value deck.js:653
    value deck.js:332
    value deck.js:705
    value animation-loop.js:289
    value animation-loop.js:381
    value animation-loop.js:181
    e animation-loop.js:321
layer-manager.js:232:6
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 15 mapbox-gl.js:29:308011
WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings) mapbox-gl.js:29:308011
deck: error during update of GeoJsonLayer({id: 'e3eb5d9d-6583-4aea-808b-78453ae31f31'}) Error: GeoJSON does not have geometry
    v assert.js:3
    value log.js:109
    m geojson.js:70
    value geojson-layer.js:113
    value layer.js:568
    value layer.js:551
    value layer-manager.js:351
    value layer-manager.js:221
    value layers-pass.js:32
    value layers-pass.js:11
    value deck-renderer.js:61
    value deck.js:653
    value deck.js:332
    value deck.js:705
    value animation-loop.js:289
    value animation-loop.js:381
    value animation-loop.js:181
    e animation-loop.js:321
layer-manager.js:232:6

**Comment by Pessimistress** [comment]
Please only open issues using templates. Head to Discussions for Q&A.
