### ISSUE TITLE
eventManager link is broken

### ISSUE THREAD

**Issue by bmg817** [visgl/deck.gl#5390]
#### Link
This link has a reference to EventManager documentation: https://deck.gl/docs/api-reference/react/deckgl#properties
If you follow the link, you get a 404 error. 

This is the exact link the docs reference: https://github.com/uber-web/mjolnir.js/blob/master/docs/api-reference/core/event-manager.md

#### Description
Please provide a working link to the EventManager documentation

**Comment by Pessimistress** [comment]
Thanks for reporting. This has been fixed.
