### ISSUE TITLE
GeoJSON Geometry Not Identified in PyDeck

### ISSUE THREAD

**Issue by stevenjbark** [visgl/deck.gl#5391]
#### Description

Using a GeoJSON file I created (and this works in other programs like Leaflet), validated in several GeoJSON validation programs.
Attempt to use PyDeck using GeoJsonLayer as indicated in pydeck.gl/gallery/geojson_layer.html.
Map shows up for Texas, but no GeoJsonLayer.
Using the PyDeck GeoJSON example as a starting point (https://pydeck.gl/gallery/geojson_layer.html).

#### Expected Behavior

Expected (hoping?) to have choropleth map of Texas that could use Population as an elevation. Only see map, no geojson layer.
Viewed Inspect Element in Firefox AND Chrome. Error of no geometry. However, I can see geometry in dictionary keys.

#### Repro Steps

- 
Load Dataset (Home-Build GeoJSON) in Jupyter Notebook as df2
https://drive.google.com/file/d/1w1jZagVbBGR0dzvkzNEKUp-Zfl96jBdY/view?usp=sharing

#Step 3: Set mapping initial state, viewport location, information, and initial view coordinates for mapping.
view_state = pdk.ViewState(
    longitude=-97.73,
    latitude=30.27,
    zoom=5,
    min_zoom=6,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36
    )

#Step4: Set map layer to overlay on viewport location. GeoJsonLayer enables use of get_elevation to set value 
#for mapping from dataframe data.
geojson = pdk.Layer(
    "GeoJsonLayer",
    df2,
    opacity=0.8,
    stroked=False,
    filled=True,
    extruded=True,
    wireframe=True,
    get_elevation="Population",
    get_fill_color="[255, 255, Population * 255]",
    get_line_color=[255, 255, 255],
)

#Step 5: Combine layers and initial view state, render in Deck
r = pdk.Deck(layers=geojson, 
    initial_view_state=view_state, 
    mapbox_key=api_key,
    )

#Step 6: Output to show or to html
r.to_html("txcounties_pop_test.html")

#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]
 - Browser Version: [e.g. Chrome 78.0]
 - OS: [e.g. Mac OS X 10.15 / iOS 14.2]
pydeck 0.5.0
Chrome Version 88.0.4324.104 (Official Build) (64-bit)
Windows 10

#### Logs

deck: error during initialization of GeoJsonLayer({id: 'fb0cf270-2a0e-4466-a9dd-bb0bd03bafc7'}) Error: GeoJSON does not have geometry

**Comment by kylebarron** [comment]
I took a look at your geojson file. Not sure where you've tried to validate it but it's not a valid geojson file.

![image](https://user-images.githubusercontent.com/15164633/106093451-8fbd5e00-60ed-11eb-9462-922344c1ee2a.png)

1. The top level data is a list. According to the GeoJSON spec, only JSON objects/maps are valid GeoJSON constructs, though many applications like deck.gl support a list of **`Features`**.
2. Each element of your list is a `FeatureCollection`, not a `Feature`. If you're going to use `FeatureCollection`s you should have a single `FeatureCollection` without having an Array
3. The value of `Features` is an object, it should be an array

I suggest you refer to the [GeoJSON spec](https://tools.ietf.org/html/rfc7946)

**Comment by kylebarron** [comment]
Closing as this is not an issue with deck.gl/pydeck.
