### ISSUE TITLE
Pydeck orthographic polygon layer not working as expected

### ISSUE THREAD

**Issue by cornhundred** [visgl/deck.gl#5392]
#### Description
The polygon layer is not rendering correctly when using the Orthographic view in PyDeck. I am following the instructions on how to use this layer from this discussion: https://github.com/visgl/deck.gl/discussions/5291

#### Expected Behavior
I expect to see the polygon rendered in a similar manner to how it is rendered in the default view. The rendered polygon using the Orthographic view appears as a circular star-like set of polygons, implying something has gone wrong with the processing of the coordinates.

#### Repro Steps
This [notebook](https://github.com/cornhundred/pydeck_orthographic_polygon_test/blob/master/Polygon_Example.ipynb) from this repo (https://github.com/cornhundred/pydeck_orthographic_polygon_test) shows how can can load in polygon coordinate data and visualize it correctly using the default view, but it is not rendered correctly using the orthographic view. See screenshots below

<img width="875" alt="Screen Shot 2021-01-27 at 11 00 54 PM" src="https://user-images.githubusercontent.com/8352840/106088220-89ca7b80-60f3-11eb-9201-7cd24c4ec755.png">

<img width="877" alt="Screen Shot 2021-01-27 at 11 01 25 PM" src="https://user-images.githubusercontent.com/8352840/106088257-9f3fa580-60f3-11eb-9806-1e3c1e0e2820.png">

<img width="882" alt="Screen Shot 2021-01-27 at 11 01 58 PM" src="https://user-images.githubusercontent.com/8352840/106088283-b1214880-60f3-11eb-9e47-d6140caf8b92.png">

#### Environment
 - Framework Version: pydeck 0.5.0
 - Browser Version: Version 87.0.4280.141 (Official Build) (x86_64)
 - OS: Mac OS X 10.15.6

#### Logs
No relevant console logs

**Comment by cornhundred** [comment]
I'm seeing a similar problem when using deck.gl on Observable https://observablehq.com/@cornhundred/deck-gl-polygon-layer

**Comment by cornhundred** [comment]
The line layer is working as expected in the orthographic view https://observablehq.com/@cornhundred/deck-gl-line-layer-orthographic-view (toggle between views in the second cell)

**Comment by Pessimistress** [comment]
This is not a bug. If you examine your data, the x, y coordinates are very close together. The size of each edge segment is on the scale of `0.001`. In your polygon layer notebook, the path width is set to `1`, and in your path layer one the width is `100` (`getWidth * widthScale`). When you use the default view (i.e. the `MapView`), x and y are interpolated as longitude and latitude in degrees, and width is in meters. When you use `OrthographicView`, all of x, y, and width are in the same unit. You can find more information on this page: https://deck.gl/docs/developer-guide/coordinate-systems#supported-coordinate-systems

Set `getWidth`/`getLineWidth` to `0.0001` will fix both your examples.

**Comment by cornhundred** [comment]
Thanks @Pessimistress!!
