### ISSUE TITLE
Error "Unimplemented type: 4" when using IconLayer from a MVTLayer

### ISSUE THREAD

**Issue by neokore** [visgl/deck.gl#5453]
#### Description
When loading the icon image `iconAtlas` for an IconLayer loaded as sublayer of a MVTLayer (or CartoLayer) it returns a `deck: Unimplemented type: 4` error and doesn't load the layer. It happens with Deck.gl v8.4 but not with v8.3 with which it works properly.

#### Expected Behavior
Icon layer loads properly.

#### Repro Steps
Try this code from Codepen: https://codepen.io/neokore/pen/NWrOpeo

#### Environment
 - Framework Version: deck.gl 8.4.0
 - Browser Version: Chrome and Firefox at least
 - OS: OSX and Linux at least

**Comment by neokore** [comment]
After debugging a bit deeply it looks like it is trying to load the `iconAtlas` image in the `load` function from loaders.gl using the parser for MVT layers, and therefore throws this error code that I relate with an error parsing MVT data, but I'm not completely sure.

**Comment by kylebarron** [comment]
I believe the unimplemented type is coming from the MVTLoader. I think that's a low level error in the Mapbox vector tile parsing code

**Comment by neokore** [comment]
Yeah, but it seems that is deck.gl what sends the config for the loader, because when debugging I got to the `load` function with the image URL and the MVT config in options as parameters, so I thought that this could be the problem, as it may use an "Image loader" or something similar for this type of data, am I right?

**Comment by Pessimistress** [comment]
I know what's going on. I'll put up a fix.

**Comment by neokore** [comment]
That's great! Thank you @Pessimistress!

**Comment by Pessimistress** [comment]
Fixed in 8.4.3
