### ISSUE TITLE
@deck.gl/react: setting `zoom` and `transitionDuration` together doesn't trigger transition

### ISSUE THREAD

**Issue by nekitk** [visgl/deck.gl#5458]
#### Description
Starting with `8.4.0-beta.1` when changing `zoom` together with `transitionDuration` and passing it via `viewState` prop to Deck.GL, zoom change doesn't animate.

#### Expected Behavior

In `8.3.15` and `8.4.0-alpha.6` zoom is animating:
https://codesandbox.io/s/deckgl-transitionduration-840-alpha6-5t5di?file=/src/Deck.js
Try clicking +/- buttons:
![20210210133140](https://user-images.githubusercontent.com/7345182/107498229-8bd91380-6ba4-11eb-88ce-70985b02c303.gif)

#### Repro Steps

Example in CodeSandbox: https://codesandbox.io/s/deckgl-transitionduration-840-iykiy?file=/src/Deck.js
![reproduce](https://user-images.githubusercontent.com/7345182/107498481-e6726f80-6ba4-11eb-991a-4334c480c5df.gif)

Reduced example:
```jsx
const Deck = () => {
  const [viewState, setViewState] = useState(INITIAL_VIEW_STATE);
  const handleZoom = (delta) => () =>
    setViewState((state) => ({
      ...state,
      zoom: state.zoom + delta,
      transitionDuration: 300
    }));

  return (
    <>
      <button onClick={handleZoom(+1)}>+</button>
      <button onClick={handleZoom(-1)}>-</button>
      <DeckGL
        viewState={viewState}
        onViewStateChange={({ viewState }) => setViewState(viewState)}
        controller={true}
      >
        <StaticMap />
      </DeckGL>
    </>
  );
};
```

#### Environment
 - Framework Version: 8.4.0-beta.1, 8.4.0, 8.4.2
 - Browser Version: Chrome 88.0.4324.146
 - OS: Mac OS 10.15.7

#### Logs
No relevant errors

**Comment by Pessimistress** [comment]
Thanks for reporting! Fixed in 8.4.3.
