### ISSUE TITLE
TileLayer Obscures TextLayer Labels With Map Pitch

### ISSUE THREAD

**Issue by jfuehner** [visgl/deck.gl#5468]
#### Description
When tilting the map that uses deck's TextLayer and TileLayer the TextLayer labels are obscured/fall through the TileLayer tiles

#### Expected Behavior
Ideally the TextLayer labels would not be obscured by the TileLayer tiles

#### Repro Steps
I have put together a Codepen [example](https://codepen.io/jfuehner/pen/MWbbGGp) that reproduces the issue using the TextLayer and TileLayer examples from the deck website.

#### Environment
 - Framework Version: deck.gl 8.4.3
 - Browser Version: Chrome 87.0
 - OS: Windows 10 and Mac OS X 11.1

#### Logs
Nothing found in console.

**Comment by Pessimistress** [comment]
#3544
