### ISSUE TITLE
pydeck api_keys dict not working properly

### ISSUE THREAD

**Issue by karosc** [visgl/deck.gl#5474]
#### Description
When assigning an API key using the api_keys dict, it is not saved as a pydeck property.

#### Expected Behavior
given
`r = pdk.Deck(layer, initial_view_state=view_state, api_keys={'mapbox':mapbox_api_token})`

I would expect `r.mapbox_key=mapbox_api_token` but instead  `r.mapbox_key=None`

#### Repro Steps
create a Deck object with an api token using the api_keys dict

#### Environment
 - Python 3.8
 - pydeck 0.6.0

#### Logs
- Not browser reelated

**Comment by ajduberstein** [comment]
Thanks for identifying the bug and fixing it, @karosc. [pydeck 0.6.1](https://pypi.org/project/pydeck/0.6.1/) includes your change.
