### ISSUE TITLE
tile-3d-layer: absence of `normals` fails loading

### ISSUE THREAD

**Issue by belom88** [visgl/deck.gl#5484]
#### Description

I improve `I3SLoader` to support DRACO compressed geometry.
https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_3DObjects_1_7/SceneServer
doesn't contain `normals` attribute and loading fails.

#### Expected Behavior

The layer is shown correctly.

**Comment by Pessimistress** [comment]
Fix landed in 8.4.6
