### ISSUE TITLE
Column-geometry - inconsistent winding order

### ISSUE THREAD

**Issue by igorDykhta** [visgl/deck.gl#5491]
#### Description
With culling enabled the top caps of hexbins are invisible.

#### Expected Behavior
The top cap geometry should be visible for hexbins layer without extrusion.

#### Repro Steps
1) Enable winding for Deck (cull: true)
2) Create h3 layer, looks good with and without extrusion.
3) Create hexbins layer, the top caps are invisible when the layer isn't extruded

**Comment by Pessimistress** [comment]
Fix landed in 8.4.6
