### ISSUE TITLE
GeoJson layer on OrthographicView initial render is incorrect.

### ISSUE THREAD

**Issue by tech-meppem** [visgl/deck.gl#5522]
#### Description

Using a geojson layer on orthographic view starts out as the mercator projection, even though it's not using that view.
The reason we want to use the OrthographicView is because we want the equirectangular projection, not mercator.
It works after zooming/panning, and looks correctly, except a couple of random lines that appear.

![deck-gl-zoom-snapping](https://user-images.githubusercontent.com/54634811/108848581-11af8280-75d9-11eb-8367-09545f04ed40.gif)

#### Expected Behavior
The projection should be consistent, and not suddenly change after zooming/panning.

#### Repro Steps

Example test file: https://gist.github.com/tech-meppem/5a40e00b04220e924177791b4982be0f
GeoJSON: https://gist.github.com/tech-meppem/0fff9cc0147b992406e579607533f42e

#### Environment
 - Framework Version: deck.gl 8.4.7
 - Browser Version: Chrome: Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by Pessimistress** [comment]
`longitude` and `latitude` are not valid `OrthographicView` states and falsely flag the viewport as geospatial. While the view itself should check against this, if you remove them from your `initialViewState` it will work as expected.

**Comment by tech-meppem** [comment]
Yeah, that works, and gets rid of the error lines too!
Thanks.

**Comment by Pessimistress** [comment]
This is fixed in 8.4.8.
