### ISSUE TITLE
GridCellLayer vertical shift

### ISSUE THREAD

**Issue by carlostxm** [visgl/deck.gl#5523]
#### Description
GridCellLayer draws cells shifted vertically. the problem seems to be related with the vertex used. According to the documentation it should render cells taking coordinates as the top-left corner but it drawing the cells using coordinates as the bottom-left corner which produces a vertical shift.

#### Expected Behavior
Take given coordinates as top-left corner or update documentation with the current behaviour.

#### Repro Steps
See the example provided:
https://codepen.io/carlostxm/pen/JjbOEMM

#### Environment
 - Framework Version: deck.gl@latest

**Comment by Pessimistress** [comment]
Thanks for reporting. The documentation has been updated.
