### ISSUE TITLE
Different errors with different 3d-tiles (b3dm)

### ISSUE THREAD

**Issue by ikemarv** [visgl/deck.gl#5529]
#### Description

I have used different building data in b3dm format and get different errors except for one data source.
- My institution's own data with its own conversion tools:
`tileset-3d.js:481 A 3D tile failed to load: undefined Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`
- Open Data of North Rhine-Westphalia (Germany) or Hanover (Germany), converted by pg2b3dm (converted data NRW: https://github.com/ikemarv/test-itowns-nrw/tree/master/apps/data/lod2_nrw ):
No error, but buildings are not visible and it zooms into the Indian Ocean
- data of Manhattan by JoeThunyathep from https://github.com/visgl/deck.gl/issues/4582#issuecomment-627283569 : 
`tileset-3d.js:481 A 3D tile failed to load: undefined Unexpected token F in JSON at position [...]`
- pg2b3dm cesium sample-data of Delaware https://github.com/Geodan/pg2b3dm/tree/master/sample_data/delaware/cesium : 
WORKS!

The first two data are displayed in the correct place in CesiumJS.
On the page with the examples at loaders.gl, all 3D tiles examples that do not have the data source via Cesium Ion do not work either.

#### Repro Steps

I used the 3d-tiles example ( https://github.com/visgl/deck.gl/tree/master/examples/website/3d-tiles ) and just replaced the tile3DLayer:

> const tile3DLayer = new Tile3DLayer({
>     id: 'tile-3d-layer',
>     data: './data/buildings/tileset.json',
>     //data: './data/lod2_nrw/tileset.json',
>     //data: './data/Manhattan/tileset.json',
>     //data: './data/delaware-cesium-pg2b3dm/tileset.json',
>     loader: Tiles3DLoader,
>     loadOptions: {
>       isTileset:true
>     },
>     onTilesetLoad
>   });

#### Environment
 - Framework Version: deck.gl 8.4.6
 - Browser Version: Chrome 88.0
 - OS: Mac OS X 11.2.1

**Comment by ibgreen** [comment]
@ikemarv Thanks for reporting.

3D Tile loading in deck.gl is handled by loaders.gl - would you consider opening this issue there instead?
