### ISSUE TITLE
GeoJsonLayer material will be wrong when dragrotate the map

### ISSUE THREAD

**Issue by chinesejar** [visgl/deck.gl#5530]
#### Description
I use GeoJsonLayer in Deck.GL with React, it shows as follow:

geojson data file: https://drive.google.com/file/d/1I_50OaMSqvlS5Z01MdLfeUcN4f_gVI7C/view?usp=sharing

```
const colors = [
  [0, 172, 164],
  [192, 192, 254],
  [122, 114, 238],
  [30, 38, 208],
  [166, 252, 168],
  [0, 234, 0],
  [16, 146, 26],
  [252, 244, 100],
  [200, 200, 2],
  [140, 140, 0],
  [254, 172, 172],
  [254, 100, 92],
  [238, 2, 48],
  [212, 142, 254],
  [170, 36, 250],
];
const dbz = [-5, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70];

<GeoJsonLayer
  id="product"
  data={data}
  stroked={false}
  getFillColor={(feature) => {
    const color =
      colors[dbz.indexOf(feature.properties.value)];
    if (color) {
      const [r, g, b] = color;
      return [r, g, b];
    }
    return [255, 0, 0];
  }}
/>
```

![good.png](https://i.loli.net/2021/02/24/ywJ9mQleN8VkvEL.png)

but as I dragrotate the map, the material of geojsonlayer will be wrong.

![worse.png](https://i.loli.net/2021/02/24/YRHajsluB5zgoQM.png)

#### Environment
 - Framework Version: deck.gl 8.4.7
 - Browser Version: Chrome 88.0.4324.182
 - OS: Mac OS X Big Sur and Windows 10

**Comment by padawannn** [comment]
Hi @chinesejar,

if you add this property to your layer it should work fine: `parameters: { depthTest: false}`

Here you have a small explanation about the problem
https://github.com/visgl/deck.gl/blob/master/docs/developer-guide/tips-and-tricks.md#z-fighting-and-depth-testing

Reopen the issue if the problem persists
