### ISSUE TITLE
DeckGL/Mapbox interleaving works locally, map flickers in production

### ISSUE THREAD

**Issue by mayteio** [visgl/deck.gl#5554]
[Interleaving layers between deck.gl & mapbox](https://deck.gl/gallery/mapbox-layer) is possible to make deck.gl layers sit behind mapbox labels.

This works great in development, however, in a production build it causes the map to flicker. My understanding from a [2019 issue about the same map flickering problem](https://github.com/visgl/deck.gl/issues/3280#issuecomment-505143410) is that this is caused because;

> Deck would not know that the context is being shared unless mapbox tells it so. The flashing you are seeing is because Deck thinks it's the only one drawing into the context, therefore clearing the canvas every time the viewport changes.

I am guessing this has to do with minification during `yarn run build`. I am wondering if a certain variable is being renamed that has to have a stable identity?

To reproduce:
[I have created a repository reproducing this](https://github.com/mayteio/deckgl-mapbox-interleaving) - sorry it's not a code sandbox, the issues is between dev & production.

0. `$ git clone git@github.com:mayteio/deckgl-mapbox-interleaving.git && cd deckgl-mapbox-interleaving`
1. `$ yarn`
2. `$ yarn start:dev // see working map in local dev mode @ localhost:3000`
3. In another terminal, `$ yarn start:prod // build & serve the app @ localhost:5000`

You'll notice that the map interleaves nicely on local dev, with the label for "Laranjal do Jari" sitting over the GeoJsonLayer, while in the production version the map flickers.

The interleaving happens in `src/DeckGLMapboxMap.js`:

- Line 38:39 store the deck & gl instances
- Line 42 we store a simple array of DeckGL layers
- Line 80:82 we add the MapboxLayers to mapbox
- Line 102:103 setting deck & gl instances in state
- Line 110 passing the gl instance to `<StaticMap />`

**Comment by padawannn** [comment]
@mayteio it seems to be a bug with mapbox-gl@2.0.0 you can get more information here https://github.com/visgl/react-map-gl/issues/1266 

For your case, a quick workaround could be downgraded `react-map-gl` to v5.2.11

**Comment by Pessimistress** [comment]
This is not a bug. You must defer the rendering of `<StaticMap>` until `gl` is available, as shown in [the documentation](https://deck.gl/docs/api-reference/mapbox/overview#using-with-react). Swapping out the `gl` prop after mapbox is created has no effect.

**Comment by mayteio** [comment]
> This is not a bug. You must defer the rendering of `<StaticMap>` until `gl` is available, as shown in [the documentation](https://deck.gl/docs/api-reference/mapbox/overview#using-with-react). Swapping out the `gl` prop after mapbox is created has no effect.

This had no effect, but I'll do this from now on regardless.

[This solved it for me](https://github.com/visgl/react-map-gl/issues/1266#issuecomment-753686953):

> Downgrading to v5.2.11 of `react-map-gl` was insufficient for my use case since I'm using Mapbox GL JS v2.x.x features (`setTerrain()` specifically)
> 
> For those out there in a similar spot, I was able to hack around things for the time being by adapting the suggestions in [mapbox/mapbox-gl-js#10173](https://github.com/mapbox/mapbox-gl-js/issues/10173):
> 
> Install `worker-loader`:
> 
> ```
> yarn add worker-loader
> ```
> 
> In your map component:
> 
> ```
> import ReactMapGL from "react-map-gl";
> import mapboxgl from "mapbox-gl"; // This is a dependency of react-map-gl even if you didn't explicitly install it
> 
> // eslint-disable-next-line import/no-webpack-loader-syntax
> mapboxgl.workerClass = require("worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker").default;
> ```
> 
> I hope the Mapbox team can provide a long term solution soon.

**Comment by kelvindecosta** [comment]
Hey @mayteio 

I clone your reproduction repository and played with it a little.

During `develop` the map was lagging whenever I moved.
Zooming in and out didn't affect much.

I decided to comment out a few lines and it seems to work much better now:

```diff
diff --git a/src/DeckGLMapboxMap.js b/src/DeckGLMapboxMap.js
index f189524..ec76334 100644
--- a/src/DeckGLMapboxMap.js
+++ b/src/DeckGLMapboxMap.js
@@ -119,12 +119,12 @@ export const DeckGLMapboxMap = ({
             mapboxToken || process.env.REACT_APP_MAPBOX_API_ACCESS_TOKEN
           }
           mapStyle={mapStyle}
-          onLoad={(e) =>
-            e.target.on(
-              "load",
-              () => staticMapProps.onLoad && staticMapProps.onLoad(e)
-            )
-          }
+          // onLoad={(e) =>
+          //   e.target.on(
+          //     "load",
+          //     () => staticMapProps.onLoad && staticMapProps.onLoad(e)
+          //   )
+          // }
           width={width}
         >
           {children}
```

I didn't test the `production` build without the changes.
Still, with the change, the map is as responsive as it was during `develop`.

In the documentation, it is suggested to pass `onMapLoad` as `onLoad` prop for `StaticMap`.
When reimplementing the documentation example, I experienced lagging.
I like the use of `MapContext` provider and the `useEffect` hook.

Thanks for sharing your implementation!
