### ISSUE TITLE
deck.gl MapboxLayer prevents touch scroll on mobile

### ISSUE THREAD

**Issue by derMart** [visgl/deck.gl#5564]
#### Description
Consider a Mapbox GL JS map with disabled touch navigation.
As soon as a MapboxLayer is added to the map, the webpage the map is inside is not scrollable using touch, when the touch is started over the map.

#### Expected Behavior
The webpage should be scrollable using touch, just as it would be without the MapboxLayer added.

#### Repro Steps
Open this jsbin on an Android phone and try to scroll, starting the touch over the map:
https://output.jsbin.com/buhorim/13/quiet (code: https://jsbin.com/buhorim/13/edit?html,output)
-> The scroll isn't working

When the addLayer call is commented out:
https://output.jsbin.com/buhorim/14/quiet
-> The scroll is working

It seems the MapboxLayer is doing some magic to capture the touch events and I guess somehow triggers preventDefault().
I wasn't able to find the relevant places in the deck.gl code. Any hint or any idea where / why this happens is highly appreciated, so that I can find a patch / workaround.

#### Environment
 - Framework Version: deck.gl 8.4.0
 - Browser Version: Android Chromium / Android Fennec
 - OS: Lineageos 17 / Android 10

**Comment by padawannn** [comment]
Try to add `pointer-events: none;` to the `map div`. In your example code:
```
#map {
    width: 800px;
    height: 600px;
    pointer-events: none;
  }
```

**Comment by derMart** [comment]
Thanks, yes, pointer-events: none works for the example above. However, this is just a minimal example to demonstrate the issue. In my actual use case I need pointer-events on the map. First, I need an onClick() handler on the MapboxLayer and second, I have two finger map pan (see also https://github.com/mapbox/mapbox-gl-js/issues/2618), and pinch to zoom enabled. The latter two work without the MapboxLayer. So, still any hints what the deck.gl MapboxLayer is actually doing to prevent the scroll is appreciated.

**Comment by Pessimistress** [comment]
deck.gl's event manager automatically adds `touch-action: none` to the DOM container (in this case, the Mapbox canvas). Normally, this can be controlled by the [touchAction](https://deck.gl/docs/api-reference/core/deck#touchaction) prop; however, when using `MapboxLayer` the underlying Deck instance is not exposed.

For the time being you can work around this by adding the following CSS rule:

```js
.mapboxgl-canvas {
    touch-action: auto !important;
}
```

**Comment by Pessimistress** [comment]
@padawannn An easy fix would be to add `touchAction: 'unset'` to https://github.com/visgl/deck.gl/blob/b84456dac9489a3fd313414c0a4865eedd3e3de2/modules/mapbox/src/deck-utils.js#L11

**Comment by padawannn** [comment]
@derMart we’ve just released a patch version with `touchAction: 'unset'` for this case

**Comment by kylebarron** [comment]
Just to add for future reference, this patch is `v8.4.11`.
