### ISSUE TITLE
The bitmap layer doesn't work with multi picking

### ISSUE THREAD

**Issue by alexandruandrei91** [visgl/deck.gl#5576]
#### Description
I try to get the picking information from multiple overlapping bitmap layers. When trying to use `pickMultipleObjects` on bitmap layers, I get the following error instead:
```
Uncaught TypeError: colors is undefined
    _disablePickingIndex layer.js:673
    disablePickingIndex layer.js:664
    _pickClosestObject deck-picker.js:252
    pickObject deck-picker.js:64
    _pick deck.js:364
    pickMultipleObjects deck.js:321
    pickMultipleObjects deckgl.js:89
    onClick DeckGLMap.jsx:68
```
 For more details, see this question on the discussion board: https://github.com/visgl/deck.gl/discussions/5574.

#### Expected Behavior
`pickMultipleObjects` returns all the layers, including bitmaps, together with the picking info returned by `getPickingInfo`.

#### Repro Steps
* Create a bitmap layer
* Call `pickMultipleObjects`

https://codepen.io/aalexandru/pen/yLVGgEe?editors=001

#### Environment
 - Framework Version: deck.gl 8.4.9
 - Browser Version: Firefox 86, Chrome 88
 - OS: Windows 10

**Comment by Pessimistress** [comment]
Fixed in 8.4.13
