### ISSUE TITLE
Polygons with hole look incorrectly rendered

### ISSUE THREAD

**Issue by nageguanzi** [visgl/deck.gl#5578]
#### Expected Behavior

I just want to get a mask layer like this:

![87450008-1E9D-4D8A-BC84-D1393EB6362D](https://user-images.githubusercontent.com/46484344/110908603-06cf4e80-834a-11eb-87ee-c22f856aeb98.png)
but my code works incorrectly:

![CADC9967-78B7-4586-BDB8-C4B7160C2561](https://user-images.githubusercontent.com/46484344/110906482-f669a480-8346-11eb-95ba-34c10039e9da.png)
![F95653F0-6D8A-4989-A1B4-0EE30636478F](https://user-images.githubusercontent.com/46484344/110906486-f8336800-8346-11eb-8ae3-f3106d6bae66.png)

#### Repro Steps

Here is my code about the polygon:

```javascript
  const outerPath = [
    [180, 90],
    [-180, 90],
    [-180, -90],
    [180, -90],
    [180, 90],
  ];
  const innerPath = [
    [119.892637, 31.020798],
    [119.889215, 31.016655],
    [119.88453, 31.012407],
    [119.883386, 31.011626],
    [119.878133, 31.005249],
    [119.876599, 31.000395],
    [119.876582, 30.995411],
    [119.876327, 30.982886],
    [119.886079, 30.987355],
    [119.896992, 30.985796],
    [119.899358, 30.984866],
    [119.906449, 30.98344],
    [119.915757, 30.981642],
    [119.918586, 30.981498],
    [119.92812, 30.981392],
    [119.9541, 30.986196],
    [119.955247, 30.989809],
    [119.944324, 30.991166],
    [119.944262, 30.99885],
    [119.944084, 31.009509],
    [119.944062, 31.014593],
    [119.943982, 31.020018],
    [119.94388, 31.029315],
    [119.943825, 31.035228],
    [119.936589, 31.035192],
    [119.931136, 31.035201],
    [119.928658, 31.035164],
    [119.926103, 31.035168],
    [119.921637, 31.035165],
    [119.9164, 31.035176],
    [119.912625, 31.035147],
    [119.900378, 31.035135],
    [119.90035, 31.03318],
    [119.900201, 31.030329],
    [119.894123, 31.022537],
    [119.892637, 31.020798],
  ];
  const data = [
    {
      path: [outerPath, innerPath],
    },
  ];
  const layer = new PolygonLayer({
    id: 'areaLayer',
    data,
    pickable: true,
    stroked: true,
    filled: true,
    wireframe: true,
    lineWidthMinPixels: 2,
    getPolygon: (d: any) => d.path,
    getFillColor: [0, 0, 0, 100],
    getLineColor: [80, 80, 80],
    getLineWidth: 2,
  });
```
And if I change `outerPath` to `[[180, 80], [-180, 80], [-180, -80], [180, -80], [180, 80]]`, it will looks correctly. But when zoom in, after the 'zoom' bigger than 12, it looked like this:

![255F80C6-D82E-44F7-A5EC-4386312D294E](https://user-images.githubusercontent.com/46484344/110908491-dbe4fa80-8349-11eb-9b3d-c31377ecf552.png)

#### Environment
 - Framework Version: [e.g. deck.gl 8.4.9 ]
 - Browser Version: [e.g. Chrome 89.0]
 - OS: [e.g. Mac OS X 11.2.3 (arm64) ]

**Comment by AdriSolid** [comment]
I think that's not a bug, here we are facing with the `concept of a linear ring`. The first ring should be the filled polygon, the rest are the holes.

Replace
```javascript
const data = [{ path: [outerPath, innerPath] }];
```
With
```javascript
const data = [{ path: [innerPath, outerPath] }];
```

**Comment by kylebarron** [comment]
You should check that your winding order is correct. The `PolygonLayer` assumes GeoJSON-like input

https://tools.ietf.org/html/rfc7946#section-3.1.6

> A linear ring MUST follow the right-hand rule with respect to the area it bounds, i.e., exterior rings are counterclockwise, and holes are clockwise.

You can also check the new `_windingOrder` prop: https://deck.gl/docs/api-reference/layers/polygon-layer#_windingorder

When I paste your data into [geojson.io](https://geojson.io/) I don't see a hole:

![image](https://user-images.githubusercontent.com/15164633/111234390-0fc35880-85b4-11eb-87f2-07ae47294c9c.png)

**Comment by nageguanzi** [comment]
> You should check that your winding order is correct. The `PolygonLayer` assumes GeoJSON-like input
> 
> https://tools.ietf.org/html/rfc7946#section-3.1.6
> 
> > A linear ring MUST follow the right-hand rule with respect to the area it bounds, i.e., exterior rings are counterclockwise, and holes are clockwise.
> 
> You can also check the new `_windingOrder` prop: https://deck.gl/docs/api-reference/layers/polygon-layer#_windingorder
> 
> When I paste your data into [geojson.io](https://geojson.io/) I don't see a hole:
> 
> ![image](https://user-images.githubusercontent.com/15164633/111234390-0fc35880-85b4-11eb-87f2-07ae47294c9c.png)

You don't see the hole because the hole is to small at this zoom, do you see the point on the map in China? That's the hole if you zoom in to see.

**Comment by Pessimistress** [comment]
This is because MapView switches to offset mode to improve projection precision at zoom>12. Offset mode by design does not project positions very far away from the current viewport (e.g. [-180, 80] correctly. Usually this is not an issue since the  vertex is outside the viewport and not visible. However, in polygon layer it can result in incorrect tessellation.

I suggest you use an outer ring that is much smaller - Instead of covering the entire world, make the polygon only big enough to cover a local area. Given that the hole is so small, it probably doesn't make sense to zoom all the way out anyways.

**Comment by nageguanzi** [comment]
> This is because MapView switches to offset mode to improve projection precision at zoom>12. Offset mode by design does not project positions very far away from the current viewport (e.g. [-180, 80] correctly. Usually this is not an issue since the vertex is outside the viewport and not visible. However, in polygon layer it can result in incorrect tessellation.
> 
> I suggest you use an outer ring that is much smaller - Instead of covering the entire world, make the polygon only big enough to cover a local area. Given that the hole is so small, it probably doesn't make sense to zoom all the way out anyways.

OK, thanks for your suggestion.
