### ISSUE TITLE
Pydeck: Tooltip can't show the values of extra dataframe columns in addition to colorValue in GridLayer

### ISSUE THREAD

**Issue by lyzhan** [visgl/deck.gl#5580]
#### Description

In the Gridlayer, the dataframe with extra columns such as 'TotalVehicles' in the following example code are feed into data. But the tooltip can't recognize 'TotalVehicles' to present the value as the screenshot shows.
![image](https://user-images.githubusercontent.com/42555492/110980073-72f28800-8333-11eb-8aea-358aec803ae2.png)

I also tried the default format of tooltip as setting tooltip=True. Unfortunately, the tooltip box is not wide enough to show the 'TotalVehicles' value in points as this screenshot shows.
![image](https://user-images.githubusercontent.com/42555492/110980596-ff04af80-8333-11eb-8db4-97b6bd85f683.png)

#### Expected Behavior

Hope there is some way to show the 'TotalVehicles' value in tooltip.
#### Repro Steps

Here is my example code.

```
df_dump=geotab_pop[geotab_pop['date_time']==start][['TotalVehicles','Latitude_CP','Longitude_CP','ProbabilityOfPrecipitation']]
display(df_dump.head())

grid_layer = pdk.Layer(
    "GridLayer", data=df_dump, \
        cellSize=4900, colorRange=np.flipud(colormap).tolist(),\
        pickable=True, extruded=False, elevationRange=[0, 1000],\
        getColorWeight="ProbabilityOfPrecipitation",colorAggregation=pdk.types.String("MEAN"),\
        get_position=["Longitude_CP","Latitude_CP"],coverage=1
)

view_state = pdk.ViewState(latitude=40,longitude=-90,zoom=2,bearing=0,pitch=0)
r = pdk.Deck([grid_layer,bitmap_layer], initial_view_state=view_state,height=600,\
             tooltip={"text": "POP: {colorValue}\n Tot Veh: {TotalVehicles}"})
r.show()
```

The output of df_dump.head() is here:

```
 TotalVehicles | Latitude_CP | Longitude_CP | ProbabilityOfPrecipitation
 -- | -- | -- | --
10 | 29.025879 | -99.865723 | 0.017
9 | 29.025879 | -99.074707 | 0.017
11 | 29.025879 | -99.030762 | 0.017
7 | 29.025879 | -98.591309 | 0.017
11 | 29.025879 | -98.415527 | 0.017
```

#### Environment
 - Framework Version: [pydeck 0.6.0]
 - Browser Version: [e.g. Chrome 89.0.4389.82]
 - OS: [Windows 10]

**Comment by ajduberstein** [comment]
Hey @lyzhan I believe `GridLayer` expects different picking info. You'll notice [here](https://pydeck.gl/gallery/grid_layer.html) for example that the variable `count` is mentioned in the tooltip but no where in the [original data](https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/sf-bike-parking.json). You may want to [specify a different aggregation](https://deck.gl/docs/api-reference/aggregation-layers/grid-layer#elevationaggregation) (example of this in the [ContourLayer](https://pydeck.gl/gallery/contour_layer.html)).

**Comment by ajduberstein** [comment]
I think the issue here is resolved. Closing this out but feel free to re-open.
