### ISSUE TITLE
Type 'Provider<MapContextProps>' is not assignable to type 'Provider<ContextProviderValue>'

### ISSUE THREAD

**Issue by barmettlerl** [visgl/deck.gl#5581]
Hi

I using typescript with `deck.gl` and `react-map-gl`. In order to get the types I've imported the [danmarshall/deckgl-typings ](https://github.com/danmarshall/deckgl-typings). Now I want to add the Mapbox popup layer. This, however, is not possible due a type miss mach of the deck.gl `<DeckGL/>` element and the react-map-gl `MapContext.Provider`. Do you have the same problem? Can someone help me?

Thank you 

```typescript
  <DeckGL
      initialViewState={INITIAL_VIEW_STATE}
      controller
      layers={layers}
      views={[
        new MapView({
          repeat: true,
        }),
      ]}
      ContextProvider={MapContext.Provider}
    >
      {hoverInfo && (
        <div style={{ position: 'absolute', zIndex: 100, pointerEvents: 'none', left: hoverInfo.x, top: hoverInfo.y }}>
          {hoverInfo.message}
        </div>
      )}
      <Popup latitude={37.78} longitude={-122.41} closeButton closeOnClick={false}>
        <div>You are here</div>
      </Popup>
      <StaticMap key="baseMap" mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN} />
    </DeckGL>
```

**Comment by Pessimistress** [comment]
Please only use templates to open issues. Generic Q&A should be posted in Discussions.
