### ISSUE TITLE
Geojson layer can't render path across the pacific

### ISSUE THREAD

**Issue by heshan0131** [visgl/deck.gl#5597]
#### Description
Geojson layer can't properly render path across the pacific, with `wrapLongitude: true | false`

__`wrapLongitude: false`__

<img width="1137" alt="Screen Shot 2021-03-19 at 2 24 28 PM" src="https://user-images.githubusercontent.com/3605556/111843753-f6c1ec80-88be-11eb-8619-027e59309701.png">

__`wrapLongitude: true`__

<img width="1302" alt="Screen Shot 2021-03-19 at 2 26 26 PM" src="https://user-images.githubusercontent.com/3605556/111843846-1fe27d00-88bf-11eb-8023-c8db2a736967.png">

#### Expected Behavior
Line should be able to across pacific

#### Repro Steps
Try geojson in this ticket
https://github.com/keplergl/kepler.gl/issues/1438

#### Environment
`@deck.gl/layers@8.4.10`

**Comment by Pessimistress** [comment]
You need to turn on `repeat:true` in MapView, see https://deck.gl/docs/upgrade-guide

**Comment by jeffcsauer** [comment]
Can this parameter be added to Kepler.gl in jupyter notebooks?
