### ISSUE TITLE
TextLayer rendering on same pane / z-fighting (8.5.0-alpha.x)

### ISSUE THREAD

**Issue by rkhayat** [visgl/deck.gl#5598]
#### Description
TextLayer rendering on same pane, z-fighting (8.5.0-alpha.x)

#### Expected Behavior
TextLayer stacks per 8.4

#### Repro Steps
https://codesandbox.io/s/deckgl-forked-ok3n8?file=/src/DeckGLOverlay.js
```
 new TextLayer({
          data: [
            {
              getPixelOffset: [0, 3],
              position: [-102.552784, 23.634501],
              text: "AAAAAAAAAAAAAAAAAAAAAAAAA"
            },
            {
              getPixelOffset: [0, -3],
              position: [-102.552784, 23.634501],
              text: "BBBBBBBBBBBBBBBBBBBBBBBBBB"
            }
          ],

          backgroundPadding: [8, 4],
          getColor: [180, 0, 0],
          backgroundColor: [0, 0, 0],
          getPixelOffset: (d) => d.getPixelOffset,
          getText: (d) => d.text
        })
```
#### Environment
 - Framework Version: 
- @deck.gl/core: 8.5.0-alpha.1
- @deck.gl/google-maps: 8.5.0-alpha.1
- @deck.gl/layers: 8.5.0-alpha.1

![image](https://user-images.githubusercontent.com/5125481/111852696-597eac80-88ee-11eb-9f7c-9bbc35685da4.png)

**Comment by Pessimistress** [comment]
This is one of the breaking changes from adding the new TextLayer styling features. Backgrounds are now rendered with a separate layer from the characters. You can work around this by adding a small z to each position.

**Comment by rkhayatintrepid** [comment]
> This is one of the breaking changes from adding the new TextLayer styling features. Backgrounds are now rendered with a separate layer from the characters. You can work around this by adding a small z to each position.

Thank you, when adding a z to each position, those with a difference of 1 seem to overlap, _is this intended?_

![image](https://user-images.githubusercontent.com/59570712/113514560-61209100-953d-11eb-935d-8955b87fb5e9.png)

changing it to a difference of two fixes the original issue found, _should this be in the documentation?_

![image](https://user-images.githubusercontent.com/59570712/113514611-b2308500-953d-11eb-8204-2d58d8ec1ad4.png)

**Comment by rkhayat** [comment]
> This is one of the breaking changes from adding the new TextLayer styling features. Backgrounds are now rendered with a separate layer from the characters. You can work around this by adding a small z to each position.

Thank you, when adding a z to each position, those with a difference of 1 seem to overlap, _is this intended?_

![image](https://user-images.githubusercontent.com/59570712/113514560-61209100-953d-11eb-935d-8955b87fb5e9.png)

changing it to a difference of two fixes the original issue found, _should this be in the documentation?_

![image](https://user-images.githubusercontent.com/59570712/113514611-b2308500-953d-11eb-8204-2d58d8ec1ad4.png)

**Comment by Pessimistress** [comment]
> changing it to a difference of ~3 fixes the original issue found until max zoom, should this be in the documentation?

The z offset that is needed depends on multiple viewport/WebGL statuses. You may want to try adjust/disable [getPolygonOffset](https://deck.gl/docs/api-reference/core/layer#getpolygonoffset) for more predictable results.

**Comment by rkhayat** [comment]
@Pessimistress can we move this to a discussion please?

I am having issues scaling the solution by adding random numbers.

![image](https://user-images.githubusercontent.com/5125481/114706110-932cb280-9cf6-11eb-9c23-28c226492712.png)

**Comment by rkhayat** [comment]
Reopening so we can move to discussion please
