### ISSUE TITLE
visible in MVTLayer's renderSubLayers is not effective

### ISSUE THREAD

**Issue by fifzteen** [visgl/deck.gl#5616]
#### Description
I use MVTLayer, and renderSubLayers returns two GeoJsonLayer. 
one shows always tile exists (calls "A"), and the other shows only if the zoom is over threshold (calls "B").

when zooming-in to minZoom, "A" layer is shown. That's OK.
but "B" layer is also shown even though the zoom is under threshold. 

my sample code is below.
https://codepen.io/fifzteen/pen/ExZjjLB

minzoom - maxzoom : 4 -16,
"B" threshold zoom: 14

(minzoom is 4, but tiles show from 3.5. that may be somthing wrong but not my interest. ignore it.)

#### Expected Behavior
render subLayers due to "visible" value when zooming-in to minZoom too.

#### Environment
 - Framework Version: deckgl v8.4.11
 - Browser Version: Chrome 89.0.4389.90
 - OS: MacOS 10.15

**Comment by Pessimistress** [comment]
This is expected. `renderSubLayers` is only called the first time a tile is rendered. After that, the visibility of the sub layers are toggled based on the visibility of the tile. This is designed to provide the best performance.

You can force `renderSubLayers` to be called on every redraw by adding the following prop to the MVTLayer:

```js
updateTriggers: {
  renderSubLayers: zoom
}
```

Alternatively, you can create your own CompositeLayer that handles zoom, and have your `renderSubLayers` return the custom layer.

**Comment by fifzteen** [comment]
Thank you for your answer. 

> You can force renderSubLayers to be called on every redraw by adding the following prop to the MVTLayer:

I try this. (codePen updated!)
But problem remains... at the time zooming-in to minZoom, "B" layer is shown.
(when next zoom changing, "B" layer disappears correctly.)

so I will try your second solution. 

> you can create your own CompositeLayer that handles zoom, and have your renderSubLayers return the custom layer.

**Comment by Pessimistress** [comment]
My bad - TileLayer/MVTLayer may rerender without a view state change, e.g. when a new tile is loaded, in which case the visibility of cached sub layers will still be overwritten. The way it currently works just would not allow users to directly control the `visible` prop of sub layers. We should add a remark in the documentation.

**Comment by fifzteen** [comment]
For now, I update visible flag variable on viewStateChange, and add/remove sub layers by the flags.
(This way is introduced as a bad pattern in document below, but it's reliable.)
https://deck.gl/docs/developer-guide/performance#favor-layer-visibility-over-addition-and-removal
