### ISSUE TITLE
HeatmapLayer dosen't aggregate as expect in high precision

### ISSUE THREAD

**Issue by timeless15** [visgl/deck.gl#5620]
#### Description

When I use HeatmapLayer, it dosen't aggregate as expect. I use the ScatterplotLayer to show the original data.
When zoom in the map, the scatter points obviously don't aligned to heatmap points. The heatmap points seem aligned vertically, and the layer is shaking when zooming.

![image](https://user-images.githubusercontent.com/25543532/113021923-a7c96080-91b6-11eb-909d-c5e3b1eb7dbf.png)

#### Expected Behavior

But if I remove the integer part of the coordinates, like `[120.15948104329973, 30.27054640617553]` to `[0.15948104329973, 0.27054640617553]`, it shows as expect:

![image](https://user-images.githubusercontent.com/25543532/113021939-ac8e1480-91b6-11eb-9e4a-2f4555cb3061.png)

#### Repro Steps

[Here is the code](https://codesandbox.io/s/jovial-moon-nveow?file=/src/index.js), you can click the toggle button to see different data behaviors.

I'm using Deck.GL for indoor map, which means the coordinate has more digits, and zoom level is set above 18. So I guess it's due to precision loss, I tried the `fp64` prop, but it didn't work. I still can't figure out, can anyone help me? Thanks a lot🙏

#### Environment

 - Framework Version: deck.gl 8.4.11
 - Browser Version: Chrome 89.0
 - OS: Mac OS X 10.15

**Comment by kylebarron** [comment]
Please don't create duplicate issues. For now this is tracked in https://github.com/visgl/deck.gl/discussions/5617

**Comment by Pessimistress** [comment]
This should be fixed in 8.4.12
