### ISSUE TITLE
Heatmap Layer crashes (shows and then dies) after deck.gl last update. [GL_INVALID_OPERATION : glDrawArrays: Source and destination textures of the draw are the same.]

### ISSUE THREAD

**Issue by RELNO** [visgl/deck.gl#5635]
#### Description

Heatmap layer renders once, and disappears upon pan/zoom 
These errors appear when toggling the layer on: 
![Screen Shot 2021-04-05 at 5 21 13 PM](https://user-images.githubusercontent.com/14296774/113630605-22bacd00-9636-11eb-85c1-be58bcdaaa8d.png)

#### Expected Behavior

display Heatmap layer as usual 
#### Repro Steps

Very basic heatmap setup, data format the same as in the docs

```
 return new HeatmapLayer({
      id: 'ACCESS',
      colorRange: settings.map.layers.heatmap.colors,
      radiusPixels: 50,
      opacity: 1,
      data: data,
      threshold: 0.5,
      getPosition: (d) => d.coordinates, // [lat, lon]
      getWeight: (d) => d.values[accessToggle], // [0.1, 0.5]
      updateTriggers: {
        getWeight: [accessToggle],
      },
    })
```
#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]
 - Browser Version: [e.g. Chrome 78.0]
 - OS: [e.g. Mac OS X 10.15 / iOS 14.2]
Chrome/firefox latest. 
Deckgl 8.4.11

#### Logs

Not sure if related, but these new errors also appear as of last update:

![Screen Shot 2021-04-05 at 5 44 19 PM](https://user-images.githubusercontent.com/14296774/113630902-a4125f80-9636-11eb-8cdd-9f4dcd6e0e8d.png)

**Comment by Pessimistress** [comment]
The [documentation page](https://deck.gl/docs/api-reference/aggregation-layers/heatmap-layer) is running the latest version of deck.gl (8.4.11). Please create a Codepen that reproduces your issue.

**Comment by RELNO** [comment]
@Pessimistress thanks!  issue is internal and related to infinite GL loop due to re-renders.
