### ISSUE TITLE
IconLayer-getIcon 更改width和height时无效

### ISSUE THREAD

**Issue by DominicBao** [visgl/deck.gl#5639]
在使用iconLayer的时候
![image](https://user-images.githubusercontent.com/41851914/113838617-858c9f80-97c1-11eb-8999-719950ea64f6.png)

发现无论如何更改width和height的值都不会引起icon的重新渲染

后面发现icon层内部进行了下面的逻辑处理
![image](https://user-images.githubusercontent.com/41851914/113838880-c97fa480-97c1-11eb-92cc-3f77759efc88.png)

只有当id或者url变换的时候才会重新处理icon，个人觉得这样处理不太友好，参阅了相关文档也未找到说明

猜测作者是为了降低请求icon的性能损耗这样做的，提出下面的建议不知道是否合理
width，height，anchorX等相关配置项是否可以从getIcon中抽离出来，更改他们并不会重新请求icon
或者，在文档中做出更详细的说明，如要修改width和height而不用修改url时需要修改id

**Comment by Pessimistress** [comment]
This is explained in the docs page: https://deck.gl/docs/api-reference/layers/icon-layer#geticon

> IconLayer use id (fallback to url) to dedupe icons. If for the same icon identifier, getIcon returns different width or height, IconLayer will only apply the first occurrence and ignore the rest of them.

**Comment by Jenny-YJ** [comment]
> IconLayer use id (fallback to url) to dedupe icons. If for the same icon identifier, getIcon returns different width or height, IconLayer will only apply the first occurrence and ignore the rest of them. 

I understand about that.

so How about different url?

```
getIcon: d => {
          return {
            id: d.id,
            url: makeFlowIconAtlas(flowicoDatas[d.id] ?? flowicoDatas[0], rcvDatas[d.id]?.aFlow),
            height: 100,
            width: 100,
            anchorX: 50,
            anchorY: 50,
          };
        },
updateTriggers: {
          getIcon: { rcvDatas, flowicoDatas },
        },
```

I checked about that change the url data.
sometimes  working sometimes not working,

please advice for me. thanks.
