### ISSUE TITLE
Allow an onError callback to be passed to getDeckInstance-constructed Deck via MapboxLayer

### ISSUE THREAD

**Issue by shabbyrobe** [visgl/deck.gl#5647]
#### Target Use case
It doesn't appear to be possible, if using a getDeckInstance-constructed Deck instance, to pass an onError callback to Deck, so we can't capture errors and handle them as we wish, which we'd be able to do if we were in a position to create the Deck instance ourselves (we aren't, as we are relying on the wiring that happens in deck-utils).

#### Proposed feature

Adding support for an onError callback prop to MapboxLayer, which is propagated to the Deck constructor's [onError prop](https://deck.gl/docs/api-reference/core/deck#onerror) within getDeckInstance, solves this problem for us. Usage would hopefully look something like this:

```js
const layer = new MapboxLayer({
    ...,
    onError: (...args) => { console.log("deck error:", args) },
})
```

I've whipped up a prototype diff that demonstrates a version of this that meets our needs, but is not sufficiently well developed to be PR-worthy. If there is interest in accepting this feature request I am happy to turn it into a proper PR and to adjust for any feedback:

```diff
diff --git a/modules/mapbox/src/deck-utils.js b/modules/mapbox/src/deck-utils.js
index 976488776..41e805a88 100644
--- a/modules/mapbox/src/deck-utils.js
+++ b/modules/mapbox/src/deck-utils.js
@@ -1,6 +1,6 @@
 import {Deck, WebMercatorViewport} from '@deck.gl/core';
 
-export function getDeckInstance({map, gl, deck}) {
+export function getDeckInstance({map, gl, deck, onError}) {
   // Only create one deck instance per context
   if (map.__deck) {
     return map.__deck;
@@ -38,6 +38,7 @@ export function getDeckInstance({map, gl, deck}) {
     // Using external gl context - do not set css size
     Object.assign(deckProps, {
       gl,
+      onError,
       width: false,
       height: false,
       touchAction: 'unset',
diff --git a/modules/mapbox/src/mapbox-layer.js b/modules/mapbox/src/mapbox-layer.js
index 0462a75a3..a38a054a9 100644
--- a/modules/mapbox/src/mapbox-layer.js
+++ b/modules/mapbox/src/mapbox-layer.js
@@ -19,7 +19,7 @@ export default class MapboxLayer {
 
   onAdd(map, gl) {
     this.map = map;
-    this.deck = getDeckInstance({map, gl, deck: this.props.deck});
+    this.deck = getDeckInstance({map, gl, deck: this.props.deck, onError: this.props.onError});
     addLayer(this.deck, this);
   }
```

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
We probably shouldn't pass a layer's `onError` directly to Deck. If there are multiple Mapbox layers, they could be sharing the same Deck instance, while only the `onError` of one of the layers will be called.

Have you tried [Use a Layer from an Existing Deck's Layer Stack](https://deck.gl/docs/api-reference/mapbox/mapbox-layer#use-a-layer-from-an-existing-decks-layer-stack)?

**Comment by shabbyrobe** [comment]
It's only for the case where MapboxLayer creates the Deck itself though. If MapboxLayer creates the Deck, there's no way to get a custom onError into the AnimationLoop that doesn't feel like a house of cards.

I considered passing in a prebuilt Deck in our app, but were hoping to avoid that given the number of additional things that getDeckInstance is doing for us already when it creates the Deck itself. We wanted to avoid replicating all of that (onMapMove, getViewState, etc).

It's true that my original suggestion adds a prop that makes no sense in the case when getDeckInstance _doesn't_ create the Deck, but I still feel like some control over this when it _does_ create the Deck is justified.

What about something like `deckCreateProps` callback in `deck-utils.js` instead, that allows you to pass in additional props when and only when MapboxLayer will create the Deck instance:
```js
  if (deck) {
    // --- 8< --- deck already passed --- 8< ---
  } else {
    // Using external gl context - do not set css size
    Object.assign(deckProps, {
      gl,
      onError,
      width: false,
      height: false,
      touchAction: 'unset',
      viewState: getViewState(map),
      ...(this.props.deckCreateProps || {}),
    });

    deck = new Deck(deckProps);
```

Or something like a `beforeDeckCreate` callback in `deck-utils.js`, to allow the props to be modified before being passed to the Deck constructor?
```js
  if (deck) {
    // --- 8< --- deck already passed --- 8< ---
  } else {
    // Using external gl context - do not set css size
    Object.assign(deckProps, { ... })

    deck = new Deck(
        this.props.beforeDeckCreate ?
            this.props.beforeDeckCreate(deckProps) :
            deckProps,
    )
```

**Comment by Pessimistress** [comment]
Theoretically you should be able to achieve this by setting `onError` after the deck instance is constructed:

```js
const layer = new MapboxLayer({...});
layer.deck.setProps({
  onError: (...args) => { console.log("deck error:", args) }
});
```

**Comment by shabbyrobe** [comment]
Thanks for the pointer, I didn't spot that before. I gave this a try:

```js
const layer = new MapboxLayer({...});
const map = new mapboxgl.Map({...});
map.once('idle', () => {
    map.addLayer(layer)
    layer.deck.setProps({
        onError: (...args) => {
        console.log('DECK ERROR', args)
    })
})
```

This seems to partially work, but it does not allow the onError callback to catch any errors that happen in `initializeState`, or in the first call to things like `shouldUpdateState`, as they appear to happen before MapboxLayer.onAdd returns, in the call to addLayer on line 23:

https://github.com/visgl/deck.gl/blob/2fbd91d99db7e248d45ddfe936d857d8c2b955e8/modules/mapbox/src/mapbox-layer.js#L21-L23

I will try to do a bit more digging to confirm that this is indeed what I'm seeing, but I would like to be able to catch these errors as well. Is there a way register the `onError` before the first time the layers get added to the created Deck instance?

**Comment by Pessimistress** [comment]
All layers will support an `onError` prop in v8.5. You can try it now with `8.5.0-alpha.5`.

**Comment by shabbyrobe** [comment]
Thank you! I will try it out and report back if I find any issues. I notice the roadmap document has no mention of 8.5 and the alpha has been worked on for a while; is there a rough estimate of the release for 8.5, or is it a case of "when it's ready"?
