### ISSUE TITLE
add getTileData option to TerrainLayer

### ISSUE THREAD

**Issue by farfromrefug** [visgl/deck.gl#5648]
Right now there is no way to "override" how a `TerrainLayer` load a tile terrain data.
In my case i would like to load it from an sqlite database.
I can do that by subclassing and overloading `loadTerrain` but it would be best to be able to do it the same way we can do it for `TileLayer`

**Comment by Pessimistress** [comment]
What format are you trying to load? `TerrainLayer` currently only supports color-coded height images. If you want to render your own meshes you can use `TileLayer` directly and return a `SimpleMeshLayer` with `renderSubLayers`.

**Comment by farfromrefug** [comment]
@Pessimistress it is not the question for the format i load the terrain data in. I am loading rgb images from a local sqlite database. And i am running martini in a native env and not a worker.
I am asking because it makes sense to have it the same as `TileLayer`.
Now as i said not a big deal as i can subclass. Just thought it would be nice for me and others

**Comment by Pessimistress** [comment]
You can supply a `fetch` prop to the layer:

```js
fetch: (url, {propName, layer, signal}) => {
  ...
}
```

**Comment by Pessimistress** [comment]
Looks like `fetch` is not being respected in TerrainLayer. Merging this thread with https://github.com/visgl/deck.gl/issues/5808 - this use case should be addressed there.
