### ISSUE TITLE
Text Distorts at large font sizes

### ISSUE THREAD

**Issue by mogmog** [visgl/deck.gl#5658]
#### Description
If text is very very large, then it distorts as the map is moved up and down.

#### Expected Behavior
I would expect the text to stay the same size 

#### Repro Steps
[Codepen](https://codepen.io/grahambates/pen/eYgMrEr)

https://user-images.githubusercontent.com/934073/114551561-80b16b00-9c5b-11eb-8e5a-1bbc9784c51a.mov

#### Environment
deck.gl 8.4.0

**Comment by Pessimistress** [comment]
This is expected. deck.gl calculates meter sizes based on the center of the viewport, therefore subjects to the [distortion of Mercator projection](https://en.m.wikipedia.org/wiki/Tissot%27s_indicatrix). If you wish for stable size then you should use `sizeUnits: 'pixels'`

**Comment by mogmog** [comment]
OK that makes sense.

My requirements are quite unusual in that I want the text to be large but not a stable size. If the map zooms, the text should scale with it, as if it is drawn on a paper map.

Are there any other ways I could simulate this effect?

**Comment by Pessimistress** [comment]
You can update `sizeScale` whenever zoom changes:

`sizeScale: 2 ** zoom`
