### ISSUE TITLE
MapboxLayer and Mapbox with 3D Terrain 'jumps' problem

### ISSUE THREAD

**Issue by Infl1ght** [visgl/deck.gl#5662]
#### Description
I'm trying to add 3D meshes to the Mapbox map with enabled terrain elevation data. When I move the camera, these meshes start to 'jump' (change their z-positions).
It's ok when I use a standard 2d map without terrain data.

#### Expected Behavior
3D meshes must stay at their z-positions.

#### Repro Steps
1) Load Mapbox map and set terrain elevation data.
2) Add a deck.gl SimpleMeshLayer with some meshes
3) Move camera

- A Codepen: https://codepen.io/infl1ght/pen/abpGBeZ

#### Environment
 - Framework Version: deck.gl 8.4.11 / mapbox-gl 2.1.1 / vue.js 2.6.11
 - Browser Version: Chrome 88.0
 - OS: Linux Mint 20

**Comment by ibgreen** [comment]
AFAIK, we have not yet done any serious testing of the Mapbox v2 3D mode integration with deck.gl. We do have fairly extensive testing the deck.gl TerrainLayer, though the Mapbox basemaps are of course nicer. There is likely some work that needs to be done here.

This may be an area where a strong contributor or some engagement through the Linux foundation/UCF could help us accelerate things.

**Comment by Infl1ght** [comment]
> AFAIK, we have not yet done any serious testing of the Mapbox v2 3D mode integration with deck.gl. We do have fairly extensive testing the deck.gl TerrainLayer, though the Mapbox basemaps are of course nicer. There is likely some work that needs to be done here.
> 
> This may be an area where a strong contributor or some engagement through the Linux foundation/UCF could help us accelerate things.

I like deсk.gl and I need this functionality. I could take a look and try to fix this.
Could you tell me where I should start?

**Comment by ibgreen** [comment]
> Could you tell me where I should start?

@Infl1ght I suppose on. higher level, understanding what is broken and what needs to be done is a first step.

I think for your particular case, your issues may at least partly be related to changes how mapbox v2 calculates their view. The deck.gl view matrix is calculated by `@math.gl/web-mercator` and is finely tuned to match the mapbox v1 view matrix, but mapbox v2 likely uses different calculations, and we may need to add a "mapbox v2 mode" in math.gl.

This probably requires a digging in to the mapbox v2 code and some understanding of 3D math. It depends on your background / level of interest in learning about such things whether that is something you are likely to be successful with.

I know that @chrisgervang has also been looking at this.

**Comment by chrisgervang** [comment]
When you say move camera, do you mean pitch the camera close to 90 and move it over mapbox terrain to observe jumping? 

I've noticed that mapbox doesn't allow the camera to go "under" terrain, so it will jump when panning in situations like that.

I tried the codepen, but having trouble with the repro steps.

**Comment by Pessimistress** [comment]
When terrain is enabled, Mapbox positions the camera to look at the center of the viewport with elevation. Deck does not currently handle this. The MapView's camera points at the longitude/latitude returned by `map.getCenter()` and elevation=0. A fix for this will need to look at:

- How to retrieve the elevation at a given point from Mapbox, and
- Match the projection matrix of WebMercatorViewport with that of Mapbox's.

**Comment by oscarfonts** [comment]
We've found the way to read elevation from Mapbox.

We run this onViewportChange:
```
const elevation = map.transform.elevation.getAtPoint(MercatorCoordinate.fromLngLat(map.getCenter()));
const modelMatix = new Matrix4().identity().translate([0, 0, -elevation]);
```

And then apply the matrix over deck layers, "pushing" them down to meet mapbox's terrain.

A working example here:
https://codesandbox.io/s/mapbox2-deckgl-matrix-he4ok

This is somewhat hacky, as the elevation should be handled internally.

Also, as you can see in the example, the layers are still not matching exactly. There is still a small offset depending on camera position, which we don't know how to fix.

We'll try to contribute a better patch, but we may need some guidance from you.

**Comment by Pessimistress** [comment]
Looks like you can call [map.queryTerrainElevationAt](https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/map.js)

You can add a `position` parameter to `viewState` to shift the camera up instead of shifting the geometries down. https://deck.gl/docs/api-reference/core/viewport#constructor-1

Mapbox adjusts the camera zoom based on the elevation: https://github.com/mapbox/mapbox-gl-js/blob/5624309e3abe2cd61860846c491ba87d31f44774/src/geo/transform.js#L284 which is likely the source of the discrepancy.

**Comment by cai30304** [comment]
@Pessimistress thx provide can use position to shift viewport,
But it look like can't be use onViewStateChange + setViewStates to set position
here is my code
`const onViewStateChange = ({ viewState }) => {
        
        const map = mapRef.current.getMap()
        if(map && map.transform.elevation){
            const mapbox_elevation = map.transform.elevation.getAtPoint(MercatorCoordinate.fromLngLat(map.getCenter()));
            setViewStates({
                ...viewState,
                ...{position:[0,0,mapbox_elevation]}
            });
        }else{
            setViewStates({
                ...ViewState,
                ...viewState
            });
        }
    };`
    
the viewState's position value is indeed modify, but present like zero.
i try to modify position by F12 react dev tools, it will be come back.
like this photo below, that is my setViewStates error?




https://user-images.githubusercontent.com/4905652/118603545-9da30600-b7e6-11eb-8611-cc44861f5c62.mov

**Comment by oscarfonts** [comment]
FWIW, we finally solved this by disabling horizon shift and zoom changes on mapbox code:
https://github.com/geomatico/mapbox-gl-js/compare/v2.2.0...geomatico:2.2.0-deck?expand=1

This makes both deck and mapbox cameras fit perfecty. This is still a hack, as the good solution would be to incorporate the new behaviour to deck, not to disable it in mapbox.

**Comment by bolatuly** [comment]
Is there any progress on the issue?
I guess this relates to my problem too. I have 3d tiles with real-world elevation and mapbox v2 with the terrain. Tiles are supposed to fit correctly on terrain, but instead, they are flying above the map.

**Comment by spacerunner22** [comment]
@oscarfonts tried your hack. Nothing has changed. Maybe I'm missing something.

**Comment by Pessimistress** [comment]
Merging with #7064
