### ISSUE TITLE
ScatterplotLayer radiusMinPixels set by data

### ISSUE THREAD

**Issue by cornhundred** [visgl/deck.gl#5673]
#### Target Use case
I would like to be able to control the `radiusMinPixels` parameter using the data in the same way we can control `getRadius`. This would be useful for cases where we have many points and would like to highlight a subset of points by increasing the minimum pixel radius. 

#### Proposed feature
We would be able to control the value using a function similar to 
```
getRadius: d => Math.sqrt(d.exits),
```

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Your use case should be achieved by using `sizeUnits: 'pixels'`. `sizeMinPixels` does not reflect the actual radius being rendered on screen.

**Comment by cornhundred** [comment]
Hi @Pessimistress did you mean `radiusUnits`? I could not find `sizeUnits` in the documentation https://deck.gl/docs/api-reference/layers/scatterplot-layer#radiusunits. Also, when I set `radiusUnits: 'pixels'` the scatterplot points always appeared to remain the same size when zooming in or out.

**Comment by cornhundred** [comment]
I would like to have points that get larger/smaller when zooming in/out, have a minimum size so they never get too small when zooming out (e.g. `radiusMinPixels`), and I would like to have the points have a variable value `radiusMinPixels` such that I can control their smallest representation size. For instance I would like to highlight a set of points when fully zoomed out and have those points have a larger `radiusMinPixels` than other points.

**Comment by Pessimistress** [comment]
Sorry, it should have been `radiusUnits`. I have corrected my original comment.

`radiusMinPixels` is meant to be a cheap way to prevent the radius from becoming too small. Switching a setting from per-layer to per-object introduces a [significant performance cost](https://deck.gl/docs/developer-guide/performance#favor-constants-over-callback-functions). A more important concern is that WebGL has a limit of 16 attributes per shader. By making more settings per-object (i.e. add an attribute) we will use up the valuable resource of other potential features (e.g. using the data filter extension).

Back to your use case - depending on your styling there are other options, e.g. add a stroke to the selected points, or add another layer to render the highlighted subset.

**Comment by cornhundred** [comment]
Thanks @Pessimistress, that makes sense.
