### ISSUE TITLE
TerrainLayer: some wrong polygons appear

### ISSUE THREAD

**Issue by farfromrefug** [visgl/deck.gl#5686]
#### Description

While rotating on this codepen https://codepen.io/farfromrefuge/pen/GRrYGoz?editors=0010
You can see some polygon appearing while rotating. They always disappear when you stop moving.
Feels like they are meshes from much lower zoom which randomly appear
#### Expected Behavior
you should not see random polygons appear

#### Repro Steps
open the codepen
look left / right 

#### Environment

 - Framework Version: deck.gl 8.4.13
 - Browser Version: Chrome 90  /Safari
 - OS: Mac OS X 10.15

**Comment by Pessimistress** [comment]
Please use the issue template to report bugs.

**Comment by Pessimistress** [comment]
[refinementStrategy](https://deck.gl/docs/api-reference/geo-layers/tile-layer#refinementstrategy)

**Comment by farfromrefug** [comment]
I am not sure I understand your point and I read that doc.multiple times. I did not want best available. 
and by other 2 never seemed the best and by no mean does the doc implie tiles can overlap. 
what does "not selected" mean then ? 
maybe adding screenshots to the doc showing the difference of the 3 could help future users like me.

**Comment by Pessimistress** [comment]
I agree that the doc can be improved. "Selected" tiles are the tiles that are expected to be displayed in a given viewport. This prop controls whether cached tiles from other zoom levels should be rendered while we wait for the selected tiles to load.

If you think the prop is not doing what the doc describes, then you need to update your codepen to demonstrate that. Your codepen link contains hundreds of lines of irrelevant code and cannot be used for testing. As I said in my previous comment please

> provide a clean codepen that only contains the minimal code that reproduces your issue.

**Comment by farfromrefug** [comment]
@Pessimistress here you go https://codepen.io/farfromrefuge/pen/yLgQRBL?editors=0010
Simplest of examples showing the issue. Whatever refinementStrategy you choose you can see the issue

**Comment by Pessimistress** [comment]
@chrisgervang looks like `refinementStrategy` is not passed through to `TileLayer`: https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/terrain-layer/terrain-layer.js#L210

**Comment by ibgreen** [comment]
@kylebarron @igorDykhta

**Comment by Pessimistress** [comment]
`refinementStrategy` prop is fixed in 8.4.14
