### ISSUE TITLE
how to make a continuous animation in the trips

### ISSUE THREAD

**Issue by parkjk93** [visgl/deck.gl#5693]
Hi,
I am making an example [TripsLayer.](https://github.com/visgl/deck.gl/tree/8.4-release/examples/website/trips) 
set loopLength 1800 as in the example.
when the animation time goes from 1800 to 0, Even if there is traill time left, the whole turns off and then turns on again.
like this, (red circle means time)
![image](https://user-images.githubusercontent.com/38125895/115824083-5ec99c80-a442-11eb-97fb-24a23183a9fa.png)
![image](https://user-images.githubusercontent.com/38125895/115824092-61c48d00-a442-11eb-9e18-e496ee49f12a.png)

but, in this [Example](https://deck.gl/examples/trips-layer/) Seems to be continuous

how can i make it continuous?

**Comment by Pessimistress** [comment]
Please only use templates to open issues. Go to Discussions for general Q&A.
