### ISSUE TITLE
ScreenGridLayer picking crashes in Safari

### ISSUE THREAD

**Issue by layik** [visgl/deck.gl#5699]
#### Description
`TypeError: undefined is not an object (evaluating 'results[weightId].aggregationData')`
Line in question: 
https://github.com/visgl/deck.gl/blob/master/modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js#L217

#### Expected Behavior
Handle undefined

#### Repro Steps
This sandbox example is modified but borrowed from #5620 

Just open the link and hover over the ScreenGridLayer
https://codesandbox.io/s/deckgl-issue-kjsf6

#### Environment
 - Framework Version: deck.gl 8.4.13 
 - Browser Version: Safari 14.03
 - macOS 11.2.3

#### Logs
`TypeError: undefined is not an object (evaluating 'results[weightId].aggregationData')`

Finally, my problem was not totally understanding `weightId` in lines above, otherwise got a commit which "might" resolve this by just making sure the object exists before accessing it.

**Comment by Clebal** [comment]
Hi @layik, I opened your CodeSandbox and hovered over the ScreenGridLayer and there wasn't any error.

![image](https://user-images.githubusercontent.com/9151432/116264561-aa4db480-a77a-11eb-981a-2cb395042d24.png)

**Comment by layik** [comment]
Thanks @Clebal, seems I cannot reproduce this on macOS Chrome Version 90.0.4430.93 (Official Build) (x86_64)
and FF 88.0 (64-bit).

Happy to close it if this is an obscure Safari GPU issue.

**Comment by Pessimistress** [comment]
Safari does not support GPU aggregation (requires WebGL2). You can test the behavior in Chrome by setting the prop `gpuAggregation: false`.

**Comment by layik** [comment]
Thank you @Pessimistress. Leave it open then?

**Comment by Pessimistress** [comment]
Fixed in 8.4.14
