### ISSUE TITLE
ColumnLayer: angle property has no effect

### ISSUE THREAD

**Issue by zogs** [visgl/deck.gl#5704]
#### Description
Hi, the angle property has no effect

#### Expected Behavior
Should be able to rotate the columns. This could be usefull for aligning columns when using diskResolution = 4

#### Repro Steps
https://codepen.io/zogs/pen/rNjbEyx

#### Environment
 - Framework Version: latest from https://unpkg.com/deck.gl@latest/dist.min.js
 - Browser Version: all

**Comment by AdriSolid** [comment]
That's probably a bug.

I see in [ColumnLayer vertex shader](https://github.com/visgl/deck.gl/blob/7decad2a29c156a34d7e816a45beffde55ebd49b/modules/layers/src/column-layer/column-layer-vertex.glsl.js#L59) that `mat2 rotationMatrix` is:
```javascript
 mat2 rotationMatrix = mat2(cos(angle), sin(angle), -sin(angle), cos(angle));
```
and should be:
```javascript
mat2 rotationMatrix = mat2(cos(angle), -sin(angle), sin(angle), cos(angle));
```

@Pessimistress

**Comment by Pessimistress** [comment]
`angle` should be in degrees, not radians. The documentation should be corrected.

**Comment by Pessimistress** [comment]
@AdriSolid WebGl matrices are column-major. https://en.m.wikipedia.org/wiki/Rotation_matrix
