### ISSUE TITLE
SimpleMeshLayer - implement getSizeScale method

### ISSUE THREAD

**Issue by Kris-B** [visgl/deck.gl#5722]
#### Target Use case
Possibility to have different object sizes, to avoid having to create multiple ``SimpleMeshLayer`` instances.

#### Proposed feature
Method to define different scale size for each object instance.

Replace the ``sizeScale`` property with a ``getSizeScale`` method.

**Comment by Pessimistress** [comment]
[getScale](https://deck.gl/docs/api-reference/mesh-layers/simple-mesh-layer#getscale)
