### ISSUE TITLE
Make it easier to target local math.gl in development

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#5736]
#### Target Use case
`examples/webpack.config.local.js` has support for easily configuring deck.gl to use a local copy of luma.gl while developing, by passing `local-luma` as an [environment variable](https://github.com/visgl/deck.gl/blob/763f62f4d71481ff4f7392e89136dd5f6f0a6645/examples/webpack.config.local.js#L118). It would be useful if this could be extended to other dependancies, in particular my current need is to pull in math.gl.

#### Proposed feature
Following the pattern present for luma, add an environment variable `local-math` which configures webpack to target a local copy of math.gl.

An example of how to use is to modify (for example) `examples/website/radio/package.json` and modify the `start-local` script to include the `--env.local-math` option.

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Doc update
  - [x] Test

**Comment by felixpalmer** [comment]
Regarding documentation, I think it would be helpful to document somewhere the existence of the `local-luma` (and now `local-math`) flags, but I don't know where is the best location for documentation aimed at developers enhancing deck.gl, rather than those consuming it. Thoughts @ibgreen?

**Comment by ibgreen** [comment]
We have a `dev-docs` folder with some markdown files. Not sure how maintained they are. We haven't published these on the web page but we do have the https://deck.gl/docs/contributing page. It could potentially be added there.

**Comment by felixpalmer** [comment]
I've [added a section](https://github.com/visgl/deck.gl/pull/5737/commits/aedc2f13dd2e1271cd02d16c4a89d38ff3e4131a) to the contributing page, if you're happy with the wording, I'll go ahead and merge

**Comment by ibgreen** [comment]
Sounds good.
