### ISSUE TITLE
will LineLayer support ends of the line being round?

### ISSUE THREAD

**Issue by Kaiyiwing** [visgl/deck.gl#5746]
#### Target Use case

It seems like rouned line will looks better?

or could you tell me how to generate line with round end?

#### Proposed feature

Just both ends of line being round.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Use the PathLayer with `rounded: true`.
