### ISSUE TITLE
Missing texture constants in bundle

### ISSUE THREAD

**Issue by zakjan** [visgl/deck.gl#5763]
#### Description
When using bundled distribution of deck.gl, luma.gl constants are missing in global `luma` object. I suppose that's intentional, because deck.gl bundle shouldn't expose luma.gl internals.

However, exporting at least texture constants is necessary to be able to control texture filtering and repeating as documented in https://deck.gl/docs/api-reference/layers/bitmap-layer#textureparameters

#### Expected Behavior
Texture constants are exported.

#### Repro Steps
```
<script src="https://unpkg.com/deck.gl@8.5.0-alpha.5/dist.min.js"></script>
```

Check content of global `luma` object, texture constants are missing.

**Comment by Pessimistress** [comment]
WebGL constants are not exported to optimize bundle size. You can access them by via the WebGLContext object.

**Comment by zakjan** [comment]
After https://github.com/visgl/luma.gl/pull/1469 is merged, constants are available in `luma.GL`.
