### ISSUE TITLE
Pixel size isn't equivalent to CSS pixel in IconLayer and LineLayer

### ISSUE THREAD

**Issue by yuriybelike** [visgl/deck.gl#5786]
#### Description

When I place an IconLayer (setting `getSize` to `20`) the icon appears smaller than 20px.
The same thing can be reproduced with LineLayer, setting `getWidth` to `20` (and `widthUnits` to `pixels`).

#### Expected Behavior

Both the icon and the line width are exactly 20px, when compared to an off-deck.gl element (such as a CSS div with `height` and `width` set to `20px`)

#### Repro Steps

- Load https://codesandbox.io/s/deckgl-forked-jnvi4?file=/src/Deck.js
- Pan the map so the icon and the line can be compared with the 20px-sized red square at the top-left corner
  - ![image](https://user-images.githubusercontent.com/60257988/118669906-6d636380-b7f6-11eb-9657-4f8eee985014.png)

#### Workarounds
- Set viewState's `altitude` to `1` as per related issue linked below
  - I couldn't make it work in my project, which combines deck.gl with react-map-gl
- For IconLayer, a partial workaround is to set `billboard` to `false`
  - The "icon looks at the camera" feature is lost
- For IconLayer, a partial workaround is to set `getSize` to `30` (x1.5 of the expected size)
  - This renders the icon not as sharp

#### Environment
 - deck.gl 8.4.16
 - Chrome 90
 - Windows 10

#### Notes
- Might be related to https://github.com/visgl/deck.gl/issues/4285
- This was first asked about on Slack: https://deckgl.slack.com/archives/C34AC5MSQ/p1621236514321300

#### Search keywords
icon size scale pixels smaller device pixel ratio blurry resolution

**Comment by Pessimistress** [comment]
I believe this was broken in 8.0 when we changed the projection matrix calculation. While there is a trivial fix, it will introduce a breaking change, so it has to go into the v8.5 release.

**Comment by Pessimistress** [comment]
Fix is published in `8.5.0-alpha.7`
