### ISSUE TITLE
I3s attribute picking

### ISSUE THREAD

**Issue by Radik24** [visgl/deck.gl#5787]
#### Description
When picking object from I3S data, info.index is always 0

#### Expected Behavior
return non zero index

#### Repro Steps
wherever I click, info.index is 0 (tested on my data + San Francisco example https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_Bldgs/SceneServer/layers/0)

```
 new Tile3DLayer({
    id: 'i3s',
    data: ...,
    loader: I3SLoader,
    pickable: true,
    pickFeatures: true,
    onClick: async info => {
      console.log(info.index);
    }
  });
```

#### Environment
 - @deck.gl version: 8.5.0-alpha.6
 - @loaders.gl version: 3.0.0-alpha.14
using Vue, not @deck.gl/react

**Comment by Pessimistress** [comment]
Tile3DLayer does not support picking individual parts. It is a feature being worked on targeting v8.5. You can follow the progress via #5754.
