### ISSUE TITLE
Effects Break Multiple Views

### ISSUE THREAD

**Issue by mcost45** [visgl/deck.gl#5797]
#### Description
When applying effects (I have only tested PostProcessEffects) to Deck using multiple views, the multiple views will break. It seems to me that when applying effects, the last view in the array of views is taken, then all the 'views' are rendered within the dimensions and positions of that final view.

I have multiple views with a minimap. In the case of having my minimap as the final views array element, everything renders within the dimensions of that view:
![image](https://user-images.githubusercontent.com/17732915/119127625-d801e280-ba34-11eb-8caa-ce0cc62f249a.png)

And in the case of reversing the order, to have the main view as the final views array element: - the positioning is fixed as the main view uses 100% of the screen area, but now the depth order is wrong:
![image](https://user-images.githubusercontent.com/17732915/119128149-8f96f480-ba35-11eb-9614-313873f572e4.png)

#### Expected Behavior
Applying effects should not break views. Perhaps also effects could be applied to individual views instead as a Deck prop.

#### Repro Steps
- Set views prop to array of two views with different sizes and/or positions (i.e. minimap / main view)
- Set effects prop to (a non-empty) array of any effects (in my case PostProcessEffects brightnessContrast and/or hueSaturation)

#### Environment
 - Framework Version: 8.4.16
 - Browser Version: Chrome  90.0.4430.212
 - OS: Windows 10.0.19042 Build 19042

#### Logs
None

**Comment by Pessimistress** [comment]
Fix is published in 8.4.20
