### ISSUE TITLE
MVTLayer and TerrainLayer loading options

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#5808]
#### Description

TileLayer's default loading behavior merges the user-provided `loadOptions` and the [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) of the tile:

https://github.com/visgl/deck.gl/blob/d5bb542d4b5d6053e61ddd38680b6ed737867a4b/modules/geo-layers/src/tile-layer/tile-layer.js#L28-L38

`MVTLayer` overrides the `getTileData` method with their own implementation. It currently does not use the abort signal - therefore it does not abort tile loading when a tile moves out of view.

`TerrainLayer` supplies `TileLayer` with a `getTileData` callback. The callback currently does not use `loadOptions` or the abort signal.

#### Expected Behavior

`MVTLayer` and `TerrainLayer`'s treatment of loading options should be consistent with that of the `TileLayer`.

Bonus if `props.fetch` is used instead of `load` so that users can override the default loading logic dynamically.

#### Repro Steps

- Open https://codepen.io/Pessimistress/pen/oNZwGLL?editors=001
- Open debug tools - network, examine request headers
- Custom header is not present

#### Environment
 - Framework Version: deck.gl 8.4.16

#### Logs

None

**Comment by alasarr** [comment]
Thanks a lot for the catch @Pessimistress.

@felixpalmer can you take a look at this?
