### ISSUE TITLE
Removing then adding to views prop giving inconsistent controller behaviour

### ISSUE THREAD

**Issue by mcost45** [visgl/deck.gl#5845]
#### Description
My use case involves being able to toggle the visibility of a minimap view, which is on top of the main view. Though I can toggle layer visibility easily, I also need to alter the views prop to remove/re-insert the minimap view on toggling, as it is interactable (panning). Removing the view does work for removing interactivity, but I have ran into this issue when toggling the minimap back on, by adding the view back to the views prop.

After I add the minimap view back, interactions on the minimap will instead 'fall-through' to the main view underneath instead (i.e. panning etc) - though before it was hidden it would work properly. I've verified visually with a clear colour that the interactive minimap view does get removed and added again, above the main view - but I am not sure why the controller no longer works properly.

Here's the most relevant code:

- When toggling the view based on the boolean 'visible' (views is an array of view objects with said minimap view stored at [2]):

```
if (visible) {
    // create a new minimap view object (same function responsible for its original, working creation)
    // with controller: true
    views[2] = getNewDynamicMinimapView();
    // I've tested resetting its viewState back to its initial state as well, but this doesn't seem to change anything
    viewStates.dynamicMinimapView = initialViewStates.dynamicMinimapView;
} else {
    // remove the minimap view from the views array
    views[2] = null;
}
deck.setProps({
    viewState: {
        dynamicMinimapView: {...viewStates.dynamicMinimapView}
    },
    views: [...views]
});
```

- Get new minimap view object function:
```
getNewDynamicMinimapView() {
    return new OrthographicView(
        {id: dynamicViewMinimapView, controller: MinimapController}
    );
}
```

MinimapController is an extension of OrthographicController, it is the exact same except it also has additional 'mousedown' event functionality. With my implementation, _after_ I toggle the minimap view off then back on again, deck will pickup the initial 'mousedown' event on the minimap view via onViewStateChange, but then the following pan events from dragging will be triggered from the main view, even though the click began on the minimap view. _Before_ I toggle the minimap off then back on again (initially), clicking and dragging on the minimap view will trigger the panning events from the minimap view as expected, not from the main view.

_Original discussion from https://github.com/visgl/deck.gl/discussions/5839#discussioncomment-829272_

#### Expected Behavior
When a view is added back into the views prop after being removed, it should behave the same as initially, and maintain correct controller interaction.

#### Repro Steps
- Create two views, with one positioned over the other (like a minimap)
- Alter the views prop to remove/re-insert one of the views, triggered by a 'toggle' function, creating the new view object on re-insertion with controller: true
- After removing then re-inserting, interacting with the minimap view will 'fall-through' to the main view under

#### Environment
Framework Version: 8.4.16
Browser Version: Chrome 90.0.4430.212
OS: Windows 10.0.19042 Build 19042

#### Logs
None

**Comment by Pessimistress** [comment]
Fix published in 8.4.17.
