### ISSUE TITLE
Updating props on Google Maps Overlay

### ISSUE THREAD

**Issue by Simone1315** [visgl/deck.gl#5848]
I am currently using a GeoJsonLayer inside a GoogleMapsOverlay to create a bubble layer over google maps. I would like to change the line width of one of the bubbles when clicking on a particular bubble. At the moment, I am updating the whole overlay each time the user clicks on a bubble, as suggested in this [issue](https://github.com/visgl/deck.gl/issues/4501) :

`this.deckOverlay.setProps({
                        layers: deckLayers
 });`

Is there any way I can partially update the layer without having to create a new layer every time (for example, update a signle prop of a layer?)

**Comment by Pessimistress** [comment]
Please only use templates to open issues.

**Comment by saadmb** [comment]
What is the solution to this?
