### ISSUE TITLE
onViewStateChange viewState values + performance

### ISSUE THREAD

**Issue by mcost45** [visgl/deck.gl#5858]
#### Description
I am observing this with an orthographic view, using the non-react version of deck. Currently, I have smooth-zoom disabled (so no transition time). I handle onViewStateChange to set new viewState props. From a single (instant) zoom, onViewStateChange will consistently get called three times with:

1. The new state post-zoom (with new target/zoom)
2. The old state pre-zoom (with old target/zoom)
3. Then finally the new state post-zoom (with new target/zoom) again

This is my orthographic view controller setup:
`      controller: {
        scrollZoom: {speed: 1, smooth: false},
        inertia: true,
        doubleClickZoom: false
      }`

The first onViewStateChange always has a transitionDuration of 1, and if I manually set it to 0 this prevents the two following calls, however that would prevent being able to use inertia or smooth-zoom.

The three onViewStateChange calls can be seen in this profile below, twice from the mouse wheel event, and once more within the following request animation frame:
![image](https://user-images.githubusercontent.com/17732915/121154882-9c925100-c847-11eb-9fce-dbdeed6672e3.png)

What this essentially amounts to, is that for a single frame, the viewports are getting recreated/recalculated three times, and only the last is actually providing for the drawn results, even for a zoom with smooth disabled. I've created a constraint on the navigatable area, so these clamps on the view target also get recalculated for each onViewStateChange call.

I am just wondering if I am doing something wrong or if this is necessary, or if onViewStateChange could be called once before each individual frame is rendered, instead of three times?

#### Expected Behavior
Run onViewStateChange once before drawing each frame, with the new state values.

#### Repro Steps

- Set up orthographic view with controller: true
- Use onViewStateChange to apply the new viewState to deck's viewStates prop

#### Environment
Environment
Framework Version: 8.4.16
Browser Version: Chrome 90.0.4430.212
OS: Windows 10.0.19042 Build 19042

#### Logs
None

**Comment by Pessimistress** [comment]
The 1ms transition on wheel is basically our work around to make a discrete event (`wheel`) behave like a continuous one. This is needed for resetting the `isZooming` state flag.

Recalculating viewport is not expensive in itself. If you perform any expensive operation on `onViewStateChange`, then it's highly recommended that you add a debounce to it.

> The first onViewStateChange always has a transitionDuration of 1, and if I manually set it to 0 this prevents the two following calls, however that would prevent being able to use inertia or smooth-zoom.

If you want to use inertia or smooth zoom then you need to allow for transition, which naturally will call `onViewStateChange` multiple times. If you don't, then manually setting `transitionDuration` to `0` is fine.
