### ISSUE TITLE
Globe View - inconsistent tile traversal / selection

### ISSUE THREAD

**Issue by igorDykhta** [visgl/deck.gl#5860]
#### Description
tile-2d-traversal::getBoundingVolume for the top tile {x: 0, y: 0, z: 0} generates a bounding sphere with center on the equator:
{center: [0, -256, 0], radius: 377} (the blue sphere on the image below is the bounding sphere, the green sphere is the globe).
![image](https://user-images.githubusercontent.com/8210766/121248689-6509c000-c8ac-11eb-8b39-47996fa23877.png)

This causes inconsistent behavior of labels, satellite tiles, etc on the opposite side of the globe (East Asia, Pacific) for certain zoom levels. The top tile level can be either selected as LOD, or fail to get into a frustum of the view and discarded together with all children tiles.

#### Expected Behavior
- Consistent selection of active tiles in globe mode 
- Bounding sphere of the top tile is placed at (0, 0, 0) ? (Causes different issues...)

#### Repro Steps
- Globe with an MVTLayer+TextLayer.
- Zoom out, target camera on Europe > labels are visible.
- Rotate the camera to Australia > labels aren't visible, as the topmost tile is selected instead of children tiles.

#### Environment
 - Framework Version: deck.gl 8.4.16

**Comment by Pessimistress** [comment]
A fix is published in 8.5.4.
