### ISSUE TITLE
Icons disappearing from TileLayer when panning (Google Maps)

### ISSUE THREAD

**Issue by clementprdhomme** [visgl/deck.gl#5873]
#### Description
I have a map that is using Google Maps under the hood, and I use deck.gl's `GoogleMapsOverlay` to render a `TileLayer` on top of it. The layer renders a few thousands points on the map using an `IconLayer` sub-layer.

When panning the map (horizontally only), some of the points disappear from the map and then re-appear if panning further.

https://user-images.githubusercontent.com/6073968/122046601-658be480-cddf-11eb-9f79-309acdbbc7dd.mp4

#### Expected Behavior
The points should not disappear in the first place.

#### Repro Steps
I've created an environment with just one point to exhibit the issue:
https://codesandbox.io/embed/sweet-cerf-4q4qn?fontsize=14&hidenavigation=1&theme=dark _(please put your own Google API key there)_

In order to reproduce the issue:
1. Update the size of the window so that the tile containing the marker and the next one horizontally are fully displayed
2. Pan horizontally to the right until the start of the tile containing the marker is hidden

At this stage, you will see that the point disappears from the map.

If you continue panning to the right, and until the third tile to the right of the one containing the marker starts to appear, you will see that the marker re-appears.

I would like to note that in my dataset, not all the points disappear when panning. Only some of them do, but since I'm clustering points, this has a significant impact on the “crowdedness” of the map.

#### Environment
 - Framework Version:  deck.gl 8.4.17
 - Browser Version: Firefox 90.0b7, Chrome 91.0, Safari 14.1.1
 - OS: MacOS 11.4

#### Logs
No relevant log.

**Comment by Pessimistress** [comment]
The problem is in your `getTileData`:

```js
    getTileData: ({ x, y }) => {
        if (x === 0 && y === 1) {
          return [
            {
              lng: -6.771661421038465,
              lat: 54.02171074328135
            }
          ];
        }
        return [];
      },
```

The coordinate `[-6.771661421038465, 54.02171074328135]` is not inside tile `{x: 0, y: 1, z: 2}`, which is the tile being displayed at this zoom level. If you change `if (x === 0 && y === 1)` to `if (x === 1 && y === 1 && z === 2)` you can see that the layer behaves as expected.

**Comment by clementprdhomme** [comment]
Hi @Pessimistress,

Thank you so much for your quick answer. You're right, the point should be in a different tile.

I believe the issue stems in the fact the map's zoom is different from the `z` parameter I get in `getTileData`.

As you can see in my example, the map has a min zoom of 3. You can further check this by printing it in the console:
```js
console.log(map.getZoom()); // Print the initial zoom level
map.addListener('zoom_changed', () => console.log(map.getZoom()));
```

Nevertheless, if you print `z` in `getTileData`, you will see it has a value of 2. 

This is this discrepancy that puts points in wrong tiles. Any idea why this is happening?
