### ISSUE TITLE
WebMercatorViewport fitBounds() not working.

### ISSUE THREAD

**Issue by BenjaminSAILcloud** [visgl/deck.gl#5890]
#### Description
Hi,

I have a problem when using the `WebMercatorViewport`'s `fitBounds()` method.
I want to initialize the `DeckGL` object with the `initialViewState` calculated from two coordinates.
But the `fitBounds` method returns a `WebMercatorViewport` which has a very low zoom, and does not fit the bounding box.

#### Expected Behavior
The map to be initialized with the correct viewstate showed by the two markers.

#### Repro Steps

<details>
<summary>Code</summary>

```js
const southWest = [-64.89027335336503, 32.22041257595005]
const northEst = [-28.43581017513801, 38.70974838512729]

const viewport = new WebMercatorViewport().fitBounds([southWest, northEst])

return (
    <DeckGL initialViewState={viewport} controller={true}>
        <StaticMap reuseMaps mapStyle={MAP_STYLE} preventStyleDiffing={true} />
    </DeckGl>
)
```

</details>

#### Environment
 - Framework Version: [deck.gl 8.4.15]
 - Browser Version: [Chromium  93.0.4523.0, Firefox 89.0]
 - OS: [Mac OS X 10.15.7]

#### Logs

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/33052668/122427198-34531600-cf91-11eb-9719-fe0aa473e04a.png)

</details>

**Comment by Pessimistress** [comment]
You are not passing width and height to the WebMercatorViewport constructor. The default value is 1x1.
