### ISSUE TITLE
Underground Data

### ISSUE THREAD

**Issue by mogmog** [visgl/deck.gl#5892]
#### Description
I have a data set that contains bathymetry data - depths of water from a depth finder. I was hoping to use deck.gl to visualise this data, but it doesn't feel right at the moment.

The tile loading seems glitchy.

The MVT Layer doesn't feel aligned.  

#### Expected Behavior
 Data renders correctly. Tiles load.

https://user-images.githubusercontent.com/934073/122603469-4b1a6b00-d06c-11eb-8c82-191bc0b492bf.mov

#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]
 - Browser Version: [e.g. Chrome 78.0]
 - OS: [e.g. Mac OS X 10.15 / iOS 14.2]

**Comment by Pessimistress** [comment]
I cannot tell if anything is wrong by looking at your video. Can you make a CodeSandbox?

General advice regarding showing underground data:

- set a custom [farZMultiplier](https://deck.gl/docs/api-reference/core/map-view#constructor-1) on your MapView. The default far plane clips at z=0.
- set [zRange](https://deck.gl/docs/api-reference/geo-layers/tile-layer#zrange) of your MVTLayer

**Comment by mogmog** [comment]
I had set a max width param on my MVT Layer, so that was (correctly) causing things to not line up right. 

I'll raise a new ticket for another issue.
