### ISSUE TITLE
MVTLayer is not refreshed with UpdateTriggers

### ISSUE THREAD

**Issue by Cadfael31** [visgl/deck.gl#5902]
Hi,

#### Description
I am triying to update the getFillColor of a MVTLayer with the updateTriggers. But nothing happens until I load new tiles moving the map. And the tiles hat are already loaded are not updated. If I zoom, all tiles have the right colormap. If I unzoom, the old tiles keep the old (and wrong) colormap.

#### Expected Behavior
I guess that when I change the property defined in the updateTriggers, the MVT tiles should be redrawn with the right colors, but I think there is a problem, maybe with the cache.

#### Repro Steps
Here is my code. I think you can replace my data URL by anything else.

`
import { Deck } from '@deck.gl/core';
import {MVTLayer} from '@deck.gl/geo-layers';

class Demo {

    INITIAL_VIEW_STATE = {
        latitude: 44,
        longitude: 0,
        zoom: 5
    };

    deck: Deck;
    fillcolor: number[]=  [192, 192, 192];

    // Run demo.setColorMap to change the fill color
    // e.g. demo.setColorMap([255,0,0]);
    setColorMap(colormap){
        this.fillcolor=colormap;
    }

    deckgl() {
        this.deck =  new Deck({
            initialViewState: this.INITIAL_VIEW_STATE,
            controller: true,
            layers: [
                new MVTLayer({
                    data: 'http://in-web-02-eu:3000/api/maps/AQ_mvt/amu/{z}/{x}/{y}.pbf?blockcode=EuropeAMU',                
                    minZoom: 0,
                    maxZoom: 23,
                    getLineColor: [192, 192, 192],
                    getFillColor: ()=>{return this.fillcolor;},
                    maxCacheSize:0,
                    updateTriggers:{
                            getFillColor:this.fillcolor
                          },
                    lineWidthMinPixels: 1
                  })
            ]
        });
    }
}

(() => {
    const demo = new Demo();
    window['demo'] = demo;
    window.onload = () => {
        demo.deckgl();
    };
})();
`
At the beginning I have this:
![image](https://user-images.githubusercontent.com/34963305/122931371-1d376e00-d36d-11eb-9012-c19dc07267db.png)

after running setColorMap, I have the same thing.

after moving the map
![image](https://user-images.githubusercontent.com/34963305/122932887-689e4c00-d36e-11eb-8957-93bd600a50dd.png)

after zooming
![image](https://user-images.githubusercontent.com/34963305/122932981-7eac0c80-d36e-11eb-9788-f503164ae8d2.png)

after going back to the previous zoom
![image](https://user-images.githubusercontent.com/34963305/122933068-94213680-d36e-11eb-96ff-31dbd092abc6.png)

#### Environment
 - deck.gl 8.7.17 / TypeScript 4.2.2
 - Browser Version: Chrome Version 91.0.4472
 - OS: Window 10

Is there something that I do wrong, or is there a workaround please?
Than you for your help.

**Comment by Pessimistress** [comment]
You are not updating `updateTriggers`. Search for it in issues/Discussions you will find plenty of examples.

Bug report is for identified bugs in the framework. To help debug your own app, go to Discussions.
