### ISSUE TITLE
ArcLayer的落地点在high zoom时发生偏移

### ISSUE THREAD

**Issue by cqRou** [visgl/deck.gl#5922]
#### Description
图中icon的经纬度和ArcLayer落地点的经纬度相同，但是在high zoom时两者出现偏移，对不上，如下图所示
![image](https://user-images.githubusercontent.com/59086968/123893323-c34b2f80-d98e-11eb-9671-6e511da3f0ff.png)

这是在low zoom时的情况
![image](https://user-images.githubusercontent.com/59086968/123893796-a6fbc280-d98f-11eb-99fa-398dfe0d929c.png)

**Comment by Pessimistress** [comment]
There is a bug report template for a reason. Please edit this issue and fill in all the information required by the template, and I will reopen it. If you are unable to provide sufficient details to form a bug report, use Discussions to get help instead.

**Comment by Pessimistress** [comment]
We cannot debug from screenshots. Please provide a code and data sample that reproduces your issue.
