### ISSUE TITLE
MVTLayer getFillColor feature coordinates

### ISSUE THREAD

**Issue by bolollo** [visgl/deck.gl#5953]
#### Description
The feature coordinates are relative to the tile and not the real world coordinates (WGS84)

#### Expected Behavior
Feature coordinates realtive to the real world coordinates (WGS84) 

Example on the onHover function the coordinates are the real world coordinates (WGS84)

**Comment by AdriSolid** [comment]
I think you should move this to `discussions` trying to explain a bit more your doubts related with `MVTLayer`

**Comment by ibgreen** [comment]
Please move to discussions. Also check out `loadOptions.mvt.coordinates = 'wgs84'` 

See https://loaders.gl/modules/mvt/docs/api-reference/mvt-loader#options
