### ISSUE TITLE
Binary MVT Layer doesn't return geometry when picking

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#5958]
#### Description

When suppling `getTooltip: ({object})` on `MVTLayer` the returned `object` only contains the `properties` member.

#### Expected Behavior

The full geojson Feature should be returned, including the `geometry`

#### Repro Steps

Add the following `getTooltip` function to a Deck object with a `MVTLayer` or `CartoLayer`:

```javascript
getTooltip: ({object}) => {
  object && console.log(object); 
}
```

For example, modify the `get-started/pure-js/carto/app.js ` example

**Comment by ibgreen** [comment]
@kylebarron Maybe we should add a `getSingleFeature(BinaryGeometry, objectId)` helper function to the loaders.gl GIS helpers.

**Comment by kylebarron** [comment]
That sounds reasonable.

**Comment by felixpalmer** [comment]
Yes this is more or less the solution I've been working towards. loaders.gl has a lot of good utility functions in `modules/gis/src/lib/binary-to-geojson.js`, but only `binaryToGeoJson` is exported

**Comment by felixpalmer** [comment]
_Originally posted by @borja-munoz in https://github.com/visgl/deck.gl/issues/5948#issuecomment-875477586_
