### ISSUE TITLE
deck.gl esri new layer not displayed when added to the mapview

### ISSUE THREAD

**Issue by sgavathe** [visgl/deck.gl#5975]
Hello,

It appears that the older version of deck.gl and esri works when new layer is added to the map view with the layer add code.   

To demonstrate, made 2 code pens. One with the old version and one with the latest version. 

  Older one works. (for the new layer it says lifecycle: "Matched. State transferred from previous layer"	)
  https://codepen.io/sgavathe/pen/mdmWXdZ

  Newer one does not, unless I am missing a Layer update workflow. ( for the new layer it says lifecycle: "Initialized")
  https://codepen.io/sgavathe/pen/jOmBZbV

 You can see see two blue arc lines added after pressing a button.
![image](https://user-images.githubusercontent.com/6047188/125804944-a734f81c-08d5-413b-a253-f7e7efe74f13.png)

Thanks,

**Comment by Pessimistress** [comment]
Please do not delete the template when you open an issue.

See working example in https://github.com/visgl/deck.gl/blob/master/examples/get-started/scripting/arcgis/index.html

**Comment by sgavathe** [comment]
why was this closed? There is still an issue I demonstrated under code pens. Not sure, if you understood the issue that I tried to explain.

**Comment by Pessimistress** [comment]
There is a reason why there is a bug template. Are you reporting an issue on a particular version of deck.gl, or a combination of deck.gl and an ArcGIS versions?

**Comment by sgavathe** [comment]
I was reporting the issue on deck.gl and ArcGIS version 
deck.gl@8.4.20, arcgis@8.4.20 

I see , so I will need to find the bug template to report it again then. Thanks.
