### ISSUE TITLE
Newly added layer to the map view is not displayed deck.gl/ArcGIS

### ISSUE THREAD

**Issue by sgavathe** [visgl/deck.gl#5977]
#### Description
It appears that newly added layer to the map view is not displayed with the newer deck.gl , ArcGIS versions.

#### Expected Behavior
The layer should be displayed when added after the map view is initialized.

#### Repro Steps
To demonstrate, made 2 code pens. One with the old version and one with the latest version.

**Older one works** (for the new layer it says lifecycle: "Matched. State transferred from previous layer" )
https://codepen.io/sgavathe/pen/mdmWXdZ

**Newer one does not** ( for the new layer it says lifecycle: "Initialized")
https://codepen.io/sgavathe/pen/jOmBZbV

#### Environment
 - Framework Version: [e.g. deck.gl@8.4.20 & deck.gl/arcgis@8.4.20 & arcgis@4.20 ]
 - Browser Version: [e.g. Chrome Version 91.0.4472.124  ]

#### Logs
did not see any logs specific to this after enabling them.
But I see that the new layer it says lifecycle: "Initialized".

**Comment by Pessimistress** [comment]
The `DeckLayer` class is not really designed to support rendering multiple instances. To render deck.gl layers correctly and efficiently you should place them all under a single `DeckLayer` instance:

```js
deck.loadArcGISModules([
    "esri/Map",
    "esri/views/MapView"
]).then(({DeckLayer, modules}) => {
    const [Map, MapView] = modules;
    
    const deckLayer = new DeckLayer({
        'deck.layers': [
            // initial layers
        ]
    });

    const mapView = new MapView({
        container: "mapViewDiv",
        map: new Map({
            basemap: "dark-gray-vector",
            layers: [deckLayer]
        }),
        center: [0.119167, 52.205276],
        zoom: 1
    });
    
    onButtonClick = function (elmnt,clr) {
        deckLayer.deck.layers = deckLayer.deck.layers.concat([
            // layers to add
        ]);
    }
});
```

**Comment by sgavathe** [comment]
Thank you @Pessimistress . Appreciate the response. It indeed work without me setting up any new instance for the deckLayer. Excellent.
