### ISSUE TITLE
Allow to set the ID of the wrapper div for multiple DeckGL components on a page

### ISSUE THREAD

**Issue by andreasg123** [visgl/deck.gl#5999]
#### Target Use case
While it is possible to [set the ID of the canvas](https://deck.gl/docs/api-reference/core/deck#id), the ID of the wrapper is always `deckgl-wrapper`: https://github.com/visgl/deck.gl/blob/8.4-release/modules/react/src/deckgl.js#L209

I'm not completely sure if this causes a problem but it violates the requirement for HTML that IDs in a document are unique.

#### Proposed feature
Please offer a prop for changing the wrapper ID.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
As of 8.5.0 if you specify the `id` prop on `<DeckGL>` then the wrapper id is set to `${id}-wrapper`
