### ISSUE TITLE
Passing webgl context to react-map-gl StaticMap makes the map blink

### ISSUE THREAD

**Issue by kewersonhugo** [visgl/deck.gl#6015]
#### Description
I followed the example given by [@deck.gl/mapbox](https://deck.gl/docs/api-reference/mapbox/overview) and any interaction with the map makes it blink. The same problem happens with Firefox and Chrome.

#### Expected Behavior
The map should not blink.

#### Repro Steps
This minimal codesandbox reproduces the problem. Hope it helps.
https://codesandbox.io/s/funny-currying-zewd1?file=/src/App.js

#### Environment
 - Framework Version: 
     - deck.gl@8.4.20
     - react-map-gl@6.1.16
     - mapbox-gl@2.3.1
     - react@17.0.2
     - react-dom@17.0.2
 - Browser Version: 
     - Firefox 90.0.2
     - Chrome 91.0.4472.164
 - OS: Windows 10 build 21390.2025

**Comment by Pessimistress** [comment]
You must add at least one deck.gl layer for this pattern to work. See https://github.com/visgl/deck.gl/discussions/5809#discussioncomment-784019

**Comment by kewersonhugo** [comment]
> You must add at least one deck.gl layer for this pattern to work. See [#5809 (comment)](https://github.com/visgl/deck.gl/discussions/5809#discussioncomment-784019)

Made this other codesandbox adding the layer, with the same code from the docs, and I still getting the same problem. I also noticed addLayer is throwing an error.

https://codesandbox.io/s/gracious-moser-715zr?file=/src/App.js

**Comment by kewersonhugo** [comment]
Sorry, just figured out it was caused by the "beforeId" on addLayer. To be honest this behavior was completely unexpected to me.

**Comment by Pessimistress** [comment]
> To be honest this behavior was completely unexpected to me.

I agree. deck.gl is independent from any base map provider, so we cannot code any mapbox-specific handling into the library. The way it works now, `Deck` only becomes aware that it is sharing the gl context with another library when a `MapboxLayer`'s `onAdd` is invoked. We can explore other avenues but it might always be a little hacky.

**Comment by cgarrovillo** [comment]
To be clear, what `beforeId` should be used when the closest parent is a `<DeckGL>` component?

**Comment by cgarrovillo** [comment]
nvm. https://docs.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/
