### ISSUE TITLE
[Clarification] - Data format for HexagonLayer

### ISSUE THREAD

**Issue by jaballogian** [visgl/deck.gl#6020]
#### Link
https://deck.gl/docs/api-reference/aggregation-layers/hexagon-layer (documentation)
https://deck.gl/examples/hexagon-layer/ (sample demo)
https://github.com/visgl/deck.gl/blob/8.5-release/examples/website/3d-heatmap/app.js (sample code)

#### Description

I need to clarify and ask something about the format and sample data for ```HexagonLayer``` component from ```@deck.gl/aggregation-layers``` from the documentation above.

Data from the documentation:
```
/**
   * Data format:
   * [
   *   {COORDINATES: [-122.42177834, 37.78346622]},
   *   ...
   * ]
   */
```

Data source from the sample code:
```
const DATA_URL =
  'https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv'
```

As seen in the documentation above (also the sample code), the ```data``` for ```HexagonLayer``` component is an array of locations (latitude and longitude) and **the height of the hexagon item is determined based on the count (occurrence) of each location point**. 

#### Question

If the data I have is something like this:
```
"rows": [
    {
        "id": 5226,
        "lat": -6.107405,
        "lng": 106.777575,
        "speed": 9,
    },
    ...
]
```

can I use the ```speed``` value (from every item inside ```rows```) to determine the height of the hexagonal item?

**Comment by Pessimistress** [comment]
There already are examples in https://deck.gl/docs/api-reference/aggregation-layers/hexagon-layer#elevationaggregation

Open a Discussion thread if you have questions.
