### ISSUE TITLE
TileLayer no longer updates Tileset min/maxZoom opts when said props change

### ISSUE THREAD

**Issue by jcready** [visgl/deck.gl#6023]
#### Description
I'm trying to update from 8.4.13 to 8.5.0 and I'm noticing a difference in how the TileLayer (I'm using the MVTLayer specifically) behaves. It looks like when I change the min/max zoom props the Tileset instance is no longer seeing that change.

I believe the issue comes down to how the `updateState` method updates the Tileset options. In v8.5.0 it does this:

https://github.com/visgl/deck.gl/blob/40141c7b9209ca2497648fb0f3c470b61a85fc79/modules/geo-layers/src/tile-layer/tile-layer.js#L73-L74

Compared to 8.4.13:

https://github.com/visgl/deck.gl/blob/640bce52a72151033fbffef3f64a45dbc716bad9/modules/geo-layers/src/tile-layer/tile-layer.js#L107-L108

It seem to me like the `updateState` method need to update its `state.maxZoom` and `state.minZoom` when those props change or revert to the previous behavior where the props are passed directly to `tileset.setOptions`. For what it's worth it looks like that change happened in v8.4.15.

#### Expected Behavior
Changing the `minZoom` or `maxZoom` props will appropriately update the Tileset opts.

#### Environment
 - deck.gl 8.5.0
 - Browser Version: Firefox 90.0.2
 - OS: Mac OS 11.4

**Comment by Pessimistress** [comment]
@alasarr  MVTLayer should set `state.minZoom` and `state.maxZoom` to `null` if they are not defined by tileJSON. `_updateTileData()` is only called on data change, so `props.minZoom` change is being ignored.

**Comment by alasarr** [comment]
Thanks a lot for reporting, it doesn't look complicated, I'll create a PR later today or tomorrow with the fix

**Comment by alasarr** [comment]
I've created a fix, @Pessimistress once approved I'll create a patch release

**Comment by Pessimistress** [comment]
Fixed in 8.5.1
