### ISSUE TITLE
Recreating Orthographic View Not Clearing Previous Keyboard Event Handlers

### ISSUE THREAD

**Issue by mcost45** [visgl/deck.gl#6026]
#### Description
If I recreate an Orthographic view many times, replacing it in the views array each time (i.e. views = [getNewOrthographicView()]), keyboard activated controller events will be very laggy as onKeyDown gets called many times:
![image](https://user-images.githubusercontent.com/17732915/127311584-d5ba65e4-57e2-4d2c-adb0-6e6d188c401d.png)
(from the + key).

When the view has been recreated only once, the onKeyDown handler will also run twice:
![image](https://user-images.githubusercontent.com/17732915/127311961-ed07f2cb-1879-4c3a-bc0d-8181fa0918c7.png)

It looks like previous view controller keyDown events are not being cleared when a new view gets created, leading to duplicates running. In my case I am recreating the view with a new minZoom prop on window resizes.

#### Expected Behavior
When a view gets recreated, clear previous controller onKeyDown handlers so only one will run.

#### Repro Steps
1. Recreate an orthographic view several times with the same id/props/position in views array, only changing the minZoom prop.
2. Use a keyboard triggered action (like the + key).
3. onKeyDown will run the same number of times as the view has been recreated.

#### Environment
 - Framework Version: deck.gl 8.5.0
 - Browser Version: 92.0.4515.107
 - OS: Windows 19043.1110

**Comment by Pessimistress** [comment]
I cannot reproduce this. Can you provide a Codepen/CodeSandbox?

**Comment by mcost45** [comment]
Hmmm after quite some time I haven't been able to reproduce it in a Codepen either. For now I have another method to avoid the problem occurring, but maybe I will look into it further later.
