### ISSUE TITLE
React - Right click on IconLayer marker returns null for pickObject

### ISSUE THREAD

**Issue by IncredibleMrTim** [visgl/deck.gl#6027]
I have been trying to figure out how to get right click to work on IconLayer map marker.  I have tried the suggested way

eg.
```
onClick: (info, event) => console.log(event.rightcllick)
```

but this does not seem to be working for me.  Whenever I right-click no event is fired or my action listener fires from the map canvas instead (I have already tested removing the map listener I get the same results, no event)

After some further searching, I have found this in the docs.

https://deck.gl/docs/developer-guide/interactivity#calling-the-picking-engine-directly

however, when I fire the onclick i am unable to find any markers on the map and the `pickInfo` comes back as null.

I have had to slightly adapt the way it has been done as this is a class-based component so I am unable to use hooks

```javascript
    ...

    deckRef = React.createRef()

	deckClick = e => {
		const pickInfo = this.deckRef.current.pickObject({
			x: e.clientX,
			y: e.clientY,
			radius: 1,
			layerIds: ['icon-layer-TEST'],
		})

		console.log(pickInfo)
		console.log(e, e.clientX, e.clientY)
		console.log(this.deckRef.current)
	}


    render() {
		const { center, google, initialMapCenter, language, zoom } = this.props

		return (
			<Container
				className={MAP_CONTAINER_CLASS_NAME}
				id="map"
				onContextMenu={this.deckClick}
			>
				<DeckGL ref={this.deckRef}>
					<GoogleMap

    ...
```

**Comment by Pessimistress** [comment]
Please only create issues using templates. Go to Diacussions for help with debugging your app.
