### ISSUE TITLE
Tile3DLayer not working with cesium 3D tiles

### ISSUE THREAD

**Issue by Radik24** [visgl/deck.gl#6028]
#### Description
after recent upgrade to 8.5.0 cesium 3D tiles seems to be not working, cesium point cloud works.
I'm absolutely sure the tested tilesets were working on older version.

`onTilesetLoad` is working perfectly, it zooms me to the tileset (i know it's location, I added openstreet layer to see where I am), but nothing is rendered.

opacity is correct, everything seems to be correct, I did not change my old code (just updated loadOptions.fetch - it's changed in this version)

There are no error logs at all. I can see successful requests in network.

It loads new .b3dm files when I zoom in.

![image](https://user-images.githubusercontent.com/23722745/127325851-2f7adea7-a165-432d-b506-b7f1a20e1385.png)

```
return new Tile3DLayer({
  id: layer.id,
  visible: true,
  opacity: 1,
  data: ...,
  loader: Tiles3DLoader,
  sizeUnits: 'pixels',
  pickable: false,
  loadOptions: {
    '3d-tiles': {
      isTileset: true
    },
    tileset: {
      throttleRequests: false
    },
    fetch: {
      headers: this.requestHeaders()
    }
  },
  onTilesetLoad: this.onTilesetLoad3DTiles.bind(this, layer)
});
```

Point cloud layer is same as ^^ + `pointSize` and works fine, I3S data too

#### Expected Behavior
render cesium 3D tiles with Tile3DLayer

#### Repro Steps
upgrade @deck.gl from 8.4.x (if I remember correctly) to 8.5.0
upgrade @loaders.gl from 3.0.0-alpha.16 to 3.0.6

#### Logs
no error logs, nothing. Everything seems to be fetched from server correctly

Am I missing something or it's a bug?

Thanks

**Comment by Radik24** [comment]
I updated my tileset to ION and it's the same, data is loaded but not rendered

**Comment by Pessimistress** [comment]
Can you share your dataset with us? If not, can you try 8.5.0-alpha.x and 8.5.0-beta.x and see which was the last working version?

**Comment by ibgreen** [comment]
@dryabinin-actionengine @belom88

**Comment by belom88** [comment]
loaders.gl:3.0.7 has been published today. Can you check it now? There was a bug with cesium_rtc extension I've fixed recently.
https://github.com/visgl/loaders.gl/pull/1703

**Comment by Radik24** [comment]
Yeah I'll try. I tried New York tileset from https://deck.gl/playground/ on 8.5.0 and it worked. So don't know here the problem is but I'm absolutely sure my tilesets worked on previous versions. 

Will let you know. Thanks

**Comment by Radik24** [comment]
@belom88 loaders.gl 3.0.7 solved my problem :) Thank you all very much, you're great!
