### ISSUE TITLE
ArcGIS deck.gl - allow deck.gl modules to be loaded similar ES6 @arcgis/core

### ISSUE THREAD

**Issue by sgavathe** [visgl/deck.gl#6033]
#### Target Use case

@Pessimistress 
Currently the only way to load deck.gl modules along with esri is via esri-loader. 

Most of the newer development is moving towards ES6 modules imports (@arcgis/core) instead of esri-loader

More information is here
https://developers.arcgis.com/javascript/latest/es-modules/

The result of mixing ES6 imports and deck.gl esri-loader makes the console flooded with these messages.
`[esri.core.Accessor] Accessor#set Assigning an instance of 'esri.geometry.SpatialReference' which is not a subclass of 'esri.geometry.SpatialReference' `

#### Proposed feature

Allow deck.gl to be loaded as ES6 imports, since newer development is moving towards ES6.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
@damix911 Looks like the script tag use case still requires `loadModules`?
I think we should switch to recommending the ES module, while keeping the support for the old usage pattern.

**Comment by damix911** [comment]
> Looks like the script tag use case still requires loadModules?

Yes, `esri-loader` is always used. We should change that.

So, if I understand correctly we should have @deck.gl/arcgis try ES6 first and fall back to `loadModules` if ES6 does not work out?

**Comment by Pessimistress** [comment]
Here's how I imagine things could work:

- Make `@arcgis/core` a peer dependency
- export `DeckLayer` and `DeckRenderer` etc. directly like

  ```js
  import Accessor from '@arcgis/core/accessor';
  import Layer from '@arcgis/core/layers/layer';
  ...

  const DeckProps = createDeckProps(Accessor);
  export const DeckLayer = createDeckLayer(DeckProps, Layer, ...);
  ```

- For the script tag use case, https://github.com/visgl/deck.gl/blob/master/modules/arcgis/bundle.js should only import `loadArcGISModules` to avoid bundling `@arcgis/core`
- Update docs and examples/get-started/pure-js/arcgis to use ES modules

**Comment by sgavathe** [comment]
@Pessimistress @damix911 was wondering, if we could have a fix for this in the upcoming releases?

**Comment by Pessimistress** [comment]
I do not have time to work on this at the moment. Happy to help review if you open a PR.

**Comment by Pessimistress** [comment]
This will be availalable in v8.7.0. You can try it with v8.7.0-alpha.1.

**Comment by sgavathe** [comment]
Thank you @Pessimistress . Let me try it on v8.7.0-alpha.1. Thanks again.
