### ISSUE TITLE
IconLayer icons size 

### ISSUE THREAD

**Issue by lukaszbarkowski** [visgl/deck.gl#6039]
#### Description
Latest update to 8.5 has caused IconLayer icons to significantly grow, for example demo: 
@latest:
![image](https://user-images.githubusercontent.com/40040662/127488143-9fa949c6-bf2b-47db-815c-a82b90ffa487.png)
8.4.0:
![image](https://user-images.githubusercontent.com/40040662/127488238-454b226c-9188-4a59-8c70-24c9aa5d98ac.png)

Should there be any additional props added to layer to keep old size, or is it a regression that will be fixed ?

**Comment by Pessimistress** [comment]
[Upgrade guide](https://deck.gl/docs/upgrade-guide#upgrading-from-deckgl-v84-to-v85)
