### ISSUE TITLE
[mapbox] Can't interact with the map on 8.5.1

### ISSUE THREAD

**Issue by Bowen7** [visgl/deck.gl#6052]
#### Description

I can't interact with the map(drag, zoom in...) when I use deck.gl 8.5.1 with React

#### Repro Steps
Copy code from [docs #using-with-react](https://deck.gl/docs/api-reference/mapbox/overview#using-with-react)

[CodeSandbox](https://codesandbox.io/s/hopeful-stonebraker-dytrh?file=/src/App.js)

#### Environment
 - Framework Version: deck.gl 8.5.1
 - Browser Version: Chrome 92.0.4515.107
 - OS: Mac OS X 10.15.7

**Comment by Pessimistress** [comment]
Thanks for reporting! This issue is fixed in v8.5.2.
