### ISSUE TITLE
jupyter-widget tests are failing

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6063]
#### Description

CI tests are failing for jupyter-widget, see test runs:

https://github.com/visgl/deck.gl/pull/6059/checks?check_run_id=3243442718
https://github.com/visgl/deck.gl/pull/6062/checks?check_run_id=3243149173

The changes in these PR appear to be unrelated to the failing tests

**Comment by ibgreen** [comment]
@ajduberstein @kylebarron

**Comment by kylebarron** [comment]
It looks like this error might be intended to be skipped but the messaged changed?
https://github.com/visgl/deck.gl/blob/1049956d723fe7a92c39ea203bc2b5c5fe00cc36/test/modules/jupyter-widget/index.spec.js#L12-L16

The error message might've changed from

```
Cannot read property 'widget_manager' of undefined
```

to

```
TypeError: Cannot read properties of undefined (reading 'widget_manager')
```

**Comment by Pessimistress** [comment]
@kylebarron The failed tests were running in headless browser.

**Comment by kylebarron** [comment]
Ah, I didn't notice that. Well it's clear `createTestModel` is failing for some reason. I don't know the JS jupyter-widget codebase virtually at all. @ajduberstein do you have any ideas?

**Comment by ajduberstein** [comment]
I'm in the process of debugging this now. I'll keep you all posted.

**Comment by ajduberstein** [comment]
Thanks for flagging. Replicated this and confirmed it's broken on master. The fix is in #6064 which appears to pass CI. If I can get a review and merge, we can close this issue out.

**Comment by ajduberstein** [comment]
@felixpalmer can you verify this is still an issue?

**Comment by felixpalmer** [comment]
Thanks, that fixed it. I re-ran the CI on those two PRs and they pass now
