### ISSUE TITLE
Is there a way to use Material-UI icons or generic Material-UI components (e.g. Avatar) in IconLayer?

### ISSUE THREAD

**Issue by jyjyj** [visgl/deck.gl#6069]
#### Link
Based on the current [docs](https://deck.gl/docs/api-reference/layers/icon-layer), a url of some sort is required, or an input to some png or similar. Can I use a Material UI icon or general React component? My goal is to display icons with dynamically-generated counts.

#### Description

As mentioned in the title, can I use the [Material UI icon imports](https://material-ui.com/components/material-icons/) in the IconLayer? I would like to leverage the performance of `deck.gl` by using `IconLayer` rather than using individual `<Marker>`s, which is what I did with `react-map-gl` previously. Thanks!

**Comment by Pessimistress** [comment]
Issues are for identified errors in the documentation. Please use Discussions to get help.
