### ISSUE TITLE
depthTest fail on 3d tileset

### ISSUE THREAD

**Issue by yan-map** [visgl/deck.gl#6077]
Hello
my Tile3DLayer struggles to pass depthTest, causing artifacts:
![Screenshot_8](https://user-images.githubusercontent.com/53347730/128775480-65ded88e-c9c7-463c-b738-7d5bcaba5ab7.png)
![Screenshot_9](https://user-images.githubusercontent.com/53347730/128775484-17a3e55f-61a4-4288-a6f9-dde24970d83c.png)

Here's a sample of the code:
`new MapboxLayer({
        id: "tileset",
        type: Tile3DLayer,
        data: "...",
        loader: Tiles3DLoader,
        onTileLoad: (tile) =>
          tile.tileset.setProps({
            maximumScreenSpaceError: 0.7
          }),
        loadOptions: {
          tileset: {
            throttleRequests: true,
          }
        },
        _subLayerProps: {
          scenegraph: {
            _lighting: "flat",
          }
        }
      }),`

**Comment by ibgreen** [comment]
@belom88 @dryabinin-actionengine @igorDykhta 

I have not seen this type of issue before. Trying to guess what could cause it - are we rendering multiple resolutions (parent and child) of the mesh at the same time?

**Comment by dryabinin-actionengine** [comment]
@yan-map Hello! To make sure that your data is valid please upload your tileset in [Cesium ION](https://cesium.com/ion/assets/1). Make sure there are no such gaps as you shown. So if they are still there - the problem with data, If not -  we need to fix it on our side. Also it will be good if you provide some open for testing examples for us for debugging purposes.

**Comment by yan-map** [comment]
> @yan-map Hello! To make sure that your data is valid please upload your tileset in [Cesium ION](https://cesium.com/ion/assets/1). Make sure there are no such gaps as you shown. So if they are still there - the problem with data, If not - we need to fix it on our side. Also it will be good if you provide some open for testing examples for us for debugging purposes.
Hi! Here's an example

This tileset works perfectly on Cesium JS, here's an example on deck.gl
https://sbw00.csb.app/

**Comment by Pessimistress** [comment]
@yan-map can you try my suggestion above?

**Comment by yan-map** [comment]
> @yan-map can you try my suggestion above?

That worked, thank you!

**Comment by Pessimistress** [comment]
@dryabinin-actionengine Can you update the Tile3DLayer to add this prop to all sub layers:

https://github.com/visgl/deck.gl/blob/d67688e3f71a37e2f021dde6681bb1516bebac2b/modules/geo-layers/src/tile-layer/tile-layer.js#L215

See https://github.com/visgl/deck.gl/pull/4388

**Comment by dryabinin-actionengine** [comment]
@Pessimistress Done - [PR](https://github.com/visgl/deck.gl/pull/6108)

**Comment by Pessimistress** [comment]
Thank you! Fix is published in 8.5.4.
