### ISSUE TITLE
GoogleMapsOverlay with Scatterplot/GeoJson Circles

### ISSUE THREAD

**Issue by MikeKeane** [visgl/deck.gl#6100]
I've been using deck.gl and the GoogleMapsOverlay to visualise data on my map.  

The problem I'm facing is when using either the ScatterplotLayer or the GeoJsonLayer to draw circles to the map, when panning up and down (north and south) the circles appear to grow/shrink, quite considerably.  It appears more apparent when the radius is quite large, for example, I have some that are 100000 meters and larger.  

I had not noticed this at first but when going back to the Google Maps documentation (which is where I came across deck.gl), it appears their example does the same (https://developers.google.com/maps/documentation/javascript/examples/deckgl-points).

**Comment by Pessimistress** [comment]
This is due to the Mercator projection's [distortion](https://en.m.wikipedia.org/wiki/Mercator_projection#/media/File%3AMercator_with_Tissot's_Indicatrices_of_Distortion.svg). Thesame meter size appears larger towards the poles.

If you want stable radius, use `radiusUnits: 'pixels'`.

Please only open issues using the provided templates. If you have a question, go to Discussions.

**Comment by MikeKeane** [comment]
@Pessimistress 
I do not want a consistent radius at different zoom levels (I understand that can be achieved by simply changing the radiusUnits).

The problem is, that the radius changes when panning around the map, without zooming.  So a circle drawn just above the equator, appears to grow/shrink as the user pans up and down the map.  

I understand that the projection used distorts the actual size of countries, etc, that are near the poles but this is not what is happening.  The link I provided to Google's documentation clearly shows the problem.  If you pan around that map, you will see the circles growing and shrinking as you do.  The radiusUnits property is set to "meters", so at any given zoom level, the size of the circle should not change by simply moving around the map.  

You have closed this issue but I do not think you have addressed it.
