### ISSUE TITLE
assertion failed when using external view state with react-map-gl 

### ISSUE THREAD

**Issue by cgarrovillo** [visgl/deck.gl#6104]
#### Description

Upon trying to use an [Externally Managed View State](https://deck.gl/docs/developer-guide/interactivity#externally-manage-view-state) alongside `react-map-gl` (as seen here: https://deck.gl/docs/api-reference/mapbox/overview#using-with-react),  an exception is thrown.
#### Expected Behavior

Externally managed view state should behave as said in Docs

#### Repro Steps

https://codesandbox.io/s/deck-gl-react-map-libre-uqnzu?file=/src/App.js

#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]
 - Browser Version: [e.g. Chrome 78.0]
 - OS: [e.g. Mac OS X 10.15 / iOS 14.2]
deck.gl 8.5.3
firefox 92.0
MacOS 10.15

#### Logs

```
Error: deck.gl: assertion failed.
    assert assert.js:6
    MapState map-controller.js:71
    setProps map-controller.js:432
    _updateController view-manager.js:281
    _rebuildViewports view-manager.js:318
    _update view-manager.js:186
    setProps view-manager.js:176
    _updateCanvasSize deck.js:461
    _setGLContext deck.js:697
    onInitialize deck.js:512
    onInitialize animation-loop.js:265
    startPromise animation-loop.js:162
    promise callback*start animation-loop.js:138
    Deck deck.js:221
    createDeckInstance deckgl.js:64
    node_modules vendors~main.chunk.js:21942
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 3
    workLoop scheduler.development.js:417
    flushWork scheduler.development.js:390
    performWorkUntilDeadline scheduler.development.js:157
    js scheduler.development.js:180
    js scheduler.development.js:645
    Webpack 21
index.js:1

```

**Comment by Pessimistress** [comment]
In your code pen, 

```js
onViewStateChange={setViewState}
```

should be
```js
onViewStateChange={e => setViewState(e.viewState)}
```
