### ISSUE TITLE
highlightColor function isn't working for MVTLayer

### ISSUE THREAD

**Issue by NgoKnows** [visgl/deck.gl#6120]
#### Description
When providing `highlightColor` as a function to MVTLayer, the function isn't executed as expected. Rather what is happening is that the auto highlight shows up as a `cyan` color.

#### Expected Behavior
If `highlightColor` is provided as a function, that function would be executed for the picked object to determine the highlight color.

#### Repro Steps
- https://codesandbox.io/s/deck-gl-mvttilelayer-example-forked-0z17x?file=/src/App.js
- 
![Kapture 2021-08-19 at 12 32 27](https://user-images.githubusercontent.com/8966794/130133366-346e4407-5a69-414a-a6f6-fd605c4c7ad8.gif)

#### Environment
 - Framework Version: deck.gl 8.5.4
 - Browser Version: Chrome 92
 - OS: Mac OS X 11.2

**Comment by Pessimistress** [comment]
Fixed in v8.6.5.
