### ISSUE TITLE
[GlobeView]: tile bounding volume is wrong for [0, 0, 0] osm tile

### ISSUE THREAD

**Issue by igorDykhta** [visgl/deck.gl#6147]
#### Description
For [0, 0, 0] OSM tile the bounding volume is calculated incorrectly.
Multiple ref points are projected to the position as the topmost tile wraps around the whole globe 360° x 170°

![image](https://user-images.githubusercontent.com/8210766/131408063-1ec201d6-649e-4043-b775-0163c1e91606.png)

And as result the bounding volume is calculated as:

center: (3) [0, 0, 0]
halfAxes: 
[ 3-14 0 0
   0 256 0 
  0 0 255 ]

#### Expected Behavior
- Bounding volume should contain the whole tile (globe in this case). 

Adding two additional sampling points for z = 0 level should solve the problem.

**Comment by Pessimistress** [comment]
Fix landed in v8.5.7.
