### ISSUE TITLE
GeoJsonLayer only create sublayers which target geometry type exists in the data  when _subLayerProps is set

### ISSUE THREAD

**Issue by fifzteen** [visgl/deck.gl#6149]
#### Target Use case
GeoJsonLayer only creates sublayers which target geometry type exist in the data.
But when changing sublayer's props with `_subLayerProps`, GeoJsonLayer creates all sublayers.

This is a sample.
https://codepen.io/fifzteen/pen/MWoKVVd
I set no Polygon data, but GeoJsonLayer creates 'polygons-fill' and 'polygons-stroke'.

If GeoJsonLayer has `pickable: true`, this increases pickable layers we don't need.
In usecase as sublayer of some TileLayer, pickable layers count reach 255 soon.

#### Proposed feature
GeoJsonLayer only creates sublayers which target geometry type exist in the data, even though `_subLayerProops` is set.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [ ] What’s new update 
  - [x] Test

**Comment by Pessimistress** [comment]
That sounds reasonable. Would you open a PR to change the check here: 

https://github.com/visgl/deck.gl/blob/e26e60aa32c164813fabc844d7ffdade2e2bfd3c/modules/core/src/lib/composite-layer.js#L92

to drop

```js
(overridingProps && overridingProps[id])
```

**Comment by Pessimistress** [comment]
Published v8.5.7
