### ISSUE TITLE
Heatmap - expose additional properties

### ISSUE THREAD

**Issue by igorDykhta** [visgl/deck.gl#6157]
#### Target Use case
Exposing several properties of Heatmap layer can be beneficial.

#### Proposed feature
- expose debounceTimeout prop to be able to control debounce timeout by adjusting it based on dataset size and radius.
- expose weightsTextureSize prop to control performance of max-weight calculation, rendering quality, memory usage.
- expose a callback to be able to modify weights transform shaders.
- move updateState logic to a separate method to be able to override it in an extended class.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Published v8.5.7
