### ISSUE TITLE
Text layer is not adjusting to the angle assigned to getAngle prop (slightly different slope)

### ISSUE THREAD

**Issue by vissharm** [visgl/deck.gl#6162]
[####](url) Description
Text layer is not aligning text as per angle

#### Expected Behavior
It should align text as per provided angle

#### Repro Steps
1. Create a line between two points (path array having lng,lat values)
2. Now try to add text layer between same points. You will see in case of slopes, it will not get aligned properly. You can verify that instantly by looking and the line and then text rendered. Not in same alignment.
--> Now in case of parallel lines, it looks more bad.

Please refer screenshot. Slope formula is common and standard.

Slope calculation :- 
```
export function getSlopeOfLineInDegree (x1, y1, x2, y2) {
  const slope = getSlopeOfLine(x1, y1, x2, y2)

  return (Math.atan(slope) * 180) / Math.PI
}

export function getSlopeOfLine (x1, y1, x2, y2) {
  const slope = (y2 - y1) / (x2 - x1)
  // return Math.abs(slope)
  return slope
}

```

Other logic I used, but it's similar and has the same issue.
I swap start and end in the params-order for below logic if pointA.x > pointB.x

```
export function calculateSlope (pointA, pointB) {
  let deltaX = pointB.x - pointA.x
  let deltaY = pointB.y - pointA.y
  let slopeAngleInRadian = Math.atan(deltaY / deltaX)
  let slopeAngleInDegrees = toDegrees(slopeAngleInRadian)
  if (deltaX < 0) {
    slopeAngleInDegrees += 180
  } else if (deltaY < 0) {
    slopeAngleInDegrees += 360
  }
  return slopeAngleInDegrees
}

function toDegrees (angle) {
  return angle * (180 / Math.PI)
}

```
#### Environment
MacOS & Windows both

Notes: 
I am using below properties.
getAngle: slope calculation   
getTextAnchor: 'middle',
getAlignmentBaseline: 'center',

**Comment by vissharm** [comment]
![image](https://user-images.githubusercontent.com/21159071/132085766-dbb767b1-bce5-4363-a644-c627cca3c736.png)

**Comment by vissharm** [comment]
I am not able to resolve it since quite long.... expecting you guys might be able to help.

**Comment by Pessimistress** [comment]
Can you at least provide the code that you use to calculate angle?

**Comment by vissharm** [comment]
> Can you at least provide the code that you use to calculate angle?

Added slope calculation logic, which is used by getAngle prop.

**Comment by vissharm** [comment]
@Pessimistress Also as I migrated from 8.4 to 8.5 hover seems to break over paths..... Any idea?

**Comment by Pessimistress** [comment]
Your calculation of angle is incorrect. Distances along one degree longitude and one degree latitude are not equal. You can use [turf.js](http://turfjs.org/docs/#bearing) to calculate the heading between two geospatial points.

Closing this as it's not a deck.gl bug. If you need help with your own code, please go to Discussions.

**Comment by vissharm** [comment]
@Pessimistress bearing gives a totally different angle.....
