### ISSUE TITLE
autohighlight stop working while migrating from 8.4 to 8.5 deck.gl version (pathlayer and textlayer)

### ISSUE THREAD

**Issue by vissharm** [visgl/deck.gl#6163]
#### Description
autohighlight stop working while migrating from 8.4 to 8.5 deck.gl version (pathlayer and textlayer)

#### Expected Behavior
autohighlight should work as it was working in 8.4

#### Repro Steps
try to assign autohighlight property to true in pathlayer or textlayer with 8.5 deckgl version

#### Environment
windows and mac os (chrome browser)

**Comment by Pessimistress** [comment]
Please provide a Codepen/CodeSandbox that reproduces your issue.

**Comment by vissharm** [comment]
ok , I will create one and share in today or tomorrow.

**Comment by vissharm** [comment]
@Pessimistress Closing this as this is working fine in the codesandbox example I created. Only difference in my code is , in the example I create react declarative layer object, but in my project due to complexity.. I create those layers objects in javascript and asssign to <deckgl react component layers property by pushing multiple layers into array.
