### ISSUE TITLE
`TileLayer` Update Triggers

### ISSUE THREAD

**Issue by ilan-gold** [visgl/deck.gl#6179]
#### Target Use case
For Viv, when you make a new channel selection (i.e the drop downs above the colored sliders on avivator.gehlenborglab.org), the the whole `TileLayer` reloads which means there is a gap where there is no image on the screen from the `TileLayer`.

Our channel update mechanism is done via an update trigger: https://github.com/hms-dbmi/viv/blob/cac61bed228d28110db688fa30a3c2888d16a6d6/src/layers/MultiscaleImageLayer/MultiscaleImageLayer.js#L194-L196

#### Proposed feature

Is there a way to leave up the tiles until the `Tileset2D` has updated its tiles and is ready to swap out layers?  Is this desired behavior?  I can try to make a PR for this if it seems reasonable. 

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [x] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ilan-gold** [comment]
It's totally possible that this can be achieved without a new feature in which case I can close this!

**Comment by Pessimistress** [comment]
I think the easiest way to do this is to add a `reload` method to `Tileset2D`, and call it instead of discarding the current cache here: https://github.com/visgl/deck.gl/blob/v8.5.7/modules/geo-layers/src/tile-layer/tile-layer.js#L61

**Comment by ilan-gold** [comment]
@Pessimistress That sounds clean.  I was hacking on Thursday but having trouble with exactly how to make it smooth.
