### ISSUE TITLE
BitmapLayer with HTML Canvas is distorted after properties update

### ISSUE THREAD

**Issue by aparshin** [visgl/deck.gl#6192]
#### Description
Here is a code pen: https://codepen.io/parshin/pen/oNwwqde
  1. Initially, a single BitmapLayer is added to the map. The image is an HTML canvas element filled with green. It is rendered as a green rectangle on the map.
  2. When I click on the "Update layer properties" button, I create a new layer with the same properties. HTML canvas is recreated, but it's still filled with green.
  3. After calling `map.setProps()` method, I see a black rectangle on the map.

#### Expected Behavior
I expect to see a green rectangle after the properties update.

#### Environment
 - Framework Version: Deck.gl latest (https://unpkg.com/deck.gl@latest/dist.min.js)
 - Browser Version: Chrome, Firefox
 - OS: Ubuntu 16.04

**Comment by Pessimistress** [comment]
Thanks for reporing. It seems that the `image` prop is not resolved to the correct value when it's set to `canvas` directly. While we work on a fix, if this is blocking you, try `image: Promise.resolve(canvas)` as a work around.

**Comment by aparshin** [comment]
@Pessimistress Thank you for the workaround! Looks like it works fine.

Just a minor note: Promises as possible values of the `image` property are not mentioned on https://deck.gl/docs/api-reference/layers/bitmap-layer
