### ISSUE TITLE
After upgrade to 8.5 from 8.4, Icons from IconLayer became bigger than usual.

### ISSUE THREAD

**Issue by phyopwint1912** [visgl/deck.gl#6200]
Hello, 
I realized that icons size are changing after I have upgraded deck-gl version to the latest one. When I looked at the upgrade guidelines, nothing is mentioned regards to the IconLayer. Do we know what is the reason behind. TIA :) 

After upgrade,
![image](https://user-images.githubusercontent.com/17942350/133368132-568c4532-0107-447a-ad6b-068bf60a65ed.png)

Before upgrade,
![image](https://user-images.githubusercontent.com/17942350/133368092-7d8934ea-658b-4906-bb20-a457dcbc334f.png)

**Comment by Pessimistress** [comment]
Please only use templates to open issues.

Also if you search in issues or discussion you can find several people asking the same question.
