### ISSUE TITLE
Need to specify the uniqueIdProperty for highlighting to work in MVTLayer

### ISSUE THREAD

**Issue by borja-munoz** [visgl/deck.gl#6204]
#### Description
Highlighting with MVTLayer using vector tiles does not work for a line dataset unless the uniqueIdProperty is set.

#### Expected Behavior
It shouldn't be needed to specify the property if the dataset contains a column with the default name (cartodb_id)

#### Repro Steps
https://codepen.io/borja-munoz/pen/QWgOGWw

#### Environment
 - Latest deck.gl (8.5.8)
 - Browser Version: Chrome Version 93.0.4577.63
 - OS: Mac OS X 11.4

#### Logs
No errors or warnings in the console

**Comment by Pessimistress** [comment]
MVTLayer is vendor neutral. It will not be coded to look for a specific name such as cartodb_id. If you need more CARTO integration features you can look into the [CartoLayer](https://deck.gl/docs/api-reference/carto/overview).

**Comment by alasarr** [comment]
Agree with @Pessimistress , a better place to include it is at CartoLayer. Doesn’t it happen with polygons or points?

**Comment by borja-munoz** [comment]
Sorry, my fault. I started with CartoLayer but I switched later the bug to MVTLayer.

It happens with all the geometry types. I'm opening another issue for CartoLayer.
