### ISSUE TITLE
GeoJsonLayer not parsing x, z & y vars

### ISSUE THREAD

**Issue by psociety** [visgl/deck.gl#6210]
#### Description
DeckGL does not process `{z}`, `{x}`, `{y}` vars from a GeoJsonLayer url :S

#### Expected Behavior
To have the vars properly replaced.

#### Repro Steps
Use the following layer:
```js
const roadLayer = new GeoJsonLayer({
    id: 'geojson-layer',
    data: "http://localhost:8123/map/{z}/{x}/{y}.geojson",
    pickable: true,
    stroked: false,
    filled: true,
    extruded: true,
    pointType: 'circle',
    lineWidthScale: 10,
    lineWidthMinPixels: 2,
    getFillColor: [160, 160, 180, 200],
    getLineColor: f => {
      const hex = '#eccc2e78';
      // convert to RGB
      return hex ? hex.match(/[0-9a-f]{2}/g).map(x => parseInt(x, 16)) : [0, 0, 0];
    },
    getPointRadius: 100,
    getLineWidth: 0.3,
    getElevation: 30
  });
```

#### Environment
 - Framework Version: deck.gl 8.5.6

#### Logs
Output url is `http://localhost:8123/map/%7Bz%7D/%7Bx%7D/%7By%7D.geojson`

**Comment by Pessimistress** [comment]
Use the [TileLayer](https://deck.gl/docs/api-reference/geo-layers/tile-layer#data).
