### ISSUE TITLE
MultiPolygon not rendered in renderSubLayers when using a MapboxLayer of type MVTLayer

### ISSUE THREAD

**Issue by CoMeMak** [visgl/deck.gl#6215]
Dear deck.gl team, many thanks for the amazing library that you crafted here! We've been using it successfully until this little mishap occurred.

#### Description
We are trying to visualize concave polygons provided by a geoserver instance in the "application/vnd.mapbox-vector-tile" format. 

Problem: Depending on the zoom level, when a tile contains two sub-polygons, none of them is rendered. The problem seems to be that, when attempting to render sublayers, larger convex polygons sometimes get divided into MultiPolygons, which are not handled correctly by deck.gl. 

Here are some additional infos about the data and layer definition:

- The data source URL is formatted as follows: 

http://localhost:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=poly:polygons-2Polygon&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/vnd.mapbox-vector-tile&TILECOL={x}&TILEROW={y}

- We instantiate the layer as follows (the code below might not be 100% clean):

```javascript
var layer = new MapboxLayer({
      id: "poly",
      type: MVTLayer,
      data: ...,
      props: var props = {
      renderSubLayers: (props) => getSubLayers(props),
	  visible: true,
	  filled: true,
          getLineWidth: 2,
          getLineColor: [0,0,150],
	  getFillColor: [0,150,0],
    }
		  
    });
```

- The getSubLayers function looks like this:

```javascript
function getSubLayers(props) {
    let polygonProps = { ...props }
	polygonProps.getPolygon = f => 
	{
		if(f.geometry.type == "MultiPolygon")
		{
			console.log("set breakpoint here");
		}
		
		return f.geometry.coordinates;
	}
	var pl = new PolygonLayer(polygonProps);
	
    return [
      pl,	  
    ]
  }
```

#### Expected Behavior
The MultiPolygon should be rendered correctly.

#### Repro Steps

Let's assume the execution reaches the getSubLayers function, where the condition f.geometry.type == "MultiPolygon" is checked. 

Let's further assume that the relative geometry.coordinates are:

```javascript
f.geometry.coordinates == '[[[[0.365966796875,1.0068359375],[0.16064453125,1.0068359375],[0.11865234375,0.91455078125],[0.208251953125,0.77734375],[0.2109375,0.75537109375],[0.218017578125,0.719970703125],[0.242431640625,0.671875],[0.278076171875,0.644287109375],[0.30078125,0.64013671875],[0.308837890625,0.640625],[0.338623046875,0.652587890625],[0.37060546875,0.689208984375],[0.388916015625,0.742919921875],[0.391357421875,0.789306640625],[0.39013671875,0.80419921875],[0.365966796875,1.0068359375]]],[[[-0.0068359375,0.06201171875],[-0.0068359375,-0.0068359375],[0.36767578125,-0.0068359375],[0.715576171875,1.0068359375],[0.5107421875,1.0068359375],[0.226318359375,0.1787109375],[0.158935546875,0.223876953125],[0.06787109375,0.08642578125],[0.068603515625,0.0693359375],[-0.0068359375,0.06201171875]]]]'
```

... and f.geometry.type == 'MultiPolygon'

Note that in the data we have two polygons that are actually part of the same polygon at a higher zoom level. 

Using https://unpkg.com/deck.gl@8.5.8/dist/dist.dev.js, we get the following error:

Error: initialization of SolidPolygonLayer({id: 'clusters-34203-22654-16-fill'}): Illegal attribute generated for positions
    at Attribute._checkAttributeArray (deck_gl_.js:75903)
    at Attribute.updateBuffer (deck_gl_.js:75696)
    at AttributeManager._updateAttribute (deck_gl_.js:75175)
    at AttributeManager.update (deck_gl_.js:75009)
    at SolidPolygonLayer._updateAttributes (deck_gl_.js:79516)
    at SolidPolygonLayer._updateState (deck_gl_.js:79764)
    at SolidPolygonLayer._initialize (deck_gl_.js:79706)
    at LayerManager._initializeLayer (deck_gl_.js:78945)
    at LayerManager._updateSublayersRecursively (deck_gl_.js:78909)
    at LayerManager._updateSublayersRecursively (deck_gl_.js:78924)

Here's how this can be patched so that the problem does not occur anymore:

*Original _forEachGeometry (line 86221):*

```javascript
_forEachGeometry(visitor, startRow, endRow) {
    const {data, getGeometry} = this;
    const {iterable, objectInfo} = Object(_iterable_utils__WEBPACK_IMPORTED_MODULE_0__["createIterable"])(data, startRow, endRow);
    for (const object of iterable) {
      objectInfo.index++;
      const geometry = getGeometry(object, objectInfo);
      visitor(geometry, objectInfo.index);
    }
  }
```

*Patched _forEachGeometry:*

```javascript
  _forEachGeometry(visitor, startRow, endRow) {
    const {data, getGeometry} = this;
    const {iterable, objectInfo} = Object(_iterable_utils__WEBPACK_IMPORTED_MODULE_0__["createIterable"])(data, startRow, endRow);
	
	for (const object of iterable) {
	  objectInfo.index++;
	  const geometry = getGeometry(object, objectInfo);
	  if(object != null && object.geometry != null && object.geometry.type == "MultiPolygon")
	  {
		  for(var i=0;i<geometry.length;i++)
		  {
			  visitor(geometry[i], i);
		  }		  
	  }
	  else
	  {
		  visitor(geometry, objectInfo.index);
	  }
    }
  }
```

*Original _getPath (line 99154):*

```javascript
  _getPaths(dataRange = {}) {
    const {data, getPolygon, positionFormat, _normalize} = this.props;
    const paths = [];
    const positionSize = positionFormat === 'XY' ? 2 : 3;
    const {startRow, endRow} = dataRange;

    const {iterable, objectInfo} = Object(_deck_gl_core__WEBPACK_IMPORTED_MODULE_0__["createIterable"])(data, startRow, endRow);
    for (const object of iterable) {
      objectInfo.index++;
      let polygon = getPolygon(object, objectInfo);
      if (_normalize) {
        polygon = _solid_polygon_layer_polygon__WEBPACK_IMPORTED_MODULE_3__["normalize"](polygon, positionSize);
      }
      const {holeIndices} = polygon;
      const positions = polygon.positions || polygon;

      if (holeIndices) {
        // split the positions array into `holeIndices.length + 1` rings
        // holeIndices[-1] falls back to 0
        // holeIndices[holeIndices.length] falls back to positions.length
        for (let i = 0; i <= holeIndices.length; i++) {
          const path = positions.slice(holeIndices[i - 1] || 0, holeIndices[i] || positions.length);
          paths.push(this.getSubLayerRow({path}, object, objectInfo.index));
        }
      } else {
        paths.push(this.getSubLayerRow({path: positions}, object, objectInfo.index));
      }
    }
    return paths;
  }
```

*Anything but elegant patch:*

```javascript
_getPaths(dataRange = {}) {
    const {data, getPolygon, positionFormat, _normalize} = this.props;
    const paths = [];
    const positionSize = positionFormat === 'XY' ? 2 : 3;
    const {startRow, endRow} = dataRange;

    const {iterable, objectInfo} = Object(_deck_gl_core__WEBPACK_IMPORTED_MODULE_0__["createIterable"])(data, startRow, endRow);
    for (const object of iterable) {
      objectInfo.index++;
      let polygon = getPolygon(object, objectInfo);
	  let polis = [];
	  // HACKHACK
	  if(object.geometry.type == "MultiPolygon")
	  {
		  polis = polygon;
	  }
	  else
	  {
		  polis.push(polygon);
	  }
	  
	  for(var i=0;i<polis.length;i++)
	  {
		  polygon = polis[i];
		  if (_normalize) {
			polygon = _solid_polygon_layer_polygon__WEBPACK_IMPORTED_MODULE_3__["normalize"](polygon, positionSize);
		  }
		  const {holeIndices} = polygon;
		  const positions = polygon.positions || polygon;

		  if (holeIndices) {
			// split the positions array into `holeIndices.length + 1` rings
			// holeIndices[-1] falls back to 0
			// holeIndices[holeIndices.length] falls back to positions.length
			for (let i = 0; i <= holeIndices.length; i++) {
			  const path = positions.slice(holeIndices[i - 1] || 0, holeIndices[i] || positions.length);
			  paths.push(this.getSubLayerRow({path}, object, objectInfo.index));
			}
		  } else {
			paths.push(this.getSubLayerRow({path: positions}, object, objectInfo.index));
		  }
	  }
    }
    return paths;
  }
```

#### Environment
 - Framework Version: deck.gl 8.5.8
 - Browser Version: [e.g. Chrome 93.0.4577.63]
 - OS: Windows 10 Pro, 64bit

We obviously don't want to maintain this patch in our codebase.

Is there a layer property that I'm missing, which could trigger the correct behavior? 

Any suggestions would be greatly appreciated! 

Thank you very much!

Best wishes,
Tudor

**Comment by Pessimistress** [comment]
PolygonLayer's `getPolygon` must return a single polygon, not an array of polygons. See [documentation](https://deck.gl/docs/api-reference/layers/polygon-layer#getpolygon).

You should instead use the GeoJsonLayer, which can correctly handle the MultiPolygon type.

**Comment by CoMeMak** [comment]
Yes, that works. Many thanks.

Best wishes,
Tudor
