### ISSUE TITLE
H3HexagonLayer - force instanced rendering, exit h3 data analysis loop early

### ISSUE THREAD

**Issue by igorDykhta** [visgl/deck.gl#6238]
#### Target Use case
Forcing instanced rendering for H3HexagonLayer layer can be beneficial for performance.
Skipping initial initialization analysis in updateState can save 20%-30% of initialization time.

#### Proposed feature
- force instanced rendering by **highPrecision: false**.
- automatically select rendering mode by **highPrecision: 'auto'**.
- skip h3 data analysis for **highPrecision: true** mode.
- get resolution from the first h3 index for **highPrecision: false** mode and exit h3 data analysis loop early.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ibgreen** [comment]
@igorDykhta @isaacbrodsky @nrabinowitz  Can `hasPentagon` be deduced from resolution (assuming true for top level resolution) or do we gain benefit from being even more specific?

**Comment by dfellis** [comment]
> @igorDykhta @isaacbrodsky @nrabinowitz Can `hasPentagon` be deduced from resolution (assuming true for top level resolution) or do we gain benefit from being even more specific?

Every resolution has exactly 12 pentagons, so that on its own can't be the determining factor.

The underlying icosahedron in H3 could be useful here. The pentagons sit at the points of the triangle faces on the icosahedron, so you could check if any of those 12 lat, lng pairs are visible (or close enough to visible, depending on the resolution as lower resolutions will have larger pentagons).

**Comment by nrabinowitz** [comment]
Something else we could do here, which @Pessimistress implemented for an H3 tiling layer at one point - you can check `h3GetFaces` for the corners of the viewport, and if you have > 1 face represented, use precise rendering. This is less precise, though, as you may not have data in those areas, so you could force precise rendering unnecessarily.

This is moot if we pass in the resolution and `hasPentagon` explicitly, however.
