### ISSUE TITLE
Trip Layer and Terrain Layer 

### ISSUE THREAD

**Issue by maevarun** [visgl/deck.gl#6258]
#### **Description**
Hey! I try to render a track with terrain layer. 
This is a scientific project on an ultra trail race.
I have an .gpx file and I can retrieve the data with latitude and longitude.

But how to recover the altitude to reproduce it on the terrain layer ? 
Is there a function like get_altitude ? Or the function get_coordinates is enough ? And in this case, how to do this ?

I would appreciate any help!!

I use Python with Jupyter

#### **The code**

`df2 = df.copy()

df2["coordinates"] = df2["waypoints"].apply(lambda f: [item["coordinates"] for item in f])
df2["timestamps"] = df2["waypoints"].apply(lambda f: [item["timestamp"] - 946691608 for item in f])

df2.drop(["waypoints"], axis=1, inplace=True)

terrain_layer = pdk.Layer(
    "TerrainLayer", 
    elevation_scale=100,
    radius=50,
    elevation_decoder=ELEVATION_DECODER, 
    texture=SURFACE_IMAGE, 
    elevation_data=TERRAIN_IMAGE
)

track_layer = pdk.Layer(
    "TripsLayer",
    df2,
    get_path="coordinates",
    get_timestamps="timestamps",
    get_color=[253, 128, 93],
    opacity=0.8,
    width_min_pixels=5,
    rounded=True,
    fadeTrail = True,
    trail_length = 60000000,
    current_time = 5000000,
    trailLength = 150
)

view_state = pdk.ViewState(
    latitude=-21.115141, 
    longitude=55.536384, 
    zoom=10.5, 
    bearing=140, 
    pitch=60)

mapSector = pdk.Deck(
    layers=[terrain_layer, track_layer], 
    initial_view_state=view_state)

mapSector.to_html("terrain_trip.html")`

#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]

**Comment by Pessimistress** [comment]
This is not a bug report. Please use Discussions if you need help.
