### ISSUE TITLE
[Rect deck.gl] Expose layers (iconlayer, pathlayer etc) objects and related API's to update properties of specific objects instead of recreate and rerender whole layer

### ISSUE THREAD

**Issue by vissharm** [visgl/deck.gl#6262]
#### Target Use case
[Rect deck.gl] Expose layers (iconlayer, pathlayer etc) objects and related API's to update properties of specific objects instead of recreate and rerender everything. This will improve the performance drastically.

#### Proposed feature
User should be able to update/delete particular objects from the deck.gl layers instead of recreating/re-rendering everything again. e.g. Update icon position on user drag operation or update specific path stroke in pathlayer.

**Comment by Pessimistress** [comment]
See discussion #6254

**Comment by vissharm** [comment]
@Pessimistress We still don't have any support in case of new object addition or deletion from data array. It will still rerender the whole layer i.e. rewrite the whole layer using GPU,

**Comment by kylebarron** [comment]
See https://deck.gl/docs/faq#should-i-really-regenerate-all-layers-every-time-something-changes

**Comment by Pessimistress** [comment]
@vissharm I have detailed my opinion about imperative API and React in the linked discussion thread. Deck.gl already have APIs and best practices that optimize for incremental data change, and they work with or without React. Please move there to make your argument so we don't have to duplicate our comments.

**Comment by vissharm** [comment]
Sure @Pessimistress
