### ISSUE TITLE
ScenegraphLayer not available in streamlit by way of json / pydeck, "JSON converter: No registered class of type ScenegraphLayer"

### ISSUE THREAD

**Issue by krosaen** [visgl/deck.gl#6278]
#### Description
I'm attempting to use `ScenegraphLayer` in pydeck

#### Expected Behavior
I'd like to be able to reproduce this example

https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer

in pydeck within streamlit 

https://docs.streamlit.io/en/stable/api.html#streamlit.pydeck_chart

#### Repro Steps
```
    sample_model_layer = pydeck.Layer(
        "ScenegraphLayer",
        [
            {"name": "test",
             "coords" : [-83.7582848, 42.2739968],
            },
        ],
        "scenegraph-layer",
        get_position="coords",
        scenegraph='https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF-Binary/BoxAnimated.glb',
    )

    deck = pydeck.Deck(
        map_style="mapbox://styles/mapbox/light-v9",
        initial_view_state=pydeck.ViewState(
            latitude=42.2739968,
            longitude= -83.7582848,
            # latitude=np.median(gps_data.lat_lon.apply(lambda x: x[0])),
            # longitude=np.median(gps_data.lat_lon.apply(lambda x: x[1])),
            zoom=14,
            pitch=0,
        ),
        layers=[sample_model_layer],
    )
    streamlit.write(deck)
```
The rendered page, on the javascript side, ends up with 

"JSON converter: No registered class of type ScenegraphLayer"

I set a breakpoint and confirmed that at the logging point

https://github.com/visgl/deck.gl/blob/3d760068d788cf23487e8645a22ab6ecc029e26b/modules/json/src/helpers/instantiate-class.js#L14

`configuration.classes` does not include any of the mesh layers.

#### Environment
pydeck 0.7.0

**Comment by krosaen** [comment]
@kylebarron interesting - but that's within jupyter-widgets - how does one configure the inclusion of the mesh layers for pydeck used outside of jupyter notebooks? I'm using streamlit and importing pydeck.

**Comment by karl-rosaen-skydio** [comment]
I think I have a fix:

https://github.com/streamlit/streamlit/pull/4027

**Comment by krosaen** [comment]
oh wait I linked to the wrong issue :) I'm closing this because the issue was with streamilt's, I have a PR open over there now

https://github.com/streamlit/streamlit/issues/3895
