### ISSUE TITLE
Add a fullscreen control to a map

### ISSUE THREAD

**Issue by giswqs** [visgl/deck.gl#6285]
Is it possible to add a fullscreen control to a pydeck map? Similar to the Mapbox GL JS?

https://docs.mapbox.com/mapbox-gl-js/example/fullscreen
![image](https://user-images.githubusercontent.com/5016453/136678617-08be9f96-07e4-4d5e-909f-31e84c4c9716.png)

**Comment by andhuang-CLGX** [comment]
Is this it?
https://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control/

But is it exposed on the python / pydeck side?

**Comment by kylebarron** [comment]
On the JS side you can add the full screen control from `react-map-gl`. I don't believe there's currently a way to do this through Pydeck.

**Comment by andhuang-CLGX** [comment]
Does pydeck expose any hooks to the JS side (i.e. add additional JS to add full screen)

**Comment by giswqs** [comment]
Both folium and ipyleaflet have the fullscreen button. It would be nice if pydeck can have it as well.

**Comment by andhuang-CLGX** [comment]
Is there a way to combine https://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control with https://deck.gl/docs/api-reference/json/conversion-reference

**Comment by Jamal8548** [comment]
SO HERE WE GO!!! HACK SOLUTION
Use [react-map-gl](https://visgl.github.io/react-map-gl/examples/controls) Components with DeckGL
For React users, it is now easy to use react-map-gl components with DeckGL, including DOM-based [marker](https://visgl.github.io/react-map-gl/docs/api-reference/marker), [popup](https://visgl.github.io/react-map-gl/docs/api-reference/popup), [navigation control](https://visgl.github.io/react-map-gl/docs/api-reference/navigation-control) and [fullscreen control](https://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control). This can be done by supplying the ContextProvider prop on DeckGL:

/// Example using react-map-gl controls with deck.gl
import DeckGL from '@deck.gl/react';
import {_MapContext as MapContext, NavigationControl} from 'react-map-gl';

<DeckGL ... ContextProvider={MapContext.Provider}>
  <div style={{margin: 10, position: 'absolute', zIndex: 1}}>
    <NavigationControl />
  </div>
</DeckGL>

**Comment by Jamal8548** [comment]
<div style={{margin: 10, position: 'absolute', zIndex: 1}}>
    <NavigationControl />
  </div>
</DeckGL>

**Comment by Jamal8548** [comment]
The above mentioned solution is only react-map-gl version below 7. v7 does not work with Deckgl.

**Comment by chjch** [comment]
Is there any update on this? Besides full-screen control, it would be nice too to have [NavigationControl](https://visgl.github.io/react-map-gl/docs/api-reference/navigation-control) exposed through pydeck.
