### ISSUE TITLE
Setting map width and height in pydeck has no effect

### ISSUE THREAD

**Issue by giswqs** [visgl/deck.gl#6286]
Even though I set `height=800, width="50%"`, the map size does not change. It seems to always use the default `width='100%', height=500`

https://deckgl.readthedocs.io/en/latest/gallery/geojson_layer.html
![image](https://user-images.githubusercontent.com/5016453/136678868-03bf8fc9-d92b-4726-9a64-6cbffdc932b2.png)

**Comment by n-splv** [comment]
This helped me:
```
r = pdk.Deck(
    layers=[layer], 
    initial_view_state=view_state, 
)
r.to_html(iframe_height=900)
```
