### ISSUE TITLE
Error when _onDrawVector is call after GoogleMapOverlay is finalized

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6298]
#### Description

When using the`GoogleMapsOverlay`, after the `overlay.setMap(null)` method is called, the `onDrawVector` method is still invoked, leading to an error.

#### Expected Behavior
While it isn't expected that the Google Maps library would call the draw method after the overlay is removed, we should handle this case, to avoid the error

**Comment by Pessimistress** [comment]
To reproduce:

- Open https://codepen.io/Pessimistress/pen/porJxmb
- Set api key and map id
- Click "hide overlay" - overlay does not disappear immediately. Now pan the map, `_onDrawVector` is called and crashes
- Comment out line 23 `mapId: GOOGLE_MAP_ID`, this causes Google Maps to fall back to raster rendering
- Click "hide overlay" - overlay disappears and no errors if pan & zoom

**Comment by felixpalmer** [comment]
Fixed in https://www.npmjs.com/package/@deck.gl/google-maps/v/8.6.1
