### ISSUE TITLE
Some props are missing from GeoJsonLayer

### ISSUE THREAD

**Issue by urdeveloper** [visgl/deck.gl#6335]
#### Target Use case
While working with GeoJsonLayer, I've noticed some of the properties related to point features are missing:

Missing props from TextLayer:
- `billboard`
- `fontSettings`

Missing props from IconLayer:
- `billboard`
- `alphaCuttoff`

Missing props from ScatterPlotLayer:
- `billboard`

It would be great to make the available GeoJsonLayer props consistent with what's available in sub layers.

#### Proposed feature
Map the missing props from GeoJsonLayer to corresponding sub layers props.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Thank you for your contribution! The new props are now available in v8.6.3.
