### ISSUE TITLE
AutoHighlight - Line or Fill or Width Only

### ISSUE THREAD

**Issue by tghamm** [visgl/deck.gl#6346]
I'm working with a `GeoJsonLayer` and I want to either change the Line Color or Fill Color or possibly the width of the line.  I found a somehwat hacky way to achieve this using onHover, but I was hoping to take advantage of the performance benefits of autoHighlight.  I see in release notes that this behavior was changed at some point, is there any way to leverage autoHighlight to only update either the Fill Color, Line Color, or Width without essentially redrawing the whole layer?

**Comment by Pessimistress** [comment]
Please only use templates to open issues. Go to Discussions for Q&A.
