### ISSUE TITLE
CARTO getData function returns map metadata

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6354]
#### Target Use case

`getData` currently only returns the actual data payload, without including metadata provided by the server

#### Proposed feature

Add a new function `getLayerData` which has an expanded return value, allowing retrieval of metadata. The `getData` function will eventually be retired, but not until a future major release as it is a breaking change.

#### To Do List
  - [x] Coding
  - [x] Test

**Comment by alasarr** [comment]
Done at 8.6.2
