### ISSUE TITLE
Nextjs / SWC compile issue: Class constructor CompositeLayer cannot be invoked without 'new'

### ISSUE THREAD

**Issue by brandonjpierce** [visgl/deck.gl#6357]
#### Description
Nextjs recently swapped to using SWC as its compiler instead of Babel. There are some pretty awesome improvements with this change but it appears Deckgl has an issue compiling with it.

![Screen Shot 2021-11-03 at 11 31 34 AM](https://user-images.githubusercontent.com/5483779/140091721-b7df8860-7bdf-47d9-969d-d4c534d9458b.png)

Note that this issue does not appear when you use the nextjs babel compiler.

#### Expected Behavior
Deckgl compiles with either Babel or SWC.

#### Repro Steps
1. Clone https://github.com/brandonjpierce/nextjs-deckgl-issue
2. Create a `.env.local` file in the repo root
3. Add in `NEXT_PUBLIC_MAPBOX_TOKEN=<token>` to `.env.local` and replace `<token>` with an actual token
4. `npm i`
5. `npm run dev`
6. Access http://localhost:3000

Error should pop up right away.

#### Environment
 - Framework Version: 8.6.1
 - Browser Version: Chrome 95.0
 - OS: Mac OS X 11.6

#### Logs
[localhost-1635953179036.log](https://github.com/visgl/deck.gl/files/7468703/localhost-1635953179036.log)

**Comment by Pessimistress** [comment]
I am not familiar with Nextjs, but this error usually happens when you mix es5/es6 class syntax. I am not aware of a browser that does not support es6 class while supporting the WebGL features that deck.gl requires. If you must transpile your app into es5 then you need to tell SWC to include the code in node_modules: https://deck.gl/docs/upgrade-guide#transpilation

**Comment by Pessimistress** [comment]
You can set SWC to target the same browsers as deck.gl's dist - `>0.2%, maintained node versions, not ie 11, not dead, not chrome 49`

https://swc.rs/docs/preset-env

**Comment by brandonjpierce** [comment]
Thanks @Pessimistress i'll try matching the browserslist settings and report back!

**Comment by brianshano** [comment]
Did you get this working @brandonjpierce ?

**Comment by brandonjpierce** [comment]
@brianshano awaiting a reply from the Vercel team (seems this error is not unique to Deckgl) https://github.com/vercel/next.js/issues/30904

**Comment by ilyabo** [comment]
I experienced the same issue. Adding the following to `next.config.js` solved it for me:
```
const withTM = require('next-transpile-modules')([
  '@deck.gl/core',
]);

module.exports = withTM({
  reactStrictMode: true,
});
```

Thanks @Pessimistress for the great explanation about the transpilation. That helped a lot to understand the root of the problem.

**Comment by brandonjpierce** [comment]
Latest version of NextJS actually resolves this out of the box now, no modifications needed 🎉 

Confirming the issue was with the SWC compiler.

**Comment by ilyabo** [comment]
Hm, I tried `next@12.0.5-canary.12`, still getting this error (when not adding `@deck.gl/core` to `withTM`).
