### ISSUE TITLE
deck.pickMultipleObjects returning duplicate features in binary MVTLayer

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6362]
#### Description
`MVTLayer` is returning duplicate features from `deck.pickMultipleObjects` when in fact there is only one in the dataset. The issue only occurs when `binary: true`.

#### Expected Behavior
Correct picking as per `binary: false`

#### Repro Steps
https://stackblitz.com/edit/deckgl-pickmultipleobjects?file=index.js
Hover over polygon and observe console output. Compare with same layer, but with `binary: false`.

**Comment by Clebal** [comment]
@felixpalmer If you zoom in, the picked feature is repeated even with binary as false.

**Comment by reececasey** [comment]
I am seeing the same issue on the GeoJsonLayer is this related?

**Comment by Pessimistress** [comment]
The issue is present when `layerFilter` or `CompositeLayer.filterSubLayer` is involved. I will put up a fix.

**Comment by Pessimistress** [comment]
Fixed in v8.6.4.
