### ISSUE TITLE
Tileset2D: Offer a mode where the parent tile is replaced only when all children are loaded.

### ISSUE THREAD

**Issue by ibgreen** [visgl/deck.gl#6367]
#### Target Use case

Improve the user experience when panning in TileLayer (and its derivatives).

#### Proposed feature

Right now the parent tile is hidden as soon as one of the children is loaded. This leads to the background (usually basemap) temporarily becoming visible until the other children are loaded. 

The minimal solution here is to offer a mode when the parent tile is replaced only when all children are loaded. Slower updates but no visual flashing.

Side note: The downside with the proposed refinement mode is that a child tile will now only be visible when all its sibling tiles have been loaded. A more refined solution would be to split the parent tile into "low res" child tiles, such that we could replace them one by one as child tiles come in. This would likely need to be done through a callback as different tiles would need to be cut in different ways (bitmaps would need to be scaled, vector tile polygons would need to be cut, etc)

@nrabinowitz @isaacbrodsky @igorDykhta 

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Does it make sense to just update the behavior of `refinementStrategy: 'no-overlap'` to match your description, instead of creating a new mode? The difference is quite subtle and I suspect it will confuse users if we have too many options.

**Comment by ibgreen** [comment]
Yes I think so. The current behavior seems broken to me. But I will take longer for data to show up, so can't rule out that someone might complain.
