### ISSUE TITLE
Heatmap Layer onHover Tooltip has no .object data

### ISSUE THREAD

**Issue by brianshano** [visgl/deck.gl#6369]
#### Description

I'm trying to display data onHover of a node with a tooltip. The hover function is working and I can render a tooltip, but I cannot quickly access the data of the hovered node with .object. 

The best I can get is the full dataset through the hover info. 
At `info.layer.props.data` where I would expect to see `info.object`

This `info.object` is available in the hover for a scatterplot and hexlayer but not for heatmap. 
Maybe there's a reason for this?

Using React

#### Expected Behavior

Tooltip info is available at info.object as per hover on scatterplotlayer

#### Repro Steps

Inspect this codepen and see the console.log results onHover. 
https://codepen.io/brianshano/pen/JjypgrJ

![image](https://user-images.githubusercontent.com/5247913/140551962-34a5fc20-298e-4bf6-9c44-b80cdf942da5.png)

Modify the deck.gl heatmap example
(https://github.com/visgl/deck.gl/tree/master/examples/website/heatmap)
with 

```
      pickable: true,
      onHover: (info) => {
        console.log('onHover heatmap', info);
      },
```

#### Environment
    "deck.gl": "^8.6.0-alpha.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-map-gl": "^5.0.0"

**Comment by Pessimistress** [comment]
What object do you expect to show up in the picking info? Heatmap is continuous and you are not hovering over any particular object.

**Comment by brianshano** [comment]
Hmm, I didn't think about that. 
I wanted to grab some data from the nearest node to the click or hover. I guess that isn't going to be straighforward. 
Thanks for the reply... not a bug I guess.
