### ISSUE TITLE
Attempted import error: '_binaryToFeature' is not exported from '@deck.gl/layers'.

### ISSUE THREAD

**Issue by neelduttahere** [visgl/deck.gl#6372]
#### Description

When I try to install deck.gl on a completely fresh instance using both npm and yarn, I get the following error when starting the development server of react using "yarn start" (and their respective start script in my package.json):

`./node_modules/@deck.gl/geo-layers/dist/esm/mvt-layer/mvt-layer.js
Attempted import error: '_binaryToFeature' is not exported from '@deck.gl/layers'.`

#### Expected Behavior

I guess this error should not be there?
#### Repro Steps

yarn add deck.gl to install deck.gl on a fresh instance, and the run the react server.

On further inspecting, I found the "_binaryToFeature" is imported in `/node_modules/@deck.gl/geo-layers/dist/esm/mvt-layer/mvt-layer.js` from @deck.gl/layers. But when I see the file under @deck.gl/layers, the function does not exist. On further comparing with previous installation for deck.gl on another server at my premises, this function exists in that instance.

#### Environment
 - Framework Version: deck.gl 8.4.20
 - Browser Version: microsoft edge Version 95.0.1020.44
 - OS: tested on linux only

**Comment by Pessimistress** [comment]
https://unpkg.com/browse/@deck.gl/layers@8.4.20/dist/esm/index.js

**Comment by neelduttahere** [comment]
> https://unpkg.com/browse/@deck.gl/layers@8.4.20/dist/esm/index.js
> 
> You should check the installed submodule versions with `yarn list "@deck.gl/*"`. They should all be the same version if installed correctly.
> 
> > yarn add deck.gl to install deck.gl on a fresh instance, and the run the react server.
> 
> A fresh instance of what exactly? What are your other dependencies? My guess is that you already have an existing yarn.lock file that locks `@deck.gl/layers` to an incompatible version.
`├─ @deck.gl/aggregation-layers@8.4.20
├─ @deck.gl/carto@8.4.20
├─ @deck.gl/core@8.4.20
├─ @deck.gl/extensions@8.4.20
├─ @deck.gl/geo-layers@8.4.20
├─ @deck.gl/google-maps@8.4.20
├─ @deck.gl/json@8.4.20
├─ @deck.gl/layers@8.4.20
├─ @deck.gl/mapbox@8.4.20
├─ @deck.gl/mesh-layers@8.4.20
├─ @deck.gl/react@8.5.0
└─ deck.gl@8.4.20
   └─ @deck.gl/react@8.4.20
Done in 4.01s.`

I guess @deck.gl/react is not up to the right version in comparison to others. Bringing the version down to 8.4.20 did the job. Thanks a lot for the support!
