### ISSUE TITLE
Layer extension is seemingly not calling `.finalize()` to delete a texture when using `testLayer`

### ISSUE THREAD

**Issue by jeffpeck10x** [visgl/deck.gl#6419]
#### Description
I am testing a layer that uses a custom extension that happens to store a texture.

```
import { testLayer } from "@deck.gl/test-utils";

describe("MyLayer", () => {
  it("renders layer", async () => {
    testMyLayer({
      Layer: MyLayer,
      testCases: [
        {
          onAfterUpdate({ layer }: OnAfterUpdateParams) { ... },
          props: { data },
        },
      ],
    });
  });
});
```

The layer being tested - `MyLayer` is a composite layer that renders a `SolidPolygonLayer` with a custom extension:
```
export class MyLayer extends CompositeLayer {
  render() {
    const { data } = props;
    return new SolidPolygonLayer({
      data,
      extensions: [new MyExtension()],
      ...
    });
  }
}
```

Where `MyExtension` maintains a texture that is passed as a uniform:
```
export class MyExtension {
  constructor(opts) {
    super(opts);
    this.opts = opts;
    this._texture = null;
  }
  finalize(): void {
    console.log("finalize was called!!!");
    this._texture?.delete();
  }
  updateState(updateStateInfo, extension) {
    if (updateStateInfo.updateTriggers.shouldMakeNewTexture) { // This is just an example...
      if (extension._texture) {
        extension._texture?.delete();
        extension._texture = null;
      }
      extension._texture = new Texture2D(...);
    }
  }
}
```

Everything seems to work correctly when I run the application, but when I run the unit tests, it fails with the cryptic message:
```
 1 Texture2Ds
 ```
 which happens in `testLayer(...)`, and points to:
```
       at cleanupAfterLayerTests (node_modules/@deck.gl/test-utils/src/lifecycle-test.js:138:14)
```

I am taking this message to mean "Hey, there is one texture that was never cleaned/deleted after the test completed."

And it looks like `.finalize()` is never called.

I am wondering why `.finalize()` is not called, and if that is related to the issue.

I am not sure if this is a bug or simply a misuse. I am using deck.gl/icon-manager.js as an example, but maybe I am misunderstanding something. If so, then I am simply looking for clarification

#### Expected Behavior
I would expect `.finalize()` to be called after the tests are complete and for `._texture` to be deleted.

#### Repro Steps
I would be happy to turn the above contrived example into a real example if the above does not help to resolve this.

#### Environment
 - Framework Version: deckl.gl 8.4.11
 - Browser Version: N/A
 - OS: Mac OS X 11.6.1

#### Logs
```
    1 Texture2Ds

      23 |   >
      24 | ) {
    > 25 |   return testLayer(params);
         |          ^
      26 | }
      27 |

      at cleanupAfterLayerTests (node_modules/@deck.gl/test-utils/src/lifecycle-test.js:138:14)
      at testLayer (node_modules/@deck.gl/test-utils/src/lifecycle-test.js:70:17)
      at testMyLayer (packages/my-layers/src/layers/my-layer/my-layer.test.ts:25:10)
      at _callee$ (packages/my-layers/src/layers/my-layer/my-layer.test.ts:62:5)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
```

**Comment by jeffpeck10x** [comment]
Aha! gotit!

It is `finalizeState`:
```
  finalizeState(extension): void {
    extension._texture?.delete();
  }
```

Works perfectly.

And right here in the documentation:
https://deck.gl/docs/developer-guide/custom-layers/layer-extensions#finalizestate

Closing this ticket.

**Comment by jeffpeck10x** [comment]
This actually still seems to be an issue with multiple `testCases`. Re-opening.

So,
```
describe("MyLayer", () => {
  it("renders layer", async () => {
    testMyLayer({
      Layer: MyLayer,
      testCases: [
        {
          onAfterUpdate({ layer }: OnAfterUpdateParams) { ... },
          props: { data },
        },
        {
          onAfterUpdate({ layer }: OnAfterUpdateParams) { ... },
          props: { data },
        },
      ],
    });
  });
});
```

is still an issue, because it does not call `.finalizeState` in-between.

It seems like the extension is being recreated between tests without ever cleaning/finalizing the previous instance of the extension.

A hacky workaround at the moment is to do this in `onAfterUpdate`:
```
subLayers[0].props.extensions[0].finalizeState(subLayers[0].props.extensions[0]);
```

Perhaps this just means that it would be better to manage the texture outside of the extension (like the icon-manager). But, it seems like it should not be necessary to manually call `.finalizeState` on the extension between tests.

**Comment by Pessimistress** [comment]
The confusion here is that a layer extension is not designed to hold on to resources in its own instance. Extensions are only initialized/finalized with the layer's initialization and finalization, as in it "extends" the layer's own lifecycle methods. If you create new extension instances during each update, then the removed instance will simply be discarded. This is consistent with how Layer classes are implemented - a layer never stores resources in `this._texture`. Instead, persistent resources need to be stored in `this.state`, which is transferred from an old instance to a new instance during each layer update.

**Comment by jeffpeck10x** [comment]
@Pessimistress Thank you for explaining that. It makes sense, and explains why the IconLayer has a separate class to _manage_ the icons.
