### ISSUE TITLE
GeoJsonLayer on GlobeView wrong lighting

### ISSUE THREAD

**Issue by Baseform** [visgl/deck.gl#6423]
#### Description
When using GeoJsonLayer on GlobeView lighting effects are wrong. Normals seem not to be calculated for Polygons in GlobeView.

#### Expected Behavior
With the right normals, GeoJsonLayer/Polygon layers should normally, behave as SimpleMesh does.

#### Repro Steps
https://codepen.io/diogovit/full/OJjeeJG

#### Environment
Using the latest build of deckgl from unpkg.

<img width="483" alt="Screenshot 2021-11-25 at 10 40 49" src="https://user-images.githubusercontent.com/1381857/143426798-53bd37ba-3899-4acf-ae08-61fedce5e74a.png">

**Comment by Pessimistress** [comment]
The fix will be landed in v8.7.0 since it introduces visual breaking changes. You can try it now with `deck.gl@beta`.
