### ISSUE TITLE
[RFC] Supply attributes directly in binary GeoJsonLayer

### ISSUE THREAD

**Issue by Clebal** [visgl/deck.gl#6432]
#### Proposed feature
I want to be able to [supply attributes directly](https://deck.gl/docs/developer-guide/performance#supply-attributes-directly) to GPU as it's possible in others layers. Due to GeoJsonLayer nature, it isn't possible right now. But this is one of the most interesting features to avoid bottlenecks in deck.gl and I think it should be covered in such a relevant layer like GeoJsonLayer is.

#### Target Use case
Being able to supply attributes directly in the binary GeoJsonLayer would improve performance in advanced use cases. In my case, for example, I want to supply getFilterValue attribute to GeoJsonLayer, because its value comes from one of the TypedArray contained in the `numericProps` data.

#### How? - First proposal
My proposal is very simple:

The attribute would be pass seperately for each geometry type:

```
  return new GeoJsonLayer(props, {
    data: {
      pointsAttributes: {
        getFilterValue: { value: Uint16Array, size: 1 }
      },
      polygonsAttributes: {
        getFilterValue: { value: Uint16Array, size: 1 }
      },
      linesAttributes: {
        getFilterValue: { value: Uint16Array, size: 1 }
      },
      ...data
    }
  });
```

And in `createLayerPropsFromBinary` from [geojson-layer-props](https://github.com/visgl/deck.gl/blob/master/modules/layers/src/geojson-layer/geojson-layer-props.js#L41):

At line 43:
```
const {points, pointsAttributes = {}, lines, linesAttributes = {}, polygons, polygonsAttributes = {}} = geojsonBinary;
```

And I would spread these objects for each data:

![image](https://user-images.githubusercontent.com/9151432/143543205-c6ff76c3-2016-46b5-a913-ad942e97c956.png)

(Also polygonsOutline, but it didn't fit in the image)

#### How? - Second proposal

Same as first proposal but instead of summiting separately to binary data, I would create a property called `attributes` inside `data.points`, `data.lines` and `data.polygons`.

```
  return new GeoJsonLayer(props, {
    data: {
      points: {
        ...data.points,
        attributes: {
           getFilterValue: { value: Uint16Array, size: 1 }
        }
      },
      // others geometry types
    }
  });
```

#### To Do List
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update
  - [ ] Test

**Comment by felixpalmer** [comment]
Looks good to me, I prefer the second variant - it makes it clearer how the data will be processed. @Pessimistress do you have any thought on this?
