### ISSUE TITLE
TerrainLayer is limited to Web Mercator Projection

### ISSUE THREAD

**Issue by warflash** [visgl/deck.gl#6451]
#### Description
Currently TerrainLayer is limited to only supporting Web Mercator Projection as mentioned here: https://github.com/visgl/deck.gl/discussions/6431

#### Expected Behavior
Terrain Layer has usecases that don't involve geospatial projections, so adding support for those would be nice!

**Comment by Pessimistress** [comment]
Fixed in v8.6.5.
