### ISSUE TITLE
GeoJson layer line can not change width and color based on variable

### ISSUE THREAD

**Issue by qiaoxin136** [visgl/deck.gl#6485]
#### Description

 i try to change the width and color of line file. see codesandbox

https://codesandbox.io/s/empty-snow-ycmnz?file=/app.js:2092-2970

if i implement the following code, the line will disappear with error, is this a bug or i did something wrong. Thanks. 

      lineWidthMinPixels: (f) => (f.properties.DIAMETER > 15 ? 6 : 2),

      getLineColor: (f) => (f.properties.DIAMETER > 15 ? [207, 159, 255, 255] : [128, 154, 26, 255]),

#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]
 - Browser Version: [e.g. Chrome 78.0]
 - OS: [e.g. Mac OS X 10.15 / iOS 14.2]

**Comment by Pessimistress** [comment]
[lineWidthMinPixels](https://deck.gl/docs/api-reference/layers/geojson-layer#linewidthminpixels) is expected to be a number.

The bug template is used to report bugs in the library itself. Please use Discussions to get help debugging your own app.

**Comment by qiaoxin136** [comment]
thank you very much.
