### ISSUE TITLE
change "extruded" value cause webgl context crashing on microsoft edge Version 96.0.1054.43

### ISSUE THREAD

**Issue by r2dev** [visgl/deck.gl#6490]
#### Description

gl context crash

javascript

#### Expected Behavior

render the extruded change correctly across different platform
#### Repro Steps

the codepen  here --->https://codepen.io/r2dev/pen/OJxXbYY
after click "change" multiple times on edge browser, the webgl context will crash. It wont recover after refresh.

#### Environment
 - Framework Version: deck.gl 8.6.4
 - Browser Version: microsoft edge Version 96.0.1054.43
 - OS: windows 10

gpu: gtx 1070

#### Logs

 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

**Comment by Pessimistress** [comment]
I cannot reproduce this in Edge v96.0.1054.53.

**Comment by Pessimistress** [comment]
Reopen if able to reproduce.
