### ISSUE TITLE
Unable to preview the example on The First Person View

### ISSUE THREAD

**Issue by g-wozniak** [visgl/deck.gl#6502]
#### Description
The example of [The First Person View](https://deck.gl/docs/api-reference/core/first-person-view) does not render correctly.

#### Expected Behavior
I am able to see the FPV example working

#### Repro Steps
- Visit [The First Person View page](https://deck.gl/docs/api-reference/core/first-person-view)
- Visit [CodePen](https://codepen.io/vis-gl/pen/oNYXxNE)
- Try to view the example.

#### Environment
 - Framework Version: deck.gl website, latest
 - Browser Version: Chrome 96.0.4664.93
 - OS: Win 10

#### Logs
`unpkg.com/@loaders.gl/ply@3.1.0/dist/dist.min.js:1 Failed to load resource: the server responded with a status of 404 ()`
`dist.min.js:11 Error: loading data of PointCloudLayer({id: 'PointCloudLayer'}): null loader`

**Comment by Pessimistress** [comment]
@ibgreen Looks like loaders.gl's pre-built bundle are no longer named dist.min.js: https://unpkg.com/browse/@loaders.gl/ply@3.1.0/dist/

**Comment by ibgreen** [comment]
https://github.com/visgl/loaders.gl/issues/2008

**Comment by Pessimistress** [comment]
Thank you for reporting. This is now fixed by loaders.gl v3.1.2.
