### ISSUE TITLE
GoogleMapsOverlay iconAtlas error: texImage2D: no bound PIXEL_UNPACK_BUFFER

### ISSUE THREAD

**Issue by massimiliamanto74** [visgl/deck.gl#6515]
### Discussed in https://github.com/visgl/deck.gl/discussions/6510

<div type='discussions-op-text'>

<sup>Originally posted by **mantox74** December 15, 2021</sup>
Hallo everyone,
I'am new on deck.gl.
I'm trying to create a google map in Angular with about 380k of markers.
I use GoogleMapsOverlay and IconLayer (also the GeoJsonLayer has the same error) to add an iconAtlas to show 2 different markers.
This is an extract of my code:
```
import { GoogleMapsOverlay as DeckOverlay } from '@deck.gl/google-maps';
........
this.pointOverlay = new DeckOverlay();
this.renderLayer();
......
renderLayer() {
    this.pointOverlay.finalize();
    this.pointOverlay.setProps({
      layers: [
        new IconLayer({
          id: 'geojson_data',
          data: this.jsonData,
          getPosition: (d) => d.geometry.coordinates,
          getIcon: (d) => 'marker',
          iconAtlas: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/icon-atlas.png',
          iconMapping: {
            marker: {
              x: 128,
              y: 0,
              width: 128,
              height: 128,
            },
          },
          getSize: (d) => 5,
          sizeScale: 8,
          onClick: (info) =>
            info.object &&
            console.log('..'),
        }),
      ],
    });

    // show default layer
    this.pointOverlay.setMap(this.map);
  }
```

When I run my project and show the google map I have these console warning and black squares on map (no markers image):

1. **WebGL: INVALID_OPERATION: texImage2D: no bound PIXEL_UNPACK_BUFFER**
2. **[.WebGL-0x7fd54f950600]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips**

And then I have also this warning every time I move mouse on square.
**[.WebGL-0x7fd54f950600]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?**

<img width="592" alt="Schermata 2021-12-16 alle 14 55 36" src="https://user-images.githubusercontent.com/62379864/146512853-21521180-7d75-40cb-afcc-8e96101bd7ca.png">

Here is the code problem:

<img width="698" alt="Schermata 2021-12-16 alle 15 08 20" src="https://user-images.githubusercontent.com/62379864/146512895-95ddc324-ae38-4cbe-ae06-54728e7b5a17.png">

This is my map with the black squares instead imageAtlas

<img width="709" alt="Schermata 2021-12-17 alle 09 21 18" src="https://user-images.githubusercontent.com/62379864/146512824-c9c7d22c-78b9-4ee6-a62b-4b48270ca490.png">

I have searched on web what should be the problem but I can't find nothing. Also in documentation there is not any (or I can't find it).

Can any one suggest a solution?
</div>

**Comment by Pessimistress** [comment]
If you wish to report a bug, provide a CodeSandbox/repository that others can use to investigate the issue. If you are just looking for ideas, please use Discussions.

**Comment by mantox74** [comment]
Hi @Pessimistress,
you can find [sandbox project here](https://codesandbox.io/s/deck-gl-angular-7fm2k).
Thanks for help!

**Comment by Pessimistress** [comment]
As I suggested in the Discussion thread, your global `Promise` object is overwritten by a polyfill, so `<Promise> instanceof Promise` returns false:

![image](https://user-images.githubusercontent.com/2059298/146654797-69274a50-b3b9-42f0-a3c8-24af14714d8c.png)

I am not an Angular user so I do not know how you can configure your app to not do that. I know there are plenty of Angular apps using deck.gl so it's definitely possible.

**Comment by massimiliamanto74** [comment]
Hi @Pessimistress and thank you very much for your response and your debugging.
I am not very convinced that the problem is what you were suggesting because if I use the single icon instead iconAtlas I have the same result un the console but the icon is loaded as you can see in images below. 

<img width="586" alt="Schermata 2021-12-20 alle 09 25 18" src="https://user-images.githubusercontent.com/62379864/146736326-1863ef44-16f7-4a76-bbea-353686b551b8.png">

<img width="609" alt="Schermata 2021-12-20 alle 09 28 21" src="https://user-images.githubusercontent.com/62379864/146736339-010c83b5-72ad-45a0-8618-3f9d1e71a105.png">

If the problem is the override of Promise object it should be unload also the single icon, i'm wrong?

I try to investigate more but I don't know very well dock.gl, GooglemapsOverlay and Webgl in deep....

**Comment by Pessimistress** [comment]
Auto packing through `getIcon` does not use the same mechanism as asynchronous props.

You will also find your app broken if you provide an URL to `data`.

**Comment by massimiliamanto74** [comment]
Your are right, with URL my app broken.
Thanks for your help, I will try to find some suggestions about fix this issue in the web.

**Comment by jcready** [comment]
In what version of deck.gl was this bug fixed? The bug being that checking `instance of Promise` is not an acceptable way to determine if something is awaitable where the correct way would be to check if `'then' in value && typeof value.then === 'function'`.
