### ISSUE TITLE
2D tile layer does not wrap across the international date line

### ISSUE THREAD

**Issue by jessekrubin** [visgl/deck.gl#6520]
#### Description

2d tile layers do not wrap across the international dateline.

- deck.gl (react)
- React
- react-map-gl
- maplibre-gl

#### Expected Behavior

Tile layer would wrap longitude correctly

#### Repro Steps

Will put together a repro repo

#### Environment
 - Framework Version: deck.gl 8 latest
 - Browser Version: [e.g. Chrome 78.0]
 - OS: redhat/windows

**Comment by Pessimistress** [comment]
[repeat](https://deck.gl/docs/api-reference/core/map-view#repeat)
