### ISSUE TITLE
[Bug] CartoLayer - Highlighting does not work with point data

### ISSUE THREAD

**Issue by borja-munoz** [visgl/deck.gl#6526]
### Description

Highlighting in the CartoLayer does not work with point data when using a GeoJson data source.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Highlighting should work as it does with other types of geometries (lines, polygons) and data sources (vector tiles).

### Steps to Reproduce

https://codepen.io/borja-munoz/pen/GRMvdPG

### Environment

- Framework version: deck.gl@8.7.0-alpha.9 (seems it has not worked since v8.5)
- Browser: Chrome
- OS: macOS

**Comment by Pessimistress** [comment]
Fixed in v8.6.6
