### ISSUE TITLE
[Feature] CARTO - Maps API client

### ISSUE THREAD

**Issue by eamador** [visgl/deck.gl#6527]
### Target Use Case

`maps-v3-client` and `maps-client` are attaching a `client` parameter to the urls before sending any request, the problem is that the `client` value is hardcoded `deck-gl-carto`.

As this `client` value could be useful for metrics, ideally it could be set dynamically.

### Proposal

In order to allow the developers to specify the `client` value for the Maps API (v1, v2 & v3) we should add this as argument to the exported functions found at `modules/carto/src/api/maps-v3-client.js` & `modules/carto/src/api/maps-client.js`

**Comment by alasarr** [comment]
I think the best approach is to add a new prop to CartoLayer with the default value to the one which is hardcoded right now. As you point out your need to add a parameter to maps api client
