### ISSUE TITLE
[Bug] GlobeView MVT layers not showing 

### ISSUE THREAD

**Issue by Baseform** [visgl/deck.gl#6528]
### Description

MVT Layers don't show up; no error reported on console. 
alpha.3 and previous versions do not have the same problem.

### Expected Behavior

For MVT Layer data to show on Globe

### Steps to Reproduce

Two codepens:
a) with alpha.7 (not working):
https://codepen.io/diogovit/pen/rNGGWQz

b) with alpha.3 (working)
https://codepen.io/diogovit/pen/dyVVOBw

### Environment

- Framework version: deck.gl@8.7.0-alpha.7
- Browser: safari, chrome
- OS: mac

**Comment by Pessimistress** [comment]
@felixpalmer Looks like MVTParser returns `NaN` coordinates when using `coordinates: 'wgs84'`.

**Comment by felixpalmer** [comment]
@Pessimistress thanks for the report, will look into it this week

**Comment by felixpalmer** [comment]
Underlying issue fixed in https://github.com/visgl/loaders.gl/pull/2052
