### ISSUE TITLE
[Feat] adding an animation controller in Trips Layer

### ISSUE THREAD

**Issue by kkdd** [visgl/deck.gl#6533]
### Target Use Case

Users could control animation if available.

### Proposal

I propese adding an animation controller in the same way as in [kepler.gl's trip layer](https://docs.kepler.gl/docs/user-guides/c-types-of-layers/k-trip) as follows:
![image](https://user-images.githubusercontent.com/5372642/147401846-9c0d8f07-6816-40ba-acd3-e6b56b61611c.jpg)

**Comment by Pessimistress** [comment]
Layers are rendered in WebGL. deck.gl does not render any DOM UI components. You can use any of the UI libraries out there and hook up the value with the `currentTime` prop.
