### ISSUE TITLE
[Bug] TileLayer xyz swapping doesn't work with multiple occurances of {x}

### ISSUE THREAD

**Issue by grahambates-sp** [visgl/deck.gl#6546]
### Description

I have some drone map imagery.

https://www.mapsmadeeasy.com/maps/detail/a785dfc8ccb94e1a812b6cc82aa81ba0/

I have noticed what I believe to be a small bug in TileLayer - due to the fact that this tile provider seems to use {x} in the url twice:

https://s3-us-west-1.amazonaws.com/0-tiles.mapsmadeeasy.com/**{x}**/2f3052f01d42419da6e9819e9a5d004d/a785dfc8ccb94e1a812b6cc82aa81ba0/{z}/**{x}**/{y}.png

The deckgl tile request seems to not swap out the second {x}

![image](https://user-images.githubusercontent.com/45166327/147880269-b16a72a0-26ad-417a-b114-e574d381945f.png)

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Tile Imagary should load.

### Steps to Reproduce

Use any tile imagery that has a repeated {x} param

### Environment

OSX

**Comment by Pessimistress** [comment]
The replacement is handled here:

https://github.com/visgl/deck.gl/blob/e66228aff7983ea068dfdc3db4ce0c636b31669f/modules/geo-layers/src/tile-layer/utils.js#L67-L71

I'm happy to release a patch if you open a PR.

**Comment by Pessimistress** [comment]
Fixed in v8.6.6
