### ISSUE TITLE
[Feat] Vanishing point offset for `WebMercatorViewport`

### ISSUE THREAD

**Issue by JannikGM** [visgl/deck.gl#6548]
### Target Use Case

mapbox provides a similar feature which is shown in https://docs.mapbox.com/mapbox-gl-js/example/offset-vanishing-point-with-padding/
The feature is documented here: https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setpadding

deck.gl support for this feature will be necessary to overlay a deck over mapbox map which has padding enabled.

In my use case, we consider splitting the map into multiple smaller portions that is displayed on separate windows / displays / screens ([basically a display mosaic](https://www.nvidia.com/content/dam/en-zz/es_em/Solutions/design-visualization/social-media/proviz-social-banner-mosaic.jpg)).

---

The feature has been requested in deck.gl GitHub discussions and on Slack before:
- https://github.com/visgl/deck.gl/discussions/5359
- https://deckgl.slack.com/archives/C34AC5MSQ/p1633560683171800

Until this feature is implemented it can probably be worked around by rendering at higher resolution (including the padding area) and using CSS transforms and clipping to show a subregion of the canvas, thereby moving the vanishing point ([see this for inspiration](https://github.com/mapbox/mapbox-gl-compare/blob/77a28e7a3dd3cdc91eff5ac986cb20f2924571bc/index.js#L90-L109)).

Supplying a custom `projectionMatrix` to the `WebMercatorViewport`-constructor which includes these transformations did not work in my test; I assume the feature is broken?

### Proposal

There are different options how this feature could be controlled:

1. In mapbox, the vanishing point is calculated from 4 padding values (left/right, top/bottom). The vanishing point is constrained to be within the mapbox canvas.
2. There could also be direct control of the X,Y coordinate of the vanishing point within the viewport.
3. There could be an API where the user sets a virtual framebuffer-size / coordinate system, and then defines a window into that framebuffer.

I don't think there's any good argument for the constraint in the mapbox API (1), and it would be better if the vanishing point could also be outside of the map.
I consider removing the constraint of mapbox for maplibre.

The X,Y-API (2) is probably too limited as moving the vanishing point might also lead to unintended scaling of the map or scaling the map is impossible.

The window-API (3) is probably comparable to mapbox (as negative padding could potentially be used to define a "window" into the map canvas).

**Comment by Pessimistress** [comment]
@JannikGM I opened a preliminary PR that implements an X,Y offset. Could you elaborate how Mapbox's handling of padding affect scaling (zoom)?

**Comment by felixpalmer** [comment]
I think `padding` (as per Mapbox) would be a better API. I imagine the primary use case will be offset the vanishing point to present some UI. With `padding` it is simpler to maintain a responsive design. The padding could also be optionally expressed as percentages. Achieving this using `offset` requires the user to perform the calculations using `width`and `height` themselves and could lead to glitches when resizing the window if they are not in sync with the deck.gl animation loop.

**Comment by yukiasakura60** [comment]
I was looking at the release version of deck.gl but couldn't figure out if this is already available for use. If it is not release yet, when will it be published?

**Comment by vincentmvdm** [comment]
Thanks for the feature @JannikGM @Pessimistress!

+1 to Yuki's question on when this will be available. Would love to use this for upcoming UXR!

**Comment by Pessimistress** [comment]
This feature is going to be part of v8.8. We will publish an alpha release soon.

**Comment by Pessimistress** [comment]
This is available in 8.8.0-alpha.
