### ISSUE TITLE
Browser reload on iPad

### ISSUE THREAD

**Issue by Radik24** [visgl/deck.gl#6551]
### Description

Hello i'm experiencing som issue on mobile devices. Map is created correctly, I can see all the data, but after few interactions (zoom, move,..) application crashes and reloads browser.

When using only openstreet TileLayer I get:
![image](https://user-images.githubusercontent.com/23722745/148746153-67bb1149-ba2c-48d2-9b1c-c9fc721d3ce6.png)

With Tile3DLayer and some i3S data:

![image](https://user-images.githubusercontent.com/23722745/148746564-e187d861-651c-413a-9665-b5a85a9c5c48.png)

On desktop browsers everything is ok. 

Have you ever met with this behavior? What should be wrong? I was wondering IPad Pro does not have enough RAM or something.

Thanks

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Do not reload browser if some error occurs.

### Steps to Reproduce

Open working app in mobile browser

### Environment

- Framework version: deck.gl 8.7.0-alpha.11 (older versions are not working too|, loaders.gl 4.0.0-alpha.5
- Browser: Chrome, Safari
- OS: IOS

**Comment by Pessimistress** [comment]
Is there a reason you are using loaders.gl 4.0 alpha? The current deck.gl depends on loaders 3.1.

**Comment by Pessimistress** [comment]
Do you see the same issue with https://deck.gl/examples/tile-layer/ on your device? If so please provide the version of Safari/iOS.

**Comment by Radik24** [comment]
Hi, I found out where is the problem. I was generating url query from deck.gl viewState. Lots of viewState changes was flooding browser. I optimised it and now it seems to be working properly.

I'll close this issue.

Thanks
