### ISSUE TITLE
[Bug] Interactivity not working in the MapboxLayer example

### ISSUE THREAD

**Issue by HighRune** [visgl/deck.gl#6556]
### Description

Event handler functions are not working in [this example](https://deck.gl/docs/api-reference/mapbox/mapbox-layer#use-a-layer-from-an-existing-decks-layer-stack) from the deck.gl documentation.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

'onHover' and 'onClick' functions should be working

### Steps to Reproduce

https://codesandbox.io/s/mapboxlayer-interactivity-59u2j?file=/src/index.js

### Environment

- Framework version: deck.gl@8.6.5
- Browser: Chrome 96.0.4664.93 (Official Build) (64-bit)
- OS: Linux

**Comment by Pessimistress** [comment]
Fixed in v8.6.9.

**Comment by HighRune** [comment]
Thanks a lot !
