### ISSUE TITLE
[Bug] Props, layerName and default props are not recognized/found, when extending composite layer.

### ISSUE THREAD

**Issue by neelduttahere** [visgl/deck.gl#6567]
### Description

Props, layerName and default props are not recognized, when extending a composite layer.

Its showing as error, with the message `Property 'props' does not exist on type 'WrappedTextLayer'.ts(2339)`.
Same goes for .layerName and .defaultProps, with their error messages respectively:
1. `Property 'layerName' does not exist on type 'typeof WrappedTextLayer'.ts(2339)`
2. `Property 'defaultProps' does not exist on type 'typeof WrappedTextLayer'.ts(2339)`

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

It should work as it is.

### Steps to Reproduce

Try my code 
```js
import {CompositeLayer, TextLayer} from "@deck.gl/layers";

class WrappedTextLayer extends CompositeLayer {
    renderLayers() { // a method of `Layer` classes
        // special logic here
        return [new TextLayer(this.props)];
    }
}
WrappedTextLayer.layerName = 'WrappedTextLayer';
WrappedTextLayer.defaultProps = {
    getText: (): string => 'x',
    getSize: (): number => 32,
    getColor: [255, 255, 255]
};

export { WrappedTextLayer };
```

### Environment

- Framework version: 8.6.5
- Browser: Chrome
- OS: Windows 10

**Comment by Pessimistress** [comment]
These are TypeScript errors. The current deck.gl release does not contain any typing. If you are using a third-party type declaration you need to report it to that library.

**Comment by ibgreen** [comment]
Maybe try moving the static elements into the class?

```typescript
class WrappedTextLayer extends CompositeLayer {
    static layerName = 'WrappedTextLayer';
    static defaultProps = {
        getText: (): string => 'x',
        getSize: (): number => 32,
        getColor: [255, 255, 255]
    };

    renderLayers() { // a method of `Layer` classes
        // special logic here
        return [new TextLayer(this.props)];
    }
}
```

**Comment by neelduttahere** [comment]
@ibgreen Yes I tried it as that's the more logical way out, but somehow "props" is not a recognized type under Composite layer. 

I will look into what @Pessimistress suggested.
