### ISSUE TITLE
[Bug] Mapbox integration, layer get repeated even with renderWorldCopies set to false

### ISSUE THREAD

**Issue by inwebitrust** [visgl/deck.gl#6584]
### Description

I followed the example to use a DeckGL custom layer in Mapox.

It works well but the Custom Layer gets repeated even if I set the renderWorldCopies to false in Mapbox.

Is there any way we can prevent this behaviour 
![Screen Shot 2022-01-25 at 4 41 17 PM](https://user-images.githubusercontent.com/9989202/151064750-d0b39c70-7adc-4ca8-9071-0d554b0723e7.png)

![Screen Shot 2022-01-25 at 4 41 27 PM](https://user-images.githubusercontent.com/9989202/151064722-df3cb57f-997b-466d-9037-da7e2e28c5bd.png)
?

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

var map = new mapboxgl.Map({
            container: 'ParcoursMap',
            center: [-20.276018, 50.220830],
            zoom: 1.6,
            pitch: 25,
            //maxPitch: 50,
            bearing: 0,
            minZoom: 1,
            maxZoom: 15,
            renderWorldCopies: false,
        });

### Environment

- Framework version: deck.gl@8.3.0
- Browser: All
- OS: All

**Comment by Pessimistress** [comment]
Fixed in v8.6.7
