### ISSUE TITLE
[Bug] Picking a point on 3D object

### ISSUE THREAD

**Issue by arianos11** [visgl/deck.gl#6587]
### Description

I'm trying to add point to objects after click on specific place. 

Object is loading from obj file (loaders.gl) and used in SimpleMeshLayer.

After click, coordinates generated by the engine are incorrect. The point appears behind the object.

![deck_problem](https://user-images.githubusercontent.com/42947202/151182828-014c1884-cd9b-4e34-8b74-ce84e16b2ad4.png)

Red circle is located where I clicked.

![image](https://user-images.githubusercontent.com/42947202/151183673-555f0c56-4141-4520-9bb6-f81acf0a0d18.png)

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Point should appears in place where I clicked

### Steps to Reproduce

> Layers

```
setLayers([
          new SimpleMeshLayer({
            id: 'mesh-layer',
            data: [0],
            mesh: data,
            pickable: true,
            _useMeshColors: true,
            getPosition: d => d.position,
            pointSize: 1,
            getColor: data ? [212, 212, 212] : [255,255,255],
            onClick: (i, e) => !adding && addPin(i, e),
          }),
          new SimpleMeshLayer({
            coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
            id: "simple_mesh_layer",
            data: pins,
            pickable: true,
            getColor: d => d.color,
            getScale: d => d.scale,
            getPosition: d => d.position,
            getOrientation: d => d.angle,
            getTranslation: d => d.position,
            onHover: info => setHoverInfo(info),
  
            mesh: new CubeGeometry(),
          })
        ]);
```

> Change position on first point

```
function addPin(info, event) {

        console.log(info);
        console.log(event);

        const info2 = info.layer.context.deck.pickObject({
          x: info.x,
          y: info.y,
          radius: 0,
          layerIds: [ info.layer.id ],
          unproject3D: true
        })

        let temp = pins;
        console.log(info.coordinate);
        temp[0].position[0] = info2.coordinate[0];
        temp[0].position[1] = info2.coordinate[1];
        temp[0].position[2] = info2.coordinate[2];
        setPins(temp);
        setAdding(!adding);
      }
```

> DeckGL component

`<DeckGL
            views={new OrbitView({
              orbitAxis: 'Y',
            })}
            viewState={viewState}
            onViewStateChange={e => setViewState(e.viewState)}
            controller={adding}
            layers={layers}
          />`

### Environment

- Framework version: deck.gl@8.6.5
- Browser: All
- OS: All

**Comment by Pessimistress** [comment]
The default picking does not return 3D information. You need to call  `deck.pickObject` with [unproject3D](https://deck.gl/docs/api-reference/core/deck#pickobject) in the `onClick` callback.

**Comment by arianos11** [comment]
Hi, but I have already used unproject3D in function addPin()
```
const info2 = info.layer.context.deck.pickObject({
          x: info.x,
          y: info.y,
          radius: 0,
          layerIds: [ info.layer.id ],
          unproject3D: true
        })
```

and I call it in the layer

```
 onClick: (i, e) => !adding && addPin(i, e)
```

I have a 3d coordinates but they are incorrect

**Comment by Pessimistress** [comment]
You are doubling the position here:

```js
getPosition: d => d.position,
getTranslation: d => d.position,
```

Also, mutating `pins` does not update the layer. You need to create a new object.

If you need help debugging, please create a functional Codepen/Code sandbox and open a thread in Discussions.

**Comment by Pessimistress** [comment]
Repro: https://codesandbox.io/s/viewer3d-with-points-htq9w

**Comment by Pessimistress** [comment]
Try v8.6.7.
