### ISSUE TITLE
[Bug] TileLayer Utils: Matrix4.transformPoint Deprecated Warning

### ISSUE THREAD

**Issue by mcost45** [visgl/deck.gl#6607]
### Description

This warning has appeared in the console when using the latest Deck version (8.6.7):

'Matrix4.transformPoint has been removed in version 3.0, see upgrade guide for more information: validators.js:33'

Looks like it is related to this: https://math.gl/docs/upgrade-guide

![image](https://user-images.githubusercontent.com/17732915/151768230-7e1dd55c-f44d-4567-a05a-88c77252fe85.png)

https://github.com/visgl/deck.gl/blob/44586e28548c91ea0cebc2a23d316fff3bb1f389/modules/geo-layers/src/tile-layer/utils.js#L34-L42

Potentially related to new Matrix4 additions in #6602?

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

- Using tileLayer with latest Deck version

### Environment

- Framework version: 8.6.7

### Logs

![image](https://user-images.githubusercontent.com/17732915/151769347-d2a17579-5df8-47d3-bb00-432bd1786b0b.png)

**Comment by Pessimistress** [comment]
Fixed in v8.6.9.
