### ISSUE TITLE
[Bug] IconLayer LoadOptions don't work with GeoJsonLayer

### ISSUE THREAD

**Issue by arthurgailes** [visgl/deck.gl#6616]
### Description

Hello,

I don't believe loadOptions are working inside the GeoJsonLayer, see codepen here: https://codepen.io/arthurgailes/pen/oNoLRGQ?editors=001

The y-axis isn't flipping, as it does in this example:  https://codepen.io/arthurgailes/pen/Exbyzzd?editors=001

Code: 
```

const layer = new GeoJsonLayer({
  id: 'GeoJsonLayer',
  data: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/bart.geo.json',
  
  /* props from GeoJsonLayer class */
  pointType: 'icon+text',
  binary: false,
  getIcon: d => ({
      url: "https://avatars1.githubusercontent.com/u/7025232?v=4",
      width: 128,
      height: 128,
      anchorY: 128
    }),
    getIconSize: 50,
    sizeScale: 15,
    loadOptions: {
      image: { type: 'imagebitmap' },
      imagebitmap: {
        // Flip the image vertically
        imageOrientation: 'flipY',
      },
    },
  // also tried for good measure
  _subLayerProps: {
            points: {
              loadOptions: {
                image: { type: 'imagebitmap' },
                imagebitmap: {
                  // Flip the image vertically
                  imageOrientation: 'flipY',
                },
              },
            },
          },
});

```

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

https://codepen.io/arthurgailes/pen/oNoLRGQ?editors=001

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
`getIcon` does not take `loadOptions`, see https://deck.gl/docs/api-reference/layers/icon-layer#geticon

`point` is not a valid sub layer, see https://deck.gl/docs/api-reference/layers/geojson-layer#sub-layers

**Comment by arthurgailes** [comment]
> `point` is not a valid sub layer, see https://deck.gl/docs/api-reference/layers/geojson-layer#sub-layers

Please note that I've edited it and the bug stands as is.

**Comment by arthurgailes** [comment]
Oh, I see, it should be "points-icon". This example suggests otherwise, should it be updated? https://deck.gl/docs/api-reference/core/composite-layer#_sublayerprops
