### ISSUE TITLE
[Bug] Map Polygons not rendering in Safari 15

### ISSUE THREAD

**Issue by spkompella** [visgl/deck.gl#6617]
### Description

I am having very similar issues to issue #6414 but using maps generated with Pydeck.
Currently using Pydeck 0.7.1 (latest) but still seeing the issues on iOS devices. 
Maps are working smoothly on older versions of Safari and I haven't been able to try and new Dev Previews for Safari.

### Flavors

- [ ] React
- [X] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

Visit my test app at  http://testapp2-env.eba-ms3mqwrb.us-west-2.elasticbeanstalk.com/ on a iOS device running 15+.
See images for expected results vs observe
![Image from iOS (7)](https://user-images.githubusercontent.com/85196767/152432049-35f7bc5e-e43c-4f2f-9294-18b0cc8ca678.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/85196767/152432058-74c8a2a8-d199-4075-8074-27ba1a0da9c6.png)

### Environment

- Framework version: Pydeck 0.7.1
- Browser: Safari 15
- OS: iOS 15.0.2

**Comment by Pessimistress** [comment]
@ajduberstein What version of deck.gl is pydeck on?

**Comment by kylebarron** [comment]
Looks like pydeck 0.7.1 sets 
```py
DECKGL_SEMVER = "~8.5.*"
```

**Comment by Pessimistress** [comment]
@spkompella Your app shows that it's using deck.gl v8.2.5 (type `deck.version` in the console). I doubt it is generated with the latest pydeck. Safari 15 compatibility was fixed in v8.5.

**Comment by spkompella** [comment]
Closing issue as this error was caused by a different package with Deck.GL dependency.
