### ISSUE TITLE
[Bug]PathLayer do not draw lines when two points have the same lngLat but different altitudes

### ISSUE THREAD

**Issue by linze99** [visgl/deck.gl#6643]
### Description

I am using PathLayer to render 3d lines.
when rendering a line between two adjacent nodes which have the same lngLat but different altitudes,
the line do not displayed.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

render a vertical line between the two points

### Steps to Reproduce

const {DeckGL, PathLayer} = deck;

const layer = new PathLayer({
  id: 'PathLayer',
  data: [{
    color: "#00ff00",
    path: [[-122.407985,37.700029,0],[-122.407368,37.700196,0],[-122.406504,37.6983689,0],[-122.406504,37.6983689,20],[-122.4065042,37.69836892,20],[-122.4059580250479,37.69721086434434,0]]
  }],
  
  /* props from PathLayer class */
  
  // billboard: false,
  // capRounded: false,
  getColor: d => {
    const hex = d.color;
    // convert to RGB
    return hex.match(/[0-9a-f]{2}/g).map(x => parseInt(x, 16));
  },
  getPath: d => d.path,
  getWidth: d => 1,
  // jointRounded: false,
  // miterLimit: 4,
  // widthMaxPixels: Number.MAX_SAFE_INTEGER,
  widthMinPixels: 2,
  widthScale: 1,
  // widthUnits: 'meters',
  
  /* props inherited from Layer class */
  
  // autoHighlight: false,
  // coordinateOrigin: [0, 0, 0],
  // coordinateSystem: COORDINATE_SYSTEM.LNGLAT,
  // highlightColor: [0, 0, 128, 128],
  // modelMatrix: null,
  // opacity: 1,
  parameters: {
    depthMask: false
  },
  pickable: true,
  // visible: true,
  // wrapLongitude: false,
});

new DeckGL({
  mapStyle: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
  initialViewState: {
    longitude: -122.407985,
    latitude: 37.700029,
    zoom: 15,
    maxZoom: 20,
    pitch: 30,
    bearing: 0
  },
  controller: true,
  getTooltip: ({object}) => object && object.name,
  layers: [layer]
});
  

### Environment

- Framework version:
- Browser:
- OS:

**Comment by felixpalmer** [comment]
Use `billboard: true`. As per [the docs](https://deck.gl/docs/api-reference/layers/path-layer#billboard), if `billboard: false` the flat side of the line will face up, which isn't possible for vertical lines. 

Also I would recommend you preprocess your line data to simplify the line. In your example points 4 & 5 are virtually identical and result in rendering artifacts. If point 5 is removed the line is drawn cleanly:

<img width="608" alt="Screenshot 2022-02-17 at 11 06 34" src="https://user-images.githubusercontent.com/453755/154453216-fdc1e69c-29ff-4f4d-a1ac-67724c0f63b5.png">

**Comment by felixpalmer** [comment]
https://deck.gl/docs/api-reference/layers/geojson-layer#linebillboard
