### ISSUE TITLE
[Bug] Broken geometry when switching tabs in Chrome

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6649]
### Description

The rendering output of deck.gl breaks when switching tabs in Chrome (more details below). Typical results:
<img width="628" alt="Screenshot 2022-02-15 at 11 30 51" src="https://user-images.githubusercontent.com/453755/154043936-10918398-810a-40c7-8cb1-89e90e507f99.png">
<img width="1220" alt="Screenshot 2022-02-15 at 11 31 25" src="https://user-images.githubusercontent.com/453755/154043952-fd52ca6e-a959-4267-9db1-3f1699362e8a.png">

The issue occurs with larger geometry. In particular, notice how above some of the US states are rendered fine. By selectively rendering some states it becomes apparent that the issue occurs when the `instanceCount` of the tessellated geometry exceeds 65536.

While this issue seems obscure it occurs frequently when a user has multiple maps open in different tabs

### Expected Behavior

Rendering is correct

### Steps to Reproduce

See https://jsfiddle.net/felixp/azwg9kpo/. Here two circles are drawn, one with 65536 segments (red) and the other with 65535 segments (green). To trigger the issue:

- Open https://jsfiddle.net/felixp/azwg9kpo/ in a new tab (Tab A)
- Open https://deck.gl/docs/api-reference/geo-layers/mvt-layer in another tab (Tab B)
- Return to jsfiddle (Tab A) and drag deck.gl canvas to trigger render
- Red circle will disappear
- Open the jsfiddle again in a fresh tab (Tab C)
- Return to original jsfiddle (Tab A) and drag deck.gl canvas to trigger render
- Red circle will re-appear

I have examined the draw calls issued by deck.gl (using `luma.log.level=3`) and it appears that the same rendering commands are issued. It appears to be the case that somehow the WebGL state in Tab B corrupts the state in Tab A, and then Tab C fixes it.

Note that the bug is not triggered if for an arbitrary Tab B. For example, opening https://deck.gl/docs/api-reference/layers/point-cloud-layer in Tab B doesn't trigger the issue.

My best theory is that this is down to an issue in Chrome as I don't see how else to explain it. If this was somehow related to garbage collection in Tab A caused by memory pressure in Tab B then I don't understand how the correct state is then re-instated in Tab A by Tab C.

### Environment

- Framework version: deck@8.7.0-beta.5
- Browser: Chrome Version 96.0.4664.110 (Official Build) (arm64)
- OS: OSX 12.0.1 (21A559)

**Comment by felixpalmer** [comment]
@Pessimistress @ibgreen would be great to get your input here as this feels like a very low level issue and I'm pretty much out of ideas for a fix

**Comment by ibgreen** [comment]
Yes, looks like I can actually repro this on my machine (2021 Macbook Pro). For this type of issue it can make sense to test multiple machines to see if it could be specific to some driver. Looks like you are also using an arm-based Mac?

@kenrussell - Are you aware of any known issues when number of instances >= 65536?

**Comment by felixpalmer** [comment]
I have a 2021 16inch MBP with a Apple M1 Pro chip

**Comment by Pessimistress** [comment]
I can reproduce this on a Mac Mini 2018 (OSX 12).

Firefox for Mac works as expected.
Chrome on a Windows machine works as expected.

**Comment by mcost45** [comment]
Could this be related to a Uint16Array somehow? [They only have a value range of 0-65535](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray). Setting a value to greater than 65535 wouldn't cause an error, it would just be set to 0. Not sure how this relates to the cross-browser inconsistencies though.

**Comment by felixpalmer** [comment]
We tried to reproduce this again today and the bug is gone. My Chrome has since updated to 98.0.4758.109 and using a online testing service we can confirm that it is still present in Chrome 96. So far we have been unable to find another repro scenario so I am closing this.
