### ISSUE TITLE
[Bug] Unable to resolve correctly dependency tree for @deck.gl/carto@8.7.0-beta.5

### ISSUE THREAD

**Issue by VictorVelarde** [visgl/deck.gl#6654]
### Description

I have a project, requiring “@deck.gl/carto": "^8.7.0-beta.5" as a dependency, but getting ‘@deck.gl/core@8.6.8’ and thus failing.

Top lines from the npm console issue look like

```jsx
Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-sample-app-3@0.1.0
npm ERR! Found: @deck.gl/core@8.6.8
npm ERR! node_modules/@deck.gl/core
npm ERR!   peer @deck.gl/core@"^8.0.0" from @deck.gl/carto@8.7.0-beta.5
npm ERR!   node_modules/@deck.gl/carto
npm ERR!     @deck.gl/carto@"^8.7.0-beta.5" from the root project
npm ERR!     peer @deck.gl/carto@"^8.7.0-beta.5" from @carto/react-api@1.2.1-beta.6
npm ERR!     node_modules/@carto/react-api
npm ERR!       @carto/react-api@"^1.2.1-beta.6" from the root project
npm ERR!     2 more (@carto/react-core, @carto/react-redux)
npm ERR!   peer @deck.gl/core@"^8.0.0" from @deck.gl/geo-layers@8.6.8
npm ERR!   node_modules/@deck.gl/geo-layers
npm ERR!     peer @deck.gl/geo-layers@"^8.0.0" from @deck.gl/carto@8.7.0-beta.5
npm ERR!     node_modules/@deck.gl/carto
npm ERR!       @deck.gl/carto@"^8.7.0-beta.5" from the root project
npm ERR!       3 more (@carto/react-api, @carto/react-core, @carto/react-redux)
npm ERR!   3 more (@deck.gl/extensions, @deck.gl/layers, @deck.gl/mesh-layers)
```

I’m also using here several @carto/react-* packages, that require as peerDep same  "^8.7.0-beta.5"

For npm ≥ 8.3 I can fix it with ‘overrides’ (and ‘resolutions’ for yarn) in my package.json, but I can’t for previous ones (eg npm 8.1.2).

Original dep that looks like the root cause is [https://github.com/visgl/deck.gl/blob/ab96366b709056b020902fa431d7dce5b85a6294/modules/carto/package.json#L48](https://github.com/visgl/[deck.gl](http://deck.gl/)/blob/ab96366b709056b020902fa431d7dce5b85a6294/modules/carto/package.json#L48). All peerDependencies there with other deck.gl packages are specified as **^8.0.0**. 

I’ve checked other deck.gl modules, and it looks like ^8.0.0 is the preferred way in all of them for peers.
 
My question here is, does it make sense to use ^8.7.0? Could that change be applied just to one module @deck.gl/carto?

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

All peer deps are resolved correctly to corresponding ^8.7.0-beta.*, ideally without `resolutions` and for any npm version

### Steps to Reproduce

I have no small & reproducible project, but it manifests when using our create react app template project (using npm / node versions specified down):

```
npx create-react-app test-sample-app-3 --template  @carto/cra-template-sample-app-3@prerelease
```

### Environment

- Framework version: ^8.7.0-beta.5
- npm: 8.1.2
- node: 16.13.2

### Logs

I can paste # npm resolution error report later if required (>2000 lines)

**Comment by felixpalmer** [comment]
I wonder if this is due to the fact `loaders.gl/core` is listed as a peer dependency rather than a dependency: https://github.com/visgl/deck.gl/blob/f2cfa1438c32a5ef0bab027623bd9c77267eebea/modules/carto/package.json#L47-L52

Any idea why this is @alasarr ? It looks strange to me.

As for bumping up ^8.0.0 to ^8.7.0 this isn't great as it would force all users of the carto module to use the latest deck - I don't think we can do this.

**Comment by Pessimistress** [comment]
Technically the peer dependencies of an alpha/beta release should be `^8.0.0-alpha` instead of `^8.0.0`. We don't always make this change because betas are mostly for internal testing.

**Comment by felixpalmer** [comment]
We can live with this as it only affects alpha/beta releases
