### ISSUE TITLE
[Bug] Non-Square Deep Zoom Images Have Weird Behavior

### ISSUE THREAD

**Issue by kyleawayan** [visgl/deck.gl#6698]
### Description

I'm using example code from https://github.com/visgl/deck.gl/tree/8.6-release/examples/website/image-tile to create a zoomable Deep Zoom Image for non-geospatial purposes. However, I get weird behavior with the DZIs I'm using.

I'm dealing with DZIs with non-square aspect ratios (e.g. one image size is 39414x37671). The tiles that are towards the right and bottom edge of the image stretch to "form" a square. For example, one of the tiles towards the edge of the Deep Zoom image has a resolution of 77x512, but either the `BitmapLayer` or `TileLayer` stretches the image to fit a 512x512 square.

My problem is similar to the [moon example](https://deck.gl/examples/tile-layer-non-geospatial/) below, but imagine that the tile I'm hovering over—shown in the transparent grey rectangle—was stretched horizontally into a square aspect ratio.

<img width="610" alt="Screen Shot 2022-02-24 at 10 35 03 PM" src="https://user-images.githubusercontent.com/56655579/155666573-7cb04616-4847-4a04-92e0-2d294c60bf3d.png">\

I tried changing `gl.TEXTURE_WRAP_S` and `gl.TEXTURE_WRAP_T` to different values but the issue still persists.

We are using libvips with the `--overlap 0 --tile-size 512 --compression 2` arguments to generate DZIs.

I also get tons of errors about image files not being found probably due to tiles actually not existing at the location. I'm not sure if this relates to the stretching issue.

Do `BitmapLayer` and `TileLayer` play nice with non-square aspect ratio images? The [moon image](https://deck.gl/examples/tile-layer-non-geospatial/) is in a square aspect ratio and works perfectly.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Tiles that are not stretched like the [moon example](https://deck.gl/examples/tile-layer-non-geospatial/)

### Steps to Reproduce

1. Create a DZI with libvips with the arguments `--overlap 0 --tile-size 512 --compression 2`
2. Use the example code from the [moon example](https://github.com/visgl/deck.gl/tree/8.6-release/examples/website/image-tile)
3. Start a local file server with the DZIs and replace the URLs in the example code
4. Start the example, then see the stretched images on the right and bottom edges

### Environment

- Framework version: deck.gl@8.6.8
- Browser: Chrome 98.0.4758.109
- OS: macOS 12.2.1 (21D62)
- libvips: vips-8.12.2-Tue Jan 25 09:34:32 UTC 2022

**Comment by Pessimistress** [comment]
BitmapLayer stretches the image to fit the rectangle defined by its `bounds` prop, so you should check if you are passing the correct values here: https://github.com/visgl/deck.gl/blob/master/examples/website/image-tile/app.js#L75

Requests can be limited by [extent](https://deck.gl/docs/api-reference/geo-layers/tile-layer#extent).

You are clearly asking a question, not reporting a bug in the library. Please use Discussion for this purpose.
