### ISSUE TITLE
Trip Layer does not show the path when only z (height) coordinate is changing and x and y stays the same[Bug]

### ISSUE THREAD

**Issue by MariDani** [visgl/deck.gl#6782]
### Description

I am using TripLayer for animating my path data that actually represents trajectories of land depression in time, which means than the x and y coordinates are staying the same and only the height (z coordinate) is changing in time. When I want to visualize data like this, the paths are not rendered at all. However when I modify the input dataa by adding small constatnt to x and y coordinates in each time frame, everything works like expected and the paths are visible.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Is there any chance that you could update the shaders so the layer works correctly even for data where only height coordinate is changing?

### Steps to Reproduce

This is Codepen reproducing the issue https://codepen.io/maridani-the-animator/pen/ExomQRo. 

Three paths should be visualized, but only two are visible:

- green "trips-layer-2D" which represents 2D path only to prove that the prototype is working
- violet "trips-layer-3D" that represents 3D path where only z coordinate is changing (no visual result)
- pink "trips-layer-3D-modified" that is generated from same dataset as the 3D but small constatnt is added to x and y coordinates in each frame.

### Environment

- Framework version: deck.gl@8.7.3
- Browser: Chrome 99.0.4844.84
- OS: Windows 10 Pro 19044.1348

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/issues/6643
