### ISSUE TITLE
[Bug] Square-like rendering of points with layer blending > substractive

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6784]
### Description

`ScatterplotLayer` points have their edges clipped. The problem is most obvious when subtractive blending is used on the layer.
<img width="336" alt="Screenshot 2022-03-23 at 12 01 10" src="https://user-images.githubusercontent.com/453755/160609125-973f245f-402f-47b9-9eec-e5180c08d5dd.png">

The root cause is that the edge smoothing in the fragment shader widens the area into which the antialiased circle is drawn:

https://github.com/visgl/deck.gl/blob/9d6d63e0635dc02ae8953cffe23afdd67e79a77b/modules/layers/src/scatterplot-layer/scatterplot-layer-fragment.glsl.js#L40-L42

while the vertex shader does not.

By increasing `SMOOTH_EDGE_RADIUS` to 10.0 we can see the issue more clearly.

https://github.com/visgl/deck.gl/blob/9d6d63e0635dc02ae8953cffe23afdd67e79a77b/modules/core/src/shaderlib/misc/geometry.js#L40 

<img width="842" alt="Screenshot 2022-03-29 at 14 12 37" src="https://user-images.githubusercontent.com/453755/160609979-d3fe02c8-22bc-4357-9fcd-473af98e9388.png">

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Edges are not clipped.

### Steps to Reproduce

Increase `SMOOTH_EDGE_RADIUS` to 10.0 and load any `ScatterplotLayer`.

### Environment

- Framework version: deck.gl@8.7.3
- Browser: all
- OS: all

**Comment by Pessimistress** [comment]
Fixed in v8.7.4
