### ISSUE TITLE
[Bug] BitmapLayer with COORDINATE_SYSTEM.LNGLAT doesn't support zoom >= 12

### ISSUE THREAD

**Issue by zakjan** [visgl/deck.gl#6798]
### Description

BitmapLayer with COORDINATE_SYSTEM.LNGLAT doesn't support zoom >= 12. The image colors change to something in greyscale that doesn't seem to correspond to the image colors. The actual gray varies depending on the zoomed area.

Zoom 11.99:

<img width="1109" alt="Screenshot 2022-04-04 at 8 53 28" src="https://user-images.githubusercontent.com/173585/161489295-ed467a07-4fbd-49ea-9b86-db01fc895f04.png">

Zoom 12:

<img width="1109" alt="Screenshot 2022-04-04 at 8 53 52" src="https://user-images.githubusercontent.com/173585/161489318-da86f4aa-3984-4509-940f-82cf3ec90b4e.png">

Note that this is not caused by overzooming the image. Codepen uses an image with global bounds `[-180, -90, 180, 90]`, but the same behaviour in zoom >= 12 stays with small bounds e.g. `[-0.5, -0.25, 0.5, 0.25]`.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

BitmapLayer with COORDINATE_SYSTEM.LNGLAT renders well in zoom >= 12

### Steps to Reproduce

- open https://codepen.io/zakjan/pen/MWrrepW
- zoom >= 12

### Environment

- Framework version: deck.gl@8.7.0

Tested on multiple devices:

- Browser: Chrome 99
- OS: Mac M1

- Browser: Safari
- OS: iOS 15.4

- Browser: Chrome
- OS: Android

### Logs

none

**Comment by Pessimistress** [comment]
Fixed in v8.7.4
