### ISSUE TITLE
[Bug] Massive performance drop on Macbook with dedicated GPU

### ISSUE THREAD

**Issue by gkbar** [visgl/deck.gl#6807]
### Description

deck.gl content viewed on Chrome or Safari on Macbook Pro with dedicated graphics slows down to sub-1 fps rates. This seems to be dependent on scene complexity. Map-only view looks responsive, but performance tanks once point cloud is enabled.

This only appears when using Chrome (and seems to happen similarly on Safari) while forcing Macbook to use the dedicated Radeon gpu. This bug does not appear on Firefox, Chrome launched on the integrated Intel card, and on Chrome with passed `--disable-gpu-driver-bug-workarounds` flag.

Bug appears in my React application while displaying a point cloud, but it is also simple to replicate by visiting any geometry-intensive deck demo.
I can verify it hapens across multiple similar machines (Macbooks with 560 and 560X cards)

I am unable to replicate the issue with other WebGL, non-deck demos. 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

I should be able to open https://deck.gl/examples/point-cloud-layer/ and smoothly rotate the view. The banner on https://deck.gl/ should animate smoothly.

### Steps to Reproduce

- On MacBook with dedicated Radeon system, open `System Preferences > Battery` and disable `Automatic Graphics Switching` in both Battery and Power adapter menu.
- Start new Chrome instance.
- Navigate to https://deck.gl/examples/point-cloud-layer/
- Attempt to move the point cloud
- The cloud animation is choppy (inconsistent ~1fps)

### Environment

- Framework version: 8.6.5
- Browser: Chrome 100.0.4896.75
- OS: macOS Monterey 12.3 
- Macbook Pro 2017 with Radeon Pro 560

### Logs

None

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/discussions/6627

This is a known regression of Chrome itself on MacBook+Radeon 500 series GPU due to some unknown performance bug in Apple's OpenGL drivers. The recommendation from the Chrome team is to turn on Metal backed ANGLE in your Chrome's about:flags. See: https://bugs.chromium.org/p/chromium/issues/detail?id=1245448#c22
