### ISSUE TITLE
[Bug] CPUGridLayer misses some columns when cellSize === 1

### ISSUE THREAD

**Issue by fifzteen** [visgl/deck.gl#6813]
### Description

CPUGridLayer some columns are missing.
I found this when `props.cellSize === 1`.
I’m not sure if this bug raises with other values.

See my Codepen in `Steps to Reproduce` section.
this image is a screen capture of that codepen.

![CPUGridLayer_column_missing](https://user-images.githubusercontent.com/25410805/162687184-0197a652-415f-4423-9b2a-5c9a7c4b5db1.png)

The length of `data` passed from CPUGridLayer is 12. (should be 4 x 4 = 16)
And the values of `lonIdx` are (`28818328`, `28818330`, `28818331`). 
`28818329` is missing, even though data points exist in those cell area.

In every case I faced, missed cells are column-ordered.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

CPUGridLayer fills all grid cells(columns) contains some data point.

### Steps to Reproduce

https://codepen.io/fifzteen/pen/GRyGzNw

### Environment

- Framework version: deck.gl v8.7.3
- Browser: Chrome 100.0.4896.75
- OS: macOS 11.6.2

**Comment by felixpalmer** [comment]
Seems to be some sort of precision issue, I tried a few different values and `1.04` is broken while `1.05` is fine

**Comment by felixpalmer** [comment]
As your data is very fine-grained, it is better if you use a [different coordinate system](https://deck.gl/docs/developer-guide/coordinate-systems). Could you try defining your data in `COORDINATE_SYSTEM.METER_OFFSETS` or `COORDINATE_SYSTEM.LNGLAT_OFFSETS`?

**Comment by fifzteen** [comment]
@felixpalmer 
> it is better if you use a [different coordinate system](https://deck.gl/docs/developer-guide/coordinate-systems).

I add `LNGLAT_OFFSETS` codes to my Codepen... That's works fine!
Thanks a lot!
![スクリーンショット 2022-04-11 19 27 50](https://user-images.githubusercontent.com/25410805/162721883-11eef266-914a-4305-b37f-5a95896d378a.png)

**Comment by Pessimistress** [comment]
Looks like positions are stored in a `Float32Array` in the `CPUGridLayer`. I'll put up a fix.

**Comment by Pessimistress** [comment]
Fixed in v8.7.8

**Comment by fifzteen** [comment]
I confirm fixed in v8.7.8. thanks! (Codepen updated)
![スクリーンショット 2022-04-25 11 58 47](https://user-images.githubusercontent.com/25410805/165013593-f626aa47-f8dc-45aa-8b0c-2d64598e3516.png)
