### ISSUE TITLE
[Feat] modelMatrix animation transition

### ISSUE THREAD

**Issue by bbss** [visgl/deck.gl#6830]
### Target Use Case

In our application we have some overlayed tile-layers that I'd like to animate the layout of, I see that attribute transitions are still in development and I think it would be great if the modelMatrix could be transitioned. I've made a simplified use case with a SolidPolygonLayer. What I tried in my the codesandbox already partially works, in that the easing function gets called but the transition is instant. I'm now animating the modelMatrix manually within the react render, that works well enough for our use-case but it would be nice to have this supported by deck (get the easing/better performance).

https://codesandbox.io/s/hopeful-northcutt-gzc89v?file=/src/App.js

### Proposal

Expand the current transitions prop to support modelMatrix, as I've tried to use in the example.

**Comment by Pessimistress** [comment]
Uniform transition is supposed to work in v8. This should be a bug.

**Comment by Pessimistress** [comment]
Fixed in v8.7.8
