### ISSUE TITLE
[Bug] CARTO maps api not including schema in the response

### ISSUE THREAD

**Issue by eamador** [visgl/deck.gl#6831]
### Description

The maps api should return the `schema` in the response for both `GET` and `POST` requests.

**Issue**
When sending a request to the maps api, from the `mapInstantiation` function found at `maps-v3-client.ts`, the schema is not returned in the response
```ts
const body = JSON.stringify({
      q: source,
      client: clientId || DEFAULT_CLIENT
    });
return await requestJson({method: 'POST', url: baseUrl, accessToken, body});
``` 
![Captura de pantalla 2022-04-18 a las 13 29 47](https://user-images.githubusercontent.com/9006480/163802096-d89cefe3-f914-48bf-a204-a77f47858446.png)
![Captura de pantalla 2022-04-18 a las 13 29 53](https://user-images.githubusercontent.com/9006480/163802097-458b231a-89fc-412f-a588-766536276943.png)

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The schema should be included in the response

### Steps to Reproduce

Send a POST request to the maps API like below and check the response, where no schema is found.
```ts
const body = JSON.stringify({
      q: source,
      client: clientId || DEFAULT_CLIENT
    });
return await requestJson({method: 'POST', url: baseUrl, accessToken, body});
``` 

### Environment

- Framework version: `deck.gl/carto@^8.7.3`
- Browser: any
- OS: any

**Comment by alasarr** [comment]
Closing as it's a bug at CARTO maps API. However, we can clean part of our code: https://github.com/visgl/deck.gl/issues/6832
