### ISSUE TITLE
[Bug] Map Provider from react-map-gl not work

### ISSUE THREAD

**Issue by suryakumara** [visgl/deck.gl#6870]
### Description

I wondering how to add full screen button in DeckGL with MapGL React. Now it's unbale to click the button.
        <DeckGL
                    viewState={viewState}
                    controller={{ doubleClickZoom: false }}
                    layers={[geoJSONLayerRef.current]}
                    onHover={(e) => {
                      setHoveredArea({ coordinate: e.coordinate, feature: e.object });
                    }}
                    onViewStateChange={onViewStateChange}
                    ref={mapRef}
                    ContextProvider={MapProvider}
                  >
                    <Map
                      mapStyle="mapbox://styles/mapbox/streets-v11"
                      mapboxAccessToken={
                        process.env.REACT_APP_MAPBOX_ACCESS_TOKEN || ''
                      }
                    >
                      <div style={{ margin: 10, position: 'absolute', zIndex: '20' }}>
                        <FullscreenControl containerId="fullscreen-deckgl" />
                      </div>
                    </Map>
        </DeckGL/            

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

Attached below

### Environment

- Framework version:
- Browser:
- OS: Mac

**Comment by Pessimistress** [comment]
react-map-gl v7's context does not work with deck.gl, see http://visgl.github.io/react-map-gl/docs/upgrade-guide. You can downgrade to v6 if you need the react map controls.
