### ISSUE TITLE
[Bug] Zooming past anti meridian, the map jumps somewhere else

### ISSUE THREAD

**Issue by metdockal** [visgl/deck.gl#6876]
### Description

I'm facing an issue when zooming past antimeridian, the map jumps to the west.
This is happening only with mapbox-gl version 2.8.0 and above.

When I'm using version mapbox-gl version 2.7.1 and below, the custom DeckGL TileLayer disappears until you pan the map, however, the map doesn't jump to the west.

But to be fair, I haven't found anywhere the official supported mapbox-gl version for deck.gl@8.7.8

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

**Either:**
For mapbox-gl version 2.8.0 and above
- The map doesn't jump elsewhere when zooming

For mapbox-gl version 2.7.1 and below
- The custom DeckGL TileLayer does not disappear

### Steps to Reproduce

Codepen demo https://codepen.io/metdockal/pen/zYRxRzX

At some point, the map jumps to the west when zooming in past antimeridian
1. Zooming from level 1
![image](https://user-images.githubusercontent.com/49377387/166448940-dfe5e75f-8b2d-4a1a-8d66-9bd256532882.png)

2. Still good, keep zooming
![image](https://user-images.githubusercontent.com/49377387/166448828-cdd363e8-1c7e-4ce2-9796-6cb82348817e.png)

3. Jumps to South America 
![image](https://user-images.githubusercontent.com/49377387/166449003-aec784d6-4bf7-41bf-ba26-be35b511e7f5.png)

### Environment

- Framework version: deck.gl@8.7.8, mapbox-gl-js/v2.8.0
- Browser: Chrome 101.0.4951.41
- OS: Ubuntu 20.04.4 LTS

**Comment by Pessimistress** [comment]
I am unable to reproduce this issue with your sandbox. When you use the MapboxLayer the map interactions are handled by mapbox-gl. Are you observing the same issue with the base map only?

**Comment by metdockal** [comment]
Thank you for your reply. Yes, I'm observing the same issue with the base map only so the issue is in mapbox-gl itself. https://github.com/mapbox/mapbox-gl-js/issues/11866

**Comment by metdockal** [comment]
Closing in favor of https://github.com/visgl/deck.gl/issues/6894
