### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mmz15** [visgl/deck.gl#6878]
### Description

I have a React project that uses DeckGL and Mapbox. I'm interleaving the layers to display Mapbox layers in DeckGL. One of the layers I want to interleave is Mapbox's 3D buildings layer. [Here's](https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/) a non-React implementation from the DeckGL website.

**The bug:** Extruded Mapbox buildings don't work when interleaving DeckGL and Mapbox layers.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Extruded 3D buildings on zoom. Currently, there's no building extrusion, regardless of the zoom level. Code below is, to my knowledge, the correct implementation of building extrusion in DeckGL. The fail to load. There is no error, yet `console.log(Object.keys(mapbox.style._layers))` shows that `3d-buildings` exists as a Mapbox layer (the last one in the list).

### Steps to Reproduce

Here's the return statement of my custom DeckGL component:
```
return (
    <DeckGL
      controller
      height={height}
      layers={layers}
      onViewStateChange={({ viewState }) => setViewport(viewState)}
      onWebGLInitialized={(gl) => setGl(gl)}
      ref={(ref) => ref && setDeck(ref.deck)}
      viewState={viewport}
      width={width}
      getTooltip={getTooltip}
      {...props}
    >
      {gl && (
        <StaticMap
          ref={mapRef}
          height={height}
          gl={gl}
          mapboxApiAccessToken={mapboxToken}
          mapStyle={mapStyle}
          onLoad={(e) => {
            const layers = mapbox.getStyle().layers;
            const labelLayerId = layers.find(
              (layer) => layer.type === "symbol" && layer.layout["text-field"]
            ).id;
            e.target.addLayer(
              new MapboxLayer(
                {
                  deck: deck,
                  id: "3d-buildings",
                  source: "composite",
                  "source-layer": "building",
                  filter: ["==", "extrude", "true"],
                  type: "fill-extrusion",
                  minzoom: 10,
                  paint: {
                    "fill-extrusion-color": "#aaa",
                    "fill-extrusion-height": [
                      "interpolate",
                      ["linear"],
                      ["zoom"],
                      15,
                      0,
                      15.05,
                      ["get", "height"],
                    ],
                    "fill-extrusion-base": [
                      "interpolate",
                      ["linear"],
                      ["zoom"],
                      15,
                      0,
                      15.05,
                      ["get", "min_height"],
                    ],
                    "fill-extrusion-opacity": 0.6,
                  },
                },
                labelLayerId
              )
            );
          }}
          width={width}
        >
          {children}
        </StaticMap>
      )}
    </DeckGL>
  );
```

### Environment

- Framework version: 8.7.8
- Browser: Chromium Version 95.0.4631.0 (Developer Build) (x86_64)
- OS: Mac 12.3.1

**Comment by Pessimistress** [comment]
What is the bug you are trying to report?

**Comment by mmz15** [comment]
@Pessimistress updated the report

**Comment by Pessimistress** [comment]
The purpose of `MapboxLayer` is to add a deck.gl layer to Mapbox. You are trying to add 3D buildings as a mapbox-gl native layer. You should pass a plain object to `addLayers`.

Please use Discussions if you need further help debugging your own application.
