### ISSUE TITLE
[Bug] bearing is required for transition

### ISSUE THREAD

**Issue by NameFILIP** [visgl/deck.gl#6883]
### Description

We're facing an issue when zooming a map the following error is thrown:
```
bearing is required for transition
```

I've investigated a little bit and looks like it's coming because of the following definition: https://github.com/visgl/deck.gl/blob/v8.7.0/modules/core/src/controllers/map-controller.ts#L503

I've noticed that this logic was refactored in https://github.com/visgl/deck.gl/pull/6708 which might have fixed the issue.

But I'm struggling to understand the release process of deck.gl now.

* modules on master have `8.7.0-beta.7` version
* on the releases page I see `8.7.8` which was released 12 days ago: https://github.com/visgl/deck.gl/releases
* The PR I mentioned above was merged 2 months ago, but it's still not present in the `8.7.8` 

What's the release strategy for this library? 
When will the fix be available?

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

-

### Steps to Reproduce

-

### Environment

-

**Comment by Pessimistress** [comment]
You are correct that this issue is fixed on the master branch. It will be in the alpha release of v8.8.

> I'm struggling to understand the release process of deck.gl now.

Master is the branch in development. The latest production release is published from the 8.7-release branch.

See https://github.com/visgl/tsc/blob/master/developer-process/directory-structure.md#branching-and-releasing-model

**Comment by Pessimistress** [comment]
Fixed in the latest alpha release.
