### ISSUE TITLE
[Bug] Zooming past anti meridian the custom layer disappears

### ISSUE THREAD

**Issue by metdockal** [visgl/deck.gl#6894]
### Description

When I'm using version mapbox-gl version 2.7.1 and below, the custom DeckGL TileLayer disappears until you pan the map.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The custom DeckGL TileLayer does not disappear

### Steps to Reproduce

1. Initialize map at center: [175, -40], zoom: 1
2. Add a custom TileLayer
3. Zoom to Chatham Island (East of NZ)
4. The custom layer disappears
https://jsbin.com/bifofik/edit?html,output

https://user-images.githubusercontent.com/49377387/167366951-370669f1-3864-42bd-99bd-c27514d3b5d8.mp4

### Environment

- Framework version: deck.gl@8.7.8, mapbox-gl-js/v2.7.1
- Browser: Chrome 101.0.4951.41
- OS: Ubuntu 20.04.4 LTS

**Comment by Pessimistress** [comment]
Fixed by v8.7.10
