### ISSUE TITLE
[Bug] Using deck.gl with Create React App

### ISSUE THREAD

**Issue by abouroubi** [visgl/deck.gl#6896]
### Description

I'm trying to use deck.gl with CRA 5 and Mapbox, unfortunately Mapbox JS has an issue with webworker.

I tried the solutions found in Mapbox docs: https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling
Updating the borwserlist is the only solution that I could use, because CRA don't let the user update webpack config.
This solution didn't work with deck.gl, I wonder if mapbox is imported by dekc.gl in a specific way that prevent this solution from working ? Or if anybody found a solution for this issue.

Thanks

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

The codepen can't reproduce the bug because we need to use CRA.

### Environment

- Framework version: 8.6.0
- Browser: Firefox or Chrome 
- OS: Mac OS

**Comment by Pessimistress** [comment]
deck.gl does not reference mapbox-gl. Please refer to https://github.com/visgl/react-map-gl/issues/1266 if you are using react-map-gl.
