### ISSUE TITLE
[Bug]npm i deck.gl failed

### ISSUE THREAD

**Issue by liuheng-pony** [visgl/deck.gl#6902]
### Description

I failed to install neither a package who depends on deck.gl nor the deck.gl and got 404 for https://registry.npmjs.org/@deck.gl/extensions/-/@deck.gl/extensions-8.7.9.tgz

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

```console
$ npm i deck.gl
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @deck.gl/extensions@8.7.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'deck.gl'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liuheng/.npm/_logs/2022-05-12T12_00_39_812Z-debug.log
$ npm i @deck.gl/extensions@8.7.9
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @deck.gl/extensions@8.7.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liuheng/.npm/_logs/2022-05-12T12_01_58_167Z-debug.log
```

### Environment

- Framework version: deck.gl@8.7.9
- Browser:
- OS: Ubuntu 18.04
- node: v14.18

**Comment by Pessimistress** [comment]
I cannot reproduce this. NPM lists 8.7.9 in https://www.npmjs.com/package/@deck.gl/extensions. 
If you are still experiencing the failure, there might be an issue with your local NPM config.

**Comment by liuheng-pony** [comment]
> I cannot reproduce this. NPM lists 8.7.9 in https://www.npmjs.com/package/@deck.gl/extensions. If you are still experiencing the failure, there might be an issue with your local NPM config.

Thank you, It recovers now.

However, I was not able to download https://registry.npmjs.org/@deck.gl/extensions/-/extensions-8.7.9.tgz from browser, so it should have none business with local npm and nodejs.
