### ISSUE TITLE
[Feat] CartoLayer support for spatial indices

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#6912]
### Target Use Case

The [recent changes to TileLayer](https://github.com/visgl/deck.gl/pull/6848) make it possible to use data that has its geography encoded using a spatial index, rather than with latitude/longitude. 

The upcoming API in the CARTO platform will support tiled data using quadkeys and h3 indices.

### Proposal

`CartoLayer` is extended to support these datasets:

```js
return new CartoLayer({
    // Usual data props
    connection,
    data,

    // Aggregation configuration
    aggregationExp: 'avg(population) as value, 0.1*avg(population) as elevation',
    aggregationResLevel: 6,
    geoColumn: 'geom',
    getQuadkey: d => d.id,

    // Styling
    getFillColor: d => [255 * d.properties.value, 0, 0],
    getElevation: d => d.properties.elevation,
    extruded: true,
    opacity: 0.3,
    elevationScale: 100
  })
```

As the spatially indexed datasets are aggregated, the following props are added:

- `aggregationExp` a SQL expression to specify how to aggregate
- `aggregationResLevel` the resolution at which to aggregate

These parameters are passed directly to the API and are opaque to the client code.

**Comment by felixpalmer** [comment]
## Checklist

- [ ] Implement quadkey support
- [ ] Implement h3 support
- [ ] Tests
- [ ] Doc update
- [ ] QA

**Comment by alasarr** [comment]
After creating a couple of maps I've just realized that we shouldn't require the usage of  `getQuadkey: d => d.id`. As the format is always like that I'd like to remove that complexity for the user.
