### ISSUE TITLE
[Feat] GeohashLayer

### ISSUE THREAD

**Issue by ragnarok56** [visgl/deck.gl#6916]
### Target Use Case

Like quadkeys and s2, geohashes are another way of encoding geospatial data. 

Rather than attempting to load large datasets with all of the individual points, tools like [Elasticsearch Geohash Aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html) can pre-compute the information server side and return much smaller payloads for clients to then visualize.  Having this layer supported by deck.gl would simplify integration with Elasticsearch and similar applications.

### Proposal

This would work very similar to QuadkeyLayer, inheriting from GeoCellLayer and defining the polygon based on geohash bounding box.  

![image](https://user-images.githubusercontent.com/1396398/168719707-b5fbf58e-03c2-4b05-a225-01aaf7613e24.png)

**Comment by ibgreen** [comment]
Great idea. I do feel there is a lot of boilerplate overhead involved in creating a new sublayer for each geo key system (i.e. just to plug in a different geo key library). The attached PR illustrates this. 

At some point we may want a deeper integration of geo keys into library but this is of course a very nice addition for now.

**Comment by jmp601** [comment]
I'd like to point out the new geohex aggregation type that could be leveraged here as well. Lots of libraries for H3.
