### ISSUE TITLE
[Doc] outdatex example using MapContext

### ISSUE THREAD

**Issue by frafra** [visgl/deck.gl#6920]
### Link

https://deck.gl/docs/api-reference/react/deckgl#contextprovider

### Description

This example is not valid as version 7 removed MapContext: https://deck.gl/docs/api-reference/react/deckgl#contextprovider
Related: https://github.com/visgl/react-map-gl/issues/662#issuecomment-1049785859

### Expected Behavior

Examples should work on the latest stable.

### Steps to Reproduce

Try to run the example.

### Environment

- react-map-gl@7.0.0.12

**Comment by Pessimistress** [comment]
The `ContextProvider` prop does not work with react-map-gl v7. We should clarify that in the docs.

**Comment by Alek-S** [comment]
is there another way of using react-map-gl 7 with deck without ContextProvider, or does it require a downgrade to v6?

**Comment by Pessimistress** [comment]
@Alek-S https://github.com/visgl/deck.gl/discussions/6955
