### ISSUE TITLE
Declaring object from the `Deck` component from the `@deck.gl/core` dependency change the app style

### ISSUE THREAD

**Issue by jaballogian** [visgl/deck.gl#6930]
### Description

I'm testing some deck.gl documentations by creating one by one playground here https://codesandbox.io/s/learn-deck-gl-s1jmeb

I'm testing this documentation https://deck.gl/docs/developer-guide/interactivity (Reset Camera Position section) by creating this playground https://codesandbox.io/s/learn-deck-gl-s1jmeb?file=/src/pages/AddingInteractivity/ResetCameraPosition.jsx

I imported the `Deck` class from the `@deck.gl/core` dependency and created an instance from it (see the screenshot below)
then I refreshed the page to see the changes
then the scrollbar suddenly appeared in the playground and the map was not interactive anymore (I couldn't zoom or drag the map)
![image](https://user-images.githubusercontent.com/24468466/169447013-4dacb70d-1973-4554-b3a3-0f8513376a11.png)

If I commented/hid the instance from the `Deck` class, the scrollbar disappeared and the map was back to interactive (I could zoom or drag the map)
![image](https://user-images.githubusercontent.com/24468466/169447699-e4d477d8-79ce-483f-ad79-d4f1f029d920.png)

The code (in the codesandbox) from the page "ResetCameraPosition" is very similar to the code from the "GettingStarted" page (I copied and pasted the code then created an instance from the `Deck` class)

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Creating an instance from the `Deck` class shouldn't change the page/app style (shouldn't show the scrollbar) and shouldn't disappear the map interactivity

### Steps to Reproduce

1. run and test this codesandbox https://codesandbox.io/s/learn-deck-gl-s1jmeb?file=/src/pages/AddingInteractivity/ResetCameraPosition.jsx -> the scrollbar appears and the map is not interactive
2. comment the instance from the `Deck` class -> the scrollbar disappears and the map is back to interactive

### Environment

- Framework version:  deck.gl@8.7.9
```
"dependencies": {
    "@deck.gl/aggregation-layers": "8.7.9",
    "@deck.gl/core": "8.7.9",
    "@deck.gl/layers": "8.7.9",
    "@deck.gl/react": "8.7.9",
    "deck.gl": "8.7.9",
    "mapbox-gl": "2.8.2",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-map-gl": "7.0.12",
    "react-router-dom": "6.3.0",
    "react-scripts": "4.0.0"
  },
```
- Browser: Chrome 101
- OS: Windows 11

**Comment by Pessimistress** [comment]
The `DeckGL` React component creates a `Deck` instance under the hood. You either use `Deck` or `DeckGL`, not both. Please refer to the [React get started example](https://github.com/visgl/deck.gl/tree/master/examples/get-started/react/basic).
