### ISSUE TITLE
[Bug] Orthographic controller + 'pinchend' event + inertia completely breaks interaction on iOS (only)

### ISSUE THREAD

**Issue by mcost45** [visgl/deck.gl#6960]
### Description

Hey, after lots of testing I've found 'pinchend' events will completely break interaction on iOS - curiously this doesn't occur on any other touch device I've tested (android, tablets).

The exact problematic code path only occurs when inertia is enabled - [when _onPinchEnd triggers newControllerState.zoom()](https://github.com/visgl/deck.gl/blob/0d3e70aefb845cd7b37ce030a67d8a6540420c5c/modules/core/src/controllers/controller.ts#L659). In the following zoom func, specifically of [orbit controller, makeViewport is undefined](https://github.com/visgl/deck.gl/blob/0d3e70aefb845cd7b37ce030a67d8a6540420c5c/modules/core/src/controllers/orbit-controller.ts#L220), throwing the error, essentially freezing the application.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

pinchend should not throw

### Steps to Reproduce

Test out this example (orthographic view example with inertia enabled) on iOS to see it. Use two finger pinching to cause the bug:
https://codepen.io/mttrx/pen/yLvKKmM

### Environment

- Framework version: 8.7.10 - though this issue has been present for quite a while
- Browser: Chrome, safari
- OS: iOS 15.5

### Logs

TypeError: this.makeViewport is not a function. (In 'this.makeViewport({...this.viewportProps, zoom: newZoom})', 'this.makeviewport' is undefined

**Comment by Pessimistress** [comment]
Can you confirm that this is fixed in the latest version?

**Comment by mcost45** [comment]
On first test, my mouse panning is broken 😅 I will investigate a little more to see what's going on.

**Comment by mcost45** [comment]
Yes it's fixed, thanks!!
