### ISSUE TITLE
[Bug] Error while rendering a Polygon layer

### ISSUE THREAD

**Issue by rk-yen** [visgl/deck.gl#7020]
### Description

While rendering a Polygon, I am seeing an error that reads:
```
SolidPolygonLayer({id: 'PolygonLayer-fill'}): @math.gl/web-mercator: assertion failed.
```

The same Geojson being used in the example renders as expected at http://geojson.io/.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

Codepen link: https://codepen.io/raviyenduri/pen/ZErmGep?editors=0011

### Environment

- Framework version: Latest (https://unpkg.com/deck.gl@latest/dist.min.js) and also v8.3.2
- Browser: Chrome
- OS: macOS

### Logs

```
SolidPolygonLayer({id: 'PolygonLayer-fill'}): @math.gl/web-mercator: assertion failed.
```

**Comment by Pessimistress** [comment]
The PolygonLayer does not support `MultiPolygon`, please read https://deck.gl/docs/api-reference/layers/polygon-layer#getpolygon

If you want to render an arbitrary GeoJSON, use GeoJsonLayer instead.
