### ISSUE TITLE
[Bug] FillStyleExtension precision at high zoom

### ISSUE THREAD

**Issue by exceptiondc** [visgl/deck.gl#7069]
### Description

I am using fillstyleextension in geojsonlayer to fill polygons, but dragging the page under high magnification will find the map redrawing and jittering. I have reproduced my problem in codepen. Please have a look

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

https://codepen.io/exceptiondc/pen/yLvdeGM

### Environment

- Framework version: ^8.7.0-beta.6
- Browser: chrome 102.0
- OS: win10

**Comment by Pessimistress** [comment]
Fixed in 8.7.12
