### ISSUE TITLE
[Bug] Website documentation: "Contributing to deck.gl" is not working

### ISSUE THREAD

**Issue by AnaDiaz85** [visgl/deck.gl#7083]
### Description

I can’t visualize "Contributing to deck.gl" documentation.

<img width="1383" alt="Screenshot 2022-06-24 at 12 04 04" src="https://user-images.githubusercontent.com/49390946/175513821-c92f56c1-75bd-430e-b45a-a239dc95b228.png">

It happens in all browsers, with the lastest version:

<img width="795" alt="Screenshot 2022-06-24 at 10 10 33" src="https://user-images.githubusercontent.com/49390946/175492952-075bd7db-72d8-4b8b-aef4-54d54f800e55.png">

```
Request URL: https://pessimistress.github.io/docs/contributing
Request Method: HEAD
Status Code: 404 
Remote Address: 185.199.109.153:443
Referrer Policy: strict-origin-when-cross-origin
```

```
curl 'https://pessimistress.github.io/docs/contributing' \
  -X 'HEAD' \
  -H 'authority: pessimistress.github.io' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,es;q=0.8' \
  -H 'cache-control: no-cache' \
  -H 'cookie: _ga=GA1.3.1192310826.1656001380; _gid=GA1.3.1737840587.1656312579' \
  -H 'pragma: no-cache' \
  -H 'referer: https://pessimistress.github.io/deck.gl/docs' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36' \
  --compressed
```

[pessimistress.github.io-1656339212212_contributingdeck.log](https://github.com/visgl/deck.gl/files/8992731/pessimistress.github.io-1656339212212_contributingdeck.log)

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

It should work.
The same link in the official deck.gl website is working fine.

### Steps to Reproduce

1. Go to https://pessimistress.github.io/deck.gl/docs/contributing

### Environment

- Framework version: `8.8.0-beta`. `latest `
- Browser: All browsers
- OS: macOS Monterey version 12.4 / iOS (iPhone 13 Pro - iPad 12.9) / Android (Galaxy S22 - Galaxy Tab S8)

**Comment by AnaDiaz85** [comment]
@felixpalmer , it is also happening from iPhone (safari-chrome). I have tested iPhone 13 Pro

**Comment by Pessimistress** [comment]
This was due to an error pushing to the staging environment. Fixed.
