### ISSUE TITLE
[Bug] Website Examples: Integrations Google Maps is not working

### ISSUE THREAD

**Issue by AnaDiaz85** [visgl/deck.gl#7085]
### Description

I can’t visualize the integration of Google Maps.

<img width="1388" alt="Screenshot 2022-06-24 at 12 37 41" src="https://user-images.githubusercontent.com/49390946/175518597-5c4605fb-e4b3-4dc3-9f5e-7683cf35159b.png">

It happens in all browsers, with the lastest version:

<img width="795" alt="Screenshot 2022-06-24 at 10 10 33" src="https://user-images.githubusercontent.com/49390946/175492952-075bd7db-72d8-4b8b-aef4-54d54f800e55.png">

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

You should be able to visualize the example

### Steps to Reproduce

1. Go to https://pessimistress.github.io/deck.gl/examples/arcgis/

### Environment

- Framework version: `8.8.0-beta`. `latest `
- Browser: All browsers / iPhone (Safari - Chrome)
- OS: macOS Monterey version 12.4

**Comment by felixpalmer** [comment]
This is just due to testing on the non-production domain

**Comment by AnaDiaz85** [comment]
> This is just due to testing on the non-production domain

ah, ok, Thank you @felixpalmer
