### ISSUE TITLE
[Bug] pydeck.show() does not render in voila

### ISSUE THREAD

**Issue by DiracConvergence** [visgl/deck.gl#7090]
### Description

I am unable to render pydeck.show() in voila, although it works correctly in Jupyter. Is this an expected behavior or should it be addressed ?

Is this because pydeck is notebook specific? I thought not, as some examples seem to be hosted on mybinder. I assumed it was possible to use pydeck in a Voila environment. I'm also unable to make those examples work, which could lead to a different issue (https://mybinder.org/v2/gh/uber/deck.gl/binder is not working, so every link in the documentation related to binder is down). 

### Flavors

- [ ] React
- [X] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Consistency between voila and jupyter.

### Steps to Reproduce

Type the following in a jupyter cell :

import pydeck as pdk
res = pdk.Deck(height = 800)
res.show()

Launch a Voila with the command : voila --enable_nbextensions=True

### Environment

- Python version : Python 3.7
- Framework version: deck.gl@0.7.1
- Browser: Microsoft Edge
- OS: Windows 10

### Logs

It is possible to inspect the Voila to see some javascript errors.

**Comment by kylebarron** [comment]
Does voila support jupyter widgets? If not, you can use [`.to_html()`](https://pydeck.gl/deck.html#pydeck.bindings.deck.Deck.to_html) to generate an html representation of the pydeck map and render that in an iframe

**Comment by kylebarron** [comment]
> Launch a Voila with the command : voila --enable_nbextensions=True

Does this also include enabling the pydeck extension specifically? With some versions of notebook you need to explicitly bundle the extension with JS https://pydeck.gl/installation.html#enabling-pydeck-for-jupyter

**Comment by luipir** [comment]
Hi @DiracConvergence any answer to questions by @kylebarron ?

**Comment by donmccurdy** [comment]
Closing, but happy to re-open if anyone is able to help identify what's needed for voila support.
