### ISSUE TITLE
[Feat] Customising texture parameters on auto packed icon layer

### ISSUE THREAD

**Issue by Lyeeedar** [visgl/deck.gl#7126]
### Target Use Case

I would like to be able to customise the texture parameters used on an auto-packed texture in an IconLayer. I see there is a textureParameters field on IconLayer that is documented to only work on a passed in iconAtlas (though I glanced over the code and couldn't spot where it was actually passed in to the a texture constructor, so that may not work either).

I would like to be able to use this field for the auto-packed texture too, instead of DEFAULT_TEXTURE_PARAMETERS.

I can raise a PR if you like, it seems like an easy thing to add.

### Proposal

I propose passing the textureParameters into the from icon-layer into icon-manager setProps function, then in the packIcons functions doing:

this._texture = new Texture2D(this.gl, {
          width: this._canvasWidth,
          height: this._canvasHeight,
          parameters: this._textureParameters ?? DEFAULT_TEXTURE_PARAMETERS
        });

Commit with proposed changes: https://github.com/Lyeeedar/deck.gl/commit/36676fd411f7765047e5074f3e397f6a9299c96e

**Comment by Lyeeedar** [comment]
PR opened https://github.com/visgl/deck.gl/pull/7136

**Comment by Pessimistress** [comment]
Thank you! Published v8.8.5
