### ISSUE TITLE
tileset.modelMatrix.clone is not a function

### ISSUE THREAD

**Issue by Radik24** [visgl/deck.gl#7133]
### Description

Hi,

I upgraded deck.gl from `8.7.11` to `8.8.3` and now I cannot render any `Tile3DLayer`. Did I miss something in upgrade guide?

Thanks

### Expected Behavior

I want to see 3D data in map.

### Steps to Reproduce

Upgrade deck.gl from `8.7.11` to `8.8.0`+

### Environment

- Framework version: `deck.gl@8.8.3`, `loaders.gl@3.2.4`
- Browser: chrome
- OS: MacOS

### Logs

![image](https://user-images.githubusercontent.com/23722745/178260488-792e4389-dc3f-41e0-b018-a0a0b51844f6.png)

**Comment by Radik24** [comment]
Will, try. I just installed upgraded modules (multiple times and neither 8.8.+ version does not work) and started app. Yeah i saw examples so I don't know what is wrong. Will let you know.

Thanks

**Comment by ibgreen** [comment]
- Perhaps you can break on uncaught exceptions and inspect the `modelMatrix` value in the debugger? 
- If the `modelMatrix` is just an `Array` and not a `Matrix4` instance (which inherits from array), it won't have a `clone()` method. 
- It could be that some code path now just sets the matrix to a hardcoded array. 
- If so, could easily be fixed in loaders.gl or you could just import Matrix4 from `@math.gl/core` and copy the array into a Matrix4().

**Comment by Radik24** [comment]
I found it.

Don't know why examples work. My backend, data,.. is unchanged, just upgraded deck.gl. But it is an Array sometimes

![image](https://user-images.githubusercontent.com/23722745/178421413-54830fe4-c611-442c-85cd-292d63c3171a.png)

**Comment by Pessimistress** [comment]
Check the installed version of all your `@loaders.gl/*` modules with `npm ls`/`yarn list`.

**Comment by Radik24** [comment]
also tried it with the same data from ion as in example

**Comment by Pessimistress** [comment]
What is the `__ob__` thing? Are you using Vue?

**Comment by ibgreen** [comment]
> could cause Vue to observe the instance as a mutable (which mutates layer.state.tileset).

That seems like a more general concern beyond the specific problem of the model matrix? I don't think I know enough about how those observers work to form an opinion. In a number of cases I was freezing objects to prevent surprises from new fields being added during run-time. Layers are a bit different since they are by design immutable. Not up to date on what challenges with doing object.freeze in constructors in typescript are....

**Comment by ibgreen** [comment]
For the specific matrix issue:
- I suppose it could be that the process of observing destroys the Matrix4 prototype and "forgets" that it is in fact an Array subclass. Subclassing from Array is a bit uncommon and may not be properly handled by the observers. 
- However, the fact that the debugger screenshot shows that is an identity matrix could also mean that some maintainer of loaders.gl (probably @belom88 or @dryabinin-actionengine) added some code path that initializes to an identity matrix and forgot to wrap it in Matrix4. It should not be too hard to put breakpoints in various constructors and track it down.

**Comment by Pessimistress** [comment]
Loaders seems to be implemented correctly. As discussed above, the same layer works when using React.

@Radik24 you can confirm the diagnosis by manually freezing your layer, i.e. `const layer = Object.freeze(new Tile3DLayer(...))`.

**Comment by Radik24** [comment]
@Pessimistress it seems to be solved with:

![image](https://user-images.githubusercontent.com/23722745/179004952-306c6617-f210-494e-915e-99cdd70b62d9.png)

Do you think it will work fine?

Some quasar/vue issues. I hope we will upgrade to latest quasar/vue where it should be solved (I found somewhere on google).

Thanks!

**Comment by Pessimistress** [comment]
Ah how about `const layer = Object.seal(new Tile3DLayer(...))`?

Ultimately we should have a test case for Vue. @Radik24 if you could help us put together a [get-started](/examples/get-started/pure-js) example it would make future releases less prone to such regressions. I don't believe anyone among the current contributors is familiar with Vue.js.

**Comment by Radik24** [comment]
@Pessimistress yeah ^^ is works fine on `Tile3DLayer` and `ScenegraphLayer`, all the other layers seems to be working.

Thanks!

Yeah I can help you, but not sure if it will be helpful now. We use outdated version nowadays and we are talking about upgrade months. It seems to be very challenging. But once we upgrade I'll love to write some notes.
