### ISSUE TITLE
[Feat] Add new layer to implement force directed destination-origin flow maps

### ISSUE THREAD

**Issue by ehartford** [visgl/deck.gl#7138]
### Target Use Case

This will enable for directional flow maps

### Proposal

it should be similar to ArcLayer, and GreatCircleLayer

But the path should be directional force directed arcs like this:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/1117701/178597529-3a53d9cc-1c6b-4d45-9bdc-d7dfd8ae33bd.png">

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1117701/178597658-40e98ed1-3181-4daa-ba8c-23a9a65622e9.png">

The algorithm is described in this paper.

Jenny, Bernhard & Stephen, Daniel & Muehlenhaus, Ian & Marston, Brooke & Sharma, Ritesh & Zhang, Eugene & Jenny, Helen. (2017). Force-directed Layout of Origin-destination Flow Maps. International Journal of Geographical Information Science. 31. 10.1080/13658816.2017.1307378.

**Comment by Pessimistress** [comment]
I think this will be a good suggestion for https://flowmap.blue, which is also part of the visgl organization.

**Comment by ehartford** [comment]
Thank you for the feedback.
I will raise the issue there instead.

**Comment by ehartford** [comment]
I'll look at https://github.com/FlowmapBlue/flowmap.gl
