### ISSUE TITLE
[Bug] MapboxOverlay - Resolving layerIndex of Layers after Tile-like layer looks strange

### ISSUE THREAD

**Issue by fifzteen** [visgl/deck.gl#7139]
### layers
layers are like below.
some Tile-like layer, and primitive layer follows that.

```js
layers: [
  // Tile-like layer
  new MVTLayer({...}),
  // primitive layer
  new SolidPolygonLayer({
    getFillColor: [255, 0, 0, 255],
    getPolygonOffset: ({layerIndex}) => {
      console.log(layerIndex)
      retrun [0, -layerIndex * 100] // same as default
    },
  })
]
```

### overlays
and set layers to GoogleMapsOverlay / MapboxOverlay

```js
// google
const googleMap = new google.maps.Map(document.getElementById("google"), {...})
new GoogleMapsOverlay({ layers }).setMap(googleMap)

// mapbox
const mapboxMap = new mapboxgl.Map({
  container: 'mapbox',
  style: 'mapbox://styles/mapbox/streets-v11',
})
mapboxMap.on('load', () => {
  const overlay = new MapboxOverlay({ interleaved: true, layers })
  mapboxMap.addControl(overlay)
})
```

### rendered

![スクリーンショット 2022-07-13 17 09 05](https://user-images.githubusercontent.com/25410805/178684206-73990b6e-9713-47ee-8ad7-657daa4bb35e.png)

on Mapbox, former tile geometries is overlaid on latter red polygon. (looks reversed)

### layerIndex
Just after rendering, layerIndex outputted in console are `4` (GoogleMaps), `0` (Mapbox)
after that, some mouse action on map and layerIndex (Mapbox) turns `4` (rendering not changes. still reversed)

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Same as GoogleMapsOverlay behavior (maybe it's same as pure deck.gl)

### Steps to Reproduce

https://codepen.io/fifzteen/pen/MWQvQLr

### Environment

- Framework version: deck.gl@8.8.4
- Browser: Chrome 103.0.5060.114
- OS: macOS 11.6.2

**Comment by Pessimistress** [comment]
Fixed in v8.8.5
