### ISSUE TITLE
[Feat] Pass lat/lng/zoom to the onError handler whenever possible

### ISSUE THREAD

**Issue by NameFILIP** [visgl/deck.gl#7140]
### Target Use Case

This would help developers to reproduce the error once it is detected in the logs.

### Proposal

Currently, `onError` handler receives 2 arguments: `(error, layer)`. 
I suggest adding a third one that would contain `longitude, latitude, zoom`.

**Comment by NameFILIP** [comment]
I also reported a similar issue for `react-map-gl`: https://github.com/visgl/deck.gl/issues/7140

**Comment by Pessimistress** [comment]
You can use `layer.context.viewport` to get the latest viewport.
