### ISSUE TITLE
[Bug] mapboxApiAccessToken still in the docs

### ISSUE THREAD

**Issue by ShaneLee** [visgl/deck.gl#7143]
### Description

mapboxApiAccessToken has been replaced in favour of mapboxAccessToken

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

Just documentation

### Environment

- Framework version: 8.8.4
- Browser: N/A
- OS: N/A

**Comment by Pessimistress** [comment]
There is no mistake in the prop names used in this repo. Please do not mix the API of deck.gl and react-map-gl.

**Comment by ShaneLee** [comment]
Ah okay - I was just confused by this page (https://deck.gl/docs/get-started/using-with-react) which has mapboxApiAccessToken but the examples don't work until it's swapped for mapboxAccessToken.

**Comment by Pessimistress** [comment]
The prop name for access token changed between react-map-gl v6 and v7. You are welcome to open a PR to clarify that in the documentation. The PR you opened was trying to replace API names in the deck.gl source code.
