### ISSUE TITLE
[Bug] mapboxOverlay support multiple Instance when use interleaved

### ISSUE THREAD

**Issue by adolfheir** [visgl/deck.gl#7181]
### Description

The current implementation does not share deck Instance which will cause the screen to blink when used multiple mapboxOverlay

![image](https://user-images.githubusercontent.com/26828649/182580733-9cbe8ab0-2cae-494c-9bf4-0574d6d9bffc.png)

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

like this
![image](https://user-images.githubusercontent.com/26828649/182581998-2e1e1008-9917-48a1-bf2a-c4b1450752b6.png)

### Steps to Reproduce

<img width="506" alt="image" src="https://user-images.githubusercontent.com/26828649/182582094-c81713ac-ae21-40c9-93a1-941c1ba653b9.png">

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Why do you use multiple instances? There is only one WebGL context when interleaved.

**Comment by adolfheir** [comment]
> Why do you use multiple instances? There is only one WebGL context when interleaved.

What I mean by that is that mapboxOverlay supports calling in different places, and internal DECkGL objects can be shared
Just like Mapbox-Layer

Let's say I have a business component that shows cluster
There is also a business component that displays Geosjon
Both have some encapsulation of business within them
These are actually two components that I don't want to write in one place and call even though they share a GL object

**Comment by Pessimistress** [comment]
You can't have two Deck instances share the same canvas/context. Each of your component can generate a set of layers and merge them into one `layers` list.

**Comment by adolfheir** [comment]
It's not development friendly,
I mean the merge operation can be done in mapbox-overlay
Similar to Mapbox-layer implementation

**Comment by adolfheir** [comment]
> You can't have two Deck instances share the same canvas/context. Each of your component can generate a set of layers and merge them into one `layers` list.

It's not development friendly,
I mean the merge operation can be done in mapbox-overlay
Similar to Mapbox-layer implementation

**Comment by pathikdevani** [comment]
@adolfheir  I was facing a similar problem and I created an internal wrapper and layer component which merges layers. 

```
import { MapboxOverlay, MapboxOverlayProps } from '@deck.gl/mapbox';
import { noop } from 'lodash';
import { createContext, PropsWithChildren, useCallback, useState } from 'react';
import { useControl } from 'react-map-gl';
const DEFAULT_VALUE: LayersList = [];
export type LayersList = MapboxOverlayProps['layers'];

export const DeckGLLayersContext = createContext<{
  layers: LayersList;
  replace: (layers: LayersList, prev: LayersList) => void;
}>({
  layers: DEFAULT_VALUE,
  replace: noop,
});

function DeckGLOverlay(props: MapboxOverlayProps) {
  const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props));
  overlay.setProps(props);
  return null;
}

type DeckGLWrapperProps = {
  interleaved?: boolean;
};

export function DeckGLWrapper(props: PropsWithChildren<DeckGLWrapperProps>) {
  const { interleaved, children } = props;
  const [layers, setLayers] = useState<LayersList>(DEFAULT_VALUE);

  const replace = useCallback((newL: LayersList, prevL: LayersList) => {
    setLayers(old => {
      let result = old || [];
      if (prevL && prevL.length > 0) {
        result = result.filter(e => prevL.findIndex(prev => prev === e) == -1);
      }

      if (newL && newL.length > 0) {
        result = [...result, ...newL];
      }
      console.log('layers-replace', result);
      return result;
    });
  }, []);
  return (
    <DeckGLLayersContext.Provider value={{ layers, replace }}>
      <DeckGLOverlay interleaved={interleaved} layers={layers} />
      {children}
    </DeckGLLayersContext.Provider>
  );
}

```


```
import { useContext, useEffect, useRef } from 'react';
import { DeckGLLayersContext, LayersList } from './DeckGLWrapper';

type DeckLayerProps = {
  layers: LayersList;
};

export function DeckGLLayer(props: DeckLayerProps) {
  const { layers } = props;
  const prevLayers = useRef<LayersList>([]);
  const { replace } = useContext(DeckGLLayersContext);

  useEffect(() => {
    replace(layers, prevLayers.current);
    prevLayers.current = layers;
  }, [layers, replace]);

  useEffect(() => {
    return () => {
      replace([], prevLayers.current);
      prevLayers.current = [];
    };
  }, [replace]);
  return null;
}
```

**Comment by adolfheir** [comment]
> @adolfheir I was facing a similar problem and I created an internal wrapper and layer component which merges layers.我遇到了类似的问题，我创建了一个内部包装器和图层组件来合并图层。
> 
> ```
> import { MapboxOverlay, MapboxOverlayProps } from '@deck.gl/mapbox';
> import { noop } from 'lodash';
> import { createContext, PropsWithChildren, useCallback, useState } from 'react';
> import { useControl } from 'react-map-gl';
> const DEFAULT_VALUE: LayersList = [];
> export type LayersList = MapboxOverlayProps['layers'];
> 
> export const DeckGLLayersContext = createContext<{
>   layers: LayersList;
>   replace: (layers: LayersList, prev: LayersList) => void;
> }>({
>   layers: DEFAULT_VALUE,
>   replace: noop,
> });
> 
> function DeckGLOverlay(props: MapboxOverlayProps) {
>   const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props));
>   overlay.setProps(props);
>   return null;
> }
> 
> type DeckGLWrapperProps = {
>   interleaved?: boolean;
> };
> 
> export function DeckGLWrapper(props: PropsWithChildren<DeckGLWrapperProps>) {
>   const { interleaved, children } = props;
>   const [layers, setLayers] = useState<LayersList>(DEFAULT_VALUE);
> 
>   const replace = useCallback((newL: LayersList, prevL: LayersList) => {
>     setLayers(old => {
>       let result = old || [];
>       if (prevL && prevL.length > 0) {
>         result = result.filter(e => prevL.findIndex(prev => prev === e) == -1);
>       }
> 
>       if (newL && newL.length > 0) {
>         result = [...result, ...newL];
>       }
>       console.log('layers-replace', result);
>       return result;
>     });
>   }, []);
>   return (
>     <DeckGLLayersContext.Provider value={{ layers, replace }}>
>       <DeckGLOverlay interleaved={interleaved} layers={layers} />
>       {children}
>     </DeckGLLayersContext.Provider>
>   );
> }
> ```
> 
> ```
> import { useContext, useEffect, useRef } from 'react';
> import { DeckGLLayersContext, LayersList } from './DeckGLWrapper';
> 
> type DeckLayerProps = {
>   layers: LayersList;
> };
> 
> export function DeckGLLayer(props: DeckLayerProps) {
>   const { layers } = props;
>   const prevLayers = useRef<LayersList>([]);
>   const { replace } = useContext(DeckGLLayersContext);
> 
>   useEffect(() => {
>     replace(layers, prevLayers.current);
>     prevLayers.current = layers;
>   }, [layers, replace]);
> 
>   useEffect(() => {
>     return () => {
>       replace([], prevLayers.current);
>       prevLayers.current = [];
>     };
>   }, [replace]);
>   return null;
> }
> ```

Thank you, but I no longer use deck.gl.
