### ISSUE TITLE
[Bug] Geojson with only z change doesn't render filled

### ISSUE THREAD

**Issue by Lyeeedar** [visgl/deck.gl#7203]
### Description

When giving a geojson layer a polygon with only Z changes it only renders a stroke at the top and bottom, but no filled polygon interior. Giving the geojson layer lineBillboard: true renders the full outline, but still no interior.

See pic for the issue. Red is the geojson, yellow with lineBillboard, blue when adding 0.00001 to the points at the upper line (so they arent perfectly vertical anymore).

![image](https://user-images.githubusercontent.com/1607501/184928041-297a40a7-c1b0-426a-8e67-f20918401268.png)

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

https://codepen.io/lyeeedar/pen/MWVzQXX

### Environment

- Framework version: deck.gl@8.7.11
- Browser: Firefox 
- OS: Windows 10

**Comment by Pessimistress** [comment]
There isn't a quick fix for this. We tesselate polygons using `earcut` which only handles 2D input. Technically the GeoJSON specification is also 2D. The z component is only respected when projection is performed. Adding a small shift to some points may be the easiest workaround for now. If you are only rendering vertical rectangles in your layer, you could also consider using `SimpleMeshLayer`.

We could use a section in the `PolygonLayer`/`GeoJsonLayer` docs to explain this limitation.

**Comment by Lyeeedar** [comment]
Sadly I'm currently rendering a large amount of arbitrary geojson with z, and just noticed this when some faces weren't rendering. I'd like to avoid triangulating myself to make geometries (I assume that SimpleMeshLayer is only going to handle triangles).

In theory would we maybe be able to have an optional parameter on geojson (and presumably polygon layer) that uses a 3d variant of the earcut algorithm (e.g. if earcut produces no triangles flip 2 of the axis, cut, then flip back. Or maybe something cleverer)? I'm more than happy to try to take a look if you think thats something worth persuing. Would you be able to point me to where in the code it does the earcutting?

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/blob/6708cd139680863d17335600066257a2d16c2c68/modules/layers/src/solid-polygon-layer/polygon.ts#L305-L321

We do pass the z values to [earcut](https://github.com/mapbox/earcut#usage) but I don't think it handles them internally. It's probably more efficient to handle this inside `earcut` instead of calling it multiple times from the layer.

**Comment by Lyeeedar** [comment]
@Pessimistress Is there a way to run the tests for a single file? As it is 'yarn test fast' runs a LOT of tests and takes roughly 5mins to complete.

**Comment by Pessimistress** [comment]
You can use `test.only` on the spec file to only run one test.

**Comment by Lyeeedar** [comment]
Can confirm this works in v8.9.0-alpha.2 when adding _full3d: true to the geojson layers.

**Comment by Lyeeedar** [comment]
![image](https://user-images.githubusercontent.com/1607501/187966678-c8145892-d00b-4088-bbeb-095cbd2468d4.png)
