### ISSUE TITLE
[Bug] Pressing arrow keys with OrthographicView controller performs inverted pan

### ISSUE THREAD

**Issue by odfalik** [visgl/deck.gl#7209]
### Description

Pressing the right arrow key pans the view left (and vice versa, as well as for up/down panning).

If this is actually a bug and not expected behavior, I'd be happy to look into it and submit a PR!

As a workaround, I've tried settings the `moveSpeed` in the `OrthographicViewController`'s `ControllerOptions` to a negative number, but that seems to brick DeckGL.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Pressing the left arrow key should pan left, right should pan right, up should pan up, and down should pan down.

### Steps to Reproduce

This issue manifests in the [OrthographicView example in the documentation](https://codepen.io/vis-gl/pen/YzpXqzv).
Click to focus on the canvas, then press the right arrow key on your keyboard. The view will pan left!

I've reproduced the same behavior when using the default OrthographicView controller in React, as well.

### Environment

- Framework version:
- Browser:
- OS:

### Logs

Nothing in console

**Comment by odfalik** [comment]
If it's useful to know, keyboard panning is also inverted for `OrbitController`.

**Comment by Pessimistress** [comment]
Hmm, the default indeed feels weird, and apparently it's always been working like this.

I am able to change the direction with negative `moveSpeed` though:

```js
controller: {keyboard: {moveSpeed: -100}},
```

**Comment by Pessimistress** [comment]
That does not sound relevant to this issue. I suggest you create a CodeSandbox and open another thread in issues or discussions.
