### ISSUE TITLE
[Bug] The canvas id is not assigned since 8.5.0

### ISSUE THREAD

**Issue by Jesus89** [visgl/deck.gl#7210]
### Description

Testing pydeck (https://github.com/visgl/deck.gl/pull/7125#pullrequestreview-1081859744) I discovered that the canvas has no default id "deckgl-overlay".

I suspect it was introduced in https://github.com/visgl/deck.gl/pull/6010, so when the canvas exists, the id is not assigned.

### Expected Behavior

The default id "deckgl-overlay" should be assigned to the canvas, like in 8.4.

### Steps to Reproduce

It can be seen in [this example](https://deckgl.readthedocs.io/en/latest/gallery/custom_layer.html).

### Environment

- Framework version: deck.gl@8.5.0
- Browser: Chrome 104
- OS: Ubuntu 20.04.4 LTS

**Comment by Pessimistress** [comment]
This was an intentional change. What exactly is the bug here?

**Comment by Jesus89** [comment]
Pydeck expects the canvas to have an `id` called "deckgl-overlay". It uses that to apply the background color.

In [this example](https://deckgl.readthedocs.io/en/latest/gallery/custom_layer.html) the `css_background_color` does not correspond to the background in the map because the canvas has no `id`. If this is expected behavior, I guess it should be updated/fixed in pydeck.

**Comment by Pessimistress** [comment]
Given that pydeck created the canvas, it should take care of assigning the id too.
