### ISSUE TITLE
[Bug] DEFAULT_TEXTURE_PARAMETERS not being applied to resized layers in icon-manager

### ISSUE THREAD

**Issue by nrt9843** [visgl/deck.gl#7221]
### Description

In icon-layer/icon-manager, DEFAULT_TEXTURE_PARAMETERS are applied to the initial texture, however subsequent textures being created through `resizeTexture` do not copy these attributes from the original texture nor use these defaults. This is an issue when using auto packed icons, as new icons being added to the layer can cause the texture to be resized. In my case these missing parameters seem to cause aliasing issues on all displayed icons in the layer as soon as the texture gets resized.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

All attributes of the current texture are carried over to the new texture when `resizeTexture` is called.

### Steps to Reproduce

In a JS project using IconLayer with auto packed icons, add new elements to the layer with new icons (in my case 208 by 208 SVGs) until the 1024 pixel texture width is reached and the texture is resized. Observe that the icons have now become aliased.

(Or see that in `icon-manager.js`, the texture created by `resizeTexture` is not provided the parameters that are passed to the initial texture created bin `packIcons`).

### Environment

- Framework version: 8.8.9
- Browser: Firefox
- OS: Windows 10

**Comment by Pessimistress** [comment]
Fixed in v8.8.10.
