### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jwilliams-ecometrica** [visgl/deck.gl#7231]
### Description

Points not rendering when using geojson layer but the same layer works correctly if polygon data is provided instead. 

Hopefully I'm just missing something simple here.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

A point rendered on the map.

### Steps to Reproduce

This is using the following code.

const data = [
    {
        type: 'Feature',
        properties: {},
        geometry: {
            type: 'Point',
            coordinates: [-0.092010498046875, 51.6900106725452]
        }
    }
];

    const layers = [
        new GeoJsonLayer({
            id: 'geojson-layer',
            data: data,
            stroked: true,
            filled: true,
            lineWidthMinPixels: 2,
            opacity: 1,
            getLineColor: [255, 100, 100],
            getFillColor: [200, 160, 0, 180],
            radiusScale: 100000,
            getRadius: (d) => 10000000,
            pointType: 'circle'
        })
    ];

    return (
        <DeckGL
            initialViewState={INITIAL_VIEW_STATE}
            controller={true}
            layers={layers}
            style={{ width: 600, height: 400 }}>
            <Map
                mapStyle="mapbox://styles/mapbox/streets-v9"
                mapboxAccessToken={MAPBOX_ACCESS_TOKEN}
            />
        </DeckGL>
    );

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Your layer works fine as far as I can tell.

If you need help debugging your own application, create a Code Sandbox and use Discussions.

**Comment by jwilliams-ecometrica** [comment]
Did you test it with react-map-gl?
