### ISSUE TITLE
[Bug] H3HexagonLayer has gaps/displacement on some resolutions at specific map area

### ISSUE THREAD

**Issue by sup3rcow** [visgl/deck.gl#7251]
### Description

On left side we can see a bug when using **H3HexagonLayer**, and on the right side there is no bug when using **H3ClusterLayer**.

![image](https://user-images.githubusercontent.com/25765498/189080488-a7ef46d7-9469-4be1-b26c-0c92faf934e5.png)

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

I expected to see no gaps/displacement  when using H3HexagonLayer.

### Steps to Reproduce

Here is working codepan **example**
https://codepen.io/cowchicken/pen/rNvOvPO

To show/hide bug, you can change property value showBug.
if showBug is true, H3HexagonLayer is used
if showBug is false, H3ClusterLayeris used

### Environment

- Framework version: 8.8.8
- Browser: google chrome
- OS: windows 10

**Comment by Pessimistress** [comment]
This is a known limitation, See [highPrecision](https://deck.gl/docs/api-reference/geo-layers/h3-hexagon-layer#highprecision). Although the auto detection works most of the time, it may fail in some cases.

@nrabinowitz
