### ISSUE TITLE
[Bug] MVTLayer flickering on zoom when polygon fill uses alpha channel

### ISSUE THREAD

**Issue by DanielBoa** [visgl/deck.gl#7252]
### Description

When using the MVTLayer to render polygons which are partially transparent, they seem to "flicker" to fully opaque when zooming in and out or panning around. This happens inconsistently/randomly, but is fairly reproducible if you pan and move around the map "aggressively". 

I believe what may be happening is that when zooming in/out you see two copies of the same polygon from the two different zoom levels overlaid upon each other which results in them appearing more opaque. As for the same thing happening when panning maybe it's the same cause but with the buffered edge of a tile?

I also believe the longer the tile response times the more frequently you see the tearing/clipping.

Below is a video of what I'm describing, you can see it happen over the body of water. I've also linked to the codesandbox I used to capture this clip below.

https://user-images.githubusercontent.com/1169866/189081096-fc084d01-3c9c-465f-9b9c-eac0d6360184.mp4

Any help or pointers towards a potential solution/workaround would be greatly appreciated.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

No flickering when using the alpha channel of polygons in the MVTLayer.

### Steps to Reproduce

https://codesandbox.io/s/deckgl-mvt-zoom-flicker-minimal-example-yrg85d

### Environment

- Framework version: 8.8.5
- Browser: Chrome Version 104.0.5112.101 (Official Build) (arm64)
- OS: macOS Big Sur 11.1

**Comment by Pessimistress** [comment]
[refinementStrategy](https://deck.gl/docs/api-reference/geo-layers/tile-layer#refinementstrategy)

**Comment by DanielBoa** [comment]
> [refinementStrategy](https://deck.gl/docs/api-reference/geo-layers/tile-layer#refinementstrategy)

Somehow that passed me by! 🙏 @Pessimistress, fixed it in one!
