### ISSUE TITLE
HexagonLayer cannot get bar height

### ISSUE THREAD

**Issue by BirdyZhao** [visgl/deck.gl#7264]
### Description

Hi, I am using HexagonLayer in pydeck_chart. My data is a 3 column dataframe, ['lat','lon','number of clients']. I got the map and points successfully, but I am hoping they are par plot to show number of clients. The number of clients ranges from 1 to 50. But the map I got didn't show height differences. Here is my code.

>  st.pydeck_chart(pdk.Deck(
        map_style=None,
        initial_view_state=pdk.ViewState(
         latitude= np.mean(zip_all['lat']),
         longitude= np.mean(zip_all['lon']),
         zoom=11,
         pitch=50,
     ),
     layers=[
          pdk.Layer(
            'HexagonLayer',
            data=zip_all,
            get_position=["lon","lat"],
            radius=200,
            elevation_scale=50,
            elevation_range=[0, 100],
            pickable=True,
            extruded=True,
            auto_highlight=True,
         )
         ]
 ))

I am eager for the solution. Thanks for your help. #[Bug] 

### Flavors

- [ ] React
- [X] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Could you please help me find the problems in my code?

### Steps to Reproduce

A sample of your code

### Environment

- Framework version:deck.gl@8.3.0
- Browser:Chrome 78.0
- OS: iOS 15.1

**Comment by Pessimistress** [comment]
Issues are for reporting bugs in the library. Please use Discussions to get help.
