### ISSUE TITLE
[Bug] Marker offset outside map when crossing longitude 180 -> -180

### ISSUE THREAD

**Issue by fnatiq** [visgl/deck.gl#7291]
### Description

I have my deckgl map zoomed out to see most of the globe, and I have a `<Marker />` located somewhere in Indonesia (lat -3.8, lon 102), where my map is initially centered at. As I pan the map horizontally (dragging my mouse left i.e. longitude increasing), when the longitude cross somewhere in the middle of the Pacific Ocean, the centre of the map's longitude jumps to -180, and my points disappear. I debugged and have the NW / SE points plotted based on the bounds calculated by `new WebMercatorViewport().getBounds()`, and noticed that the EW longitudes jump from to (272, 61) to (-69, -280). Should these be within the ranges of (-180, 180)? I expect to see my markers on the map while the locations are still there, as I noticed that the points are all the way to the right outside the view of the visible map.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Expect to see the marker remain on the map while in view

### Steps to Reproduce

See description

### Environment

- Framework version: deck.gl@^8.6.0
- Browser: Chrome 89.0
- OS: Windows 10

**Comment by Pessimistress** [comment]
[wrapLongitude](https://deck.gl/docs/api-reference/core/layer#wraplongitude)
[MapView:repeat](https://deck.gl/docs/api-reference/core/map-view#repeat)
