### ISSUE TITLE
[Bug]import { MapboxLayer } from '@deck.gl/mapbox' error

### ISSUE THREAD

**Issue by huihui-gao** [visgl/deck.gl#7292]
### Description

 import { MapboxLayer } from '@deck.gl/mapbox' error  in my  ts file

The declaration file for module '@deck.gl/mapbox' could not be found.“/node_modules/.pnpm/@deck.gl+mapbox@8.8.11/node_modules/@deck.gl/mapbox/dist/es5/index.js”Implicitly owns type "any".
  Try using `npm i --save-dev @types/deck.gl__mapbox` if it exists, or add a new declaration (.d.ts) file ts containing `declare module '@deck.gl/mapbox';` (7016)

i tried 
    npm i    
    npm i --save-dev @types/deck.gl__mapbox

I looked at the @deck.gl/mapbox source it's written in typescript，

But I can't directly import 

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

 import { MapboxLayer } from '@deck.gl/mapbox' success 

like importing other typescript packages

### Steps to Reproduce

npm i @deck.gl/mapbox
create ts file
 import { MapboxLayer } from '@deck.gl/mapbox'

### Environment

- Framework version:"@deck.gl/mapbox": "^8.8.11",
- typescript version 4.8.3

**Comment by Pessimistress** [comment]
https://deck.gl/docs/get-started/using-with-typescript
