### ISSUE TITLE
[Feat] Update IconLayer example to latest react-map-gl version

### ISSUE THREAD

**Issue by tranquanghuy0801** [visgl/deck.gl#7293]
### Target Use Case

Our developers can reuse the example IconLayer project code in our own projects without having to downgrade `react-map-gl` library.

Note: I have the issue of not importing `StaticMap` successfully as it is not available in the latest version of `react-map-gl`

### Proposal

The project directory: https://github.com/visgl/deck.gl/tree/master/examples/website/icon
Current react-mapbox-gl: `5.0.0`
Target version to update: `7.0.0`

Update all written, imported functions to match the latest version

**Comment by felixpalmer** [comment]
Have you tried importing `Map` instead, as per the upgrade guide? https://github.com/visgl/react-map-gl/blob/156bce42464adf02635b90b289f318523c1431d3/docs/upgrade-guide.md#module-exports

**Comment by Pessimistress** [comment]
Examples on master are now using the latest version.
