### ISSUE TITLE
Error: mvt loader - no parser found and worker is disabled - Electron app

### ISSUE THREAD

**Issue by Ali-Baker** [visgl/deck.gl#7299]
### Description

```
tile-layer.ts:32 Error: mvt loader - no parser found and worker is disabled
    at parseWithLoader (parse.ts:100:1)
    at async parse (parse.ts:58:1)
    at async load (load.ts:48:1)
    at async Tile2DHeader._loadData (tile-2d-header.ts:107:1)
```

![image](https://user-images.githubusercontent.com/30794075/192733348-2363730f-741e-4043-9422-c54a1b304041.png)

I am getting this error with this piece of code using `electron`. It works fine on Chrome.

```
new CartoLayer({
        index: 'NDVI',
        id: `ColorLayer${Math.random()}`,
        type: MAP_TYPES.TILESET,
        connection: env.process.connection,
        data: `env.process.project.${tableName}`,
        lineWidthScale: 0.2,
        getLineColor: [255, 255, 255, 100],
}),
```

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

electron version `19.0.4`

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
https://deck.gl/docs/developer-guide/loading-data#loaders-and-web-workers
