### ISSUE TITLE
[Bug] Custom Class extending MapController

### ISSUE THREAD

**Issue by adriangonzalezrodrigo** [visgl/deck.gl#7313]
### Description

I want to have a class to add some custom behavior because I need to handle click and mousemove events on the map.

I have a class like this

```
import { MapController } from '@deck.gl/core';

export interface ControllerManager {
  onEvent: (e: GestureEvent) => void;
}

export interface ControllerProps {
  controllerManager: ControllerManager ;
}

export const handleGestureEvent = (controllerManager: ControllerManager , event: any): void => {
  controllerManager.onEvent({
    type: event.type,
    center: {
      x: Number(event.center.x),
      y: Number(event.center.y),
    },
    offsetCenter: {
      x: Number(event.offsetCenter.x),
      y: Number(event.offsetCenter.y),
    },
    target: event.target,
    srcEvent: event.srcEvent,
  });
};

export class GestureController extends MapController {
  private controllerManager: ControllerManager;
  public events: MapEvents[] = ['click', 'mousemove'];
  public myEvents: MapEvents[] = ['click', 'mousemove'];

  constructor(props: ControllerProps) {
    super(props);
    // Here I also pass a controller manager instance to handle the event
    this.controllerManager= props.controllerManager;
  }

  public handleEvent(event: any): any {
    if (this.myEvents?.includes(event.type)) {
      handleGestureEvent(this.controllerManager, event);
    }
    super.handleEvent(event);
  }
}
```

the code above works until the version of deck gl 8.4 but from the version 8.5 and above it doesn't work.

Config on DeckGL
```
<DeckGL
        ref={deckRef}
        controller={{ type: GestureController, dragRotate: checked3DMode, doubleClickZoom: false, gestureManager: gestureManagerRef.current }}
        ....
>
```

I also have tried something similar to:
```
<DeckGL
        ref={deckRef}
        controller={new GestureController({ dragRotate: checked3DMode, doubleClickZoom: false, gestureManager: gestureManagerRef.current  })}
        ....
>
```
but with the same error.

And when I try to pass the custom controller I have the error:
TypeError: Class constructor MapController cannot be invoked without 'new'

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The custom MapController should work.

### Steps to Reproduce

    "@deck.gl/core": "8.6.0",
    "@deck.gl/extensions": "8.6.0",
    "@deck.gl/geo-layers": "8.6.0",
    "@deck.gl/layers": "8.6.0",
    "@deck.gl/mapbox": "8.6.0",
    "@deck.gl/mesh-layers": "8.6.0",
    "@deck.gl/react": "8.6.0",
    "react-map-gl": "7.0.19",

### Environment

- Framework version: deck.gl@8.6.0
- Browser: Chrome 106
- OS: Windows

**Comment by Pessimistress** [comment]
The error occurs because you are mixing es5 and es6 syntax in the final bundle. Either avoid transpiling your own code to es5, or include `node_modules` in your Babel config. See [breaking change in 8.5](https://deck.gl/docs/upgrade-guide#transpilation).
