### ISSUE TITLE
[Bug] Inconsistent line height in WebMercatorView

### ISSUE THREAD

**Issue by 4nthonylin** [visgl/deck.gl#7316]
### Description

When drawing lines with a non-zero height, the height of the lines seems to be fixed to a single height above the map plane. However, it seems to depend on the projected height of first point.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/4007580/194247033-1d2d01f4-bc73-46e4-9a65-3bd1dd8f708e.png">

Line layer with following data:
```
data: [
  // red line
  {
    start: [-120, 60, 550000],
    end: [-40, 75, 550000]
  },
  // green line
  {
    start: [-40, 75, 550000],
    end: [-120, 60, 550000]
  }
],
```

Note that the red line and green line have different "projected" heights on the viewport even though they have the same altitude. I'm still quite new to the code base but couldn't figure out what it could be. Guessing it's related to the line-layer vertex shader and is not properly interpolating the line segments with the commonspace height.

Will continue digging around but wondering if anyone else with better glsl knowledge can shed some insights. 

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Expect the lines to be interpolated between the projected height and the order of the start/end should not impact the rendering.

Although thinking it might be cleaner to add a new mode to project the height consistently. A constant altitude over the map plane instead of projecting the altitude to be farther away. 

### Steps to Reproduce

https://codepen.io/4nthonylin/pen/mdLGbEG

### Environment

- Framework version: https://unpkg.com/deck.gl@latest/dist.min.js
- Browser: Edge Version 106.0.1370.34
- OS: Windows/MacOS/Linux

**Comment by 4nthonylin** [comment]
Just wanted to add that globe view has the correct behavior.
<img width="507" alt="image" src="https://user-images.githubusercontent.com/4007580/194249328-da9f5fd2-bed2-40e6-a746-3908545afe02.png">
Only see one line since it overlaps the first line.

**Comment by Pessimistress** [comment]
Fixed in v8.8.13.

**Comment by 4nthonylin** [comment]
Thanks for the quick fix!

**Comment by 4nthonylin** [comment]
Confirmed codepen now works
<img width="567" alt="image" src="https://user-images.githubusercontent.com/4007580/195257404-56420127-5bd1-4640-b451-684edd5a5fbb.png">
