### ISSUE TITLE
[Bug] Vite Super expression must either be null or a function

### ISSUE THREAD

**Issue by convers39** [visgl/deck.gl#7353]
### Description

When I migrate from create-react-app to vite, I encountered the issue that the application failed due to this bug:

<img width="777" alt="image" src="https://user-images.githubusercontent.com/42597395/197136387-3cc16cf4-2193-4da0-b1ec-0c9581b8a2c9.png">

```
Super expression must either be null or a function
```

It points to this `buffer.js` file.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/42597395/197158938-c21944f5-d60f-4960-b6c0-848764f36e0f.png">

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

render the page without error

### Steps to Reproduce

WIP

### Environment

- Framework version: 8.8.14
- Browser: 106.0.5249.103 (Official Build) (arm64)
- OS: MacOS 12.5

**Comment by Pessimistress** [comment]
This was resolved as of #6134, make sure your installation of luma.gl is up to date.
