### ISSUE TITLE
[Doc] `beforeId` prop documented on `Layer` and within mapbox sub-module

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#7359]
### Link

https://deck.gl/docs/api-reference/core/layer

### Description

Our interleaved mapbox implementation supports placing deck layers before mapbox layers by setting a `beforeId` layer prop. The id is expected to be a [basemap layer id](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addlayer), like `land`. I noticed this appears to be undocumented behavior. It's implemented [here](https://github.com/visgl/deck.gl/blob/master/modules/mapbox/src/resolve-layers.ts#L50), but there's no mention of the prop in our [layer docs](https://deck.gl/docs/api-reference/core/layer).

**Comment by Pessimistress** [comment]
`beforeId` is not a base Layer class prop. It is only respected when used with `MapboxOverlay`, which is documented [here](https://deck.gl/docs/api-reference/mapbox/mapbox-overlay).

**Comment by chrisgervang** [comment]
Ok, that makes sense. In addition to the code example on MapboxOverlay, I think it should be called out in the text somewhere, and then also documented on the MapboxLayer page.

Could do into the "props" breakdown, and a section for Layer Ordering.

**Comment by chrisgervang** [comment]
I see it's also mentioned in the MapboxOverlay constructor section, so I'll rephrase to its just not apparent enough. What do you think of adding "Layer Ordering" section in remarks, and/or calling it out at the top of the Interleaved section?
