### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ctrebbau** [visgl/deck.gl#7363]
### Description

`yarn bootstrap` exits with an `error Command failed with exit code 1` trying to build `pydeck/julia-pycall-binding` branch
(is this the right place to ask this?)

### Flavors

- [ ] React
- [X] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Being able to call pydeck from Julia's PyCall

### Steps to Reproduce

I am trying to follow this tutorial [https://deloitteoptimalreality.github.io/LightOSM.jl/notebooks/tutorial/](url). As explained there I've cloned the repo where `Pkg.dir("PyCall")` points to but `yarn bootstrap` fails with code mentioned above. I've tried
rm -rf node_modules
yarn cache clean
yarn
and then yarn bootstrap, to no avail

Also `yard run test` fails with 85 `error  Unable to resolve path to module '@deck.gl/core'  import/no-unresolved`

### Environment

- Framework version:
- Browser:
- OS: MacOS

**Comment by Pessimistress** [comment]
There is no such branch in this repo. Please go ask in the fork that you cloned.
