### ISSUE TITLE
[Bug] GeoJSON Layer should probably tolerate null geometries

### ISSUE THREAD

**Issue by tmcw** [visgl/deck.gl#7367]
### Description

The GeoJSON layer has a check that confirms that each feature has a geometry:

https://github.com/visgl/deck.gl/blob/c0b508f246014b2bd655de060066757ad8622261/modules/layers/src/geojson-layer/geojson.ts#L94

It also is documented as saying that input data should be valid geojson: https://deck.gl/docs/api-reference/layers/geojson-layer#remarks

This is in conflict - the [geometry member of a feature](https://www.rfc-editor.org/rfc/rfc7946#section-3.2) can be null, according to the official specification.

The behavior here should probably be to `continue` instead of throwing with an assertion.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Using GeoJSON with null geometry values should work

### Steps to Reproduce

Use GeoJSON with null geometry values.

### Environment

- Framework version: deck.gl@8
- Browser: Chrome
- OS: macOS

**Comment by Pessimistress** [comment]
Fixed in 8.8.17
