### ISSUE TITLE
[Bug] MapView padding prop not respected in child react-map-gl Map

### ISSUE THREAD

**Issue by mfitzer** [visgl/deck.gl#7382]
### Description

I am trying to set a padding value on the deck-gl MapView and have that same padding also apply to the child react-map-gl Map component. I have tried setting the padding only on the MapView, on the MapView and the Map, and only on the Map. In every one of those scenarios, the react-map-gl Map's padding is never changed from the default. Both components support the padding prop and work correctly by themselves, but when brought together, the react-map-gl padding is no longer applied. This results in the deck canvas getting out of alignment with the Mapbox map.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

I expect the deck-gl MapView's padding to be replicated in the react-map-gl Map component. This should work either by the MapView automatically setting the padding prop on the react-map-gl Map or by manually setting the padding prop on both components to match.

### Steps to Reproduce

This codesandbox shows react-map-gl with padding working as expected in an independent application: [react-map-gl-padding-example](https://codesandbox.io/s/react-map-gl-padding-example-lg4073?file=/src/index.js:112-151)

This codesandbox shows the integration issue between deck-gl's MapView padding and react-map-gl's Map padding: [deck-gl-react-map-gl-padding-bug](https://codesandbox.io/s/deck-gl-react-map-gl-padding-bug-ptkq2v?file=/src/App.js)
- **Note:** I could not get the Mapbox map to work in this sandbox without a mapbox token, so you will have to provide one to see the example working.
- To highlight the issue, try rotating the map, the deck layer does not rotate in sync with the Mapbox map

### Environment

- **Framework version:** deck.gl 8.8.17
- **Browser:** Chrome 107.0.5304.88
- **OS:** Windows 10 Home 21H2

**Comment by Pessimistress** [comment]
This issue is specific to react-map-gl v7.0 (examples in this repo use v5). I will put up a fix.

**Comment by Pessimistress** [comment]
Fixed in v8.8.18.
