### ISSUE TITLE
Unable to zoom in to the Americas with longitude adjusted to cross the Pacific

### ISSUE THREAD

**Issue by EmilyFitzgerald** [visgl/deck.gl#7389]
### Description

I've got a map where I have added 360 to the longitudes, in order to have the arcs and the trips travel across the Pacific (it's showing movement from the US to Australia and South East Asia). I've added this as has been recommended in other issue requests. 

However, on doing this, when I try and zoom in to the United States, the arcs or trips move across to the next map in the wrap/loop, and so I can't zoom in on the map. wrapLongitude is set to false. 

Short video to show what is happening:
[https://user-images.githubusercontent.com/44518869/177279237-7b22769e-ebc9-4c6c-8377-56b1cd04504c.mp4](https://user-images.githubusercontent.com/44518869/177279237-7b22769e-ebc9-4c6c-8377-56b1cd04504c.mp4)

Is there any advice on how to stop this happening? Either a bounding box to keep the map within, or some other fix?

I noted this in a comment on another issue a while back, but thought it better to raise as a new issue. 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Expect to be able to zoom in on all areas of the map and still see the trip layer

### Steps to Reproduce

import React, { useState } from "react";
import "mapbox-gl/dist/mapbox-gl.css";
import Map from "react-map-gl";
import DeckGL from "@deck.gl/react";
import { ScatterplotLayer, PathLayer, ArcLayer } from "@deck.gl/layers";
import { TripsLayer } from "@deck.gl/geo-layers";
import exampleData from "../data/example.json";

const accessToken = process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN;

function MyMap(props) {
  const [initialViewState, setInitialViewState] = useState({
    longitude: 180,
    latitude: 0,
    zoom: 1.5,
    minZoom: 1.5,
    maxZoom: 16,
    pitch: 5,
    bearing: 0,
  });

  const tripsLayer = new TripsLayer({
    id: "trips-layer",
    data: exampleData,
    pickable: true,
    getPath: (d) => d.waypoints.map((p) => p.coordinates),
    getTimestamps: (d) => d.waypoints.map((p) => p.timestamp),
    getColor: (d) => d.map_color,
    wrapLongitude: false,
    opacity: 0.6,
    widthMinPixels: 8,
    jointRounded: true,
    capRounded: true,
    fadeTrail: true,
    trailLength: 0.8,
    currentTime: props.year,
    visible: props.trips,
  });

  return (
    <div
      className="d-flex justify-content-center"
      style={{ paddingTop: "0.5em" }}
    >
      <div
        className="col-12 border"
        style={{ height: "90vh", width: "95vw", position: "relative" }}
      >
        <DeckGL
          controller={true}
          initialViewState={initialViewState}
          layers={[tripsLayer]}
        >
          <Map
            reuseMaps
            mapboxAccessToken={accessToken}
            mapStyle={"mapbox://styles/mapbox/light-v10"}
            preventStyleDiffing={true}
          />
        </DeckGL>
      </div>
    </div>
  );
}

### Environment

- Framework version: deck.gl@8.7.11
- Browser: Google Chrome
- OS: Mac

**Comment by Pessimistress** [comment]
[repeat](https://deck.gl/docs/api-reference/core/map-view#repeat)

**Comment by EmilyFitzgerald** [comment]
> [repeat](https://deck.gl/docs/api-reference/core/map-view#repeat)

I've just tried repeat and it does not solve the issue, the trip layer moves to the next map meaning I cannot zoom in on the United States regardless of if repeat is set to true or false.
