### ISSUE TITLE
[Bug] TileLayer doesn't render when jumping to zoom 0

### ISSUE THREAD

**Issue by oscarnc** [visgl/deck.gl#7396]
### Description

My TileLayer sometimes doesn't render when changing viewState from a high zoom to zoom 0.
I think it is being caused by the cache resize removing the zoom 0 tiles before they become visible: https://github.com/visgl/deck.gl/blob/8.8-release/modules/geo-layers/src/tile-layer/tileset-2d.ts#L420

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The layer should be visible when zoomed out.

### Steps to Reproduce

[Codepen link](https://codepen.io/oscarnc/pen/zYaZOyq?editors=0011)

Bring up the console and run `setZoom(0)` - the layer is not rendered. However, running `setZoom(1)` followed by `setZoom(0)` shows the layer correctly.

### Environment

- Framework version: deck.gl@8.8.17
- Browser: Chromium 107.0.5304.87
- OS: Arch Linux

**Comment by Pessimistress** [comment]
Thanks for reporting. This is fixed in v8.8.19.
