### ISSUE TITLE
Spatial query on MVT layer on given location to select a feature

### ISSUE THREAD

**Issue by gireeshbhogireddy** [visgl/deck.gl#7406]
### Target Use Case

I want to select the building of MVT layer based on given location. Real use case is Person represented as iconlayer will be moving across the buildings and all the buildings which are intersected by the person should get selected.

### Proposal

Icon moving across the buildings and all the buildings which are intersected by him should get selected.

**Comment by Pessimistress** [comment]
Not sure what feature is being proposed here. Please use discussions if you need help with implementing a specific use case.
