### ISSUE TITLE
Mouse hover should work on Iconlayer even if icon is inside a 3D building

### ISSUE THREAD

**Issue by gireeshbhogireddy** [visgl/deck.gl#7407]
### Target Use Case

Icons that are inside a 3D transparent building should show their information even when they are inside the 3D transparent building. 

### Proposal

Something like Z- index should be enabled to iconlayer so that icon layer can be hovered and clicked even if it is inside the building.

**Comment by Pessimistress** [comment]
Default hover only triggers on the top most object. If you don't want to pick the building then set the building layer's `pickable` to `false`.
