### ISSUE TITLE
Ripple effect for 3D sphere IconLayer

### ISSUE THREAD

**Issue by gireeshbhogireddy** [visgl/deck.gl#7419]
### Target Use Case

User who represented as 3D sphere icon of IconLayer should have ripple effect or animation so that it will be known he is in danger

### Proposal

User who represented as 3D sphere icon of IconLayer should have ripple effect or animation so that it will be known he is in danger

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/issues/4872
