### ISSUE TITLE
[mapbox] Set viewState when interleaved?

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#7423]
According to the MapboxOverlay [docs](https://deck.gl/docs/api-reference/mapbox/mapbox-overlay#constructor-1), `viewState` doesn't need to be set because its managed internally. 

But when interleaved, viewState isn't set as it is when overlaid.
https://github.com/visgl/deck.gl/blob/1342a961ba9ce320ddd0eebe1cd53a021c3c8382/modules/mapbox/src/mapbox-overlay.ts#L93-L95

Is there a reason for this, or should viewState also be set internally when interleaved?

Currently, when I don't set it myself there is an error thrown about the missing viewState.

**Comment by Pessimistress** [comment]
In interleaved mode, view states are set when layers get rendered: https://github.com/visgl/deck.gl/blob/master/modules/mapbox/src/deck-utils.ts#L111

**Comment by chrisgervang** [comment]
Oh ok, I see that. Following up in #7458 with additional observations.
