### ISSUE TITLE
[Bug] Fast clicking is not registered

### ISSUE THREAD

**Issue by juneidy** [visgl/deck.gl#7425]
### Description

Deck.gl drops all previous click within 300ms even after the cursor moved.

See the recording:

https://user-images.githubusercontent.com/13762553/202627704-1547f7e7-8de8-4b46-90d3-8d9c42706a15.mp4

I have outputted the console on the `anytap` event. But deck's own `onClick` is only called once.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

All clicks should be registered like in the recording:

https://user-images.githubusercontent.com/13762553/202627890-df86a3c0-cacd-4fa3-97f3-e293691f8249.mp4

### Steps to Reproduce

Provide `onClick` callback to Deck and quickly (within 300ms) click different place in the map. Only one click is fired.

### Environment

- Framework version: deck.gl@8.8.10
- Browser: Chromium 107.0.5304.110
- OS: Archlinux

**Comment by Pessimistress** [comment]
There is an intentional delay after click to distinguish single click from double clicks (which triggers two anyclick events and zero click events). If you don't want that delay you can disable double click by setting `controller: {doubleClickZoom: false}`.

**Comment by juneidy** [comment]
Understood. I would still like to be able to perform double click.

Would it be sensible to short circuit the 300ms if the cursor or taps has moved by more than (the threshold of) 10px?

That way, a user can still perform a succession of clicks on 3 different location quickly.

**Comment by Pessimistress** [comment]
I don't think we should change how `onClick` behaves because of the reason stated above. However, we could possibly support additional callbacks on custom event types, in this case `anyclick`. Would that solve your problem?

To test it with the current release, you could try this in your app:

```js
import {EVENTS} from '@deck.gl/core/dist/esm/lib/constants';

EVENTS['anyclick'] = {handler: 'onAnyClick'};
```
