### ISSUE TITLE
3D Labels of textlayer are getting hidden inside 3D building

### ISSUE THREAD

**Issue by gireeshbhogireddy** [visgl/deck.gl#7428]
### Target Use Case

I want to show floor level as labels of 3D building. I am able to add labels but they are hidden if I move map in specific angle. Attaching the screenshot.

<img width="786" alt="pic" src="https://user-images.githubusercontent.com/54057993/202764483-e9f662ea-7ce9-439e-91af-c11d29d611e0.png">

### Proposal

I want to show floor level as labels of 3D building. I am able to add labels but they are hidden if I move map in specific angle. Attaching the screenshot.

**Comment by Pessimistress** [comment]
Please use discussions to get help with a specific implementation.

**Comment by yaras-phoenix** [comment]
Is this the same I experience here?
![image](https://github.com/visgl/deck.gl/assets/37367584/a88cb262-3b80-4506-9dfb-25ef2daaea7c)
I'm publishing 3d objects and textlayer from deck.gl demos and I see no way to render Text labels on top of 3d data. Not possible as of now?

**Comment by ibgreen** [comment]
Recommend opening a discussion item if you want to discuss more. Generally deck maintainers do not respond to comments on old closed tickets.

**Comment by yaras-phoenix** [comment]
> Recommend opening a discussion item if you want to discuss more. Generally deck maintainers do not respond to comments on old closed tickets.

Thanks! Will open and a new one with a codepen.
