### ISSUE TITLE
Not able to tilt the map horizontal view (0 degree camera view) in deck GL

### ISSUE THREAD

**Issue by gireeshbhogireddy** [visgl/deck.gl#7429]
### Target Use Case

I am trying to tilt the map horizontally(0 degree camera view) but unable to do in deck gl map. In other frameworks like cesium and arcgis I am able to tilt and see horizontal, but not in deck gl. 

### Proposal

I am trying to tilt the map horizontally but unable to do in deck gl map. In other frameworks like cesium and arcgis I am able to tilt and see horizontal, but not in deck gl.

**Comment by Pessimistress** [comment]
[maxPitch](https://deck.gl/docs/api-reference/core/map-view#view-state)
