### ISSUE TITLE
Is it possible to resize text layer size based on map distance

### ISSUE THREAD

**Issue by gireeshbhogireddy** [visgl/deck.gl#7436]
### Target Use Case

I want text layer size should be decreased when map camera is far from the text layer and text layer size to be increased if map camera position is close to the text.

### Proposal

I want text layer size should be decreased when map camera is far from the text layer and text layer size to be increased if map camera position is close to the text.

**Comment by Pessimistress** [comment]
@gireeshbhogireddy  I have informed you multiple times over the last few days that you should use Discussions for "how do I..." questions. You will be banned from creating issues if you do it again.
