### ISSUE TITLE
[Bug] TextLayer does not support RTL languages

### ISSUE THREAD

**Issue by aaranadev** [visgl/deck.gl#7448]
### Description

I've encountered a bug with RTL support in both the basemap and the text layer.

When the text displayed is in RTL the mapstyle doesn't currently have the direction, here there is a test with Gmaps where we can see that the text in **arabic** has the wrong direction in deckGL.

On the left deckgl and on the right gmaps

<img width="716" alt="Screenshot 2022-11-23 at 10 39 44 AM" src="https://user-images.githubusercontent.com/11427698/203517328-758e4cca-b5dc-411b-b67f-55f4122ac086.png">

With the TextLayer happens the same, the data introduced is written in RTL and is shown in LTR.

<img width="1013" alt="Screenshot 2022-11-23 at 10 55 37 AM" src="https://user-images.githubusercontent.com/11427698/203517813-8cbe795e-ee3f-4e5f-8c87-eb7abf8e0d72.png">

The `characterSet` prop is settled in 'auto'

### Expected Behavior

See the text in the correct direction.

<img width="1100" alt="Screenshot 2022-11-23 at 10 58 08 AM" src="https://user-images.githubusercontent.com/11427698/203518317-a1edac8e-3262-41cf-a9d8-ea0e46499a70.png">

### Steps to Reproduce

To reproduce the issue, please run the following CodePen: [https://codepen.io/aaranadev/pen/RwJMRNe](https://codepen.io/aaranadev/pen/RwJMRNe).

### Environment

- Framework version: 8.8.20
- Browser: Chrome 107
- OS: All

**Comment by Pessimistress** [comment]
https://github.com/visgl/deck.gl/discussions/6302

**Comment by aaranadev** [comment]
Great! Thanks for the information!
