### ISSUE TITLE
Highlighting or Selecting 3D building of MVT Layer not working as expected

### ISSUE THREAD

**Issue by gireeshbhogireddy** [visgl/deck.gl#7461]
### Description

I am using MVT layer class for showing buildings in 3D. I was expecting to highlight the building on mouse hover over the building. It is working fine for small buildings but for tall buildings when I tilt the map it is working fine till a certain angle but not selecting when I change the map pitch towards 90 degrees. Sometimes selecting the buildings behind the hovered building. 
[https://codepen.io/gireesh-bhogireddy/pen/eYKPReX?editors=0011]

Also when I tried with geojson Layer class of geojson layer it is working as expected, able to highlight building irrespective of the pitch.

- 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

 Irrespective of tilt, 3D Building should get selected when hovering over it.

### Steps to Reproduce

Below is the codepen link where I have implemented the behavior. Change the tilt of map and mouse hover on buildings to observe the behavior.
[https://codepen.io/gireesh-bhogireddy/pen/eYKPReX?editors=0011](url)

### Environment

- Framework version:deck.gl@8.3.0
- Browser: Chrome 78.0
- OS:Windows 10

**Comment by Pessimistress** [comment]
Can you attach a video of what it looks like on your end?

**Comment by gireeshbhogireddy** [comment]
Below is the video link and in this if you observe the tall building is not getting highlighted on mouse hover instead the buildings behind the tall building are getting selected. I suspect it is considering 2D geometry for highlighting but unable to conclude.

https://user-images.githubusercontent.com/54057993/205320619-7bc8fe5b-da99-4871-ae2f-653ba77a113b.mp4

**Comment by Pessimistress** [comment]
Unfortunately I cannot reproduce the issue on your codepen.

**Comment by gireeshbhogireddy** [comment]
I have updated the codepen code so that the initial view will be at the same tall building which was there in the video. After opening the codepen example only do mouse hover and don't do panning or tilting, then you will see the issue on the tall building at the center. Let me know if you still unable to reproduce.
[https://codepen.io/gireesh-bhogireddy/pen/eYKPReX?editors=0011](url)

**Comment by Lyeeedar** [comment]
This is the same behaviour I was seeing in this issue https://github.com/visgl/deck.gl/issues/7237

**Comment by Pessimistress** [comment]
@gireeshbhogireddy This is not a bug, though confusing (and poorly documented). For better performance, TileLayer/MVTLayer only considers a subset of the tiles during picking. By default, it treats all tiles as flat. Since you render extruded buildings, a tile that does not overlap with the picking pixel in 2D may overlap with it in 3D. You will need to provide the layer with additional information for it to cull the tiles correctly.

If you add `zRange: [0, 1000]` to your MVTLayer you can see the issue go away. This value should correspond to the max height of the buildings.

@Lyeeedar I do not believe it's the same as your issue. You need to provide steps to reproduce yours.

**Comment by gireeshbhogireddy** [comment]
Thanks @Pessimistress for the explanation and solution. It works for me

**Comment by Lyeeedar** [comment]
@Pessimistress I was actually using TileLayer with GeoJson layers inside (potentially why I couldn't repro when I extracted a single object into a standalone GeoJson layer), so potentially it is the same issue. Currently awaiting the release of 8.9 to test this fix though (adding zRange).

**Comment by Pessimistress** [comment]
zRange is an existing prop in the current release.
