### ISSUE TITLE
[Bug] Uint32Array PolygonLayer vertices no longer work

### ISSUE THREAD

**Issue by keller-mark** [visgl/deck.gl#7498]
### Description

In v8.6.7, PolygonLayer's getPolygon would accept an array of Uint32Arrays representing polygon vertices.

In v8.8.20, this no longer works.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Expect to see rendered polygons regardless of whether vertices are returned from getPolygon as `Array` or `Uint32Array`.

### Steps to Reproduce

- works: [DeckGL PolygonLayer in v8.6.7 with Uint32Array](https://codepen.io/kellermark/pen/RwJOGBr)
- works: [DeckGL PolygonLayer in v8.8.20 with plain Array](https://codepen.io/kellermark/pen/wvXZzEd)
- bug: [DeckGL PolygonLayer in v8.8.20 with Uint32Array](https://codepen.io/kellermark/pen/qBKwayz)

### Environment

- Framework version: deck.gl@8.8.20
- Browser: Firefox Developer Edition 108.0b9 (64-bit)
- OS: macOS Big Sur

**Comment by keller-mark** [comment]
Thanks, I see, I did not realize that.
The benefit has just been that we load the polygon data from a [Zarr NestedArray](https://guido.io/zarr.js/#/getting-started/nested-arrays), so using a plain `Array` or a flat TypedArray requires some data transformation whereas using the nested TypedArrays does not (we can pass around the same object we receive from Zarr).

**Comment by Pessimistress** [comment]
After a quick look at this library, I suspect the underlying data is still stored in a flat array (see "raw arrays").
