### ISSUE TITLE
[Bug] Too many objects returned by pickMultipleObjects when using PathLayer with binary data

### ISSUE THREAD

**Issue by harveylee** [visgl/deck.gl#7504]
### Description

When I call pickMultipleObjects on a position over a PathLayer that has been created using binary data, the number of PickingInfo objects returned is whatever the max. depth is set to.

This doesn't occur when for a PathLayer created with regular object data.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Only one PickingInfo object returned per PathLayer regardless of using binary or object data.

### Steps to Reproduce

https://stackblitz.com/edit/deckgl-demo-dj2lrj?file=index.js

1. Hover over the red path, the console prints that 10 objects are returned from pickMultipleObjects.
2. Hover over the blue path, the console prints that 1 object is returned from pickMultipleObjects. 

In both cases only one path is represented so the console should print 1.

### Environment

- Framework version: deck.gl@8.8.20
- Browser: Chrome 108.0.5359.73 (Official Build) (64-bit)
- OS: Windows 11

**Comment by Pessimistress** [comment]
Fixed in v8.8.21.
