### ISSUE TITLE
[Bug] DataFilterExtension very poor performance 

### ISSUE THREAD

**Issue by AnthonyWhitaker** [visgl/deck.gl#7509]
### Description

Extremely poor performance (3-4 FPS) when using the data-filter extension on a PolygonLayer where the geometry *would* render hundreds of overlapping fullscreen polygons. Even if the majority, or all, of the polygons are filtered - the fragment shader must run countless times only to `discard` all of the fragments.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Improved performance.

### Steps to Reproduce

Create a geojson with 100s of whole world quads and attempt to render using the data-filter.

### Environment

- Framework version: deck.gl@8.8.6
- Browser: Chrome 108.0.5358.94 (arm64)
- OS: Mac Ventura 13.0.1 (Apple M1 Max) 64 GB RAM

**Comment by AnthonyWhitaker** [comment]
To avoid this, we move the vertex shaders' output beyond clipspace and to a single degenerate point at (-2, -2, -2). With only this four-line change, we saw the framerate jump back to 120 FPS for the same geometry.

**Comment by Pessimistress** [comment]
Thank you. Fix published in v8.8.21.
