### ISSUE TITLE
[Feat] add resolution to elevationDecoder object to replace color scalers

### ISSUE THREAD

**Issue by AndrewAnnex** [visgl/deck.gl#7514]
### Target Use Case

Currently the deck.gl api exposes an `elevationDecoder` object that takes 3 scaler values for each color channel and an offset parameter. This means 4 parameters are required to define an elevationDecoder.

### Proposal

Instead, how about updating the elevationDecoder object to only take two parameters, the `offset` (unchanged) and `resolution` (new floating point number). This would take the place of individually defining scalers for each color channel (which is just 256^2 and 256 multiplied each by 0.1 from the example in the docs) and would result in only two parameters needing to be defined by the user if the order of the bands and the style of quantization remains the same. The bScaler is already the value of the resolution in fact. Alternatively, `resolution` could be added as an optional parameter, and if present whatever logic in deck.gl actually converts the RGB tile to a mesh could switch to use it rather than the color scalers. 

The advantages are a slight simplification of the decoder object and parameters that have more physical meaning. Disadvantages could be the number of additional floating point computations are needed to define the scaler values, but that's got to happen somewhere anyways to compute the initial values and I assume that these 3 values can be cached efficiently. Another disadvantage is that this may assume that the band order is always RGB for the elevation data which at least defining the scalers individually allows one to compensate for. How common of an issue that is I do not know. 

I attempted to locate the bit of logic where the parameters from the elevationDecoder is actually used but couldn't locate it even using the silver searcher. Links to the appropriate lines would be appreciated

**Comment by Pessimistress** [comment]
`TerrainLoader` is from https://github.com/visgl/loaders.gl and all proposals should be redirected over there.

Just to comment on your request: there are many terrain data sources and they do not all adhere to the same encoding. You are likely making assumptions (e.g. rScaler > gScaler) based on the tile source you are using.

**Comment by kylebarron** [comment]
> This would take the place of individually defining scalers for each color channel (which is just 256^2 and 256 multiplied each by 0.1 from the example in the docs) and would result in only two parameters needing to be defined by the user if the order of the bands and the style of quantization remains the same

Indeed, you're referring to the Mapbox encoding IIRC, but there's also a mapzen encoding still used by AWS terrain tiles, so not sure that would be an acceptable general solution

**Comment by AndrewAnnex** [comment]
@kylebarron while the mapbox encoding is what I mainly have in mind, I do think the mapzen encoding is equivalent, or perhaps a switch in behavior can be made depending if the resolution is set to 1:

The mapzen decoder as I understand it multiplies the R band by 256, the B band by 1/256, and takes the G band unmodified (*1). It then subtracts the 32768 offset from the cumulative sum:
```
# https://www.mapzen.com/blog/terrain-tile-service/
z = (R*256 + G + B/256) + -32768
```

The mapbox Terrain-RGB v1 and Terrain-DEM v1 instead multiplies R by 256^2, G by 256 and leaves B unmodified (*1) then takes the cumulative sum and multiplies it by the vertical resolution of 0.1 before adding the offset. 

```
# https://docs.mapbox.com/data/tilesets/reference/mapbox-terrain-rgb-v1/
z = ((R*256*256 + G*256 + B)*0.1) + -10000 
```

If you use the distribute property you are left with the same operations as the mapzen decoder, 3 bands multiplied by 3 coefficients (although one of these are 1.0 for mapzen) summed together then added to an offset. So for my proposed solution the resolution would just be 1.0 for mapzen encoded tiles. 

@Pessimistress that is correct regarding the R>G>B assumption, although that does seem to be consistent across these two popular specs so it is a semi safe assumption to make. Individual scalers make it possible to work around that assumption. 

While I think my proposal is interesting, it seems like it's trivial to define a utility function to define the scaler values given an specification. It would be great if these encodings were defined using json-schema somewhere, as I am playing around with this idea for other planetary bodies where we would want different offsets and vertical precision.

**Comment by Pessimistress** [comment]
Relavent: https://github.com/visgl/loaders.gl/issues/936
