### ISSUE TITLE
[Bug] Should `nearZMultiplier` and `farZMultiplier` types be `number` and not `boolean`?

### ISSUE THREAD

**Issue by jeffpeck10x** [visgl/deck.gl#7518]
### Description

I think that these types ought to be `number` and not `boolean`.
```
  /** Scaler for the near plane, 1 unit equals to the height of the viewport. Default to `0.1`. Overwrites the `near` parameter. */
  nearZMultiplier?: boolean;
  /** Scaler for the far plane, 1 unit equals to the distance from the camera to the top edge of the screen. Default to `1.01`. Overwrites the `far` parameter. */
  farZMultiplier?: boolean;
```

https://github.com/visgl/deck.gl/blob/master/modules/core/src/views/map-view.ts#L34

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

Attempt to set prop `nearZMultiplier` to a number with typescript.

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Thank you. Fix published in v8.8.21.
