### ISSUE TITLE
[Bug] Globe View Tooltips show on other side of globe

### ISSUE THREAD

**Issue by DrewRidley** [visgl/deck.gl#7544]
### Description

Hey all, if I have a ArcLine with a tooltip on the other side of the globe, the picking engine incorrectly assumes I am hovering over the line, despite it behind occluded by the globe itself.

This definitely does not seem like intended behavior, but I am not really sure how to go about fixing it.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Tooltip only shows if you hover over the ArcLayer

### Steps to Reproduce

Draw an ArcLayer from Australia to California. Add a tooltip and follow line beyond what is visible. Tooltip continues to show even when occluded by the globe.

### Environment

- Framework version: deck.gl@8.8.21
- Browser: Chrome
- OS: M1 Mac (macOS Ventura)

**Comment by Pessimistress** [comment]
If you want occlusion during picking, you need to set the globe to be pickable too.
