### ISSUE TITLE
[Bug] Typescript definition does not allow SimpleMeshLayerProps to have wireframe: true

### ISSUE THREAD

**Issue by thpica** [visgl/deck.gl#7555]
### Description

When creating a `SimpleMeshLayer`, the typescript compilation fails if the `wireframe` prop is set to `true`.

It fails with the following error:
```console
test.ts:4:3 - error TS2322: Type 'true' is not assignable to type 'false'.

4   wireframe: true,
    ~~~~~~~~~

  node_modules/@deck.gl/mesh-layers/typed/simple-mesh-layer/simple-mesh-layer.d.ts:70:5
    70     wireframe?: false;
           ~~~~~~~~~
    The expected type comes from property 'wireframe' which is declared here on type 'SimpleMeshLayerProps<any>'
```

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Setting wireframe to true should be accepted as it is a valid value.

### Steps to Reproduce

```typescript
import { SimpleMeshLayerProps } from "@deck.gl/mesh-layers/typed";

const props: SimpleMeshLayerProps = {
    wireframe: true
};
```

### Environment

- Framework version: deck.gl@8.8.20
- Typescript: 4.9.4

**Comment by Pessimistress** [comment]
Thank you for submitting a fix. It is included in v8.8.22.
