### ISSUE TITLE
autoHighlight and highlightedObjectIndex unexpected behaviour

### ISSUE THREAD

**Issue by Baseform** [visgl/deck.gl#7560]
### Description

I’m fighting with some unexpected behaviour using a combination of autoHighlight and highlightedObjectIndex to combine selected and hover visualization.
Using a layer (tested with a number of different types), with autoHighlight and pickable properties => up to this point all works as expected
onClick handler, if click on a feature, sets highlightedObjectIndex=info.index of the selected object => now, hovering no longer highlights, again, all good
onClick handler, if clicking outside any feature, set highlightedObjectIndex=null => now, the issue is that deck does not redraw (unhighlight the object) until you hover something else on that layer
I’ve also tried doing highlightedObjectIndex = -1, which does “unhighlight” the object but blocks autoHighlight.

### Expected Behavior

setting highlightedObjectIndex to null would unhighlight the previously highlighted feature

### Steps to Reproduce

[codepen example](https://codepen.io/diogovit/pen/ExpgpZY)

### Environment

- Framework version: 8.8.21

**Comment by Pessimistress** [comment]
Thank you for reporting. Fixed in v8.8.22.
