### ISSUE TITLE
[Bug] Incorrect prop type on `internalTextures`

### ISSUE THREAD

**Issue by jeffpeck10x** [visgl/deck.gl#7570]
### Description

https://github.com/visgl/deck.gl/blob/master/modules/core/src/utils/texture.ts#L14

I think this:
```
const internalTextures: Record<string, Texture2D> = {};
```

should actually be this:
```
const internalTextures: Record<string, boolean> = {};
```

https://github.com/visgl/deck.gl/blob/master/modules/core/src/utils/texture.ts#L14

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

n/a

### Steps to Reproduce

n/a

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Closed by #7652
