### ISSUE TITLE
[Doc] Wrapping layers with non-component functions

### ISSUE THREAD

**Issue by andreyselin** [visgl/deck.gl#7592]
### Link

https://deck.gl/docs/api-reference/react/deckgl

### Description

Hey!
DeckGL react documentation says nesting layers in components wont work.
What about returning component-like notation in function executed inside top-level notation?

Lets say we have function
```
const getSomeLayer = () => <GeoJsonLayer />
```

What if we get this layer like this?
```
const MapComponent = () => <DeckGL>{getSomeLayer()}</DeckGL>
```
Also, I found out that hooks work as expected in these functions, but it is [not recommended](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) by react docs
Reason for this approach to make sense is to abstract layer stuff inside this function.

Are there any performance issues around this?
Could you make it clear if high-frequency reinstantiation of deckgl and its layers (caused by continuous hover events changing react state, for example) is normal behaviour?
Thank you!

**Comment by Pessimistress** [comment]
Please follow the directions and use Discussions for Q&A.
