### ISSUE TITLE
[Bug]transition not forwarded to sub-layers in GeoJsonLayer

### ISSUE THREAD

**Issue by nils1404** [visgl/deck.gl#7594]
### Description

Adding a getPosition transition to a GeoJsonLayer does not have an effect because the transition is not forwarded to the respective sub-layer.
Workaround: set sub-layer properties manually 
```
_subLayerProps: {
    'points-circle': {
        transitions: {
          getPosition: 500,
        }
      }
    },

```

See also https://github.com/visgl/deck.gl/discussions/5283 where a similar issue for the hexagon layer is described. 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Setting sub-layer properties manually should not be necessary, i.e.
```
transitions: {
    getPosition: 500,
}
```
should work.

### Steps to Reproduce

```
export default function TestMap({someData}) {
// do some stuff and derive featureCollection

const layer = new GeoJsonLayer({
  id: "test",
  data: featureCollection,
  pickable: true, 
  stroked: true,
  filled: true,
  extruded: false,
  pointType: "circle+text",
  // getIcon: (f) => "marker",
  sizeScale: 15,
  // getPosition: (d) => 0,
  getSize: (d) => 5,
  lineWidthScale: 20,
  lineWidthMinPixels: 2,
  getTextSize: 10,
  getText: (f) => "test",
  textSizeUnits: "meters",
  getTextColor: [255, 0, 0, 200],
  getFillColor: [0, 0, 0, 0],
  getLineColor: [255,0,0,200],
  getPointRadius: 10,
  getLineWidth: 1,
  transitions: {
        getPosition: 500,
      }
});

return (
<DeckGL
  layers={[layer]}
  initialViewState={INITIAL_VIEW_STATE}
  controller={true}
>
  <StaticMap mapboxApiAccessToken={MAPBOX_API_KEY} mapStyle={MAP_STYLE} />
</DeckGL>
);
}
```

### Environment

- Framework version: 8.8.22
- Browser: Chrome 109.0.5414.75 
- OS: Windows 10 Enterprise LTSC, 10.0.17763

**Comment by Pessimistress** [comment]
GeoJsonLayer has no accessor called `getPositions`. See https://deck.gl/docs/api-reference/layers/geojson-layer#remarks for how to use transitions.
