### ISSUE TITLE
[Bug] DeckGl does not work on Samsung S22

### ISSUE THREAD

**Issue by razvanmargineanu** [visgl/deck.gl#7613]
### Description

DeckGl crashes when I try to use it with Samsung S22.
I cannot reproduce it on S20 or other older Android phones.
The map loads for 1 second but quickly dissapears.

The error I get in the console is:
deck: WebGL context is lost

I am able to reproduce the same crash on Firefox also, on the same phone

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Deck gl should load

### Steps to Reproduce

Navigate to this page on a Samsung S22 (plus or ultra should be same)
[https://deck.gl/examples/data-filter-extension/](https://deck.gl/examples/data-filter-extension/)

### Environment

- Framework version: 8.8.7 locally and whatever version is running on your examples page
- Browser: Chrome 109
- OS: Android 13

### Logs

deck: WebGL context is lost

**Comment by Pessimistress** [comment]
Possibly related to https://github.com/visgl/deck.gl/issues/5463 and float texture blending.

As noted [here](https://github.com/visgl/deck.gl/issues/5463#issuecomment-780845213), this browser does not pass the WebGL conformance test, i.e. it claims to support certain features while they are not correctly implemented. I'm not sure if there is a better way to handle this other than just detecting the Samsung browser via its agent string and throw a "not supported" error.

**Comment by puopg** [comment]
I've been looking into some crashes on our app, and it just so happened that one of my colleages could repro it. Still doing some more research into it, but Im thinking its could be related to Samsung's Exynos processors on some devices.

The test setup here is just to load the example: https://deck.gl/docs/api-reference/layers/scatterplot-layer.

I used the Samsung remote test lab on the S22 Ultra in the US, which I think is equipped with Snapdragon. But my colleage is located in the UK, and he has the S22 Ultra International version, which is equipped with the Exynos processor.

In the remote test lab in the US, the S22 Ultra does not have any issues with displaying the example, and the scatterplot orange dots appear.

 But when I swap to the UK (Its an option in the remote test lab), the model seems to change to the International Version, and visiting the same website, the example does not load.

<img width="1109" alt="Screen Shot 2023-04-06 at 11 40 04 PM" src="https://user-images.githubusercontent.com/7741481/230555812-85b6f21b-309b-49f8-9dd1-e1f08ef2a6fd.png">

Not sure if this could be useful at all, but just something I noticed.

**Comment by puopg** [comment]
@Pessimistress Curious, im pretty naive when it comes to deckgl and this sorta stuff, but would it work to do something like this instead of singling out the Samsung browser via user agent?

```
const checkIfWebGLIsOkToUse = (): boolean => {
  const canvas = document.createElement("canvas");
  const gl = canvas.getContext("webgl", { failIfMajorPerformanceCaveat: true });

  return Boolean(gl);
};
```

**Comment by Pessimistress** [comment]
You can try it by setting `glOptions: { failIfMajorPerformanceCaveat: true }` on `Deck`/`DeckGL`.

The other issue I linked above should only affect layers leveraging GPU aggregation. The fact that a basic layer such as the ScatterplotLayer does not work on this device indicates something else. It would be great if you can help us try a few things to understand the cause.

**Comment by puopg** [comment]
Yea no i agree, something seems weird about this. Here is a video recording of the same device Samsung S22 Ultra. You can see the device models are different though.

Looking up the model, you can see the main differences. I see they have different GPU's, one being Qualcomm Adreno 730 on the Snapdragon device, the other UK device running Exynos using Xclipse 920 [AMD RDNA 2 based].


https://user-images.githubusercontent.com/7741481/230653889-bd39879d-4360-47e4-9d90-0d166d32293c.mp4

**Comment by marklit** [comment]
Without naming names I've spoken to developers on this project on other channels. There is concern that there are a lot of mobile devices out there so supporting all of them would be an expensive endeavor. In reality, the latest iPhone and the latest flagship device from Samsung are 90% of what you need to support.

Not having Samsung support out of the box puts this offering far behind competitors. I've attached a screenshot of a 3D viewer from Esri complete with vectors and I can confirm it runs smoothly on the Samsung S22 Ultra. We need first-class support for Samsung's latest devices.

![Screenshot_20230421_074834_Brave](https://user-images.githubusercontent.com/359316/233544179-505c6843-078f-454a-b1eb-beecbe131943.jpg)

**Comment by ibgreen** [comment]
@marklit 
- In a way it is quite encouraging that you think of a free open source project like deck.gl as a competitor to Esri's proprietary offerings.
- But there is a difference, deck.gl is free software maintained largely by developers who work on their free time and while they generally want to fix issues they would need to pay for S22 hardware themselves (in addition to spending possibly a couple of evenings of work debugging and fixing). Also maintainers are spread over the world so if the problem requires more than one engineer, the unit needs to be sent around or multiple units need to be purchased, etc.

Now since you are in fact a Foursquare customer using our commercial products that happen to be built on deck.gl, you are of course entitled to hold us to much a higher bar. I have messaged you offline on a path forward to support you.

**Comment by lm1** [comment]
I see "WebGL context is lost" message on Exynos based S22 in Chrome 115 when opening https://rivermap.org.

**Comment by lm1** [comment]
I suspect the issue is not related to Exynos CPU but to the Xclipse graphics IP/drivers.
In Exynos based S21 Samsung use Mali-G78 and the issue does not reproduce there.
But in Exynos based S22 Samsung uses new Xclipse 920 graphics based on AMD RDNA2 (while Snapdragon variant comes with Adreno 730).
S22/S22+/S22 Ultra seem to be the first products line with Xclipse 920 graphics (in Exynos 2200 variants).
S23 FE is touted to include Xclipse 920 as well.

**Comment by lmielick** [comment]
ScatterplotLayer issue reproduces on S22 even with the simplest single datapoint plot ([example](https://github.com/visgl/deck.gl/blob/1516031a50fecb0b2afbefc59f19716739c0465b/examples/playground/json-examples/dot-text.json)) so I spent some time isolating it with the release packages available on [unpkg](https://unpkg.com/browse/deck.gl/) and I have found a working version!

v6.4.0-alpha.1 passes on S22 while [v6.4.0-alpha.2](https://github.com/visgl/deck.gl/commits/v6.4.0-alpha.2) and anything newer fails.
Fairly narrow range of commits ([diff](https://github.com/visgl/deck.gl/compare/v6.4.0-alpha.1...v6.4.0-alpha.2)) includes among other changes ScatterplotLayer shaders update (#2573) and some changes from luma.gl ([diff](https://github.com/visgl/luma.gl/compare/v6.4.0-alpha.1...v6.4.0-alpha.2)).

**Comment by lm1** [comment]
ScatterplotLayer issue reproduces on S22 even with the simplest single datapoint plot ([example](https://github.com/visgl/deck.gl/blob/1516031a50fecb0b2afbefc59f19716739c0465b/examples/playground/json-examples/dot-text.json)) so I spent some time isolating it with the release packages available on [unpkg](https://unpkg.com/browse/deck.gl/) and I have found a working version!

v6.4.0-alpha.1 passes on S22 while [v6.4.0-alpha.2](https://github.com/visgl/deck.gl/commits/v6.4.0-alpha.2) and anything newer fails.
Fairly narrow range of commits ([diff](https://github.com/visgl/deck.gl/compare/v6.4.0-alpha.1...v6.4.0-alpha.2)) includes among other changes ScatterplotLayer shaders update (#2573) and some changes from luma.gl ([diff](https://github.com/visgl/luma.gl/compare/v6.4.0-alpha.1...v6.4.0-alpha.2)).

**Comment by lm1** [comment]
I have setup temporary build environment for 6.4 and was able to confirm the failure on S22 starts with #2573.
I don't see any specific issue the changes, but with some fiddling I can say Xclipse graphics clearly does not like [the discard statement](https://github.com/visgl/deck.gl/blob/cb718477fa89bb5a7744d61f118e239bd144043e/modules/layers/src/scatterplot-layer/scatterplot-layer-fragment.glsl.js#L45) in the scatterplot fragment shader.

**Comment by lm1** [comment]
This issue appears to be the same problem as #6783.
