### ISSUE TITLE
[Bug] `picking` cross the 180º/-180º meridian with `MapView: { repeat: true }` not working

### ISSUE THREAD

**Issue by weberjavi** [visgl/deck.gl#7614]
### Description

When setting the `view` as a `MapView` with `repeat: true` Current behaviour only sets as interactive map the one that is under the center of the viewport. This is problematic when centering the view on the Polynesia, because half of the map is not interactive 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Expected behaviour would be that features (on an MVTLayer) could be selected from both sides of the antimeridian; all the repeated maps being interactive.

### Steps to Reproduce

Issue can be tested on [this codepen](https://codepen.io/weberjavi/pen/oNMQXEj).
Features to the East of the date change line are not picked

### Environment

- Framework version: deckgl@8.8.23
- Browser: Chrome 109.0.5414.119 (Official Build) (64-bit)
- OS: Ubuntu 22.04.1 LTS

**Comment by Pessimistress** [comment]
Fixed in 8.8.24.
