### ISSUE TITLE
[Bug] Type AccessorContext not (re-)exported

### ISSUE THREAD

**Issue by cneumann** [visgl/deck.gl#7620]
### Description

AccessorContext cannot be imported with `import { AccessorContext } from "@deck.gl/core/typed"`, because it is not listed in `modules/core/src/index.ts` (where `Accessor` and `AccessorFunction` are re-exported).

As a workaround:
```
import { AccessorContext } from "@deck.gl/core/typed/types/layer-props";
```
can be used, but it seems rather ugly to reach into the internals for this...

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Import should compile.

### Steps to Reproduce

- Create new deck.gl project
- Write source file with:
```
import { AccessorContext } from "@deck.gl/core/typed"`
```

### Environment

- Framework version: deck.gl@8.8.23
- Browser: Firefox 109
- OS: Windows 10

**Comment by Pessimistress** [comment]
You can use `Parameters<AccessorFunction<DataT, number>>[1]`.

**Comment by felixpalmer** [comment]
That seems quite obscure, why not export the type?
