### ISSUE TITLE
[Bug]SimpleMeshLayer adding FillStyleExtension is invalid

### ISSUE THREAD

**Issue by ranranbyte** [visgl/deck.gl#7622]
### Description

 const layer = new SimpleMeshLayer({
            id: 'trafficSignLayer',
            data: this.trafficSignData,
            coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS,
            coordinateOrigin: this.trackPosition,

            getColor: d => [256, 256, 256],
            getOrientation: d => d.orientation === '+' ? [0, d.hdg * 180, 90] : [0, -d.hdg * 180, 90],
            getPosition: d => d.position,
            mesh: './../../data/trafficSign.obj',
            sizeScale: 0.08,
            fillPatternAtlas: './../../data/texture/bus-sign.png',
            fillPatternMapping: './../../data/texture/bus-sign.json',
            getFillPattern: d => 'direct-right-sign',
            getFillPatternScale: 1,
            getFillPatternOffset: [0, 0],

            extensions: [new FillStyleExtension({ pattern: true })],
            loaders: [OBJLoader],
            pickable: true
        });

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

SimpleMeshLayer texture can be displayed normally

### Steps to Reproduce

Add a SimpleMeshLayer and then add the FillStyleExtension extension

### Environment

- Framework version:@
- Browser:all
- OS:all
"@deck.gl/extensions": "^8.4.13",
 "@deck.gl/core": "^8.1.5",
 "@deck.gl/layers": "^8.1.5",
 "@deck.gl/mesh-layers": "^8.1.5",

**Comment by Pessimistress** [comment]
`FillStyleExtension` does not work with `SimpleMeshLayer` as the texture is applied on the XY plane.  You should use the `texture` prop of the layer.
