### ISSUE TITLE
[Bug]Tile3DLayer no longer working from Cesium

### ISSUE THREAD

**Issue by haitunxiaomo** [visgl/deck.gl#7628]
### Description

URL: https://deck.gl/examples/tile-3d-layer/
The example on the official website does not work properly。 
And returns an invalid token.

![image](https://user-images.githubusercontent.com/8519144/217476443-2e1c3906-5df3-4c50-ae33-edb5cb65bf37.png)

### Flavors

- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

URL: https://deck.gl/examples/tile-3d-layer/

### Environment

- Browser:chrome

**Comment by ibgreen** [comment]
Cesium has shut down older tokens. @belom88 you just refreshed tokens in loaders.gl, any chance you can do it here as well?
