### ISSUE TITLE
[Bug] deck.gl dark mode is not working properly with CARTO integration

### ISSUE THREAD

**Issue by adrianes21** [visgl/deck.gl#7676]
### Description

While testing the new deck.gl version I tested the integration with CARTO and using dark mode it seems the labels in the layer are not visible until you click on them.

![image](https://user-images.githubusercontent.com/8087799/220601651-7df5e9cc-8bb4-4f92-9fca-1b1035cc3366.png)
![image](https://user-images.githubusercontent.com/8087799/220601716-2485ec25-5948-45ef-a7f2-09a46ede723d.png)

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The labels in the legend should be visible in both modes

### Steps to Reproduce

Go to https://pessimistress.github.io/deck.gl/examples/carto and activate dark mode. Label in legend are not there

### Environment

- Framework version: deck.gl@8.9
- Browser: Chrome, Safari, firefox
- OS: 110.0.5481.100, 16.2, 109.0.1

**Comment by Pessimistress** [comment]
Please report all issued on the staged website under #7635. Bugs are for production releases only.
