### ISSUE TITLE
[Bug] Error for probe.gl in @deck.gl/core v8.8.25

### ISSUE THREAD

**Issue by chris-befoul** [visgl/deck.gl#7683]
### Description

![image](https://user-images.githubusercontent.com/55672717/220796268-b5e4532e-d5fb-4350-87b5-c12542ba413f.png)

Recently began receiving the error above with 

"@deck.gl/core": "8.8.25"

Tried dropping to earlier versions but continuing to receive the same error. Any solutions to resolve would be greatly appreciated. Thanks! 

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Prior was not receiving the above error and worked great.

### Steps to Reproduce

Install @deck.gl/core v8.8.25 and then attempt to build/run application and will replicate error.

### Environment

Framework version: deck.gl@8.8.25
Angular v13

### Logs

![image](https://user-images.githubusercontent.com/55672717/220796650-48be83dd-d48d-49e2-afd7-644e239d607a.png)

**Comment by ibgreen** [comment]
While the posted fix will sort this, this specific error shouldn't happen. 

The umbrella "probe.gl" has been removed in probe.gl 4.0 which hasn't been officially published yet (just alpha releases). It would be interesting to see what the result of `yarn why probe.gl` returns on your box.

**Comment by chris-befoul** [comment]
My application is utilizing 
"@probe.gl/stats": "3.6.0"

if that helps.

**Comment by ibgreen** [comment]
OK thanks for checking. At least you are not getting v4.0 installed by mistake by some "errant" bundler :)

**Comment by chris-befoul** [comment]
Thanks for all of the timely responses and quick fix! Roughly when should the fix be available for v8.8-

**Comment by ibgreen** [comment]
Not long. Patches are usually cut on a weekly basis.

**Comment by Pessimistress** [comment]
Published 8.8.26 with the fix.
