### ISSUE TITLE
animationSpeed parameter in TripsLayer example

### ISSUE THREAD

**Issue by kodonnell** [visgl/deck.gl#7685]
### Target Use Case

Varying the speed of the animation feels like a pretty common use for the TripsLayer e.g. viewing traffic for the whole day (fast) or inspecting something particular in details (slow). The 'obvious' solution to someone like me (i.e. data scientist who's not an expert in React) of just making `animationSpeed` a parameter like `trailLength` doesn't work. So maybe updating the example to show how to do this is worthwhile, especially for such a popular layer and because I'm assuming it's not a big task for someone who knows react.

Extra points if a slider is added for the time so you can slide forward and backward in time = )

### Proposal

The UI should look the same, except with a slider for Animation Speed, like with Trail. As you slide, the animation speed changes.

**Comment by Pessimistress** [comment]
`animationSpeed` is already a parameter in the example app:

https://github.com/visgl/deck.gl/blob/683a648014026a2d757f640701148d31a2491adc/examples/website/trips/app.jsx#L73

Please use Discussions if you don't know how to adapt it to your use case.

**Comment by kodonnell** [comment]
Thanks. I don't believe it works (e.g. by using a slider parameter as per other parameters), hence this issue - though I'll rename/edit it for clarity that I want an *interactive* parameter.

**Comment by Pessimistress** [comment]
I don't know what you mean by "interactive". If you are looking for a slider/playback control, that is out of the scope of this library, and you should look for a UI library instead. Sounds like you just want to understand how to connect the TripsLayer to an environment that you work in. You can get better help by opening a thread in Discussions.
