### ISSUE TITLE
[Bug] TileLayer Props

### ISSUE THREAD

**Issue by tomeronen** [visgl/deck.gl#7697]
### Description

Description
i think the typing for TilesetClass prop in TileLayer should be optional.
the type:

```
/** All props supported by the TileLayer */
export type TileLayerProps<DataT = any> = CompositeLayerProps<any> & _TileLayerProps<DataT>;

/** Props added by the TileLayer */
type _TileLayerProps<DataT> = {
  /**
   * Optionally implement a custom indexing scheme.
   */
  TilesetClass: typeof Tileset2D;
....
...

}
```

Maybe should be:
```
/** All props supported by the TileLayer */
export type TileLayerProps<DataT = any> = CompositeLayerProps<any> & _TileLayerProps<DataT>;

/** Props added by the TileLayer */
type _TileLayerProps<DataT> = {
  /**
   * Optionally implement a custom indexing scheme.
   */
  TilesetClass?: typeof Tileset2D;
....
...
}
```

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

TilesetClass should be optional 

### Steps to Reproduce

Check type in modules/geo-layers/src/tile-layer/tile-layer.ts

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Fixed in v8.8.27.
