### ISSUE TITLE
pickObject with unproject3D returns weird elevation

### ISSUE THREAD

**Issue by Radik24** [visgl/deck.gl#7698]
### Description

Hi,

when I use `pickObject` with `unproject3D` it returns weird elevation, I expect it to be 0.

I use it with multiple layers and I thought it's my problem, but I created sandbox with only `TileLayer` and it's the same.

On my project I combine it with point cloud (elevation seems to be ok), but when I hover somewhere else elevation is crazy number.

Thanks

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

return 0 elevation

### Steps to Reproduce

Check the console to see the coordinates:

https://codesandbox.io/s/deck-gl-3d-tiles-triangles-m0p2cg?file=/src/App.js

### Environment

- Framework version: deck.gl@8.8.26
- Browser: Arc
- OS: MacOS

**Comment by Pessimistress** [comment]
Can you try the latest beta (8.9.0-beta.3)?

**Comment by Pessimistress** [comment]
You may want to see https://github.com/visgl/deck.gl/issues/7461#issuecomment-1337931864 as well

**Comment by Radik24** [comment]
Yeah, I don't have any extruded data, so elevation should be 0

**Comment by Pessimistress** [comment]
I can put up a fix. However it's not going to be 0 precisely - we read clips pace z then perform the unprojection. The precision error can be significant when you zoom out.

**Comment by ibgreen** [comment]
Maybe worth calling out the limitation in the docs if not already done?

**Comment by Radik24** [comment]
Thank you @Pessimistress! 

It does not make sense to perform these actions from distance :)

**Comment by ibgreen** [comment]
FWIW Other 3D frameworks offer options for logarithmic depth buffers etc that improve depth buffer precision for many use cases. So if this became a really important issues, there might be ways to improve it. 

There is a really neat example from three.js. https://threejs.org/examples/webgl_camera_logarithmicdepthbuffer.html

Maybe this could be packaged as an extension?

**Comment by Pessimistress** [comment]
Fixed in v8.8.27.
