### ISSUE TITLE
[Bug] Heatmap layer data points cover entire map  mapbox

### ISSUE THREAD

**Issue by YonatanHanan** [visgl/deck.gl#7703]
### Description

Hi,

I get the same [https://github.com/visgl/deck.gl/issues/6994](https://github.com/visgl/deck.gl/issues/6994) issue as this bug report.

I have a mapbox deckgl overlay with 10 layers.
the Heatmap is the last one.

I'm using the import from:
```typescript 
import { HeatmapLayer } from '@deck.gl/aggregation-layers/typed';
```
and the code
```typescript
 const dynamicHeatmapLayer = new HeatmapLayer<WeightedPosition>({
        id: 'dynamic-trade-area-heatmap-layer',
        beforeId: 'road-label',
        zoom,
        data,
        getPosition: ({ lat, lng }) => [lng, lat],
        getWeight: ({ weight }) => weight,
        visible: showDynamicHeatmapLayer,
        colorRange: defaultHeatmapColorRange,
        opacity: 0.2,
        aggregation: 'SUM',
        threshold: 0.005,
    });
```

https://user-images.githubusercontent.com/6177147/222097411-789404ee-6d7b-4403-86e0-45b308e8c771.mp4

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [x] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

no flashing

### Environment

- Framework version:8.8.26
- Browser:Chrome109
- OS:macOS Version 12.1

**Comment by PriyanujBora** [comment]
did you fix it?
