### ISSUE TITLE
[Bug] Local Build Not Working

### ISSUE THREAD

**Issue by 00hello** [visgl/deck.gl#7704]
### Description

I've been trying to use deck.gl from the source code in my own project rather than the modules from npm for the past few days but I can't get it to work. Particularly, I'm trying to make modifications to the [Tripslayer](https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/trips-layer/trips-layer.ts) for my own project.

The docs [here](https://deck.gl/docs/contributing#specific-module-overrides) describe how to implement a local build but those links now go nowhere. [ocular-dev-tools.config.js](https://github.com/visgl/deck.gl/blob/master/ocular-dev-tools.config.js) is now no longer even in the repo.

I want to use a local version of the deck.gl source code so I can modify it for my projects. I've tried making changes to [Tripslayer](https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/trips-layer/trips-layer.ts) in node_modules but none of the changes have any effect. Not sure what I'm doing wrong. 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

I expect to be able to run the examples using deck.gl from the local source code

### Steps to Reproduce

Follow the repo's instructions to run any of the [website examples](https://github.com/visgl/deck.gl/tree/master/examples/website). Then run `npm run start-local` in order to run from the local source code

### Environment

- Framework version: 8.8.26
- Browser: Firefox 110.0.1
- OS: Ubuntu 20.04

I've tried all the attempts listed here using node version v14.21.2, v16.19.0, and v19.4.0. I've used typescript version 4.6.4 and 4.9.5 as well as vite version 4.0.0 and 4.1.4

### Logs

**On branch: 2cab2c75ca48ecfbddb94515241a32368a99af2d (HEAD -> master, origin/master, origin/HEAD) I get...** 

The browser opens to http://localhost:8080/. But the window is just completely white. Nothing's there. I get no errors, in the terminal or in the browser's (Firefox) dev console.

**On branch: ffb07503b3878e443dc37cc8d07fdb9e57df096f (HEAD, tag: v8.8.26, origin/8.8-release) I get...**

```
> geojson@0.0.0 start-local
> webpack-dev-server --env.local --progress --hot --open

/home/david/experiments/deck.gl/examples/webpack.config.local.js:18
const {getOcularConfig} = require('ocular-dev-tools');
                          ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/david/experiments/deck.gl/node_modules/ocular-dev-tools/src/index.js from /home/david/experiments/deck.gl/examples/webpack.config.local.js not supported.
Instead change the require of index.js in /home/david/experiments/deck.gl/examples/webpack.config.local.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/david/experiments/deck.gl/examples/webpack.config.local.js:18:27)
    at module.exports (/home/david/experiments/deck.gl/examples/website/geojson/webpack.config.js:32:32)
    at handleFunction (/home/david/experiments/deck.gl/examples/website/geojson/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
    at prepareOptions (/home/david/experiments/deck.gl/examples/website/geojson/node_modules/webpack-cli/bin/utils/prepareOptions.js:9:5)
    at requireConfig (/home/david/experiments/deck.gl/examples/website/geojson/node_modules/webpack-cli/bin/utils/convert-argv.js:117:14)
    at /home/david/experiments/deck.gl/examples/website/geojson/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/david/experiments/deck.gl/examples/website/geojson/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at Object.<anonymous> (/home/david/experiments/deck.gl/examples/website/geojson/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40) { 
}
```

**Comment by Pessimistress** [comment]
Did you try `yarn bootstrap` at root?

**Comment by JunboXi** [comment]
When I run the ''yarn bootstrap'' command I get an error: 
$ PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn && ocular- bootstrap
'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD' is not an internal or external command, nor is it a runnable program
or batch file.
