### ISSUE TITLE
[Bug] `IconLayer` fails shallow comparison of `textureParameters` prop, because it's not deep-compared

### ISSUE THREAD

**Issue by JannikGM** [visgl/deck.gl#7708]
### Description

`IconLayer` with `textureParameters` will fail a shallow comparison when naively passing an object.
This is in contast to the `Layer` prop `parameters` (which accepts similar values) which does a deep-compare instead.

I've originally brought this up on Slack in https://deckgl.slack.com/archives/C34AC5MSQ/p1677684985788469:

> Shouldn't `textureParameters` on `IconLayer` behave similar to `parameters` on base `Layer` (~ deep compare: `{type: 'object', value: {}, optional: true, compare: true, depth: 1},`)?
>
> Currently, having
> ```
> textureParameters: {
>   [GL.TEXTURE_MIN_FILTER]: GL.NEAREST,
>   [GL.TEXTURE_MAG_FILTER]: GL.LINEAR
> }
>  ```
> will cause shallow comparison failure which triggers an update to the layer.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

There should be a deep-comparison, no failed comparison should be logged at log level 3.

- `parameters` on `Layer` has an explicit prop-type: https://github.com/visgl/deck.gl/blob/2cab2c75ca48ecfbddb94515241a32368a99af2d/modules/core/src/lib/layer.ts#L160
- `textureParameters`on `IconLayer`  **does not**  have an explicit prop-type: https://github.com/visgl/deck.gl/blob/2cab2c75ca48ecfbddb94515241a32368a99af2d/modules/layers/src/icon-layer/icon-layer.ts#L131-L132

### Steps to Reproduce

/

### Environment

- Framework version: All
- Browser: /
- OS: /

**Comment by Pessimistress** [comment]
Related to https://github.com/visgl/deck.gl/issues/7506

@felixpalmer Now I think more about this, I do not believe deep comparison is the right thing to do. Prop changes in `loadOptions` and `textureParameters` are NOT handled by the layers. The documentation even states that they are only used when resources are loaded. I think what we need is a "ignore" flag in the prop type.

**Comment by felixpalmer** [comment]
@Pessimistress, agreed - it also saves us needlessly comparing potentially deep parameters objects
