### ISSUE TITLE
[Bug] MapboxOverlay error when interleaved is true

### ISSUE THREAD

**Issue by OwenTrokeBillard** [visgl/deck.gl#7724]
### Description

Using `MapboxOverlay` with the `interleaved` property set to true results in an error "this.animationLoop is null". I am following the [docs example](https://deck.gl/docs/api-reference/mapbox/mapbox-overlay#using-with-react-map-gl) exactly except with interleaved enabled. The error crashes the whole application.

![image](https://user-images.githubusercontent.com/20851553/223228878-1e524e8f-d7ad-414b-ac91-230da36bdf04.png)

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

No error occurs and the the layers interleave correctly.

### Steps to Reproduce

1. See a working replica of the docs example at https://codesandbox.io/s/romantic-bardeen-xw8f7o?file=/src/App.tsx.
2. Uncomment "interleaved" on line 41 and save the file.
3. Interact with the map.
4. Observe that the preview crashes.

### Environment

- Framework version: deck.gl@8.8.26
- Browser: Firefox 110.0.1, Chrome 112.0.5615.12
- OS: Windows 10 (build 19044.2604)

**Comment by Pessimistress** [comment]
Same issue as https://github.com/visgl/deck.gl/issues/7532, triggered by React StrictMode

**Comment by OwenTrokeBillard** [comment]
@Pessimistress You are right, disabling React StrictMode fixes the issue. Thank you!
