### ISSUE TITLE
[Bug] Subclassing layer does not inherit props

### ISSUE THREAD

**Issue by brandonjpierce** [visgl/deck.gl#7732]
### Description

Reproduction:

https://codepen.io/brandonjpierce/pen/KKxyRdy

This is an isolated example but our use case is that we have a common spritesheet used across our app and we wanted to provide a slightly higher abstraction on top of IconLayer that sets some predefined defaults, assumptions, etc for visualizing icons. The thought was to simply extend `IconLayer`, set some defaults, and in the future provide additional attributes if necessary.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The `iconAtlas` and `iconMapping` would be inherited correctly in `SpriteLayer` since it is subclassing (extending) `IconLayer`

### Steps to Reproduce

See codepen, note that you can repro this behavior even if you move `iconAtlas` and `iconMapping` directly into the `SpriteLayer` prop object instead of `defaultProps`

### Environment

- Framework version: Latest
- Browser: Chrome
- OS: MacOS

### Logs

None

**Comment by brandonjpierce** [comment]
(updated codepen: https://codepen.io/brandonjpierce/pen/KKxyRdy) still seeing the same behavior 🤔 

```
SpriteLayer.defaultProps = {
  iconAtlas: {type: 'image', value: ATLAS, async: true},
  iconMapping: {type: 'object', value: ATLAS_MAPPING, async: true},
}
```

**Comment by Pessimistress** [comment]
`value` in the descriptor is the resolved value, not an URL. If you just want to hard code a prop value for a custom layer, create a `CompositeLayer` that renders an `IconLayer`.

I suggest you move this conversation to a discussion thread since it is not a bug.
