### ISSUE TITLE
[Bug] loadOptions issue for WMSLayer

### ISSUE THREAD

**Issue by brandonjpierce** [visgl/deck.gl#7747]
### Description

Context:

Trying to reach out to a WMS endpoint that has basic access authentication (meaning we need to pass `Authorization` header).

Given:

```
new WMSLayer({
  ...otherOptions,
  loadOptions: {
    fetch: {
      headers: {
        Authorization: 'Basic <hash>',
      },
    },
  },
}),
```

This does not attach additional headers to the WMS request:

![Screenshot 2023-03-13 at 11 30 50 AM](https://user-images.githubusercontent.com/5483779/224749717-20216642-486b-4e05-b010-d906981d5cd6.png)

### Flavors

- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Expectation would be that we could see the `Authorization` header in dev tools for the request.

### Steps to Reproduce

```
new WMSLayer({
  ...otherOptions,
  loadOptions: {
    fetch: {
      headers: {
        Authorization: 'Basic <hash>',
      },
    },
  },
}),
```

### Environment

- Framework version: Latest
- Browser: Chrome
- OS: MacOS

### Logs

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

```
layer.js?1808:500 Uncaught (in promise) TypeError: Cannot set property message of  which has only a getter
    at WMSLayer.raiseError (layer.js?1808:500:1)
    at WMSLayer.loadImage (wms-layer.js?61fd:209:1)
```

**Comment by ibgreen** [comment]
yes, somewhere your `loadOptions` are not being plumbed through. From a quick read I suspect it is here: https://github.com/visgl/loaders.gl/blob/master/modules/wms/src/lib/data-sources/ogc/wms-service.ts#L128 where we need to pass in `props.loadOptions` instead of `props`

**Comment by ibgreen** [comment]
Would you mind opening a bug on loaders.gl and linking this issue?

**Comment by brandonjpierce** [comment]
@ibgreen https://github.com/visgl/loaders.gl/issues/2382 thanks!

**Comment by Pessimistress** [comment]
This should be fixed with loaders.gl v3.4.
