### ISSUE TITLE
[Bug] PostProcessEffect stopped working starting 8.9.0-beta.1

### ISSUE THREAD

**Issue by bortomar** [visgl/deck.gl#7748]
### Description

Hello, try to play with [PostProcessEffect example on deck.gl site](https://deck.gl/docs/api-reference/core/post-process-effect), but it doesn't work. When I've changed deck.gl version to 8.8.27 on Code pen example it's worked again. 

### Steps to Reproduce

https://codepen.io/vis-gl/pen/YbRGvv

### Environment

- Framework version: deck.gl@8.9.0
- Browser: Vivaldi 5.8.2955.3
- OS: Windows 10

**Comment by Pessimistress** [comment]
Is this a browser-specific problem for you? I do not see any issue on Chrome, FF or Safari.

**Comment by bortomar** [comment]
> Is this a browser-specific problem for you? I do not see any issue on Chrome, FF or Safari.

It's not browser specific. There is the ame issue on Firefox, Chrome, Safari, Arc (macOS), Chrome, Vivaldi, Firefox Developer Edition (Windows 10), Opera, Chrome (Android).

**Comment by Pessimistress** [comment]
Ok how about we start by defining "it doesn't work"?

**Comment by bortomar** [comment]
> Ok how about we start by defining "it doesn't work"?

Okay, I apologize for the vague description of the problem. If I change the parameters directly in the code of the mentioned example, everything works correctly. However, if I use the UI to change the effect parameters, the change is not reflected in the rendering.

**Comment by Pessimistress** [comment]
Fixed in v8.9.3.
