### ISSUE TITLE
[Feat] Add minimum permissions to workflows

### ISSUE THREAD

**Issue by gabibguti** [visgl/deck.gl#7767]
### Target Use Case

Add minimum permissions to workflows is important to keep the repository safe against supply-chain attacks.

### Proposal

The proposal is to go through each workflow, checking what actions they use and set the permissions they need based on least privilege access rule.

##### Additional context

This is considered good-practice and recommended by [GitHub](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

If you agree with these changes, I can open a PR!

**Comment by Pessimistress** [comment]
Thank you. Please do open a PR!
