### ISSUE TITLE
[Bug] Artifact when using CollisionFilterExtension with text outline

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#7776]
### Description

When creating a `TextLayer` with the `CollisionFilterExtension` the sdf outline drawing can in some cases create an ugly artifact across a quarter of the view

https://user-images.githubusercontent.com/453755/226573412-7e621255-7b31-40a4-b7b5-9a965aa7cbc2.mov

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

NOTE: you need to resize to window to observe this bug, it doesn't happen at all resolutions

```js
const {DeckGL, TextLayer, CollisionFilterExtension} = deck;

const layer = new TextLayer({
  id: 'TextLayer',
  data: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/bart-stations.json',
  fontSettings: {sdf: true},
  getAlignmentBaseline: 'center',
  getColor: [255, 128, 0],
  getPosition: d => d.coordinates,
  getText: d => d.name,
  getSize: 12,
  getTextAnchor: 'middle',
  outlineColor: [255, 0, 0, 255],
  outlineWidth: 5,
  extensions: [new CollisionFilterExtension()],
});
new DeckGL({
  mapStyle: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
  initialViewState: {
    longitude: -122.4,
    latitude: 37.74,
    zoom: 11,
    maxZoom: 20,
    pitch: 30,
    bearing: 0
  },
  controller: true,
  layers: [layer]
});
  
```

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Fixed included in v8.9.4
