### ISSUE TITLE
[Bug] Bumpy animation with getTransition on IconLayer and ScatterplotLayer

### ISSUE THREAD

**Issue by albasitum** [visgl/deck.gl#7780]
### Description

When there are small changes on the position and with high levels of zoom (over 18 or so) the animation over the position attribute on IconLayer and ScatterplotLayer (possibly over other layers too) does not look smooth. You can clearly see how the position jumps between the interpolated points from the source position to the target position:

https://user-images.githubusercontent.com/123469201/226656546-0fa0f1fe-b59b-4fe2-ac67-cb1cf1995e23.mp4

Where the orange icon is an instance of IconLayer with a transition defined over the position and the blue icon is a custom layer whose vertex shader has  been modified 

The problem seems to be that the interpolated transitions are being computed directly on the clip space on [GPUInterpolationTransition](https://github.com/visgl/deck.gl/blob/b6d06976b8076ba0dc108879a111d8138986eae4/modules/core/src/transitions/gpu-interpolation-transition.js):

```
const vs = `
#define SHADER_NAME interpolation-transition-vertex-shader
uniform float time;
attribute ATTRIBUTE_TYPE aFrom;
attribute ATTRIBUTE_TYPE aTo;
varying ATTRIBUTE_TYPE vCurrent;
void main(void) {
  vCurrent = mix(aFrom, aTo, time);
  gl_Position = vec4(0.0);
}
`;
```

 The vertex shader for the custom layer computes the interpolated position on the common space, and then it projects the obtained position onto the clip space, which results on the smooth transition shown on the video.  

This is done directly on the vertex shader defined for the layer, the implementations mimics the one on IconLayer but computes the interpolated position before projecting onto the  clip space:

```
uniform float time;
uniform vec3 start;
uniform vec3 end;

...

void main(void) {

 ...
  // Compute the interpolated position on the common space
  vec3 common_start = project_position(start);
  vec3 common_end = project_position(end);
  vec3 interpolatedPosition = mix(common_start, common_end, time);

  if (billboard)  {
    // Project the interpolated position onto the clip space
    gl_Position = project_common_position_to_clipspace(vec4(interpolatedPosition, 0.0));
   ....
  } else {
    ...
    interpolatedPosition.xy += offset_common.xy / 1.0;
    // Project the transformed position onto clip space
    gl_Position = project_common_position_to_clipspace(vec4(interpolatedPosition, 0.0));
  }

...
}
`;
``` 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

The following codepen reproduces this behaviour:

https://codepen.io/albasitum/pen/abaRWmJ

### Environment

- Framework version: deck.gl@8.9.3
- Browser: Brave (Version 1.49.120 Chromium: 111.0.5563.64)
- OS: Ubuntu 22.04

**Comment by darcy-kenyon** [comment]
I also found this to be an issue for my particular use case, and would love to hear others thoughts on what might cause this.

If anybody else runs into this and needs a quick hacky fix here's a working example based on Albasitum's suggestion and the docs:

[](https://codepen.io/darcy-kenyon/pen/mdzZjoQ)

I had to project into common space before mixing or ended up with the same issue (is this a precision issue?) which can been seen here:

[](https://codepen.io/darcy-kenyon/pen/JjmQBzO)

I know very little about shaders and how the projection system works, so any suggestions on improving the working example shader would also be much appreciated.

btw a quick thanks to all of those involved in making this a great framework.
