### ISSUE TITLE
[Bug] onDrag event not fired in MapboxOverlay

### ISSUE THREAD

**Issue by YonatanHanan** [visgl/deck.gl#7785]
### Description

I'm experiencing the same as https://github.com/visgl/deck.gl/issues/4415.

Is there a fix for that?

The only event I get is onClick but not all the drag ones.

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

<img width="552" alt="image" src="https://user-images.githubusercontent.com/6177147/226900849-c41b8d34-8429-4328-89ac-ba95931684f8.png">

### Environment

- Framework version:8.9.3
- Browser:chrome
- OS:mac

**Comment by YonatanHanan** [comment]
@Pessimistress thanks, that will be very helpful

**Comment by Pessimistress** [comment]
Fixed in 8.9.6.
