### ISSUE TITLE
[Bug] Invalidate Controller when changing View type

### ISSUE THREAD

**Issue by hkfb** [visgl/deck.gl#7789]
### Description

When changing the `views` in DeckGL from one type to another, eg. from `OrthographicView` to `OrbitView` (the `id` remains the same), then the `controller.type` argument is apparently not honored.

See this example: https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer--view-state-synchronization

Initially the views have the `OrthographicView` type with the `OrthographicController`, and controls work as expected, ie. I am able to pan the camera.

If I then use the `show3d` toggle to switch to 3D, then the views are re-created with the same `id`s but using the `OrbitView` type with an `OrbitController` with `dragRotate` enabled. However in this case the `OrbitController` is ignored, and the `OrthographicController` remains, and thus I'm not able to rotate as expected.

Vice versa, if the initial `views` type is `OrbitView`, then I'm not able to pan the camera after I switch to `OrthographicView`, which can be demostrated with this example: https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer--view-state-synchronization&args=show3d:true

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The `controller.type` argument should be honored when creating new `views` even if the `id` is re-used.

### Steps to Reproduce

1. Open https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer--view-state-synchronization&args=show3d:true

2. Observe that the camera can rotate.

3. Toggle off `show3d`

4. Observe that the camera is not able to pan

### Environment

- Framework version: deck.gl@8.8.25
- Browser: Chrome
- OS: Linux

**Comment by Pessimistress** [comment]
This is not a bug. deck.gl uses `id` to uniquely identify a view, the same way `id` is used to uniquely identify a layer. Internal state is shared between two instances across updates. You cannot change the type without changing the id.

**Comment by hkfb** [comment]
Fair enough, although it is a bit confusing that I'm able to re-create a view with a different type, eg. Orbit to Orthographic, (but with the same `id`), and the new type is honored, but the new Controller type is not.

Anyway, I could perhaps solve it by using just `OrbitView` and emulating Orthographic controls and projection or changing the view `id` to force a new controller. So we can close the issue.

**Comment by hkfb** [comment]
@Pessimistress even if it's not a bug, it's still an inconvenience having to update the `id` and keep track of them in order to synchronize between the different `View` objects and `<View>` react components.

I think this PR improves the behavior and makes it less confusing: https://github.com/visgl/deck.gl/pull/7814

I would appreciate if someone could review it. I'm unable to clear the "Changes requested" flag.

**Comment by hkfb** [comment]
Fixed in #7814.
