### ISSUE TITLE
[Bug] viewManager is Null, when MapboxGL resize

### ISSUE THREAD

**Issue by ye332866614** [visgl/deck.gl#7801]
### Description

When Mapbox resize, Deck did not determine whether the object exists

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

> 
>   // Public API
>   // Check if a redraw is needed
>   // Returns `false` or a string summarizing the redraw reason
>   // opts.clearRedrawFlags (Boolean) - clear the redraw flag. Default `true`
>   needsRedraw(opts = {clearRedrawFlags: false}) {
>      if (this.props._animate) {
>        return 'Deck._animate';
>      }
>      let redraw = this._needsRedraw;
>      if (opts.clearRedrawFlags) {
>       this._needsRedraw = false;
>     }
>     const viewManagerNeedsRedraw = this.viewManager.needsRedraw(opts);
>     const layerManagerNeedsRedraw = this.layerManager.needsRedraw(opts);
>     const effectManagerNeedsRedraw = this.effectManager.needsRedraw(opts);
>     const deckRendererNeedsRedraw = this.deckRenderer.needsRedraw(opts);
>     redraw =
>       redraw ||
>       viewManagerNeedsRedraw ||
>       layerManagerNeedsRedraw ||
>       effectManagerNeedsRedraw ||
>       deckRendererNeedsRedraw;
>     return redraw;
>   }

### Environment

- Framework version: deck.gl@8.4.20
- Browser: Chrome 111.0
- OS: w10

**Comment by Pessimistress** [comment]
Fixed in 8.9.6.

**Comment by ye332866614** [comment]
感谢来件，已收到！
