### ISSUE TITLE
[Bug] Type error when passing a PathStyleExtension object to a PathLayer

### ISSUE THREAD

**Issue by lstuartfry** [visgl/deck.gl#7804]
### Description

Hello! I'm seeing a typescript issue when trying to pass a `PathStyleExtension` object to `PathLayer`'s `extensions` property. I'm importing both `PathStyleExtension` and `PathLayer` from their respective `/typed` modules. I'm using deck.gl/core, deck.gl/layers and deck.gl/extensions all on v8.9.4. I'm defining the extension object like so: `{ offset: true }`, but I run into the same type error even if I fail to define any parameters in the object.

```
const extensions = new PathStyleExtension({ offset: true });

  const pathLayer = new PathLayer({
    extensions: [extensions] // type error
  });

Type 'PathStyleExtension' is not assignable to type 'PathStyleExtension & LayerExtension<undefined>'.
  Type 'PathStyleExtension' is not assignable to type 'LayerExtension<undefined>'.
    Types of property 'opts' are incompatible.
      Type 'PathStyleExtensionOptions' is not assignable to type 'undefined'.
```

<img width="784" alt="image" src="https://user-images.githubusercontent.com/14063740/228618486-52cf015d-764b-4ace-b2d9-215ac9346c3b.png">

I can bypass this typescript error by simply importing the `PathLayer` from the non-`/typed` module, and the extension and layer behave as expected. However, I would strongly prefer to continue using the fully-typed `PathLayer`.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expect typescript to accept the `PathStyleExtension` type as I've defined it and passed it to the `PathLayer` `extensions` property.

### Steps to Reproduce

Reproducible codesandbox: https://codesandbox.io/s/path-style-extension-type-error-xwg6vq?file=/src/App.tsx

```
import { PathLayer } from '@deck.gl/layers/typed';
import { PathStyleExtension } from '@deck.gl/extensions/typed';

export default function App() {
  const extensions = new PathStyleExtension({ offset: true });

  const pathLayer = new PathLayer({
    extensions: [extensions] // type error - Type 'PathStyleExtension' is not assignable to type 'PathStyleExtension & LayerExtension<undefined>'.
  });

  return (
    <div>
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}
```

### Environment

- Framework version: deck.gl/core@8.9.4, deck.gl/layer@8.9.4, deck.gl/extensions@8.9.4
- Browser: Chrome 110.0
- OS: macOS 13.2.1

**Comment by Pessimistress** [comment]
Fixed in v8.9.7.
