### ISSUE TITLE
[Bug] SimpleMeshLayer + Tile3DLayer opacity

### ISSUE THREAD

**Issue by Radik24** [visgl/deck.gl#7807]
### Description

Hi,

It seems there is some bug in rendering Tile3DLayer when combined with SimpleMeshLayer.

When I set 0 opacity on Tile3DLayer, I can't see SimpleMeshLayer behind. It's somehow cut by Tile3DLayer.

![image](https://user-images.githubusercontent.com/23722745/228880050-dbed431e-ad14-4066-862f-e6f953c7a156.png)

![image](https://user-images.githubusercontent.com/23722745/228880113-e53fc4a0-c1df-4ef2-bb36-e26825f830e5.png)

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

See whole SimpleMeshLayer

### Steps to Reproduce

Just set 0/1 opacity on Tile3DLayer.

https://codesandbox.io/s/deck-gl-3d-tiles-opacity-84gs6u?file=/src/App.js:1335-1346

### Environment

- Framework version: 8.9.4
- Browser: Arc 0.95.1
- OS: MacOs 13.2.1

**Comment by Pessimistress** [comment]
This is not a bug. If you want to see through to the mesh layer then you must render the mesh first. Otherwise it is discarded by depth test.

**Comment by Radik24** [comment]
@Pessimistress ok, but it's not ok when you combine multiple layers together in map (e.g. 3DTiles buildings and some gltf trees). From one place it's ok, but when you move forward and turn 180 degrees the opacity strikes back.

It would be impossible to change render order based on you position and bearing/pitch I think. If it makes sense.

You can simply simulate it in my codesandbox ^^.

Thanks

**Comment by ibgreen** [comment]
Ideas are certainly welcome, but completely application-independent, order-independent transparency is a hard problem in depth buffer based 3D graphics. 

Scenegraph oriented 3D frameworks sometimes offer a semi-general solution in the form of optional "primitive sorting by distance from camera" before rendering, but that leverages the fact that each instance is rendered with a separate draw call and is very hard to combine with instanced rendering where all instances are rendered in one go.

It is sometimes possible to handle this on the application level. Perhaps in your case you might be able to break up your scene more and control rendering order or what is rendered to get a reasonable effect.

**Comment by Pessimistress** [comment]
The rule of thumb is to always render the opaque layers first, then the translucent layers. If you have several layers that all contain translucent 3D objects, they are not going to be rendered correctly by the current layers x instanced draw model. Your best chance is to combine them into one layer and do some custom sorting before invoking a separate draw call on each object.

In the past, we have done some exploration on order-independent transparency while maintaining the instanced draw model. We do plan to improve transparency handling within the context of a single layer, e.g. extruded PolygonLayer. The use case you describe is more complicated.

**Comment by Radik24** [comment]
Hi @Pessimistress @ibgreen I think I overcomplicated it. Basically I'm talking about 0 opacity, I can check opacity value and do not render layer on 0. Hopefully I won't see any "holes" in other model.

Thanks for your help

**Comment by ibgreen** [comment]
Yes, many of our fragment shaders use the `discard` keyword to discard the pixel if alpha is 0 to avoid touching the depth buffer.

Perhaps you found some shader that doesn't do this?
