### ISSUE TITLE
[Feat] Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [visgl/deck.gl#7822]
### Target Use Case

Adding a Security Policy is important to inform users how the repository handles security vulnerabilities.

### Proposal

The proposal is to add a `SECURITY.md` file. This file will provide instructions on how to report security vulnerabilities (e.g. via GitHub Security Advisories, email) and set expectations of when vulnerabilities will be confirmed, fixed and disclosed.

##### Additional context

As https://github.com/visgl/deck.gl/issues/7767, this is also considered good-practice and recommended by [GitHub](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard).

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

If you agree, I can open a PR to suggest a Security Policy! We can then work together to communicate how the repo can best handle vulnerability reports.

**Comment by chrisgervang** [comment]
Thank you! Have we done this in our other repos? Once we have, we've completed another step in our OpenJS onboarding https://github.com/openjs-foundation/project-status/issues/65

**Comment by gabibguti** [comment]
Hi @chrisgervang! As @ljharb commented here https://github.com/openjs-foundation/project-status/issues/65#issuecomment-1565233749, we can add a security policy at org level. The default security policy will be displayed to all repos that do not have their own security policy.

There are instructions on how to create org level files [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file). Plus, if you choose to use GitHub Security Advisories feature for reporting, you can enable it org level too.

##### How to enable Security Advisories for an organization
1. Open the org's settings
2. Click on "Code security & analysis"
3. Click "Enable all" for "Private vulnerability reporting (Beta)"
4. You can choose to check "Automatically enable for new public repositories"


If you'd like, I can help out opening PRs to the group of orgs or to the individual repos you believe this would be helpful.

**Comment by chrisgervang** [comment]
Thanks @gabibguti, I've just applied a security configuration to enable "Private vulnerability reporting" and Dependabot alerts Security Alerts to all of our repos.
