### ISSUE TITLE
[Feat] Support arrowheads in dashed lines

### ISSUE THREAD

**Issue by Lucas20000903** [visgl/deck.gl#7839]
### Target Use Case

Currently, the direction is calculated at each specific point and arrows are drawn using iconlayer, but if the number of paths increases, performance problems occur.

I'd appreciate your help.

### Proposal

![image](https://user-images.githubusercontent.com/130944577/232357384-ef006a2d-235e-42bd-be54-7aa2971e798d.png)
![image](https://user-images.githubusercontent.com/130944577/232357387-2f5c91fa-f22e-4f8d-9042-44a4708fcf21.png)

**Comment by Lucas20000903** [comment]
It doesn't work the way I want it to, but thank you for your help

I hope you can apply at deck.gl someday.

**Comment by camillegachido** [comment]
hey @Lucas20000903, could you share how you did it? I'd like to show an arrow with the direction of travel on a triplayer but I don't know how to do that
