### ISSUE TITLE
[Bug] `FillStyleExtension` breaks when filtering layers data

### ISSUE THREAD

**Issue by DanielBoa** [visgl/deck.gl#7854]
### Description

I have a `GeoJsonLayer` layer which uses the `FillStyleExtension` to apply a pattern to polygon features. The data array passed to this layer is filtered externally to `deck.gl`.

If you filter all features from the data array, then begin to add them back in, the `FillStyleExtension` no longer seems to work.

https://user-images.githubusercontent.com/1169866/234597947-9861f38e-609e-4c04-b103-67fe81a1ea16.mp4

_Find the link to this codesandbox below._

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

For the `fillStyleExtension` to work correctly before and after the layers data is filtered to empty.

### Steps to Reproduce

https://codesandbox.io/s/fill-style-extension-issue-when-filtering-features-5xb1m1

### Environment

- Framework version: 8.9.4
- Browser: 112.0.5615.137 (Official Build) (arm64) 
- OS: macOS Big Sur 11.1

**Comment by Pessimistress** [comment]
Fixed in v8.9.12
