### ISSUE TITLE
[Bug] Map does not scale with browser zoom when using `interleaved: true`

### ISSUE THREAD

**Issue by kochis** [visgl/deck.gl#7857]
### Description

We're using DeckGL + MapLibre in interleaved mode, and we noticed an issue when the browser is scaled with cmd+ or cmd- . It looks like the Deck layer scales as expected, but the underlying map does not.  This seems to be an issue only when using interleaved, the map & Deck layer scale as expected when interleaved: false.

Have an example here: https://codepen.io/boon21/pen/abRwpPy

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The map & Deck layer should scale at the same rate.

### Steps to Reproduce

CodePen: https://codepen.io/boon21/pen/abRwpPy

Scale the browser's zoom level `cmd+` or `cmd-` and zoom in/out on the visualization. You will see they map and layer are no longer in sync.

### Environment

- Framework version: latest
- Browser: Chrome 112
- OS: MacOS

**Comment by kochis** [comment]
Also noticed, this works as expected on Safari, so the bug just applies to Chrome and Firefox (have not tested Edge)

**Comment by Pessimistress** [comment]
Fixed in v8.9.13.
