### ISSUE TITLE
[Bug] MapboxLayer/MapboxOverlay have farPlane culling issues 📷 

### ISSUE THREAD

**Issue by Beilinson** [visgl/deck.gl#7863]
### Description

When using the MaboxLayer / MapboxOverlay, rotating the camera at near zoom levels ( > 14) results in certain geometries getting rendererd out. For example, using the Tile3DLayer, at certain angles the base of the meshes is invisible. Here is an example:

[scrnli_4_30_2023_12-01-32 AM.webm](https://user-images.githubusercontent.com/54665621/235324099-0517e95e-7d5a-4c70-ae06-83041e4e67eb.webm)

This occurs with all Tile3D assets, both Cesium and I3S.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

No farZ culling except for where really needed.

### Steps to Reproduce

Create a mapbox map, add a Tile3DLayer overlay / mapboxlayer, zoom in and look around. Happens on both interleaved true / false

### Environment

- Framework version: 8.9
- Browser: Chrome, Firefox
- OS: Windows

**Comment by Beilinson** [comment]
Upon further investigation it seems to be caused by the fact that the model is actually rendering slightly below the surface of the map. This happens in both mercator and globe projection

**Comment by Beilinson** [comment]
adding the following code to the tile3dlayer is extremely patchy but seems to fix the problem:

`onTileLoad: (tile) => tile.content.cartographicOrigin[2] += 30;`

Essentially shifting the entire gltf by an arbitrary 30 units upwards. Would be nice if mapboxLayer ensured that no gltf could be loaded below the mapbox surface (again, this is problematic even without terrain)

**Comment by Pessimistress** [comment]
If you use interleaved layers,  then the near/far planes will match those set by Mapbox.

If you use the overlay mode, then you can adjust the far plane with [farZMultiplier](https://deck.gl/docs/api-reference/core/map-view#farzmultiplier).

**Comment by Beilinson** [comment]
Thanks, I have tried both options as you mentioned, but again the issue ends up being that the layer is simply positioned below the mapbox zero level, even on Mercator projection. 

These are not some problematic assets as they are from the official cesium ion asset depot, so this should not be happening and should not require manual tinkering from the user.

**Comment by Pessimistress** [comment]
Mapbox renders its 2d map at sea level, and 3D tiles are positioned at their real world altitude. If your application is intentionally mashing two dataset with different reference points together, then it is your responsibility to make that arbitrary adjustment.

**Comment by DerKorb** [comment]
I am having the same problem. I am quite sure this is a problem in the formula for calculating the depth values.
When tilting the camera in my case it is clearly visible that my point cloud emerges gradualy and linearely from behind my 3d terrain. You can see the same effect in the video above between second 6 and 7.

**Comment by DerKorb** [comment]
https://github.com/visgl/deck.gl/assets/2011423/f98fd483-e634-4e59-bd29-3915cd8e2f07
