### ISSUE TITLE
[Feat] Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [visgl/deck.gl#7868]
### Target Use Case

Referencing actions by commit SHA in workflows is relevant to guarantee you are using an immutable version. In contrast, actions referenced by tags and branches are vulnerable to attacks, such as the tag being moved to a malicious commit, a malicious commit being pushed to the branch or typosquatting. Using commit SHAs can avoid these attacks as they are unique identifiers.

### Proposal

The proposal is to go through each workflow searching for actions referenced by tags and branches and replacing them by commit SHAs.

##### Additional context
It's good to highlight that although there are pros and cons for using each reference (tags, branches and SHAs), GitHub acknowledges that [using commit SHAs is more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), as does [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool.

About me, hi again! I'm Gabriela, I recently recommended https://github.com/visgl/deck.gl/issues/7767, and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

If you agree, I can open a PR.

**Comment by Pessimistress** [comment]
Please go ahead. Thanks!
