### ISSUE TITLE
[Bug] PathStyleExtension offset affect dashline

### ISSUE THREAD

**Issue by vrman** [visgl/deck.gl#7875]
### Description

i have 3 custom dashed path layer with different offsets , i want those paths with offset have same dashed style as the layer 0 with no offset (center path), but its impossible to make this happen, please check this example :
[https://codepen.io/vrman/pen/mdzxBOx](https://codepen.io/vrman/pen/mdzxBOx)

### Flavors

- [x] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

[https://codepen.io/vrman/pen/mdzxBOx](https://codepen.io/vrman/pen/mdzxBOx)

### Environment

- Framework version: 8.9.12
- Browser: chrome
- OS: windows

**Comment by mrsiahpoosh** [comment]
@Pessimistress Can you please check this bug? 
thanks

**Comment by vrman** [comment]
@Pessimistress Can you please check this bug?
thanks

**Comment by vrman** [comment]
any comment on this issue ?

**Comment by Pessimistress** [comment]
Fixed in v8.9.21.
