### ISSUE TITLE
deck.gl doesn't compile in Angular 15 typescript

### ISSUE THREAD

**Issue by qi-326** [visgl/deck.gl#7881]
### Description

I have tried to use deck.gl with googlemap in an Angular 15 project. lighting-effect.d.ts seems to be missing an import. Can you investigate? 

Error: node_modules/@deck.gl/core/typed/effects/lighting/lighting-effect.d.ts:30:22 - error TS2304: Cannot find name 'Texture2D'.
30         shadowMaps?: Texture2D[] | undefined;

![image](https://github.com/visgl/deck.gl/assets/133215099/803d36c3-b66e-4e77-9dc7-76e95bc34201)

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Install the deck.gl framework @deck.gl/core, @deck.gl/layers and @deck.gl/google-maps

### Environment

- Framework version: Angular 15 typescript
- deck.gl version: 8.9.13

**Comment by Pessimistress** [comment]
v9.0 has now been published and is supposed to be fully TS compliant. Open a new issue if Angular is still experiencing problems.
