### ISSUE TITLE
[Bug] GoogleMapsOverlay.setMap(null) doesn't hide or remove (with .finalize) the overlay

### ISSUE THREAD

**Issue by chriszrc** [visgl/deck.gl#7888]
### Description

The codesandbox is here:

https://codesandbox.io/s/typescript-deckgl-googlemaps-v8swpy

There's both a button to click and timeout that calls `.setMap(null)` and `.finalize()` but the overlay is not removed unless the window is resized or the map is physically interacted with or [EDIT] modified in some way; I did find if I called `map.setCenter()` with slightly different coords that was enough to trigger the redraw.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expected the overlay to be removed from the map

### Steps to Reproduce

https://codesandbox.io/s/typescript-deckgl-googlemaps-v8swpy

### Environment

- Framework version: 8.9.13
- Browser: Chrome Chrome, Firefox, Safari, etc
- OS: Mac

**Comment by Pessimistress** [comment]
Fixed in v8.9.16.
