### ISSUE TITLE
GlobeView polygon tessellation error

### ISSUE THREAD

**Issue by Baseform** [visgl/deck.gl#7897]
### Description

Since 8.9.11 we’re experiencing tesselation error on large areas when feeding direct data to a GeoJsonLayer (or to SolidPolygonLayer).

### Flavors

- [X] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The previous behavior where polygon areas are not flattened.

### Steps to Reproduce

[https://codepen.io/diogovit/full/eYPLzNq](https://codepen.io/diogovit/full/eYPLzNq)

### Environment

- Framework version: >8.9.12
- Browser: any
- OS: any

**Comment by Pessimistress** [comment]
Fixed in v8.9.16.
