### ISSUE TITLE
[Bug] partially initialized module 'pydeck' has no attribute 'ViewState' (most likely due to a circular import)

### ISSUE THREAD

**Issue by andysingal** [visgl/deck.gl#7899]
### Description

Hi,
While working with Pydeck, i am getting the following error... AttributeError: partially initialized module 'pydeck' has no attribute 'ViewState' (most likely due to a circular import)
<img width="731" alt="Screenshot 2023-05-17 at 12 03 42 PM" src="https://github.com/visgl/deck.gl/assets/20493493/50cce0f4-5bec-4b83-bc40-964891078559">

my code is:
import streamlit as st

import pandas as pd

import pydeck as pdk

st.title('SF Trees')

st.set_page_config(layout="wide")

st.write('This app analyses trees in San Francisco using'

     ' a dataset kindly provided by SF DPW')
trees_df = pd.read_csv('https://raw.githubusercontent.com/tylerjrichards/'
'Getting-Started-with-Streamlit-for-Data-Science/main/pretty_trees/trees.csv')

trees_df.dropna(how='any', inplace=True)

sf_initial_view = pdk.ViewState(
latitude=37.77,
longitude=-122.4,
zoom=11
)

sp_layer = pdk.Layer(
'ScatterplotLayer',
data = trees_df,
get_position = ['longitude', 'latitude'],
get_radius=30)

st.pydeck_chart(pdk.Deck(
map_style='mapbox://styles/mapbox/light-v9',
initial_view_state=sf_initial_view,
layers = [sp_layer]
))

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

here is what i was working on: https://medium.com/codex/visualising-satellite-data-with-pydeck-and-streamlit-to-discover-possible-forest-fires-worldwide-7cb4f25351ba

### Steps to Reproduce

The code is available here: https://medium.com/codex/visualising-satellite-data-with-pydeck-and-streamlit-to-discover-possible-forest-fires-worldwide-7cb4f25351ba

### Environment

- Framework version: Pycharm
- Browser: Chrome
- OS: MacoSX

### Logs

Already shared in the description

**Comment by Jesus89** [comment]
Hi @andysingal,

We will take a look and provide a solution.

**Comment by vdelacruzb** [comment]
Hi @andysingal,

We could not reproduce this issue from our side.

**Steps Followed**
- Unzip this [file](https://github.com/visgl/deck.gl/files/11622907/issue_7899.py.zip) into an empty folder.
- Run it from the terminal by executing: ```streamlit run issue_7899.py```.

We are getting the next result:

<img width="782" alt="Screenshot 2023-06-01 at 10 35 00" src="https://github.com/visgl/deck.gl/assets/6054336/34c4e1c1-8ff2-4c4b-a258-25600bee3935">

**Environment**
Browser: Chrome
OS: MacoSX

It should be related with some configuration in your local environment. If you have any file called `pydeck` in the same directory it could interfere with the import. This is the reason for recommending testing from an empty folder.

Please, let us know if the issue persist so we can do further research.

**Comment by vdelacruzb** [comment]
Hi @andysingal,

Did you have time to give a go and see if this was still a problem?

Thanks

**Comment by andysingal** [comment]
> Hi @andysingal,
> 
> Did you have time to give a go and see if this was still a problem?
> 
> Thanks

Hi @vdelacruzb , i was able to resolve this issue. Thanks again for your assistance
