### ISSUE TITLE
[Bug] Google 3D Tiles: "Request contains an invalid argument"

### ISSUE THREAD

**Issue by RELNO** [visgl/deck.gl#7903]
### Description

- I'm testing the new 3d tiles API as as described here https://developers.google.com/maps/documentation/tile/use-renderer#deckgl_renderer_examples

- when using deck's Tile3DLayer with the new google 3d tiles API, requests for further tiles (json/glb) fail with code 400
<img width="412" alt="Screenshot 2023-05-18 at 4 24 48 PM" src="https://github.com/visgl/loaders.gl/assets/14296774/e1a5d609-c8d5-43e4-bc33-710d7aa7902d">

The inspector shows that past `root` request, follow up requests **fail to include the API** key after the session:

`https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/UlRPVEYubm9kZWRhdGEucGxhbmV0b2lkPWVhcnRoLG5vZGVfZGF0YV9lcG9jaD05NDYscGF0aD0wMyxjYWNoZV92ZXJzaW9uPTYsaW1hZ2VyeV9lcG9jaD05NjY.glb??session=CK_blahBlah`

**possible fix**: 
change the loader code so that the `key` is carried with each request, similar to how `session` is. Note the format of the request  [described here](https://developers.google.com/maps/documentation/tile/create-renderer#requests-and-responses) i.e:

`https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/UlRPVEYubm9k.glb?session=CIqhrPOFvdHSYg&key=YOUR_API_KEY`

[also mentioned here https://github.com/visgl/loaders.gl/issues/2488, might be `loaders` issue]

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

tiles should render 

### Steps to Reproduce

run this template with latest builds https://developers.google.com/maps/documentation/tile/use-renderer#deckgl_renderer_examples
replit to clone (change to your API) https://replit.com/@RELNO/deck3DTiles?v=1

### Environment

- Framework version: latest 
- Browser: Chrome/Firefox latest 
- OS: OSx 13.2.1

### Logs

see above

**Comment by Pessimistress** [comment]
If you follow the sample code in the linked documentation, the api key will be sent via a request header.

**Comment by RELNO** [comment]
@Pessimistress thanks, I believe it was followed. Not sure how to test nextjs in codepen, please see replit https://replit.com/@RELNO/deck3DTiles?v=1  [change `YOUR_API` to your API]

**Comment by Pessimistress** [comment]
Well since you just copied and pasted the example code, I suggest you check if your api key has all the necessary permissions to access this service.

**Comment by RELNO** [comment]
@Pessimistress thanks - I believe my API has access to this resource. I have been developing in python alongside the deckgl app, and have no issues to request nested API resources (json/glb). If you run the code, you might notice that the first request does go through, but further requests are blocked with `Request contains an invalid argument` as I mentioned above. I believe that either the deck layer or the loader do not adhere to the request query structure.

**Comment by Pessimistress** [comment]
@ibgreen

**Comment by RELNO** [comment]
@mjasher indeed. also, the offical API requires `https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/UlRPV...NjY.glb?session=_SESSION__&key=__KEY__`, so the second `?` => `&`

**Comment by Pessimistress** [comment]
This should be fixed by the latest loaders.gl (v3.4.2)
