### ISSUE TITLE
[Bug] cannot start brushing example

### ISSUE THREAD

**Issue by lyancynthia** [visgl/deck.gl#7907]
### Description

Cannot start brushing example when I try to follow the instructions.

<img width="1440" alt="截屏2023-05-22 下午5 10 33" src="https://github.com/visgl/deck.gl/assets/64658248/db538d36-09bd-48ca-abd1-474cc8007737">
<img width="1440" alt="截屏2023-05-22 下午5 10 45" src="https://github.com/visgl/deck.gl/assets/64658248/87ae8ed5-82a4-4e7f-8d94-8c431826252f">
<img width="1440" alt="截屏2023-05-22 下午5 10 57" src="https://github.com/visgl/deck.gl/assets/64658248/f05fbc33-e71e-4a61-b52b-1f3ab3637fc4">

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

1. download the repo
2. cd /Users/yan/deck.gl-master/examples/website/brushing
3. npm install
4. npm audit fix
5. npm audit fix --force
6. npm start

### Environment

- Framework version:
- Browser:
- OS: MacOS 13.2.1

**Comment by Pessimistress** [comment]
As the error message states, you are using an unsupported node version.
