### ISSUE TITLE
[Bug] Unable to install deck.gl with npm

### ISSUE THREAD

**Issue by rna2i** [visgl/deck.gl#7912]
### Description

Running:
`npm install deck.gl --save`

It gets stuck and does not complete.

The npm log is filled with and it seems to be in a inifinite loop:
99972 silly placeDep ROOT d3-hexbin@0.2.2 OK for: @deck.gl/aggregation-layers@8.9.16 want: ^0.2.1
99973 timing idealTree:node_modules/@deck.gl/aggregation-layers Completed in 10ms
99974 silly placeDep ROOT cartocolor@4.0.2 OK for: @deck.gl/carto@8.9.16 want: ^4.0.2
99975 silly placeDep ROOT d3-array@3.2.3 OK for: @deck.gl/carto@8.9.16 want: ^3.2.0
99976 silly placeDep ROOT d3-color@3.1.0 OK for: @deck.gl/carto@8.9.16 want: ^3.1.0
99977 silly placeDep ROOT d3-format@3.1.0 OK for: @deck.gl/carto@8.9.16 want: ^3.1.0
99978 silly placeDep ROOT d3-scale@4.0.2 OK for: @deck.gl/carto@8.9.16 want: ^4.0.0
99979 silly placeDep ROOT moment-timezone@0.5.43 OK for: @deck.gl/carto@8.9.16 want: ^0.5.33
99980 silly placeDep ROOT quadbin@0.1.9 OK for: @deck.gl/carto@8.9.16 want: ^0.1.9
99981 timing idealTree:node_modules/@deck.gl/carto Completed in 80ms
99982 silly placeDep ROOT @loaders.gl/3d-tiles@3.4.3 OK for: @deck.gl/geo-layers@8.9.16 want: ^3.4.2
99983 silly placeDep ROOT @loaders.gl/terrain@3.4.3 OK for: @deck.gl/geo-layers@8.9.16 want: ^3.4.2
99984 silly placeDep ROOT @loaders.gl/wms@3.4.3 OK for: @deck.gl/geo-layers@8.9.16 want: ^3.4.2
99985 silly placeDep ROOT long@3.2.0 OK for: @deck.gl/geo-layers@8.9.16 want: ^3.2.0
99986 timing idealTree:node_modules/@deck.gl/geo-layers Completed in 49ms
99987 silly placeDep ROOT @mapbox/tiny-sdf@2.0.6 OK for: @deck.gl/layers@8.9.16 want: ^2.0.5
99988 timing idealTree:node_modules/@deck.gl/layers Completed in 12ms
99989 silly placeDep ROOT @loaders.gl/core@3.4.0 REPLACE for: @loaders.gl/3d-tiles@3.4.3 want: 3.4.0
99990 silly placeDep ROOT long@5.2.3 OK for: @loaders.gl/3d-tiles@3.4.3 want: ^5.2.1
99991 silly timing Tried to end timer that doesn't exist: idealTree:#root
99992 silly placeDep ROOT @loaders.gl/core@3.4.3 REPLACE for: @deck.gl/core@8.9.16 want: ^3.4.2
99993 timing idealTree:node_modules/@deck.gl/core Completed in 11ms
99994 timing idealTree:node_modules/@loaders.gl/core Completed in 0ms
99995 silly placeDep ROOT @deck.gl/aggregation-layers@8.9.16 OK for: deck.gl@8.9.16 want: 8.9.16
99996 silly placeDep ROOT @deck.gl/layers@8.9.16 OK for: @deck.gl/aggregation-layers@8.9.16 want: ^8.0.0
99997 silly placeDep ROOT @deck.gl/carto@8.9.16 OK for: deck.gl@8.9.16 want: 8.9.16
99998 silly placeDep ROOT @deck.gl/geo-layers@8.9.16 OK for: @deck.gl/carto@8.9.16 want: ^8.0.0
99999 timing idealTree:node_modules/deck.gl Completed in 14ms

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Expected the deck.gl dep to install succesfully with npm.

### Steps to Reproduce

Simple example on empty react project:
Run:
```
npx create-react-app testapp
cd testapp
npm install deck.gl --save
```

### Environment

- Framework version: deck.gl@latest
- Browser: Firefox 102.11.0esr
- OS: Mac OS X Ventura 13.3.1

**Comment by rna2i** [comment]
Just want to add that we discovered this on github actions where our build would timeout or report a memory issue.
We can reproduce locally, but just attempting to do a clean install of deck.gl with npm.

**Comment by squaremarco** [comment]
I confirm the issue. I too can't install deck.gl through npm

**Comment by Pessimistress** [comment]
What is your Node/NPM version?

**Comment by rna2i** [comment]
Same issue with Node v18.16.0 and NPM 9.6.7

NPM log file:

[2023-05-24T14_31_02_181Z-debug-0.log](https://github.com/visgl/deck.gl/files/11555809/2023-05-24T14_31_02_181Z-debug-0.log)

**Comment by Pessimistress** [comment]
The issue is in loaders.gl: https://github.com/visgl/loaders.gl/issues/2502

**Comment by johanneserhardt** [comment]
Same here running `npm install deck.gl react-map-gl`

**Comment by ibgreen** [comment]
loaders.gl@3.4.4 is published with a fix. I just successfully ran `npm install deck.gl react-map-gl` in a fresh directory.

**Comment by rna2i** [comment]
Works again. Thanks! :)
