### ISSUE TITLE
[Feat] Make canvas instance readonly instead of protected

### ISSUE THREAD

**Issue by akre54** [visgl/deck.gl#7918]
### Target Use Case

Right now there isn't a way to access the canvas instance [as seems to be suggested](https://github.com/visgl/deck.gl/issues/4436#issuecomment-610472868), as Typescript forbids it. It's possible to cast the deck instance as `any` before getting the canvas prop but this way provides a formalized accessor.

### Proposal

Change the type on `canvas` from `protected` to `readonly`.

**Comment by felixpalmer** [comment]
Fixed in 8.9.31
