### ISSUE TITLE
[Bug] Text position in combination with Grid Layer

### ISSUE THREAD

**Issue by markuplab** [visgl/deck.gl#7922]
### Description

I using Text Layer together with Grid Layer, every cell has a text block with a numeric value (2-3 characters).

I specify the coordinates in the lower left corner for both layers, but the text is displayed at absolutely arbitrary points (left, right, center). 

Are there is ways to set text position to center in every case?

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

https://js-fdatwf.stackblitz.io

### Environment

- Framework version: Latest
- Browser: Chrome (latest)
- OS: Mac OSX (latest)

**Comment by Pessimistress** [comment]
The GridLayer aggregates the input data, so the bins are always aligned to a grid. TextLayer displays text at the exact position that you specify. There is no bug in this scenario. If you need help implementing something please use Discussions.
