### ISSUE TITLE
polygon elevation drawn incorrectly

### ISSUE THREAD

**Issue by qiaoxin136** [visgl/deck.gl#7934]
### Description

polygon geojson file on google 3d terrain.

polygon elevation is only 3-4 meter, but they are floating on top of buildings. see below. from the docs, i understand that the polygons are drawn based on their x,y,z info. i also tried the getposition apporach. the result is the same. please see the screen capture below. The elevation for each polygon, if you click it, is very low. 

![image](https://github.com/visgl/deck.gl/assets/44871863/3c5c6e07-50ec-46f2-8144-2bb2fddf17b5)

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

the polygon close to the ground

### Steps to Reproduce

https://codesandbox.io/p/github/qiaoxin136/polygon11/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clikee2hb000b356mz83aca1s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clikee2hb000d356mf4h3lxo9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clikee2hb000b356mz83aca1s%2522%253A%257B%2522id%2522%253A%2522clikee2hb000b356mz83aca1s%2522%252C%2522activeTabId%2522%253A%2522clikegq8x00ej356mh2xpqlgz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clikee2hb000a356mvap86flk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522id%2522%253A%2522clikegq8x00ej356mh2xpqlgz%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clikee2hb000d356mf4h3lxo9%2522%253A%257B%2522id%2522%253A%2522clikee2hb000d356mf4h3lxo9%2522%252C%2522activeTabId%2522%253A%2522clikelndr009l356mmjorzplu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clikehkps00jn356mdsg2bgfk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clikelndr009l356mmjorzplu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Environment

- Framework version: deck.gl@ 8.9.16
- Browser: microsoft edge Version 114.0.1823.37
- OS: windows 10

**Comment by Pessimistress** [comment]
This is not a bug. The 3D tiles dataset does not differentiate which geometry is ground and which is building. The TerrainExtension can only treat the whole thing as the basis for offset.

If you want the polygons drawn over the ground but not the buildings, you need to load a dataset that is only the ground surface and set `operation: 'terrain'` on that layer.
