### ISSUE TITLE
[Bug] clearColor parameter covers the terrain

### ISSUE THREAD

**Issue by nvn-nil** [visgl/deck.gl#7942]
### Description

The clearColor parameter covers the terrain.

While experimenting with different ways to get this to work, I added a TerrainExtension to the TerrainLayer (without any specific expectations). Surprisingly, it gives the desired terrain + clearColor behavior but other layers are not positioned correctly on the terrain. The terrainExtension is doing something that fixes this issue, and I briefly considered creating my own extension to see if I can get a solution (and learn). However, since I need something out soon, I am currently using a TerrainLayer without texture, overlaid with a TileLayer (with TerrainExtension).

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

`clearColor` + Terrain works as expected

### Steps to Reproduce

Here's a codesandbox that demonstrates this issue: https://codesandbox.io/s/clearcolor-parameter-issue-0hz5tz?file=/src/components/Map.jsx

### Environment

- Framework version: 8.9.4
- Browser: chrome
- OS: Windows/Ubuntu/Mac

**Comment by ShubhamPatilsd** [comment]
Will be working on this

**Comment by Pessimistress** [comment]
Fixed in v8.9.22.
