### ISSUE TITLE
[Bug] Vulnerability on dependency fast-xml-parser

### ISSUE THREAD

**Issue by mgm793** [visgl/deck.gl#7957]
### Description

<img width="914" alt="Screenshot 2023-06-19 at 08 41 01" src="https://github.com/visgl/deck.gl/assets/11296854/4d50dbb7-5b24-494e-acd1-cac54e5c58f8">

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

You can check using `npm audit` 

### Environment

- Framework version: deck.gl@8.9.19
- Browser: ALL
- OS:ALL

**Comment by Pessimistress** [comment]
`fast-xml-loader` is not a direct dependency of deck.gl. You can find out which dependency brought it in with `yarn why`, which indicates `@loaders.gl/wms`.

Please report this to the loaders.gl repo.
