### ISSUE TITLE
[Bug] centerCameraOnTerrain doesn't account for terrain exaggeration

### ISSUE THREAD

**Issue by bolatuly** [visgl/deck.gl#7958]
### Description

Recent feature which synchronizes camera when the base map contains terrain seems like doesn't account for terrain [exaggeration](https://docs.mapbox.com/mapbox-gl-js/style-spec/terrain/#exaggeration). You can observer it in the example below, where elevation is exaggerated by 1.5

https://github.com/visgl/deck.gl/assets/10495413/844a25c8-9669-437d-a1c2-a9097deaaad7

Changing this line https://github.com/visgl/deck.gl/blob/master/modules/mapbox/src/deck-utils.ts#L244 to 

`viewState.position = [0, 0, surfaceElevation / unitsPerMeter(latitude) / map2.transform.elevation.exaggeration()];`

seems like is fixing a problem.

https://github.com/visgl/deck.gl/assets/10495413/3f31b263-359f-4ce2-8404-ca0801e9d1b9

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

camera should  synchronize better when the base map contains terrain with exaggeration

### Steps to Reproduce

Add any 3d tiles using Mapbox Overlay on top of mapbox gl with exaggerated terrain.

### Environment

- Framework version: deck.gl@8.9.3
- Browser: chrome 110.0
- OS: MacOS 13.0.1

**Comment by Pessimistress** [comment]
> Add any 3d tiles using Mapbox Overlay on top of mapbox gl with exaggerated terrain.

deck.gl does NOT fit data to the terrain defined in the base map. Mapbox does not provide sufficient API for us to do so. Your 3D tiles are always rendered at the elevation that is defined in the tiles, and that is why it does not synchronize with the exaggerated terrain. This has nothing to do with the camera position. If your hack works for your use case, feel free to use it in your application. This is not a bug in the calculation of deck's camera position.
