### ISSUE TITLE
[Bug] @loaders.gl/parquet compatibility

### ISSUE THREAD

**Issue by skemaikin** [visgl/deck.gl#7959]
### Description

Hi!
I am currently trying to use `ParquetLoader` from the `@loaders.gl/parquet`, but as soon as I use `import { ParquetLoader } from '@loaders.gl/parquet'` instruction I have got a compilation error.
I have written a simple react project test to demonstrate the problem. 
Project link: https://drive.google.com/file/d/13RHfYffw_ksw7N9Gj9b74bXLANjRwwxu/view?usp=sharing

The App.js file contains `import { ParquetLoader } from '@loaders.gl/parquet'` instruction. Uncomment it to produce an error.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

compilation without any errors

### Steps to Reproduce

1. Download example code
2. npm install
3. npm start

### Environment

- Framework version: node 18.16.0, react 18.2.0
- Browser: chrome
- OS: Ubuntu 22.04

### Logs

ERROR in ./node_modules/@loaders.gl/parquet/dist/esm/lib/wasm/encode-parquet-wasm.js 13:9-41
export 'RecordBatchStreamWriter' (imported as 'RecordBatchStreamWriter') was not found in 'apache-arrow' (module has no exports)
ERROR in ./node_modules/@loaders.gl/parquet/dist/esm/lib/wasm/parse-parquet-wasm.js 14:17-45
export 'RecordBatchStreamReader' (imported as 'RecordBatchStreamReader') was not found in 'apache-arrow' (module has no exports)
ERROR in ./node_modules/@loaders.gl/parquet/dist/esm/lib/wasm/parse-parquet-wasm.js 19:13-18
export 'Table' (imported as 'Table') was not found in 'apache-arrow' (module has no exports)
ERROR in ./node_modules/parquet-wasm/node/arrow1.js 7:4-19
Module not found: Error: Can't resolve 'util' in '/home/sergeyk/test/parquet-react-test/node_modules/parquet-wasm/node'

**Comment by Pessimistress** [comment]
Please report your issue to the loaders.gl repo.
