### ISSUE TITLE
[Bug] TerrainExtension - picking doesn't work for draped geojson polygons and lines 

### ISSUE THREAD

**Issue by igorDykhta** [visgl/deck.gl#7964]
### Description

TerrainExtension - picking doesn't work for draped geojson polygons and lines.
Not exactly sure whether it's a bug or an unimplemented feature.

### Expected Behavior

Picking should work with draped polygons and lines in TerrainExtension mode.
If picking cannot be supported in drape mode then this should be mentioned in the docs.

### Steps to Reproduce

https://codepen.io/Igor-Dykhta/pen/vYQyexB

### Environment

- Framework version: 8.9.12

**Comment by Pessimistress** [comment]
Duplicate of #7892
