### ISSUE TITLE
[Bug] AggregateAccessor not a function

### ISSUE THREAD

**Issue by KilJH** [visgl/deck.gl#7967]
### Description

In aggregation-layers, some properties are AggregateAccessor type. like getColorValue, getElevationValue.

but AggregateAccessor is not function. it is just arguments of function.

in my thought. AggregateAccessorFunction will be added like

```
type AggregateAccessorFunction<DataT, ReturnT> = (data:AggregateAccessor<DataT>) => ReturnT
```

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

property of type AggregateAccessor will be function

### Steps to Reproduce

not runtime bug.
just code level & to support typescript

### Environment

- Framework version: deck.gl@8.9.19
- Browser: any
- OS: any

**Comment by Pessimistress** [comment]
Fixed in v8.9.21.
