### ISSUE TITLE
[Bug]  `FillStyleExtension` no longer works with an `MVTLayer` 

### ISSUE THREAD

**Issue by jamesscottbrown** [visgl/deck.gl#7968]
### Description

For recent versions (e.g., `8.9.19`), applying the `FillStyleExtension` to an `MVTLayer` doesn't work: the outline of features is drawn, but they have no fill (they have neither the fill pattern than should be applied, or the solid fill that is applied if the `FillStyleExtension` is not used )

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expect the specified fill pattern to be applied (as it is if I use a GeoJSON layer rather than an MVTLayer, or use an older version of deck.gl).

### Steps to Reproduce

This CodePen is based on an [example](https://codepen.io/Pessimistress/pen/qBbrbaw) made by @Pessimistress in a [previous issue](https://github.com/visgl/deck.gl/issues/4718#issuecomment-650356883).

Red hashed pattern correctly applied (importing the bundle for [8.8.26](https://unpkg.com/deck.gl@8.8.26/dist/dist.dev.js)): https://codepen.io/jamesscottbrown/pen/LYXxzYr

Fill not working (importing the bundle for [8.9.19](https://unpkg.com/deck.gl@8.9.19/dist/dist.dev.js)): https://codepen.io/jamesscottbrown/pen/MWzJEYJ

(You can see or change which version is imported under the "JS" tab of the settings modal in codepen)

### Environment

The problem occurs in both Firefox 114.0.1 and Chrome 114.0.5735.134 on Windows 10 Enterprise.

I initially encountered the problem when using deck.gl inside a Sveltekit app that's built with Vite.
I then tried several versions of deck.gl with a minimal example in codepen. 

These worked:

https://unpkg.com/deck.gl@8.2.0-beta.2/dist/dist.dev.js
https://unpkg.com/deck.gl@8.5.2/dist/dist.dev.js
https://unpkg.com/deck.gl@8.6.4/dist/dist.dev.js
https://unpkg.com/deck.gl@8.7.11/dist/dist.dev.js

https://unpkg.com/deck.gl@8.8.13/dist/dist.dev.js - after zooming in
https://unpkg.com/deck.gl@8.8.26/dist/dist.dev.js

These did not:

https://unpkg.com/deck.gl@v8.9.0-beta.1/dist/dist.dev.js
https://unpkg.com/deck.gl@v8.9.0-beta.4/dist/dist.dev.js
https://unpkg.com/deck.gl@8.9.0/dist/dist.dev.js
https://unpkg.com/deck.gl@8.9.1/dist/dist.dev.js
https://unpkg.com/deck.gl@8.9.19/dist/dist.dev.js

### Logs

There didn't seem to be anything useful logged to the console. The network inspector showed that the `fillPatternAtlas` and `fillPatternMapping` files are fetched even when the pattern fill isn't applied.

**Comment by abouroubi** [comment]
I'm having the same issue.
Do you have an idea where it can come from ? I can try to fix it.

**Comment by Pessimistress** [comment]
Fixed in v8.9.20.
