### ISSUE TITLE
Adjusting longitude to cross the Pacific removes ability to zoom in

### ISSUE THREAD

**Issue by EmilyFitzgerald** [visgl/deck.gl#7974]
### Description

Following up on bug report #7389, Unable to zoom in to the Americas with longitude adjusted to cross the Pacific. 

I've got a map where I have added 360 to the longitudes, in order to have the arcs and the trips travel across the Pacific (it's showing movement from the US to Australia and South East Asia). I've added this as has been recommended in other issue requests.

However, on doing this, when I try and zoom in to the United States, the arcs or trips move across to the next map in the wrap/loop, and so I can't zoom in on the map. wrapLongitude is set to false.

Previous report recommended to set repeat in the MapView, however this does not resolve it (as seen in the codepen below. Repeat is helpful when zooming out and does allow me to zoom in further than I could, but the arcs are still disappearing when zooming right in. 

[Short video to show what is happening](https://user-images.githubusercontent.com/44518869/177279237-7b22769e-ebc9-4c6c-8377-56b1cd04504c.mp4)

Is there any advice on how to stop this happening? Either a bounding box to keep the map within, or some other fix?

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Expect to be able to zoom in on all areas of the map and still see the arc layer

### Steps to Reproduce

[Codepen replicating the issue](https://codepen.io/fiej/pen/dyQvxyX)

### Environment

- Framework version: deck.gl@8.7.11
- Browser:
- OS:

### Logs

none.

**Comment by Pessimistress** [comment]
> wrapLongitude is set to false

Ser it to true and it will work. The prop is intended to solve this exact problem.

**Comment by EmilyFitzgerald** [comment]
Thank you - that has resolved the issue for the scatterplot, path, and arc layers on my map (I thought I had seen advice that said to set it to false when adjusting the longitude) - much appreciated. 

However, if I set wrapLongitude to true on the trips layer, it's having a great circle effect, were it  cuts off at 180 longitude instead of going across the Pacific (the trips aren't mid route in the screenshot). Code for this layer included below. I tried setting greatCircle to false, but that didn't do anything (which I did not expect it to, but thought it worth a shot!)

<img width="1629" alt="Screenshot 2023-06-30 at 1 38 03 am" src="https://github.com/visgl/deck.gl/assets/44518869/f2c85c5b-fa52-4325-870e-67c6cf71bf28">

```const tripsLayer = new TripsLayer({
    id: "trips-layer",
    data: props.selectedTrips,
    pickable: true,
    getPath: (d) => d.waypoints.map((p) => p.coordinates),
    getTimestamps: (d) => d.waypoints.map((p) => p.timestamp),
    getColor: (d) => d.map_color,
    wrapLongitude: true,
    opacity: 0.7,
    widthMinPixels: 8,
    jointRounded: true,
    capRounded: true,
    fadeTrail: true,
    trailLength: 0.8,
    currentTime: props.year,
    onHover: ({ object }) => (isHovering = Boolean(object)),
    onClick: (info) => {
      props.infoClick(
        info.object.name,
        info.object.waypoints[1].timestamp,
        info.object.event_sequence,
        info.object.audio,
        info.object.waypoints[0].placename,
        info.object.waypoints[1].placename
      );
    },
    visible: props.trips,
  });```

**Comment by Pessimistress** [comment]
If you want to adjust longitudes by hand, then don't use wrapLongitude. If you enable wrapLongitude, then you should keep the longitudes in the [-180, 180] as per GroJSON spec.

There is a [known issue](https://github.com/visgl/deck.gl/issues/5631) in TripsLayer handling timestamp across the 180th meridian. I'm going to close this issue now since it's confusing many things together. Open a discussion thread if you are unsure how to use these props.
