### ISSUE TITLE
[Bug] Abort signal not working with ScenegraphLayer

### ISSUE THREAD

**Issue by sprokazin** [visgl/deck.gl#7983]
### Description

One way to cancel requests for an existing layer is to use loadOptions.

`loadOptions: {
            fetch: {
              signal: abortSignal
            }
 }`

This method works great for Tile3DLayer: 

![image](https://github.com/visgl/deck.gl/assets/79312496/13b48966-2892-4f83-96e7-3fdf975dceae)

However, when I try to use the abortSignal in the same way for ScenegraphLayer, I get an error that crashes the app

![image](https://github.com/visgl/deck.gl/assets/79312496/62a86b67-cd00-4694-a26c-89aa75741d7f)

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

ScenegraphLayer should be able to handle abort signals properly. This is essential for the layers to work well with AbortController. Right now, I have no way to cancel requests for these layers, which leads to performance issues for the app, which keeps making unnecessary requests.

### Steps to Reproduce

I created a separate repository where I reproduced this error. The repository is open and accessible at this link: https://github.com/sprokazin/deck-cancel-glb. Steps to reproduce the bug:

1. Run the project.
2. Open the developer tools window, open the ‘Network’ tab
3. Check the box ‘Disable cache’
4. If you have a very fast internet, you can enable throttling
5. Refresh the page, and, before the request for loading the .glb model is completed, click on the Abort button in the top left corner of the window.
6. This action will cause an error, shown in the screenshot below

![image](https://github.com/visgl/deck.gl/assets/79312496/9477e5c5-0c28-4247-9358-4c7d8a4043ac)

### Environment

- Framework version: deck.gl@8.9.19
- Browser: Chrome 114.0.5735.199 
- OS: Windows 10, Windows 11, Ubuntu 22.04.2

**Comment by ibgreen** [comment]
Not a deck.gl issue.

**Comment by Pessimistress** [comment]
FYI the error message is a separate issue from the loader, see #7945
