### ISSUE TITLE
[Bug] Layers provided through `layers` react prop rendering below basemap provided as child

### ISSUE THREAD

**Issue by GeospatialMax** [visgl/deck.gl#7999]
### Description

We are passing our overlayers (GeojsonLayers, MVTLayers, CompositeLayers and H3HexagonLayers) as a prop to the Deck.gl component using the JSX syntax.
As a child of the Deck.gl component we are passing the `Map` component from `react-map-gl`.

```javascript
<DeckGL
  initialViewState={viewState}
  controller={{ doubleClickZoom: false }}
  layers={layers}
>
    <Map
      style={{ opacity: 0.5 }} // for debugging
      reuseMaps={isGlobalMap}
      mapboxAccessToken={MAPBOX_ACCESS_TOKEN}
      mapStyle={mapStyle}
      ref={mapboxRef}
      preserveDrawingBuffer={true}
      onLoad={onStaticMapLoaded}
      onError={onStaticMapLoaded}
    />
</DeckGL>
```

In this setup we are observing that all layers provided through the `layers` prop are rendered underneath the mapbox basemap (with opacity set to 0.5) they shine through)

We previously were on version 8.8.20 of deck.gl (which worked) but then stopped working for some peculiar reason. An upgrade to 8.9.21 didn't change anything.

Theoretically we could render our layers as children as well which potentially could alleviate this situation (though not sure about that) but we have some complex logic for generating those layers which I don't want to neccessarily inline as a child of the Deck.gl component (which seems to be the only option as the layers are not `real` JSX components).

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Layers provided as a prop to be rendered above the base map provided as a child to the Deck.gl component.

### Steps to Reproduce

- render deck.gl component in React as in example above
- pass react-map-gl Map component as child
- pass a GeojsonLayers as prop to Deck.gl

### Environment

- Framework version:
  - deck.gl@8.9.21
  - react-map-gl@7.1.2
- Browser:
  - Chrome@114.0.5735.199
  - Firefox@116.0b2
- OS: Windows 11

**Comment by Pessimistress** [comment]
react-map-gl v7.1 made a change that would cause this, see https://visgl.github.io/react-map-gl/docs/upgrade-guide#upgrading-to-v71

You need to check that your `@deck.gl/react` module is indeed upgraded to the latest.
