### ISSUE TITLE
[Bug] Typing: MVTLayer does not allow `highlightedFeatureId` to be `number`

### ISSUE THREAD

**Issue by ebbishop** [visgl/deck.gl#8005]
### Description

The type definition for `MVTLayerProps` permits `highlightedFeatureId`s that are `string | null | undefined`, which prevents setting a `highlightedFeatureId` that is a number: [mvt-layer.ts](https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/mvt-layer/mvt-layer.ts#L78)

This causes typescript to throw errors when attempting to highlight a feature (not using autoHighlight) that is a number.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

We are using feature ids that are numbers. The `MVTLayer` code itself does nothing that prevents this, including in [how it handles `highlightedFeatureId`](https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/mvt-layer/mvt-layer.ts#L329). The typings should reflect this and allow numbers.

### Steps to Reproduce

Example data (as geojson):
```json
{
"type": "FeatureCollection",
"name": "points",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "id": 2655581, "properties": {  }, "geometry": { "type": "Point", "coordinates": [ -63, 9 ] } },
{ "type": "Feature", "id": 2655582, "properties": {  }, "geometry": { "type": "Point", "coordinates": [ 47, 31 ] } },
{ "type": "Feature", "id": 2655583, "properties": {  }, "geometry": { "type": "Point", "coordinates": [ 112, 61 ] } },
{ "type": "Feature", "id": 2655584, "properties": {  }, "geometry": { "type": "Point", "coordinates": [ -63, 9 ] } },
{ "type": "Feature", "id": 2655585, "properties": {  }, "geometry": { "type": "Point", "coordinates": [ 48, 31 ] } },
{ "type": "Feature", "id": 2655586, "properties": {  }, "geometry": { "type": "Point", "coordinates": [ 96, 60 ] } }
]
}
```

### Environment

- Framework version: deck.gl@8.8.26
- Typescript: 4.9.5
- Browser: Chrome
- OS: MacOS 11.6.8

**Comment by Pessimistress** [comment]
Fixed in v8.9.22.
