### ISSUE TITLE
[Bug] H3ClusterLayer does not normalize longitudes

### ISSUE THREAD

**Issue by 4nthonylin** [visgl/deck.gl#8009]
### Description

H3 clusters that crosses the anti-meridian will wrap around the entire world.

![image](https://github.com/visgl/deck.gl/assets/4007580/9affd373-c95d-4f27-838a-9bf38f9c90c8)

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Expect to see a closed polygon when crossing the anti-meridian.

### Steps to Reproduce

https://codepen.io/4nthonylin/pen/MWzVgRB

### Environment

- Framework version: latest
- Browser: MS Edge
- OS: Windows

**Comment by 4nthonylin** [comment]
I have a PR to resolve this issue #8010. Would be great to get that merfed!

**Comment by 4nthonylin** [comment]
@Pessimistress Would it be possible to get an alpha release on top of 8.10? Currently using 8.10 for #7913 changes.

**Comment by Pessimistress** [comment]
Yes, however I need to warn you that we will not be able to make any further 8.10-alpha releases because we are about to merge some major breaking changes into the master branch.

**Comment by 4nthonylin** [comment]
Thanks for the heads up! Can't wait to see what the big changes are.

**Comment by 4nthonylin** [comment]
@Pessimistress Saw that an alpha package was released, thanks! However seeing a weird dependency issue.

Looks like the built package still has old h3-js calls.

https://unpkg.com/@deck.gl/geo-layers@8.10.0-alpha.2/typed/h3-layers/h3-hexagon-layer.js
'''js
import { h3ToGeoBoundary, h3GetResolution, h3ToGeo, geoToH3, h3IsPentagon, h3Distance, edgeLength, UNITS } from 'h3-js';
'''

But the source has the updated functions 
'''ts
import {
  getResolution,
  cellToLatLng,
  latLngToCell,
  isPentagon,
  gridDistance,
  getHexagonEdgeLengthAvg,
  H3Index
} from 'h3-js';
'''

Is this expected?

**Comment by Pessimistress** [comment]
They should not be published, but the js files in /typed are not used: https://unpkg.com/browse/@deck.gl/geo-layers@8.9.22/typed/package.json
