### ISSUE TITLE
[Feat] mapbox / maplibre basemap as deck.gl layer

### ISSUE THREAD

**Issue by sup3rcow** [visgl/deck.gl#8011]
### Target Use Case

Hi,
I want to import maplibre basemap in deck.gl map as a layer, so I can control z-index in relation with other deck.gl layers.
Instead of importing all deck.gl layers inside maplibre map like in documentation (MapboxLayer, MapboxOverlay), I wish we can do the opposite.

### Proposal

Exactly like in this openlayers example
https://openlayers.org/en/latest/examples/mapbox-vector-layer.html

**Comment by ibgreen** [comment]
@sup3rcow It is not too hard to implement a minimal basemap deck.gl layer by iterating through the easily parsed mapbox styles and then rendering with the deck.gl MVTLayer, TextLayer etc. I suppose this won't make you happier to know but about a year ago I tried to open source the BasemapLayer we are using internally but unfortunately ran out of time.

Of course really good handling of texts etc to match the rendering quality of mapbox or maplibre takes a lot of work but one can get reasonable results quite quickly.

**Comment by sup3rcow** [comment]
Thak you for quick answer. Yes I was thinking about MVTLayer, but than I need to configure every osm layer style individually, I can't just pass osm style.json to layer configuration.

If this is not a good suggestion for a new feature, should I close the issue?
