### ISSUE TITLE
[Bug] CesiumIon tilesets from "asset depot" are failing to load

### ISSUE THREAD

**Issue by belom88** [visgl/deck.gl#8013]
### Description

CesiumIon has changed tileset urls for assets from [Asset Depot](https://ion.cesium.com/assetdepot) so they don't load. Private tilesets work as expected.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

* Open https://deck.gl/examples/tile-3d-layer
* The tileset is not loaded

### Environment

- Framework version: deck.gl@latest
- Browser: Chrome
- OS: Ubuntu

**Comment by Pessimistress** [comment]
Fixed in v8.9.22.
