### ISSUE TITLE
[Feat] New numOfSegments parameter in ArcLayer to achieve smooth lines on long paths with greatCircle param enabled

### ISSUE THREAD

**Issue by karsta26** [visgl/deck.gl#8052]
### Target Use Case

Currently, ArcLayer has a hardcoded number of segments - 50. 

_modules/layers/src/arc-layer/arc-layer.ts_
```js
protected _getModel(): Model {
    let positions: number[] = [];
    const NUM_SEGMENTS = 50;
    for (let i = 0; i < NUM_SEGMENTS; i++) {
      positions = positions.concat([i, 1, 0, i, -1, 0]);
    }

    const model = new Model(this.context.device, {
      ...this.getShaders(),
      id: this.props.id,
      geometry: new Geometry({
        drawMode: GL.TRIANGLE_STRIP,
        attributes: {
          positions: new Float32Array(positions)
        }
      }),
      isInstanced: true
    });

    model.setUniforms({numSegments: NUM_SEGMENTS});

    return model;
  }
```

When this value is a good fit for the majority of cases, for long arcs when great circle parameter is used, the path that is produced is not smooth. 

This is visible in the docs of the GreatCircle Layer:

https://deck.gl/docs/api-reference/geo-layers/great-circle-layer
![image](https://github.com/visgl/deck.gl/assets/24994759/85ef8972-74dc-456b-8c53-ce73c5c4f52f)

The longer the path is, the more edges are on the path.
It would be good to have the option to modify the hardcoded value to create smooth lines.

### Proposal

The proposition is to add a new parameter to ArcLayer. The name can be numOfSegments (or something similar). 
This new parameter would be taken instead of a current hardcoded value. For backward compatibility, the default value would still be 50. 

### Proposition of change:
```js
  protected _getModel(): Model {
    const {numOfSegments} = this.props;
    let positions: number[] = [];
    for (let i = 0; i < numOfSegments; i++) {
      positions = positions.concat([i, 1, 0, i, -1, 0]);
    }

    const model = new Model(this.context.device, {
      ...this.getShaders(),
      id: this.props.id,
      geometry: new Geometry({
        drawMode: GL.TRIANGLE_STRIP,
        attributes: {
          positions: new Float32Array(positions)
        }
      }),
      isInstanced: true
    });

    model.setUniforms({numSegments: numOfSegments});

    return model;
  }
```

### Current approve to achieve the same:
Currently, to achieve smooth lines we can use this code:

```js
import { ArcLayer } from 'deck.gl'
import {Model} from '@luma.gl/engine';
import {GL} from '@luma.gl/constants';

export class MyLayer extends ArcLayer
{
  getGeometry(numOfSegments)
  {
    let positions = []
    for (let i = 0; i < numOfSegments; i++)
    {
      positions = positions.concat([i, 1, 0, i, -1, 0])
    }

    return new Geometry({ drawMode: GL.TRIANGLE_STRIP, attributes: { positions: new Float32Array(positions) } })
  }

  updateState(opts)
  {
    super.updateState(opts)

    const NUM_SEGMENTS = 500
    this.state.model
      .setUniforms({ numSegments: NUM_SEGMENTS })
      .setGeometry(this.getGeometry(NUM_SEGMENTS))
  }
}

MyLayer.layerName = 'MyLayer'
```

It works, but It would be good to add it to the ArcLayer itself.

**Comment by felixpalmer** [comment]
Seems like a reasonable addition, seeing as you've basically written the code - could you create a PR? Note that if you make this a prop, you will need to handle the case of the prop changing also

**Comment by ibgreen** [comment]
Agree this seems reasonable. 

A minimal concern: received wisdom says that using a dynamic loop length in shaders can affect performance negatively. Static loops are sometimes "unrolled" by the shader compiler to remove branching overhead, though I wonder if that is still the case when the loop has 50 iterations like we did. There may be other magic tricks in play as well inside the shader compiler / graphics driver, so ultimately only perf testing on different GPUs can say for sure. But I suspect it is not an issue worth worrying about here.

**Comment by karsta26** [comment]
Ok, I will create a PR, thanks
