### ISSUE TITLE
GPU Process sometimes sticks at 100% when just viewing the deck.gl home page

### ISSUE THREAD

**Issue by BrianAdams** [visgl/deck.gl#8058]
### Description

When going to the homepage for https://deck.gl/ the GPU process maxes out 50% of the CPU capacity on the workstation.  This has been an issue that seems to have come and go over the last year that I have been using the library. Restarting the browser instances does not seem to help.
![image](https://github.com/visgl/deck.gl/assets/1471826/3f16d032-6507-4704-ada4-cff8a46f2c7f)

Sorry to drop such a open ended ticket, but this is a behavior I have seen for a while. I tend to recall this happening on multiple OS's over the last year.  I figure at least opening the issue means I documented case and the possibility others might have seen this happen as well.  It is of course possible this is something getting borked in the OS/Drivers that deck.gl just suffers from.

At this point I am not sure what other information I could pull to help isolate what is going on.  A good outcome could be pointers to what other tools or details I could use to narrow down this case.  I have a second machine with an very similar setup that sitting on the home page seems to do closer to 20% in the GPU Process.  

It "feels" like it is possible to get a system in such a state that this library gets stuck causing super high cpu/gpu utilization. Almost as if the system is falling back to software rendering.  I will update if restarting makes a difference in clearing the issue.  I do expect that it will "go away" at some point and then come back again in the future.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Viewing the basic demos of the geck.gl like on the home page should not max out the cpu/gpu.

### Steps to Reproduce

Go to https://deck.gl/

### Environment

- Framework version: I've seen this on v8.8.23 and v.8.9.23 that I have run my own visualizations from. Seeing it on whatever version is running on the main site today.
- Browser: Brave 1.52.129 Chromium: 114.0.5735.198 (Offical Build) (64-bit)
- OS: Linux (NixOS 23.05)
- Using Wayland
- Kernel: Linux 6.4.2
- Graphics: Using the Intel integrated GPU 
- Running 2 monitors in extended mode
- Gnome 44.2 window manager

### Logs

Just the "trips: rounded" deprication warning in the console

**Comment by BrianAdams** [comment]
So I did a fresh start of the system and went straight to the deck.gl page.  The visualization would not render with the following error.

![Screenshot from 2023-08-16 13-35-08](https://github.com/visgl/deck.gl/assets/1471826/b8fc87d3-07c5-4c36-b87b-02659fbd2108)

I then had to cycle through the examples till I found one that would load, the meteor count, and I see these errors in the console:
![Screenshot from 2023-08-16 13-36-39](https://github.com/visgl/deck.gl/assets/1471826/005aa33c-8469-4820-b659-0ec8b5e80726)

And now if I navigate back to the home page I get the high CPU form the GPU Process

![Screenshot from 2023-08-16 13-36-56](https://github.com/visgl/deck.gl/assets/1471826/64495e04-2231-4b83-bd1c-50a7994635ff)

**Comment by BrianAdams** [comment]
Well okay then, looks like my hardware acceleration got removed for some reason. Closing for now as this looks like the core of the problem.
![image](https://github.com/visgl/deck.gl/assets/1471826/4c3b40ee-b418-4b72-a639-5c49ce423a11)

**Comment by ibgreen** [comment]
Thanks for following up. FWIW - We have been discussing making and effort to detect software renderers in luma.gl during context creation (using the `failIfMajorPerformanceCaveat` flag) and warn in the console if we detect it, to save people from having to go through what you just did. 

Whether it would actually work depends on whether the browser would fail to create a context on your system without acceleration with that flag set, we haven't done the necessary testing.
