### ISSUE TITLE
[Bug]: Layers are sinking under Mapbox Terrain

### ISSUE THREAD

**Issue by belom88** [visgl/deck.gl#8060]
### Description

I'm trying to use `ScenegraphLayer` with `Mapbox 2` terrain in interleaved mode.
Having the correct z-value a model only seen on high `pitch` value close to 90 degrees. If I tilt the camera to a lower `pitch` value, the layer sinks under terrain.
Example to reproduce: https://stackblitz.com/edit/js-njts6h?file=index.js (Mapbox token required)
<img width="296" alt="image" src="https://github.com/visgl/deck.gl/assets/18549629/d0804909-bd0a-49e6-9d3b-d84b29efb1de">
<img width="276" alt="image" src="https://github.com/visgl/deck.gl/assets/18549629/748d3ed8-edb1-4a55-b094-c809fb9dc4b1">
<img width="295" alt="image" src="https://github.com/visgl/deck.gl/assets/18549629/6a2c6498-0e39-4f11-a505-5fa735e073df">

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The layer position don't change when I tilt a map with terrain.

### Steps to Reproduce

* Create mapbox map with terrain;
* Add a layer created with `MapboxLayer` class

### Environment

- Framework version: 8.9.25
- Browser: Chrome 116.0.5845.96 (Official Build) (64-bit)
- OS: Windows 11

**Comment by Pessimistress** [comment]
My guess is that deck's projection matrix near/far planes do not match those of mapbox when terrain is on.

**Comment by piergiorgio-roveda** [comment]
Hi there,

I've encountered the same error while working with Mapbox and DeckGL for 3D visualization using GeoJSON. Has there been any progress in resolving this issue? I'm eager to get this sorted out as it's affecting my project's visualization. Any updates or suggestions on a workaround would be greatly appreciated. Thanks for your efforts in addressing this matter!

Best regards,
Pj

https://github.com/visgl/deck.gl/assets/74056468/103ec74d-fc5b-4ba9-bdef-a4bcab2f569c

**Comment by felixpalmer** [comment]
@piergiorgio-roveda @belom88 could you ask on the Mapbox project for clarity on how the projection matrix changes when terrain is enabled?

**Comment by piergiorgio-roveda** [comment]
@felixpalmer good suggestion. I wait if someone reply to my question in Mapbox. Otherwise I try to mix some coordinate system between mapbox and deck, with the same result

**Comment by Pessimistress** [comment]
Fix in v8.9.28

**Comment by piergiorgio-roveda** [comment]
https://github.com/visgl/deck.gl/assets/74056468/da8988aa-fb97-4c4d-8c3b-76037b9f8118

Perfect! Thx, Pj.
