### ISSUE TITLE
[Bug] TileLayer set at visible: false initially load, expect none

### ISSUE THREAD

**Issue by plgagnon2** [visgl/deck.gl#8061]
### Description

(Might be similar to https://github.com/visgl/deck.gl/issues/6747 ??)

Easy to test

https://codepen.io/Pierre-Luc-Gagnon-the-styleful/pen/JjwjqaY?editors=001

In the fiddle, when I initially sets TileLayer visible: false you can still see OpenLayers tiles being retreived in networks (when I expected none).
If you zoom in/out (with the mousewheel, no visible feedback in the codepen sadly, but easy to see it works with visible: true), it works as expected i.e; it does not try to fetch tiles.

### Flavors

- [x] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Tiles are not fetched

### Steps to Reproduce

- Use codepen https://codepen.io/Pierre-Luc-Gagnon-the-styleful/pen/JjwjqaY?editors=001
- Visible: false
- Show dev tools/networks
- See OpenLayers tiles being loaded

### Environment

- Framework version: Latest
- Browser: Chrome
- OS: Windows 10

**Comment by Pessimistress** [comment]
This is expected behavior. If you have another layer e.g. ScatterplotLayer with `data` prop set to an URL, it will attempt to fetch the content and create the CPU/GPU resources regardless of `visible` settings. As documented, `visible:false` only guarantees that a layer is not rendered, not that it does nothing at all.

If you want no network traffic whatsoever, you should delay adding that layer until it is ready to be displayed.

**Comment by plgagnon2** [comment]
> This is expected behavior. If you have another layer e.g. ScatterplotLayer with `data` prop set to an URL, it will attempt to fetch the content and create the CPU/GPU resources regardless of `visible` settings. As documented, `visible:false` only guarantees that a layer is not rendered, not that it does nothing at all.
> 
> If you want no network traffic whatsoever, you should delay adding that layer until it is ready to be displayed.

I see, I was under the impression due to https://github.com/visgl/deck.gl/issues/6747 which is marked as closed that this was not expected

**Comment by plgagnon2** [comment]
@Pessimistress Is there another way I could proceed to make the tiles not fetched while visible: false? Maybe overwrite something I dunno :X
