### ISSUE TITLE
[Bug] GoogleMapsOverlay in 3D, zooming/tilting rapidly feels bad

### ISSUE THREAD

**Issue by plgagnon2** [visgl/deck.gl#8062]
### Description

Hi, I noticed these issues when playing with GoogleMapsOverlay + TileLayer/BitmapLayer.

I recorded two sessions just in case its not apparent on codepen
- In my app: https://youtu.be/g-mM_qpTBCI
- On codepen, similar issue: https://youtu.be/JDcnXRxUQDU
    - Here in Boston you can see weird result with tiling+tilt (University of Illinois at Chicago) https://i.imgur.com/3zdJwZu.png

You can see alot of flickering, blured/incorrect tiles loaded at certain zoom/tilt level (pay attention to end of both videos for tilt, you can see when I play with it slowly, some OpenStreetMap tiles seems to switch resolution which result in being blured and pretty bad res)

(If anyone looking for a way to fix/bypass this, I use google.maps.ImageMapType on Gmap instead atm. It behave much smoothier/without flickering, but I expect problems when I add other kinds of layers in GoogleMapsOverlay)

https://codepen.io/Pierre-Luc-Gagnon-the-styleful/pen/oNJNRKB

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

- No flickering
- No bad res / blurry tiles

### Steps to Reproduce

- Use this codepen https://codepen.io/Pierre-Luc-Gagnon-the-styleful/pen/oNJNRKB
- Zoom in somewhere you can fully use tilt
- Zoom/Tilt aggressivly XD

### Environment

- Framework version: 8.9.23
- Browser: Chrome
- OS: Windows 10

**Comment by Pessimistress** [comment]
I'm not sure what this has to do Google Maps. Your demos are very confusing with labels from both Google and OSM.

If you just have an issue with which tiles are being displayed, you can play with [refinementStrategy](https://deck.gl/docs/api-reference/geo-layers/tile-layer#refinementstrategy).

**Comment by plgagnon2** [comment]
> 

Well in my codepen I am using Gmap + OpenStreetMap tiles but any tile service will have the same flickering problem when zooming/tilting

**Comment by plgagnon2** [comment]
> I'm not sure what this has to do Google Maps. Your demos are very confusing with labels from both Google and OSM.
> 
> If you just have an issue with which tiles are being displayed, you can play with [refinementStrategy](https://deck.gl/docs/api-reference/geo-layers/tile-layer#refinementstrategy).

Well in my codepen I am using GoogleMapsOverlay + OpenStreetMap tiles but with any tile service it will have the same flickering problem when zooming/tilting

**Comment by ibgreen** [comment]
Just out of curiosity, did you bother to try changing `refinementStrategy` as suggested?

**Comment by plgagnon2** [comment]
> Changing `refinementStrategy` is basically necessary in some cases, e.g. if you have a semi-transparent tile layer.

But hum, I dont think theres transparency on OSM tiles in this case?

**Comment by Pessimistress** [comment]
> Well in my codepen I am using GoogleMapsOverlay + OpenStreetMap tiles but with any tile service it will have the same flickering problem when zooming/tilting.

Your issue is making it sound like this is only a problem when using TileLayer with Google Maps. If that's not the case I suggest you rephrase your title/change your codepen so we can focus on the real issue.

**Comment by plgagnon2** [comment]
Alright I will close look into this and closing this, tyvm everyone!
