### ISSUE TITLE
[Bug] Configuring the `GeoJsonLayer` with `getLineWidth: 0` results in barely perceptible outlines.

### ISSUE THREAD

**Issue by DanielBoa** [visgl/deck.gl#8070]
### Description

Configuring a `GeoJsonLayer` to have a line width of 0 and a transparent line colour results in features having a very faint but noticeable outline. I'd expect this to render as though `stroked` was set to `false`.

As a workaround you can have the `getLineColor` accessor return the same value as `getFillColor` for features you don't want to have a border.

![image](https://github.com/visgl/deck.gl/assets/1169866/789d1b17-e3d0-46b0-85cb-9f0ede832954)
*Points with a subtle but perceptible outline, despite `getLineWidth` returning `0`. See CodeSandbox link below for this demo.*

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

https://codesandbox.io/s/geojsonlayer-phantom-outline-issue-rjjphq

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
[pointAntialiasing](https://deck.gl/docs/api-reference/layers/geojson-layer#pointtypecircle-options)

**Comment by DanielBoa** [comment]
Ah cool that also fixes it, does mean that the exposed edges of the points don't look very good though so I'll likely stick to the other workaround I mentioned.
