### ISSUE TITLE
[Bug] TileLayer.isLoaded leads to a crash

### ISSUE THREAD

**Issue by ilyabo** [visgl/deck.gl#8073]
### Description

Calling `tileLayer.isLoaded()` may lead to a crash when called early before `selectedTiles` is initialized in `tileset`.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

There should be no crash when calling `tileLayer.isLoaded()`.

### Steps to Reproduce

In summary: Create a TileLayer and call `tileLayer.isLoaded()` just after creation.
Has been observed in FSQ Studio.
Will try to come up with a minimal example.

### Environment

- Framework version: 8.9.12
- Browser: Chrome 114
- OS: Mac OS

**Comment by Pessimistress** [comment]
8.9.27
