### ISSUE TITLE
[Bug] GlobeView + react-map-gl globe 

### ISSUE THREAD

**Issue by wangxiaogang94** [visgl/deck.gl#8075]
### Description

when deck.gl GlobeView + react-map-gl globe, the size of the earth is inconsistent.
![image](https://github.com/visgl/deck.gl/assets/51105411/8360f6d9-033d-471a-a7ff-44ba3aff4b23)

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I hope to use deck.gl to load the 3D scene in the global mode of mapbox, but if the globalView is not used, the base of the layer of the deck is a plane; if the globalView is used, the earth is not the same size

### Steps to Reproduce

```js
import { ScenegraphLayer } from '@deck.gl/mesh-layers';
import DeckGL from '@deck.gl/react';
import {_GlobeView as GlobeView} from '@deck.gl/core';
import { Map } from 'react-map-gl';
import mapStyle from '../../assets/mapStyle';

const mapboxgl = window.mapboxgl;

const MODEL_URL =
  'https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/scenegraph-layer/airplane.glb';

const INITIAL_VIEW_STATE = {
  latitude: 30,
  longitude: 120,
  zoom: 5,
  bearing: 0,
  pitch: 10,
};

export default function Root() {
  const list = [];
  for (let index = 0; index < 1000; index++) {
    list.push({
      lng: 360 * Math.random() - 180,
      lat: 160 * Math.random() - 80,
      height: 100000 * Math.random(),
      orientatio: 360 * Math.random(),
    });
  }
  const layer = new ScenegraphLayer({
    data: list,
    type: ScenegraphLayer,
    sizeScale: 25,
    scenegraph: MODEL_URL,
    sizeMinPixels: 0.7,
    getPosition: (d) => {
      return [d.lng || 0, d.lat || 0, d.height || 0];
    },
    getOrientation: (d) => [0, 180 + d.orientatio, 90],
  });
  return (
    <DeckGL
      initialViewState={INITIAL_VIEW_STATE}
      layers={[layer]}
      controller={true}
      views={new GlobeView()}
    >
      <Map
        mapLib={mapboxgl}
        initialViewState={INITIAL_VIEW_STATE}
        mapStyle={mapStyle.myNight as any}
        projection={'globe' as any}
        fog={{}}
      >
      </Map>
    </DeckGL>
  );
}


```

### Environment

- Framework version: deck.gl@8.9.23    react-map-gl@7.1.3
- Browser: 116.0.5845.96
- OS: macOS Monterey 12.3.1

**Comment by Pessimistress** [comment]
GlobeView does not currently support integration with any base map. There is already a feature request #7920.

**Comment by VieVaWaldi** [comment]
Please add that limitation to the docs (https://deck.gl/docs/api-reference/core/globe-view). I dont even want to know how much time i wasted trying to sync mapbox with globeview.
