### ISSUE TITLE
[Bug] Cannot build Carto example 

### ISSUE THREAD

**Issue by jaanli** [visgl/deck.gl#8079]
### Description

Hi! This library is awesome -- however, having some trouble using the Carto example here: https://deck.gl/examples/carto

It runs locally: 

![image](https://github.com/visgl/deck.gl/assets/5317244/b2ba30b3-a106-472d-a130-429144171b52)

However, running `npm run build` results in this error:

```
[ERROR] Docusaurus server-side rendering could not render static page with path /metropolitan-areas/new-york.


Error: Cannot find module './assets/js/158.70b6f3cc.js'
Require stack:
- main
    at Array.reduce (<anonymous>)
[WARNING] {"moduleIdentifier":"/Users/me/maps.payless.health-refreshed/node_modules/@loaders.gl/worker-utils/dist/esm/lib/node/require-utils.node.js","moduleName":"./node_modules/@loaders.gl/worker-utils/dist/esm/lib/node/require-utils.node.js","loc":"12:9-26","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/me/maps.payless.health-refreshed/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/me/maps.payless.health-refreshed/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/me/maps.payless.health-refreshed/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

This seems like it happens elsewhere too: https://stackoverflow.com/questions/74991964/critical-dependency-the-request-of-a-dependency-is-an-expression-for-loader-gl

At @onefact we are using this to visualize 176 hospitals' prices and quality in the New York area (non-profit), so would love to get this working if possible before the OpenVis summit in 2 weeks! 

Grateful for any help 🙏 and cc @alasarr in case they might have input.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

### Expected Behavior

https://deck.gl/examples/carto (code: https://github.com/visgl/deck.gl/blob/8.9-release/website/src/examples/carto.js)

### Steps to Reproduce

To reproduce: 

1. `git clone https://github.com/onefact/maps.payless.health.git`
2. `npm install`
3. `npm run start` -- check that you can see it locally:
![image](https://github.com/visgl/deck.gl/assets/5317244/56c6cf67-90fd-4935-afe5-a36ba901dfeb)
4. `npm run build` -- results in the following error:
```
[INFO] [en] Creating an optimized production build...



✔ Client


✖ Server
  Compiled with some errors in 21.55s

[ERROR] Docusaurus server-side rendering could not render static page with path /metropolitan-areas/new-york.


Error: Cannot find module './assets/js/158.70b6f3cc.js'
Require stack:
- main
    at Array.reduce (<anonymous>)
[WARNING] {"moduleIdentifier":"/Users/me/projects/maps.payless.health/node_modules/@loaders.gl/worker-utils/dist/esm/lib/node/require-utils.node.js","moduleName":"./node_modules/@loaders.gl/worker-utils/dist/esm/lib/node/require-utils.node.js","loc":"12:9-26","message":"Critical dependency: the request of a dependency is an expression","compilerPath":"server"}
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/me/projects/maps.payless.health/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/me/projects/maps.payless.health/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/me/projects/maps.payless.health/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[INFO] Docusaurus version: 2.4.1
Node version: v20.5.0
```

### Environment

- Framework version: deck.gl@8.9.0
- Browser: Chrome 
- OS: Mac  Ventura 13.4.1 (c)

**Comment by Pessimistress** [comment]
@ibgreen I believe this is from webpack trying to bundle for server side, and require-utils.node contains a dynamic `require` call.

**Comment by jaanli** [comment]
Interesting, thank you @Pessimistress and @ibgreen ! 

I just restarted from scratch with `vite`, and it seems to work fine: https://vite-react-test-theta.vercel.app/ (code: https://github.com/onefact/vite-react-test) 

So I wonder what the issue is with docasaurus! Hopefully this helps us binary search to pinpoint the issue. 

(On my end, I'll be trying to plug in hospital prices into this visualization and link to dashboards of public hospital prices we've been making: https://beta.payless.health/examples/mount-sinai.html)

Appreciate the help!! 🙏

**Comment by Pessimistress** [comment]
I just rebuilt the deck.gl website, which uses docusaurus, with the latest release. The "Critical dependency" warning is still present, but does not block the build. At this point I don't think this specific issue is caused by deck or loaders. Feel free to reopen if you can provide a minimal repo that reproduces the issue.
