### ISSUE TITLE
Model matching geojson

### ISSUE THREAD

**Issue by YIYOU27** [visgl/deck.gl#8088]
### Description

https://github.com/visgl/deck.gl/assets/45561106/0f25f830-44a0-4424-a5f6-7d76403766d6

The line is geojson, and neither geojson nor the model has elevation. The production of the model is generated by loading geojson into a shp file using Blender's plugin Blender GIS. Importing into deck.gl does not match geojson. Reduce the model for adaptation, but there are still local areas that cannot be matched, and as the perspective zooms in, zooms out, and drags, it is obvious that there has been an offset. I don't know what caused it. Geojson and the model are both large in size, several tens of kilometers. Looking forward to your reply. Thank you very much. (Machine Translation)

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Is there any way to generate large-sized models using geojson or shp, which can perfectly match geojson on deck. gl

### Steps to Reproduce

geojson ----> shp ----->blender ---->glb ≠ geojson

### Environment

- Framework version:deck.gl@8.9.7
- Browser: Chrome  116.0.5845.111
- OS:

### Logs

no

**Comment by Pessimistress** [comment]
We cannot debug from a video. Please use Discussions to get generic help.
