### ISSUE TITLE
[Bug] DataFilterExtension mess up with scenegraph colors

### ISSUE THREAD

**Issue by ricardoekm** [visgl/deck.gl#8099]
### Description

When adding the DataFilterExtension to a scenegraph layer all models are rendered black.

Codepen: https://codepen.io/ricardoekm/pen/qBLRaWy

### Flavors

- [X] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Add a DataFilterExtension to a scenegraph layer.
Codepen: https://codepen.io/ricardoekm/pen/qBLRaWy

### Environment

- Framework version: 8.9
- Browser: Chrome
- OS: Mac

**Comment by Pessimistress** [comment]
Fixed in v8.9.28
