### ISSUE TITLE
[Bug] Using `getPixelOffset` in TextLayer with `CollisionFilterExtension` hides all

### ISSUE THREAD

**Issue by kahole** [visgl/deck.gl#8104]
### Description

When using `TextLayer` with a sufficiently large pixel offset e.g. `[0, -24]` the CollisionFilterExtension filters out everything. 

Similar problems occur when using a sufficiently large `lineHeight`.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Correct collision detection and filtering based on the labels new offset position.

### Steps to Reproduce

Example:
https://codepen.io/KaHole/pen/QWzpGYV

### Environment

- Framework version: 8.9.27
- Browser: Chrome
- OS: MacOS

**Comment by felixpalmer** [comment]
The CollisionFilterExtension works by showing features whose anchor point is within their rendered hit-area bounds and isn't overlapped by another feature's hit-area. When the hit-area is moved using `getPixelOffset` no features will be shown. To fix this you need to modify the hit-area that is drawn.

For the text label case you can use [PointLabelLayer](https://github.com/visgl/deck.gl/blob/master/modules/carto/src/layers/point-label-layer.ts), see [demo](https://jsfiddle.net/felixp/hvjo5xLt/)

**Comment by Fabioni** [comment]
Together with the geojsonlayer the problem described here is a major problem. Just pointing to a `carto` layer without any documentation does not seem like a appropriate fix for this problem.

**Comment by kahole** [comment]
I found a hacky workaround that works quite well for us.
Instead of using `pixelOffset` or `getAlignmentBaseline`, we create a offset using new lines and invisible unicode characters.
The collision filter becomes quite "greedy", but nothing close to the problems with pixel-offsets.

```ts
   const blankBraileChar = '⠀'; //https://www.compart.com/en/unicode/U+2800
const deckgl_textlayer_default_charset =
  ' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~';

const expandedCharset = deckgl_textlayer_default_charset + blankBraileChar;

new TextLayer({
  getText: (e) => {
    return `${e.name}\n${blankBraileChar}\n${blankBraileChar}`;
  },
  characterSet: textlayer_expanded_charset,
  extensions: [new CollisionFilterExtension()],
  //...
```

**Comment by felixpalmer** [comment]
@Fabioni I'm not sure what you're referring to with "geojsonlayer", could you eloborate? I agree we should add docs, I'll add it to my list. However the example I posted is pretty straightforward, so I'm not sure why you're resorting to the hacky workaround @kahole

**Comment by kahole** [comment]
We had major issues with texture resources exhaustion, leading to crashes, using the PointLabelLayer.

**Comment by felixpalmer** [comment]
@kahole if you could create an issue with a jsfiddle or similar demonstrating the crash that would be helpful :) 

@Fabioni The `PointLabelLayer` can be used as a drop-in replacement in `GeoJsonLayer` via `_subLayerProps`:

```ts
const layer = new GeoJsonLayer({
  // ...
  _subLayerProps: {
    'points-text': {
      type: PointLabelLayer,
      extensions: [collisionFilterExtension],
    }
  }
});
```
