### ISSUE TITLE
CompositeLayer hover highlight unexpected

### ISSUE THREAD

**Issue by ouzhou** [visgl/deck.gl#8106]
### Description

To highlight the unexpected, you can utilize `this.getSubLayerRow()` to divide the data into separate arrays. This way, you can filter the source data into two sections and then supply each section to different layers for their respective purposes.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

This line uses `lastPickedInfo.info`, so the resulting index is as expected, similar to onHover. However, `_pickClosestObject` finds a different index. Therefore, `deck.deckPicker.lastPickedInfo.index !== deck.deckPicker.lastPickedInfo.info.index`.

### Steps to Reproduce

https://stackblitz.com/edit/stackblitz-starters-fhazpk?file=src%2FApp.tsx

There are two lines in total, hovering on either line will highlight all lines

### Environment

- Framework version: "deck.gl": "^8.9.27",
- Browser: chrome
- OS: macos

**Comment by Pessimistress** [comment]
Data created from `getSubLayerRow` does not automatically propagate to picking index. You'll have to override the default picking color accessor:

```js
class CustomLineLayer extends LineLayer {
  initializeState() {
    super.initializeState();
    const { gl } = this.context;

    this.getAttributeManager().addInstanced({
      instancePickingColors: {
        size: 3,
        type: gl.UNSIGNED_BYTE,
        accessor: (object, { index, target: value }) =>
          this.encodePickingColor(
            object && object.__source ? object.__source.index : index,
            value
          ),
      },
    });
  }
}
```

https://stackblitz.com/edit/stackblitz-starters-rpvsq1

**Comment by ouzhou** [comment]
thanks!

any plain to add 
```
  accessor: (object, { index, target: value }) =>
          this.encodePickingColor(
            object && object.__source ? object.__source.index : index,
            value
          ),
```
into https://github.com/visgl/deck.gl/blob/e9a8403fbd7d8cd7d48e2d18bb881e0718103112/modules/core/src/lib/layer.ts#L860

**Comment by Pessimistress** [comment]
No. Picking colors buffer is currently reused between layers for performance.

**Comment by ouzhou** [comment]
find better solution in `geojson-layer`
like
```
  getPickingInfo(params): GeoJsonPickingInfo {
    const info = super.getPickingInfo(params) as GeoJsonPickingInfo;
    const {index, sourceLayer} = info;
    info.featureType = FEATURE_TYPES.find(ft => sourceLayer.id.startsWith(`${this.id}-${ft}-`));
    if (index >= 0 && sourceLayer.id.startsWith(`${this.id}-points-text`) && this.state.binary) {
      info.index = (this.props.data as BinaryFeatures).points.globalFeatureIds.value[index];
    }
    return info;
  }

  _updateAutoHighlight(info: GeoJsonPickingInfo): void {
    // All sub layers except the points layer use source feature index to encode the picking color
    // The points layer uses indices from the points data array.
    const pointLayerIdPrefix = `${this.id}-points-`;
    const sourceIsPoints = info.featureType === 'points';
    for (const layer of this.getSubLayers()) {
      if (layer.id.startsWith(pointLayerIdPrefix) === sourceIsPoints) {
        layer.updateAutoHighlight(info);
      }
    }
  }
```

**Comment by ouzhou** [comment]
https://stackblitz.com/edit/stackblitz-starters-frchev?file=src%2FApp.tsx
