### ISSUE TITLE
[Bug] MaskExtension show interactivity in features filtered

### ISSUE THREAD

**Issue by aaranadev** [visgl/deck.gl#8125]
### Description

That mask extension isn't working properly, the features are filtered but the interactivity is enable, the hover and click are available.

The example is available in the doc official.

https://codepen.io/vis-gl/pen/ExbKoYg

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

- Add a new layer with Mask Extension
- Add a mask layer

### Environment

- Framework version: deck.gl@8.9.29
- Browser: Chorme 117
- OS: macOS 13

**Comment by felixpalmer** [comment]
Fixed in 8.9.31
