### ISSUE TITLE
[Doc] Is there any good example of using PROTOBUF or arrow on how we can leverage that for large data sets

### ISSUE THREAD

**Issue by dhruv4kubra** [visgl/deck.gl#8151]
### Description

Hi,
I am looking to see if i could use protobuf for performance improvement. I see thats a recommeded way in "Performance Optimization" but nothing concrete is showcased as example or documentation in using it. 

If there are links or references further that i could refer to will be greatly appreciated.

-Drew

**Comment by Pessimistress** [comment]
![Screen Shot 2023-09-29 at 10 22 00 AM](https://github.com/visgl/deck.gl/assets/2059298/637aae61-77ef-4818-9460-4fb75249b26f)
