### ISSUE TITLE
[Bug] Binary attributes do not work fully in v9

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8152]
### Description

Passing binary attributes does not work fully against the v9 API. @Pessimistress @ibgreen this is a well known issue, e.g. referenced [here](https://github.com/visgl/deck.gl/pull/8138), tracking it here to give visibility that I'm working on it.

It is possible to render using binary attributes, however in v9 the attribute `size` is not respected and the binary data passed must have the correct dimension, e.g. 3D positions work, 2D do not.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

The following test app is useful to demonstrate the issue.

```javascript
import {Deck} from '@deck.gl/core';
import {ScatterplotLayer} from '@deck.gl/layers';

const AIRPORTS =
  'https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/line/airports.json';

async function init() {
  const response = await fetch(AIRPORTS);
  const data = await response.json();

  // Requirements:
  // - Needs to be correct array type (Float64Array, Uint8ClampedArray respectively)
  // - Needs to be correct size (3D positions, 4D colors) as`size` is ignored
  const positions = new Float64Array(data.map(d => [...d.coordinates, 0]).flat(2));
  const colors = new Uint8ClampedArray(
    data
      .map(d => [(11235 * d.coordinates[0]) % 255, (7511 * d.coordinates[1]) % 255, 0, 255])
      .flat(2)
  );

  const binary = window.location.hash === '#binary';
  console.log('Data length', data.length, '* 4 =', 4 * data.length);

  const props = {
    data: {length: data.length, colors, positions},
    lineWidthMinPixels: 2,
    getFillColor: (_, {data, index}) => {
      return data.colors.subarray(4 * index, 4 * (index + 1));
    },
    getPosition: (_, {data, index}) => {
      return data.positions.subarray(3 * index, 3 * (index + 1));
    }
  };
  if (binary) {
    props.data.attributes = {
      getPosition: {value: positions, size: 3},
      getFillColor: {value: colors, size: 4}
    };
  }

  new Deck({
    container: 'map',
    initialViewState: {latitude: 50, longitude: 10, zoom: 3},
    controller: true,

    layers: [
      new ScatterplotLayer({
        ...props,
        radiusMinPixels: 4
      })
    ]
  });
}

init();

```

### Environment

- Framework version: 9
- Browser:all
- OS:all

**Comment by ibgreen** [comment]
AFAIK you can’t provide an attribute with less components than declared in the shader, WebGPU doesn’t fill the remaining fields. 

But you can probably provide an attribute with more components and skip the unused ones with byteStride.

Maybe you can use `byteStride` if you ignore the third component in the shader (it will contain the first value of the next row. But then you may run out of GPU buffer data for the last vertex unless you pad your attribute.

On top of that the 64 bit handling is special as it preprocesses and splits that 64 bit vector into two 32 bit interleaved attributes.

One could of course also modify the shader.

And without actually testing on WebGPU which is currently not possible in deck.gl it is hard to test this.
