### ISSUE TITLE
[Doc] Wrong Sentence Structure

### ISSUE THREAD

**Issue by ZukLevinson** [visgl/deck.gl#8172]
### Link

https://deck.gl/docs/developer-guide/using-layers

### Description

In the file `using-layers.md` linked [here ](https://github.com/visgl/deck.gl/blob/cf75eb89c53fec503720a7ee06e2d78a8e315e40/docs/developer-guide/using-layers.md?plain=1#L109), it says "The framework then **the makes** minimal necessary changes to account for the differences, and then redraws." - which is probably mistaken for "The framework then **makes the** minimal necessary changes to account for the differences, and then redraws."

**Comment by Pessimistress** [comment]
Would you open a PR to fix that?
