### ISSUE TITLE
[Doc] Use binary attributes with DataFilterExtension

### ISSUE THREAD

**Issue by Upcios** [visgl/deck.gl#8183]
### Link

https://deck.gl/docs/api-reference/extensions/data-filter-extension

### Description

I have a PointCloudLayer with 3M vertices, supply directy with binary attributes:

new PointCloudLayer({
  data: {
    length: data.pointCount,
    attributes: {
      getPosition: {value: data.positions, size: 3},
      getColor: {value: data.colors, size: 3},
    }
  },
  getNormal: [0, 0, 1]
});

I dont know how to use DataFilterExtension with this setup because adding getFilterValue: {value: data.timestamps, size: 1} triggers OpenGL ES errors.

**Comment by Pessimistress** [comment]
![Screen Shot 2023-09-29 at 10 22 00 AM](https://github.com/visgl/deck.gl/assets/2059298/637aae61-77ef-4818-9460-4fb75249b26f)
