### ISSUE TITLE
[Bug] relative imports in published ESM do not have explicit `.js` file extensions

### ISSUE THREAD

**Issue by keller-mark** [visgl/deck.gl#8187]
### Description

Hi, I am using DeckGL in my web application. I am running into issues when importing DeckGL (directly or indirectly) in unit testing frameworks which execute code using NodeJS (`vitest` in particular) because the ESM code (located at `dist/esm/index.js` - also see #8186) is invalid.

The code contains relative imports which lack `.js` file extensions, which are not considered valid ESM (see https://nodejs.org/api/esm.html#esm_mandatory_file_extensions).

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Expect to not need the experimental flag `--experimental-specifier-resolution=node` in order to import from the DeckGL ESM distribution in NodeJS.

Expect the code specified in the `"module"` field of the package.json to be valid ESM.

### Steps to Reproduce

Currently, in order to import this code in NodeJS (after making the changes in #8186), an experimental flag needs to be used `--experimental-specifier-resolution=node`. The default is `--experimental-specifier-resolution=explicit`. See https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm for details.

Also related to questions on stackoverflow such as https://stackoverflow.com/q/74660824 and https://stackoverflow.com/a/62626938 and 

### Environment

- Framework version: `deck.gl@8.9.30`
- NodeJS: 18.16.0
- Browser: Firefox developer edition 119.0b7
- OS: macOS

### Logs

```
Module not found: Error: Can't resolve './lib/init' in '/Users/mkeller/research/dbmi/vitessce/vitessce/node_modules/.pnpm/@deck.gl+core@8.9.30_patch_hash=m3w2bsh3hynziqtpzly5i2bujm/node_modules/@deck.gl/core/dist/esm'
```

**Comment by ibgreen** [comment]
deck.gl 8.9 is a transition version of deck.gl in respect to the `/typed` typescript imports and the few dependencies that had security critical updates bringing in ES module dependencies. 

The good news is that the next version, 9.0 is being developed on master and the alpha track is already fully ES module compatible, solving all the issues you are reporting (though it is not stable enough for use in applications yet). 

I am not aware of any plans to address these things on 8.9. For now you should probably stay on deck.gl 8.8.

**Comment by keller-mark** [comment]
Ok thanks for the context! Since the plan is to solve in v9.0 feel free to close
