### ISSUE TITLE
[Doc] add new app to showcase

### ISSUE THREAD

**Issue by dbabbs** [visgl/deck.gl#8189]
### Link

https://github.com/visgl/deck.gl/blob/master/website/showcase.json

### Description

Hello Vis.gl, I would like to add an application I made to the deck.gl showcase please.

```json
{
    "name": "Radiance: solar panel positioning optimization",
    "url": "https://useradiance.com",
    "image": "/images/showcase/radiance.png",
    "links": {
      "by Radiance": "https://useradiance.com/"
    },
    "description": "An interactive tool for panel density layout optimization and financial modeling for solar projects. Uses Google 3D tiles rendered in deck.gl to show realistic immersive environment. Visualize solar flux and hourly shade images on top of the 3D tiles."
  }
```

Image:
![square-screenshot](https://github.com/visgl/deck.gl/assets/221746/a36cc62d-dc42-4c2f-acbf-44d30a4d694f)

**Comment by felixpalmer** [comment]
Nice app! Could you create a PR for adding it to the showcase?

**Comment by dbabbs** [comment]
Thanks, @felixpalmer
https://github.com/visgl/deck.gl/pull/8190
