### ISSUE TITLE
[Bug] Enabling picking breaks ColumnLayer

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8219]
### Description

As reported here: https://github.com/visgl/deck.gl/issues/8193#issuecomment-1772425205

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Run website locally and observe http://localhost:3000/docs/api-reference/layers/column-layer fails to render. Removing `pickable: true` in `website/src/doc-demos/layers.js` shows the layer.

### Environment

- Framework version: deck.gl@9
- Browser:
- OS:

**Comment by felixpalmer** [comment]
I've done some more debugging and it is possible to get picking working in the Layer Browser, by changing some of the props (e.g. `extruded`) such that `ColumnLayer._updateGeometry` is triggered in `updateState`. So it seems to be some issue with creating resources on first draw rather than a problem specifically with picking

**Comment by ibgreen** [comment]
One wonder's what has changed in v9 to change the timing or resource creation...
