### ISSUE TITLE
[Bug] GlobeView cannot be rotated following the example in View State Transitions

### ISSUE THREAD

**Issue by alessiogmonti** [visgl/deck.gl#8230]
### Description

Hello,
[The linear interpolation example](https://deck.gl/docs/developer-guide/view-state-transitions) does not work when using globeView:

I'm just wondering if this has to do with GlobeView being under development, or if there is an error in the code. I would like to replicate that linearInterpolation example as closely as possible. Thank you

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

```
const [initialViewState, setInitialViewState] = useState({
    longitude: -122.45,
    latitude: 37.78,
    bearing: 0,
    zoom: 1,
  });

  const rotateCamera = useCallback(() => {
    setInitialViewState((viewState) => ({
      ...viewState,
      bearing: viewState.bearing + 120, //also doesnt work when changing longitude
      transitionDuration: 1000,
      transitionInterpolator,
      onTransitionEnd: rotateCamera,
    }));
  }, []);
  
  const backgroundLayer = useMemo(
    () => 
      new SimpleMeshLayer({
        id: "earth-sphere",
        data: [0],
        mesh: new SphereGeometry({
          radius: EARTH_RADIUS_METERS,
          nlat: 18,
          nlong: 36,
        }),
        coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
        getPosition: [0, 0, 0],
        getColor: [255, 255, 255],
      }), []
),
  
  return (
    <DeckGL
      initialViewState={initialViewState}
      controller={true}
      onLoad={rotateCamera}
      views={new GlobeView()}
      layers={backgroundLayer}
    />
  );
```

Incrementing bearing with useEffect works:

  ```
  useEffect(() => {
    const rotationInterval = setInterval(() => {
        setViewState((viewState) => ({
          ...viewState,
          longitude: (viewState.longitude + 0.1) % 360,
        }));
    }, 100); 
    return () => clearInterval(rotationInterval);
  }, []);
  ```

### Environment

- Framework version: deck.gl@8.9.0
- Browser: Chrome 110.0
- OS: iOS 16.3

**Comment by Pessimistress** [comment]
GlobView does not support bearing: https://deck.gl/docs/api-reference/core/globe-view

If you want a rotating globe, you should animate `longitude`.

Please use Discussions to get help with your own app.
