### ISSUE TITLE
[Bug] Deck.gl Incompatible With Google Maps Data-Driven Styling 

### ISSUE THREAD

**Issue by Derek-Herr77** [visgl/deck.gl#8245]
### Description

When Data-Driven Styling is turned on for a google map ID, deck.gl renders underneath the google maps, rendering all deck.gl layers invisible, the visibility varies based on which feature layers are turned on for a map ID, e.g. turning both administrative layers 1 & 2 on renders all of deck.gl invisible.

This only happens in Google Maps API versions 3.54 and above. Version 3.53 and below seem to work. A quick fix for this issue is to turn interleaved off when loading the google map overlay like so:
`const overlay = new GoogleMapsOverlay({ interleaved: false, layers: [layer] }`

This solution however reduces image quality and renders the deck.gl layers overtop labels, making it an incomplete fix.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Deck.gl to render correctly with Data-Driven Styling turned on for a Google Map ID. 

### Steps to Reproduce

This can be seen in the following jsfiddle in Googles documentation: [https://developers.google.com/maps/documentation/javascript/examples/deckgl-arclayer](https://developers.google.com/maps/documentation/javascript/examples/deckgl-arclayer)

### Environment

-deck.gl@8.9.0
-Google Maps Version 3.54 and above

**Comment by Derek-Herr77** [comment]
It seems that once data driven styling is turned on for a mapId, that mapIdwill no longer work even if turned off again, a new map Id has to be created to return functionality.

**Comment by jeantimex** [comment]
Hi, Maps JS pushed a new release yesterday which includes a fix in rendering WebglOverlayView, this issue should be fixed now, could you help verify? Thank you!

**Comment by felixpalmer** [comment]
@Derek-Herr77 could you confirm if it is fixed for you? [The demo](https://developers.google.com/maps/documentation/javascript/examples/deckgl-arclayer) is working well for me. Thank you for the quick fix @jeantimex !

**Comment by Derek-Herr77** [comment]
> @Derek-Herr77 could you confirm if it is fixed for you? [The demo](https://developers.google.com/maps/documentation/javascript/examples/deckgl-arclayer) is working well for me. Thank you for the quick fix @jeantimex !

I can confirm that this fix is working on my end as well. Thanks for the fix @jeantimex!

**Comment by Derek-Herr77** [comment]
Fixed with new Maps JS release.

**Comment by jeantimex** [comment]
Thank you so much for helping us verify!
