### ISSUE TITLE
Add a useDeckGL hook in the MapboxOverlay apporach to be able to use deck.gl methods in React.

### ISSUE THREAD

**Issue by Oussema-Dallel** [visgl/deck.gl#8250]
### Target Use Case

Currently and as far as I am aware, you could only visualize deck.gl layers with the `MapboxOverlay` in the react-map-gl as there is no way to access the Deck instance nor the reference. Maybe a `useDeckGL` hook that allows exposing deck.gl methods such as `pickMultipleObjects` when using MapBoxOverlay with react-map-gl. Thanks! 

This would provide developers best of both worlds and in my opinion could be the ultimate apporach to use deck.gl and mapbox within a react application.

### Proposal

Maybe a `useDeckGL` hook that allows exposing deck.gl methods such as `pickMultipleObjects` when using MapBoxOverlay with react-map-gl. Thanks!

**Comment by chrisgervang** [comment]
We've recently refreshed our mapbox and maplibre documentation, and during this discussion we [wrote](https://github.com/visgl/deck.gl/issues/8147#issuecomment-1739971782) about why we aren't adding react, react-map-gl, and/or deck.gl integrations like this to a deck module. In sum,

- `@deck.gl/react` users don't all use `@deck.gl/mapbox` or `react-map-gl`
- `@deck.gl/mapbox` is vanilla js, framework agnostic
- `react-map-gl` users don't all use `deck.gl`

This said, I don't think you need us to write this hook. You can access deck with a ref already using this:

```ts
import type { Deck, DeckProps } from '@deck.gl/core/typed'
import {MapboxOverlay, MapboxOverlayProps} from '@deck.gl/mapbox/typed';
import Map, {useControl} from 'react-map-gl';
import { forwardRef, useRef, useEffect } from 'react'

const DeckGLOverlay = forwardRef<Deck>((props: MapboxOverlayProps, ref: ForwardedRef<Deck>) => {
  // MapboxOverlay handles a variety of props differently than the Deck class.
  // https://deck.gl/docs/api-reference/mapbox/mapbox-overlay#constructor
  const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props))

  overlay.setProps(props)

  // @ts-expect-error private property
  setRef(ref, overlay._deck)
  return null
})

function DeckMap({deckProps, mapProps}) {
  const deckRef = useRef<Deck>(null);
  
  useEffect(() => {
    if(deckRef.current) {
      const deck = deckRef.current
      // access deck
    }
  }, deckRef.current)
  
  return (
    <Map {...mapProps}>
      <DeckGLOverlay ref={deckRef} {...deckProps} />
    </Map>
  )
}
```

**Comment by hdzierz** [comment]
Hi there,

if I do the above recommendation, I get:

```typescript
TS2344: Type 'MapboxOverlay' does not satisfy the constraint 'IControl<MapInstance>'.
  Types of property 'onAdd' are incompatible.
    Type '(map: Map$1) => HTMLDivElement' is not assignable to type '(map: MapInstance) => HTMLElement'.
      Types of parameters 'map' and 'map' are incompatible.
        Type 'MapInstance' is missing the following properties from type 'Map$1': style, painter, handlers, _container, and 267 more.

```

Any suggestions?

Thanx

H
