### ISSUE TITLE
CartoRasterLayer is not working

### ISSUE THREAD

**Issue by alasarr** [visgl/deck.gl#8263]
### Description

The raster layer is not visible, it performs requests against CARTO Maps API, but it doesn't appear.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

This code example demonstrates the result: 

https://github.com/CartoDB/deck.gl-examples/tree/master/raster-temperature

### Environment

- Framework version: deck.gl v9
- Browser:Chrome 119.0
- OS: MacOS Monterey

**Comment by felixpalmer** [comment]
Fixed by https://github.com/visgl/deck.gl/pull/8268
