### ISSUE TITLE
[Bug] OrbitView example broken in v9

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8266]
### Description

The [OrbitView](https://felixpalmer.github.io/deck.gl/examples/plot) example is broken in v9. 

This issue is not so much down to a problem with `OrbitView` itself, but that the example uses 3 custom layers which have yet to be ported to the v9 API. These layers will need to be converted to Typescript and fixed following the approach used in (e.g.) the core layers

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

https://felixpalmer.github.io/deck.gl/examples/plot or run `examples/website/plot` on `master` branch

### Environment

- Framework version: 9
- Browser:
- OS:

**Comment by donmccurdy** [comment]
@felixpalmer - Do you (or others) have a preference about converting the entire example to TypeScript, or just the `-layer.js` files, or something else? I do find the type-checking helpful, just want to make sure the example is still approachable. 

Enabling `"allowJs": true` mode in `tsconfig.json` might be an alternative if we want the examples to use plain JavaScript, but to still have compile-time errors about incorrect usage.

**Comment by felixpalmer** [comment]
I think it makes sense to convert the layer files, as they are complex and would benefit from the type checking. Just switching to Typescript should help the migration to v9 as many errors will be flagged

**Comment by donmccurdy** [comment]
Sounds good to me -- opened https://github.com/visgl/deck.gl/pull/8289.
