### ISSUE TITLE
Composite IconLayer: points are in wrong position

### ISSUE THREAD

**Issue by zsoooc** [visgl/deck.gl#8267]
### Description

I would like to use  IconLayer, but with MVT data source. I just want to put icons to the map. The problem is that the position of the points are very inaccurate. 
My layer contains 5 points. The correct location of these points:
![image](https://github.com/visgl/deck.gl/assets/19270270/881f7603-b402-4cd2-9e39-ef3a88c40a19)

But in my Deck GL app, I see this:
![image](https://github.com/visgl/deck.gl/assets/19270270/1f3a8b65-3f8c-4cd7-b2ee-85df1ab4cb64)

However, if I use GeoJSON layer, the points are located accurately.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Display the points at their correct position (if I use GeoJSON layer it is perfect) on the map.

This works well:

```
new deck.MVTLayer({
    data: 'http://127.0.0.1:7800/public.test/{z}/{x}/{y}.pbf?',
    id: 'places',
    renderSubLayers: props => {
        return new deck.GeoJsonLayer(props, {
            pointType: 'circle',
            radiusMinPixels: 20,
            radiusMaxPixels: 80,
            getPosition: d => d.geometry.coordinates,
            getFillColor: d => [66, 135, 245],
            getPointRadius: 10
        });
    }
})
```

### Steps to Reproduce

This is the relevant part of my code:

```
new deck.MVTLayer({
    data: 'http://127.0.0.1:7800/public.test/{z}/{x}/{y}.pbf?',
    id: 'objects',
    binary: false,
    renderSubLayers: props => {
        return new deck.IconLayer(props, {
            sizeScale: 1,
            getSize: d => 20,
            iconAtlas: 'places.png',
            iconMapping: {
                marker: {
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 200,
                    mask: true
                }
            },
            getPosition: d => d.position,
            getIcon: d => 'marker',
            billboard: false
        })
    }
})
```

```
let deckgl = new deck.DeckGL({
    views: new deck.FirstPersonView(),
    initialViewState: {
        longitude: 16.0130772,
        latitude: 45.7535322,
        position: [0, 0, 200],
        pitch: 90,
        bearing: 0
    },
    controller: true,
    layers: layers2
});
```

However, 

### Environment

- Framework version: deck.gl@8.9.0
- Browser: Firefox, Chrome
- OS: Windows 10

### Logs

There is no error or warning message on the console.

**Comment by Pessimistress** [comment]
You should not provide your own `renderSubLayers` unless you understand what data is being loaded. `MVTLayer` already renders a `GeoJsonLayer` by default and you can pass any `GeoJsonLayer` prop to it directly, including `pointType: "circle"`.

Bug reports are for bugs in the library. Please go to Discussions if you need help with your own app.
