### ISSUE TITLE
get' on proxy: property 'data' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value 

### ISSUE THREAD

**Issue by wangjiale7** [visgl/deck.gl#8292]
### Description

Add multiple  GeoJsonLayer layers throw err

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [x] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

// import * as d3color from 'd3-color'
import { MapboxLayer } from '@deck.gl/mapbox'
import { GeoJsonLayer } from '@deck.gl/layers'
import { createUUid } from '../../utils/maphelper'
import * as turf from '@turf/turf'
import { Mmap } from '../map'
import eventBus from '../../utils/event'
import { findRangeIndex } from '@/utils/color.js'
import { shallowRef, toRaw } from 'vue'

const BaseOptions = {
  opacity: 1,
  step: 6,
  noLegend: false,
  pickable: true,
  stroked: false,
  filled: true,
  visible: true
}
export class DGeoJsonLayer {
  constructor(map, json, options = {}) {
    // this.options = options
    this.options = Object.assign({}, BaseOptions, options)
    let {
      opacity,
      // colorbrewer,
      // step = 6,
      getColor,
      getLineWidth,
      noLegend,
      pickable,
      filled,
      stroked,
      id = createUUid(),
      visible
    } = this.options
    this.isRemove = false
    this.map = map
    //加载图层
    this.DeckLayer = new MapboxLayer({
      id: id || createUUid(),
      type: GeoJsonLayer,
      data: json,
      pickable,
      stroked,
      filled,
      extruded: false,
      pointType: 'circle',
      lineWidthScale: 1,
      lineWidthMinPixels: 3,
      getFillColor: getColor,
      getLineColor: getColor,
      getPointRadius: 100,
      getLineWidth:  5,
      getElevation: 30,
      opacity,
      visible,
      onHover: e => {
        eventBus.emit('hover', { obj: e })
      }
    })
  }

  addTo(obj) {
    if (obj instanceof Mmap) {
      this.map = obj
      if (this.map.map.getLayer(this.DeckLayer.id) || this.isRemove) return
      if (this.map.map.isStyleLoaded()) {
        this.map.map.addLayer(this.DeckLayer)
      } else {
        this.map.map.once('load', () => {
          if (this.map.map.getLayer(this.DeckLayer.id) || this.isRemove) return
          this.map.map.addLayer(this.DeckLayer)
        })
        this.map.map.once('sourcedata', () => {
          if (this.map.map.getLayer(this.DeckLayer.id) || this.isRemove) return
          this.map.map.addLayer(this.DeckLayer)
        })
      }
      this.map.layers.push(this)
    }
    if (this.noLegend) return
    // this.parentEl.appendChild(this.legendel)
  }
  reset() {
    if (this.map.map.getLayer(this.DeckLayer.id)) {
      this.map.map.removeLayer(this.DeckLayer.id)
    }
    this.map.map.addLayer(this.DeckLayer)
  }
  remove() {
    this.isRemove = true
    if (this.map.map.getLayer(this.DeckLayer.id)) {
      this.map.map.removeLayer(this.DeckLayer.id)
    }
    if (!this.noLegend) {
      // this.legendel.remove()
    }
    let target = this.map.layers.findIndex(item => item.DeckLayer && item.DeckLayer.id === this.DeckLayer.id)
    if (target !== -1) {
      this.map.layers.splice(target, 1)
    }
  }

  //设置toolTip
  setToolTip(text, x, y) {
    this.DeckLayer.deck.tooltip.setTooltip(text, x, y)
  }

  on(name, cb) {
    eventBus.on(name, cb)
  }

  off(name) {
    eventBus.off(name)
  }
  setProps(props) {
    this.DeckLayer.setProps(props)
  }
  updateGetFillColor() {
    this.DeckLayer.setProps({
      updateTriggers: {
        getFillColor: [this.options.interval, this.options.allColor]
      }
    })
  }
}

let layer = new DGeoJsonLayer (map, geojson)
map.addTo(layer)

### Environment

- Framework version:
- Browser:
- OS:

### Logs

![image](https://github.com/visgl/deck.gl/assets/47092916/7173aa63-2455-49f4-a289-411230da91f5)

**Comment by wangjiale7** [comment]
versions 
    "@deck.gl/aggregation-layers": "^8.8.12",
    "@deck.gl/core": "^8.8.20",
    "@deck.gl/layers": "^8.8.12",
    "@deck.gl/mapbox": "^8.8.12",
      "deck.gl": "^8.8.20",

**Comment by Pessimistress** [comment]
Vue freezes objects if you pass them through reactive properties. This is not related to deck.gl.

Please use Discussions to get help with your own application.
