### ISSUE TITLE
[Bug] PolygonLayer doesnt update when data changes

### ISSUE THREAD

**Issue by stuartin** [visgl/deck.gl#8309]
### Description

I'm relatively new to deck.gl (looks like an excellent library!!) so apologies if I'm missing something simple 🙂

- I'm drawing a simple square using the PolygonLayer
- I'm then updating the `data` that this layer uses (via setTimeout)
- The polygon layer doesnt get updated to reflect the changes to `data`

From what I've read from the docs, whenever any props change, the layer should re-render but that doesnt appear to be happening.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The Polygon layer should re-render when the `data` prop changes

### Steps to Reproduce

**Sample**
```
const { DeckGL, PolygonLayer } = deck;

let data = [
  [
    [-123.0, 49.196],
    [-123.0, 49.324],
    [-123.306, 49.324],
    [-123.306, 49.196],
  ],
];

const polyLayer = new PolygonLayer({
  id: 'polygon',
  data,
  stroked: true,
  filled: true,
  getFillColor: [255, 0, 0],
  getLineColor: [255, 255, 255],
  getPolygon: (d) => d,
  pickable: true,
});

new DeckGL({
  mapStyle:
    'https://basemaps.cartocdn.com/gl/positron-nolabels-gl-style/style.json',
  initialViewState: {
    latitude: 49.254,
    longitude: -123.13,
    zoom: 10,
    maxZoom: 16,
    pitch: 45,
  },
  controller: true,
  layers: [polyLayer],
});

console.log(data);
setTimeout(() => {
  data = [];
  console.log(data);
}, 5000);
```

### Environment

- Framework version: `8.8.0`
- Browser: `Chrome 119.0.6045.124 (Official Build) (64-bit)`
- OS: `Windows 7`

```
    <script src="https://unpkg.com/deck.gl@^8.8.0/dist.min.js"></script>
    <script src='https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.js'></script>
    <link href='https://unpkg.com/maplibre-gl@2.4.0/dist/maplibre-gl.css' rel='stylesheet' />
```

**Comment by Pessimistress** [comment]
This template is for reporting bugs in the library. Use Discussions if you need help with your own code.
