### ISSUE TITLE
[Bug] ContourLayer not working in v9

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8314]
### Description

ContourLayer example is broken as `ContourLayer` hasn't yet been ported to v9

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

https://felixpalmer.github.io/deck.gl/examples/contour-layer 

### Environment

- Framework version: deck.gl@9.0
- Browser: all
- OS: all

**Comment by donmccurdy** [comment]
Possibly related: 

- https://github.com/visgl/deck.gl/issues/8321
