### ISSUE TITLE
[Bug] FirstPersonView example not working in v9

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8315]
### Description

The [FirstPersonView example](https://felixpalmer.github.io/deck.gl/examples/first-person-view) is not working in v9.

This is due to two issues:
- The URL of the video is incorrect
- The video doesn't play back correctly (need to investigate why the video texture binding isn't working in the luma v9)

Neither of these are an issue with the `FirstPersonView` itself, which should work fine in v9

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

https://felixpalmer.github.io/deck.gl/examples/first-person-view

### Environment

- Framework version: deck.gl@9.0
- Browser: all
- OS: all

**Comment by donmccurdy** [comment]
Progress:

- https://github.com/visgl/luma.gl/pull/1853

The new video URL will be https://upload.wikimedia.org/wikipedia/commons/0/0a/NASA_VR-360_Astronaut_Training-_Space_Walk.webm. I think with those changes everything should work, though I'm having trouble testing local changes to luma against deck, and have shared a question about that in the deckgl slack channel.

**Comment by donmccurdy** [comment]
Progress:

- https://github.com/visgl/deck.gl/pull/8330
