### ISSUE TITLE
[Doc] Change datasets used in examples/carto

### ISSUE THREAD

**Issue by srtena** [visgl/deck.gl#8324]
### Link

https://deck.gl/examples/carto

### Description

The current deckgl example for the CARTO module uses a dataset provided by Mastercard that CARTO does not offer anymore.

![Screenshot 2023-11-29 at 13 29 09](https://github.com/visgl/deck.gl/assets/17271878/3a8ada00-bf35-408a-ae96-12bc57588100)

It would be ideal to update the example so that it uses a dataset available to any user coming to CARTO from deck.gl so that it can be easily reproduced if needed.

**Comment by alasarr** [comment]
Good! Assigning it to @menusal
