### ISSUE TITLE
[Bug]When using Mapbox and setting the projection to 'Globe', if an ArcLayer is added as a MapboxLayer, the ArcLayer disappears when zooming out.

### ISSUE THREAD

**Issue by ZhitaoXuBIT** [visgl/deck.gl#8337]
### Description

When the mapbox projection is **'Globe'**, The arcLayer perfomances well when the zoom is big, but when I zoom out, the 3Dline disappear gradually. However, when the mapbox projection is default (no-setting), everything plays well.
![5dfc55a204c181134eeaba43ef1a33b](https://github.com/visgl/deck.gl/assets/86584550/b3a08772-7229-4ed9-a7d0-14e76f63a1fc)

![79fddb9010d08176e9e4f83beabd2d3](https://github.com/visgl/deck.gl/assets/86584550/81b959de-7693-4c5e-95be-6990c9ddf150)

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Regardless of how I zoom in or out, 3D lines should be displayed normally in the **'Globe' projection of mapbox**.

### Steps to Reproduce

```
<template></template>

<script>
import {MapboxLayer} from '@deck.gl/mapbox'
import {ArcLayer} from "deck.gl";

export default {
  name: 'ArcLayer',
  props: {
    map: {
      require: true
    }
  },
  data() {
    return {
      arcData: [
        {
          "from": {
            "name": "19th St. Oakland (19TH)",
            "coordinates": [
              -122.269029,
              37.80787
            ]
          },
          "to": {
            "name": "12th St. Oakland City Center (12TH)",
            "coordinates": [
              -122.271604,
              45.803664
            ]
          }
        },
      ]
    }
  },
  methods: {
    initArcLayer() {
      let arcLayer = new MapboxLayer({
        id: 'arcLayer',
        type: ArcLayer,
        data: this.arcData,
        greatCircle: true,
        numSegments: 500,
        getWidth: 2,
        getSourcePosition: d => d.from.coordinates,
        getTargetPosition: d => d.to.coordinates,
        getSourceColor: d => [255, 140, 0],
        getTargetColor: d => [0, 140, 0]
      })
      console.log(arcLayer)
      this.map.addLayer(arcLayer)
      this.map.flyTo({
        center: [-122.271604, 37.803664],
        zoom: 13,
        pitch: 45
      })
    }
  },
  mounted() {
    this.initArcLayer()
  }
}
</script>

<style scoped>

</style>
```

### Environment

- Framework version: "deck.gl": "^8.9.32","mapbox-gl": "^2.15.0",
- Browser: Both Chrome and Firefox
- OS: WIndows 11

### Logs

no warnings or errors

**Comment by Pessimistress** [comment]
Globe projection is not supported at the moment.

#7920
