### ISSUE TITLE
[Bug]Local Build Not Working

### ISSUE THREAD

**Issue by JunboXi** [visgl/deck.gl#8346]
### Description

I am trying to modify the source code based on Contributing.md. 
When running the command ''yarn bootstrap'' it gives an error: 
$ PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn && ocular- bootstrap
'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD' is not an internal or external command, nor is it a runnable program
or batch file.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Follow the instructions in Contributing.md to debug the source code. Then run yarn bootstrap in order to run it from local sources

### Environment

- Framework version:v8.9.0-beta.5
- Browser: Chrome 119.0.6045.200
- OS: Windows10

**Comment by Pessimistress** [comment]
The dev set up does not work under Windows command line. Read https://github.com/visgl/deck.gl/blob/master/CONTRIBUTING.md#develop-on-windows
