### ISSUE TITLE
[Bug] IconLayer does not support GeoJson ?

### ISSUE THREAD

**Issue by eviltik** [visgl/deck.gl#8354]
### Description

The IconLayer produce nothing.

### Flavors

- [X] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I'd like to see icons :)

### Steps to Reproduce

Working example with specific json format ( [bart-stations.json](https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/bart-stations.json) ) : [Codepen](https://codepen.io/Pessimistress/pen/ZEVbMYE)

Do NOT work with geojson file ( [vancouver-blocks.json](https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/geojson/vancouver-blocks.json) ) : [Codepen](https://codepen.io/franck34/pen/qBgGGgm)

### Environment

- Framework version: 8.9.33
- Browser: Chrome 120.0.6099.71
- OS: Linux KDE Neon + NVidia

### Logs

No error in the console => should be great to show some errors ! ;)

**Comment by eviltik** [comment]
Not sure if it's a bug or not, i just started to use deck.gl yesterday. (noob spoted).

I work around and end up with this function.

```
async function loadAndConvertGeojsonUrlToIconLayerDataStructureLOL(url) {
  const response = await fetch(url);
  const json = await response.json();
  const data = json.features.map(f => {
    const r = { coordinates: f.geometry.coordinates };
    Object.keys(f.properties).map(key => r[key] = f.properties[key])   
    return r;
  });                              
  return data;
}
```
https://codepen.io/franck34/pen/MWLdMvj

**Comment by Pessimistress** [comment]
IconLayer's dada prop usually expects an array, see [data](https://deck.gl/docs/api-reference/core/layer#data).
If you want to use GeoJSON directly, use the GeoJsonLayer.

Issues are for reporting bugs in the library, not your own application. Please use discussions if you have questions about using layers.
