### ISSUE TITLE
[Bug] Scenegraph: Cannot read properties of undefined (reading 'texCoord')

### ISSUE THREAD

**Issue by joedjc** [visgl/deck.gl#8355]
### Description

When loading a GLB with textures the model doesn't load in some cases, showing a console error:

deck: loading scenegraph of ScenegraphLayer({id: 'ScenegraphLayer'}): Cannot read properties of undefined (reading 'texCoord')

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Model would display on Deck GL

### Steps to Reproduce

Add the attached GLB file to a scenegraph.
[Roof.glb.zip](https://github.com/visgl/deck.gl/files/13673330/Roof.glb.zip)

### Environment

- Framework version: 8.9.13
- Browser: Chrome 119.0.6045.199
- OS: macOS 14.1.2

### Logs

deck: loading scenegraph of ScenegraphLayer({id: 'ScenegraphLayer'}): Cannot read properties of undefined (reading 'texCoord')

**Comment by heyu3913** [comment]
Is the problem solved?

**Comment by felixpalmer** [comment]
Can you confirm if the issue is present in `9.0.1`?

**Comment by donmccurdy** [comment]
Testing locally the problem persists in v9.0.1, but is a loaders.gl issue. I've opened a PR:

- https://github.com/visgl/loaders.gl/pull/2928

However, the implementation of `KHR_texture_transform` in loaders.gl remains incomplete. I've written up more details of what's missing below:

- https://github.com/visgl/loaders.gl/issues/2929

The model should appear on screen after the fix lands, but the materials are not fully supported:

![Screenshot 2024-03-25 at 5 54 26 PM](https://github.com/visgl/deck.gl/assets/1848368/1c2b14db-3c96-4ccc-b54a-0627583eeb27)

That's due to dependencies on the following unsupported extensions:

- KHR_materials_specular
- KHR_materials_ior
- KHR_materials_volume
- KHR_materials_transmission

Support for these PBR materials would be a heavier lift — I think you will find it easier to edit the materials to avoid depending on these extensions.

**Comment by joedjc** [comment]
Thank you for looking into it @donmccurdy - we'll look into those changes to our models

**Comment by ibgreen** [comment]
> Support for these PBR materials would be a heavier lift

FWIW, Based on a fleeting read of the extension specs which specifies the math involved these do seem surprisingly simple to add, but I haven't made any actual attempts and even if easy it is indeed still a full feature that requires wiring up test models etc.

**Comment by donmccurdy** [comment]
Agreed for IOR and Specular, it's just additional math in the PBR shader. The volume and transmission extensions typically involve one or more additional render passes. Example showing both volume and transmission here:

- https://threejs.org/examples/?q=gltf#webgl_loader_gltf_transmission

**Comment by heyu3913** [comment]
> Agreed for IOR and Specular, it's just additional math in the PBR shader. The volume and transmission extensions typically involve one or more additional render passes. Example showing both volume and transmission here:
Hello,

I have tried loading two different models, airplane.glb and car.glb. I noticed that the airplane.glb model can load all materials successfully, while the car.glb model fails to load and throws an error in the browser console: "Cannot read properties of undefined (reading 'texCoord')". Do you know what could be the difference between these two models? I have attached the models for your analysis.

Thank you!
[Uploading glb.zip…]()

**Comment by heyu3913** [comment]
> Hi @heyu3913, we're still experiencing this issue and haven't found a solution so far unfortunately. We've tried it with v9 - though not the very latest beta just yet.
> 
> We're not sure if it's an issue with Deck GL or one of the associated libraries like Luma. @Pessimistress, @felixpalmer - do you have any advice or suggestions on where the source of the problem may be? Is it an expected limitation?
Hello,

I have tried loading two different models, airplane.glb and car.glb. I noticed that the airplane.glb model can load all materials successfully, while the car.glb model fails to load and throws an error in the browser console: "Cannot read properties of undefined (reading 'texCoord')". Do you know what could be the difference between these two models? I have attached the models for your analysis.

Thank you!
[glb.zip](https://github.com/visgl/deck.gl/files/14751782/glb.zip)

**Comment by donmccurdy** [comment]
@heyu3913 the current version of loaders.gl has fairly limited support for the `KHR_texture_transform` extension. Your car model uses that extension in a way that loaders.gl does not yet support (see PR above) and the airplane model does not use the extension at all. You can see which extensions are used by dropping models into https://gltf.report.

**Comment by heyu3913** [comment]
> @heyu3913 the current version of loaders.gl has fairly limited support for the `KHR_texture_transform` extension. Your car model uses that extension in a way that loaders.gl does not yet support (see PR above) and the airplane model does not use the extension at all. You can see which extensions are used by dropping models into https://gltf.report.

I understand. Thank you.
