### ISSUE TITLE
[Bug] IconLayer: cannot change icon then change back to initial icon with auto-packed atlas

### ISSUE THREAD

**Issue by ritterni** [visgl/deck.gl#8378]
### Description

I'm using an icon layer to display dynamically configurable icons (on a Google Maps overlay but this doesn't seem to be relevant to the problem). To do so I'm creating new icons with different SVG data and the same id to pass to getIcon, to replace the existing icon instead of risking filling up the texture with unused data. This works well except that I can't ever change back to the initial value of an icon with a given id. If I give the layer the same data url again the change simply isn't displayed. And this only applies to the first icon with this id; I can switch back and forth between subsequent icons without issues.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

IconLayer icons can be replaced and the change is always displayed

### Steps to Reproduce

https://codepen.io/ritterni/pen/NWJxKBK

I've made this quick demo from the IconLayer example to show the problem. Clicking the icons cycles their colors between red, green and blue SVGs in order. Switching between green and blue works, however it's impossible to return to the initial red icon again; the layer keeps showing the previous color instead.

### Environment

- Framework version: 8.9.33
- Browser: Firefox 121.0
- OS: Windows 10

**Comment by Pessimistress** [comment]
You are reusing the same id when you update icons. `id` when supplied is used to uniquely identify icons, i.e. icons with the same id are assumed to be identical (no change). See https://deck.gl/docs/api-reference/layers/icon-layer#geticon

**Comment by ritterni** [comment]
I see. What's the intended way to replace icons in the layer then? In my experience, adding icons with new ids eventually leads to black squares as we run out of space on the WebGL texture, even if only one of the icons is in use at a time.

**Comment by Pessimistress** [comment]
If you are changing "back to initial icon", as the issue indicates, then you are going back to the initial id, instead of making a new id.

If you truly have an unlimited number of icons, then the IconLayer is not really designed for that. Every now and then you need to create a new layer by changing the layer id, so that outdated resources are deleted.
