### ISSUE TITLE
[Bug] CARTO fetchMap: HeatmapLayers doesn't work

### ISSUE THREAD

**Issue by padawannn** [visgl/deck.gl#8381]
### Description

HeatmapLayers are not rendered. It's because the layer is receiving a geojson as data. To solve it we need to add the `dataTransform` property. For example:
```
dataTransform: (d) => d.features.map(d => ({...d.properties, geom: d.geometry}))
```

On the other hand, we're not passing the `getWeight` property

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Create and publish a map with a Heatmap layer in Builder. After that test it in the carto-map test app

### Environment

- Framework version: deck.gl@8.9.33
- Browser: all
- OS: all

**Comment by felixpalmer** [comment]
Closing as we now use `HeatmapTileLayer`
