### ISSUE TITLE
[Bug] Unicode characters aren't visible.

### ISSUE THREAD

**Issue by mjtworks** [visgl/deck.gl#8390]
### Description

Unable to see the Unicode characters via deck.TextLayer.

### Flavors

- [X] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Labels with the Unicode should be shown on the screen.

### Steps to Reproduce

  - A Codepen that reproduces the behavior: [deck.gl Unicode example](https://codepen.io/mjtworks/pen/abMZdee)
  - A sample dataset:
```
{
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [0, 1], },
        properties: { text: "0, 1", },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [0, 0], },
        properties: { text: "日本語", },
      },
      {
        type: "Feature",
        geometry: { type: "Point", coordinates: [0, -1], },
        properties: { text: "0, -1", },
      },
    ],
  }
```

### Environment

- Framework version: deck.gl@8.9.33, and also in deck.gl@8.7.10
- Browsers:
  - Firefox : 121.0 (64-bit)
  - Chromium : Version 115.0.5790.102 (Official Build) (64-bit)
  - Microsoft Edge : Version 120.0.2210.121 (Official build) (64-bit)
- OS:
  - Windows 11 Home Single Language, OS Build 22631.2861
  - Windows 10 Pro for Workstations, OS Build 19045.3803

### Logs

Minified file gives the following errors:
```
deck: Missing character: 日 (26085) dist.min.js:3422:2142
deck: Missing character: 本 (26412) dist.min.js:3422:2142
deck: Missing character: 語 (35486) dist.min.js:3422:2142
```

The above error is otherwise printed from the function `transformRow`'s line `114166` in the file `https://unpkg.com/deck.gl@8.9.33/dist/dist.dev.js`
```
_deck_gl_core__WEBPACK_IMPORTED_MODULE_0__["log"].warn(`Missing character: ${character} (${character.codePointAt(0)})`)();
```

**Comment by Pessimistress** [comment]
[characterSet](https://deck.gl/docs/api-reference/layers/text-layer#characterset)

**Comment by mjtworks** [comment]
Thank you @Pessimistress , it works!
