### ISSUE TITLE
[Bug] deck.gl draws points that are obscured by mapBox's terrain

### ISSUE THREAD

**Issue by xuchaozou** [visgl/deck.gl#8404]
### Description

I use the mapBox framework and deck.gl as a plugin. When I use deck.gl plugin to draw points, I load them into the mapBox map. When I find a terrain, the points drawn will be blocked by the mapBox terrain

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The points drawn should theoretically be above the mapBox

### Steps to Reproduce

[demo](https://stackblitz.com/edit/js-qc3cwh?file=index.js) 
I added a point drawn by maoBox and a point drawn by deck.gl to the map. When there is a terrain, the points drawn by mapBox can be correctly displayed, while the points drawn by deck.gl must be displayed by removing the terrain. I expect the points drawn by deck.gl to work just as well as the points drawn on mapBox, thanks

### Environment

- Framework [@8.9.33:](https://github.com/visgl/deck.gl/tree/v8.9.33)
- Browser: chrome  120.0.6099.201
- OS: windows 10

**Comment by Pessimistress** [comment]
Mapbox does not expose terrain for third party integration. This is a known limitation. https://deck.gl/docs/api-reference/mapbox/overview#limitations
