### ISSUE TITLE
[Bug] cartocolor dependency is missing a license

### ISSUE THREAD

**Issue by hkfb** [visgl/deck.gl#8419]
### Description

Cartocolor is a dependency of `@deck.gl/carto`. There is no license specified in the `cartocolor` npm package. This is reported as a high severity license issue by Snyk.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

There should be no dependencies that have no license specified.

### Steps to Reproduce

Inspect the installed `node_modules/cartocolor/package.json`. It does not specify a license for the package.

### Environment

- Framework version: deck.gl@8.9.33
- Browser: any
- OS: any

**Comment by felixpalmer** [comment]
Please report on correct repo: https://github.com/CartoDB/CartoColor
