### ISSUE TITLE
[Bug] ArcGIS module broken in v9

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8428]
### Description

The ArcGIS integration is not working

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Run `/examples/get-started/pure-js/arcgis` or `/examples/get-started/react/arcgis`

### Environment

- Framework version: deck.gl@9.0.0-alpha.6
- Browser: all
- OS: all

**Comment by jaredscarr** [comment]
Taking a crack at this. The error, appears to be that the deckFbo isn't being created correctly, but ```initializeResources``` does seem to be called from deck-layer-view-2d.js. A console log of the context object shows an instance of ```WebGLRenderingContext``` and based of this [PR](https://github.com/visgl/deck.gl/pull/8442/files) it looks like it doesn't work with WebGl 1 and would be expecting WebGL2RenderingContext.

**Comment by felixpalmer** [comment]
@jaredscarr thanks :) yes it is the case that we need the context to be WebGL2

**Comment by Pessimistress** [comment]
Like this?

https://github.com/visgl/deck.gl/blob/2408740cb0af6790f55c6e69a7a3e53db1ae8ab1/modules/core/src/lib/deck.ts#L380
