### ISSUE TITLE
[Doc] Specify `npm install @deck.gl/{layers,react}`

### ISSUE THREAD

**Issue by ryan-williams** [visgl/deck.gl#8456]
### Link

https://deck.gl/docs/get-started/using-with-typescript

### Description

For Typescript usage, seems like users need to install:
```bash
npm install @deck.gl/layers
npm install @deck.gl/react
```
in order to be able to import `typed` versions:
```tsx
import DeckGL from '@deck.gl/react/typed';
import {ScatterplotLayer} from '@deck.gl/layers/typed';
```
I only see `npm install deck.gl` recommended [in the docs](https://deck.gl/docs/get-started/getting-started), which gives me errors like:
```
Type error: Cannot find module '@deck.gl/react/typed' or its corresponding type declarations.
 
> 1 | import DeckGL from '@deck.gl/react/typed'
    |                    ^
```

This Dockerfile reproduces the issue:

```Dockerfile
FROM node:19.3.0

# Set up project, install deck.gl
RUN npm install -g pnpm \
 && npx create-next-app test-app --ts --no-tailwind --no-eslint --no-app --use-pnpm --no-src-dir --import-alias '@/*'
WORKDIR test-app
RUN pnpm i deck.gl

# Prepend `import DeckGL from '@deck.gl/react/typed'` to pages/index.tsx
RUN echo "import DeckGL from '@deck.gl/react/typed'" > import.tsx \
 && cat pages/index.tsx >> import.tsx \
 && mv import.tsx pages/index.tsx

# ❌ Build fails:
# ```
# Type error: Cannot find module '@deck.gl/react/typed' or its corresponding type declarations.
# > 1 | import DeckGL from '@deck.gl/react/typed';
#     |                    ^
# ```
RUN npm run build
```

**Comment by Pessimistress** [comment]
The package deck.gl installs all the sub modules: https://unpkg.com/browse/deck.gl@8.9.34/package.json

I don't know why your project shows error but the problem is not the docs.

**Comment by ryan-williams** [comment]
That's weird, it seems specific to pnpm. I filed https://github.com/pnpm/pnpm/issues/7594 about it, closing here.

**Comment by ryan-williams** [comment]
Per discussion on https://github.com/pnpm/pnpm/issues/7594, pnpm requires[^1] directly installing (or listing as package.json "dependencies") any libraries that are directly used, so in order for this to work:
```ts
import DeckGL from '@deck.gl/react/typed';
```
users need to run:
```bash
pnpm install @deck.gl/react
```
or list `@deck.gl/react` explicitly in package.json "dependencies."

I'm sure most DeckGL users are not using pnpm, and maybe anyone more experienced with pnpm will figure this out more quickly than I did, but maybe a note in the docs about this makes sense; feel free to reopen if so.

I will also edit the issue/title to reflect what turns out to have been the problem.

[^1]: https://medium.com/pnpm/pnpms-strictness-helps-to-avoid-silly-bugs-9a15fb306308
