### ISSUE TITLE
[Bug] Wrong collisions for icon layer with CollisionFilterExtension

### ISSUE THREAD

**Issue by just-website** [visgl/deck.gl#8459]
### Description

Hello. 
I started a discussion but didn't get any feedback. Now I expanded the example and now it looks like a bug more.

There are two layers with icons. One with a sprite, the second with a regular png icon. The problems start when I try to apply a "CollisionFilterExtension" to any of these layers and add an icon offset in the "anchor" property.

![image](https://github.com/visgl/deck.gl/assets/20595147/016689de-a9cf-41fa-a622-69f8e066d07d)

### Flavors

- [x] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

CollisionFilterExtension plugin and offset from anchor property works for icon layer

### Steps to Reproduce

https://codepen.io/Gleb-Shchukin/pen/JjzOJvL?editors=0010

in my example you can see two problems for two icon layers with different params:
1.  iconSpriteLayer. collision is Enabled and has anchorY offset. Always has transparency and seems to affect the second layer, which can disappear when changing the zoom or dragging the map. Opacity will look better if you set an incorrect anchorY for the current icon - anchorY: 96
2. iconSingleLayer. collision is Enabled and default anchor params. may look good if you don't add anchor offset and turn off anchor or collision on the first layer

### Environment

- Framework version: 8.9.34
- Browser: Chrome 120.0.6099.227
- OS: Win 11

**Comment by felixpalmer** [comment]
The `CollisionFilterExtension` samples that the anchor point of features when determining if there is a collision. At this point your image is transparent so it doesn't work. To fix it use `alphaCutoff: -1` to avoid transparent pixels being discarded, and don't set the anchor right on the edge of the sprite, so for `iconSpriteLayer` use `anchorY: 124`

**Comment by just-website** [comment]
@felixpalmer Thanks for your clarification. This is not an obvious setting.
I need to show different icons for the same data set.
But I keep seeing another problem with this example: elements of the entire layer disappearing when zooming and dragging the map. can you watch this?
![screen](https://github.com/visgl/deck.gl/assets/20595147/5e91b5a8-dd36-4357-9ff2-670736bc4f5e)

**Comment by just-website** [comment]
Perhaps this is a local codepen problem.
I tried this data on my computer, but added it as MapBoxLayer adapter layers and everything works for me without any “disappearances”. Felix Thanks again for updating this in the documentation.
