### ISSUE TITLE
[Bug] AnimationLoop error in @deck.gl/core v9.0.0.beta-1

### ISSUE THREAD

**Issue by aaranadev** [visgl/deck.gl#8463]
### Description

When the deck.gl is instanced an animation loop error is shown in console:

```
deck: Cannot read properties of null (reading
'attachTimeline')
```

I have identify the error in deck.gl file in line 952:

```
this.animationLoop!.attachTimeline
```

 I leave several screenshot with the console error and debugger

![Screenshot 2024-01-30 at 10 18 52 AM](https://github.com/visgl/deck.gl/assets/11427698/7a3f79b9-3703-4293-825a-2cf60d1d26a3)
![Screenshot 2024-01-30 at 10 18 39 AM](https://github.com/visgl/deck.gl/assets/11427698/87359cb0-7493-40cc-98d5-1b015452fd23)

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

No console error

### Steps to Reproduce

Create a new project with @deckgl/react and use it

### Environment

- Framework version: deck.gl@9.0.0-beta.1
- Browser: N/A
- OS: macOS 13.0

**Comment by donmccurdy** [comment]
@aaranadev would it be possible to share a demo, or a code snippet that you are running to reproduce this error? 

As far as I can guess from the code, this error could only happen if the Deck instance has been disposed/finalized when it should not have been. I tried setting up a simple deck/react application (attached below), and wasn't able to reproduce the bug from that. Any additional details to reproduce the issue would be welcome! It might also be worth testing again on v9.0.0-beta.3, if you haven't yet. Thanks!

[animationloop_test.zip](https://github.com/visgl/deck.gl/files/14301472/animationloop_test.zip)

**Comment by JayFoxRox** [comment]
I get the same error but in a different situation.
My code worked fine in v8; it only became a problem in v9.

> chunk-ZFZWRON5.js?v=5455841c:12874 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'attachTimeline')
>    at _Deck._setDevice (chunk-ZFZWRON5.js?v=5455841c:12874:24)
>    at Object.onInitialize (chunk-ZFZWRON5.js?v=5455841c:12798:39)
>    at AnimationLoop.start (chunk-FID7NU7V.js?v=5455841c:301:26)

My code manually creates a deck in a `useEffect` like this:

```
    useEffect(() => {
        deckRef.current = new Deck({
            parent: containerRef.current
        });
        return () => {
            deckRef.current.finalize();
        };
    }, []);
```

Even worse: Afterward I have 2 deck.gl canvases, with one of them being massive; here's a screenshot of the DOM:

<img width="1192" alt="Screenshot" src="https://github.com/visgl/deck.gl/assets/360330/8af7b8f0-0b32-48a4-ab3c-6e658b2e9d59">

Both of them are still visible, so the functioning one is being pushed a lot.

I temporarily tried to work around it by doing the `.finalize` on an interval.
I also tried to work around it by delaying the `finalize` by one frame by wrapping it in an RAF.
That improved it, but it still didn't seem reliable either, so I have to work around it by avoiding `React.StrictMode` (which is a feature that runs the `useEffect` hook twice in quick succession to ensure there are no sideeffects; it thereby creates the race condition here).

**Comment by donmccurdy** [comment]
@JayFoxRox I'm still trying to reproduce this problem. Calling `.finalize()` and recreating the Deck instance is working as expected on v9 beta-3 for me. Could you share something I can run, either locally or in a Codepen/JSFiddle/...?

**Comment by JayFoxRox** [comment]
I have it here as `enableBug1` in https://github.com/JayFoxRox/deck.gl-bugs
