### ISSUE TITLE
[Bug] Types and onDataLoad in VectorTileLayer in @deck.gl/core v9.0.0.beta-1

### ISSUE THREAD

**Issue by aaranadev** [visgl/deck.gl#8464]
### Description

The vectorLayer has several bugs:

- The onDataLoad method doesn't work
- The types aren't autocompleted correctly. e.g `getIcon` property is not autocompleted by later is recognized

I leave images

![Screenshot 2024-01-30 at 4 42 20 PM](https://github.com/visgl/deck.gl/assets/11427698/c3bf3bb4-382d-47bd-a6de-fbde0895c571)
![Screenshot 2024-01-30 at 4 42 31 PM](https://github.com/visgl/deck.gl/assets/11427698/933abcfe-0fa3-40b1-9a17-a9d1939fb027)

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

### Expected Behavior

onDataLoad event is called and the type autocomplete works

### Steps to Reproduce

Create a new project, add a new VectorLayer with an onLoadData method and type the property like getIcon or getFillColor

### Environment

- Framework version: @deck.gl/core v9.0.0.beta-1
- Browser: N/A
- OS: macOS 13.0

**Comment by felixpalmer** [comment]
Autocompletion is working fine for me, so this seems more like an issue with your IDE than the types

https://github.com/visgl/deck.gl/assets/453755/1a8bca99-02e1-4a98-97ad-36953edc51ed

**Comment by felixpalmer** [comment]
The `onDataLoad` prop is used in `MVTLayer` only when the `data` prop is a TileJSON URL. This is never the case with the `VectorTileLayer` as the `vectorTableSource` returns a Promise, which resolves to the TileJSON. It was incorrectly still allowed in the types, which is [fixed here](https://github.com/visgl/deck.gl/pull/8503).

To detect when the TileJSON is loaded, you can await the TileJSON and then create the layer:

```js
const tileJSON = vectorTableSource({...});
const data = await tileJSON;
onDataLoad(); // TileJSON has been loaded

const layer = new VectorTileLayer({
  data,
  ...
});
```

Or alternatively use `then()` if you don't want an async context

```js
const tileJSON = vectorTableSource({...});

const layer = new VectorTileLayer({
  data: tileJSON.then(data => {
    onDataLoad();
    return data;
  }),
  ...
});
```

**Comment by felixpalmer** [comment]
Actually, I forgot that there is also an [onDataLoad](https://deck.gl/docs/api-reference/core/layer#ondataload) function on the base Layer. I've tested it with `VectorTileLayer` and it is working for me. @aaranadev could you try with the latest release and if it still isn't working, post a codesandbox?

**Comment by donmccurdy** [comment]
The types were improved in beta-3 over beta-1, but also note there's an open issue https://github.com/visgl/deck.gl/issues/8499. For some `tsconfig.json` settings, types will not work yet. We can track that issue in #8499 though.

**Comment by aaranadev** [comment]
Thanks to both of you, I will follow the issue
