### ISSUE TITLE
[Doc] Several layers with realtime data update and mapbox

### ISSUE THREAD

**Issue by just-website** [visgl/deck.gl#8470]
### Link

https://deck.gl/docs/api-reference/mapbox/overview#mixing-deckgl-layers-and-mapbox-layers

### Description

How to properly add and update multiple data sources for a mapbox?
The documentation says that when working with deck.gl you need to follow a reactive programming approach and if you need to update data on a layer, you must recreate the layer each time.
What strategy should I follow when working with mapbox when I have multiple data sources displayed in deck.gl as MapBoxLayer. 
Should I create a separate deck.gl layer for each data source and wrap it in a separate MapBoxLayer adapter to add each instance to the MapBox map? Should I recreate the deck.gl layer and its MapBoxLayer wrapper every time I update the data?
Or perhaps I need to create only one Composite Layer for all data sources (as sublayers) and add it to the map as a MapBoxLayer only once? How should I update this layer's data realtime?

**Comment by Pessimistress** [comment]
Use `MapboxOverlay` and call `overlay.setLayers`.
