### ISSUE TITLE
[Bug] `dist` tests broken since introduction of ESM

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8482]
### Description

`yarn test dist` is failing on master

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Pull the latest `master` branch and execute `yarn test dist`

### Environment

- Framework version: deck.gl@9.0.0-beta.2
- Browser:
- OS:

**Comment by Pessimistress** [comment]
This is expected. `arcgis` and `test-utils` are not being built for dist on master, as noted in the TODO of #8460.

https://github.com/visgl/deck.gl/blob/940da34c207c9a980ad7162dd7b700b1dfd127d7/tsconfig.build.json#L23
