### ISSUE TITLE
[Bug] stylesheet.css not included in npm build

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#8494]
### Description

When running `yarn build`, the widget stylesheet.css isn't coying into the npm dist.
![Screen Shot 2024-02-13 at 10 25 23 AM](https://github.com/visgl/deck.gl/assets/2461547/4ffe29e0-95f0-4f5b-bd87-d1ffb8f92c9c)
This causes an file not found import error when running `yarn start` within the widget example in `examples/get-started/pure-js/widgets`. Note that `yarn start-local` works since it it's loading `src` rather than `dist`.

On `8.10-release` the stylesheet is present.
![Screen Shot 2024-02-13 at 12 07 59 PM](https://github.com/visgl/deck.gl/assets/2461547/fbfc7092-333f-41b9-901c-db451fe8d9e9)

### Flavors

- [X] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

`stylesheet.css` should be copied into `dist`.

### Steps to Reproduce

`yarn build` on master and inspect the `dist`. 

### Environment

- Framework version: 9
- Browser: Chrome
- OS: MacOS

**Comment by chrisgervang** [comment]
Which build script is responsible? Is it ocular-build? https://github.com/uber-web/ocular/blob/master/modules/dev-tools/scripts/build.sh

Which tool builds deck now? TSC, esbuild, or babel?

**Comment by Pessimistress** [comment]
The standard build process does not handle static assets. You should add any copy command to https://github.com/visgl/deck.gl/blob/master/modules/widgets/package.json#L38
