### ISSUE TITLE
[Bug] CARTO: columns property is missing in VectorQuerySourceOptions

### ISSUE THREAD

**Issue by padawannn** [visgl/deck.gl#8514]
### Description

VectorQuerySourceOptions also must accept `columns` property 

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The Maps API must be called with `columns` parameter for `vectorQuerySource` dataset

### Steps to Reproduce

Loads a `vectorQuerySource` setting the `columns` property

### Environment

- Framework version: deck.gl@9.0.0-beta.3
- Browser: N/A
- OS: N/A

**Comment by felixpalmer** [comment]
What about the `h3QuerySource`, `boundaryQuerySource` and `quadbinQuerySource`?

**Comment by padawannn** [comment]
> What about the `h3QuerySource`, `boundaryQuerySource` and `quadbinQuerySource`?

We also need it for `boundaryQuerySource` but for `h3QuerySource` and, `quadbinQuerySource` makes no sense because the maps API needs to know how to aggregate columns and we have the `aggregationExp` for this
