### ISSUE TITLE
[Bug] `MapboxOverlay` crashes with WebGL1 basemap when `interleaved: true`

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#8523]
It looks like [`MapboxLayer`](https://github.com/visgl/deck.gl/blame/ff0cc12b50b852a265a0c08a91aa1946d111ccdb/modules/mapbox/src/mapbox-layer.ts#L37-L40) implements a graceful solution and logs a warning. 

We probably need to do something similar in [MapboxOverlay](https://github.com/visgl/deck.gl/blob/ff0cc12b50b852a265a0c08a91aa1946d111ccdb/modules/mapbox/src/mapbox-overlay.ts#L94-L95). @felixpalmer, does that seem right?

_Originally posted by @chrisgervang in https://github.com/visgl/deck.gl/pull/8146#discussion_r1500112369_

**Comment by felixpalmer** [comment]
@chrisgervang yes, that would be the best solution
