### ISSUE TITLE
[Bug] CARTO: H3TileLayer and QuadbinTileLayer borders

### ISSUE THREAD

**Issue by padawannn** [visgl/deck.gl#8524]
### Description

Loading any of these layers using `getLineColor `, `getLineWidth`, and `getFillColor` we're getting strange effects with borders:

<img width="1136" alt="Captura de pantalla 2024-02-23 a las 10 39 55" src="https://github.com/visgl/deck.gl/assets/7164554/92008a37-f4a3-49ac-a108-8d29b6618ab2">
<img width="1036" alt="Captura de pantalla 2024-02-23 a las 10 40 53" src="https://github.com/visgl/deck.gl/assets/7164554/bfea9e9d-c573-4d3e-b103-89a317cdecd4">

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Load any of these layers using `getLineColor `, `getLineWidth`, and `getFillColor`

### Environment

- Framework version: v9.0.0-beta.3
- Browser: n/a
- OS: n/a

**Comment by padawannn** [comment]
I'm getting this warning. I don't know if it's related

<img width="748" alt="Captura de pantalla 2024-02-23 a las 10 53 01" src="https://github.com/visgl/deck.gl/assets/7164554/c88e39fe-daaf-4b9b-aa56-3a828930fe1b">

**Comment by felixpalmer** [comment]
This [example](https://stackblitz.com/github/CartoDB/deck.gl-examples/tree/master/spatial-features-h3?file=index.ts) is working fine, could you post a modified example with the issue?

**Comment by padawannn** [comment]
Is working well with the last beta version. Sorry for the noise
