### ISSUE TITLE
TripsLayer using Color Gradient instead of Transparancy

### ISSUE THREAD

**Issue by Fabioni** [visgl/deck.gl#8544]
### Target Use Case

I want to use fadeTrail but fading should be done using color gradient because I do not want to use transparency. 
Workaround: two identical TripsLayer on top of each other with the underlying one without fading and the one on top with fading.

### Proposal

https://github.com/visgl/deck.gl/blob/36af760071cf8655d83907feeaeb3772c662fed9/modules/geo-layers/src/trips-layer/trips-layer.ts#L94

`color.rgb = mix(vec3(0.0, 0.0, 0.54), vec3(0.53, 0.81, 0.98), 1.0 - (currentTime - vTime) / trailLength)`

**Comment by felixpalmer** [comment]
I like the idea, feel free to put up a PR for discussion. This would involve adding a new accessor to `TripsLayer`, e.g. `getFadeColor`

With the current API a better "workaround" is to subclass `TripsLayer` and override `getShaders` so that the `fs:DECKGL_FILTER_COLOR` injection contains your modified shader code

**Comment by Fabioni** [comment]
Thanks for the tip, for reference, this is the code which works as expected, (@felixpalmer any ideas why eslint is complaining so much about that code?):
```ts
// eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/ban-types
class FadingTripsLayer<DataT = any, ExtraProps extends {} = {}> extends TripsLayer<DataT, ExtraProps> {
    getShaders() {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        const shaders = super.getShaders();
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
        shaders.inject = {
            // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
            ...shaders.inject,
            'fs:DECKGL_FILTER_COLOR': `\
                if(fadeTrail) {
                    color.rgb = mix(vec3(0.0, 0.0, 0.54), vec3(0.53, 0.81, 0.98), 1.0 - (currentTime - vTime) / trailLength);
                }
            `
        };
        // eslint-disable-next-line @typescript-eslint/no-unsafe-return
        return shaders;
    }
}
```

**Comment by felixpalmer** [comment]
Can you try with this pattern:

```js
const shaders = super.getShaders();
return {
   ...shaders,
   inject: {
     ...shaders.inject,
     'fs:DECKGL_FILTER_COLOR': '<CUSTOM_SHADER>'
   }
}
```

**Comment by felixpalmer** [comment]
My guess is that you have a different tsconfig to what we use in deck.gl, you could try to compare with what we use in deck?
