### ISSUE TITLE
Layer is only visible on one side of the map when map center is around 180th meridian

### ISSUE THREAD

**Issue by wiesehahn** [visgl/deck.gl#8546]
### Description

When the map center is somewhere around the 180th meridian (side of web mercator) the data layers are only visible either eath or west of the 180th meridian, depending where the map center is.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Layers spanning on both sides of the meridian (e.g. global layers) should be visible on both sides at all time. 

### Steps to Reproduce

For example take the [data filtering extension example](https://deck.gl/examples/data-filter-extension) zoom out and pan around the 180th meridian to see where data is rendered.

https://github.com/visgl/deck.gl/assets/41429613/9893dffe-89d9-45eb-8724-d471e380069e

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
[repeat](https://deck.gl/docs/api-reference/core/map-view#repeat)
