### ISSUE TITLE
No way to get the image data coordinates, project gives the wrong ones

### ISSUE THREAD

**Issue by KamWithK** [visgl/deck.gl#8559]
### Description

I'm trying to work with DeckGL to modify an images colours based on the pixels currently being displayed on the screen. To do so I assumed that the viewport would provide coordinates relative to the input pixe datal space. DeckGL provides a `project`method to convert coordinates into pixel space, however the bottom edge of an image does not end up correctly at (image width, image height), but instead it's around two times bigger.

I am using the Cartesian co-ordinate space. The extent of the image does not match the extent of the DeckGL Cartesian space. The coordinates of the image as rendered does not match the extent we provide.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The bottom right coordinate should be (512, 512) for an image 512x512 large.

### Steps to Reproduce

Get the viewport for example using the `updateState` function and then console log the width and height (the docs don't specify what space anything is already in) and attempt to project, unproject, worldToPixels, etc to see if it's possible to reliably find the pixel coordinates
In theory according to the docs project should produce this.

### Environment

- Framework version: 8.9.3
- Browser: Chrome
- OS: Amazon Linux 2 (RHEL)

### Logs

NA

**Comment by Pessimistress** [comment]
"No way to..." is not a bug. If you believe that the library is not functioning as intended, please provide code that demonstrate the issue. If you need help implementing your own application, use Discussions.
