### ISSUE TITLE
Sometimes width of TripsLayer is not correct

### ISSUE THREAD

**Issue by Fabioni** [visgl/deck.gl#8564]
### Description

As shown in the image the width is not correct at one place.

```js
    const data = [
        {
            coordinates: simplifiedWaypoints.map((latlng) => [latlng.lng, latlng.lat]),
            timestamp: simplifiedWaypoints.map((latlng, i) => -i)
        }
    ];


    const layer: Layer = new TripsLayer({
        id: 'xyc',
        data,
        widthScale: 1,
        widthMinPixels: 2,
        widthMaxPixels: 10,
        widthUnits: 'meters',
        fadeTrail: false,
        capRounded: true,
        billboard: true,
        jointRounded: true,
        trailLength: simplifiedWaypoints.length,
        getColor: [.20 * 255, 0.80 * 255, 0.80 * 255],
        //eslint-disable-next-line
        getPath: (d) => d.coordinates,
        //eslint-disable-next-line
        getTimestamps: (d) => d.timestamp,
    });
```

<img width="254" alt="image" src="https://github.com/visgl/deck.gl/assets/45362676/8913fbe8-3199-4ae0-be5d-884e2532f6e5">

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Unfortunately is does not appear always so I can not reproduce.

### Environment

- Framework version: "@deck.gl/google-maps": "8.9.34", "deck.gl": "8.9.35",
- Browser: Chrome
- OS: Mac

**Comment by Pessimistress** [comment]
Please provide the coordinates of the path where this occurs. We cannot debug from a screenshot.
