### ISSUE TITLE
[Bug] 3D Occlusion Non-functional in @deck.gl/mapbox interleaved rendering

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#8565]
### Description

Rendering in the mapbox and maplibre context is working, 2D map layers can layered on top of each other (i.e. labels and H3), but no 3D layer occlude (i.e. deck arc and map buildings)

<img width="807" alt="Screen Shot 2024-02-29 at 4 00 36 PM" src="https://github.com/visgl/deck.gl/assets/2461547/b7fd89fc-070d-437b-9fee-20bdd421f98a">

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

<img width="1117" alt="Screen Shot 2024-02-29 at 4 25 44 PM" src="https://github.com/visgl/deck.gl/assets/2461547/e843bfcb-3f56-4b48-adbd-9faa93afb909">

### Steps to Reproduce

Run the `safegraph` or `gallery` examples

### Environment

- Framework version: 9.0.0-beta
- Browser: Chrome
- OS: MacOS

**Comment by Pessimistress** [comment]
Likely fixed by #8543

**Comment by chrisgervang** [comment]
It isn't, I've been testing with that PR merged in

**Comment by chrisgervang** [comment]
I take it back, this was likely fixed by #8543. I needed to run `yarn start-local` since it hadn't been published yet
