### ISSUE TITLE
[Bug] Broken website examples in `9.0.0-beta.10`

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#8582]
## List of broken examples

- https://felixpalmer.github.io/deck.gl/examples/line-layer (blending is off) https://github.com/visgl/deck.gl/pull/8636

### Steps to Reproduce

Visit https://felixpalmer.github.io/deck.gl/examples

### Environment

- Framework version: 9.0.0-beta.8
- Browser: Chrome
- OS: MacOS Sonoma

**Comment by chrisgervang** [comment]
The H3 layer in the Mapbox example renders random pink hexagons.
![Screen Shot 2024-03-07 at 11 22 05 AM](https://github.com/visgl/deck.gl/assets/2461547/2480e3f6-da8f-4f00-9ba6-dc819072c20a)

**Comment by chrisgervang** [comment]
A "checkerboard" rendering bug can be found in https://felixpalmer.github.io/deck.gl/gallery/maplibre-overlay

It affects interleaved with Maplibre but not Mapbox. Opened #

**Comment by estherluque** [comment]
# List of broken examples
#### Google Chrome (Version 122.0.6261.112)
- GeoJsonLayer (Paths): https://felixpalmer.github.io/deck.gl/examples/geojson-layer-paths
- TileLayer (Geospatial): https://felixpalmer.github.io/deck.gl/examples/tile-layer map disappears when activating "Show tile borders"
- TileLayer (Non-Geospatial): https://felixpalmer.github.io/deck.gl/examples/tile-layer-non-geospatial some parts disappear when zooming in
- LineLayer: https://felixpalmer.github.io/deck.gl/examples/line-layer fade color/blending is off
- Tile3DLayer: https://felixpalmer.github.io/deck.gl/examples/tile-3d-layer 3D layer doesn't appear
- ArcGis: https://felixpalmer.github.io/deck.gl/examples/arcgis In Felix's descriptions this example is broken but it's working for me (it takes a while to load the 3D layer)
- CARTO: https://felixpalmer.github.io/deck.gl/examples/carto the context of the map is different
https://felixpalmer.github.io/deck.gl/examples/plot

**Comment by donmccurdy** [comment]
Fix for `TileLayer (Geospatial)` and `TileLayer (Non-Geospatial)`

- https://github.com/visgl/luma.gl/pull/2032

**Comment by estherluque** [comment]
# Fixed
### Google Chrome (Version 122.0.6261.112), Safari Version 17.2.1 (19617.1.17.11.12), Firefox 123.0.1 (64-bit), Microsoft Edge Version 122.0.2365.80, iPhone 12 Pro Max v.16.0 Safari and Huawei P30 V.9.0 Chrome
- ~GeoJsonLayer (Paths): https://felixpalmer.github.io/deck.gl/examples/geojson-layer-paths~ Fixed ✅ 
- ~TileLayer (Geospatial): https://felixpalmer.github.io/deck.gl/examples/tile-layer map disappears when activating "Show tile borders"~ Fixed ✅ 
- ~TileLayer (Non-Geospatial): https://felixpalmer.github.io/deck.gl/examples/tile-layer-non-geospatial some parts disappear when zooming in~ Fixed ✅ 
- ~Tile3DLayer: https://felixpalmer.github.io/deck.gl/examples/tile-3d-layer 3D layer doesn't appear~ Fixed ✅ 
- ~CARTO: https://felixpalmer.github.io/deck.gl/examples/carto The context of the map is different~  ✅`the CARTO example has been changed from the old website, so it is correct that it looks different`
- ~Minimap: https://felixpalmer.github.io/deck.gl/examples/multi-view The location map (top left - Minimap checkbox) is empty~ Fixed ✅
- ~OrbitView: https://felixpalmer.github.io/deck.gl/examples/plot "This page crashed"~ Fixed ✅ 

### Only in iPhone 12 Pro Max v.16.0 Safari
- GlobeView: https://felixpalmer.github.io/deck.gl/examples/globe-view I can't press play
- DataFilterExtension: https://felixpalmer.github.io/deck.gl/examples/data-filter-extension I can't press play
- MaskExtension: https://felixpalmer.github.io/deck.gl/examples/mask-extension I can't press play

### Only in Huawei P30 V.9.0 Chrome
- HeatmapLayer: https://felixpalmer.github.io/deck.gl/examples/heatmap-layer The map is empty
- TextLayer: https://felixpalmer.github.io/deck.gl/examples/text-layer The map is empty

# List of broken docs
### Google Chrome (Version 122.0.6261.112), Safari Version 17.2.1 (19617.1.17.11.12), Firefox 123.0.1 (64-bit) and Microsoft Edge Version 122.0.2365.80, iPhone 12 Pro Max v.16.0 Safari and Huawei P30 V.9.0 Chrome
- ArcLayer: https://felixpalmer.github.io/deck.gl/docs/api-reference/layers/arc-layer Sometimes, the layers don't appear but when the page is refreshed they appear
- GPUGridLayer: https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/gpu-grid-layer The map is empty
- HeatmapLayer: https://felixpalmer.github.io/deck.gl/docs/api-reference/aggregation-layers/heatmap-layer The map is empty
- TileLayer: https://felixpalmer.github.io/deck.gl/docs/api-reference/geo-layers/tile-layer some parts disappear when zooming in

### Only in Huawei P30 V.9.0 Chrome
- HeatmapLayer: https://felixpalmer.github.io/deck.gl/examples/heatmap-layer The map is empty
