### ISSUE TITLE
[Bug] running yarn test reports a missing dependency

### ISSUE THREAD

**Issue by james-willis** [visgl/deck.gl#8595]
### Description

It seems that `eslint-plugin-prettier@latest` is required as a devDependency to run tests:

```
➜  deck.gl git:(a81c37d9e) yarn test
yarn run v1.22.21
$ ocular-test
test [ 'full' | 'fast' | 'dist' | 'bench' | 'ci' | 'cover' | 'browser' | 'browser-headless' ]
Running 'full' test by default

> lint
> ocular-lint

Running eslint in {modules,test}...
+ npx eslint '{modules,test}/**/*.{js,mjs,jsx,ts,tsx,d.ts}'

Oops! Something went wrong! :(

ESLint: 8.56.0

ESLint couldn't find the plugin "eslint-plugin-prettier".

(The package "eslint-plugin-prettier" was not found when loaded as a Node module from the directory "/Volumes/CaseSensitive/deck.gl/bindings/pydeck/env/share/jupyter/labextensions/jupyterlab_pygments".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-prettier@latest --save-dev

The plugin "eslint-plugin-prettier" was referenced from the config file in "bindings/pydeck/env/share/jupyter/labextensions/jupyterlab_pygments/package.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expect the test suite to succeed when running `yarn test` against `master`

### Steps to Reproduce

`yarn bootstrap & yarn test`

### Environment

- Framework version: deck.gl@9.0.0-beta5
- Browser: None
- OS: MacOS 14.3.1

- Node version: 18.19.1
- Yarn version: 1.22.21

**Comment by Pessimistress** [comment]
As we discussed on Slack, this has something to do with your local dev environment, which is not described in your report. The maintainers use a range of platforms (OSX, Apple silicon, Linux, WSL) and we do not have this problem. Tests are also passing on CI.

**Comment by james-willis** [comment]
Hi Xiaoji,

Sorry for the missing details. I added the node and yarn version I am using. I found a [similar issue](https://github.com/eslint/eslint/issues/16694) on the eslint repository and will use that to see if I can resolve the issue without adding the dependency.

A couple of my coworkers were able to reproduce the issue which made me think it was something beyond my personal setup.

**Comment by Pessimistress** [comment]
Ok I see what's going on. You have run the setup script in `bindings/pydeck`, so maybe include that in "step to reproduce"?

Running `npx eslint '{modules,test}/**/*.{js,mjs,jsx,ts,tsx,d.ts}'` apparently attempts to load config in a directory (`bindings/pydeck/env/...`) although it does not match the glob pattern. `npx eslint 'modules/**/*.{js,mjs,jsx,ts,tsx,d.ts}'` seems to be fine. ¯\_(ツ)_/¯
