### ISSUE TITLE
[Feat] For map/layer onClick handle to return 3D coordinates of the touched surface, not just the 2D coordinates of the "ground behind the object" 

### ISSUE THREAD

**Issue by Mandelag** [visgl/deck.gl#8619]
### Target Use Case

For 3D modelling in a Web Mercator Projection (eg. buildings).

Sometimes layer/geometry start at Z > 0. 
And often times 3D geometry are extruded from building footprints.

Usually we want to be able to click "on top" of the surface, and show pop up there, in that "touch point" coordinate. 
But instead of the "touch" point, the returned coordinate is of the "touched" ground at Z =0. Forgive my crude drawings, but here is the illustrations:

![image](https://github.com/visgl/deck.gl/assets/8395361/cf6210a6-53b7-4ac7-81fa-653ff1cc56d2)

The onClick handler data. Notice that `coordinates` only have 2 length, [long, lat] only:
![image](https://github.com/visgl/deck.gl/assets/8395361/d331d57d-f671-41d3-978d-8cd966a328ae)

It would be nice to give the `onClick()` handler the touch 3D coordinates.

I'm using geospatial layer with custom center (using delta x, delta y).
In React,
```
  "devDependencies": {
    ...
    "core": "link:@types/deck.gl/core",
    "layers": "link:@types/deck.gl/layers",
    "typescript": "^5"
  }
```
```
  "dependencies": {
    ...
    "@deck.gl/core": "^8.9.7",
    "@deck.gl/extensions": "^8.0.0",
    "@deck.gl/geo-layers": "^8.9.34",
    "@deck.gl/layers": "^8.9.7",
    "@deck.gl/mesh-layers": "^8.0.0",
    "@deck.gl/react": "^8.9.7",
    ...
}
```

### Proposal

It would be nice to give the `onClick()` handler the touch 3D coordinates.

**Comment by Pessimistress** [comment]
Call the [pickObject](https://deck.gl/docs/api-reference/core/deck#pickobject) method with `unproject3D: true`.

**Comment by Mandelag** [comment]
Thanks for the quick reply @Pessimistress. Is there a way, or any plans, to make it more React friendly (without using `ref`)? 
eg. by giving `onClick` parameter the deck reference or the `pickObject` function ...?

Is that something we can contribute ..?
