### ISSUE TITLE
How to update layer properties without creating new layer instances?

### ISSUE THREAD

**Issue by heyu3913** [visgl/deck.gl#8654]
### Target Use Case

Body:

I'm using PathLayer from deck.gl to render map path data. In my application, I need to frequently update the data of the layer, and I've noticed that every time I update the data, a new layer instance is created. This leads to an issue of increasing browser memory usage over time.

I'd like to know how to avoid creating unnecessary new layer instances when updating the layer data. Is there a way to directly update the properties of the existing layer instance without creating a new one?

If there are any feasible methods or best practices, please provide some guidance so that I can optimize my application and reduce the increase in memory usage.

Thank you!

### Proposal

If the feature involves updating layer properties without creating new layer instances, it would likely involve extending the existing API to include methods for directly updating layer properties. Here's how it might work in code:

javascript

// Define the initial data and create the PathLayer instance
const initialData = [
  {
    path: [[-122.4, 37.7], [-122.5, 37.8], [-122.6, 37.85]],
    name: 'Richmond - Millbrae',
    color: [255, 0, 0]
  },
  // Other data...
];

// Create the initial PathLayer instance
let pathLayer = new PathLayer({
  id: 'path-layer',
  data: initialData,
  pickable: true,
  widthScale: 20,
  widthMinPixels: 2,
  getPath: d => d.path,
  getColor: d => colorToRGBArray(d.color),
  getWidth: d => 5
});

// Update the data and color of the existing PathLayer instance
function updateLayer(newData) {
  // Update the data property
  pathLayer.props.data = newData;

  // Update the color accessor function
  pathLayer.props.getColor = d => colorToRGBArray(d.color);

  // You can update other properties similarly as needed

  // Trigger a re-render or update of the layer
  // For example, you might call pathLayer.update() if such a method exists
  // pathLayer.update();
}

// Call the updateLayer function with new data
updateLayer(newData);

In this example, updateLayer function is responsible for updating the data and color properties of the existing PathLayer instance. This approach allows for efficient updates to the layer without creating new instances, thus reducing memory usage and potential performance overhead.

**Comment by Pessimistress** [comment]
Please read the template instructions before filing an issue. Use discussions to ask how to questions.
