### ISSUE TITLE
[Feat]Update PathLayer to allow shape changes via data updates

### ISSUE THREAD

**Issue by heyu3913** [visgl/deck.gl#8656]
### Target Use Case

This feature enhancement is particularly useful for applications where dynamic updates to the shapes rendered by the PathLayer are required based on real-time data changes. For example, in a mapping application that displays the location of moving objects, such as vehicles or aircraft, the ability to update the shapes of paths representing their trajectories in real-time would provide a more accurate and up-to-date visualization of their movements. Additionally, in scenarios where the underlying data undergoes frequent changes or updates, such as in live tracking systems or IoT applications, the proposed feature would enable developers to seamlessly update the shapes rendered by the PathLayer without incurring the overhead of recreating the layer instance. Overall, this enhancement targets use cases where dynamic and responsive visualization of spatial data is essential for providing users with valuable insights and actionable information.

### Proposal

The current implementation of the PathLayer in deck.gl is highly efficient and user-friendly. However, it requires recreating the layer instance every time the data changes, which can be inefficient and resource-intensive.

To address this limitation and improve usability, I propose enhancing the PathLayer to support shape changes directly through data updates. This would allow users to modify the shapes rendered by the PathLayer without the need to recreate the layer instance.

The proposed solution could involve adding a method or property to the PathLayer that facilitates shape updates based on changes in the underlying data. For example, users could update the coordinates or attributes of existing paths in the data, and the PathLayer would automatically reflect these changes in the rendered shapes.

By enabling shape changes via data updates, this enhancement would streamline the workflow for users and improve performance by eliminating the need for unnecessary layer recreation.

This feature would greatly enhance the flexibility and usability of the PathLayer, making it even more versatile for a wide range of use cases.

**Comment by Pessimistress** [comment]
Creating new layer instances do not recreate new resources or use more memory.

https://deck.gl/docs/developer-guide/using-layers#should-i-be-creating-new-layers-on-every-render

**Comment by heyu3913** [comment]
> Creating new layer instances do not recreate new resources or use more memory.
> 
> https://deck.gl/docs/developer-guide/using-layers#should-i-be-creating-new-layers-on-every-render

Thank you for your answer
