### ISSUE TITLE
[Bug] Distorted Hexagons at resolutions 13 - 15

### ISSUE THREAD

**Issue by Szabadember** [visgl/deck.gl#8674]
### Description

Hexagons are rendered distorted in both Chrome and Safari but they render fine in Firefox. This seems to happen at high (13 - 15) resolutions. See attached screenshot and code pen example.

<img width="1814" alt="image" src="https://github.com/visgl/deck.gl/assets/5400248/fce8b561-91f7-46fd-b095-b27fef4b966a">

Minimal reproducible example: https://codepen.io/sjksajk/pen/vYMyqrM

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expect to see no gaps/displacement when using H3HexagonLayer. I expect the same results in Chrome, Safari as in Firefox.

### Steps to Reproduce

Here is working codepen example
https://codepen.io/sjksajk/pen/vYMyqrM

### Environment

- Framework version: 8.9.34
- Browser: Google Chrome v122
- OS: macOS 14.2.1

**Comment by felixpalmer** [comment]
I just tested on MacOS 14.3 (23D56), Chrome 122 and cannot reproduce. What chip & GPU do you have?

**Comment by Szabadember** [comment]
I accidentally changed the DeckGL version from 8.9.34 to 8.9.35. It seems that 8.9.35 fixes the issue.
