### ISSUE TITLE
Layer-browser props interface issues

### ISSUE THREAD

**Issue by 1chandu** [visgl/deck.gl#871]
`examples/layer-browser` gives nice interface to change layer props, but it is failing in following cases : 

- [ ]  When chagning a color prop which is vec4 (RGBA), color picker always returns vec3 (RGB) and app crashes as corresponding setUniform method fails. (ex: ScreenGridLayer: `minColor`, `maxColor`, or `highlightColor` on any layer)

- [ ] Props that are Integers (like `highlightedObjectIndex`), have slider that provides values from 0.0 to 1.0, but we should have a way to enter an integer (or specify the range to be 0 to N).

CC: @ibgreen @shaojingli

**Comment by shaojingli** [comment]
We probably need some new forms of controls in our layer browser example. @Pessimistress what are your thoughts on this?

**Comment by ibgreen** [comment]
> Props that are Integers (like highlightedObjectIndex), have slider that provides values from 0.0 to 1.0, but we should have a way to enter an integer (or specify the range to be 0 to N).

This could be addressed in a very clean way by the [PropTypes RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.0/prop-types-rfc.md), where the idea is that a Layer could declare not only the type but also the permissible range of a prop.

> When chagning a color prop which is vec4 (RGBA), color picker always returns vec3 (RGB) and app crashes as corresponding setUniform method fails. (ex: ScreenGridLayer: minColor, maxColor, or highlightColor on any layer)

Most layers do a check on the fourth component, setting it to 255 if not supplied. It is a bit error prone that this needs to be manually done. In fact this is another issue that could be addressed with a prop types RFC (e.g. using Color.RBG and Color.RGBA types).
