### ISSUE TITLE
[Bug] luma.gl: Model.updateModuleSettings is deprecated. Use Model.shaderInputs.setProps() warning message in the console. Layer class

### ISSUE THREAD

**Issue by hifichevymane** [visgl/deck.gl#8725]
### Description

`Layer` class uses a deprecated method. So every time I get warning message in the console:
```
luma.gl: Model.updateModuleSettings is deprecated. Use Model.shaderInputs.setProps()
```

**layer.js**:
```
// TODO deprecate in favour of setShaderModuleProps
/** Update shader module parameters */
setModuleParameters(moduleParameters) {
    for (const model of this.getModels()) {
        model.updateModuleSettings(moduleParameters);
    }
}
```

I use `MapboxOverlay` to display my layers on a `MapboxGL` map. When I pass my `MapboxOverlay` instance in `map.addControl` method as an argument I start to receive this warning message in the browser's console. But as I see it's a `Layer` class problem. Can you please fix this in the new update? Thank you

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

There is no warning message in the console

### Steps to Reproduce

1. Create a `Map` instance from `mapboxgl` library
2. Create a `MapboxOverlay` instance and pass some deck.gl layers(I use `TileLayer` with `GeoJsonLayer` as sub layer)
3. Call `addControl` method of `Map` instance and pass created `MapboxOverlay` instance
4. Check console in the browser

### Environment

- Framework version: 
  1. deck.gl: ^9.0.1,
  2. mapbox-gl: ^3.2.0,
- Browser: Chrome
- OS: Linux Mint

### Logs

![image](https://github.com/visgl/deck.gl/assets/106327285/54bdff3d-7a5b-4542-a255-fda69d8d8212)

**Comment by Pessimistress** [comment]
Addressed by https://github.com/visgl/deck.gl/pull/8696, will be in the next patch.
