### ISSUE TITLE
[Bug] Filter extension soft range unexpected behavior

### ISSUE THREAD

**Issue by jdgarrett** [visgl/deck.gl#8774]
### Description

When using the filter extension, using a soft range that matches the filter range causes the filter to become start exclusive (it will filter out any values that match the minimum filter value.  The use case where this becomes an issue is where you only want to use soft filtering on one of the channels.  For example, if I have one attribute that I would like to apply soft filtering on, and a second attribute that I want to perform exact filtering on.  if I have a feature with a filter value of 3  in the exact channel and a filter of 3-5 and a soft filter of 3-5, the feature will not be visible.

### Expected Behavior

I would expect the soft filter to do nothing if the minimum or maximum value matches the minimum or maximum value of the base filter range.

### Steps to Reproduce

I have created a codepen that reproduces this behavior:
https://codepen.io/jdgarrett/pen/wvZjqLe
In this codepen, there should be a single feature that is visible because it lies within the first channel soft range and matches the second channel filter exactly.  There are comments in the codepen that explains in a bit more detail.

After digging into the code, this appears to be happening due to a divide by zero in the smoothstep function.  I would recommend doing a regular filter check for min/max if the smooth filter value matches the filter value.

### Environment

- Framework version: deck.gl@8.9.0
- Browser: Chrome 123.0
- OS: Windows

**Comment by Pessimistress** [comment]
v9.0.9
