### ISSUE TITLE
[Bug] Layer is not cleared when data is empty with version 9

### ISSUE THREAD

**Issue by davidecassenti** [visgl/deck.gl#8776]
### Description

When updating a layer with an empty array of data, the rendered layer does not get properly cleared.

This seems to happen on several different layers, such as `TextLayer` or `IconLayer`. It starts to happen with version 9, while it was working properly before (tested `8.9.35`).

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Nothing should be rendered when the data array is empty.

### Steps to Reproduce

I used the example in the `TextLayer` documentation page (Edit on Codepen): https://deck.gl/docs/api-reference/layers/text-layer

- Change the JS code with the following:

```javascript
const {DeckGL, TextLayer} = deck;

let data = ['Foo Bar'];

const deckInstance = new DeckGL({
  mapStyle: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
  initialViewState: {
    longitude: 0,
    latitude: 51,
    zoom: 8,
  },
  layers: []
});

function redraw() {
  const layer = new TextLayer({
    id: 'TextLayer',
    data,
    getPosition: d => [0, 51, 0],
    getSize: 16,
    getText: d => d,
  });
  
  deckInstance.setProps({ layers: [layer] });
}

document.addEventListener('click', () => {
  if (data.length === 0) {
    data = ['Foo Bar'];
  } else {
    data = [];
  }

  redraw();
});

redraw();
```

- you will see the `Foo Bar` label rendered
- click on the map: this will replace the `data` with an empty array
- see that there is still the letter `F` rendered in page

### Environment

- Framework version: deck.gl@9.0.0+
- Browser: Chrome
- OS: MacOS

**Comment by Pessimistress** [comment]
@ibgreen This is caused by https://github.com/visgl/luma.gl/blob/92e6c59972e9c21ac704c8dc7766607da73d45fb/modules/webgl/src/adapter/resources/webgl-render-pipeline.ts#L188

When a layer is empty, `model.draw` is called with `instanceCount:0`.

**Comment by Pessimistress** [comment]
v9.0.9
