### ISSUE TITLE
[Bug] autoHighlight on a TileLayer with multiple sub layers

### ISSUE THREAD

**Issue by guillaume** [visgl/deck.gl#8787]
### Description

When using `autoHighlight` on a tile layer with multiple sub layers, the highlighted object spans across other features that are not hovered. 

In the comments of the [codepen](https://codepen.io/guillohm/pen/vYMrVOE), I indicate other ways to configure the layers where the bug does not occur.

* The issue didn't always occur. I found the issue started occurring at release  8.8.27 but it still occurs with the latest release 9.0.7. Other releases prior to that worked fine. For example 8.8.22 does not have this issue.
* The issue does not occur if the features meant for rendering are combined into a single sub layer of the TileLayer. I thought that could indicate a misusage of the framework but the doc states that it's supported to render multiple subLayers (an array)[ "Renders one or an array of Layer" ](https://deck.gl/docs/api-reference/geo-layers/tile-layer#rendersublayers)
* The issue does not occur if the geojson layers are rendered directly when they are not a subLayer of a TileLayer 

https://github.com/visgl/deck.gl/assets/368/cb106985-8d67-46d6-b91d-cc5430f1218f

### Flavors

- [X] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Only the hovered feature should be highlighted

### Steps to Reproduce

[codepen example](https://codepen.io/guillohm/pen/vYMrVOE) 

### Environment

- Framework version: deckgl@8.8.27 through current release 9.0.7
- Browser: Chrome 123.0.6312.123
- OS: Mac and Linux

**Comment by Pessimistress** [comment]
v9.0.9
