### ISSUE TITLE
[Bug] cannot reference the same b3dm

### ISSUE THREAD

**Issue by skemaikin** [visgl/deck.gl#8846]
### Description

Cannot use children containing content sections with the same b3dm file. Only one of them will be rendered. For example, I want to multiply the same model (f.e. tree) by placing it in several locations.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

draw multiplied model

### Steps to Reproduce

example tileset:
[tileset.zip](https://github.com/visgl/deck.gl/files/15138179/tileset.zip)

### Environment

- Framework version: deck.gl 8, deck.gl 9
- Browser: Chrome, Mozilla
- OS: Ubumtu 22.04

**Comment by Pessimistress** [comment]
Use the [ScenegraphLayer](http://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer).

If you still think there is a bug, provide code that reproduces your issue. If you just want help with usage of the API, use Discussions instead.
