### ISSUE TITLE
[Doc] AttributeManager.addInstanced behaviour change on upgrade to deck.gl 9.x

### ISSUE THREAD

**Issue by landtechjoe** [visgl/deck.gl#8849]
### Description

We had some code that handles adding gradient colour to a scatter plot layer depending on the type of object that the scatter plot item is. After updating to deck.gl 9 the code looked something like this

```
this.getAttributeManager()?.addInstanced({
      fillGradientStop: {
        size: this.props.colorFormat?.length,
        transition: true,
        type: "unorm8",
        accessor: "getPointGradientStop",
        defaultValue: [0, 0, 0, 0],
      },
    });
```

We were having issues still though. On any tile that had one of these dots that required a gradient fill all the other dots were also being affected and being rendered with a gradient (but not correctly rendered as we would expect).

Using the luma.gl debugging tools I could see that `fillGradientStop` was being passed as a `vertex` attribute instead of an `instanced` attribute despite the fact that we were calling `addInstanced` to add the attribute. After checking for problems everywhere else I finally thought I would try changing the property name to `instanceFillGradientStop` as I noticed all the instanced properties from deck.gl had that prefix (although I assumed it was just good practice so you could easily see which props were instanced by looking at their names) I didn't expect the attribute name change to fix anything but that did indeed fix the problem and start rendering things correctly and pass the gradient stop value in as an instanced attribute.

I couldn't find anything mentioning this in the docs and it wasn't necessary in deck.gl 8. I couldn't find anything mentioning this change in the luma.gl library as a requirement for instanced attributes either. There is definitely a chance that is mentioned and I just missed but I definitely think it should be called in out in **bold** in the `AttributeManager.addInstanced` documentation to save people from this same headache.

Working code below 🤦 

```
this.getAttributeManager()?.addInstanced({
      instanceFillGradientStop: {
        size: this.props.colorFormat?.length,
        transition: true,
        type: "unorm8",
        accessor: "getPointGradientStop",
        defaultValue: [0, 0, 0, 0],
      },
    });
```

**Comment by Pessimistress** [comment]
I think this should be a bug.

**Comment by ibgreen** [comment]
Agreed, its a bug.
