### ISSUE TITLE
[Bug] Typings for depthTest parameters not defined

### ISSUE THREAD

**Issue by albasitum** [visgl/deck.gl#8900]
### Description

Hi, we have recently updated deckgl to its latest version in our react application, however I have encountered an issue related to how the GPU parameters are being typed. In our project we are using `depthTest` quite heavily and from what I have seen it has not yet been added to the parameter types. 

Is this intentional? That is, should we use another prop instead of that one to control depth testing properly? Because from the tests we have conducted it is still being used internally. Or are you planning on adding this parameter to the typings?

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Uupdate deckgl on a project that uses `depthTest` and has typescript configured and simply run `tsc`

### Environment

- Framework version: deck.gl@9.0.14

**Comment by donmccurdy** [comment]
Hi @albasitum! The v9 API is closer to WebGPU, and uses `depthCompare`. For example:

```javascript
new GeoJsonLayer({
      id: 'roads',
      ...
      parameters: {depthCompare: 'always'}
}),
```

**Comment by albasitum** [comment]
Thanks for the quick response! We'll look into using `depthCompare` instead. I have one other question, is there a way to define this parameter on an instance basis?. Something like this:

`
depthCompare: (d) => condition ? "always" : "never"
`

**Comment by ibgreen** [comment]
No. Filter your instances (e.g. into two tables) and draw twice.
