### ISSUE TITLE
[Bug] test-utils: Failed to created device 'undefined': Cannot read properties of null (reading 'addEventListener')

### ISSUE THREAD

**Issue by davidcalhoun** [visgl/deck.gl#8912]
### Description

This error is triggered when importing `testLayer`:

```
import { testLayer } from "@deck.gl/test-utils";

/*
error after running test:
  console.error
    Failed to created device 'undefined': Cannot read properties of null (reading 'addEventListener')

    > 1 | import { testLayer } from "@deck.gl/test-utils";
        | ^
      2 |

      at createTestDevice (.yarn/__virtual__/@luma.gl-test-utils-virtual-e7922c1f22/3/.yarn/berry/cache/@luma.gl-test-utils-npm-9.0.14-cb312c65ae-10c0.zip/node_modules/@luma.gl/test-utils/dist/create-test-device.js:25:17)
      at Object.<anonymous> (.yarn/__virtual__/@luma.gl-test-utils-virtual-e7922c1f22/3/.yarn/berry/cache/@luma.gl-test-utils-npm-9.0.14-cb312c65ae-10c0.zip/node_modules/@luma.gl/test-utils/dist/create-test-device.js:30:28)
      at Object.<anonymous> (.yarn/__virtual__/@deck.gl-test-utils-virtual-39bcfdacb3/3/.yarn/berry/cache/@deck.gl-test-utils-npm-9.0.14-934d2420c7-10c0.zip/node_modules/@deck.gl/test-utils/dist/utils/setup-gl.js:1:48)
      at Object.require (test.js:1:1)
*/
```

Please see the minimal test case I created here: https://github.com/davidcalhoun/deck.gl-test-utils-bug

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Please see a minimal reproduction here: https://github.com/davidcalhoun/deck.gl-test-utils-bug

### Environment

- Framework version: deck.gl@9.0.14
- Browser: N/A
- OS: macOS 14.3.1

**Comment by Pessimistress** [comment]
The error is expected because your node environment does not support WebGL2. #8968 will allow the layer tests to run without a WebGLRenderingContext.

@ibgreen I think `createTestDevice` should log something more informative than the raw error. Although it is non-blocking (calling `console.error` from within `catch`) it certainly looks like the process has crashed.

**Comment by davidcalhoun** [comment]
@Pessimistress @ibgreen Great, thank you both for the context and the fix!

**Comment by yonghah** [comment]
The error seems to still happen with simple import such as (the same as @davidcalhoun):
```
import { testLayer } from "@deck.gl/test-utils";
```
The error message is little bit different:
```
Failed to created device: Cannot read properties of null (reading 'getContext')
```
My @luma.gl version is 9.1.4 and @deck.gl version is 9.1.3.

**Comment by Pessimistress** [comment]
@yonghah this issue was closed because it was fixed on the minor release where it was reported. If you are experiencing it on a newer release you need to open your own issue.
