### ISSUE TITLE
[Bug] Repeat false seems to be no longer working on MapView

### ISSUE THREAD

**Issue by ricardoekm** [visgl/deck.gl#8916]
### Description

Setting repeat false on MapView seems to be ignored.

### Flavors

- [X] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

https://codepen.io/vis-gl/pen/MWbwyWy

<img width="1507" alt="Screenshot 2024-05-22 at 15 14 32" src="https://github.com/visgl/deck.gl/assets/747894/8f8d9dee-6735-4270-b7a2-26c21d10f467">

### Environment

- Browser: Chrome
- OS: MacOS

**Comment by Pessimistress** [comment]
What are you expecting here? Setting `repeat: false` will only render one copy of your scatterplot layer, which is obviously working in your screenshot. The base map is not controlled by the MapView option.

Also what do you mean by "no longer"? Was previous versions working differently?

**Comment by ricardoekm** [comment]
Thanks for the response @Pessimistress. It seems I was tricked by my memory (pushed a bit by the docs: "Whether to render multiple copies of the map at low zoom levels"). 

I thought this parameter would avoid repeating the map itself. Any way to accomplish that?

**Comment by Pessimistress** [comment]
You can add the following to the `DeckGL` constructor:

```js
  mapOptions: {
    renderWorldCopies: false
  },
```

**Comment by ricardoekm** [comment]
Awesome! Thanks!!!

**Comment by geraldo** [comment]
This doesn't work so with _GlobeView_. When changing to GlobeView [in this example](https://github.com/visgl/deck.gl/blob/master/examples/get-started/pure-js/maplibre/app.js) features are repeated.

PS: I also don't see _renderWorldCopies_ in the documentation, is that obsolete?
