### ISSUE TITLE
[Feat] add getSourceColor, getTargetColor to PathLayer

### ISSUE THREAD

**Issue by tonnoz** [visgl/deck.gl#8918]
### Target Use Case

Pretty straightforward I would like to see a gradient for paths. Currently it is possible only for a solid color.

### Proposal

just like for GreatCircleLayer
![image](https://github.com/visgl/deck.gl/assets/2478866/8433bca1-6763-4c39-82dc-59df6146c83f)

**Comment by Pessimistress** [comment]
You can return one color for each vertex in PathLayer's getColor.
