### ISSUE TITLE
[Feat] Stacking Columns (columnlayer)

### ISSUE THREAD

**Issue by Trollgeir** [visgl/deck.gl#8929]
### Target Use Case

I'd like to create stacking columns in which I could represent different layers of information, akin to the embedded illustration:

![image](https://github.com/visgl/deck.gl/assets/7591857/4e60448c-90ab-49b0-b00f-9062b529c836)

### Proposal

Right now I can stack columns inside each other on the same position, and set different heights. I believe all that is needed to create this is a data accessor which can set a relative height as a starting point for the column.

**Comment by Pessimistress** [comment]
You can already return a 3D base position with `getPosition`.

**Comment by Trollgeir** [comment]
Thank you, that worked! I was sure I had tried this before without success, but I must have done something wrong.
