### ISSUE TITLE
[Bug] IconLayer: highlightedObjectIndex only takes effect until next render

### ISSUE THREAD

**Issue by samschurter** [visgl/deck.gl#8936]
### Description

When a user selects an object (from a menu external to deck.gl), I am trying to emphasize the associated icon by highlighting it in a different color and making it bounce. To achieve this I am setting `highlightedObjectIndex` and animating the position.

However, on the second step, when I animate the position to create the bounce, the highlight is lost, even though `highlightedObjectIndex` is still set. 

### Flavors

- [x] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [X] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The selected icon should remain highlighted as long as `highlightedObjectIndex` is set. 

### Steps to Reproduce

https://codepen.io/samschurter/pen/pomrJBM

### Environment

- Framework version:
    - "@deck.gl/google-maps": "^9.0.14",
    - "@deck.gl/layers": "^9.0.14",
- Browser: Chrome Version 125.0.6422.142 (Official Build) (arm64)
- OS: MacOS 14.5

**Comment by Pessimistress** [comment]
I will publish a patch, though this can be avoided by setting `highlightColor` to a constant.

**Comment by samschurter** [comment]
Thanks!
