### ISSUE TITLE
Pick interaction not firing

### ISSUE THREAD

**Issue by brandonjpierce** [visgl/deck.gl#9016]
### Description

My team and I are creating a "wrapper" component that does data wrangling and logic and then allows us to render a sublayer of our liking. We modeled the API of this based on `TileLayer` where you can pass a `getSubLayers` prop that returns the layer(s) you want to render.

In the codepen example below you will see a class called `WrapperLayer` that is extremely barebones but showcases an odd issue we are seeing:

Basically if we apply a `onHover` callback to a layer returned from the `renderSubLayers` prop, it will not fire.

I wasn't immediately sure _why_ this would be the case considering this paradigm works completely fine with a `TileLayer`. Any ideas?

### Flavors

- [X] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

`onHover` callback is executed for the layer rendered inside of `renderSubLayers`

### Steps to Reproduce

https://codepen.io/brandon_pierce/pen/bGPNvyO

### Environment

- Framework version: `@latest`
- Browser: Chrome
- OS: MacOS

**Comment by Pessimistress** [comment]
This is by design, see [event propagation](https://deck.gl/docs/developer-guide/custom-layers/picking#event-propagation).

In short, only a top-level layer (i.e. a layer that is passed to Deck's `layers` prop) can invoke its picking callback. You should implement the `getPickingInfo` method of your custom composite layer to handle any picking events from its sub layers.

**Comment by brandonjpierce** [comment]
I'll go ahead and update the codepen, but wanted to confirm your recommendation above:

1. Add a `getPickingInfo` to the `WrapperLayer` class
2. Add the `onHover` callback to the `WrapperLayer` instead of the `ScatterplotLayer`

Why does this technique work just fine for TileLayer?
