### ISSUE TITLE
[Bug] MapboxOverlay throw id already exists when interleaved=true

### ISSUE THREAD

**Issue by chunlampang** [visgl/deck.gl#9043]
### Description

Any layer inside `MapboxOverlay` will throw `Error: Layer with id "layer-id" already exists on this map` when `interleaved` is set to `true`.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

No error

### Steps to Reproduce

```
const { MapboxOverlay, TextLayer } = deck;

mapboxgl.accessToken = 'token';
const map = new mapboxgl.Map({
  container: document.body,
  style: "mapbox://styles/mapbox/light-v11",
  center: [0, 0],
  zoom: 10,
});

map.on('load', () => {
  const mapboxOverlay = new MapboxOverlay({
    interleaved: true,
    layers: [
      new TextLayer({
        id: 'TextLayer1',
        getText: (d) => d.name,
        getPosition: (d) => d.position,
        data: [
          { name: 'Hiiiii', position: [0, 0] }
        ]
      })
    ]
  });
  map.addControl(mapboxOverlay);
});
```

### Environment

deck.gl@9.0.24
mapbox-gl@3.5.2

**Comment by moong23** [comment]
It seems like the issue is with `mapbox-gl@3.5.2`. I found that no errors occur with version 3.5.1 of mapbox-gl. I've also reported the bug to the `mapbox-gl` library.
https://github.com/mapbox/mapbox-gl-js/issues/13239

**Comment by Pessimistress** [comment]
Thanks for bringing this to our attention. I provided a reproduction on the upstream issue thread.

**Comment by dekc** [comment]
FYI same error occurs with previous major deck.gl version. That is

- deck.gl@8.9.36
- mapbox-gl@3.5.2

**Comment by Pessimistress** [comment]
@dekc this is a Mapbox bug, not deck.gl's. It's been acknowledged by Mapbox.

**Comment by chunlampang** [comment]
In mapbox-gl 3.6.0, they solved the bug, but created another error.
`TypeError: Cannot read properties of undefined (reading 'setProps')`

**Comment by aemonm** [comment]
Specifically the issue is now caused by this section of code:
```javascript
function DeckGLOverlay(props: DeckProps) {
  const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props));
  overlay.setProps(props);
  return null;
}
```

which is [found here in the MapboxOverlay section](https://deck.gl/docs/api-reference/mapbox/mapbox-overlay) of the docs.  Issue is present in `mapbox-gl: 3.6.0`

**Comment by chunlampang** [comment]
> In mapbox-gl 3.6.0, they solved the bug, but created another error. `TypeError: Cannot read properties of undefined (reading 'setProps')`

Someone opened another issue for this case. https://github.com/visgl/deck.gl/issues/9086
