### ISSUE TITLE
[Bug] Category Filters: DataFilterExtension 

### ISSUE THREAD

**Issue by nogurtMon** [visgl/deck.gl#9049]
### Description

 I was able to get one category filter to work, but I am struggling to get multiple category filters to work via the DataFilterExtension.

Please help!

Here's a CodeSandbox that replicates the issue: [Code Sandbox](https://codesandbox.io/p/sandbox/modern-voice-f4f2dz)
### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

When multiple filters are selected, points should appear.

### Steps to Reproduce

Here's a CodeSandbox that replicates the issue: [Code Sandbox](https://codesandbox.io/p/sandbox/modern-voice-f4f2dz)

Click any two filters and notice all points disappear.

Uncomment the commented code and see how the expected implementation does not support even one category filter.

### Environment

- Framework version:
- Browser: Chrome
- OS:

**Comment by Pessimistress** [comment]
Extension settings (`categorySize` in this case) are not designed to change on the fly. Think of a layer + extension combination as a new type of layer - you can't change the same layer from Scatterplot to Text.

You have two options here:

- Change the layer's id when you need to change `categorySize`, e.g.
	```ts
	  id: `myLayer-${categorySize}-filters`
	```
  This of course will cause the old layer to be removed, a new layer initialized and all the data reloaded.

- Always render the layer with 2 category filters, e.g.
	```ts
  new MVTLayer({
      id: "anaerobic-digesters",
      data: "https://martin-image-35hapjdxpq-uc.a.run.app/anaerobic_digesters_main_deduplicated",
      minZoom: 0,
      maxZoom: 16,
      pointRadiusMinPixels: 5,
      getFillColor: [255, 0, 0],
      pickable: true,
      getFilterCategory: (d) => {
        const category = d.properties.category || "";
        const type = d.properties.type || "";
    
        return [category, type];
      },
      filterCategories: [
        hasCategoryFilter ? selectedCategories : [
              "Agricultural",
              "Research",
              "Wastewater",
              "Stand-alone",
              ""
          ],
        hasTypeFilter ? selectedTypes : [
            "Plug Flow",
            "Dry fermentation",
            "Complete Mix",
            "Covered Lagoon",
            ""
          ]
      ],
      extensions: [
        new DataFilterExtension({categorySize: 2}),
      ]
    })
	```

	Note that `getFilterCategory` does not require recalculation on filter selection.

**Comment by Pessimistress** [comment]
@felixpalmer There doesn't seem to be a way to disable a single filter channel. Maybe the extension could support setting `filterCategories` to `null`?

**Comment by nogurtMon** [comment]
> Extension settings (`categorySize` in this case) are not designed to change on the fly. Think of a layer + extension combination as a new type of layer - you can't change the same layer from Scatterplot to Text.
> 
> You have two options here:
> 
> * Change the layer's id when you need to change `categorySize`, e.g.
>   ```ts
>      id: `myLayer-${categorySize}-filters`
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   This of course will cause the old layer to be removed, a new layer initialized and all the data reloaded.
> * Always render the layer with 2 category filters, e.g.
>   ```ts
>   new MVTLayer({
>      id: "anaerobic-digesters",
>      data: "https://martin-image-35hapjdxpq-uc.a.run.app/anaerobic_digesters_main_deduplicated",
>      minZoom: 0,
>      maxZoom: 16,
>      pointRadiusMinPixels: 5,
>      getFillColor: [255, 0, 0],
>      pickable: true,
>      getFilterCategory: (d) => {
>        const category = d.properties.category || "";
>        const type = d.properties.type || "";
>    
>        return [category, type];
>      },
>      filterCategories: [
>        hasCategoryFilter ? selectedCategories : [
>              "Agricultural",
>              "Research",
>              "Wastewater",
>              "Stand-alone",
>              ""
>          ],
>        hasTypeFilter ? selectedTypes : [
>            "Plug Flow",
>            "Dry fermentation",
>            "Complete Mix",
>            "Covered Lagoon",
>            ""
>          ]
>      ],
>      extensions: [
>        new DataFilterExtension({categorySize: 2}),
>      ]
>    })
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   Note that `getFilterCategory` does not require recalculation on filter selection.

Wow. The id fix works great. Thank you!
