### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Saumya-NebCodes** [visgl/deck.gl#9105]
### Description

I am using Scatterplot, PolygonLayer and TileLayer layer to display the grids as you may see in video everything works fine on Linux and WIndows but in macOs for some reason the Scatterplot layer seems to disappear as soon as I go in 3D view and try to zoom In/Out. If I remove my PolygonLayer then grids stop disappearing rather they start flickering with grid halfway disappears. Also this issue is not specific to just Scatterplot layer even my SolidPolygon Layer and Bitmap layer have this similar issue.

Deckgl version: **8.9.36**
macOs version: **Sonoma 14.0 (even tried in latest macOs)**
Chrome version: **128.0.6613.84 (In safari also facing this issue)**

[screencast-192.168.29.102_8100-2024.08.24-21_53_29.webm](https://github.com/user-attachments/assets/4f49e1a6-8409-488a-ac13-71920f1b3133)

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Using TileLayer for map. PolygonLayer for blue box and ScatterplotLayer for grids. and to dsiplay grid data I am using .parquet file format.

### Environment

- Framework version: deckgl@8.9.36
- Browser: chrome 128.0.6613.84
- OS: macOs Sonoma 14.0

**Comment by Pessimistress** [comment]
Please provide code and data that the maintainers can use to reproduce your issue. We cannot debug from a screen recording.
