### ISSUE TITLE
[Feat] Update WASM package used for deck.gl/geo-layers

### ISSUE THREAD

**Issue by weldonji** [visgl/deck.gl#9121]
### Target Use Case

Versions of @deck.gl/geo-layers v9 and later use an out of date WASM build of FFmpeg code (lzo-wasm/0.0.4). This is a security risk and causes the latest package version to be blocked from secure repositories.

### Proposal

Use a different package that is not out of date.

**Comment by Pessimistress** [comment]
@ibgreen @belom88 this is a dependency from `@loaders.gl/3d-tiles` > `@loaders.gl/compression`

**Comment by weldonji** [comment]
Thank you for the quick response. Sorry, for opening this ticket in the wrong package. I opened one with loaders.gl now: https://github.com/visgl/loaders.gl/issues/3072

**Comment by ibgreen** [comment]
Responded in the loaders.gl issue.
