### ISSUE TITLE
Using Google 3D Tiles with GoogleMapsOverlay

### ISSUE THREAD

**Issue by fjacupar** [visgl/deck.gl#9125]
Hello all, 

I just wanted to know if it is possible to use a Tile3DLayer from Google Maps, Cesium or ArcGIS with or inside an Overlay like GoogleMapsOverlay for example, or is it better to use with Deck standalone like the normal way.

Thanks in advance.

_Originally posted by @fjacupar in https://github.com/visgl/deck.gl/discussions/9112_

**Comment by ibgreen** [comment]
@fjacupar As long as using deck.gl, you should be able to use the Tile3DLayer with the datasources you mention.

However, when working with 3D data and basemaps you face the added complication of ensuring that elevations match between your data and the basemaps, and in general I would expect there to be issues.

**Comment by ibgreen** [comment]
Please use discussions tab for further inquiries, issues are for verified bugs only
