### ISSUE TITLE
[Bug] Disabling the cache for TileLayers

### ISSUE THREAD

**Issue by sraimund** [visgl/deck.gl#9155]
### Description

It's not possible to set maxCacheSize or maxCacheByteSize to 0 to disable the cache for TileLayers. 

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

The nullish coalescing operator ?? can be used instead of || to allow zeros but disallow null/undefined values:  
https://github.com/visgl/deck.gl/blob/c20af822935a8acbe1d2998cb5b22fb14840fcb8/modules/geo-layers/src/tileset-2d/tileset-2d.ts#L471C1-L475C64

### Environment

Framework version: deck.gl@9.0.29

**Comment by ibgreen** [comment]
@sraimund Thanks for reporting. Since you seem to have a very localized change in mind that should be easy for maintainers to approve, would you consider making a PR for the fix?

@belom88
