### ISSUE TITLE
[Doc] colorAggregation does not determine the elevation value

### ISSUE THREAD

**Issue by clo-vis** [visgl/deck.gl#9177]
### Link

https://deck.gl/docs/api-reference/aggregation-layers/hexagon-layer

### Description

Documentation for colorAggregation:
getColorWeight and colorAggregation together determine the **elevation** value of each bin. If the getColorValue prop is supplied, they will be ignored.

Documentation for elevationAggregation:
getElevationWeight and elevationAggregation together determine the **elevation** value of each bin. If the getElevationValue prop is supplied, they will be ignored.

**Comment by Pessimistress** [comment]
This is fixed on the master branch and will land in 9.1.
