### ISSUE TITLE
[Doc] Examples for getColorValue and getElevantionValue cannot be compiled

### ISSUE THREAD

**Issue by clo-vis** [visgl/deck.gl#9179]
### Link

https://deck.gl/docs/api-reference/aggregation-layers/hexagon-layer

### Description

For example, for 
`getColorValue: (points: BikeRack[]) => points.length`
the error is:

> Type '(points: BikeRack[]) => number' is not assignable to type 'AggregateAccessor< BikeRack >'.

(
As a side note, the example with
points.reduce((sum: number, p: BikeRack) => sum **+=** p.SPACES, 0) / points.length
should use only + instead of +=
)

**Comment by Pessimistress** [comment]
This is fixed on the master branch and will land in 9.1.
