### ISSUE TITLE
[Bug] ReferenceError: VERSION is not defined

### ISSUE THREAD

**Issue by betovelandia** [visgl/deck.gl#9183]
### Description

Trying to run deck.gl on a React application using  Webpack v5.73.0 and I get the following error:

```
Uncaught (in promise) ReferenceError: VERSION is not defined
    at <static_initializer> (deck.js:99:14)
    at eval (deck.js:45:1)
    at ./node_modules/@deck.gl/core/dist/lib/deck.js (index.bundle.js:22555:1)
    at __webpack_require__ (index.bundle.js:29014:42)
    at eval (deckgl.js:6:71)
    at ./node_modules/@deck.gl/react/dist/deckgl.js (index.bundle.js:23215:1)
    at __webpack_require__ (index.bundle.js:29014:42)
    at eval (DeckGLMap.tsx:7:72)
    at ./src/containers/Map/DeckGLMap/DeckGLMap.tsx (index.bundle.js:3111:1)
    at __webpack_require__ (index.bundle.js:29014:42)
  ```

All I'm trying to run is passing this to a parent component for rendering:

```typescript
import React from 'react';
import DeckGL from '@deck.gl/react';
import { MapViewState } from '@deck.gl/core';

const INITIAL_VIEW_STATE: MapViewState = {
  longitude: -122.41669,
  latitude: 37.7853,
  zoom: 13
};

const DeckGLMap = () => <DeckGL initialViewState={INITIAL_VIEW_STATE} />;

export default DeckGLMap;
```

Which points [here](https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/deck.ts#L295) as it fails to find and / or execute this [method](https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/init.ts#L32) correctly.

I am following the documentation, not sure if this is a bug or something missing in the docs, has anyone else seen this error?

Thanks

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

`<DeckGL />` component rendered correctly

### Steps to Reproduce

While running webpack 

### Environment

- Framework version:  9.0.3
- Browser: Chrome
- OS: Mac

**Comment by Pessimistress** [comment]
> ### Steps to Reproduce
> While running webpack

Please provide a full repo setup that reproduces your issue.

**Comment by betovelandia** [comment]
Thanks, repo has been attached,  `yarn start` will get you started.

[sandbox.zip](https://github.com/user-attachments/files/17156069/sandbox.zip)

**Comment by Pessimistress** [comment]
Thanks. The issue is in this block:

https://github.com/visgl/deck.gl/blob/0b8fdd8b6b97cad5b69be21cb45e641bf0335a66/modules/core/src/lib/deck.ts#L291-L295

Which gets compiled by TypeScript to:

```js
export default class Deck {
    static { this.defaultProps = defaultProps; }
    // This is used to defeat tree shaking of init.js
    // https://github.com/visgl/deck.gl/issues/3213
    static { this.VERSION = VERSION; }
```

Webpack has [a bug in resolving static initialization blocks](https://github.com/webpack/webpack/issues/16054) which was [fixed in 5.74.0](https://github.com/webpack/webpack/pull/16065). Your easiest fix is to just upgrade Webpack.

@ibgreen Static initialization blocks are only emitted with `target: "ES2022"`. It maybe to aggressive?

**Comment by ibgreen** [comment]
> Static initialization blocks are only emitted with target: "ES2022". It maybe to aggressive?

Huh, yes, this is a bit of a surprise. We want to support modern input syntax and reasonably modern output syntax but we don't necessarily want to emit hyper modern syntax in our transpilation output. I didn't realize this was happening, normally transpilation converts modern syntax to older syntax, this is the first time I have seen the emitted code being upconverted into more modern javascript than we are using in the source)

**Comment by betovelandia** [comment]
Thank you for the feedback @Pessimistress upgrading

**Comment by betovelandia** [comment]
That's the issue, this is code I can not share sue to my company's policy,
