### ISSUE TITLE
[Bug] PickMultipleObjects Returning the Same Objects Repeated With MVT Layer

### ISSUE THREAD

**Issue by aemonm** [visgl/deck.gl#9228]
### Description

Using `pickMultipleObjects` is returning the same objects duplicated up to the limit specified by `depth` in the MVT Layer.

[See this pen](https://codepen.io/acdanger/pen/YzmebXr) and observe the console output when clicking on objects in the map. 

In addition - and I haven't been able to repeat this in the provided codepen yet - in our production app, `pickMultipleObjects` is returning objects that are far from the coordinates specified by x and y. You can see this occurring [here](https://cerulean.skytruth.org/?zoom=2.49679&lat=-20.891155&lng=-56.344711&mpa=0&eez=1&iho=0&aoi=19) by clicking around  the Brazilian cost - notice sometimes results will be returned in the popup far from the clicked area.

### Flavors

- [X] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Only one copy of each object should be returned when using `pickMultipleObjects`.

### Steps to Reproduce

See https://codepen.io/acdanger/pen/YzmebXr

### Environment

- Framework version: ~9.0.0
- Browser: Chrome
- OS: macOS

**Comment by donmccurdy** [comment]
Proposed fix:

- https://github.com/visgl/deck.gl/pull/9246
