### ISSUE TITLE
[Bug] Templates in WMS Experimental

### ISSUE THREAD

**Issue by ccreed1988** [visgl/deck.gl#9257]
### Description

Hello,

I know the WMS Experimental library is still being worked on (hence "experimental"). I am just wondering if anyone else has encountered the same issue I have - just to verify that something is broken (or not yet working)

It seems like using serviceType: "template" does not actually fill in values for a given template (for creating the URL to get the map images).

Can anyone else verify this? Or is it just something that we are doing incorrectly on our end?

Thanks!

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expect the serviceType: "template" to fill in values for the template URL

### Steps to Reproduce

When I try to send a template string to the WMS Experimental layer - it does not fill in the template and instead leaves the placeholder values in the string.

### Environment

- Framework version: 9.0.35
- Browser: Opera
- OS: Windows 10

**Comment by ibgreen** [comment]
@ccreed1988 Thanks for reaching out. 

Unfortunately, it is a bit of a mess as I actually don't recall what actually worked and when, but it may have been working and broken during one of the refactors, maybe WMS1.3 or DataSource refactors, as those refactors got much more complicated than expected.  Meaning that it may also depend on the loaders.gl version you are using.

I think templates would be quite useful though at the moment not 100% up to date on what the best API to specify them would be. For now, perhaps you might be able to subclass the WMSSource and control things that way.

**Comment by ccreed1988** [comment]
Thanks for confirming our suspicions. I think for us we are going to try another way to accomplish what we want without templates. But thanks for your time!

Follow up question though - how is progress going with the WMS Experimental layer? Any timeline on when it will be off "experimental status"?

**Comment by ibgreen** [comment]
>  Any timeline on when it will be off "experimental status"?

It is pretty established by now. The main issue is that this was one of the first `Sources` and the general DataSource API has evolved as more sources were added. 

There is another `DataSource` refactor coming in v4.4 that will hopefully have minimal impact and things should stabilize after that and it might be a good time to remove the label.

**Comment by ccreed1988** [comment]
So once that happens would the templating be fixed?

**Comment by ibgreen** [comment]
No sorry, I don't think that anyone is looking at WMS templating right now. Do you have a non-standard server?

**Comment by ccreed1988** [comment]
We don't have a non-standard server but we wanted to do things that weren't supported yet - like transparency and nearmaps.

Thanks for your time though - we actually ended up finding another way to do things (still using deck.gl). This was very informative. I think you can maybe close the issue - unless you think it should remain open so that templating gets addressed someday.

Thanks!
