### ISSUE TITLE
[Bug] Error installing deckgl with Next 15 and React 19

### ISSUE THREAD

**Issue by dgarciap** [visgl/deck.gl#9268]
### Description

I'm trying to npm install deck.gl with next 15 and React 19.
But I'm getting an error:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: deck.gl@9.0.36
npm ERR! Found: react@19.0.0-rc-66855b96-20241106
npm ERR! node_modules/react
npm ERR!   peer react@">=16.3.0" from @deck.gl/react@9.0.36
npm ERR!   node_modules/deck.gl/node_modules/@deck.gl/react
npm ERR!     @deck.gl/react@"9.0.36" from deck.gl@9.0.36
npm ERR!     node_modules/deck.gl
npm ERR!       deck.gl@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@">=16.3.0" from deck.gl@9.0.36
npm ERR! node_modules/deck.gl
npm ERR!   deck.gl@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.3.1
npm ERR! node_modules/react
npm ERR!   peerOptional react@">=16.3.0" from deck.gl@9.0.36
npm ERR!   node_modules/deck.gl
npm ERR!     deck.gl@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I tried installing the last beta version ```npm install deck.gl@9.1.0-beta.1 --save``` but still, I get the same error.

I guess that deck.gl is not compatible with React 19 yet?

Thank you,
David

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

npx create-next-app@latest
npm install deck.gl --save

### Environment

- Framework version: deck.gl@9.0.36
- Browser: Chrome
- OS: MacOS

**Comment by Pessimistress** [comment]
Your React version "19.0.0-rc-*" does not satisfy `>=16.3.0` because it is not a production release. We cannot promise to support every beta release of React. You can use [override](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) locally if you want to use React beta.
