### ISSUE TITLE
[Bug] Double-height React component with unwanted scrollbar

### ISSUE THREAD

**Issue by pwellner** [visgl/deck.gl#9290]
### Description

Placing a Map component  within a DeckGL component  creates a double-height view with large blank area below the map, and no way that I can find to remove the scroll-bar.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Expected a simple map that fills the screen without a scroll-bar.

### Steps to Reproduce

```bash
$ npx create-vite@latest -t react-ts
$  cd <project-name>
$ npm install --save @deck.gl/react react-map-gl maplibre-gl
```

Run the following `App.tsx`
```tsx
import DeckGL from '@deck.gl/react';
import { MapViewState } from '@deck.gl/core';
import { Map } from 'react-map-gl/maplibre';

const INITIAL_VIEW_STATE: MapViewState = {
  longitude: -122.41669,
  latitude: 37.7853,
  zoom: 13
};

export default function App() {
  return (
    <DeckGL
      initialViewState={INITIAL_VIEW_STATE}
      controller
    >
      <Map mapStyle="https://basemaps.cartocdn.com/gl/positron-gl-style/style.json" />
    </DeckGL>
  );
}
```

### Environment

- Framework version: `deck.gl/react 9.0.37`
- Browser: `Chrome`
- OS: `Linux` and `iOS`

**Comment by Pessimistress** [comment]
You are not including the maplibre stylesheet: https://visgl.github.io/react-map-gl/docs/get-started#styling

Please use react-map-gl Discussions if you have any further questions.

**Comment by pwellner** [comment]
Thank you @Pessimistress!  Adding the following line fixes the issue:

```tsx
import 'maplibre-gl/dist/maplibre-gl.css';
```
